### ISSUE TITLE
Reimburse fees lost due to timeouts

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#1]

**Comment by sneurlax** [comment]
Why?

And more fundamentally?

How?

If Bisq has funds, those funds should go to development.  We

**Comment by sneurlax** [comment]
Why?

And more fundamentally:

How?

But anyways, regardless of the question of where Bisq funds would come from (or how to spend them,) if the maker and the taker are OK with keeping the terms of their original agreement, achieving the terms of contract.json on a longer timetable is still a good outcome, all things considered.  Things required a bit of troubleshooting, but that's essentially support for free!

As a user, getting reimbursed for mining fees would feel like a luxury. I wouldn't be displeased at all.  But... why?

**Comment by cbeams** [comment]
@sneurlax, the timeout errors that traders have been experiencing are essentially due to a bug in Bisq, starting with v0.6.1. As such, we consider it our responsibility to reimburse the traders who are suffering from that bug (there have been about 30 such cases total). These users entered into their trades with the reasonable expectation that their fees would be put to productive use, and a bug in Bisq prevented that. There are two fees involved in each of these cases: the first is Bisq's own trading fee, which is routed to arbitrators. The second is the normal Bitcoin mining fee. We (the @bisq-network/arbitrators) are reimbursing both of these fees out of our own funds. The reimbursements will be issued as one or more batch transactions based on the contents of `support-1.csv` which you can find in the root of this repository.

**Comment by cbeams** [comment]
The first batch transaction of reimbursements has been broadcast. From https://tradeblock.com/bitcoin/tx/9aa7f26d5b39301a0add1b627bb8e8cd961fb8d16c9777a3342ad160c6cf1ebf:

![image](https://user-images.githubusercontent.com/301810/35068951-f6704ebe-fbd8-11e7-8a05-ec662bc48996.png)

The set of addresses and amounts was produced by running the following command against `support-1.csv` in the root of this repository at commit e76f8030a92669d7be7eab6c57cdbc0664c8c14d:

```
$ awk -F, '{print $3 "," $4+$5}' support-1.csv  | grep -v address > reimbursements.csv
```

This prints out the address to reimburse (3rd field), then the sum of the trading fee (4th field) and minining fee (5th field), eliminating the first line of the file which consists of headers.

The resulting CSV file was then fed into Electrum in the `Send` screen after selecting the `Tools->Pay to many` menu option.

Per the screenshot below, 5 reimbursements are still `Waiting for info`. It will be important to process them in a way that does not result in double-reimbursement. Should probably create a new file for them as the info comes in, e.g. `support-1a.csv` or something similar.

![image](https://user-images.githubusercontent.com/301810/35069300-0f429388-fbda-11e7-87c1-767c6caee10f.png)

Note that I went as low as possible on the fee in Electrum, which was still quite high at 418 sat/byte. This was also broadcast as an RBF transaction, in case we need it.

**Comment by cbeams** [comment]
I will wait for the transaction above to confirm, and will then comment on and close all affected reimbursement issues.

**Comment by cbeams** [comment]
Closing as complete.

The batch reimbursement transaction at https://tradeblock.com/bitcoin/tx/9aa7f26d5b39301a0add1b627bb8e8cd961fb8d16c9777a3342ad160c6cf1ebf has been confirmed.

I'll now close all individual reimbursement issues associated with this epic as well.

Any reimbursements still waiting for information will be processed in the next batch transaction, which will be managed in a new, separate epic.
