### ISSUE TITLE
Fee reimbursement for trade fnvWsLY

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#100]
This trade failed due to the issue documented at https://github.com/bisq-network/support/issues/86.

Lost maker and taker transaction fees (both mining and trading) will be reimbursed in the next batch transaction at #76.

Please subscribe to this issue for status updates.

![image](https://user-images.githubusercontent.com/301810/38772080-a937495a-402e-11e8-8d47-ab336f8d24b0.png)

Maker: 6a132a045300456ea94f0e98cad925a63eee5f68ecf43a164d96dd06a882f5ac
Taker: 496cc918ae1cdfbfff698244a6f79ebd629c5a7e741bc61c7d7c5136b27f811f 
Deposit: [was not broadcast; the value above is incorrect]

**Comment by jenechka1** [comment]
Hello. Two questions:

1) When should I expect the reimbursement to take place?
2) What about the trade itself? I, for one, would like the trade to take place still. Is there a way to restore the trade to the point where it goes through on the same terms as before?

**Comment by cbeams** [comment]
> When should I expect the reimbursement to take place?

Soon, I'm working on it now.

> What about the trade itself? I, for one, would like the trade to take place still. Is there a way to restore the trade to the point where it goes through on the same terms as before?

The trade has failed and has been closed. There is no way to continue. You'll need to make or take a new offer.

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/76#issuecomment-382711677.

**Comment by jenechka1** [comment]
Hello. Sorry to be reopening this, but while I did receive the refund of the maker and tx fees, shouldn't I also have received the 0.01 BTC that was reserved while the offer was outstanding?

**Comment by cbeams** [comment]
@jenechka1, the 0.01 BTC never left your wallet, because the deposit transaction was never broadcast. If you show the 0.01 as still being locked, then you need to resync your SPV file. You should just do this anyway for good measure after a failed trade like this. It can (and often does) leave your wallet in an inconsistent state. `Settings->Network info->Resync SPV file` should solve it.
