### ISSUE TITLE
Fee reimbursement for trade 00450

### ISSUE THREAD

**Issue by hinomomo** [bisq-network/support#1000]
![image](https://user-images.githubusercontent.com/90356969/132592389-2e142c43-2cfe-4d1d-9442-51d75bb22eda.png)

Maker: f044ddecbf8fb191229fe97f9b56e58e389887e9cad227a33f4aa419f29b9777
Taker: N/A
Deposit: N/A

Bisq version: v1.7.3
BTC address for reimbursement: bc1qxh8amk63l8wp753qqt4epqjtxhgqr82f8q3yj2

Other notes:

Error message: An error occurred at task: TakerSendInputsForDepositTxRequest
Exception: java.lang.NullPointerException

The trade is located in the "Failed" folder. Please reimburse fees. Thanks!

**Comment by pazza83** [comment]
Hi @hinomomo thanks for posting.

As you were the taker for this trade and no taker fee is present no funds will have left your wallet. There is no reimbursement required.

**Comment by MwithM** [comment]
Bisq lost 0.008 BTC from this failed trade. :(

**Comment by pazza83** [comment]
> Bisq lost 0.008 BTC from this failed trade. :(

Is it not just the maker fees that will be refunded (and these where paid with 22.90 BSQ).

There is no taker fee to refund as no transaction took place.

**Comment by MwithM** [comment]
Bisq experimented a cost of oportunity 0.008BTC from this failed trade as trading fees (0.4% of 2BTC). To that, we have to add the cost of unsatisfied users stopping the trading and not recommending Bisq.

**Comment by pazza83** [comment]
> Bisq experimented a cost of oportunity 0.008BTC from this failed trade as trading fees (0.4% of 2BTC). To that, we have to add the cost of unsatisfied users stopping the trading and not recommending Bisq.

Thanks for explaining. Agree it is not good. Are most of these wallet issues to do with the limitations of bitcoinj?
