### ISSUE TITLE
Fee reimbursement for trade EUFNJAZ

### ISSUE THREAD

**Issue by tatitas1983** [bisq-network/support#1002]
![Captura de pantalla de 2021-09-14 19-35-31](https://user-images.githubusercontent.com/90650051/133614160-9ad47f0c-824b-40bd-9b39-87904bbe8c0f.png)

Maker: e62954f9342c3c93b94b8da3591c9537a4cafbc1471805a9e9ee380755ef7160
Taker: N/A
Deposit: N/A

Bisq version: 1.7.3
BTC address for reimbursement: bc1qmj8xzld57rz9kq7hzrnky08l6jnfgsdmhpdlj6

Other notes:
An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=427009578
makersPrice=433808878

**Comment by pazza83** [comment]
@tatitas1983 

Thanks for posting.

@leo816 I am assuming when a trade fails like this because the maker tx id is ok the trade will still be avilable for another user to take? Therefore, there is no loss of funds?

**Comment by jmacxx** [comment]
Yes the maker's offer does remain open and available to trade.

**Comment by tatitas1983** [comment]
Thanks, @jmacxx and @ pazza83 I am going to activate the offer, I hope this will be resolved.
