### ISSUE TITLE
Fee reimbursement for trade RFfNCRn

### ISSUE THREAD

**Issue by monkfruit** [bisq-network/support#1003]
![Screen Shot 2021-09-16 at 21 26 38](https://user-images.githubusercontent.com/76693667/133715241-c8601237-2b3f-4826-814d-e3d7c5d4cae1.png)

Maker:  21cba0a5d6d82d8db1f1dadd8e3eedcd23771702073db449cef7dc0953e40f9e
Taker: 699d6ea2751ef77b21f4ca0483e29ecf4d15fbf3edbfa90793a6af3308ee04be
Deposit: N/A

Bisq version: 1.7.2
BTC address for reimbursement:  bc1qklw3xglw7wjctcd3j7qmrnqru7cstg4rfx6veh

**Comment by pazza83** [comment]
Thanks for posting. I can see this is a failed trade and you lost your maker fee and miner fee. 

@leo816 will arrange reimbursement.

**Comment by leo816** [comment]
Reimbursed with #1006
