### ISSUE TITLE
Fee reimbursement for trade 29502033

### ISSUE THREAD

**Issue by Crazyrph** [bisq-network/support#1005]
Hello - I am new to Bisq. I accepted a trade and was waiting for blockchain confirmation and the power went out on my laptop and my Tails session was lost. Therefore, the open trades screen does not reflect the trade and is empty. The only information I can provide is the Bisq trade ID, who I sent it to and details about the trade. My main quesiton is how can I get the trade to appear in Bisq again so I can complete it? If this is not possible can any reimbursement be made or can you complete the trade for me somehow? The BTC was confirmed now on the blockchain. I have attached a screen shot below where the 2nd trade listed is mine. 

Bisq trade ID: 29502033
To: bc1qvyqj5nwk2nptv3hr8n2nwa9jd5e3x5e3x5lzfsgg3c
Makers onion is: d3rivfps5fdzwkkwnazlfeefl4plc637paowf7q42atzrapfehwjkwid.onion:9999
Blockchain Trans ID: b5b2f4f3d6dd6a72f623da26c8215464416db9251ee8b140e4bad9231159b7b1
Date 9/19/2021
Time 21:06 
Amount of btc: 0.0016199
Block 701334
My onion: omwliu4x3kyylrk2lj3nlbioq4ys5oi2bdu7lsaq7sgwepbvoyxle7yd.onion:9999

![image](https://user-images.githubusercontent.com/91039583/133951651-4486c50d-1ba6-4742-a110-da1f8c1cbc0e.png)

Thanks for your help.

**Comment by Crazyrph** [comment]
In doing more research. I think I cannot see the trade in the portfolio because my onion address changed. How can I determine the correct address and restore it?

**Comment by pazza83** [comment]
Hi @Crazyrph thanks for the message.

Sorry to hear your laptop powered off and lost data.

I am the mediator for your ticket. Please can you send me a message in Keybase so I can assist you in completing this trade.

My username on Keybase is: pazza

**Comment by pazza83** [comment]
Hi @Crazyrph 

Thanks for providing me with the info needed in Keybase.

Manual payout has been made and this trade has now been completed.

Will close this issue.
