### ISSUE TITLE
Fee reimbursement for trade 9186044

### ISSUE THREAD

**Issue by userbisq** [bisq-network/support#1007]
![image](https://user-images.githubusercontent.com/69260167/134394373-10979342-03c6-4cbb-9f2c-3c6fde6f64cb.png)

Maker:  f212e8bf614db398ff65ddc87147bc45e67750530acbc04c5f749e914c1c0b2a
Taker: 29b2d498971fd06b21417e7f2ad588dd96982388174a1b189b0231ba5ac047e3
Deposit: 3bc65ac1a3987e76b29183c63d2f82a7b2e0dc31c78d3b530cedd79f387c350b

Bisq version: 1.7.3 
BTC address for reimbursement: 12fadrTBFckfYgx2VnHwcWkNNeR3Lg3nvy

**Comment by pazza83** [comment]
Hi @userbisq thanks for posting,

This trade has funds still locked in the multisig: https://mempool.space/address/bc1qnfcry7e4cq296u90zp7f8ctxkzvp6usxp5t66wuwvz3vu2ad329sad39kg

I would recommend opening mediation if you have not already done son.

You can do this by selecting the trade and clicking: 'Ctrl + o' or 'alt + o' or 'cmd + o'

Once you have opened mediation you will be able to communicate with the mediator to get this issue resolved.

**Comment by userbisq** [comment]
Hi @pazza83.
I'll do it 
Thank you.
