### ISSUE TITLE
Reimbursement for KEEYMAWU

### ISSUE THREAD

**Issue by anonqoder** [bisq-network/support#1008]
<img width="898" alt="reimbursment" src="https://user-images.githubusercontent.com/76815541/134726398-87e425e3-c773-44c9-abac-05d5c167145b.png">

Maker:  7d69646631a0a57ed4e300762072dbf0ea8c89bca7f5fde1a5db9cb2cf022bfa
Taker: d07a75837ea3cfcc14d1a585cd6e67ccb41039141f627fe70976017feed2a2d9
Deposit: 741acc017ac444448463c7fa81662e8e5e3bff67472516d6906354c0f59ac22d

Bisq version: v1.7.3
BTC address for reimbursement: bc1q86zlngje0fkxss0knk87pydncqfn3vssqk9r22

**Comment by leo816** [comment]
Payout made with #1028
