### ISSUE TITLE
Fee reimbursement for trade RPYSYF

### ISSUE THREAD

**Issue by jeforson** [bisq-network/support#1010]
![image](https://user-images.githubusercontent.com/52366428/136698753-1fac2667-86ac-4fe0-91e3-5c7fc956ee27.png)

Maker:  f0dd54afcfad5cf3e626a25f2a8400c3383db6f65a8b7017612bfd6d7e075967
Taker: 4708e96e2ffb9a5e5961da8d46cd39ae03d4ce206c24dc6f5e24cf196d423526
Deposit: 8155ba0a195c384aa7c22e8a595db10b6145e0b5b7e8e5b08178e32f2691236a

Bisq version: 1.7.4
BTC address for reimbursement: bc1qxq8ju5hapzt3t946yuxf5hctf7khj66eumyf94

Other notes: Lost maker and miner fees

**Comment by leo816** [comment]
Payout made with #1028
