### ISSUE TITLE
Fee reimbursement for trade 8hqzF

### ISSUE THREAD

**Issue by pfergi42** [bisq-network/support#1016]
![bisq_error](https://user-images.githubusercontent.com/4021240/139538635-07fad107-cc6d-40ad-81e7-1755ebeac6fd.png)

![bisq_error2](https://user-images.githubusercontent.com/4021240/139538445-aab651ac-9ab7-4fca-abdd-861ffd31bb87.png)

Maker:  c5bbc0e1e9d380e5df22cfa888e65d5e22bbed0898601849983cd41cb5efa30b
Taker: N/A
Deposit: N/A

Bisq version: v.1.7.4
BTC address for reimbursement: bc1qkmcnz98lcw9qx0dk04m3lt6pfgfjrj7c0z8fy5

Other notes:

**Comment by pazza83** [comment]
Hi @pfergi42 thanks for posting. I can see you have lost miner and maker fees on this trade.

@leo816 with arrange compensation in the next reimbursement cycle.

**Comment by pfergi42** [comment]
When does the next reimbursement cycle occur?

**Comment by leo816** [comment]
Payout made with #1028
