### ISSUE TITLE
Fee reimbursement for trade 93203

### ISSUE THREAD

**Issue by waleehoohaa** [bisq-network/support#1017]
![attention](https://user-images.githubusercontent.com/93359441/139579008-590d6b51-2a43-4e39-9d55-6d45c67f9e8b.png)

![93203](https://user-images.githubusercontent.com/93359441/139578718-2c17dfaa-903a-49ba-9f95-2ceacde61eb7.jpg)

Maker: 3f1e26b3b080c3a3c9e394c492bf29cd7452ee88defc6faebcd2ffc85585f9b9
Taker: 83ab87a465a9709c84482d27671e96fe48313d807c4e62d1fdd86a5f4b9e40ce

Bisq version: 1.7.5
BTC address for reimbursement: bc1q0p96wvdn7nkg03fyuuk86cw0sn2yspe9jecjqz

Other notes: Trade failed because deposit transaction is missing. I recently upgraded to v1.7.5 after another recent failed trade. Please reimburse the trade/mining fees to the above address. Thank you.

**Comment by leo816** [comment]
Payout made with #1028
