### ISSUE TITLE
Fee reimbursement for trade XQGON

### ISSUE THREAD

**Issue by fmorenof** [bisq-network/support#1019]
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/67203480/140428960-66bec851-9d2b-4277-a008-d465b89370eb.png)
![MediationResult](https://user-images.githubusercontent.com/67203480/140429111-a5041c57-b859-4958-aa7b-ac2575254dd0.PNG)
![image](https://user-images.githubusercontent.com/67203480/140429129-6ab37d2f-0f4c-49f4-8fa7-263f48efb7e3.png)

![image](https://user-images.githubusercontent.com/67203480/140429620-0c181907-2f6e-4d82-b0be-57b35c774627.png)

Maker:  113362b579a6d5cd24f50713fa59575d59f8202f5fd6faac8ac94c17de7110a5
Taker: 744826b7b7b5d9705ca94a0590aaf3d964a4290e4e4bd7c8e57e72991e56787e
Deposit: 32f9c948737f427c0ae624023b13720a7b1ed706eff942790bcb49bedde3adfd

Bisq version: 1.7.3
BTC address for reimbursement: bc1qryqe62kxxdj4cjf8326q4xrtmwn4et42uy0sh3

Other notes:

**Comment by pazza83** [comment]
Hi @fmorenof 

Thanks for opening this.

As your mediator I can confirm I asked you to open this ticket for reimbursement of your trade and miner fees.

@leo816 will make reimbursement in his next cycle.

**Comment by leo816** [comment]
Payout made with #1028
