### ISSUE TITLE
Fee reimbursement for trade XQGON

### ISSUE THREAD

**Issue by uncommon77** [bisq-network/support#1020]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/93753612/140456741-7352493c-63dd-4f4b-bdda-898f79d155f1.png)

![image](https://user-images.githubusercontent.com/93753612/140457559-81b88379-3a8b-408c-b99b-cc8b7b067b73.png)

![image](https://user-images.githubusercontent.com/93753612/140457154-e020a0f9-8572-4ab6-821d-38306d1dc330.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  113362b579a6d5cd24f50713fa59575d59f8202f5fd6faac8ac94c17de7110a5
Taker: 744826b7b7b5d9705ca94a0590aaf3d964a4290e4e4bd7c8e57e72991e56787e
Deposit: 32f9c948737f427c0ae624023b13720a7b1ed706eff942790bcb49bedde3adfd

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.7.4
BTC address for reimbursement: bc1qkalclazz77jejc9ftn2e93y8udprkwuuf8e0q2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Thank you!

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @uncommon77 

Thanks for opening this.

As your mediator I can confirm I asked you to open this ticket for reimbursement of your trade and miner fees.

@leo816 will make reimbursement in his next cycle.

**Comment by leo816** [comment]
Payout made with #1028
