### ISSUE TITLE
Fee reimbursement for trade 63195

### ISSUE THREAD

**Issue by polygonk** [bisq-network/support#1021]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
<img width="903" alt="image" src="https://user-images.githubusercontent.com/93849483/140797358-f986cfd4-7a87-4b53-8675-62597181b173.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  715add137578128b1482f9ca0614aa68e8fb866305dda4d773ed198b4d629918
Taker: 46f1990b00a9aea4e0616c2cac240529a16f13fd81407f234a294a2bfb52ab4c
Deposit: 6c0afb222b408ad0f9dffe978d3665c43dd11c041031510e87d57e4f14ca4e46
Delayed payout: 8d4c03217954db916e5c2d654555a84d77c60e0db3ff0a83be6bff3711ce7656

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.7.5
BTC address for reimbursement:
bc1qqw38aamhsel7h86whw60zu3gwynhc0k6gddaj4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Payout made with #1028
