### ISSUE TITLE
Fee reimbursement for trade gvrLX

### ISSUE THREAD

**Issue by klnit** [bisq-network/support#1022]
![grafik](https://user-images.githubusercontent.com/20220593/140809281-cca09e0b-ede0-41da-9e5d-4f1dd2f5d8a7.png)

Maker:  12768bc1000ad50230985f91279ecfb8df70a421105cd86c49a86c6fe9ee6058
Taker: c2724b0f2b919606b651dd390b68d54dd95495974e80de631ff46310c4fb4844
Deposit: 83d2754a87fb79abb2460a1ccc30897116c4d9012fbca9fa85f210a845571a2b

Deposit has been made

Bisq version: 1.7.5
BTC address for reimbursement: bc1q7jtdkwjdgp4sqy3eqz433c99yzq4w0dqx4mqp8

**Comment by klnit** [comment]
**ulqlduzo**
Now I have a second error and only with this trade partner
![grafik](https://user-images.githubusercontent.com/20220593/140997876-f3cf0625-f6ca-4047-a804-85619604f187.png)

Maker: ba02ef0145b8788571c6b39f6fd5e6460699f9e9d895c006700322a1f0d16433
ID of this trade partner: uhcbbymmw7jhqu6anvadqindm5fca6a5vgojikd6ljkswp3j2fc4m3id.onion:9999
I was able to quicky redirect the deposit to myself

**Comment by leo816** [comment]
Payout made with #1028

**Comment by klnit** [comment]
But what about that deposit made in the first buy. I cannot access it. I thought it might be a 2 of 3 musig or something to chargeback with you and me together!?!

**Comment by klnit** [comment]
My deposit tx: 83d2754a87fb79abb2460a1ccc30897116c4d9012fbca9fa85f210a845571a2b
Bisq locked it away for my buy intention with: c2724b0f2b919606b651dd390b68d54dd95495974e80de631ff46310c4fb4844
still sitting there
