### ISSUE TITLE
Fee reimbursement for trade iucpxqct

### ISSUE THREAD

**Issue by bitcoinerru** [bisq-network/support#1023]
<img width="1399" alt="Screenshot 2021-11-10 at 15 18 43" src="https://user-images.githubusercontent.com/94056829/141120274-ad73bb08-3703-4ca0-8bc5-d14d64d22efa.png">

iucpxqct-8857db65-df11-4704-b23d-81e35fdb800d-175

eab82fd75d67909811325b8a018ec8052aa8f5ca5a324099362def20022f5b7a

Using Mac OS.

**Comment by leo816** [comment]
taker fee is non existent, therefore reimbursement is not valid

**Comment by bitcoinerru** [comment]
But the Trade was completed and never got my deposit back?
