### ISSUE TITLE
Fee reimbursement for trade 2308136

### ISSUE THREAD

**Issue by 23Yc8z** [bisq-network/support#1025]
![Bisq trade 2308136 screenshot](https://user-images.githubusercontent.com/57015173/141345530-a6395b01-5821-49b0-abea-fd4200d88693.jpg)

Maker:  4c666d9a5bcbc511ab46e66d1b30a63abb30f01054cadff4eca74f4a92e28ca6
Taker: a5f07ed20ab38b6ea29c9380258c2e3773af394a0041c74e05829204499f71e6
Deposit: 7d7ef39914c034d42388e1eccfde5d9104447c7158a778a08e73fbdd11891b5c

Bisq version: 1.7.5
BTC address for reimbursement: 1PjZK1Yi9QmmRHQMRMkp4gYGwZ5HPRsXgr

Other notes:

"The deposit transaction (the 2-of-2 multisig transaction) is missing" error.
"The deposit transaction is null. You can move the trade to failed trades" error.

Please reimburse fees.

The trade was A YEAR AGO, and issue persists.

At the time of the trade, both seller and buyer had version 1.5.1.
I (the seller) have today installed version 1.7.5, and I have made a "resync" today.

I already opened issue in https://github.com/bisq-network/support/issues/772 ...

**Comment by pazza83** [comment]
Hi @leo816 please can you add reimbursement of this trade to your to do list.

@23Yc8z opened their first request in Jan 2021.

**Comment by 23Yc8z** [comment]
> Hi @leo816 please can you add reimbursement of this trade to your to do list.
> 
> @23Yc8z opened their first request in Jan 2021.

Thank you !!

**Comment by leo816** [comment]
Payout made with #1028

**Comment by 23Yc8z** [comment]
Hi, I have received the Bisq fee. Thank you.

But, on the top right corner, the "Locked" amount of the the trade is still "locked", showing and amount that is the sum of the "BTC amount to spend" and the "security deposit" of the maker (me)...

**Comment by leo816** [comment]
Did you try to do a SPV Resync?

**Comment by 23Yc8z** [comment]
> Did you try to do a SPV Resync?

Yes. I have just resynced, and the "Locked" amount still appears...

**Comment by pazza83** [comment]
This is a known issue.

GUI displays incorrectly once a trade has failed

There has been a fix published: Fix calculation & display of Locked Funds https://github.com/bisq-network/bisq/pull/5813

Should correct itself in the next release of Bisq 1.8.0
