### ISSUE TITLE
Reimbursement for trade cjtlq-550943f1-9702-4b7b-a480-31d4d085e4b5-172

### ISSUE THREAD

**Issue by bisqu1465** [bisq-network/support#1027]
Arbitrator: @refund-agent2

In August I opened an offer to sell Bitcoin in exchange for EUR. My chosen payment method was SEPA. A buyer took my offer and claimed they sent the payment. The payment never arrived to my bank account, but the buyer claims they sent it.

After the time expires I open a mediation ticket.

After 1 month of mediation, the mediator decides against me and in favor of the other party. The reason is still unclear to me, as I wasn't asked for any proof.

I obviously reject the decision of the mediator and ask for arbitration. And here I want to note that the arbitrator usually answered to my messages after a very long time (much more than the max 5 days advertised, sometimes even after more than 2 weeks) and after many pings the only way to make him contact me again was to make a Keybase account and write in the "support" chat.

Case stays with arbitrator for 2 more months and during this time I'm asked to provide a cryptographic signed proof of my bank statement first and then a video of me logging in to my bank account, showing the entire list of transfers sent and received in the month of August. I provided both proofs as requested. The arbitrator acknowledged that my proofs were valid and no transfer from the other party was displayed.

The other party keeps claiming that they sent the payment. The arbitrator confirmed I haven't received any transfer, but concludes the arbitration with this note:

```
Summary notes:
There is no payout possible at this time, as buyer and seller have provided sufficient proof to defend their cases. This is probably a banking isssue. 
Traders could reach an agreement after displaying each other their proofs.
This ticket can be reopened, or contact @refundagent2 at Keybase to keep in touch.
```

There are several problems with the claims above:

> This is probably a banking isssue. 

It is not and I'm astonished to read that. At the time the arbitrator asked me to ask the bank if there was a technical issue and I did, twice. They answered me both times that it's impossible for a transfer to be lost, in case it would come back. I referred this to the arbitrators, so I'm quite surprised and concerned that he decided to ignore the answers of the bank and used that wrong claim as the main reason to close the arbitration process. Did the arbitrator investigate at all if what he claim is the main issue is even technically possible, especially since my bank says it's not?

> Traders could reach an agreement after displaying each other their proofs.

We cannot. After arbitration was closed the chat disappeared, I cannot contact the other party anymore... but even if I could, why would I? If we contacted the arbitrator is because we couldn't reach an agreement. Beside, contacting the other party wouldn't bring any benefit at all, my funds are now stuck in Bisq, how could I reach an agreement with the other party if my funds are not under my control? This claim is illogical.

> This ticket can be reopened

No, it cannot be. There is no button to reopen the ticket and i cannot chat with the arbitrator anymore because the chat field disappeared after the arbitrator took the decision.

Now all the funds i provided for the trade are gone, even if I proved (twice) that i haven't received any transfer. The arbitrator keeps claiming that me and the other party are on the same page, that's why he voted for the neutral approach (where I lose everything). I tried to make him understand that would be stupid for me to attempt a scam when I risk the entire amount and would have been better for me to try to scam as the taker of the offer, so I would risk only the deposit, but apparently that summed with the fact that I initiated the trade and that I've been already trading on Bisq for a considerable time is not a reason strong enough, even if I proved I haven't received any money.

My feeling is that your arbitrator was gamed by the other party, which tried to scam me, and decided to side with no one, which for me is the same as siding with the other party, as i have lost my entire traded amount + deposit, when the other party only lost a small deposit.

Now, proofs aside, i tried to explain why would be very stupid for me to try to scam somebody as the creator of the offer when would be much safer to do it as the person who take the offer, but that failed. I now ask Bisq to please reconsider the decision and refund me of the entire amount.

**Comment by refund-agent2** [comment]
> After 1 month of mediation, the mediator decides against me and in favor of the other party. The reason is still unclear to me, as I wasn't asked for any proof.
> 
> I obviously reject the decision of the mediator and ask for arbitration. And here I want to note that the arbitrator usually answered to my messages after a very long time (much more than the max 5 days advertised, sometimes even after more than 2 weeks) and after many pings the only way to make him contact me again was to make a Keybase account and write in the "support" chat.

Hello.
The trade started on August 17th, mediation suggestion was delivered on 10th September and the arbitration ticket was opened September 11th. 
My first reply is the 13th September and I proceeded to ask mediator and buyer for proof of payment as  "Burden of proof comes from the buyer".
The 16th September I asked seller for pagesigned proof of all payments from 16AUG to 23AUG, as "buyer's proof is very solid". Seller replied quickly and 4 days later I asked how to open the file. At this time, to me, it was like there wasn't much more to do. This awful situation never happened before.

> My feeling is that your arbitrator was gamed by the other party, which tried to scam me, and decided to side with no one, which for me is the same as siding with the other party, as i have lost my entire traded amount + deposit, when the other party only lost a small deposit.

If buyer sent the amount and seller was the scammer, buyer would lose trade amount and security deposit and seller would lose the security deposit.
Given that I consider proof from both sides valid, [I can't make any payout](https://github.com/bisq-network/roles/issues/93#issuecomment-965778668).

**Comment by pazza83** [comment]
Hi @bisqu1465 

Thanks for posting.

Are you able to post the mediation summary? Please redact any personal info from it prior to posting?

It might also be useful to share your trade ID. Not sure if your mediator was leo816, huey735, or myself?

**Comment by bisqu1465** [comment]
@pazza83 the mediator was @huey735.

```
Ticket closed on Sep 10, 2021
Mediator node address: a56olqlmmpxrn5q34itq5g5tb5d3fg7vxekpbceq7xqvfl3cieocgsyd.onion:9999

Summary:
Trade ID: cjtlq
Currency: EUR
Trade amount: 0.0099 BTC
Payout amount for BTC buyer: 0.014350 BTC
Payout amount for BTC seller: 0.0005 BTC

Reason for dispute: Bank

Summary notes:
The BTC seller requested mediation and claimed that they hadn't received the payment for this trade. The BTC buyer shared video proof of the payment so I'll close the ticket in their favor reimbursing them for the time spent.

-----BEGIN SIGNATURE-----
302c02146600c19801643be04d741678281ac0dc51f6fc6c02142b4085a29bf3b009cdd6d9a38cd13b89f8d69a23
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator
```

**Comment by pazza83** [comment]
Hi @bisqu1465 

Was an SCT Inquiry done?

More info is in 4.4 on here: https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2020-04/EPC125-05%202019%20SCT%20Rulebook%20version%201.1.pdf

Normally an SCT Inquiry incurs a fee, however, once it is known whose bank is at fault then the trader at fault can be penalized accordingly.

**Comment by bisqu1465** [comment]
Hi @pazza83. I contacted my bank and they claim they cannot check a transfer done by another bank. I took a look at my contract to have an idea of the services they offer and i couldn't find anything about the procedure you suggest. This is confirmed by the document you posted:

> The assumption is that the Beneficiary will contact first the Originator, and that the Originator 
will launch a claim for non-receipt to the Originator Bank. The situation where the Beneficiary 
directly  addresses  a  claim  for  non-receipt  to  the  Beneficiary  Bank  is  not  described  in  the  
Scheme.

If i understood this correctly, my bank seems to be right. The sender should send the claim to his bank, not me, the beneficiary.

Anyway, this has been ongoing for too much and I'm tired of all this, when the only thing i did was to open an offer and wait. I also haven't heard from the other person since the arbitration was concluded. I'm asking for a reimbursement in Bisq.

**Comment by pazza83** [comment]
Hi @bisqu1465 thanks for letting me know.

Payments should not be able to disappear. Banks are rubbish but SEPA payments should be able to be verified.

@refund-agent2 did the Buyer in this case do any sort of SCT Inquiry / payment trace.

**Comment by refund-agent2** [comment]
> @refund-agent2 did the Buyer in this case do any sort of SCT Inquiry / payment trace.

No, I did not ask for it.

**Comment by bisqu1465** [comment]
> No, I did not ask for it.

Why did the arbitrator not investigate this possibility earlier? Why during 1 month of mediation and 2 months of arbitration, no one considered this option?
Why was i asked extensive personal and private information when the result of this request made by the other trader would have resolved the arbitration with 100% certainty?
Why a highly unlikely technical issue was blamed and used as the reason to keep my funds when the arbitrator didn't even do his due diligence to confirm it?

It's hard to think of this situation as not a result of incompetence of the Bisq team. I regret trusting this exchange with my money.

I was told on Keybase that now i have to wait likely 1-2 more months (to add to the 3 already gone) for unclear reasons. I hope this news will avoid that.

**Comment by BtcContributor** [comment]
My perspective on what happened as I followed this case on Keybase support channel.

I think @bisqu1465 should be refunded for the following reasons:

- From the amount of messages he sent he is obvious to me that he is honest
- I don't see any of this by the other peer that has also lost money
- SEPA bank issue like this one where a SEPA is not sent to another bank seems highly unlikely to me and should be proved with very solid reasons by the buyer
- refund-agent2 did not ask for a payment trace
- Refund amount is very low

I honestly think something went wrong on Arbitration process. This could happen but I think in these cases we should also use our gut feeling. And mine is saying that @bisqu1465 should be refunded :)

**Comment by pazza83** [comment]
Comments from Keybase user: hippydippy (posted on their behalf as no Github account)

> I'm new to Bisq (my first signed trade happily concluded this week) and I was checking the support channel for help with how to reduce data usage, when I saw this case. 
> 
> And I’m commenting as this situation is really alarming: SEPA trades are the highest volume trading method on Bisq and IMHO the current handling of this case represents flaw with SEPA as a Bisq payment method, and as a SEPA user, the outcome here doesn’t seem good enough and further intervention from the DAO seems necessary. 
> 
> Without seeing the proofs of each party, and from my outsider perspective, it seems likely that either A) the Buyer didn’t pay and duped the arbitrator, or B) Payment was lost between Buyer’s bank and Seller’s bank which, as previously pointed out, seems unlikely given the solidity of the SEPA system. However the SEPA document (linked by @pazza  in the Github link below) says "The cause for this claim can be at the Originator Bank, the Beneficiary Bank and/or in the clearing and settlement layer” which implies that transaction failure is indeed possible, if only extremely rare. For this reason it’s clear that for trades using SEPA the current arbitration procedure, regardless of the case in question, does not adequately cater for this possibility and needs transparent guidance to deter scummy scammers. 
> 
> I’d like to see the DAO make this situation right because, if: 
> 
> Scenario A) Buyer has not paid - this creates motivation for someone considering using Bisq for scamming, that they could simply not pay their SEPA, provide arbitrator with what must be doctored proofs, and be awarded the trade amount. Which is obviously a catastrophic situation for the integrity of the platform. 
> 
> Or if Scenario B) Bank lost payment - it’s clear the mediation / arbitration process has not adequately investigated the Seller’s assertion that they have not received payment by requesting the Buyer open an enquiry with their originator bank which, as defined by SEPA protocol in Pazza’s linked document, is the correct means of inquiry. 
> 
> I see comment above that "I don't think that with the info that the DAO has now it will be enough to accept your proposal” but this is nonsensical given Pazza’s doc. The SCT inquiry should have been requested, which is a failing of the process so the Seller has a case for compensation from the DAO if for no other reason than the arbitrator did not require Buyer to do this inquiry proof. Am assuming the DAO has no ability to request this proof now as the trade is closed and the Buyer has their BTC, in which case IMHO the Seller should be refunded at least half the trade. Probs 100% given all the hair-pulling they’ve endured.  
> 
> I also see a comment above that there has been "very little discussion about your issue” (presumably DAO discussion?) which seems negligent, and really concerning for me as SEPA user, as IMHO the integrity of the platform is the real issue here, beyond the trade in question. 
> 
> To preserve the integrity of Bisq, it seems essential that Bisq DAO establishes in the dispute resolution guidance for SEPA transaction disputes that this SCT inquiry, the actual method of enquiry defined by SEPA itself, be required as final resolution measure. As this will deter potential scammers who are emboldened by the current situation of this case - regardless of how the actual failing happened, a scammer sees this as a potential point of failure. As it stands, the fact that the proof wasn’t requested by the arbitrator is a disincentive to honest peeps using SEPA with Bisq. 
> 
> Pazza’s SEPA doc outlines how both banks must provide each other (the banks) with un altered transaction data relating to the inquiry, which is presumably data their customers have a legal right to access. Both Buyer and Seller should be required to provide whatever responses their banks provide to the arbitrator. No doubt different banks will communicate their response in different format / media but ideally the arbitrator, at their discretion, should be able to request disputing parties screen-share emails / internet banking login / or video call as necessary to review these comms. I can imagine a scenario doing all this over the phone with my bank results in me not actually having any response in writing, so it should be the responsibility of traders to request a response in writing from the bank. All SEPA banks must have at minimum a complaints email channel for customers to request written response. And, as a last resort, if trader is required to click around in their email / internet banking / phone texts, with the arbitrator watching in real time, well that’s pretty much impossible to fake. 
> 
> While this might all take a while (fuck the banks) it would provide arbitrator an accurate picture of what’s gone wrong with the trade. More importantly some public guidance from Bisq that this is how things will be resolved should deter scammers.  
> 
> If the bank communications establish that a payment is really lost and neither bank, nor clearing house, accepts liability for the loss, then the decision should probably be split equally between both parties as both traders are mutually accepting risk in using the SEPA payment method in the first instance. According to the SEPA doc one of the banks may charge the other bank a fee for SCT inquiry (fuck banks) and these kinds of fees should be split equally between both buyer and seller should they occur. 
> 
> The DAO should offer the Seller compensation here as, IMHO, the Seller is right - the arbitration process in this case does not see to have been sufficiently fair to them. Their arbitrator should have seen that further action was required and not just left the Seller hanging, empty handed. And in my experience with different banking methods is that if TFR’s are mischanneld they eventually bounce back to the sender, so in light of the SCT inquiry not yet being established as common practice, at least transparently for users, the Seller should really get a full refund. 
> 
> I’m probably going to hold off on further SEPA trades until the DAO makes a decision here. How does someone follow along this decision are they published somewhere? @bisquser1465  can you reply here with the outcome, please? Also don’t shoot the messenger brah but people might be more inclined to help you without all the swear words and put-downs. Just saying. Good luck!

**Comment by djesys** [comment]
Hi! I am the buyer, and I only respond now because I was not aware of this thread. 
I will not even start to defend allegations that I "teamed up" or anything alike as I showed  sufficient proof  about the payment. From my end, this trade went wrong either because either 

1. the seller is a scammer
2. there was a technical problem
3. the payment was flagged for some reason and is in some backlog for further analysis by banks / authorities

Besides proof of payment, I hold a statement from my bank saying that their investigation lead to nothing
due to the lack of cooperation from the receiver´s bank.
I even called the seller´s bank, obviously without any outcome as they understandably don´t give out information about their clients to strangers.

The arbitrator holds all of these proofs, even a recording of this call.

I have high confidence in the integrity of the DAO, and therefore simply accepted their decision.
BISQ is experimental, and if 1% of transactions "fail", it´s part of my risk management.
Thankfully, the amount was not high.

If there is anything I would like to see now, it´s a 50/50 refund to both parties plus the honesty of the seller
to notify if funds ever arrive at his account.

Actually, I assumed that these cases happen more often, and I was actually quite surprised to see this amount of discussion about the issue.

That said, I am available and happy to cooperate in any necessary way.
best to the project !

**Comment by lostsock1** [comment]
Hi! I am the buyer, and I only respond now because I was not aware of this thread.
I will not even start to defend allegations that I "teamed up" or anything alike as I showed sufficient proof about the payment. From my end, this trade went wrong either because either

    the seller is a scammer
    there was a technical problem
    the payment was flagged for some reason and is in some backlog for further analysis by banks / authorities

Besides proof of payment, I hold a statement from my bank saying that their investigation lead to nothing
due to the lack of cooperation from the receiver´s bank.
I even called the seller´s bank, obviously without any outcome as they understandably don´t give out information about their clients to strangers.

The arbitrator holds all of these proofs, even a recording of this call.

I have high confidence in the integrity of the DAO, and therefore simply accepted their decision.
BISQ is experimental, and if 1% of transactions "fail", it´s part of my risk management.
Thankfully, the amount was not high.

If there is anything I would like to see now, it´s a 50/50 refund to both parties plus the honesty of the seller
to notify if funds ever arrive at his account.

Actually, I assumed that these cases happen more often, and I was actually quite surprised to see this amount of discussion about the issue.

That said, I am available and happy to cooperate in any necessary way.
best to the project !

**Comment by jmacxx** [comment]
It seems to me that you are both in good faith and an error has been made by the banks.  Your proposal of a 50/50 refund seems like the most reasonable outcome if you can both agree to it.  @lostsock1 would you be willing to send your evidence of payment to @bisqu1465 - you are both on Keybase and it would be easy to do it there.  I think if they saw your proof of payment they should reasonably agree to splitting the funds 50/50.

**Comment by lostsock1** [comment]
So after sharing my proof with @bisqu1465 and him accepting it, the DAO would payout our shares ? I suggest the proof is delivered in the presence of a mediator in the room.

**Comment by pazza83** [comment]
Hi @bisqu1465  

@lostsock1 messaged me on Keybase asking if I would be willing to mediate a screen share session between you both. The aim would be to share proofs and then come to an agreement on a payout.

I said I would be happy facilitate this if it was agreeable to yourself.

I have sent you a message on Keybase. Let me know if you would be willing,

**Comment by bisqu1465** [comment]
Thanks for taking care of the issue.

Consider that the amount you are losing here is quite low, for me 500 euros are a considerable amount and losing even half would be a hit for me. I'm not a professional trader or anything like that. I was changing my own money.

I'm happy to see that things are getting more clear, but this is definitely not thanks to Bisq's arbitration process, that as hippydippy said very well, was handled poorly.

In light of this, i think would be a good idea for Bisq to refund both me and the buyer of the entire amount. I understand Bisq doesn't want to encourage non-standard behaviour, but this was definitely something that Bisq's trade dispute has handled poorly and a full reimbursement would be appreciated, even only as a sign from Bisq that they acknowledge their mistakes.

I don't think it's necessary for me to see proofs personally if what @lostsock1 has been verified. Note that i asked multiple times to the arbitrator what proofs the seller has shown. It was important to have an idea of how likely was that the other party was a scammer. I wasn't provided with any answer, so until now i didn't know that the proofs @lostsock1 provided are solid.

**Comment by lostsock1** [comment]
Despite the long waiting period, I cannot say BISQ handled this poorly. Of course I would be happy to receive the whole amount, but it wouldn't be fair to make the DAO pay for it.

**Comment by pazza83** [comment]
I think the funds from the donation address (0.01485 BTC) should be given to the traders in whatever way can be agreed between themselves.

**Comment by pazza83** [comment]
Many thanks to @bisqu1465 and @lostsock1 for entering mediation for this issue. 

Mediation is now complete.  I will post the summary below.

Please can you mark with a thumbs up or down if you agree with the mediation summary.

**Comment by pazza83** [comment]
Ticket closed on Sep 24, 2021
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: cjtlq
Currency: EUR
Trade amount: 0.0099 BTC
Payout amount for BTC buyer: 0.007425 BTC
Payout amount for BTC seller: 0.007425 BTC

Reason for dispute: Bank

Summary notes:

BTC Buyer sent payment.
BTC Seller did not receive payment.

BTC Buyer and Seller both provided strong evidence to Arbitrator.

BTC Buyer and BTC Seller have agreed to receive half the funds from the trade each.

BTC Buyer and BTC Seller also have a gentleman's agreement to contact each other via Keybase is the missing Euros turns up in either of their accounts.

Once BTC Buyer and BTC Seller have verified their btc addresses the refund agent will send:

BTC Buyer  0.007425 BTC to bc1qvw8s7p93zlcnxg8drhzq26dwxzc6ec4s6227n8 
BTC Seller 0.007425 BTC to bc1qkjeefgk40lh488ztevcqxekrdfzna3nks2eeuh

--------------------

Next steps:

Traders to accept suggestion from mediator and verify the above btc addresses.

Once addresses have been verified payment @refund-agent2 will make the payout.

**Comment by refund-agent2** [comment]
The reason to verify the addresses is that traders also confirm owning that addresses, extracted from the contract. You don't need to verify it if you don't want to, but this are the instructions:
At the bisq client, press ctrl+G and click the "Sign-Verify" tab. Fill the fields and send the result at Keybase, to pazza or me, with this format:
	Message: "Trade_ID"
	Address: "Address"
	Signature: "Signature_given_after_clicking_sign_button"

**Comment by bisqu1465** [comment]
I finally sent the string of text as requested. I have to say that this has been a nightmare. Arbitrators doing their job poorly and answering much beyond the maximum time guaranteed by Bisq. The support team agreed it shouldn't happen, but instead of giving apologies or an explanation, the arbitrator posted a comment - https://github.com/bisq-network/support/issues/1027#issuecomment-968275716 - where he conveniently mentions only the times he answered within the time frame, but "forgetting" the times he didn't. To my surprise, nobody cares.

Furthermore, let's not forget the more than 2 months of poor arbitration and mediation where personal information had to be provided because the arbitrator failed to request the one inquiry that would have resolved with 0 doubt the situation; confusing support process, documentation that doesn't match the user interface and more. I hope Bisq will make efforts to improve, because this was my single worst experience with an exchange and i was a huge fan of Bisq before, but now i will definitely not use it ever again. This is all just too unprofessional to ignore.

**Comment by refund-agent2** [comment]
Ticket closed on
Arbitrator node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Summary: 

Trade ID: cjtlq
Currency: EUR
Trade amount:0.0099 
Security deposit: 0.01485
Payout amount for BTC buyer: 0.007425 BTC
Payout amount for BTC seller: 0.007425 BTC

Delayed payout: 03928c4af8e1d3a0bdb73a6c7415c19d2af387f9db7206bc28086324ecaf81ab

Reason for dispute: Other

Summary notes: After being unable to take a decision on the payout, the traders, with mediator's help, have reached an agreement to split all the funds in dispute.
https://github.com/bisq-network/roles/issues/93#issuecomment-965778668
https://github.com/bisq-network/support/issues/1027#issuecomment-977465059

Arbitration ticket closed through TXID:d28629a13a4e07b9683cadf95daf8fd113f1a26b036296d173df0e50cb66240f

BTC address ownership proof (use ctrl+G to sign/verify):

Buyer
ID: "cjtlq-550943f1-9702-4b7b-a480-31d4d085e4b5-172"
ADDRESS: "bc1qvw8s7p93zlcnxg8drhzq26dwxzc6ec4s6227n8"
SIGNATURE: "H2ayG/dRbaRao7D/zAJ2Gijvw228kDyOE0PWJMDocAlASDomJUSApU3CPdQ9f6uutKl4GV4cQhR07Fv902ToalY="

Seller
"cjtlq"
"bc1qkjeefgk40lh488ztevcqxekrdfzna3nks2eeuh"
"H6kdXFeJskcZjiaeSq/E5XhyJEwlRJBte0/GKtzorAe5PX0ROsSIJpnk8ZKLa0YSusY+3ELGESsgMaAnx2fFoTQ="

**Comment by w0000000t** [comment]
I regret your conclusions, as it would mean having one less seller on the platform, yet I respect those, as losing money where you know you have no responsibility in the matter, definitely stings, plus the issue you report with arbitration.
Definitely a one-of-a-kind situation with the SEPA system just "losing track" of money, I believe it should turn out later if not sooner.
The arbitrator being the most trusted role on the platform, places them in extremely heavy shoes; they do have quite some time available to reply to issues tough, so this brings up questions about the reason this long delay occurred.
Could this role be ever covered by a trustless mechanism though?

**Comment by jmacxx** [comment]
In my experience the arbitrator has been utterly professional and responsive within the expected timeframe.  Its possible that some replies from the arbitrator may not have been received, causing this confusion.  Other reports of missed messages have surfaced, causing similar problems.  See https://github.com/bisq-network/bisq/issues/1172  https://github.com/bisq-network/bisq/issues/5526

**Comment by lostsock1** [comment]
my funds have arrived. ticket may be closed. thanks for all the support.

**Comment by pazza83** [comment]
I am pleased that this trade was able to reach a conclusion for both parties. 

It is an unusual case and hopefully it is a while before we will see a similar one again in mediation / arbitration.

Thanks to both traders for persisting with mediation and arbitration.

**Comment by pazza83** [comment]
Closing as payout has occurred.
