### ISSUE TITLE
Fee reimbursement for trade ykykan-fb8dabbe-0fa7-44c8-85f9-23aff3381426-094

### ISSUE THREAD

**Issue by samhar1993** [bisq-network/support#1029]
This request is a strange one. I've had 1BTC held up in this trade since 2019. I've tried and tried to get it back but no one seems to be able to help. The buyer of my BTC falsely claimed they'd sent payment but definitely hadn't. I can't open mediation as it says:

cannot invoke "org.bitcoinj.core.transaction.getlocktime()" because the return value of bisq.core.trade.getdelayedtx()" is null.

Could anyone help me please? 

![proof](https://user-images.githubusercontent.com/94456858/141988297-19a47273-bd7b-4265-a24e-fb1030fc85c4.png)

Maker:  0919d09e0d43d9b0d90ca9122eda6c2508cb52799ec992fba928b764080edaa8
Taker: e57ff57e81030eb3082e31ed98d656b09c1a46a876187ce3d00cac2495942899
Deposit: 5e618aeb3824ebd0ffc5b0c2c44c90e72d38d6354e3165e9950beb6052546800

Bisq version: 1.7.5 - Not sure what version I used for the original trade
BTC address for reimbursement: 1mKu29sP4SBHALQZoao13YkiGmHYa4CvF

**Comment by leo816** [comment]
Can you please contact me on keybase to get to the bottom of this? My handle is leo816

**Comment by samhar1993** [comment]
Thank you I've contacted you on there
