### ISSUE TITLE
Fee reimbursement for trade hr0scp

### ISSUE THREAD

**Issue by Luke-Programmer** [bisq-network/support#1030]
![obrazek](https://user-images.githubusercontent.com/94471952/142024558-38eaa195-4e1c-4878-aacd-7f16a14f73b6.png)

Maker:  b3503ccb3076c8debc1ea90c9abf6145b9b9768db09019cb413b8e16beb1c19a
Taker: d194bef2ebdc636fbd854341bec30be6e0de9f09df9c1834eb0794d137625d9e
Deposit: ..........

Bisq version: 1.7.5.
BTC address for reimbursement: bc1qujdjpedwtela4nusk0u9ymp9ad54h3y68s5mre

Other notes:
The trade protocol encountered some problems.
The deposit transaction (the 2-of-2 multisig transaction) is missing.

**Comment by leo816** [comment]
were you the maker or the taker? please show all the information required

**Comment by Luke-Programmer** [comment]
I am make
![bisq_re2](https://user-images.githubusercontent.com/94471952/142418488-73605c52-4e29-448a-a120-07a67a3a6922.jpg)
r.

**Comment by Luke-Programmer** [comment]
@leo816 do you need any more info?

**Comment by leo816** [comment]
Payout made with #1046
