### ISSUE TITLE
Deposit still locked

### ISSUE THREAD

**Issue by klnit** [bisq-network/support#1031]
There is still a deposit that I made to a failed BTC buy order. I accepted the buy order and it timed out with an error. During this time my deposit got confirmed. I cannot access it. What is the mechanism to chargeback!?!

My deposit tx: 83d2754a87fb79abb2460a1ccc30897116c4d9012fbca9fa85f210a845571a2b
Bisq locked it away for my buy intention with: c2724b0f2b919606b651dd390b68d54dd95495974e80de631ff46310c4fb4844
still sitting there

github-issue:
related issue #1022 

Bisq version: 1.7.5

**Comment by leo816** [comment]
it seems the payout was made, please reach out through keybase (leo816) to find out what happened here

**Comment by klnit** [comment]
I found the issue. Usually I am using an external wallet but this deposit was obviously locked in the Bisq wallet. I was able to claim it now. Thanks
