### ISSUE TITLE
Fee reimbursement for trade GMWNMQ

### ISSUE THREAD

**Issue by jblmk** [bisq-network/support#1032]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
<img width="914" alt="Screenshot 2021-11-17 at 22 16 28" src="https://user-images.githubusercontent.com/51084385/142283816-6df338d3-8495-49b9-a8e4-925e15de8c57.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  d93453292a480da76c02549cd55a1e78bd94bb8acf3f60aec6b15b10ebff9785
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:v1.7.5
BTC address for reimbursement:bc1q8j0y0qg8knyqzpaw9t0jlcvdvpmk957k5kcnx3

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
taker fee non existen, therefore reimbursement is not justified.
