### ISSUE TITLE
Fee reimbursement for trade sjjmbko

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1035]
![grafik](https://user-images.githubusercontent.com/63785272/142778703-f5d5e0d8-3d96-47d1-b6db-92cc571a7c93.png)

Maker:  48ad218eafdc73aa932cc417c1aaa17f7df801aa4396eebbeabf612c85fe3842
Taker: 25d305caa6a26acce1904f1eb199b26dc6ab25e44f348fb15c1208be76ae7693
Deposit: ab037b3cbea3112e275d5cec5e92eb4f65042ae11b058bcaf0d9800b5deb8dc7

Bisq version: 1.7.5
BTC address for reimbursement: bc1qt7yvam2m2njpe7m43rqnptrfc92k5jjpml0uul

Other notes: I am the maker of this offer. The trade has failed. Please reimburse my fee. Thank you.

**Comment by pazza83** [comment]
Hi @Akira45-0 thanks for posting. I can see that this trade failed and you will have lost your miner and trade fees.

@leo816 please can you add this case to you list of trades to compensate.

Many tanks

**Comment by Akira45-0** [comment]
@leo816 @pazza83 Hello, 7 months have passed and I still haven't received the reimbursement, what's happening?

**Comment by leo816** [comment]
Payout was made with #1121
