### ISSUE TITLE
reimbursement for trade ykykan-fb8dabbe-0fa7-44c8-85f9-23aff3381426-094

### ISSUE THREAD

**Issue by samhar1993** [bisq-network/support#1036]
I'm hoping for a refund for a failed trade that I've been trying to claim back for a long time. 
The maker didn't send the XMR I was trading for and the transaction just got stuck. I tried opening a mediation ticket but I get an error as shown in the image. I tried opening the trader chat but that doesn't work either. If I send the transaction to failed transactions nothing happens either.
Leo816 has been really helpful and told me to make a reimbursement post.

Please can someone reimburse me I don't know where else to turn.

Thanks,

Sam
![proof2](https://user-images.githubusercontent.com/94456858/143056689-f7492932-7901-42b8-9997-33768bd44b85.png)
![proof](https://user-images.githubusercontent.com/94456858/143056717-363ea99f-c0b7-431a-9b5d-0117bd204056.png)

![proof3](https://user-images.githubusercontent.com/94456858/143056858-c67b473a-9793-40fb-8c86-d1d6f5d7b789.png)

Maker:  0919d09e0d43d9b0d90ca9122eda6c2508cb52799ec992fba928b764080edaa8
Taker: e57ff57e81030eb3082e31ed98d656b09c1a46a876187ce3d00cac2495942899
Deposit: 5e618aeb3824ebd0ffc5b0c2c44c90e72d38d6354e3165e9950beb6052546800

Bisq version: 1.7.5
BTC address for reimbursement: bc1qw4k3ekmfnjk42k8rvpzjvenhzy959cw0xkfhwl

**Comment by leo816** [comment]
please send your bisq logs through keybase (leo816)

**Comment by leo816** [comment]
Hello Sam,

The trade is from Feb 2019, which corresponds to the old protocol. It seems that your deposit was awarded to the buyer, which means that this could only have been the case if you stopped responding and the buyer provided proof that he made the payment correctly (with the tx id and tx key). This wasn't a failed trade therefore a reimbursement is not justified.
