### ISSUE TITLE
Fee reimbursement for trades 8330785 and ryllv

### ISSUE THREAD

**Issue by nokycbitcoin** [bisq-network/support#1037]
![ryllv](https://user-images.githubusercontent.com/79871141/143950338-e573c092-b425-40e4-b9b3-3c6fdc0d4f28.jpeg)
![8330785](https://user-images.githubusercontent.com/79871141/143950343-7378bf45-a7d7-423b-9d67-a3a69e585afd.jpeg)

ryllv
Maker:  e2b103166edcf9f0aaebea52dd8bd0989f1a40652095c1bd5dcd9a0d4d1c2f1f

8330785
Maker:  2ee8237f22dd3e0849ee66d30da273f49bf8588e010622e7cd7eb5260d9a2343

Bisq version: v1.7.5
BTC address for reimbursement: bc1qjn5lry02qry4k9nw2hnm9syhj9f6xcftx8p8y0

Other notes: Automatic disable every time I try to enable them on My Open Offers Portfolio page. Thanks.

**Comment by jmacxx** [comment]
I confirm these two offers are eligible for fee reimbursement @leo816 per previous support team discussion.
`19BNi5EpZhgBBWAt5ka7xWpJpX2ZWJEYyq` is no longer recognized as a valid fee receiver.

5280 mining + 5000 trading fees
7350 mining + 5000 trading fees
**total = 22630 sats.**

![image](https://user-images.githubusercontent.com/47253594/143952033-425d0bd0-97ab-4ce7-9260-5a212dc0f8ab.png)
![image](https://user-images.githubusercontent.com/47253594/143952093-97b5c33c-a5d8-4574-b5e1-235d2104c338.png)

**Comment by leo816** [comment]
Payout made with #1046
