### ISSUE TITLE
Fee reimbursement for trade GeVOw

### ISSUE THREAD

**Issue by skatsiev** [bisq-network/support#1038]
<img width="906" alt="Screenshot 2021-11-30 at 17 14 20" src="https://user-images.githubusercontent.com/95305759/144095087-65fa2b2b-088d-4808-b292-e56267ada70e.png">

Maker:  ae398f498d283f351ffe8ae62d78b2619f6a841a6e7a7d3efa014dc37431c380
Taker: ...........
Deposit: ..........

Bisq version: 1.7.5
BTC address for reimbursement: bc1q7edtd0w6vtkps62z9ntxak8yna6qzcjcuhglpn

The error was a result of a timeout.

**Comment by skatsiev** [comment]
Any update?

**Comment by leo816** [comment]
taker fee not published therefore reimbursement is not justified
