### ISSUE TITLE
Fee reimbursement request for failed trade dzl7zu

### ISSUE THREAD

**Issue by fipanojoch** [bisq-network/support#1039]
![Screenshot from 2021-12-01 17-07-32](https://user-images.githubusercontent.com/43609631/144328911-3c1b0d58-de8b-4e10-8bb0-80bfd427fcd7.png)

**Comment by fipanojoch** [comment]
An error occurred at task: BuyerAsTakerSendsDepositTxMessage
Sending message failed: message=DepositTxMessage{
     senderNodeAddress=laj723kr5k7ihyeg5ktzav4oumh5vy3s3fkak3l53tmpsei76o3yfwid.onion:9999,
     depositTxWithoutWitnesses=0100000002474983cee07cb4dbb7a22dfd03c21889ac8010c308fb45aabc4c47a70f39d6d80100000000ffffffffa91c122798335b9508a784e85ba765cbbf632719a893959b65181ba4c1ae27b20100000000ffffffff019007160000000000220020a2e50ce7a086d085ca7071dc33dc6deded6f717f0a93fbe2e2893293456d8f6b00000000
} TradeMessage(tradeId=dzl7zu-90efb9b2-8aeb-4524-98ab-402c448a350b-174, uid=6b40369f-9c01-43d6-9025-3f8c990ae15d)
errorMessage=java.io.IOException: Cannot connect to hidden service

**Comment by w0000000t** [comment]
Both for this and your other request, you might want to copy/paste in here in cleartest the txid from that Bisq dialogue, or it's going to be a major hassle to transcribe it letter by letter from the image without getting anything wrong.

**Comment by fipanojoch** [comment]
Trading Id:  dzl7zu-90efb9b2-8aeb-4524-98ab-402c448a350b-174
Trading peer onion address:  5cjtbvoaunfhmg5rg3t3syqadm4vpmbnto6lkiosksdwbli6ofk7goqd.onion:9999
Maker Transaction Id:  b227aec1a41b18659b9593a8192763bfcb65a75be884a708955b339827121ca9
Taker Transaction Id:  d8d6390fa7474cbcaa45fb08c31080ac8918c203fd2da2b7dbb47ce0ce834947

Error Message:
An error occurred at task: BuyerAsTakerSendsDepositTxMessage
Sending message failed: message=DepositTxMessage{
     senderNodeAddress=laj723kr5k7ihyeg5ktzav4oumh5vy3s3fkak3l53tmpsei76o3yfwid.onion:9999,
     depositTxWithoutWitnesses=0100000002474983cee07cb4dbb7a22dfd03c21889ac8010c308fb45aabc4c47a70f39d6d80100000000ffffffffa91c122798335b9508a784e85ba765cbbf632719a893959b65181ba4c1ae27b20100000000ffffffff019007160000000000220020a2e50ce7a086d085ca7071dc33dc6deded6f717f0a93fbe2e2893293456d8f6b00000000
} TradeMessage(tradeId=dzl7zu-90efb9b2-8aeb-4524-98ab-402c448a350b-174, uid=6b40369f-9c01-43d6-9025-3f8c990ae15d)
errorMessage=java.io.IOException: Cannot connect to hidden service

**Comment by fipanojoch** [comment]
How about this.... the taker fee is published, can I still see a refund?

**Comment by jmacxx** [comment]
Yes, as taker in a failed trade you lost 5040 & 3728 sats.

 = 8768 sats to be refunded.

Please post your BTC address for reimbursement.

![image](https://user-images.githubusercontent.com/47253594/146021515-5ada9593-7baa-4dd7-975a-b16b70298790.png)

**Comment by fipanojoch** [comment]
Here's the BTC Address:

bc1qdhmvrq9cmvp3fn6xwpegkkamjlpd72nsldnfe8

**Comment by fipanojoch** [comment]
Here's the BTC Address:

bc1qdhmvrq9cmvp3fn6xwpegkkamjlpd72nsldnfe8

**Comment by leo816** [comment]
Payout made with #1046
