### ISSUE TITLE
Requesting refund for trade \fee - TX: xElgTkrs

### ISSUE THREAD

**Issue by fipanojoch** [bisq-network/support#1040]
![Screenshot from 2021-12-02 08-18-43](https://user-images.githubusercontent.com/43609631/144439816-7b3d8f96-13ae-4162-a5f8-b92266dab5f6.png)

**Comment by fipanojoch** [comment]
Trading Id:  xElgTkrs-fb3b81fc-23eb-458e-ad22-038f5ce3c5ba-175
Trading peer onion address:  vhtsyyi7ohvrwikgfngu5l55blb5jegfqmqbdzocgtlaq2woifbbhmid.onion:9999
Maker Transaction Id:  f5a7d739364b052079c4ea01c5875bc22b5e20a1a9f858ce64b1f22241b42576

Error message:
An error occurred at task: CreateTakerFeeTx
Exception message: Insufficient money,  missing 0.00004754 BTC

**Comment by leo816** [comment]
taker fee not published, therefore reimbursement is not justified

**Comment by fipanojoch** [comment]
How about issue #1039
This message was sent from my mobile phone.  Pardon my brevity and any typographical errors.
