### ISSUE TITLE
Trade reimbursement for trade HGVII

### ISSUE THREAD

**Issue by wildduck379** [bisq-network/support#1042]
Trade reimbursement for trade HGVII

I am BTC seller. Trade amount and asset: 2 BTC for 473.4 XMR
Deposit amount: [AMOUNT] BTC

Maker tx: a2ad4d3aef53360b4070e065e4323bf84e8b40ec2763125b1d7542be57a85342
Taker tx: a57f00436809d50f6c6cbe7658e74a1c1f697036d1fb5d575030017e930814e6
Deposit tx: 9a17b57bdebb731b8c74fc7796e25a69dd8c533da8d5e7039166aaed22801ef0
Delayed payout tx: 3853dc215bf586884ff430ce7afe4c6b85640ce9a397f45815ea0fe8a9aeb34d

Reimbursement amount: 2 BTC / [30 day BSQ average] BSQ = **`[TOTAL AMOUNT] BSQ`**
Reason for reimbursement: [REASON]

#### Mediation suggestion

System message: Mediator's dispute summary:
Mediator's node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Ticket closed on 13 Nov 2021 20:58:51
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: HGVII
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 0.30 BTC
Payout amount for BTC seller: 2.30 BTC

Reason for dispute: Bug

Summary notes:
No XMR was exchanged.

This trade failed.

The reason for failure appears to be the BTC buyer's data directory being corrupted. 

Error message for your reference was:

An error occurred at task: BuyerSignPayoutTx
Exception message: buyerMultiSigPubKey from AddressEntry must match the one from the trade data. trade id =HGVII-488aab56-a66b-45ca-b5bb-60ae95823630-174

As a result of this here is a proposal to cancel the trade the buyer's security deposit, and the seller's trade amount and security deposit. 

Any problems please re-open this ticket or reachout to me on Keybase. My username there is: pazza

Kind regards

Pazza

-----BEGIN SIGNATURE-----
302c02140dcc55efb095cfae60ae92c1d2203dd4efd6014602140cdaea490f1d090619b17e7d51ed672879afc71e
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator

#### Arbitration summary

Ticket closed on Dec 6, 2021 9:42:28 AM
Arbitrator node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Summary:
Trade ID: HGVII
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 0.3150 BTC
Payout amount for BTC seller: 0.2760 BTC

Reason for dispute: Peer was late

Summary notes:
There have been 2 bugs: one caused the trade impossible to be completed normally. and the other caused traders to be unable to accept mediator suggestiton. 
Buyer responded on time to mediation and arbitration and provided the info for a manual payout. 
Seller provided the info for the manual payout late, when seller already published the delayed payout.
Seller took more than 48h to reply to arbitration, claimed to have accepted mediation but buyer said he wouldn't as he did not agree with the suggestion. Arbitrator asked for at least a screenshot to proof that buyer said he would not accept the mediation, but did not provide it.
Due to the bugs the trade process has not been the usual, so the penalty for the seller won't be the usual for an unresponsive trader (lose all the security deposit in favour of buyer, DAO keeps 10% of the security deposit). 
Through this payout, buyer gets 0.315BTC and seller 0.276BTC. Seller should claim to the DAO 2BTC paid in BSQ as this amount is too high for the RA to be reimbursed totally in BTC. DAO keeps 3% of the security deposit as arbitration fee paid by the seller, as this issue could have been solved through a manual payout and seller delayed the arbitration process unnecessarily.
Total amount for buyer: 0.315BTC 
Total amount for seller: 2.276BTC (0.276 in BTC, 2BTC in BSQ)

-----BEGIN SIGNATURE-----
302d02150086a2dd33cc109e966235a4478751074d064eefd4021438b3ae127bb1cbb5ecb6161e8f3b91ccc8f30d2f
-----END SIGNATURE-----

**Comment by refund-agent2** [comment]
Hi @wildduck379, you forgot to add the arbitration secret. Please add it here so I can verify that the keybase handle and this github account are the from the same user.
Please edit the deposit amount: Deposit amount: 0.3 BTC
As you can see from the arbitration summary notes, I have paid 0.276 BTC and the DAO should reimburse you 2BTC to be paid in BSQ. I'm not the one reimbursing you that amount.
In 4-6 days you should edit the "30 day average BSQ/BTC trade price", which you can get from DAO - Facts and Figures. Now it's 0.00003045, which would mean that the [reimbursement request](https://bisq.wiki/Making_a_reimbursement_request#Submit_your_reimbursement_request_to_the_Bisq_DAO) that you should submit to the DAO once this is checked would be 65681.44 BSQ, but to reduce the volatility, I think it's better to wait to submit the reimbursement request to the DAO.

**Comment by refund-agent2** [comment]
Please share the arbitration secret.
It's time to update the 30 day average BSQ rate. You can find it at DAO - dashboard. Now it's 0.00003051, which would generate a reimbursement request of  65552.28 BSQ. Send a message here when you have calculated the reimbursement amount.

**Comment by wildduck379** [comment]
Arbitration secret: 15fa8b

Please send me the refund

**Comment by refund-agent2** [comment]
The arbitration secret is correct.
You should edit the first post with the BSQ you are claiming and make the reimbursement request with the amount. This link will guide you through the process, you can ask me or Support channel at Keybase if you have any doubt.
Comment the TXID of the reimbursement request when you have submitted the compensation request, you have 4 days to do it.

**Comment by wildduck379** [comment]
Hi,
![git](https://user-images.githubusercontent.com/95884461/147143933-52ed0d1b-a73e-462c-9a35-ee7b8a197ab9.png)

Cant seem to fill out this form, no idea what to put in.

Screenshot attached.

If you want just send the Bisq funds to my address: Bbc1q5y76erac2xffhjxz92lw9yyknrkvftzy7p5q2c

67,700 BSQ

**Comment by jmacxx** [comment]
@wildduck379 I agree it can be confusing, the URL is a redirect to this exact Github issue.  So in the form replace the # with this ticket number 1042.  e.g. https://bisq.network/dao-reimbursement/1042  Everything else in that screenshot looks ok.

**Comment by wildduck379** [comment]
Submitted my reimbursement request through Bisq. Please follow up on it, thank you.

**Comment by refund-agent2** [comment]
Hi, you should update the first post and comment here the TXID of your proposal, which you can find at `DAO > BSQ Wallet > Transactions`.
The reimbursement proposal asking 64000BSQ seems correct, but for that amount you should paste the TXID for the proposal to be accepted.

**Comment by wildduck379** [comment]
Here it is:
https://mempool.bisq.services/bisq/tx/02013a5629f5b00ab32e2e9df30df195c616a831e2047b63c9c1ce1e4a9b838e

TX: 02013a5629f5b00ab32e2e9df30df195c616a831e2047b63c9c1ce1e4a9b838e
