### ISSUE TITLE
Reimbursement for trade yllvu

### ISSUE THREAD

**Issue by Funk4Lif3** [bisq-network/support#1047]
![Bisq Issue Y11VU](https://user-images.githubusercontent.com/87311046/147881121-1ea6011d-9693-4d1a-8b78-2854bfbc201a.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Reimbursement for trade yllvu-9a76346f-b2e2-4856-846f-7a8306e4cece-165

I am BTC seller as maker for EUR.
Trade amount and asset: 0.09 BTC for 2972 EUR
Deposit amount: 0.024 BTC

Maker:  4cbe7d3a2db2b4ad4bcbbd9399ee0481bae78915a669bd126437672f03fa2d6e
Taker: ae6abb513eba44815e0c921adba424d029633a6709735572537f311cc1406d83
Deposit: f45828c3df01b051bbeb49548198275496b0da72a66652113f316baf4d5acf57
Delayed payout: d511aa4ad7df9bd6fef3cbd20c6dc2d82e1ce2705f5375611a1a6eda0c5655d5
BuyerMultiSigPubKeyHex: bc1qgp8qseceqxfmr0drw0axg67wlkdq36hcl2dme2 
SellerMultiSigPubKeyHex: bc1q7lsjvsuqsv29pckxlnkyj77usq2x05jjjdqzla

Reimbursement amount: [AMOUNT] BTC / [30 day BSQ average] BSQ = [TOTAL AMOUNT] BSQ
Reason for reimbursement: A SW error/bug with the (Seller's) Bisq Client side which led to months of confusion. Buyer sent the funds (one day late however) although the seller does accept that BTC + deposit should be paid out none the less & the seller should receive the corresponding deposit also.

BTC address ownership proof:  (not sure how to provide)

>_Repeat the above for each trade you need to be reimbursed_

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropriate txid**_

Bisq version: v.1.7

**Comment by refund-agent2** [comment]
Did you publish the delayed payout?
Please fill at least the security deposit tx and delayed payout transation ID, which you can find on the tab of the screenshot you shared.
Also, edit the title with _"Reimbursement for trade yllvu"_

**Comment by Funk4Lif3** [comment]
Hi,

I have followed your suggestions and updated accordingly my apologies for the poor level of data provided :)

Cheers
F
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Funk4Lif3** [comment]
Hi,

I have done as asked, at least I think it is okay. Please confirm or notify me otherwise.

cheers,
Lee
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jmacxx** [comment]
This trade paid out Jul 18 2021.  It did not go to arbitration.  That information comes from looking at your deposit transaction f45828c3df01b051bbeb49548198275496b0da72a66652113f316baf4d5acf57 in a blockchain explorer and following the outputs.

The buyer received 0.09 + 0.024 = 0.114 BTC.
The seller (you) received 0.024 BTC security deposit to this address
 https://mempool.space/address/bc1q7lsjvsuqsv29pckxlnkyj77usq2x05jjjdqzla  

![image](https://user-images.githubusercontent.com/47253594/147998360-1561e7af-8799-4e65-a12a-4ee112cddde8.png)

**Comment by Funk4Lif3** [comment]
Okay I see that path and it is now clear that it is fully resolved.

Thanks very much for your efforts, You were a great help. :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MwithM** [comment]
Closed as solved. Already paid.
