### ISSUE TITLE
Fee reimbursement for trade 630641

### ISSUE THREAD

**Issue by pjakma** [bisq-network/support#1049]
![failed-trade](https://user-images.githubusercontent.com/1454461/148071655-ae15d7ca-b8cf-40df-a01f-23223ce10845.png)

Maker: 6aad278a59fea553a9e37e8d0f76d1457c22415c4b962ac411b0b2e20c4b1887
Taker: N/A
Deposit: N/A

Bisq version: 1.8.0
BTC address for reimbursement: bc1qw3rrh0rc09ll8raszm88ylg4m5002vatv2hf7y

Other notes:

The trade is failed. My side of deposit and trade were paid into the contract. This was the error I got:

![error](https://user-images.githubusercontent.com/1454461/148072181-b0aee7cc-503b-468a-aa2c-b58894234c34.png)

**Comment by jmacxx** [comment]
- The maker's reserved amount has been spent, so the trade protocol could not initiate the trade.
- The offer maker seems to be in a bad state, their wallet possibly out of sync.
- No funds left your wallet.
- You can move this to failed trades.

**Comment by pjakma** [comment]
Ok, I have discrepancies somewhere though. I have another failed trade too. I'll open one for that.

**Comment by pjakma** [comment]
Ok, so I was the taker in this particular trade, and there's no taker transaction, so I didn't lose anything here? Am I understanding correctly?

**Comment by jmacxx** [comment]
Correct, no funds left your wallet on this failed trade.

**Comment by pjakma** [comment]
Ok, thanks @jmacxx. Could you have a look at #1050 too?
