### ISSUE TITLE
Fee reimbursement for trade 719267

### ISSUE THREAD

**Issue by pjakma** [bisq-network/support#1050]
![719-trade](https://user-images.githubusercontent.com/1454461/148253078-d5ad1539-61bd-46a4-afe8-f2db49e87e57.png)

Maker: 7d13a942f2d0196668fcb693221ea4422ef2a13bf9f73ab22476d212969b7dad
Taker: N/A
Deposit: N/A

Bisq version: 1.8.0
BTC address for reimbursement: bc1qw3rrh0rc09ll8raszm88ylg4m5002vatv2hf7y

Other notes:

I have some discrepancies in the BTC I have in Bisq from what I think it should be that I think it should be. I have 2 failed trades. See also issue #1049 - though apparently that other one isn't part of the reason for it. 

So could this one be the reason? I'm not an expert in figuring out what happened, but I see a Maker Fee Tx in the dialogue, which goes to a confirmed transaction on the block-chain?

**Comment by jmacxx** [comment]
Someone tried to take the offer and it failed.  There are numerous reasons trades can fail, could be a message got dropped during negotiation or wallet issues on either party.  If you want me to check your `bisq.log` for errors feel free to DM me on keybase.

Your offer is still open and can still be taken by other peers.  There's nothing to reimburse here as your offer is still available to the market.  Your reserved amount for the offer (security deposit) is still available (shown under Funds -> Reserved Funds) until either the offer is taken or you cancel, see https://mempool.space/address/bc1ql6ypka80zzfnffhwx6ynz89w5vza6j9h4v08up


![image](https://user-images.githubusercontent.com/47253594/148288688-ec722dbe-4f14-4c68-9eb8-c5f9dfdafc32.png)

**Comment by pjakma** [comment]
Ok, phew. Thanks :)
