### ISSUE TITLE
Fee reimbursement for trade ODOFCVW

### ISSUE THREAD

**Issue by klnit** [bisq-network/support#1051]
![grafik](https://user-images.githubusercontent.com/20220593/149020609-06188b06-3246-49ae-8fcb-56557a2d88df.png)

Maker:  37bf81ca5e44bc6f2283737e43bd21e97819f2949f7d3a8b12bf1272f76d288b
Taker: f1fe8699501e6678b29a40c2ea6efb65de59f315e7a45d0262d766b3a69bffb5
Deposit: ..........

Bisq version: 1.8.0
BTC address for reimbursement: bc1qqtpf9kfv4amuesk2lttdzxsa0q9pz2khgr8nxc

**Comment by pazza83** [comment]
Hi @klnit 

Thanks for posting.

As you were the taker for this trade I can see that you lost both trade fees (2.12 BSQ) and miner fees (0.00002390 BTC) on this trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Paid out with batch reimbursement #1064
