### ISSUE TITLE
Fee reimbursement for trade 667061

### ISSUE THREAD

**Issue by b-squared** [bisq-network/support#1054]
![image](https://user-images.githubusercontent.com/486331/150844736-f30bd468-04df-42ec-98cb-20d67a64526b.png)
Trade 667061

Maker:  10d79f527f80418b9b36dc6d9f656e8bf9380ddf453dfd5edc85aaf18092e9d0
Taker: 16c834716a84338ca6fe9068e8b0c5624ce08fce9b59a4e2831fe388ea29152f
Deposit: 79486fa9f5910e52bdcd0bfcf6d61eb1ea3d9c1431770094897e1ec2d510cc7e 

Bisq version: v1.8.0 (at the time)
BTC address for reimbursement: bc1qp2cnqc5crlzc4sfatyfeqz26qnd4k8mg3l450w

Other notes:
Apparently the deposit transaction is invalid and its ID is red in the screenshot.
"Transaction invalid: some outputs that it attempts to spend have been already spent or are no longer valid."

**Comment by b-squared** [comment]
From the relevant portion of the log:

Jan-24 12:41:35.827 [JavaFX Application Thread] ERROR b.d.m.o.w.TradeDetailsWindow: trade.getDepositTxId() and trade.getDepositTx().getTxId().toString() are not the same. trade.getDepositTxId()=null, trade.getDepositTx().getTxId().toString()=null, depositTx=null 

At first it was fine (it appeared like a normal trade and was waiting for confirmation) but was taking a while, however then I got a modal window saying the deposit transaction ID is on the blockchain but my client is not detecting it, so I did an SPV resynch and then it became the errror you see above

**Comment by pazza83** [comment]
Hi @b-squared 

Thanks for posting.

You will not have lost any funds or fees as a result of this trade. This is because you were the Taker and the Taker Transaction ID failed: https://mempool.space/tx/16c834716a84338ca6fe9068e8b0c5624ce08fce9b59a4e2831fe388ea29152f

I would recommend you do an SPV resync as the taker tx id should not be showing on your Bisq instance as successful when it failed: https://bisq.wiki/Resyncing_SPV_file

This should also fix any issues of your Bisq incorrectly displaying any locked funds from this trade.

**Comment by b-squared** [comment]
Ah OK, thanks @pazza83. I had other failed trades that never even got into my open trades so I did not request reimbursement, but was told to do so with this one because of the trade fee. Either way it's not a big deal (I'd donate the trade fee). I did resync my SPV file, actually. Interestingly before I did that, it was basically stuck waiting. Then, after a while, the application told me to resync because it could see the transaction on the blockchain but my client was not synching. It was only after the SPV resynch that the error occurred. 

BTW I have been coding virtually my whole conscious life (I learned C++ when I was like 13) so you may be seeing some PRs from me. I am interested in this project and would like to contribute. Talk is cheap but I just figured I'd say it to....feel cool I guess (although I know you have to be careful about talking about your goals beause you'll get a similar dopamine hit as if you actually accomplished the goal). Anyway, thanks again.

**Comment by pazza83** [comment]
Hi @b-squared thanks for the quick reply.

When you resynced the SPV did the taker fee still show as green? It should be showing as red as it did not confirm. If it is still showing as green I would do another SPV resync.

It is always good to here people are interested in contributing check out the checklist here: https://bisq.wiki/Contributor_checklist

Also come say hi on Bisq's Matrix channel: https://bisq.chat/
