### ISSUE TITLE
Fee reimbursement for trade wadQqMt

### ISSUE THREAD

**Issue by gjcarneiro** [bisq-network/support#1056]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screenshot-20220130124925-894x637](https://user-images.githubusercontent.com/2197096/151700508-4f099e6f-76a6-4d87-8a7c-b9f001ef7005.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  1949fd2fb35a91f12afe2fa74e934c9ca9090b2dcf4cc91f8fd91faa1e6e345c
Taker: fd2c6facff58c602c0529387e237d4d335f4fb165cc07cc821128db337ecfac9
Deposit: 04cf6d72ea671dbc96fd637e060c7c1e42fd65e996c2caba16f0ecbf4cc559ba

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.8.2
BTC address for reimbursement: bc1ql40f576pzru59qgj7cslsxwtz8sugv4dtchd67

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

Two failed trades.  Always the deposit transaction is not published to mempool.  

I have my own full node (bitcoin core 0.22).  Options: `bitcoind -blocksonly -peerbloomfilters`

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by gjcarneiro** [comment]
Hm.. Just minutes after I made this bug then the deposit transaction went through.  Fingers crossed that it sorts itself out.

**Comment by pazza83** [comment]
@gjcarneiro glad this sorted itself out.

Looks like the trade has been completed. I will close this issue.

**Comment by gjcarneiro** [comment]
Ah, right, this one went through.  I erroneously closed the other one, confused with this one.
