### ISSUE TITLE
Fee reimbursement for trade 77293

### ISSUE THREAD

**Issue by gjcarneiro** [bisq-network/support#1057]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Trade](https://user-images.githubusercontent.com/2197096/151700883-53e09811-71e8-4743-9cf9-e38cdf972593.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  50ced0083c9ca884fdfa52df1d2b052ecacb8387cd3c946f25910f6c599e7cc6
Taker: 1482e33f3b8488a7c7447248eed658c157ddbda83028269482c57396b19d5f39
Deposit: 10e0633fbfd3fd31ad1b739a799c17502b8df2e1a197190b0fe5e046c4a20dfd

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.8.2
BTC address for reimbursement: bc1ql40f576pzru59qgj7cslsxwtz8sugv4dtchd67

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: it should be noted that I used an external wallet (Sparrow 1.5.1) to make the transaction.  This is the external transaction ID: 0c58028aa365b9f2f4c2433ed6649a33b69e8c8f1b6223813b6ef8c1a5822c20

I don't know why the bisq transaction id is different from the external transaction id.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by gjcarneiro** [comment]
This one went through eventually. Closing.

**Comment by gjcarneiro** [comment]
I confused this one with wadQqMt.  wadQqMt was the one that sorted itself out.  This one might be lost, I don't know.

Look, it's not a big amount of money, if it's lost, it's lost.

However, I am worried that using an external wallet might be buggy.  I did a few traders after using only bisq's internal wallet, and it worked.  But this one, my first trade, using external wallet (Sparrow), didn't work at all, the transaction with the deposit was created but bisq was looking for a different transaction ID.

So, Bisq was looking for this transaction ID: 10e0633fbfd3fd31ad1b739a799c17502b8df2e1a197190b0fe5e046c4a20dfd
But Sparrow, called by Bisq  made this transaction ID: 0c58028aa365b9f2f4c2433ed6649a33b69e8c8f1b6223813b6ef8c1a5822c20

There might be a bug in the Bisq software, or at least interaction with Sparrow bug.  In that case, I think Bisq should strongly advise to use the internal wallet.  Using external wallet is a huge risk.

**Comment by pazza83** [comment]
Hi @gjcarneiro 

Thanks for posting. I can see you lost trade and miner fees on this trade.

You have not lost any of your security deposit as the deposit confirmation did not confirm. The funds will have been sent to an address in your Bisq wallet: bc1qlxqarerck773h8gr4jfq4rqcua39ecypmkd35c

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
Paid out with batch reimbursement #1064
