### ISSUE TITLE
Fee reimbursement for trade z4iyfi

### ISSUE THREAD

**Issue by defkult** [bisq-network/support#1058]
![image](https://user-images.githubusercontent.com/1683677/152229850-ca43efc8-aa06-4a37-8255-bf3dc4b6249e.png)

Maker:  c99ef05f17d5155b7eaf9cb90505917a033a055763ac2cdffc58bb324fff9819
Taker: N/A
Deposit: N/A

Bisq version: v1.8.2
BTC address for reimbursement: bc1q5ak09p0y0xpw0yrd26r2qz3psnexwffs4yrzwk

**Comment by pazza83** [comment]
Hi @defkult 

Thanks for opening.

As you are the taker and there is no taker transaction ID you have not lost any funds, mining or trade fees on this trade.

There is nothing to be reimbursed.
