### ISSUE TITLE
Fee reimbursement for trade WOQRL

### ISSUE THREAD

**Issue by Nikorico** [bisq-network/support#1059]
![2022-02-04-220955_924x732_scrot](https://user-images.githubusercontent.com/63113065/152603492-1de6b421-72f0-4162-a405-0b23a57bb55c.png)

Maker:  1cd87d335fce465179f4c2771ba0086197252f8e4fdbe7ebd22894717e4ed8e9
Taker: cc44cbb189aa3cfbef69c60f76bf388ea43bbada601009f7027d70721679d7e9
Deposit: ..........

Bisq version: 1.8.2
BTC address for reimbursement: bc1qlgq7zrczgf0hueml9q5urrz0jd2v3sajvwwhm6

Other notes:

Trade failed due to network issues on my side.

Thanks.

**Comment by pazza83** [comment]
Hi @Nikorico 

Thanks for posting. I can see you lost trade and miner fees on this trade.

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
Paid out with batch reimbursement #1064
