### ISSUE TITLE
Fee reimbursement for trade RPQFTC

### ISSUE THREAD

**Issue by morpheusTR** [bisq-network/support#1060]
![Screenshot from 2022-02-07 13-52-09](https://user-images.githubusercontent.com/99187082/152791812-ae655ae3-acff-4287-a856-d979c8cf7900.png)

Maker:  b1fdc5d2770dec6db8f72c667d462a3d1ec928c0fb96d1a91f26ab861b45a306
Taker: ...........
Deposit: ..........

Bisq version: 1.8.2
BTC address for reimbursement: bc1qspvxdzrey9gp9l6fj3jaz2wyqwu80252pxuvl0

Other notes: I don't know why it says Insufficient money,  missing 0.0843966 BTC. I can see that my wallet has sufficient founds. 

Please reimburse fees.
Thanks.

**Comment by leo816** [comment]
taker fee is missing, no fees left your wallet therefore reimbursement is not justified
