### ISSUE TITLE
Fee reimbursement for trade SLW86CS

### ISSUE THREAD

**Issue by chaosgamingtech** [bisq-network/support#1061]
Trade state: INIT

An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=470976718
makersPrice=461373250

I can provide the Trade ID or the Maker fee transaction ID.  Other than the Trade Fee, do I also get back the Transaction Fee.  

Maker fee transaction ID: f1fd98b055e06a6849053513959fc7f531cb8a26732ad9142af24fdacaa7ccc8

How can I tell if my deposit, and my counterparty's was refunded?

**Comment by chaosgamingtech** [comment]
![image](https://user-images.githubusercontent.com/97006029/153515101-53e5d9c2-71dc-4a4b-81a1-fd66ba28a292.png)

BTC for reimbursement: 13ezoR4RMYX1psLYX7KK7UmXbwA15VdxEE

**Comment by pazza83** [comment]
Hi @chaosgamingtech 

As you were the maker for this trade and there was no deposit tx id the trade should remain take-able for someone else.

Do you still have the offer: SLW86CS  in your open offers?

**Comment by chaosgamingtech** [comment]
No, the trade is sitting in the FAILED list.  I don't know if I lost my deposit, as well.
![error](https://user-images.githubusercontent.com/97006029/154822060-6e89ee9c-bbbc-4018-91b1-120578a91a95.png)


And, when I try to "Move trade to open trades" - I get the an error, see attachment.
![error](https://user-images.githubusercontent.com/97006029/154822095-bba10b6f-1366-4f5c-b2ec-9cec084ce4a0.png)

**Comment by chaosgamingtech** [comment]
I can also share the bisq.log file, if needed.  Not sure if contains personal identifiable information... But, can share it through Matrix.

Let me know.

**Comment by pazza83** [comment]
Hi it looks like the funds from SLW86CS were used in a trade on 11th Feb:

53d6a573152dffa966044d1f1a67a8534f5bf46917a7b30600716ca05b3d5ed2

**Comment by chaosgamingtech** [comment]
Thanks.  Though, I'm not sure what that means...

Did I lose any funds, or fees on the transaction?  And, if so, can you provide a breakdown of what I should get back.

**Comment by jmacxx** [comment]
@chaosgamingtech you cannot lose a deposit, because they do not leave your wallet until they are safely inside a trade 2-of-2 multisig.

What pazza said is correct, your offer remained open and it was successfully taken shortly afterwards on the 11th Feb.  That's what it looks like on chain, if you look in your Bisq `Funds->Transactions` screen it will give you more detail.  Look for lines mentioning the tradeId `SLW86CS`.
