### ISSUE TITLE
Fee reimbursement for trade 2866066

### ISSUE THREAD

**Issue by petka3** [bisq-network/support#1062]
Trade status -- init

![image](https://user-images.githubusercontent.com/99694967/153961202-0c2c157a-36b6-4cc7-a692-ca6021ec6f28.png)
I sent BTC to deposit from external wallet and from bisq wallet. After confirm trade have an error

Maker:  f42b8f3ca453d20ffb0f89d28dbb170eb07d0722e71d0402d435bcd8861d354e
Taker: N/A
Deposit: N/A

Bisq version: 1.8.2
BTC address for reimbursement: bc1qvggg8jffvt4vxgparf2ekf8w7swqd6dkgtxp64

**Comment by pazza83** [comment]
Hi @petka3 as you were the taker for this trade and there is no taker transaction id you have not lost any funds in this trade. Therefore there is nothing to be reimbursed, as the trade failed and no funds from yourself were used.
