### ISSUE TITLE
Fee reimbursement for trade f87BwWYw

### ISSUE THREAD

**Issue by ijeb** [bisq-network/support#1067]
![Screenshot from 2022-03-05 11-10-47](https://user-images.githubusercontent.com/25456677/156879273-cb572c0b-c16a-46e1-94da-a00a987f467c.png)

Maker:  d237b0d35a6794c76135f48642730daa4a1b740904049228c8346e12b1760c06
Taker: 142ec7acb29c58606cc7c08aff4cfe921a7dbddfce6772e3f318a526d0589259

Bisq version: 1.8.2

The trade protocol encountered some problems. Please reimburse maker fees to bc1qdtlym0ezmlge9x2sjerx4tzggcp4rqy252kmua
Thanks.

**Comment by pazza83** [comment]
Hi @ijeb Please can you post the screen shot to include maker / taker information.

**Comment by ijeb** [comment]
Hi @pazza83. I updated my first post to include the extra information.

**Comment by leo816** [comment]
Closed with #1081
