### ISSUE TITLE
Fee reimbursement for trade 7615962

### ISSUE THREAD

**Issue by iwat617** [bisq-network/support#1068]
![image](https://user-images.githubusercontent.com/100872003/156634981-32767855-a7b2-429b-bb60-345548cbb890.png)
![image](https://user-images.githubusercontent.com/100872003/156635995-d22184c2-fb73-473e-9d1e-f7af9f5dea75.png)

Maker: 7d7120ea09e2d574f8104d363f4226a77a9a37c9dc9dee7a2e6be5d0bafd6897
Taker: 615b68ead203a1d0b62abf125df6efb6fcba94375c7b05492626b90d15ec01c9
Deposit: 0.01 BTC
Deposit Transaction ID: 6d72f2044eeb862050dded15ca7e9ddb7d7a99b6be02630e63c48bb509901653
Delayed Payout Transaction ID: 86e5eedc5b701b46a72d21ca2ab9dfca344112e97daaa828a20acb6b6f6c08a6

Bisq version: 1.8.2
BTC address for reimbursement: 19qarcnnr7rSeKPLRrggGyhQG9kFFbX56x

Please advise if you require any further info.

Thanks

**Comment by pazza83** [comment]
Hi @iwat617 I can see you lost trade and miner fees with this trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
taker fee not found. Funds never left your wallet therefore a reimbursement is not justified. @pazza83 am I missing something?

**Comment by pazza83** [comment]
Hi @leo816 and @iwat617, yes my mistake!

No refund is needed as no funds left your wallet.
