### ISSUE TITLE
Fee reimbursement for trade 49988450

### ISSUE THREAD

**Issue by tsalm24** [bisq-network/support#1070]
![2654](https://user-images.githubusercontent.com/101217016/157323862-2d3fa72a-a128-4c0b-8ae1-a797fa2618ba.JPG)
BTC address for reimbursement: bc1q86ac5jr8e24x8ashd62g64s3qg2lwm3uehuy0z
Please advise if you require any further info.

Thanks

**Comment by pazza83** [comment]
Hi @tsalm24 for this trade you are the taker. As there is no taker transaction you have not lost any fees on this trade. Therefore, there is not anything to reimburse.
