### ISSUE TITLE
Fee reimbursement for trade ojtrwdqk

### ISSUE THREAD

**Issue by henry-argueta** [bisq-network/support#1071]
SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

<img width="1116" alt="Screen Shot 2022-03-08 at 10 36 05 PM" src="https://user-images.githubusercontent.com/67522444/157367894-bb9bd755-b6df-451b-ad2c-e0cca7feef6a.png">

Maker:  3fcbaa7a9bf34e87b5df9865d0a90f881951844383a3a9a5e88d56a196a34c7f
Taker: NA
Deposit: NA
Bisq version: 1.8.4

BTC address for reimbursement: bc1q5fr7zpw4fme8zerkv007tsc06tdj7ya37yvfq8
Other notes:
everything is in tx id and screenshot. Prior to taking the trade, I sent more than the amount to bisq and it isn't supposed to allow me to advance if I had anything lower than the total amount. ''''

**Comment by pazza83** [comment]
Hi @henry-argueta for this trade you are the taker. As there is no taker transaction you have not lost any fees on this trade. Therefore, there is not anything to reimburse. 

Any funds you sent to Bisq should be in your Bisq wallet.

**Comment by henry-argueta** [comment]
@pazza83 can you explain this to me? I lost all of it. nothing is in the bisque wallet.
