### ISSUE TITLE
Fee reimbursement for trade gni9x5

### ISSUE THREAD

**Issue by HowardRoarkBTC** [bisq-network/support#1072]
SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

![trade_bsq](https://user-images.githubusercontent.com/88015004/159178506-96bbc887-1afe-4401-a6fc-926b04bb9768.png)

Maker:  912fb60d90a9f3e5648cab88bdb8fec400cbb6219cd6e11b3f917d7c374bc834
Taker: 23b9156e5dd684d2b72bcb5be6454dde77485c540ae319e1c5e34e5bda2a88d4
Deposit: NA

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.8.4
BTC address for reimbursement:  bc1qsj8c3qa77vh5dvl7c8c7dfv7202eyy428qupt8

>_Provide the Bisq client version to help developers identify the causing issue._

**Comment by pazza83** [comment]
Hi @HowardRoarkBTC thanks for opening the issue.

I can see you lost trading fees and mining fees on this trade.

@leo816 please can you add to your list for reimbursement. Thanks

**Comment by leo816** [comment]
Payout with #1081
