### ISSUE TITLE
Fee reimbursement for trade E2V0RN

### ISSUE THREAD

**Issue by cl0uding** [bisq-network/support#1073]
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/33531146/159339194-a514507c-0696-4400-9c83-bf5c4d0ef88b.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: d22c5f0b56b8981c51fc325f7ddaa1febb16d3654effa33d25df22dbcbaee6f1
Taker: 7f6c1a54a63d13abbd4e86145d3d69b378ab26cd150a17a5db9d2f2686bda9ed
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.8.4
BTC address for reimbursement: bc1qyu6v47k24s2uq8lc5z95kgz50rwfu68928re22

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @cl0uding thanks for opening the issue.

I can see you lost trading fees and mining fees on this trade.

@leo816 please can you add to your list for reimbursement. Thanks

**Comment by leo816** [comment]
Payout with #1081
