### ISSUE TITLE
Fee reimbursement for trade 76994011

### ISSUE THREAD

**Issue by mammo-footnoting** [bisq-network/support#1075]
![Error message](https://user-images.githubusercontent.com/102398429/160223404-dc881176-7e44-4a26-b20b-1e16819734a7.png)

![Failed Transaction (redacted)](https://user-images.githubusercontent.com/102398429/160222800-fe31c9ec-c9b0-493b-8278-dc54eb1ca9aa.png)

Maker: 1027b7beabd58cc879301a2cdb0867f04bf729f049810a62e0aa540096bf5870
Taker: baba65fede5574760a58e376715dda27717f2500a7b834e39d550c01e2672fac
Deposit: 41db7e7cc28652b94f755868d9d37f687f82f37dea142d73b08d510e812c5a76

Bisq version: v1.8.4
BTC address for reimbursement: bc1qxfk6pegke69ec0l4euwua2rvxhcysyvlgz7yyy

Other notes: Before the error message came up, the seller tried to get me to engage in trades outside of Bisq. I did not respond. 

![Chat message](https://user-images.githubusercontent.com/102398429/160223357-143b064e-e8f4-4a23-803b-7aea4ec54b5d.png)

**Comment by pazza83** [comment]
Hi the deposit transaction for this trade was successful.

I am assisting you with this trade in mediation and the issue was fixed with an SPV resync.

As the transaction was successful no reimbursement is required.
