### ISSUE TITLE
Reimbursement for trade acpaqpzc

### ISSUE THREAD

**Issue by Muhhe** [bisq-network/support#1076]
full trade ID: acpaqpzc-faf44038-7668-425c-9308-1056b88e41d5-184

Hi, I was trying to buy BTC with SEPA payment. I sent the money, clicked the payment started button, but the seller haven't confirm the payment. He also didn't reply to my chat message. 
After the trade period ended I explained the situation to mediator (leo816). He tried to reach the seller, but no answer so he proposed  to send me the BTCs (+ some extra from security deposit). I accepted the proposal, but the seller did not.
So after the mediation time was over I requested arbitration (or maybe it was automatic). Trade info shows "You have already opened a dispute" and "Refund requested". Since then nothing happened for a week or so.
It also shows some error:
```
Attention
The trade protocol encountered some problems.

There was an error during trade protocol execution.

Error: An error occurred at task: PublishedDelayedPayoutTx
TxBroadcastException{
     txId='ee75defcac385cd5a9f05a670d7c05ebf25bcd19ebd1f35a9ed48689f1fe3b83'
} bisq.core.btc.exceptions.TxBroadcastException: We got broadcastTx called with a tx which has an open timeoutTimer. txId=ee75defcac385cd5a9f05a670d7c05ebf25bcd19ebd1f35a9ed48689f1fe3b83

It might be that this error is not critical, and the trade can be completed normally. If you are unsure, open a mediation ticket to get advice from Bisq mediators. 

If the error was critical and the trade cannot be completed, you might have lost your trade fee. Request a reimbursement for lost trade fees here: [1]
[https://github.com/bisq-network/support/issues]
```

At the moment I lost the FIAT and the security deposit :(
Please help.
I can provide more info if needed.

Selected mediator: leo816
Selected arbitrator (refund agent): refundagent2

**Comment by leo816** [comment]
Hi, thank you for reaching out. I opened the ticket again and messaged you. Let me know if you see it

**Comment by leo816** [comment]
Payout was made here to the donation address, will close this ticket as I asume this was paid out correctly
