### ISSUE TITLE
Fee reimbursement for trade 34605903

### ISSUE THREAD

**Issue by ryenski** [bisq-network/support#1078]
<img width="922" alt="Screen Shot 2022-04-18 at 9 31 20 PM" src="https://user-images.githubusercontent.com/234/163908562-af836bc2-5e8b-46fa-aafa-a015acc9287c.png">

Maker:  736d62807bdb904a29bcedeaa208406298c1dee2b716c83ba79c2b540c745467
Taker: 1c7a9cb978a4c9346110ff705e87e594e94e2e44fe668b9a1df8da23bf463ec1

Bisq version: 1.8.4
BTC address for reimbursement: bc1qgyvljt9vwsp8vhklr96vzw0pyjneq4vcge9g5p

This trade was corrupted when computer performed an unexpected hard restart at the moment when the trade was accepted. Pazza is familiar with the issue.

**Comment by leo816** [comment]
Payout with #1081
