### ISSUE TITLE
Fee reimbursement for trade 1ryrfcyz

### ISSUE THREAD

**Issue by jshizz** [bisq-network/support#1085]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE 
![image](https://user-images.githubusercontent.com/105117195/167258856-673e6a81-564d-4735-ad85-bba2a4e952d3.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  9b0f47a194614c5a1b08dfa1594223890d358647302c8f33abe68738b1f0da83
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.8.2
BTC address for reimbursement: bc1q9aw238kalt2sz60slpvxcs4xetva8u5t6j42cj

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Not really sure what happened here, this is the message I see: 
![image](https://user-images.githubusercontent.com/105117195/167258993-587984f2-64ac-49d5-b5f8-9fadf503dc06.png)

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jshizz** [comment]
Hi, just checking on this...not sure what to do here.
thanks.

**Comment by jmacxx** [comment]
No trade fees were lost; your offer is still open.
