### ISSUE TITLE
Fee reimbursement for trade SVWUOTT

### ISSUE THREAD

**Issue by ArnieSchwarz** [bisq-network/support#1089]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/106310557/170466281-4df2f4a5-278e-409d-b5a9-a221b0684e22.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  edb41a7780b0874303749bdcbb67e84f9ba79ae8c3bdb69629b4f6ae8d7ef2ff
Taker: e40d3f7bc8d0b4014176c956aadaf5ffa427a53f343f4c097ffb3dbdb7bcb87b
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.1
BTC address for reimbursement: bc1qnpllv4y7wvxvsl7ehajgtxv0qzw7w58fzppu42

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Payout was made with #1121
