### ISSUE TITLE
Fee reimbursement for trade rnN7iAD6

### ISSUE THREAD

**Issue by giannanoir** [bisq-network/support#1090]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Issue](https://user-images.githubusercontent.com/106316231/170485247-1d456707-196e-4092-97ff-fefafbb83fe8.PNG)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  25f06637507b25c0696aa6cbaef691103eaabb408619264d815761b7c014a031
Taker: bb627045479c8f3cd44430d9df90736a33bef908562dedb73885abb8625f5e3f
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.1
BTC address for reimbursement: bc1q4cxfmgwp65vlw4d85gm8lqddxdvkvpj6vkqtdr

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Payout was made with #1121
