### ISSUE TITLE
Fee reimbursement for trade dAvCMSlf

### ISSUE THREAD

**Issue by dasrecord** [bisq-network/support#1096]
![image](https://user-images.githubusercontent.com/50388266/173209543-9f764c57-e0cc-48df-8d99-9f4428af6a0d.png)

Maker: 37056b6c525d6058208d14985cc9934f4aae4c635e71b738d76930929973b0d4
Taker: 215e7bb81383c254069dae0495e7bfda6871fa36e102b0c93a629393cc7faaa2
Deposit: 1f0ae80621042cdc375d23fd6a54d85cd9f085b1402b1fd3e55170fbc91567b6

Bisq version: 1.9.1
BTC address for reimbursement: bc1q7dmr3jxx4tmn0n0lz25nuss54zul0r0xjk8a5f

Other notes: None

**Comment by jmacxx** [comment]
ACK.

Taker fee of 0.00017600 paid in 215e7bb81383c254069dae0495e7bfda6871fa36e102b0c93a629393cc7faaa2 does look eligible for reimbursement.

**Comment by leo816** [comment]
Payout was made with #1121
