### ISSUE TITLE
Fee reimbursement for trade 851100

### ISSUE THREAD

**Issue by GithubUser2061** [bisq-network/support#1097]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/107407395/173346426-28a5fbc6-c630-41fa-9600-ce2a61dd6775.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  c06df4d3b3ccc54ccabacedf32a7eff8e66064c1303aba28a38683bb8947cf69
Taker: 37d5121a4af740f214afe2e6f54c4a83ea9bffe89b9434ca453b13844a9036b2
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.1
BTC address for reimbursement: 184nf2BW6WXNxa1K74hMnnbDcdHyQjoSm6

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmacxx** [comment]
ACK.

37d5121a4af740f214afe2e6f54c4a83ea9bffe89b9434ca453b13844a9036b2 looks eligible for reimbursement of the 0.00008888 BTC taker fee paid.

**Comment by leo816** [comment]
Payout was made with #1121
