### ISSUE TITLE
Fee reimbursement for trade dD6F7z

### ISSUE THREAD

**Issue by felipesocha** [bisq-network/support#1098]
![image](https://user-images.githubusercontent.com/107418776/173379142-c022c999-6f69-4080-84f1-627fcd0bd310.png)

Maker:  44ee8bb3c70019afc23a876c658fad03a081fff09a753f2da0f816af733d9ffb
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.91
BTC address for reimbursement: bc1q8mnpsdgsj3ev8hd5gxs7cfkkvtuy7kr46tng2y

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmacxx** [comment]
NOT eligible for reimbursement, the maker fee funded a successful trade on June 13th.  44ee8bb3c70019afc23a876c658fad03a081fff09a753f2da0f816af733d9ffb
