### ISSUE TITLE
Fee reimbursement for trade fpycr

### ISSUE THREAD

**Issue by m1sterc001guy** [bisq-network/support#1099]
<img width="676" alt="FailedTx" src="https://user-images.githubusercontent.com/1859166/173408269-312e6ff6-73c3-416b-832f-531bd55a02c9.png">

Maker:  65ae2944da81891a0046b80481dc0506ff4bce295f254fccc82762bd704add9f
Taker: Didn't work (but my tx did go through on chain)
Deposit: Didn't work

Bisq version: 1.9.1
BTC address for reimbursement: bc1qtpcfvwlqkuj7ml32drwwgs8k9la03tcwsdwycu

Other notes:

I tried to take this offer to buy the bitcoin, but when taking the offer Bisq timed out. Here is the tx id I used to take the offer: 4be5632971d4fcb962344d5915e9d0e2cf4141355799cfdb611a00b94a55924f

It looks like my security deposit will be stuck in the 2-2 multisig? Is it possible to somehow still complete the trade? I have tried to move it from failed trades back to open, but that doesn't seem to be working.

**Comment by jmacxx** [comment]
NACK.  4be5632971d4fcb962344d5915e9d0e2cf4141355799cfdb611a00b94a55924f is not a bisq transaction.
You do not have a security deposit locked up, nor did you pay any trading fee.  Check your `Funds -> Transactions` list.
