### ISSUE TITLE
Fee reimbursement for trade J9DEQ

### ISSUE THREAD

**Issue by okae** [bisq-network/support#1103]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![bisq_error_1](https://user-images.githubusercontent.com/393407/175020385-62b0f8a0-a717-4f14-b76e-3334fafbda1f.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  eaaeab773acb9f79ee0ef7d0cf41a2f6b5b9208217da93b30cca226daece5486
Taker: c2d18468455e10de25f68a32f1f03039f003b892c2127bf926b1ddbb33495cfb
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.1
BTC address for reimbursement: bc1qgk4fvdx2yugu4nd6fycgrxr3pu3s3y4kwkljh5

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Payout was made with #1121
