### ISSUE TITLE
Fee reimbursement for trade zvzdshs

### ISSUE THREAD

**Issue by okae** [bisq-network/support#1104]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![bisq_error_2](https://user-images.githubusercontent.com/393407/175021208-cf00e8a8-cfe3-41b4-afae-a34a1fdac200.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  4db041d9fef49945ed4a496d43c938c8b96839132b315fe696c4dbafd2e7de93
Taker: 974fad88f2c2d6563d702ea2adbcae06c5aa701247041e8b246b74841343c3f8
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.1
BTC address for reimbursement: bc1qgk4fvdx2yugu4nd6fycgrxr3pu3s3y4kwkljh5

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Payout was made with #1121
