### ISSUE TITLE
Fee reimbursement for trade 0974478

### ISSUE THREAD

**Issue by Senti-Crypt** [bisq-network/support#1105]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT
![0974478](https://user-images.githubusercontent.com/108226343/175818485-0e65853a-af5a-44f3-bafd-157992863f42.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: b789a24f3205734eae4e28b9e0fc3b92cd41ccc2a1b25ee29202ca36c495222c
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.2
BTC address for reimbursement: bc1qld4d7kdpl26c98necuckn79xmcg4552n8fdnvn

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Funds never left your wallet, this is not eligible for a penalty
