### ISSUE TITLE
Fee reimbursement for trade v2fst

### ISSUE THREAD

**Issue by rmuller9** [bisq-network/support#1109]
![image](https://user-images.githubusercontent.com/108292582/175994761-6ec780eb-4232-4053-a6b7-fdf45fc4b928.png)

Maker:  b7a5163c847adc09c0b5a1e6878da511674bba317f932600d84d2979839ae24d
Taker: 195e0a064595fd79cb068b9deee7846621d3a7994d7c58fbe93abbd4330b96d6
Deposit: N/A

Bisq version: 1.9.2
BTC address for reimbursement: bc1q9r8k9uwzknx24x5jk5znemcnqmrld4jz422agm

Other notes: running on Ubuntu 22.04

**Comment by leo816** [comment]
Payout was made with #1121
