### ISSUE TITLE
please reimburse nkcrtv

### ISSUE THREAD

**Issue by derekellison** [bisq-network/support#1111]
fee reimbursement for trade:
nkcrtv-147c67c0-ed7e-4edb-a312-516bfa808c7c-191

please unstick this trade so that I can "take offer" thank you

Note there is a bug in the software: while the "take offer" process said "your wallet is sufficiently funded" (BTC was in process of transferring from an exchange), then at the end of the dialog boxes, the transaction failed and said I didn't have sufficient funds. Clearly the process of checking whether funds are available during "take offer" is different to the final process of actually validating the funds
![failed_trade](https://user-images.githubusercontent.com/4453793/176431175-535cd211-ae11-4d62-a15f-a2a70d4718a0.png)
.

**Comment by leo816** [comment]
Taker fee was not published therefore a reimbursement is not justified
