### ISSUE TITLE
Batch reimbursement for failed trades oceqa & ckurunn

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#112]

**Comment by cbeams** [comment]
These trades should be taken to arbitration. Have you opened a dispute for each of them?

**Comment by AdriaanJoubert** [comment]
They are just normal failed trades, with no deposit transactions. Should I open disputes for them?

[screenshot](https://imgur.com/a/XhD2x0y)

**Comment by cbeams** [comment]
Yeah, please do open disputes for them. It's the best thing from a process perspective. Thanks.

**Comment by KanoczTomas** [comment]
Closing as invalid!
