### ISSUE TITLE
Fee reimbursement for trade DCHK5g

### ISSUE THREAD

**Issue by billypendennis** [bisq-network/support#1122]
DCHK5g

SCREENSHOT HERE
![Screenshot (557)](https://user-images.githubusercontent.com/78545634/178075902-cd7b0a23-8943-4bfa-b99e-793f6803dcdb.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: e574fe2d991cfaf76a8d5c4dfa6dad2a9522e9f5803aeec0b4bdd394e9ef0e00.
Taker: cef69d9b32cb7263603e67ca024f6834efbbfcb1bcd704ec50c453fdbffc7023..
Deposit: ecc1da067b30b467eb0240c8a021045a3bfc57ed7ec2f9a3b47c5a9160e09708.

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.8.4
BTC address for reimbursement:1N1RoGr2iCfr7guQGYK7Da6VCP3vMH7v2x

>_Provide the Bisq client version to help developers identify the causing issue. v1.3.7

Other notes:
I was seller and maker but buyer/taker did not complete the trade.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmacxx** [comment]
The trade went to arbitration according to the blockchain: [e574fe2d991cfaf76a8d5c4dfa6dad2a9522e9f5803aeec0b4bdd394e9ef0e00](https://mempool.space/tx/a948474df93bb11bebcb27bafa121db98dea9fa6c73833f81992d5a5afee44ee)

**Comment by pazza83** [comment]
Hi @billypendennis the BTC from your trade will have been paid out in arbitration.

Reimbursement requests are only be valid if submitted within 3 months of the trade date: https://github.com/bisq-network/proposals/issues/369

**Comment by billypendennis** [comment]
Hi Pazza83 and jmacxx, Thank you for your replies. Does that mean that I should of received something or did it go to the Arbitrator?
I know it is no big deal but I just like to know how it works.
Thanks again.

**Comment by pazza83** [comment]
Hi @billypendennis if you contact me on Matrix I will be able to provide this information to you. My username on Matrix is: @pazza83:matrix.org

For more info on Bisq Matrix see: https://bisq.wiki/Matrix_bisq.chat
