### ISSUE TITLE
Fee reimbursement for trade VYVHC5 (security deposit locked up after failed payout)

### ISSUE THREAD

**Issue by mventura2022** [bisq-network/support#1123]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/108956909/178100127-894710a7-1988-459a-a77e-6733b4b99e97.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  787e4570b7701c59dcca011825e23eb99bbf1ca83aafcae2df85e7b1e15ddbbe
Taker: 141cc28222b05d13ffd340f97467ad4335ae5e525107e24632bb7d6c577b85ed
Deposit: fd1d80535f4fce092e307519d455a54aa13eabfe64a9f28043de18b763f34472

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.4
BTC address for reimbursement: bc1q7jdd6wgcm7netdw9jrh7525ss376g6pr07k8ex

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

I am the seller of BTC. I received the FIAT after mediation, but the buyer forgot to accept the outcome. I tried opening arbitration but then got the error: 

"An error occurred at task: PublishedDelayedPayoutTx
Exception: java.lang.IllegalStateException"

My security deposit is still locked up. It now says the transaction was failed and I should move it to the failed transactions tab. But I still need my security deposit to be released.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmacxx** [comment]
The trade paid out, that's why you could not publish to arbitration.  Check the [deposit transaction](https://mempool.space/tx/fd1d80535f4fce092e307519d455a54aa13eabfe64a9f28043de18b763f34472) and follow the output.  0.035 security deposit  was returned to you.  Perhaps your Bisq did not get notified of the payout, but it is on the blockchain and hence in your wallet.

![image](https://user-images.githubusercontent.com/47253594/178106703-311be770-20e1-4913-8180-5e8384790e17.png)

**Comment by mventura2022** [comment]
Aha, ok that makes sense.
