### ISSUE TITLE
Fee reimbursement for trade 52076730

### ISSUE THREAD

**Issue by buddhalore** [bisq-network/support#1124]
![Bisq failed](https://user-images.githubusercontent.com/85696011/179388395-5ef2d656-5caa-4332-aa89-e59015a1339c.png)

Maker:  dfa95c1ebdd125e907117fc27b5ae94ce718ad1114803da7d5146cdf52704c43
Taker: 78f51517efa07dabd5ab91feb56f4ee6adce6afe607673d92b81cf44dd4f0205
Deposit: 9bfe4c829936e0c3817c839b3c5ad3111689fe7f2b00ae0ac1d948d1afe4afb6

Bisq version: 1.9.2
BTC address for reimbursement: bc1qm5yw8ujym002d9947prld4vts2yq40v9a6m2zl

Other notes:
The moderation resolution acceptance seem to have worked, but I missed getting the fee back. Probably due to a bad connection or VPN cutting communication in the client. See following screenshots for error:

![Screen Shot 2022-07-17 at 09 08 56](https://user-images.githubusercontent.com/85696011/179388144-a2af1f6e-4fc3-4d93-9e1b-c27e2e5e80b4.png)

![Screen Shot 2022-07-17 at 09 07 13](https://user-images.githubusercontent.com/85696011/179388187-cad274cc-3230-4ff6-bce8-61886588834b.png)

![Screen Shot 2022-07-17 at 09 05 48](https://user-images.githubusercontent.com/85696011/179388192-c7ada651-0ca0-444e-b1ac-49f984a058fd.png)

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
the funds are still in the multisig, please talk to the mediator. This is not eligible for compenasation
