### ISSUE TITLE
Fee reimbursement for trade YNZBM-a953d777-63c2-451e-a9b2-66582c98bd58-191

### ISSUE THREAD

**Issue by fldm** [bisq-network/support#1128]
>_The YNZBM part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
<img width="918" alt="nn" src="https://user-images.githubusercontent.com/109765284/180310661-ef60e7e8-f73c-4360-86e2-7b45032d4cc6.png">
>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  b6801eff8c1f16682580c41c3b343714d4e621ec4391cac1dbb6ec266108103a
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.4
BTC address for reimbursement: bc1q4snx566gk9cdyw2xqdkfnc88yl8unau7c5qms9

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
taker fee not published, funds never left your wallet
