### ISSUE TITLE
Fee reimbursement for trade LJYSC-661ac4d9-6f92-4993-9f68-468f95257886-184

### ISSUE THREAD

**Issue by SnowWireSand** [bisq-network/support#1129]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
LJYSC-661ac4d9-6f92-4993-9f68-468f95257886-184
SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images
![FEE](https://user-images.githubusercontent.com/110151074/181425662-8aca79b3-d37c-463d-b09f-ddc272b54173.PNG)
 where sensitive private data is visible!**_

Maker:  9144e906fad65d03e53637ff5f46e1ed140e091c983443fc28c16115345ad97e
Taker: 030f1e1bf898026ed15b18c68fb0106341661405e10c4ed1a41a230ec0292018
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.1
BTC address for reimbursement:  bc1qjphnwmgfmrcf8lsfe4nurz9smeq7nz937pwej0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Paid out with #1144
