### ISSUE TITLE
Fee reimbursement for trade 497406-434ce8c4-6479-4662-a4ca-678822346ce8-194

### ISSUE THREAD

**Issue by yellowbluefish** [bisq-network/support#1130]
Trade ID: 497406-434ce8c4-6479-4662-a4ca-678822346ce8-194

Maker: fa1802f3206613903d8f809b8017732e869f35a0181397c6220dc7ec77c8171a
Taker: N/A
Deposit: N/A
![497406 failed](https://user-images.githubusercontent.com/110358321/182048583-cbf144cd-0481-4da0-aa92-665762798903.jpg)

Bisq version: 1.9.4
BTC address for reimbursement: 1BbUQFQboGCWwsR74mTRzXKygRkwXcSFNU

"Taker's trade price is too far away from our calculated price based on the market price" error. Please, reimburse fees.

**Comment by leo816** [comment]
please copy and paste the maker fee tx to verify all the info
