### ISSUE TITLE
Fee reimbursement for trade FgeWo

### ISSUE THREAD

**Issue by rodrigolmmota** [bisq-network/support#1131]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/1029902/182234934-4307a9ac-bfd4-44a1-af2e-338ca7b5d34a.png">

Maker:  1c280fde60dd1caf6e7e6c066e332e70cd1efd7974642ba977e17cd7f6bfb45a
Taker: N/A
Deposit: N/A

Bisq version: v1.9.4
BTC address for reimbursement: bc1q08dgr0445cywp3h4pp93czzv2pqle6wk2pzfr4

Please reimburse fees.
Thanks.

**Comment by leo816** [comment]
taker fee was not published, funds never left your wallet therefore this is not eligible for compensation.
