### ISSUE TITLE
Reimbursement for .onion:

### ISSUE THREAD

**Issue by pitachef** [bisq-network/support#1134]
Note Error: : Timeout reached. Protocol did not complete in 120 sec.

Reason for reimbursement: there was an error in the transaction within the bisq platform and I can't transfer the btcs to the buyer, the buyer money  is already in my revolut account but I can't complete the transfer. I have already called the midfielders to solve the problem. bisq has blocked 0.0075 btcs from me until this issue is resolved. I want to settle this soon as much as the buyer wants. thanks for listening

BTC address ownership proof:

Bisq version: 1.9.4

**Comment by pazza83** [comment]
Hi @pitachef 

This trade has now paid out:

https://mempool.space/tx/d27a8771b203cd4c63226f45203e2619b62873fdaeddbf81eeddb563158843a8

Are you happy for this to be closed. There are no longer any funds in the multisig
