### ISSUE TITLE
Fee reimbursement for trade howevdr

### ISSUE THREAD

**Issue by bytesorchestra** [bisq-network/support#1136]
![bsq-howver2](https://user-images.githubusercontent.com/4754018/185236028-3e0d4508-602f-499e-839e-1d68d86a614e.png)

Maker:  993f8e078ec07a7133ec9a5452504452493da8be4854ed884e460a4da1f11a3a
Taker: e6fbf6c814233c98bf6ff0e40c00bf576f7f63d901d76d260f9b449681598363
Deposit: 60a93f81d245dfa2380bcf1a6f4b44756ad8ace598c98b9bac8bdcf578b317ce

Bisq version: v1.9.4
BTC address for reimbursement: bc1ql8d0anpvltw04w8gptdsmftltkl42r56c9lcvx

**Comment by bytesorchestra** [comment]
This transaction never made a confirmation on the blockchain, but fee charged

**Comment by leo816** [comment]
Paid out with #1144
