### ISSUE TITLE
Fee reimbursement for trade Bv0ikO and fdtMWM

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#1137]
# Trade 1 - Bv0ikO
![image](https://user-images.githubusercontent.com/111596410/185674806-8d6d66bc-7fc8-4822-b7bb-0a301b6c54b9.png)
![image](https://user-images.githubusercontent.com/111596410/185674846-9310179b-3f9d-44fe-b6ac-8a9c840a5644.png)

Maker: ff3aa5bbf53f529793c3ac3734402ccb7e81d3f4fde8fb119e32551d793769bf
Taker: 29cddc0d427757b875701763847980c3c15384030e07adb45bb81672a6ee7349
Deposit: 523a3db3c3a2a91db6329331465b5ccd21896654d40efb4d462525d82dba1c4b

# Trade 2 - fdtMWM
![image](https://user-images.githubusercontent.com/111596410/185674921-0b517559-5e3b-4b74-9ce5-70c6cb2dfa1f.png)
![image](https://user-images.githubusercontent.com/111596410/185674938-d6d29b39-48ba-472c-a1f2-86b80ecddd66.png)

Maker: 039f25bb0e335bea1827cf9cc899e5f98f6fcf05df1cdcc395ee03353ca30fac
Taker: 07c308eacfab046182dd633ad3fdd523bb4f6203e98466ac31ac7abbcfcc5cfa
Deposit: 7f013e5f6f94ba7bd9e46a957a7995f04879dbef0a8442b383a3e7fb51a49964

Bisq version: v.1.9.4
BTC address for reimbursement: bc1qn8mavukfm8ydxga2hjdk9x98tj9zs50584g6v4

**Comment by jmacxx** [comment]
If you were the maker then you need to do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file), as neither maker Txs were published on the blockchain.

**Comment by merneyllo** [comment]
This is after a SPV resync, does that mean no BSQ was deducted after all?

**Comment by jmacxx** [comment]
Nothing was deducted for the offer maker.
The offer takers, however, did lose fees.

**Comment by leo816** [comment]
please show a screenshot of the trade details if you were the taker
