### ISSUE TITLE
Fee reimbursement for trade fdtMWM

### ISSUE THREAD

**Issue by Lregent** [bisq-network/support#1138]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

![image](https://user-images.githubusercontent.com/112039975/186549582-6868ad9b-3ac0-4995-bfa7-922850bcb0ba.png)
![image](https://user-images.githubusercontent.com/112039975/186549601-005cb9b0-24de-41fd-9f11-0af6f7a5bc3c.png)

Maker:  .........039f25bb0e335bea1827cf9cc899e5f98f6fcf05df1cdcc395ee03353ca30fac
Taker: ...........07c308eacfab046182dd633ad3fdd523bb4f6203e98466ac31ac7abbcfcc5cfa
Deposit: ..........7f013e5f6f94ba7bd9e46a957a7995f04879dbef0a8442b383a3e7fb51a49964

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.4
BTC address for reimbursement: bc1q8m59p2d49jgz52rdr5ft6qgee42gru5nsq8l02

>_Provide the Bisq client version to help developers identify the causing issue._ 

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please show a screenshot of the trade details that show if you were the taker or the maker

**Comment by Lregent** [comment]
![image](https://user-images.githubusercontent.com/112039975/188500730-c641ca22-f15c-4cc0-a42e-32af7839d0ed.png)

**Comment by leo816** [comment]
Paid out with #1144
