### ISSUE TITLE
Fee reimbursement for trade tlrqaqnw

### ISSUE THREAD

**Issue by schick17** [bisq-network/support#1140]
I attempted to purchase bitcoin and the trade failed but the fee's and deposits were paid.  I was instructed to make a request to be reimbursed.  Thank you.

Maker: ab57669c6c5c6c433b0ab03b4c014929cfef080be217cd90d2bca6b8714fef0f
Taker: 932c186365b1ce1d094664a57a1e4e83dc25bcb7e60a9b0b26e30611c7445898
Deposit: 3efd705ef10ec688d095ad597d0ea005d8046f601166519ea533a0d7eafa69ef

BTC address for reimbursement: bc1q3d4ledw0n0m28zs2rxcmdh0h3gphqhv6h40erm

**Comment by schick17** [comment]
![image](https://user-images.githubusercontent.com/103888970/188009445-6c6d4659-6ad4-4548-9c19-148a2f83219f.png)

**Comment by schick17** [comment]
![image](https://user-images.githubusercontent.com/103888970/188009538-ffc17216-a64f-4a98-9ce5-ea5eee961ef0.png)

**Comment by schick17** [comment]
![image](https://user-images.githubusercontent.com/103888970/188009950-df0967d8-9c0b-4fc1-8bd2-5c94264857f0.png)

![image](https://user-images.githubusercontent.com/103888970/188010032-899054a1-4455-41ce-8df2-d016050e44c2.png)

**Comment by MwithM** [comment]
Edit the title to `Fee reimbursement for trade tlrqaqnw`

**Comment by leo816** [comment]
please copy and paste the deposit tx id, taker fee tx id... and the rest of information like in the rest of reimbursement requests

**Comment by schick17** [comment]
Maker: ab57669c6c5c6c433b0ab03b4c014929cfef080be217cd90d2bca6b8714fef0f
Taker: 932c186365b1ce1d094664a57a1e4e83dc25bcb7e60a9b0b26e30611c7445898
Deposit: 3efd705ef10ec688d095ad597d0ea005d8046f601166519ea533a0d7eafa69ef

BTC address for reimbursement:  bc1q3d4ledw0n0m28zs2rxcmdh0h3gphqhv6h40erm

**Comment by leo816** [comment]
payout was made correctly, reimbursement is not justified
