### ISSUE TITLE
Fee reimbursement for trade VAf1Gt

### ISSUE THREAD

**Issue by h13458** [bisq-network/support#1143]
![Screenshot from 2022-09-05 14-27-23](https://user-images.githubusercontent.com/112901072/188505554-dc6422a0-fa16-4a22-8cda-c6816498d9d3.png)

![Screenshot from 2022-09-05 14-27-46](https://user-images.githubusercontent.com/112901072/188505596-1570e495-75a8-4af0-a07f-338eb9dd44b1.png)

Maker: 43481b3b4e69ed97135db5273b0729e47c4cc6841f89b2a41bfe654eae7857c5

Taker: 6e47c69cd8e111eabaa5680c29c113020a7e2a0f01410d9626900f0f3718f336

Deposit: NA

Bisq version: v1.9.5

BTC address for reimbursement:  

bc1q78ws8nm0ymfjt6gpsd3kdmta29tex3tt75vmdn

**Comment by leo816** [comment]
Paid out with #1144
