### ISSUE TITLE
Fee reimbursement for trade 02180803

### ISSUE THREAD

**Issue by zdick** [bisq-network/support#1145]
![Snímek obrazovky (3)](https://user-images.githubusercontent.com/22180386/188838027-a33f3106-8aba-4437-ab6b-98682d1478ae.png)

Maker:  a5e13608cd2ca3e109ddb00c1d65df4fe2a9eba9b746287f812f9e00b4ee7da0
Taker: 056dfa5e7d38409bab1fbf040aacef6ea6fd76df954def5edec8a51f3539c14b
Deposit: a6be6583316251e866943cab21838d6515cc23b99b7c4e07525404e6e2a5c120

Bisq version: v1.9.5
BTC address for reimbursement: bc1q9s5my5va2d6kf8td8u7nmdug9pfrmq9f8fhf6c

**Comment by leo816** [comment]
payout was made correctly here, reimbursement request is not justified.

**Comment by zdick** [comment]
Which payout was made?
![Snímek obrazovky (4)](https://user-images.githubusercontent.com/22180386/189121465-6aebe727-ded7-417c-91f5-b623545aa4dd.png)
![Snímek obrazovky (5)](https://user-images.githubusercontent.com/22180386/189121484-8d4d9fca-32ce-413f-aab4-cc008d7bc823.png)
![Snímek obrazovky (6)](https://user-images.githubusercontent.com/22180386/189121493-f8bed04f-fc39-4ec4-b8bf-45b03983a15a.png)

**Comment by leo816** [comment]
you are right, I must have copied the wrong deposit tx id

**Comment by leo816** [comment]
payout made with #1158
