### ISSUE TITLE
Fee reimbursement for trade 2573284

### ISSUE THREAD

**Issue by lgarciaaco** [bisq-network/support#1146]
<img width="892" alt="Screenshot 2022-09-08 at 12 31 25" src="https://user-images.githubusercontent.com/8087166/189101748-068247ea-e9c5-4bbd-ba2d-46aabae1d7a1.png">

Maker: f1e3951bf8154f7ef9fba7b4227b15915f4ce0a40d5a00d541803704e65ecc54
Taker: 4ed6c84d7d2b1e1f0041d00291e981f32db1857b6eb68b839e20b47f3d17f4e0
Deposit: 9930c67ec49f8112ea15b1b331b3d4dc82c250c77e5d6e447ddc78bbe73bcf85

Bisq version: 1.9.5
BTC address for reimbursement: bc1qqlpgsl0mfw4fwxx8v04wjwhnu2zxgh9vt4aqe4

After mediation I didn't get the proposed (and accepted) compensation of 75%(0.0015 BTC). Please reimburse.
Thanks

**Comment by pazza83** [comment]
Hi @lgarciaaco thanks for the report.

Looks like you have submitted this to the DAO for compensation. Normally these trades are compensated by @leo816 

This is not one of my mediations so I imagine it would have been @leo816 that mediated this trade.

**Comment by leo816** [comment]
that is correct, the mediation proposal was made correctly (penalty to the seller in favor of the buyer) nevertheless, the seller was able to release and complete the trade without a penalty.

**Comment by leo816** [comment]
@lgarciaaco  please create the reimbursement request again and copy and paste the tx id here

**Comment by lgarciaaco** [comment]
@leo816 @pazza83 done
```
20fedd7cd1426407b9142ed2c1a9d3c6ee59ca348f36f48dd11d7aa6f31dd9ab
```

**Comment by leo816** [comment]
closing this as the reimbursement was accepted by the DAO
