### ISSUE TITLE
Fee reimbursement for trade TBT9WJA

### ISSUE THREAD

**Issue by felipesocha** [bisq-network/support#1147]
![image](https://user-images.githubusercontent.com/107418776/189126564-6400abeb-8ba5-49a2-b169-b6d311c1c9f0.png)

**Comment by felipesocha** [comment]
"offerFeePaymentTxId": "f91716d969c989df11475cf6217272b1c74443d27328294c7a708db1bbe4ac29",
 "takerFeeTxID": "0550fa16b05f184bab60de700c5467c02c58b929aa177013c77a7d817bddc937",

Adress for deposit of fee reimbursement = bc1qqumxvweh3epy9wlrgf78yg7qhymp85eyfgduq0

**Comment by leo816** [comment]
payout made with #1158
