### ISSUE TITLE
Fee reimbursement for trade iSg2t

### ISSUE THREAD

**Issue by ElMajaxBTC** [bisq-network/support#1148]
>_The iSg2t part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/95971992/191036186-5e61025c-e65c-4b61-af4b-5f1cbf89c7aa.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  4c88593d4647ed96d82354b80dd8551b0f5e0ed106d0c5c297eb1cd8db95f960
Taker: N/A - Faster Payments selected
Deposit: 74f3d3e2a837a555a66b51e7268cdb87437e79eb97afe8021f007374678be9d8

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.8.4
BTC address for reimbursement: 
bc1q4wagsxduk4ej095rfpnqjf0k38tnj49e3dgemt

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Timeout reached. Protocol did not complete in 120 sec. After making the deposit transaction - Funds deposited to be refunded to BTC address indicated above. thanks.

**Comment by pazza83** [comment]
Hi @ElMajaxBTC 

Thanks for posting.

Who was your mediator for this trade?

Are you able to repost the screen shot showing if you were the maker or taker?

Also does the screen shot show the taker / deposit transactions (even if they are blank), if so please can you post the screen shot that shows them also.

Many thanks

**Comment by ElMajaxBTC** [comment]
Please ignore my query. Thank you.
