### ISSUE TITLE
Fee reimbursement for trade 0361952

### ISSUE THREAD

**Issue by PicklErik21** [bisq-network/support#1150]
<img width="886" alt="reimbursementBisq0361952" src="https://user-images.githubusercontent.com/113917025/191327489-bf0c9e35-648a-46c5-8757-00e2548f7047.png">

Maker:  ec50ff9c3d915569b64f4028493ba9df9ae385acdb4387c42bc7d3d95850b39b
Taker: c518d17f0fd759ed2df8617effb0321702b3cd3c768bfac465748bf936acaa0e
Deposit: cb73d0c708e6d07d6dc3955014908964cb5ba67d79be5c23ab54f34b5cde5850

Bisq version: 1.9.5
BTC address for reimbursement: bc1q63sps9k6ur6lr9nh93kz8p8apen35zxcde5ka4

Other notes:
Errormessage: 
Ger: "Warnung. Fehlermeldung:Deposit transaction is null or has unexpected input count."
Eng: "Warning. Errormessage: Deposit transaction is null or has unexpected input count."

Additional screenshot after errormessage: 

<img width="570" alt="errorTradeBisq0361952" src="https://user-images.githubusercontent.com/113917025/191328849-fdda8cd2-08cd-4401-b2eb-5591c3322579.png">

Please reimburse TradeFee and advise how to proceed and if I should re-sync SPV going forward. Thank you!

**Comment by PicklErik21** [comment]
After SPV re-sync (the second time) the error seems to be gone. A little confusing. I will go ahead and finish the trade, but will leave the issue open in case it goes wrong after all.

**Comment by pazza83** [comment]
Hi @PicklErik21 

Thanks for posting.

Yes this trade ended up completing:

https://mempool.space/tx/f0adc108752732a723581a0122994861d4fd3eb14d884a3ec3ab0ee5fa31a807

No reimbursement is needed.
