### ISSUE TITLE
Fee reimbursement for trade HFstLrCl

### ISSUE THREAD

**Issue by zealot-9gate** [bisq-network/support#1152]
![image](https://user-images.githubusercontent.com/114029696/191368405-0f167b9d-5fb6-4853-bcb4-48f17a00946b.png)

Maker:  a339ad59c007ccbb52344b965fa50134a127748aacd613c2a23438405f7006c0
Taker: 4a24c66324a6e5a57f69f8608ef592d1219a5ac756388243da23e4ddab455146
Deposit: N/A
Delayed: 05d4b42030ce0f1f9268b9b9a4b5c8679a87c56b8f2833e5efa12180d37063a4

Bisq version:
![image](https://user-images.githubusercontent.com/114029696/191368555-08586bb0-987c-45fa-9cf1-828525ab1f2e.png)

BTC address for reimbursement:
bc1qfymyk0ncrnsndj46mam5p5dazf00tx3vhrx4tg

Other notes: "Timeout reached. Protocol did not complete in 120 sec."

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by zealot-9gate** [comment]
![image](https://user-images.githubusercontent.com/114029696/194700744-66958691-bb86-448c-95b9-b9215ba07f89.png)
Hey @pazza83 sorry, here it's the top info

**Comment by pazza83** [comment]
Hi @zealot-9gate 

Thanks for providing.

I can see you have lost miner and trade fees on this trade.

@leo816 please can you add to your list for reimbursements

**Comment by leo816** [comment]
payout made with #1158
