### ISSUE TITLE
Fee reimbursement for trade u6eby

### ISSUE THREAD

**Issue by fymp** [bisq-network/support#1153]
![timeout](https://user-images.githubusercontent.com/109087111/191590243-47e991e8-64d4-47c0-9d8c-4ce263123208.png)

Maker:  b646d3a39f203b99295057f2c749d6876b757901e9b54505c6d1e93772d21b3c
Taker:4247dc35a60cb12ce29c572b084ef4a267ffb85980733ef2e22552a33f950ce7
Deposit:N/A

Bisq version:1.9.5
BTC address for reimbursement:bc1qxhrmf4hhd65tt8n09j34gu37zncf0kqyfwd09w

Other notes:Timeout reached. Protocol did not complete in 120 sec. Please reimburse fees. Thanks.

**Comment by pazza83** [comment]
Hi @fymp 

Please can you post a more complete screenshot showing if you were the maker or taker.

**Comment by fymp** [comment]
![updated_screenshot](https://user-images.githubusercontent.com/109087111/194545468-ae7a334d-a35d-42b3-88fa-c0444f2f0795.png)
Yes, here is the updated screenshot.

**Comment by pazza83** [comment]
Thanks @fymp 

I can see that you have lost miner and trade fees on this trade.

@leo816 please can you add this to your list of reimbursements.

**Comment by leo816** [comment]
payout made with #1158
