### ISSUE TITLE
Fee reimbursement for trade n8chkmb

### ISSUE THREAD

**Issue by eurodiablo** [bisq-network/support#1154]
SCREENSHOT HERE

<img width="879" alt="image" src="https://user-images.githubusercontent.com/114872514/193464632-ef77fc14-f987-4cae-8ed3-50ae9bd4c567.png">

Maker:  b674ffc2ff211b35818b65ff74f3ef9e90f9fe738ae90e8c208f117149ff725d
Taker: b95f435e212846c4efa1b91b4ae7e676de92bc95d76ad28e914dd98285928593
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.5
BTC address for reimbursement: bc1qz6rrpdaspavxempxe5p8n3ej5l64efnayudp63

**Comment by pazza83** [comment]
Hi @eurodiablo 

Thanks for posting this.

This trade failed. No BTC was sent to the multisig.

As you were the maker of this trade it should still be available for taking. Therefore you will not have lost any funds on this trade. You can check your open offers for trade ID: n8chkmb
