### ISSUE TITLE
Fee reimbursement for trade 49892

### ISSUE THREAD

**Issue by czechpartisan** [bisq-network/support#1155]
[sceenshot](https://user-images.githubusercontent.com/115089565/194075098-021cfa32-e5f1-4a65-8e39-c695da25177b.png)

Maker:  fad176eb4801ba1371595c17a5f0a72afee75cac6b8a556d56b6a1f53f771033
Taker: ec4d00735b27a51580522c4aee85771d2e0d89fe4afbb33eceadb9b4986254d0
Deposit: N/A

Bisq version: 1.9.5
BTC address for reimbursement: bc1qzk46mt7vf8908gxtyx7l2n3xgm9zjsh6he0gkp

Error message: Timeout reached. Protocol did not complete in 120 sec.

Please reimburse funds. Thank you.

**Comment by pazza83** [comment]
Hi @czechpartisan thanks for posting this.

I can see you have lost trade and mining fees on this trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
payout made with #1158
