### ISSUE TITLE
Fee reimbursement for trade 4dGwqJ

### ISSUE THREAD

**Issue by n0thingpersxnal** [bisq-network/support#1157]
<img width="1311" alt="Screenshot 2022-10-08 at 13 57 09" src="https://user-images.githubusercontent.com/108984803/194726893-971bb955-bf4f-4af5-9635-9073b6c8e689.png">

Maker:  40adb08bfcc0d4609572237b1589282178743b208d5c9abf6c57503c6d347ad6
Taker: e039ff0dc269be0be5f1ef9b51ebefe2d99b6822bb9146b8e65276f32c0eeb60
Deposit: 44afeb83088d49373233dccce7725acb76f48e6b1da5316996e0ab220009455a

Bisq version: v1.9.5
BTC address for reimbursement: bc1qwquu9g9jevxu6jz2udgntvefzmfzfeh990kqq5

Other notes: "The deposit transaction (the 2-of-2 multisig transaction) is missing.
Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make
a request to be reimbursed the trade fee. Feel free to move this trade to failed trades."

**Comment by leo816** [comment]
taker fee not found, therefore reimbursement is not justified
