### ISSUE TITLE
 Failed transaction help needed; fee reimbursement for trade KZFJR

### ISSUE THREAD

**Issue by AncientOaks** [bisq-network/support#1160]
>_The XXXXX part are a random string generated with the command `date | shasum | cut -b-6`._

Description:
I had a timeout error on a transaction submit.  I don't know if I have paid a fee or what state this is in.  Never had this issue before so I'm a bit lost.  Is a credit due for a fee?  Is the transaction still open/valid?

started_at_UTC:
<_yyyy-mm-dd hh:mm_

Bisq version:
1.9.5

Device or machine:
Linux 

SCREENSHOTS HERE
![image](https://user-images.githubusercontent.com/115735213/195671144-eca5109c-32e8-4d5d-8f93-2861bca5c0ad.png)

Other notes:

**Comment by pazza83** [comment]
Hi @AncientOaks 

As you are the taker in this instance and their is no taker transaction you did not lose any trade or mining fees on this trade.

Is your wallet showing the correct balance?

If not you should do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file)
