### ISSUE TITLE
Fee reimbursement for trade WTFEFKD

### ISSUE THREAD

**Issue by scott687** [bisq-network/support#1161]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

Hi all.  I'm new to Github and Bisq and will do the best here that i can.  Thanks for your patience.
When i took the offer, the app took a good 10 to 20 seconds to verify that the offer was still valid.  After inputting all data, and providing the security BTC from my Bisq BTC wallet, it returned a failed error.  Not knowing anything different, I took the trade again with the same result.  None of my fees have been returned and the security BTC is still reserved.  No sure if it is relevant, but i did make an offer to buy and it closed successfully earlier in the day.

Thank you for your assistance. 
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/115853137/195964588-94d7fbf8-d147-4126-93e7-d46c1c24a5d0.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.5
BTC address for reimbursement: bc1qrgvfjgmq99j6q788t2zfxxjfjt52xeaw50v532

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @scott687 

As you are the taker in this instance and their is no taker transaction you did not lose any trade or mining fees on this trade.

Sounds like your wallet is out of sync.

Please do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file) and you should see your correct balance including the amounts shown as missing for the above trade.
