### ISSUE TITLE
Fee reimbursement for trade 54653081

### ISSUE THREAD

**Issue by tmpuser-bisq-trading-fee-refund** [bisq-network/support#1162]
![Screenshot_2022-10-17_01-30-29](https://user-images.githubusercontent.com/115961078/196073511-51a51973-e2ea-4c78-8061-96f13c938621.png)

Maker: cc6c2ca1c370aac389cae610ea63cef92180806c0c942b38b441412b1a86bf45
Taker: ace731573dc20dbd0e22a19602591ae6c2d1daedf18dc801e6682a66d08534b9
Deposit: N/A

Bisq version: 1.9.4
BTC address for reimbursement: bc1q9n3r6q9nztk74zd7njum4c8jp5z2xhdfyj85cz

Other notes: Offer taker to buy Bitcoin. After sending a funding payment from my Electrum wallet, my Tor connection dropped amid clicking the `Review: Take offer buy Bitcoin` button then this screen just stuck for 10+ minutes until I restarted Bisq. After restarting Bisq, I got the funding amount unlocked (0.07504660 BTC) except the trading fee (0.0044 BTC), which was paid according to the error that indicated me to create the reimbursement issue here, hence I would like to get a refund for the 0.0044 BTC trading fee.

**Comment by pazza83** [comment]
Hi @tmpuser-bisq-trading-fee-refund 

Thanks for posting.

I can see you lost mining and trade fees on this failed trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
payout made with #1170

**Comment by tmpuser-bisq-trading-fee-refund** [comment]
I've been only refunded the mining fee (0.00064838 BTC) however the trading fee wasn't refunded that is still being withheld by Bisq. Note that both trade fee and mining fee were confirmed by @pazza83 in their [previous comment](https://github.com/bisq-network/support/issues/1162#issuecomment-1287504859) to be refunded:  

> @pazza83:
> I can see you lost **mining and trade fees** on this failed trade.

I am still awaiting for a trade fee refund (0.0044 BTC that went to `38bZBj5peYS3Husdz7AH3gEUiUbYRD951t` from my [transaction](https://blockchair.com/bitcoin/transaction/ace731573dc20dbd0e22a19602591ae6c2d1daedf18dc801e6682a66d08534b9)). Reopening the issue.

**Comment by tmpuser-bisq-trading-fee-refund** [comment]
I've been only refunded the mining fee (0.00064838 BTC) however the trading fee wasn't refunded that is still being withheld by Bisq. Note that both trade fee and mining fee were confirmed by @pazza83 in their [previous comment](https://github.com/bisq-network/support/issues/1162#issuecomment-1287504859) to be refunded:  

> @pazza83:
> I can see you lost **mining and trade fees** on this failed trade.

I am still awaiting for a trade fee refund (0.0044 BTC that went to `38bZBj5peYS3Husdz7AH3gEUiUbYRD951t` from my [transaction](https://blockchair.com/bitcoin/transaction/ace731573dc20dbd0e22a19602591ae6c2d1daedf18dc801e6682a66d08534b9)). 

@leo816 please reopen this.

**Comment by tmpuser-bisq-trading-fee-refund** [comment]
I've been only refunded the mining fee (0.00064838 BTC) however the trading fee wasn't refunded that is still being withheld by Bisq. Note that both trade fee and mining fee were confirmed by @pazza83 in their [previous comment](https://github.com/bisq-network/support/issues/1162#issuecomment-1287504859) to be refunded:  

> @pazza83:
> I can see you lost **mining and trade fees** on this failed trade.

I am still awaiting for a trade fee refund (0.0044 BTC that went to `38bZBj5peYS3Husdz7AH3gEUiUbYRD951t` from my [transaction](https://blockchair.com/bitcoin/transaction/ace731573dc20dbd0e22a19602591ae6c2d1daedf18dc801e6682a66d08534b9)). 

@leo816 please reopen this.

**Comment by tmpuser-bisq-trading-fee-refund** [comment]
I've been only refunded the mining fee (0.00064838 BTC) however the trading fee wasn't refunded that is still being withheld by Bisq. Note that both trade fee and mining fee were confirmed by @leo816 and @pazza83 in their [previous comment](https://github.com/bisq-network/support/issues/1162#issuecomment-1287504859) to be refunded:  

> @pazza83:
> I can see you lost **mining and trade fees** on this failed trade.

I am still awaiting for a trade fee refund (0.0044 BTC that went to `38bZBj5peYS3Husdz7AH3gEUiUbYRD951t` from my [transaction](https://blockchair.com/bitcoin/transaction/ace731573dc20dbd0e22a19602591ae6c2d1daedf18dc801e6682a66d08534b9)). 

This issue needs to be reopened because it's unsolved.

**Comment by tmpuser-bisq-trading-fee-refund** [comment]
I've been only refunded 0.00064838 BTC meanwhile the total amount of refund should be 0.0044 BTC. 

From my transaction of 0.07946990 BTC you can see that 0.0044 BTC went to `38bZBj5peYS3Husdz7AH3gEUiUbYRD951t` which belongs to Bisq and is a known address used to handle fees.

I don't know what exactly those 0.0044 BTC were calculated for since it neither seem to be a trading fee or a mining fee, but there is a fact that Bisq charged it for something, probably erroneously.

This issue needs to be reopened because it's unsolved.

**Comment by tmpuser-bisq-trading-fee-refund** [comment]
I've been only refunded 0.00064838 BTC meanwhile the total amount of refund should be 0.0044 BTC. 

From my [transaction](https://blockchair.com/bitcoin/transaction/ace731573dc20dbd0e22a19602591ae6c2d1daedf18dc801e6682a66d08534b9) of 0.07946990 BTC you can see that 0.0044 BTC went to `38bZBj5peYS3Husdz7AH3gEUiUbYRD951t` which belongs to Bisq and is a known address used to handle fees.

I don't know what exactly those 0.0044 BTC were calculated for since it neither seem to be a trading fee or a mining fee, but there is a fact that Bisq charged it for something, probably erroneously.

This issue needs to be reopened because it's unsolved.

**Comment by tmpuser-bisq-trading-fee-refund** [comment]
I've been only reimbursed 0.00064838 BTC (a mining fee) meanwhile a total amount of this reimbursement should be 0.0044 BTC.

From my [transaction](https://blockchair.com/bitcoin/transaction/ace731573dc20dbd0e22a19602591ae6c2d1daedf18dc801e6682a66d08534b9) of 0.07946990 BTC it's clear that 0.0044 BTC went to 38bZBj5peYS3Husdz7AH3gEUiUbYRD951t which belongs to Bisq and is a known address used to handle fees. 0.0044 BTC is a taker's part of the trading fee ([0.88%](https://bisq.wiki/Trading_fees)) paid by me, given that the total trade's amount is 0.50 BTC. 

@pazza83 also confirmed in their previous message that both trading and mining fees were to be refunded:

> @pazza83
> [...]
> I can see you lost **mining and trade fees** on this failed trade.
> [...]

This issue needs to be reopened because it's unsolved.

**Comment by ghost** [comment]
ISSUE RESOLVED

**Comment by MwithM** [comment]
@leo816 check if 0.0044BC from trade fees were not paid.

**Comment by leo816** [comment]
@tmpuser-bisq-trading-fee-refund thank you for spotting it out, will reimburse the remaining on the next cycle

**Comment by leo816** [comment]
paid out with #1198
