### ISSUE TITLE
Fee reimbursement for trade y7SoEe

### ISSUE THREAD

**Issue by pali00008** [bisq-network/support#1163]
![image](https://user-images.githubusercontent.com/116119360/196539883-608f404a-4f5e-4c1b-a3ad-b2b9ee17aab7.png)

Maker:  e4846fcde1284431ee7ebeb1546d6ec337f138cc5c375d0ca091186fd0db929c
Taker: dba51574a4ae2f3d9e5079aa1ced4bd1ec61a1762e9bd063a803d04238b78310
Security deposit: Buyer: 0.0010 BTC / Seller: 0.0010 BTC
Mining fee: Maker: 0.00002450 BTC / Taker: 0.00009087 BTC

Timeout reached. Protocol did not complete in 120 sec. Please reimburse fees.

Bisq version: Bisq-64bit-1.9.5.deb
BTC address for reimbursement:
bc1qlcvuutsq34sau0kzfvrfrtcx09xu2kgahc488n

**Comment by pazza83** [comment]
Hi @pali00008 

Thanks for posting.

I can see you lost mining and trade fees on this failed trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
payout made with #1170
