### ISSUE TITLE
Fee reimbursement for trade eapxll

### ISSUE THREAD

**Issue by dav1dpgit** [bisq-network/support#1166]
Failed trade (I was taker) after 120 second time out
![image](https://user-images.githubusercontent.com/60247151/197369046-36971957-6cc5-4b4f-934e-34e239f82846.png)

**Comment by pazza83** [comment]
Hi @dav1dpgit as you are the taker and there was no taker transaction you have not lost any trade or mining fees on this trade.

**Comment by dav1dpgit** [comment]
Was there a lost bsq transaction?  That was what I was applying for reimbursement.

**Comment by pazza83** [comment]
No, the maker paid miner and trade fees.

You as the taker came to take the trade. For some reason the transaction did not go through. This means no transaction occurred at your end. Therefore no BSQ trade fees, or mining fees were spent by yourself.

This should tally with your Funds > Transactions screen     

Also you BSQ wallet transactions.

**Comment by dav1dpgit** [comment]
Understood

Thank you for making that clear
