### ISSUE TITLE
Fee reimbursement for trade DOTWEW

### ISSUE THREAD

**Issue by emisolo** [bisq-network/support#1167]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
<img width="868" alt="Screen Shot 2022-10-26 at 17 08 48" src="https://user-images.githubusercontent.com/16525537/198064267-f22f7d82-3ef3-46e1-a109-5a901ec2502d.png">
![Uploading Screen Shot 2022-10-26 at 17.08.48.png…]()

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  b9e49006345f78e294d3b4ea3c1e69a27f874ac77bb6ef11a0a0f17a23759f5f
Taker: 256794b3a1c36d3635f20395fddd4ad6f49b1a80e636640ca073a947daf27b41
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.5
BTC address for reimbursement: 121uUgFRXwkhffzWiVWni6RKeDwLshRYA6

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @emisolo as there was no deposit confirmation your offer should still be available. Therefore, you should not have lost any miner or trade fees for this trade.
