### ISSUE TITLE
An error occurred at task: MakerProcessesInputsForDepositTxRequest

### ISSUE THREAD

**Issue by rotch101** [bisq-network/support#1171]
Description:
Received an error message:
An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=149293011
makersPrice=147080789

What caused this? How do I prevent this? How do I withdraw reserved funds? Thank you for any help you can offer!

started_at_UTC:
10 Nov 2022 00:20:11

github-issue:
>_Please provide a reference issue number to which this case is related. If there isn't one go ahead and create that issue first._

Im sorry, I dont understand what this is asking of me. This is what Bisq recommends me to do:
![image](https://user-images.githubusercontent.com/117872901/200971799-50b4203c-a490-4371-8b9e-b8e262f64cfa.png)

Bisq version:
1.9.6

Device or machine:
Windows 10

SCREENSHOTS HERE
![image](https://user-images.githubusercontent.com/117872901/200972031-b0b2718a-5e78-4cff-bbc4-9a68be046520.png)

solution:

Other notes:

**Comment by jmacxx** [comment]
It means your software and your trading peer's software could not agree on the market price at the time.  One of Bisq's price servers may have been stuck using an old price.

Not to worry, the trade just failed to start. None of your funds were sent anywhere, and you should still see them in your Bisq wallet (Funds -> Transactions).  You can send your funds from there at any time.
