### ISSUE TITLE
Fee reimbursement for trade pcA74w

### ISSUE THREAD

**Issue by user9102** [bisq-network/support#1173]
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/91982756/201447933-b077577c-1718-4827-bb3a-5d59fbb808fe.png)

Maker: f3529870631c396798814ee11d55109da407a3941c0c67e8086c843a6aa6f0d0
Taker: d599680e56424a75deada5c8a95a762f168621225bfbe191c3bbbed5539a9dd7
Deposit: 3fb77e91d5fb6aa9e657cf8e306acb21532c87af42b84821fb0e24c7f86e67dc

Bisq version: 1.9.6
BTC address for reimbursement: bc1q8hd5epycykunuznrf6wpmzaxe3wvfu2tt3gqxs

Other notes: Deposit transaction failed.

Log:

Raw deposit transaction as hex:
01000000000102d79d9a53d5bebbc391e1fb5b222186162f765aa9c8a5adde754a42560e6899d50100000000ffffffffd0f0a66a3a846c08e8670c1c94a307a49d10551de14e819867391c63709852f30100000000ffffffff01fa70350000000000220020bda4ef92f044beeb8eb1b6ada1d859cdb85159f7f19e51d18bd63f622b2928540248304502210092d6b01ced29c0a11ee7e33a605f0ecd7bca3e4ffc905fbf9a2046f03681ae660220022dc0329d815bc5130d24e0bf519443afc8f2f2a1635cb3943892d3124e4c13012102cef64951902be6fc1203e545f0a78bfa9ddf08b7f686d8638a9fa37725e2c47e0247304402207aa0895ea6227eb8f4911cde73ed53990f39f9a53032afcfed4012980ee4bcb7022019d0c853527d0b0b7ff367833e0804afe210e6e6ce1f262d7f2822028c2888170121030e7060c909b6021fd550611679fc80f89e325c78a15a9c64b655f09304ebe90700000000

**Comment by pazza83** [comment]
Hi @user9102 

Many thanks I can see you lost miner and trade fees for this trade.

@leo816 please can you add to your list for reimbursements.

**Comment by leo816** [comment]
paid out with #1198
