### ISSUE TITLE
Fee reimbursement for trade RMIUKPLR-179b1257-38fe-46b6-8752-50ff0909b5ab-196

### ISSUE THREAD

**Issue by luismagh** [bisq-network/support#1174]
RMIUKPLR
<img width="887" alt="Captura de Pantalla 2022-11-14 a las 16 07 54" src="https://user-images.githubusercontent.com/39332559/201694440-793fc3d4-1584-4f86-bad7-4a959bd80f3a.png">

Maker: ctc3suwkvguwkhvkmj6bun4ievb6oa6j3sxqbw45ix72zl6q6xedpxqd.onion:9999

Taker:
Deposit: 0,01

Bisq version: 1.9.6
BTC address for reimbursement:  bc1q266yym84dj64f40hz2ydv9smhmcm0y24ppga2k

>_Provide the Bisq client version to help developers identify the causing issue._

**Comment by pazza83** [comment]
Hi @luismagh 

You were the taker for this trade.

Please can you post the Taker transaction ID.

**Comment by luismagh** [comment]
This is my taker transaction
ID: d6a4e4567e956cf089e3d87e073da915273b289d6bf53063de4c58aa7145aba2
Thanks in advance.

*Luis *

**Comment by pazza83** [comment]
hi @luismagh 

The taker ID you provided is different from the one shown in the screen shot for trade ID: RMIUKPLR

Please can you provide the one in the screenshot.

Thanks

**Comment by luismagh** [comment]
I already got a resolution through bisq (with a big delay.. but finally it
came). SO thanks for everything but I think now could be settled.
Thanks so much.

*Luis *

**Comment by luismagh** [comment]
[image: Captura de Pantalla 2022-11-22 a las 16.49.03.png]

I don really know exactly what do you want, but here you have the
screenshot and the two ID data:

ID creater: ba7c81876285b78e82d9a3a0c6f3ed1841cd8a36827b47357f9b76538beec799
ID taker:  d6a4e4567e956cf089e3d87e073da915273b289d6bf53063de4c58aa7145aba2

*Luis *
