### ISSUE TITLE
Fee reimbursement for trade SVEJDXHQ

### ISSUE THREAD

**Issue by PatVers** [bisq-network/support#1176]
![captura](https://user-images.githubusercontent.com/66955857/202027303-fabd9833-dc80-438c-bf4e-7b355badb9ab.png)

Maker: a8631649d278763261fcbd42c742209b22faf80e19e12696d3176134689163ef
Taker: 39901ceab2afa1791fa23291c54d35700cfc03aadceb968933dafcdb83aa03c7
Deposit: 913deafcdbf6d841f713403131d1867ead3d6c4e4433c5f8c47578d8458c318e

Bisq version: 1.9.6
BTC address for reimbursement: bc1qvjt8x7dkc5usej36znwfkglt5pqq9upzyqtyef

Other notes: Deposit transaction failed

**Comment by pazza83** [comment]
Hi @PatVers  thanks for posting.

I can see you lost mining and trade fees.

@leo816 please can you add to your list for reimbursement.

Many thanks

**Comment by leo816** [comment]
Payout made with Batch Reimbursement #1198
