### ISSUE TITLE
Fee reimbursement for trade 95170511

### ISSUE THREAD

**Issue by Chordbridge** [bisq-network/support#1177]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/18390838/202134966-8caa9bd2-00d7-4ed6-9f58-84993dd4a34b.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ed3b08f8cbe8597f6c7ece4859db40044612bb42ebf3412400324603c9e3113d
Taker: none
Deposit: none

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Contract as json:
{
  "offerPayload": {
    "id": "95170511-6fd611fd-ba34-4176-b45e-8da7cfc1e6f0-195",
    "date": 1668515740955,
    "ownerNodeAddress": {
      "hostName": "jc4bjmxzvwwp5qaiqskl223lgissed2zvuflohdahgxeafnelqspiuqd.onion",
      "port": 9999
    },
    "direction": "SELL",
    "price": 0,
    "marketPriceMargin": 0.077,
    "useMarketBasedPrice": true,
    "amount": 3050000,
    "minAmount": 3050000,
    "baseCurrencyCode": "BTC",
    "counterCurrencyCode": "USD",
    "arbitratorNodeAddresses": [],
    "mediatorNodeAddresses": [
      {
        "hostName": "6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion",
        "port": 9999
      },
      {
        "hostName": "7hkpotiyaukuzcfy6faihjaols5r2mkysz7bm3wrhhbpbphzz3zbwyqd.onion",
        "port": 9999
      }
    ],
    "paymentMethodId": "CLEAR_X_CHANGE",
    "makerPaymentAccountId": "a672575c-dd81-4982-aead-f65719cea81e",
    "offerFeePaymentTxId": "ed3b08f8cbe8597f6c7ece4859db40044612bb42ebf3412400324603c9e3113d",
    "versionNr": "1.9.5",
    "blockHeightAtOfferCreation": 763278,
    "txFee": 13648,
    "makerFee": 43,
    "isCurrencyForMakerFeeBtc": false,
    "buyerSecurityDeposit": 1443870,
    "sellerSecurityDeposit": 1443870,
    "maxTradeLimit": 25000000,
    "maxTradePeriod": 345600000,
    "useAutoClose": false,
    "useReOpenAfterAutoClose": false,
    "lowerClosePrice": 0,
    "upperClosePrice": 0,
    "isPrivateOffer": false,
    "extraDataMap": {
      "capabilities": "0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17",
      "accountAgeWitnessHash": "628577150d21309571e41c493fcbdc4379bc3425"
    },
    "protocolVersion": 4
  },
  "tradeAmount": 3050000,
  "tradePrice": 183033639,
  "takerFeeTxID": "0bfcdd10cf6b4091305e5c85784070cbcad82955a14d6695630adbf0465d178f",
  "buyerNodeAddress": {
    "hostName": "52hcifl7n7tu4eum3b5ksvk3z2tu6uuu6wyu6zgg4vvhas5hvchhruyd.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "jc4bjmxzvwwp5qaiqskl223lgissed2zvuflohdahgxeafnelqspiuqd.onion",
    "port": 9999
  },
  "mediatorNodeAddress": {
    "hostName": "6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion",
    "port": 9999
  },
  "isBuyerMakerAndSellerTaker": false,
  "makerAccountId": "376890014",
  "takerAccountId": "472073998",
  "makerPayoutAddressString": "bc1q38uj5ftxzn03flpn4stxe6g5yylk5f7ruqx5k9",
  "takerPayoutAddressString": "bc1qvf4gyn8ac4adr5suc86lp7xaz0lj0htkc5peuf",
  "lockTime": 766188,
  "refundAgentNodeAddress": {
    "hostName": "3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion",
    "port": 9999
  },
  "hashOfMakersPaymentAccountPayload": [
    34,
    -25,
    -69,
    19,
    -85,
    -12,
    -83,
    0,
    -56,
    28,
    -98,
    -34,
    87,
    22,
    -24,
    45,
    72,
    13,
    -41,
    122
  ],
  "hashOfTakersPaymentAccountPayload": [
    -73,
    84,
    -51,
    -57,
    112,
    -128,
    5,
    -102,
    -75,
    126,
    97,
    97,
    -77,
    -75,
    -60,
    -57,
    24,
    -15,
    73,
    20
  ],
  "makerPaymentMethodId": "CLEAR_X_CHANGE",
  "takerPaymentMethodId": "CLEAR_X_CHANGE"
}

Other detail data:

BuyerMultiSigPubKeyHex: 02b0b0905c02bb27be62fd25405f4011bb4cba3df5c47c383beb93f1b8467b8f7b
SellerMultiSigPubKeyHex: 03b3a2b5c7f5be50ac06bc92f98bc4f92eac12bd0da52fdd21ed2d6f565655b02c

BuyersAccountAge: Payment account age not known.
SellersAccountAge: Payment account age not known.

Selected mediator: pazza83
Selected arbitrator (refund agent): refundagent2Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @Chordbridge 

Thanks for posting.

As you were the taker and there is not taker transaction your trade will still be available for someone to take.

You have not lost any funds on this trade.

Let me know if you have any questions.
