### ISSUE TITLE
Fee reimbursement for trade RbSmbv

### ISSUE THREAD

**Issue by jpfzn** [bisq-network/support#1180]
RbSmbv

![image](https://user-images.githubusercontent.com/118642146/202878517-7538c723-409c-4f10-9ebb-cdfb2e7d307a.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  9b9870524da4b76b3e27b89a9e3fb647f38593b4dc96fcb85a013793e67c7e0d
Taker: 5116b1bdf16eb8d8ff83fa647813b4d85b551c54ca49159e20953b4575b955a8
Deposit: 154f4ddeaf69b85dbcda9291de011fcbc0f5260bdcaf63fc345920516bf32ffd

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: V1.9.5
BTC address for reimbursement: bc1qmecw08x63zdeumvmsda2nqxpp6638gpgr7srse

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:
Attention
The trade protocol encountered some problems.
The deposit transaction (the 2-of-2 multisig transaction) is missing.
Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: [1]

Attention
The trade protocol encountered a serious problem.
The deposit transaction (the 2-of-2 multisig transaction) is missing.
Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: [1]
Feel free to move this trade to failed trades.
>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Payout made with Batch Reimbursement #1198
