### ISSUE TITLE
Fee reimbursement for trade KKFCB

### ISSUE THREAD

**Issue by plzsolveproblem** [bisq-network/support#1181]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/118666171/202900560-816238fd-41e9-4a09-b307-9fd372b6d290.png">

Maker: bf22f4b69a47d92abc938282a5b4a5bdf09721962a83e289b21ed38b52cf635d
Taker: 98ce0db5c40053657e774aeacf58957c3c436b171157f834f914867f448a88ac
Deposit: 2f4f1c1aa0db224138b6831b3115b9fbe2c2e8768f775b626dbb1fb76b42f1d5

Bisq version: 1.9.6
BTC address for reimbursement: bc1qeh9t8gr5fezrs6l75xrndqjk6qx2k5t0d4jzvz

Other notes:
Deposit transaction was never broadcasted. After 10h got the error that the trade timed out / failed. Suspecting mempool congestion or hardware issue (had to reboot machine due to some OS problem) and rebuilt the SPV.

**Comment by pazza83** [comment]
Hi @plzsolveproblem thanks for posting.

I can see you lost mining and trade fees.

@leo816 please can you add to your list for reimbursement.

Many thanks

**Comment by leo816** [comment]
paid out with #1198
