### ISSUE TITLE
Fee reimbursement for trade QIFVWATB

### ISSUE THREAD

**Issue by danileca** [bisq-network/support#1183]
<img width="676" alt="bisq" src="https://user-images.githubusercontent.com/118264362/203658223-4f7665e3-c794-439f-a04a-860231003f6d.png">

Maker:  6486d0fe33eea359e836d8f621b70fcfc57a1532861e5cc81634fed94285c5ea
Taker: a18aa8b41234597cb53d9782db6b372086e1034d2ea5ec5c89249961217a83e4
Deposit: 37166875e7fca9cad86cc94042034b06241a43a5db0e238ee0f70d2b11173cc1

Bisq version: 1.9.5
BTC address for reimbursement: bc1qt27p579ru8s5q2z52wgm9wrx8plgq6zwqmecnn

Attention
The trade protocol encountered some problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: [1]

Feel free to move this trade to failed trades.

**Comment by pazza83** [comment]
Hi @danileca 

I can see you lost miner and trade fees.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
paid out with #1198
