### ISSUE TITLE
Fee reimbursement for trade 41536

### ISSUE THREAD

**Issue by khagler** [bisq-network/support#1184]
<img width="901" alt="Screenshot 2022-11-28 at 5 09 59 PM" src="https://user-images.githubusercontent.com/1522554/204400043-b34b3fa9-17f0-4efa-bdc6-5a9e8f81dbf3.png">

Maker:  5302a4e5283b9c3f2619979fca2953f85129f556ca66148ed56450ceb3195a6c
Taker: dbf2231342fa42bbc8c5d26c53422dd402d5c9c4a0c0817440697f681f73a020
Deposit: 1422350e2f3c7b0696bb76c9c57121ba8670ef59036ea62848487cfa87f7abd4

Bisq version: v1.9.6
BTC address for reimbursement: bc1q75f243h0gdztpatl5hv68a2lpkn8e979wczgmv

Other notes:

Attention
The trade protocol encountered some problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: [1]

Feel free to move this trade to failed trades.
[https://github.com/bisq-network/support/issues]

**Comment by leo816** [comment]
taker payout tx not found, therefore your funds never left your wallet and reimbursement is not justified

**Comment by khagler** [comment]
Thanks for the clarification. Perhaps it would be advisable for the app to check for this scenario before telling users about making a reimbursement request?
