### ISSUE TITLE
Fee reimbursement for trade yhqfamml-31aa1b3e-c6d6-4ec6-ab20-e287d97b9a37-196

### ISSUE THREAD

**Issue by TheTotalConnector** [bisq-network/support#1185]
![Unbenannt](https://user-images.githubusercontent.com/50043671/205039387-6e603391-1df7-483c-b4bb-8055ee9f4c28.JPG)
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by TheTotalConnector** [comment]
Sorry, not familiar with this reimbursement form. Can you just reimburse my trading fee due to an unforeseen error.

**Comment by TheTotalConnector** [comment]
Maker Fee Tx ID: 677d18ed8dc32ec50dcb3ed4a11b630d0a78f19c6cfe3cbd6247dbb2b1ad72d9
Taker Fee Tx ID: 0f44f29dcfefc6576693f08b06c9d16f02ed29b5b483ed01704cdb3d0c758266

Other infos missing. See screenshot, please. 

Reimbursement BTC address: bc1qc26u7ajzu8rtsexvre9845nkmfwaqrf74s3lck

Thanks!

**Comment by leo816** [comment]
taker fee not found therefore your funds never left your wallet and reimbursement is not justified
