### ISSUE TITLE
Fee reimbursement for trade 457117

### ISSUE THREAD

**Issue by exitramp505** [bisq-network/support#1187]
![Screen Shot 2022-12-03 at 3 02 11 PM](https://user-images.githubusercontent.com/119704679/205459705-1ea7172a-c2b7-424e-9f68-2c2cc90c5d55.png)

Maker:  7e81ceec6927838385118a49d58aa4c4e4d523bad6982bf581bb447d183f855e
Taker: e04a42493316ca9d50a5be9e9127eba72b7d1a1a2a506ce2ea4178cf27d779da
Deposit: NA

Bisq version: 1.9.6
BTC address for reimbursement: bc1qz89zz56sxctzkvkawyzfejr4hxlsnjc3kha9je

Other notes: I was the Maker

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @exitramp505 as you were the maker for this trade and there is no deposit transaction your offer should still be available for someone to take. 

So you have not lost any funds on this trade.
