### ISSUE TITLE
Fee reimbursement for trade 457117

### ISSUE THREAD

**Issue by tamrolyat** [bisq-network/support#1188]
<img width="890" alt="Screenshot 2022-12-03 at 1 38 11 PM" src="https://user-images.githubusercontent.com/119762902/205463208-0b494c8e-0c6f-4409-a1b5-cf5d7a44bc1d.png">

Maker:  7e81ceec6927838385118a49d58aa4c4e4d523bad6982bf581bb447d183f855e
Taker: e04a42493316ca9d50a5be9e9127eba72b7d1a1a2a506ce2ea4178cf27d779da
Deposit: N/A

Bisq version: 1.9.3
BTC address for reimbursement: bc1qeej9t394eycl2clvhnd0wa8jdw68f54ey6h4v8

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @tamrolyat thanks for opening the issue.

I can see you lost miner and trade fees on this failed trade.

@leo816 please can you add to your list for remibursement.

Many thanks
