### ISSUE TITLE
Fee reimbursement for trade vpcfq

### ISSUE THREAD

**Issue by nolim13** [bisq-network/support#1191]
![image](https://user-images.githubusercontent.com/72128378/206993990-ca0200a1-f223-4cb3-9ea8-e1ce80740f55.png)

![image](https://user-images.githubusercontent.com/72128378/206993590-bd620d87-ffed-4add-8b3b-3a356cbecce4.png)

![image](https://user-images.githubusercontent.com/72128378/206993716-24685bf5-e869-4d4f-a1a4-9abbf04d94ed.png)

Maker:  3f36b6f73b444f47bab7f4b8beb763db77cc094bdc904de9e9ec34079d219c01
Taker: ...........
Deposit: ..........

Maker:  b04aad5ef23e7a2270caee67661e460d1e7acc3bfed6e8207ee16622583aed2a
Taker: ...........
Deposit: ..........

Maker:  8e790fc2100fd730e4c3d7cca3bb545ceda1bf7a8c87350fedb3aacc7f3618be
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.6
BTC address for reimbursement: bc1qvjdsjc5v6hevmwjwrm6rpnlj7vgfrgz35vqvey

Other notes:

Duplicating offers, I created 3 times a trade with the same trade ID but different maker trading fees. Logs and details were sent to a dev for bug fixing.

**Comment by leo816** [comment]
paid out with #1198
