### ISSUE TITLE
Fee reimbursement for trade WJQBGHk

### ISSUE THREAD

**Issue by forbes340** [bisq-network/support#1194]
![image](https://user-images.githubusercontent.com/120720620/208082494-9689099e-2c05-42e2-958c-d9e8d06cdd66.png)

Maker:  d6f34f01d639a209edc7ec9251774519f3b24db9fe7276f3fcd21e7da6399e7c
Taker: 6f80eff6fdc1be95f5aec10aae55abbd4a1af22924376e16c001a603d7d25eb5
Deposit: a327beb4057d0023d1c6447b2d2e48c30281137b791a8d51525b229250457deb

Bisq version: 1.9.6
BTC address for reimbursement: bc1q4426s9m7w6egzmlqnw6x50snwf7zfsmmvce5p8

**Comment by leo816** [comment]
taker fee tx not found. Therefore your funds never left your wallet and a reimbursement is not justified
