### ISSUE TITLE
Fee reimbursement for trade QGUZM

### ISSUE THREAD

**Issue by forbes340** [bisq-network/support#1196]
![image](https://user-images.githubusercontent.com/120720620/208085871-42944555-aa33-4505-bbcd-274a33958a15.png)

Maker:  db84976831f0368c3aeb30ad28cf59e535fce2a9796b782ababb002fd24f661f
Taker: f6df68ddc9d437c9af200dc43ee35dcfdec00472fea9c7e042960399847c2769
Deposit: de08879a221b98f1fb1329b9adb4da4430abf14f03ebd34d0fb0f359f151ceca

Bisq version: 1.9.6
BTC address for reimbursement: bc1q4426s9m7w6egzmlqnw6x50snwf7zfsmmvce5p8

**Comment by leo816** [comment]
taker fee is invalid therefore a reimbursement is not justified
