### ISSUE TITLE
Fee reimbursement for trade 36306181

### ISSUE THREAD

**Issue by SusiSan1** [bisq-network/support#1197]
![1](https://user-images.githubusercontent.com/120753028/208188171-9f0d486f-8bd7-4d41-b04d-f699ad6a6ed1.png)

Maker:  d6eea0ece5102cf76e6dce2340c100897360795b6869e15ace648512d8b6ad76
Taker: 3de889b6066cafbd3b1232b86bbb42193f3e7a6ee7056759fbb103b4637de24d
Deposit: N/A

Bisq version: v1.9.6
BTC address for reimbursement: bc1qxx04ma0hlzw53xx8red4z9u96fyf7j039un9se

Other notes: I was Taker

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
paid out with #1198
