### ISSUE TITLE
Fee reimbursement for trade WqckOtsn

### ISSUE THREAD

**Issue by bieber-t-beaver** [bisq-network/support#1199]
**Screenshot has PII**

My role: BTC seller (maker)

Maker fee txid: 34e47292693f011dec0a4e5181cc177e75a101c621bc23754f70dc4e4bb0f833 [confirmed]
Taker fee txid: 4a45e6a5a4aa1480ed6640b37641c97234aa5e7e95261787c9966ee6a4a974fd
Deposit txid: 438b9c09cc062cd0ac1a9336d480831205d79f63a6ccfd8919c61767868e7549
[**FAILED to post to network**]

Bisq version: v1.9.6
BTC address for reimbursement: 1P7d9uGGniBT8W7GaoW4cpwLzLDsYHYw4e

Other notes:
Initiated support ticket, with @leo816.

**Comment by leo816** [comment]
please post a screenshot of the trade details

**Comment by bieber-t-beaver** [comment]
![Wqck0tsn](https://user-images.githubusercontent.com/107782777/210189043-524a87bd-8a82-4acb-83c2-e40175ad94e4.jpg)

**Comment by leo816** [comment]
paid out with #1298
