### ISSUE TITLE
Fee reimbursement for kvsomcba

### ISSUE THREAD

**Issue by keo-bisq** [bisq-network/support#120]
<img width="759" alt="kvsomcba" src="https://user-images.githubusercontent.com/33939632/41285127-97574132-6e3b-11e8-9c79-398d916fbfb9.png">

ab78a9f263d9f27497a6d74c4341cffcf7ae6f68ebf38cc7eb8ec11f621394fb

**Comment by cbeams** [comment]
Maker transaction fees will be reimbursed in #101.
