### ISSUE TITLE
Fee reimbursement for trade w0h2wc

### ISSUE THREAD

**Issue by havingfun2023** [bisq-network/support#1200]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

![2022-12-27_11-36-58](https://user-images.githubusercontent.com/121514499/209708882-59021140-6cae-48de-bf61-fcd7fd2498d9.jpg)

Maker:  a2080b0938b96ce877d4d0790754d933d169fc00cb0ba983ec16f5e58b4fcb9c
Taker: N/A
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1qyy83tcl3nj737ut62jxacskrxmx8zxst5w0r99

Other notes:
"An error occurred at task:  "Exception message: Insufficient money,  missing 0.00214426 BTC" Please reimburse fees.
Thanks.
>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please show a complete screenshot of the trade details
