### ISSUE TITLE
Fee reimbursement for trade 53031775

### ISSUE THREAD

**Issue by nolim13** [bisq-network/support#1206]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/72128378/210130752-1c2024b0-598f-4274-b9c6-826efbdb4057.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  3a9c6d937bfdc9bd28de2db830f708b4f63e6b4bc9efa2bbe7ac8a4d40c1287c
Taker: 953a48aae4d05edf5f606f55f2d6292ff6162b5e3b9d44a8bdac8488094e82cb
Deposit: 1b43467f0203aa952732d9a7d2ed18dc9a349b947d9231cf0a2de37d1f6e9cc3

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.8
BTC address for reimbursement: bc1qckerg0vww8kad0xr35k9l4dxl3ngmv4ercvp6u

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Trade sent to failed trades, deposit tx not broadcasted. Maker fee paid with BSQ.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by HenrikJannsen** [comment]
See https://github.com/bisq-network/support/issues/1205#issuecomment-1372468096

**Comment by leo816** [comment]
On this case he is the maker and therefore this is eligible for reimbursement, @HenrikJannsen let me know if i'm missing something

**Comment by HenrikJannsen** [comment]
Only maker fee is for reimbursement: 0.43 BSQ
https://bisq.mempool.emzy.de/tx/3a9c6d937bfdc9bd28de2db830f708b4f63e6b4bc9efa2bbe7ac8a4d40c1287c

As taker fee tx and deposit are invalid no funds have left makers wallet beside the small fee.

Not sure if < 1 USD trade fee reimbursements are worth the effort...
