### ISSUE TITLE
Fee reimbursement for trade jdwwj

### ISSUE THREAD

**Issue by madis** [bisq-network/support#1210]
![Screenshot from 2023-01-02 08-46-22](https://user-images.githubusercontent.com/674621/210246899-016fdf33-416b-4117-bcf3-3c462a0586fd.png)

Maker:  `ce5795875f55057cee137f68c30f6480671f17006c3fbad2d33de50fe35333e5`
Taker: `f801ba6dbc0810ab7e900d5be5aa26f24c9421ef5e5adeee689d5be51b74172a`
Deposit: ..........

Bisq version: `1.9.8-1`
BTC address for reimbursement: `bc1qhu8ppehh8hdxdgltx6tvh9xymjphaz266l5wle`

**Comment by leo816** [comment]
paid out with #1298
