### ISSUE TITLE
Fee reimbursement for trade qjefuhv

### ISSUE THREAD

**Issue by BielSalvador** [bisq-network/support#1211]
![2023-01-02 (2)](https://user-images.githubusercontent.com/121811363/210248585-f1652e56-728d-4ed3-993f-47c25b65ef7c.png)

Maker:  a522f475c5f64181fc7e9b61bc16f885efd0bfd8caa41d5bc95bce8a5582f88e
Taker: 4c4fc2a9a4b3195fd839b34d1d56c3318a161e73b23e7f53c37e66ce57fd630f
Deposit: N/D

Bisq version: v1.9.8
BTC address for reimbursement: [bc1q7fsdtksxr8gxgk2qjnkw2t67wgfp3m78p35f75]

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
paid out with #1298
