### ISSUE TITLE
Fee reimbursement for trade 68385

### ISSUE THREAD

**Issue by BielSalvador** [bisq-network/support#1212]
![2023-01-02 (3)](https://user-images.githubusercontent.com/121811363/210249678-f5d18458-314a-4228-a366-6eccfe05aa60.png)

Maker:  96d0015dd7a361ab7c908deab424c7beff54899a54bc99123158cdbc95d54f97
Taker: 1aaeb11510cd13f6a0712356d5ce4f57ec4a5651d288a94aa443e0a1383a495f
Deposit: N/D

Bisq version: v1.9.8
BTC address for reimbursement: bc1q7fsdtksxr8gxgk2qjnkw2t67wgfp3m78p35f75

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
paid out with #1298
