### ISSUE TITLE
Fee reimbursement for trade zxrad

### ISSUE THREAD

**Issue by chiefrocca1** [bisq-network/support#1213]
![image](https://user-images.githubusercontent.com/42627443/210256187-3f8f8968-e364-4e35-adc1-76fb2f8cb7cc.png)

Maker: 7f3713f2f4866e08b5cfada719f678ba17152a756ae2328bb9e505f01d9e6eba
Taker: c63c12a7a30f6dd17d56a633e94c4eeb71b3cb0019beddb465a56ceb5837f8ea
Deposit: N/D

Bisq version: v1.9.8
BTC address for reimbursement: bc1q8c2ae0ahuny98gamzkcnscm8xafu2998zhn9mx

Other notes:

**Comment by kryptosader** [comment]
Will this reimburse both sides of the trade?

**Comment by leo816** [comment]
paid out with #1298
