### ISSUE TITLE
Fee reimbursement for trade OANKM

### ISSUE THREAD

**Issue by chiefrocca1** [bisq-network/support#1214]
![image](https://user-images.githubusercontent.com/42627443/210255861-c7f961d5-e434-4025-8db1-f505503f30a2.png)

Maker: c57baeee530e2ae17e3dacef68aa9df1383dcb25cad1396b081549c93934a1e1
Taker: ff69eba3a26e484fd6f3eeb5263b03d11bf86c5b8c38d8466d9afdcf7d0b9671
Deposit: N/D

Bisq version: v1.9.8
BTC address for reimbursement: bc1q8c2ae0ahuny98gamzkcnscm8xafu2998zhn9mx

**Comment by kryptosader** [comment]
Does this reimburse both sides of the transaction?
It looks like my security deposit 0.003btc is also missing.  Is that normal when this happens?

/home/bitsader/Pictures/Screenshot from 2023-01-02 10-36-12.png

**Comment by kryptosader** [comment]
Indeed, my 0.003 btc security deposit is still missing after failed transaction.... my "wallet balance" is different from "available balance"

![Screenshot from 2023-01-02 12-15-41](https://user-images.githubusercontent.com/121820827/210271347-c6b5debd-6dfe-431f-a12d-29e8e46bf7f8.png)

**Comment by kryptosader** [comment]
after restarting bisq, it appears my 0.03btc deposit has been restored.

**Comment by culvereric3** [comment]
I am having this issue with every trade. How do I fix this?

**Comment by uskrusader** [comment]
> I am having this issue with every trade. How do I fix this?

It seems to be happening a lot lately.  I'm told a new version will be released very soon....hopefully it takes care of this issue

**Comment by kryptosader** [comment]
DAO state
Your node is in consensus with the seed nodes. Some of your peers are not in consensus.

**Comment by kryptosader** [comment]
[BisqLogsArchive_20230105_085828.zip](https://github.com/bisq-network/support/files/10353659/BisqLogsArchive_20230105_085828.zip)

**Comment by jmacxx** [comment]
@chiefrocca1 it would be really helpful to get your logs in the same way as provided above by your trade peer to see what's going on with the current trading issues.  Thanks!

**Comment by uskrusader** [comment]
Kryptosader is the one who posted his logs.  The OP did not post logs yet.

**Comment by leo816** [comment]
paid out with #1298
