### ISSUE TITLE
Fee reimbursement for trade UHSPuf

### ISSUE THREAD

**Issue by BielSalvador** [bisq-network/support#1218]
![2023-01-02 (5)](https://user-images.githubusercontent.com/121811363/210267581-8f8c239a-22b9-4946-aa5a-a935df486168.png)

Maker: 34d50a2f0203ce6101aeeb120b3c831f7d83b7cb90a8881db287e5f94801c853
Taker: ec8199a818842591bd5f6ea1890c426b6c7c96b47f7140203ccbbde971900824
Deposit: N/D

Bisq version: v1.9.8
BTC address for reimbursement: bc1q7fsdtksxr8gxgk2qjnkw2t67wgfp3m78p35f75

Other notes:
Today, January 02, 2023, I tried to buy BTC three times, but in all trades the same error occurred.

**Comment by leo816** [comment]
paid out with #1298
