### ISSUE TITLE
Fee reimbursement for trade hnqsk

### ISSUE THREAD

**Issue by georgeorwell23** [bisq-network/support#1220]
![hnqsk](https://user-images.githubusercontent.com/108611713/210268655-d5da61ac-41f9-4c0f-b7e1-f785fddc83c6.png)

Maker: d4601d3e2a9673bb47a1480f12491eb425b11bb78aa6a1af94198f9156a2a89a
Taker: fae4c3d556c80ab2dc8ad6b6c5d1081ec339dd721e71b87288854a62f6b1923e
Deposit: N/D

Bisq version: v1.9.8
BTC address for reimbursement: bc1q36g7q5mzt66474md2ay72yahf7tdgke9rwnnwsnp559gug7ntnvq4rjezr

**Comment by leo816** [comment]
paid out with #1298
