### ISSUE TITLE
Fee reimbursement for trade wqbnd

### ISSUE THREAD

**Issue by Krvopije** [bisq-network/support#1222]
![Bildschirmfoto vom 2023-01-02 19-44-29](https://user-images.githubusercontent.com/34864681/210269077-3fcf9765-07c5-4adb-9f50-b1ae9d80bc34.png)

Maker:  446f6ad7a854f5f9ac36d4cbbecfbdd651f2730d93e1f86a59eceb9aafe93a2b
Taker: 0fdde20f7317a6b21d8b41972f5b9259bdb4d4d8115f4db67eae3ea7f66b16df
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1q7x2lg0reehhvx8h3r6h3elpuh3c7uddj7l0fup

**Comment by leo816** [comment]
paid out with #1298
