### ISSUE TITLE
Fee reimbursement for trade ycliu

### ISSUE THREAD

**Issue by mably** [bisq-network/support#1223]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/385653/210274157-34b67316-db95-435e-95ec-26c5a3563ccf.png">

Maker:  0ff2327c7988a9b9df11b4b5ce1a7ff0f0918d8706258e07dd2982d14f86849f
Taker: 7a85082b29fda5b9384af7a550050d9003a5bde1df58f8096e08a65c09486dfd
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1qav4l8nrauawalxjayldvuh247kckju8s29rt58

**Comment by leo816** [comment]
paid out with #1298

**Comment by mably** [comment]
@leo816 will this issue be deleted?
