### ISSUE TITLE
Fee reimbursement for trade SIymr

### ISSUE THREAD

**Issue by fupm** [bisq-network/support#1224]
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/76731476/210287665-3a658401-d12f-4f4c-9667-9eb950205494.png)

Maker:  ccd980bcf472713b8d2dc76ce851022334149775c41019241e949fa86879f18d
Taker: f29f617a1155637e7f49eb6bb94390d99aa2266340c200e4230abaf25224bd38
Deposit: ..........

Bisq version: 1.9.8
BTC address for reimbursement: bc1qkxlh0xr943uthgh9gwvmal0mzw79gax7nmwat7

Other notes:

**Comment by leo816** [comment]
paid out with #1298
