### ISSUE TITLE
Fee reimbursement for trade 22725882

### ISSUE THREAD

**Issue by culvereric3** [bisq-network/support#1225]
![image](https://user-images.githubusercontent.com/66539613/210287657-fb9c7074-3656-4192-b9a7-6ca60be733aa.png)

Maker:  a33dacb70086d4fe546156e4e35262cf870f239b60e979ec1a3e3d23e8b14fd7
Taker: f2a3a6c2583d48627d6128bc07a30d6621b46a43f4082bb9290075529e2ae9c8
Deposit: N/A

Bisq version:  V1.9.8
BTC address for reimbursement:  bc1qdvyfu0y9t27kgh386v74xxks90djp644vh4l5z

**Comment by leo816** [comment]
resync your DAO state and update to the newest version

**Comment by leo816** [comment]
paid out with #1298
