### ISSUE TITLE
Fee reimbursement for trade ngbtzo

### ISSUE THREAD

**Issue by iujzvbc** [bisq-network/support#1227]
![image](https://user-images.githubusercontent.com/40712918/210386292-f0ded115-fb6f-4b4a-8ba0-a78baebd93d4.png)

Maker:  ec45d09fb903c39fe9c60e1f85cac15cef6cd79441364f80ad4611efdf4a9251
Taker: 7e65c2fc699bbb9c4c4b02f35212e74c8548eae2556bf4b43d57742eca8dffcf
Deposit: none displayed

Bisq version: 1.9.8
BTC address for reimbursement: bc1qnt5qhjk6767hznndewc7zh9hanmu7te2vjf4wk

**Comment by leo816** [comment]
paid out with #1298
