### ISSUE TITLE
Fee reimbursement for trade ukmlna

### ISSUE THREAD

**Issue by kryptosader** [bisq-network/support#1228]
![Screenshot from 2023-01-03 08-30-01](https://user-images.githubusercontent.com/121820827/210388868-6aad9cc5-320e-45ab-bc4b-6fc48489e13a.png)

Maker:  58a211922a3d253c278cd4450581d90b1b27928ce7c9547dc3f7ed04b6dae908
Taker: b52a588f977c8e9bcb5820839a38c02e56f8920c304e837ea36e51912bb9de7d
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1qq608pgdnlwvpg63z56ah3zamas6l005vsp3z29

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by kryptosader** [comment]
DAO state
Your node is in consensus with the seed nodes. Some of your peers are not in consensus.

**Comment by leo816** [comment]
did you resync your DAO state?
