### ISSUE TITLE
Fee reimbursement for trade 51957144

### ISSUE THREAD

**Issue by roofey** [bisq-network/support#1229]
Looks like transaction has been accepted by someone else just few moments ago...

![image](https://user-images.githubusercontent.com/25032676/210413481-fc0b6ecd-be55-4daf-a0df-76270b769d43.png)

Maker:  4e2a977832bab44c8024d58162c2751123b809cab62d24c6140129d9d447521f
Taker: 3ad18d4e95bba407a24301ab4103500e0a7b121950b2e9e422c56452e0f95584

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

Bisq version: v1.9.8

BTC address for reimbursement: bc1qpluaml24fkllu8n94wucnv03y4akrq83dc45sk

**Comment by leo816** [comment]
paid out with #1298
