### ISSUE TITLE
Fee reimbursement for trade 9548493

### ISSUE THREAD

**Issue by haromz** [bisq-network/support#1231]
![CleanShot 2023-01-03 at 20 40 54@2x](https://user-images.githubusercontent.com/14028407/210421047-274ed2d2-99ae-474c-92bc-5a1069dcec86.png)

Maker:  ee571339c0df90fb4fc492f054f4de67c9cdc6c639a16affbf16c5c7e3c146e2
Taker: 4d02e249a37d09d3bc578e9f5b936adc8b6252d28a396f83b52d1db9685ce8cd
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1qqmjq6cm764vlx886t6j3zlp55x9dydn6sr9d84

Other notes:

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

**Comment by jmacxx** [comment]
Hi, would it be possible to provide your `bisq.log` to see what went wrong with this trade?
In Bisq: Account -> Backup -> `Zip Log Files` will make a zip file containing your logs and open its directory.

Also could you go to DAO -> Network Monitor and tell us what it says for `DAO State`.

**Comment by haromz** [comment]
Hi @jmacxx I attached the logs from the failed trade and screenshot from the DAO state
![CleanShot 2023-01-05 at 10 51 42@2x](https://user-images.githubusercontent.com/14028407/210739708-4fa0f058-2e1c-4930-99c4-b8e5bcdcc06c.png)
[bisq_log.txt](https://github.com/bisq-network/support/files/10350712/bisq_log.txt)

**Comment by HenrikJannsen** [comment]
From the logs there is nothing visible. It could be that the DAO was not in sync at take offer time either by @haromz or by the trade peer. If @haromz can provide more complete log history we could look further. Also if mediators can get logs from trade peer it would be helpful for further investigation.

**Comment by haromz** [comment]
What do you mean by nothing visible? The logs says:
`Task runner failed with error An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx`
 and 
`We got an onSuccess callback for a broadcast which already triggered the timeout. txId=4d02e249a37d09d3bc578e9f5b936adc8b6252d28a396f83b52d1db9685ce8cd`

This is the transaction id of the fees leaving my wallet but the trade failed. It is clearly an error or a bug of the bisq software if this can happen. How can something be broadcasted to the blockchain which was timed out earlier and the whole trade to fail, but the fees leave the wallet?

**Comment by leo816** [comment]
paid out with #1298
