### ISSUE TITLE
Fee reimbursement for trade w8GWk

### ISSUE THREAD

**Issue by AlexdeGraaff** [bisq-network/support#1232]
<img width="673" alt="Failed" src="https://user-images.githubusercontent.com/115416344/210441399-8e3531ca-4afe-4969-8ca9-4f15d3ce9242.png">

Maker: e5693119d5d3c3394f68a53fc63a08e90cb79d84e4f587f11a6d324275344b51
Taker: 590a723981123179b98319a15e61eaf86b8e024483f377e27d0a5022fe44ee40
Deposit: N/D

Bisq version: v1.9.8
BTC address for reimbursement: bc1qg8x93dz0dx2qxhk79ywzvavxnxzv794xklwzzgjtrkmme7uaxnhs24lk0a

**Comment by jmacxx** [comment]
Hi, would it be possible to provide your `bisq.log` to see what went wrong with this trade?
In Bisq: Account -> Backup -> `Zip Log Files` will make a zip file containing your logs and open its directory.

Also could you go to DAO -> Network Monitor and tell us what it says for `DAO State`.

**Comment by leo816** [comment]
paid out with #1298
