### ISSUE TITLE
Fee reimbursement for trade HJUJSUT

### ISSUE THREAD

**Issue by lost-in-gatlin** [bisq-network/support#1233]
![image](https://user-images.githubusercontent.com/121902194/210441138-582a17e3-8f28-420b-bf42-8fdf2f36781b.png)

Reimbursement for trade HJUJSUT-735a3895-4233-4bb9-b1c2-548f3a99f0ee-198

I am BTC buyer as taker for EUR.
Trade amount and asset: 0.01 BTC for 164 EUR
Deposit amount: 0.001513 BTC

Maker:  bd4c841a270a2a23388be2d41e765fd3bc63918fb99cd1d9cb404395ae96a5ee
Taker: 45dd4e2c47ea4d4da7d964aa0ec4bb48c22ca8bb188a180537449ded61e5bc80
Deposit: ---
Delayed payout: ---

Reimbursement amount: 1.04 BSQ
Reason for reimbursement: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

BTC address for reimbursement:
bc1q7g4ae53vyn3cs3qyclvkl33yevrrsx3c8xayjq

Bisq version:
1.9.8

**Comment by leo816** [comment]
reimbursements are done in btc, please provide a btc address

**Comment by lost-in-gatlin** [comment]
I changed the amount and address to BTC in the opening post. Thanks.

**Comment by leo816** [comment]
Reimbursement made with #1341
