### ISSUE TITLE
Fee reimbursement for trade dteq0l

### ISSUE THREAD

**Issue by fupm** [bisq-network/support#1234]
SCREENSHOT
![image](https://user-images.githubusercontent.com/76731476/210449067-9df37713-ab16-47c0-9fbc-e0045c9a4a1b.png)

Maker:  48aa479c9544794d0e239ced18ed2df35b195783b2b302615a8ede282229be26
Taker: b4bd86583dce5ad1d774d2e4c82b879472b24c486589fc7b162f1f9ef34921ed
Deposit: ..........

Bisq version: 1.9.8
BTC address for reimbursement: bc1qkxlh0xr943uthgh9gwvmal0mzw79gax7nmwat7

Other notes:

**Comment by leo816** [comment]
paid out with #1298
