### ISSUE TITLE
Fee reimbursement for trade HZpYRNpm

### ISSUE THREAD

**Issue by georgeorwell23** [bisq-network/support#1235]
![HZpYRNpm](https://user-images.githubusercontent.com/108611713/210449981-e5b3741a-8f46-4b96-9a3b-6b95bd054983.png)

Maker: bc85f4b2e32b9f4167bc54ab3c9b2b4afbe8d317dba467eda92f6b989ebdb946
Taker: 1414f7af98ff2482b005b0d8b41366f51044922187061e8cc2ab4df416322968
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1qj8ykpn54hktm926ecaqvfcxfj0tck80skqczp4znazkpu6daw2tsyy4zfu

**Comment by leo816** [comment]
paid out with #1298
