### ISSUE TITLE
Fee reimbursement for trade ixubrfl

### ISSUE THREAD

**Issue by georgeorwell23** [bisq-network/support#1237]
![ixubrfl](https://user-images.githubusercontent.com/108611713/210450903-35181a13-2c46-49f6-871e-9427cb8fbfad.png)

Maker: a7fc9b7d957de0d7444219badb5da4dfafced30f9681f077baca89bdce07dcbe
Taker: 99dd6a1b7481c71500d1f2616135c9988ea2b3b9336b3fbf7c59744ae156c1f6
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1q3ld7mvn6tpmh4dztl24cdngc8pzx83gtggtes74uazngmh770lcqa4meml

**Comment by leo816** [comment]
paid out with #1298
