### ISSUE TITLE
Fee reimbursement for trade abjm5esv

### ISSUE THREAD

**Issue by jodacg** [bisq-network/support#1239]
![Bisq trade error](https://user-images.githubusercontent.com/121907582/210456070-12305d6d-2292-4def-8361-fdad3cef9c01.jpg)

Maker: 825a2b441ef1660762563706dfa16829e5374bef04c1b73e3ab1fb8e12de0992
Taker: N/D

Bisq version during trade: v1.9.7
Bisq current version: v1.9.8 
BTC address for reimbursement: bc1qj28xv3wskkj0ecqn9k3mrwmc9ypeqxegekh0uj

**Comment by leo816** [comment]
taker fee not found, therefore not eligible for reimbursement
