### ISSUE TITLE
Fee reimbursement for trade LKbOiP

### ISSUE THREAD

**Issue by SuperManNotAmI** [bisq-network/support#1240]
![image](https://user-images.githubusercontent.com/121919849/210485560-71f1ccfc-2f1d-4922-aa16-671b59587733.png)

Maker:  aabc54440fccd4aaf96b4b4a29622dd395a28f6deb6b423ef1916b5ed30936af
Taker: 19342ce28c5341eb5ab74e1520ef7cf9a9242f2456f3f84ac7b2a3fa818596f3
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1qwr43krjvau9cy8907ptn0cxnv8uyzjlx7s4puy

Other notes: I am the Maker

**Comment by leo816** [comment]
paid out with #1298
