### ISSUE TITLE
Fee reimbursement for trade 24287

### ISSUE THREAD

**Issue by BLTCCS** [bisq-network/support#1241]
24287 fee reimbursment
![image](https://user-images.githubusercontent.com/112088187/210553088-f12f49db-43fd-4f17-af1b-6fdf7428f28c.png)

Maker: add9f1caee60d196759fb1fc353e31d9d090a006a803c3bda8a70ecd0cd54a31
Taker: 9a9765c59e94d6352bb9fa2c9fe7a013f40e55cd512c778189f4522cfd815f60

Bisq version: 1.9.8
BTC address for reimbursement: bc1qwews2fkugj0ch4n06d3rnddny90v3z6htxlj47

Detailed data:
[BISQ Detailed data 24287.docx](https://github.com/bisq-network/support/files/10343967/BISQ.Detailed.data.24287.docx)

I have an issue with BISQ over past days, reported under #6499: Task TrustedListenableFutureTask@b5b5126[status=PENDING, info=[task=[running=[NOT STARTED YET], 
-can this be connected?

Please reimburse the fees

**Comment by leo816** [comment]
paid out with #1298
