### ISSUE TITLE
Fee reimbursement for trade qjefuhv

### ISSUE THREAD

**Issue by felipesocha** [bisq-network/support#1242]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/107418776/210554714-fcada4fa-6076-4d8f-a16f-949e116f1950.png)

Maker:  a522f475c5f64181fc7e9b61bc16f885efd0bfd8caa41d5bc95bce8a5582f88e
Taker: 4c4fc2a9a4b3195fd839b34d1d56c3318a161e73b23e7f53c37e66ce57fd630f
Deposit: ..........

Bisq version: v1.9.8
BTC address for reimbursement: bc1qkgnwee64x5zy4hcy6q9j94padyhzadhvycfrmc

Other notes:

**Comment by jmacxx** [comment]
Could you go to DAO -> Network Monitor and tell us what it says for `DAO State`?

**Comment by felipesocha** [comment]
Your local node is in consensus with the network

![image](https://user-images.githubusercontent.com/107418776/210795534-7b38cef1-80f5-47e1-a5c2-baea59c768bb.png)

**Comment by leo816** [comment]
paid out with #1298
