### ISSUE TITLE
Fee reimbursement for trade bemard

### ISSUE THREAD

**Issue by BLTCCS** [bisq-network/support#1243]
bemard fee reimbursment

![image](https://user-images.githubusercontent.com/112088187/210554526-6702839d-6161-4efe-9c51-552d596fe69c.png)

Maker: 92f5aca36730949c863cbeb3354f3be4ebfd807e0bd11205e11e598ca0feae1b
Taker: 577d71769639aadea015daeff8ff109403c223ed7b144971df650183904a6853

Bisq version: 1.9.8
BTC address for reimbursement: bc1q6vrnnz38gu4j3ux8lkerkpmy8wj2tgudk2pkqc

Detailed data:
[BISQ Detailed data BEMARD.docx](https://github.com/bisq-network/support/files/10344005/BISQ.Detailed.data.BEMARD.docx)

I have an issue with BISQ over past days, reported under #6499: Task TrustedListenableFutureTask@b5b5126[status=PENDING, info=[task=[running=[NOT STARTED YET],
-can this be connected?

Please reimburse the fees

**Comment by leo816** [comment]
please provide a full screenshot of the trade details

**Comment by leo816** [comment]
were you the maker or taker?

**Comment by BLTCCS** [comment]
Hi, I was maker, please find the screenshot below
![Bemard](https://user-images.githubusercontent.com/112088187/212086737-b1e80c89-ee7e-4f16-8710-41ea604452d1.png)

**Comment by leo816** [comment]
Reimbursement made with #1341
