### ISSUE TITLE
Fee reimbursement for trade 05568269

### ISSUE THREAD

**Issue by btcminer002** [bisq-network/support#1245]
![image](https://user-images.githubusercontent.com/121956556/210582179-a8097c56-2853-488d-ab37-f2670570d2ec.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  89d77d24e0077034f13380adfc0bac24a2da49a099e09c31398461feba0cccc9
Taker: 7047cc5af356e85dd7ab6194cc691c9a0dcabf72c223df200e54949e6b0a74cd
Deposit: 812bb8bfda37c6041c12bf0d7fe627234cee5e70357db9ca03a7f3fcb2897ce2

Bisq version: v1.9.8
BTC address for reimbursement: 
bc1qrdk49gq5e3qnsq9a8kw6yqnrj084kt30m4akw7

Other notes:
Please reimburse my fees.  the deposit transaction never made it to the mempool.  After reloading SPV, I got this error message:

> The trade protocol encountered some problems.
> 
> The deposit transaction (the 2-of-2 multisig transaction) is missing.
> 
> Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: [1]
> 
> Feel free to move this trade to failed trades.
Thanks!

**Comment by leo816** [comment]
please provide a full screenshot of the trade details, were you the maker or taker?

**Comment by btcminer002** [comment]
I thought I did that. I was the taker. Is this what you needed?
Thanks.

[image.png]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by btcminer002** [comment]
are you still waiting on me? The initial issue had a screen shot of the details and i sent an email with it after you asked. Is that not what you needed? Please advise. thanks.

[image.png]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by leo816** [comment]
Reimbursement made with #1341
