### ISSUE TITLE
Fee reimbursement for trade xbucsx

### ISSUE THREAD

**Issue by Christian891** [bisq-network/support#1246]
![image](https://user-images.githubusercontent.com/85958076/210590057-45ecb7a6-dfab-493a-87cd-e5d302679807.png)

Maker:  5f591f76daa51ba17b9c84fe6eb043c08687ffa746d4db77d6784fdada77ff38
Taker: cb3731d9046651d3aabc1709d5f6114cacc02e57f49341c57e3849a8e555ded7
Deposit: N/A

Bisq version: 1.98
BTC address for reimbursement: bc1q8h50jzq2ny82acemj2rjxz2x8wk4r7cxzq24j3

Other notes: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

**Comment by jmacxx** [comment]
Could you go to DAO -> Network Monitor and tell us what it says for `DAO State`?

**Comment by culvereric3** [comment]
I'm having the same issue repeatedly. My DAO state is "Your local node is in consensus with the network"

**Comment by Christian891** [comment]
> 

![image](https://user-images.githubusercontent.com/85958076/210773402-2334c347-9fe4-4749-91cc-cd8d82392e93.png)

**Comment by leo816** [comment]
paid out with #1298
