### ISSUE TITLE
Fee reimbursement for trade PRGK9Y

### ISSUE THREAD

**Issue by jaque2312** [bisq-network/support#1247]
![Screenshot_1](https://user-images.githubusercontent.com/121966038/210609584-e4db6288-1197-47ea-a157-663a278d8f62.png)

Maker:  61f862b64954f2d6ce158e256d3411ef1e6ee30318338d08fde62393fc3692f9
Taker: ea9363e55f7366dfd2d6b14168f783092059e08ec64d80b952962a0357e1e53d
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: 183PDm1hNn4JcjqPH1tSMrKizdtsPrRqj6

Other notes: Timeout reached. Protocol did not complete in 120 sec.

**Comment by jmacxx** [comment]
Hi, would it be possible to provide your `bisq.log` to see what went wrong with this trade?

Also could you go to DAO -> Network Monitor and tell us what it says for `DAO State`.

**Comment by jaque2312** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/121966038/211056314-497ebbd3-0b71-4acd-aac6-fac2761617dc.png)

**Comment by leo816** [comment]
paid out with #1298
