### ISSUE TITLE
Fee reimbursement for trade PibtVuBx

### ISSUE THREAD

**Issue by jaque2312** [bisq-network/support#1248]
![Screenshot_2](https://user-images.githubusercontent.com/121966038/210614238-79716878-327f-49cf-8310-7a41919c1b4b.png)

Maker:  ecf8edd2ceb9a392fac6b333e904d841682a67bcb7b6cceb210d753c632e7ce2
Taker: 7122209723ae8c8f9cbbd0f11dd9bdd6a8398530530117e4eeabcc166fd0afe0
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: 183PDm1hNn4JcjqPH1tSMrKizdtsPrRqj6

Other notes: Timeout reached. Protocol did not complete in 120 sec.

**Comment by jmacxx** [comment]
Could you go to DAO -> Network Monitor and tell us what it says for `DAO State`?

**Comment by jaque2312** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/121966038/211056213-698a8c4e-606a-45ef-aa7e-d35c5845bc8e.png)

**Comment by leo816** [comment]
paid out with #1298
