### ISSUE TITLE
Fee reimbursement for trade 88484

### ISSUE THREAD

**Issue by Dunno259** [bisq-network/support#1249]
![image](https://user-images.githubusercontent.com/121972516/210626736-e482ef20-e242-4eb5-93f1-c56c12492730.png)

Maker:  bf409a646eb04fafcfd4cea53de86083fd348e328d33941ae4bc1d2b391f5d0a
Taker: 6a5a64aa708371ede87c00bf1b7f16d7f53b66029a5e3d8e85157abdfcd56bc0
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1qa6kgr2t3ajzhlrf6xt5k7fll0d7l900yw8h2kl

Other notes:

Error message is 

```
An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same
```

**Comment by jmacxx** [comment]
Could you go to DAO -> Network Monitor and tell us what it says for `DAO State`?

**Comment by leo816** [comment]
paid out with #1298
