### ISSUE TITLE
Fee reimbursement for trade PRGK9Y

### ISSUE THREAD

**Issue by zsojma** [bisq-network/support#1250]
![image](https://user-images.githubusercontent.com/28751135/210626758-1100de0f-cc26-4bdf-8d58-60cec81ef373.png)

Maker: 61f862b64954f2d6ce158e256d3411ef1e6ee30318338d08fde62393fc3692f9
Taker: ea9363e55f7366dfd2d6b14168f783092059e08ec64d80b952962a0357e1e53d
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1qvmfe7u2h2g0cav2tgrd564fzz0sq95x67u0g90

**Comment by jmacxx** [comment]
Hi, would it be possible to provide your `bisq.log` to see what went wrong with this trade?

Also could you go to DAO -> Network Monitor and tell us what it says for `DAO State`.

**Comment by culvereric3** [comment]
I'm having the same issue. Where do I find the log?

**Comment by jmacxx** [comment]
In Bisq: Account -> Backup -> `Zip Log Files` will make a zip file containing your logs and open its directory.

**Comment by zsojma** [comment]
Hi, here is the log:
[bisq.log](https://github.com/bisq-network/support/files/10352773/bisq.log)

> could you go to DAO -> Network Monitor and tell us what it says for DAO State.

`Your local data is not in consensus with at least one seed node. Please resync the DAO state.`

I will do the resync :)

**Comment by HenrikJannsen** [comment]
From what I saw in the logs the issue was caused because your DAO state was not in sync. It seems also that your wallet is already quite heavy (many transactions), if that is the case consider to start over with a new fresh Bisq app. Support can help you how to transfer the account data and signing state.

**Comment by leo816** [comment]
paid out with #1298
