### ISSUE TITLE
Fee reimbursement for trade H6ZKJRKL

### ISSUE THREAD

**Issue by pareto328** [bisq-network/support#1251]
![2023-01-04 13_50_00-](https://user-images.githubusercontent.com/121972201/210630737-d4c79d10-98a4-4e9b-82d7-e11f50d9cdd5.png)

Maker:  80d71d1667ecb0f8300dc32d98331e54182f9c4669ff5a00b3a78cafdc02cebb
Taker: 7777959f29f0a9ac2083ba79c4cb2c32eca80b38f3acacc13efa4723ed4c9f1f
Deposit: a33df8d3c669f947be618ff6ea74f4f9b0893a5d3569f8e20cec8eb39bef2ccf

Bisq version: 1.9.8
BTC address for reimbursement: 1BCu8gpqhszpTsm6TqeTTpDJ82pFJy3j8j
Network version: 1; P2P message version: 10; Local DB version: 1; Trade protocol version: 4

Other notes:
- Received error message: "Deposit transaction is null or has unexpected input count"
- SPV resync did not resolve
- Requesting reimbursement for Taker fee

**Comment by leo816** [comment]
paid out with #1298
