### ISSUE TITLE
Fee reimbursement for trade V7KREMZ-1d36a392-ffbd-4107-ba3b-4da94694fef2-198

### ISSUE THREAD

**Issue by floressecas** [bisq-network/support#1252]
SCREENSHOT HERE

![Screenshot (3)](https://user-images.githubusercontent.com/121909419/210660843-137eae2d-f53a-421f-930a-9a764b419512.png)

Maker:  3802f591bb5c54bd1d73d72136429be6f63f92766247a21383b6c2826a6065a9
Taker: c498b4514800e039b8348b02d1cc1dbb2bdbdf5f3e5b5c25a06735ed8ded7985
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmacxx** [comment]
Could you go to DAO -> Network Monitor and tell us what it says for `DAO State`?

**Comment by floressecas** [comment]
DAO state
Status
Your nose is in consensus with the seed nodes. Some of your peers are not in consensus

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by leo816** [comment]
no btc address for reimbursement

**Comment by floressecas** [comment]
Ok, what I have to do to get the reimbursement?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by leo816** [comment]
put a btc address, please create a new template and put all the details
