### ISSUE TITLE
Fee reimbursement for trade 58411871

### ISSUE THREAD

**Issue by kaliban93** [bisq-network/support#1253]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
![Screenshot 2023-01-04 232430](https://user-images.githubusercontent.com/121982999/210661786-19e39a5d-359d-4860-81d5-45c281f55372.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  8ff8931fe731b4fc990924b6024f6f77583181a420e8b3e83fc7e2001498d60e
Taker: 53b0b27d1ee0280f7fbccb05451be7b5eec8ba6855b40411068c9c2fcfe6d63c
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.8
BTC address for reimbursement: bc1qm2ktxcugyvydlqweaysdmkm62wcy742av3uhqp

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmacxx** [comment]
Could you go to DAO -> Network Monitor and tell us what it says for `DAO State`?

**Comment by kaliban93** [comment]
DAO state says: Your node is in consensus with the seed nodes. Some of your peers are not in consensus.

**Comment by leo816** [comment]
paid out with #1298
