### ISSUE TITLE
Fee reimbursement for trade mzi4l

### ISSUE THREAD

**Issue by culvereric3** [bisq-network/support#1254]
![image](https://user-images.githubusercontent.com/66539613/210698566-17c2047b-3452-4341-9c00-8260bad607f4.png)

Maker:  814f76c08593ed1bc79e1a4a8922b8621a5839702ac49f72def786924e97f2b5
Taker: 30a3651a3650906069bfa15019c70cdc257982a3b9aecefb7ccd48a30815cbdf
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1q24ffzult6tsw3xcdlpp2rvesuw0dzmhdmuuayy

**Comment by leo816** [comment]
paid out with #1298
