### ISSUE TITLE
Fee reimbursement for trade kjzPmL

### ISSUE THREAD

**Issue by culvereric3** [bisq-network/support#1255]
![image](https://user-images.githubusercontent.com/66539613/210699164-8cc5ec06-cd49-42c5-9b6b-30465dc47a56.png)

Maker:  b5a573f59fd342af94747a9da2078f2ef5c4622f091d1e580ec4478b82ffa2cc
Taker: 8c7a0b0d91b4e162b055e8ee48df7395524f5166ffc1132d09035a2ca12b642f
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1q24ffzult6tsw3xcdlpp2rvesuw0dzmhdmuuayy

**Comment by culvereric3** [comment]
DAO State: "Your local node is in consensus with the network"

**Comment by leo816** [comment]
paid out with #1298
