### ISSUE TITLE
Fee reimbursement for trade 082043

### ISSUE THREAD

**Issue by culvereric3** [bisq-network/support#1256]
![image](https://user-images.githubusercontent.com/66539613/210699340-36a58904-3d20-4778-a600-3f2772bcd03b.png)

Maker:  4b91821b884d69d1de309fb97eb3ad75c63fbf384044febd077e481caf5dd504
Taker: 5e5d0060eb0f4561c1fdef11cf41892b363ffe29a7905cad0b020f4dd2c12a0f
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1q24ffzult6tsw3xcdlpp2rvesuw0dzmhdmuuayy

**Comment by culvereric3** [comment]
DAO State: "Your local node is in consensus with the network"

**Comment by leo816** [comment]
paid out with #1298
