### ISSUE TITLE
Fee reimbursement for trade rsfzl

### ISSUE THREAD

**Issue by heredia21** [bisq-network/support#1259]
![Selection_001](https://user-images.githubusercontent.com/16310744/210751985-ced241c8-e3e5-41c5-9f38-363124b91d2c.png)

Reimbursement for trade rsfzl

I am BTC buyer as maker for BTC.
Trade amount and asset: 0.0142 BTC for 242 USD
Deposit amount: 0.00358266 BTC

Maker: 1648bd0aa85e6deeea3e301b9f816cafc938fd6325449e8fc37207b56c90e1c1
Taker: 1a80f01a1ebd634b957976efe5c6f98861a445ef2e6f3355334991b9e080e855
Deposit: N/A
Delayed payout: N/A

Reimbursement amount: 0.00358266

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same
Please reimburse fees.

Thanks.

**Comment by leo816** [comment]
please provide a btc address to reimburse to

**Comment by heredia21** [comment]
bc1qh5qldwrw8v3qj0e2tw0utspzvljnagykltv509

**Comment by leo816** [comment]
Reimbursement made with #1341

**Comment by heredia21** [comment]
I did not receive the proper amount.
