### ISSUE TITLE
Fee reimbursement for trade PibtVuBx

### ISSUE THREAD

**Issue by Nadumanov** [bisq-network/support#1261]
<img width="1292" alt="Screenshot 2023-01-05 at 6 46 28 PM" src="https://user-images.githubusercontent.com/55026777/210762726-96e9ae90-5949-4e0d-95f5-431bbf494709.png">

Maker:  ecf8edd2ceb9a392fac6b333e904d841682a67bcb7b6cceb210d753c632e7ce2
Taker: 7122209723ae8c8f9cbbd0f11dd9bdd6a8398530530117e4eeabcc166fd0afe0
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1qyyduwzq5mdu9jqrux4fmuwq6ylkaqw2p56yp29

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

**Comment by jmacxx** [comment]
Hi, would it be possible to provide your `bisq.log` to see what went wrong with this trade?
In Bisq: Account -> Backup -> `Zip Log Files` will make a zip file containing your logs and open its directory.

Also could you go to DAO -> Network Monitor and tell us what it says for `DAO State`.

**Comment by Nadumanov** [comment]
Current DAO status: _Your local data is not in consensus with at least one seed node. Please resync the DAO state._

I'm hesitant to post log files here tbh. Is there something particular you're looking for?

**Comment by jmacxx** [comment]
We want to see logs from both sides of a failed trade, to understand exactly why one of the tx from one trading peer differs from the other.  That is causing the current bump of failed trades.  We've had plenty of logs from one or the other sides, but not both.  For this particular trade the counterparty is #1248 and currently has not provided logs either, so its not the end of the world, perhaps some other trade users will be nice enough to help us fix the problem, or when a new hotfix is deployed its improved logging might help pinpoint the issue.

**Comment by Nadumanov** [comment]
Got it, I actually have two other failed trades (incl. an XMR one) so something's really broken. I'm resyncing the DAO state. Here are the log files
[BisqLogsArchive_20230107_122745.zip](https://github.com/bisq-network/support/files/10365509/BisqLogsArchive_20230107_122745.zip)


My other failed trades: #1278 and #1282
