### ISSUE TITLE
Fee reimbursement for trade gqdka

### ISSUE THREAD

**Issue by Sun0fABeach** [bisq-network/support#1262]
![image](https://user-images.githubusercontent.com/8113158/210789482-0b49db95-e386-4729-aa37-d2b680ba4a67.png)

Maker:  186a292428d1bc3986ada4dff8b8f3185094fe684b30e8da17482a3118e72a75
Taker: 75d41f1487ff7f7908879b3fd2413cbc0386162fd64e0ae3bd0306300abbfbe2
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1qza0z3avdty66u4hl5v5swulqajhkay883zy0cr

Other notes:
> An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
> Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

**Comment by leo816** [comment]
were you the maker or the taker? please provide a full screenshot of the trade details

**Comment by Sun0fABeach** [comment]
Hi, I was the maker.

![image](https://user-images.githubusercontent.com/8113158/211549513-9a2048ef-9d93-4f0b-bc7c-2aff98a5475e.png)

**Comment by leo816** [comment]
paid out with #1298
