### ISSUE TITLE
Fee reimbursement for trade sahkybe

### ISSUE THREAD

**Issue by asd3dsa** [bisq-network/support#1263]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![sahkybe](https://user-images.githubusercontent.com/122039605/210826955-7db8865f-4c58-434e-97d2-4558f0931a9c.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  d279dda015e2bbd91513ee83505579a4158e3f19ae2c4a3cfd75710ba7b8fe57
Taker: 16b9d7da2fcd2d4559fd77199c184a483a3e335c155e695f2fbde7950e6fbd72
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.8
BTC address for reimbursement: 1JbEYc5FUW4tePwTsLPU4Tpw57u1GgmuLf

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: This happened two times with the same taker. (1/2)

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
paid out with #1298
