### ISSUE TITLE
Fee reimbursement for trade SQWIVN

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/support#1265]
![bisq](https://user-images.githubusercontent.com/52383635/210845690-aacbc541-7194-4611-ab51-772a52b39aed.png)

Maker:  521d474eddd12c5f77a807616436d5d774a051972f7b75b515ffdf8a1094c70e
Taker: 2801795295fb5a43442052a0c9bc3a2f4f52c6a89afa19c48777e17a59102b95
Deposit: NA

Bisq version: v1.9.8
BTC address for reimbursement: bc1qfz93ee69skwmfvg27h93j5fdgx2zdjl6s88r34

Other notes: error "Timeout reached. Protocol did not complete in 120 sec."

**Comment by leo816** [comment]
were you the buyer or the seller? please provide a full screenshot of the trade details

**Comment by Drazen-V** [comment]
I'm the maker, thanks.
![bisq](https://user-images.githubusercontent.com/52383635/212077874-ab3c4ed6-264b-4aab-a43e-60fbd9984390.png)

**Comment by leo816** [comment]
Reimbursement made with #1341
