### ISSUE TITLE
Fee reimbursement for trade 00v1q2

### ISSUE THREAD

**Issue by derndaddy** [bisq-network/support#1267]
![Screen Shot 2023-01-05 at 3 30 11 PM](https://user-images.githubusercontent.com/103206086/210884058-f7aace94-5d45-44fa-a585-d54d88f789ce.png)

Maker:  7b6895bf51373cc1dbbbde84b1a914d597d6aba802330c64eb91184729619166
Taker: b40ea363b10624d6d88ac2a07c6675d0f0e33706d016edb6cf0111c043b36d07
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1qsvqqhew242yvr9w2x62lychrfxrypndqcysf4n

Other notes: "An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same"

**Comment by leo816** [comment]
paid out with #1298
