### ISSUE TITLE
Fee reimbursement for trade 30553

### ISSUE THREAD

**Issue by derndaddy** [bisq-network/support#1268]
![Screen Shot 2023-01-05 at 3 43 36 PM](https://user-images.githubusercontent.com/103206086/210886301-8ad71760-16b3-40f9-bac0-47d06f1ca4f5.png)

Maker:  bb890b2fb2c37a6b65a326ffc0ee76535a40ccadf3648f451ff51098303877a6
Taker: f872170259229c9547c78be7182c009115916cb6e8e5bc0fddb47136f0d9dee1
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1q70zpxrev7eqleje82ltcfe5r05s66sjpvvwu05sm5479lz72va2sjjx0vy

Other notes: This appears to have failed in exactly the same way as the trade I tried to make before, this time as taker.
"An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same"

**Comment by leo816** [comment]
paid out with #1298
