### ISSUE TITLE
Fee reimbursement for trade 97112038

### ISSUE THREAD

**Issue by iandundee** [bisq-network/support#1274]
![Screenshot 2023-01-06 at 01 32 54](https://user-images.githubusercontent.com/122066656/210912404-e7744aae-b672-4781-b260-d8be2732ea1a.png)

Maker:  1ef3eb87fcd9a2ebc89e8e5db9d391e6390915f46d99158732643748cf2f4922
Taker: 60b3f5a508e2d9f72840159b60595a1c0f55bd5c75387965591b21667b9774c0
Deposit: 0.001

Bisq version: 1.9.8
BTC address for reimbursement: bc1qt5hq2h7c74tvuckygs54zh98c0td0snyfqqpes

**Comment by leo816** [comment]
paid out with #1298
