### ISSUE TITLE
Fee reimbursement for trade ondbmo

### ISSUE THREAD

**Issue by Truffle3280** [bisq-network/support#1275]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/122084488/210963248-13b3f01b-98d7-4efc-a1cf-d5996dab3cc0.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  c8d97b1d25f9f9e29f7df11b651c07fefe500528f18d743791ba8404aa077edc
Taker: 0da4d5c4f3051e3ed86eea9987e21bc22043d62800ec69ab4f325e0dd048e196
Deposit: 0.001125

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.8
BTC address for reimbursement: bc1q4zqavfq4zvu6jtn5pparq3pxmwrxfercwdtu58

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by Truffle3280** [comment]
Hi, I am wondering why I only got 16600 sats, shouldn't I receive 112500 sats from this tx security deposit?

**Comment by jmacxx** [comment]
You paid 2700 sats in miner fees and 6600 sats in trade fees.  I don't know why you were overpaid.

Security deposits do not leave your wallet unless sent to a valid 2-of-2 trade multisig, which is not the case.

Please look in your Bisq wallet (under Funds menu) to follow where your deposit went.

According to [mempool.space](https://mempool.space/tx/3:846df9510325b2cf22495b06430bba5ad672c734cd1f9bfdf7937c89ca09b653), it was used in a subsequent trade.

**Comment by Truffle3280** [comment]
Got it, thanks!
