### ISSUE TITLE
Fee reimbursement for trade 38206

### ISSUE THREAD

**Issue by Truffle3280** [bisq-network/support#1276]
![image](https://user-images.githubusercontent.com/122084488/210964628-c9bc89cd-ec11-41d7-bc88-c170857c4037.png)

Maker:  12bb310d257e845c4ffea0a291edc9877bc6861cb9ea452d22417d51dfbf26b9
Taker: f83c4b0686447cd4b40c104e6a8231e161f36704f4a160b27c0df3fb53946cc5
Deposit: 0.002703

Bisq version: 1.9.8
BTC address for reimbursement: bc1q4zqavfq4zvu6jtn5pparq3pxmwrxfercwdtu58

**Comment by leo816** [comment]
paid out with #1298

**Comment by Truffle3280** [comment]
Hi, I am wondering why I only got 16600 sats, shouldn't I receive 270300 sats from this tx security deposit?

**Comment by jmacxx** [comment]
You paid 2275 sats in miner fees and 5000 sats in trade fees.  I don't know why you were overpaid.

Security deposits do not leave your wallet unless sent to a valid 2-of-2 trade multisig, which is not the case.

Please look in your Bisq wallet (under Funds menu) to follow where your deposit went.
Hint: it is [here](https://mempool.space/address/bc1qlm6dwz94jumyy9j9dn7pw06wtmwwgqewhgu5zk)

**Comment by Truffle3280** [comment]
Got it, thanks!
