### ISSUE TITLE
Fee reimbursement for trade 216541

### ISSUE THREAD

**Issue by Truffle3280** [bisq-network/support#1277]
![image](https://user-images.githubusercontent.com/122084488/210965084-3672a227-e417-44ec-93f1-4ca178346bd2.png)

Maker:  f073e93076029d84042563f15450302905e9683fddc1f611f2e70992506d6ab0
Taker: 6dabd64eec53fc1cf643358f01f7a2f7b124e1c320c6b9187c628fb2808818ec
Deposit: 0.002703

Bisq version: 1.9.8
BTC address for reimbursement: bc1q4zqavfq4zvu6jtn5pparq3pxmwrxfercwdtu58

**Comment by leo816** [comment]
paid out with #1298

**Comment by Truffle3280** [comment]
Hi, I am wondering why I only got 16600 sats, shouldn't I receive 270300 sats from this tx security deposit?

**Comment by jmacxx** [comment]
Here is your [fee tx](https://mempool.space/tx/f073e93076029d84042563f15450302905e9683fddc1f611f2e70992506d6ab0).  You paid 1750 sats in miner fees and 5000 sats in trade fees.  Your reimbursement should have been 6750 sats.  I don't know why you were overpaid.

Security deposits do not leave your wallet unless sent to a valid 2-of-2 trade multisig, which is not the case.

Please look in your Bisq wallet (under Funds menu) to follow where your deposit went, search from the maker fee tx.

According to mempool.space, your 0.01270300 BTC deposit + sell amount is in your wallet under address [bc1q77rna2wv4lwk7wkh09t6jn4psxp99za79437rs](https://mempool.space/address/bc1q77rna2wv4lwk7wkh09t6jn4psxp99za79437rs)

**Comment by Truffle3280** [comment]
Got it, thanks for explaining it to me!
