### ISSUE TITLE
Fee reimbursement for trade 216541

### ISSUE THREAD

**Issue by Nadumanov** [bisq-network/support#1278]
<img width="1248" alt="Screenshot 2023-01-06 at 6 52 20 PM" src="https://user-images.githubusercontent.com/55026777/210998105-778146af-b6f5-442b-90b3-33c3b6d22d39.png">

Maker: f073e93076029d84042563f15450302905e9683fddc1f611f2e70992506d6ab0
Taker: 6dabd64eec53fc1cf643358f01f7a2f7b124e1c320c6b9187c628fb2808818ec
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1qyyduwzq5mdu9jqrux4fmuwq6ylkaqw2p56yp29

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

Trade state: TAKER_FEE_PUBLISHED

**Comment by leo816** [comment]
paid out with #1298
