### ISSUE TITLE
Fee reimbursement for trade 03zdpv

### ISSUE THREAD

**Issue by rafaelqm** [bisq-network/support#1279]
03zdpv-10ae24e3-b664-40ee-89e9-fcdd1b8fe3c0-198

<img width="864" alt="image" src="https://user-images.githubusercontent.com/4494881/211014867-0f3546d7-909d-4d17-a8b9-f191379542c6.png">

Maker:  66a6df8a8e2da4077af8b942b66723641dbfb47e7c9ab66ea4b468cd6bea0dbc
Taker: e34c7d865eb8ef2d46cab50d8e26b773a0eeeedda3612b9233ca57c9328cbff9
Deposit: N/A

Bisq version: 1.9.8
BTC address for reimbursement: bc1q4ggfadyq88z69plx4awl7nfk9d2q7lvqwh09dw

Other notes:
`Contract as json:
{
  "offerPayload": {
    "id": "03zdpv-10ae24e3-b664-40ee-89e9-fcdd1b8fe3c0-198",
    "date": 1672846326517,
    "ownerNodeAddress": {
      "hostName": "lyx5ldbffi7jfci5vjom6cpbr2rd4wzutwudc2ifdwropjqu4amwhjad.onion",
      "port": 9999
    },
    "direction": "SELL",
    "price": 0,
    "marketPriceMargin": 0.0221,
    "useMarketBasedPrice": true,
    "amount": 1500000,
    "minAmount": 1500000,
    "baseCurrencyCode": "BTC",
    "counterCurrencyCode": "BRL",
    "arbitratorNodeAddresses": [],
    "mediatorNodeAddresses": [
      {
        "hostName": "6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion",
        "port": 9999
      },
      {
        "hostName": "7hkpotiyaukuzcfy6faihjaols5r2mkysz7bm3wrhhbpbphzz3zbwyqd.onion",
        "port": 9999
      }
    ],
    "paymentMethodId": "NATIONAL_BANK",
    "makerPaymentAccountId": "d2874370-4f9e-4be8-a759-cab9cff2d17e",
    "offerFeePaymentTxId": "66a6df8a8e2da4077af8b942b66723641dbfb47e7c9ab66ea4b468cd6bea0dbc",
    "versionNr": "1.9.8",
    "blockHeightAtOfferCreation": 770348,
    "txFee": 2450,
    "makerFee": 21,
    "isCurrencyForMakerFeeBtc": false,
    "buyerSecurityDeposit": 225000,
    "sellerSecurityDeposit": 225000,
    "maxTradeLimit": 10000000,
    "maxTradePeriod": 345600000,
    "useAutoClose": false,
    "useReOpenAfterAutoClose": false,
    "lowerClosePrice": 0,
    "upperClosePrice": 0,
    "isPrivateOffer": false,
    "extraDataMap": {
      "capabilities": "0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17",
      "accountAgeWitnessHash": "7e431284f75e01a46d9f1f2b90aacec847301045"
    },
    "protocolVersion": 4
  },
  "tradeAmount": 1500000,
  "tradePrice": 921658634,
  "takerFeeTxID": "e34c7d865eb8ef2d46cab50d8e26b773a0eeeedda3612b9233ca57c9328cbff9",
  "buyerNodeAddress": {
    "hostName": "jj6u2zjrcvlknqwfakglo6gpdu6ynjctdp5c6hygauft4xcifj2kc2qd.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "lyx5ldbffi7jfci5vjom6cpbr2rd4wzutwudc2ifdwropjqu4amwhjad.onion",
    "port": 9999
  },
  "mediatorNodeAddress": {
    "hostName": "7hkpotiyaukuzcfy6faihjaols5r2mkysz7bm3wrhhbpbphzz3zbwyqd.onion",
    "port": 9999
  },
  "isBuyerMakerAndSellerTaker": false,
  "makerAccountId": "1161888782",
  "takerAccountId": "1177907275",
  "makerPayoutAddressString": "bc1qykzvm76ut97s94qrswgj7z48u06qvvja9pgl3s",
  "takerPayoutAddressString": "bc1qelgf44zn2mxvqr3ktk0h4gy7g34tv2cfk3lgde",
  "lockTime": 773497,
  "refundAgentNodeAddress": {
    "hostName": "3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion",
    "port": 9999
  },
  "hashOfMakersPaymentAccountPayload": [
    -1,
    57,
    -16,
    109,
    -47,
    -82,
    -88,
    32,
    -15,
    75,
    44,
    66,
    1,
    120,
    -46,
    59,
    -31,
    44,
    61,
    76
  ],
  "hashOfTakersPaymentAccountPayload": [
    59,
    -25,
    65,
    47,
    -98,
    -112,
    -55,
    113,
    28,
    62,
    -72,
    -79,
    -54,
    -29,
    -22,
    70,
    -42,
    -38,
    106,
    -6
  ],
  "makerPaymentMethodId": "NATIONAL_BANK",
  "takerPaymentMethodId": "NATIONAL_BANK"
}

Other detail data:

BuyerMultiSigPubKeyHex: 03a001ade9b503746a2ead5eaace7dbef76db6957fff6f5fdb04f0be6e240d0d34
SellerMultiSigPubKeyHex: 027c53982fc68bbc73de9178352e4ea687b881d60590cadbb77c7f39783fe92ba4

BuyersAccountAge: Payment account age not known.
SellersAccountAge: Payment account age not known.

Selected mediator: leo816
Selected arbitrator (refund agent): refundagent2`

**Comment by rafaelqm** [comment]
Also looks like the amount of the transaction 0.015 didn't returned to my available balance.

**Comment by oldGrumpyEngineer** [comment]
I believe these funds should become available once you move the trade to failed trades.

**Comment by leo816** [comment]
paid out with #1298
