### ISSUE TITLE
Fee reimbursement for trade WZINHM44

### ISSUE THREAD

**Issue by iandundee** [bisq-network/support#1281]
![Screenshot 2023-01-06 at 19 44 09](https://user-images.githubusercontent.com/122066656/211087900-a9f224b4-72d8-423a-90c1-dcf048c25642.png)
Maker:  c4cf52610c8bcad06d771faa24fcd7f1ddcef8d2497ae7aeea5b255e8615edf1
Taker: ec5838c82c15929b916f7daf2e0c6332aed27b882ee6ccec883574586768289f
Deposit: 0.001
Bisq version: 1.9.8
BTC address for reimbursement: bc1qjz0r47ypm28u6fnf7pfcncp0xmmefrzp4q7pnu

**Comment by leo816** [comment]
paid out with #1298
