### ISSUE TITLE
Fee reimbursement for trade SNURV

### ISSUE THREAD

**Issue by Nadumanov** [bisq-network/support#1282]
<img width="1248" alt="Screenshot 2023-01-07 at 12 29 35 PM" src="https://user-images.githubusercontent.com/55026777/211130999-0627c85f-83c0-4ef2-a35e-fddcd53a2162.png">

Maker:  00c2be080843609f352fa713b048b2ff534cea34d09539548b7a6fee18037f2a
Taker: 7cd92a847ede9469c90d97175fcf635c6e51b05044cced3ec476cffe57442328
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1qaph95l9retr2j9d0wlunsmcgfmr33pvctg4v09

Other notes:
An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same
Trade state: TAKER_FEE_PUBLISHED

**Comment by leo816** [comment]
paid out with #1298
