### ISSUE TITLE
Fee reimbursement for trade 89111

### ISSUE THREAD

**Issue by emisolo** [bisq-network/support#1283]
<img width="883" alt="Screen Shot 2023-01-07 at 18 30 03" src="https://user-images.githubusercontent.com/16525537/211163175-947cf355-1564-4092-915e-8ef165e06b1f.png">

Maker:  2440d353f7be27c2378164e6cff1a86d89a5e3efac7204e6b4b465461e1ca563
Taker: 2eab2b9cea77af10445fdcfa65cb75db00976ff4efe8c8d3f5ca69bfc541d724
Deposit: 

Bisq version:   1.9.8
BTC address for reimbursement:   16HBSsrgaB9CfjSEUxHp5tgWnVLvfUH5Y4

I am the maker. The deposit transaction is missing but I guess my trade fee has been paid. Please reimburse it.

**Comment by leo816** [comment]
paid out with #1298
