### ISSUE TITLE
Fee reimbursement for trade xwo0s3

### ISSUE THREAD

**Issue by adamsmithofm** [bisq-network/support#1284]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

![teste](https://user-images.githubusercontent.com/122175220/211166158-bf36dc36-b564-4b3c-873e-14f10be913c9.JPG)

Maker:  0.00002450 BTC
Taker: 0.00007080
Maker: c726a811d64ed67dffe43b0a06b481937b2b49e9738d425cfe96edc33b9f2e4e
Taker: 2cafd6b9c684a5b37513b8126f14e16cfb503e5d1d057a19f75a6e409dc60604
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.8
BTC address for reimbursement: bc1qpeuwdnrcneq3gslq0um4kmrfk30mqrz7tlt8qs

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please copy and paste the taker and maker tx id

**Comment by adamsmithofm** [comment]
Maker: c726a811d64ed67dffe43b0a06b481937b2b49e9738d425cfe96edc33b9f2e4e
Taker: 2cafd6b9c684a5b37513b8126f14e16cfb503e5d1d057a19f75a6e409dc60604

**Comment by leo816** [comment]
Reimbursement made with #1341
