### ISSUE TITLE
Fee reimbursement for trade osqizigd

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/support#1285]
![bisq](https://user-images.githubusercontent.com/52383635/211192966-1deaf775-a49a-4a02-b85a-9d611b1818b3.png)

Maker: d53417dea1f9752354ec2f7af04362982816010e3d18b7c380c51db6cbe897c8
Taker: 5b530ab6a32c07fde68f349c49673696215255bc563c65ed58d2330ec79b9f7e
Deposit: NA

Bisq version: v1.9.8
BTC address for reimbursement: bc1qfz93ee69skwmfvg27h93j5fdgx2zdjl6s88r34

Other notes: error "Timeout reached. Protocol did not complete in 120 sec."

**Comment by Drazen-V** [comment]
![bisq](https://user-images.githubusercontent.com/52383635/212078473-2456956e-9120-48f9-aefb-479acf200e12.png)

**Comment by leo816** [comment]
Reimbursement made with #1341
