### ISSUE TITLE
Fee reimbursement for trade XCbx8a

### ISSUE THREAD

**Issue by emisolo** [bisq-network/support#1288]
<img width="884" alt="Screen Shot 2023-01-08 at 16 07 33" src="https://user-images.githubusercontent.com/16525537/211203802-ed595d6c-149d-4025-ac39-9d27cee732a9.png">

Maker:  015314d4a44c6975b4f8892ddb1ef38b2f01cd3a6383f9d6c5f2a13f10315382
Taker: d1664f4d700e43edd9a4345dfb70e6c8a9eaf016f6262e49262118934ceea652
Deposit: ..........

Bisq version: v1.9.8
BTC address for reimbursement:

Other notes:
I am the maker. The deposit transaction was missing. Please reimburse me the trade fee.

**Comment by leo816** [comment]
no btc address for reimbursement

**Comment by emisolo** [comment]
BTC address for reimbursement:

19x5ZUofgGBz2WwZ82a92QXyF2SY2nHRCT

(Sorry)

**Comment by leo816** [comment]
Reimbursement made with #1341
