### ISSUE TITLE
Fee reimbursement for trade XDTAUMU

### ISSUE THREAD

**Issue by dian1200** [bisq-network/support#1289]
![XDTAUMU](https://user-images.githubusercontent.com/109658671/211208871-269a47d5-e781-49c3-a531-e800674c812e.JPG)

Maker:  fca047557c497321bed1fb24ae6d1b1fb3e94784266b04f34f9cbbcccfaa6f90
Taker: ab4c4381473a5a0d2b8f521dc2d58a13871d40cea449345702816d50e5bbfd37
Deposit: ..........

Bisq version: v1.9.8
BTC address for reimbursement:
bc1qmg4uh0rd6j7umt5xz42wjc34yp6fcyw2yef3ll

Other notes:
I am the taker. The deposit transaction was missing. Please reimburse me the trade fee.

**Comment by leo816** [comment]
paid out with #1298
