### ISSUE TITLE
Fee reimbursement for trade QUZZESN

### ISSUE THREAD

**Issue by BTCNautilus** [bisq-network/support#1291]
<img width="909" alt="Screen Shot 2023-01-05 at 7 47 42 AM" src="https://user-images.githubusercontent.com/103174795/211367386-e0b3602a-59d1-4aeb-8271-5ff9b37c1b0a.png">

Maker:  f0224409a4845ad1b8cdb230a7063d3651ecf7dfb9b1479bed68dfb1be101689
Taker: e84a0932cf575c2a2afaa04350f459813438783a4c4aae87dc386dcc9f6f4cff
Deposit: NA

Bisq version: 1.9.8
BTC address for reimbursement: bc1q3gw3x280upahkg9ugjgkqdavzyuup7dg4z4wp0

Other notes:
I am the taker of this trade. Trade failed when An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx. Please reimburse the trade fees.

**Comment by BTCNautilus** [comment]
Thanks!

**Comment by leo816** [comment]
paid out with #1298
