### ISSUE TITLE
Fee reimbursement for trade XDTAUMU

### ISSUE THREAD

**Issue by emisolo** [bisq-network/support#1292]
<img width="872" alt="Screen Shot 2023-01-10 at 13 45 06" src="https://user-images.githubusercontent.com/16525537/211555281-3e352993-fde0-4a1e-a56b-2b21401b2a27.png">

Maker:  .......... fca047557c497321bed1fb24ae6d1b1fb3e94784266b04f34f9cbbcccfaa6f90
Taker: ........... ab4c4381473a5a0d2b8f521dc2d58a13871d40cea449345702816d50e5bbfd37
Deposit: ..........

Bisq version: v1.9.9
BTC address for reimbursement: 19x5ZUofgGBz2WwZ82a92QXyF2SY2nHRCT

I am the maker. Deposit transaction was missing. Please reimburse me the fee.

**Comment by pazza83** [comment]
Hi @emisolo 

As you were the maker and no deposit transaction was published you should not have lot funds on this trade as your offer should still be available for someone else to take.

**Comment by leo816** [comment]
paid out with #1298
