### ISSUE TITLE
Fee reimbursement for trade 7rcvc7h

### ISSUE THREAD

**Issue by cointrader1982** [bisq-network/support#1293]
![7rcvc7h](https://user-images.githubusercontent.com/122401313/211651836-7964e540-a52c-4064-b3ab-eecd661b7230.JPG)

Maker:  3d30793139c9d63fe1b32d40165388f064f838f9222cfa3832c39f900d2166e8
Taker: 81ed30a99b6a3d036b98f077a66dfdd5b68756cad555bf174004fa0ae4fd6e76
Deposit: N\A

Bisq version: 1.9.9
BTC address for reimbursement: bc1qf2gm08w0kxnp8xp4jy3p94e3fcgcs7v3dfmekl

**Comment by leo816** [comment]
paid out with #1298
