### ISSUE TITLE
Fee reimbursement for trade 5707284

### ISSUE THREAD

**Issue by cointrader1982** [bisq-network/support#1294]
![5707284](https://user-images.githubusercontent.com/122401313/211652270-128fb150-ae39-4fa5-94b4-bb85eddc12e6.JPG)

Maker:  4f8bc34f68e07174e511899fd205cf2da2c8af88a1008838f3d05012722c4733
Taker: 9111cebaf3487940b99e60a3f78805743dd737dc91435dfaedb061436db63ddc
Deposit: N/A

Bisq version:1.9.9
BTC address for reimbursement: bc1qf2gm08w0kxnp8xp4jy3p94e3fcgcs7v3dfmekl

**Comment by leo816** [comment]
paid out with #1298
