### ISSUE TITLE
Fee reimbursement for trade CZIV0N

### ISSUE THREAD

**Issue by cointrader1982** [bisq-network/support#1295]
![CZIV0N](https://user-images.githubusercontent.com/122401313/211654452-5deb2445-a98b-4738-bac9-619b00360adc.JPG)

Maker: 59cf1f9b228a96b3fd869b9a52307b17e2eb27f9036e0e5a74a0b881e51a7b2f
Taker: fd79e9d47fe69afa2a102e540182ec24bb92e7bf565bce9b768a62c044331490
Deposit: N\A

Bisq version: 1.9.9
BTC address for reimbursement: bc1qf2gm08w0kxnp8xp4jy3p94e3fcgcs7v3dfmekl

**Comment by leo816** [comment]
paid out with #1298
