### ISSUE TITLE
Fee reimbursement for trade 5707284

### ISSUE THREAD

**Issue by stumpnet** [bisq-network/support#1296]
5707284-bae232f5-cf6a-4757-823e-04d0b859fd2a-198 is the trade ID.

![failed_bisq5707284](https://user-images.githubusercontent.com/122417178/211699528-3994f4a5-6356-43f6-94b3-d442e3eb2bd1.JPG)

Maker:  4f8bc34f68e07174e511899fd205cf2da2c8af88a1008838f3d05012722c4733
Taker: 9111cebaf3487940b99e60a3f78805743dd737dc91435dfaedb061436db63ddc
Deposit: N/A

Bisq version:  1.9.9
BTC address for reimbursement:   bc1qvquwkcmy2knzxuzs2vy22ck56el7wucvlpqg5t

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @stumpnet 

As you were the maker and no deposit transaction was published you should not have lot funds on this trade as your offer should still be available for someone else to take.

**Comment by stumpnet** [comment]
My funds are not locked, but the balance was not returned.  I have both of these screens in the fail trade detailing how to ask for my funds to be returned.
![bisq_error2](https://user-images.githubusercontent.com/122417178/211943343-032c92f6-e91b-402b-b2b5-bf3d6383ecfa.JPG)
![bisq_error1](https://user-images.githubusercontent.com/122417178/211943344-50476c4c-af93-4d64-9467-dba095c4cd01.JPG)

**Comment by stumpnet** [comment]
Upon reboot of the app, the funds have been made available.  I'm good. Looks like a recurrent error made it through testing though.  Lots of requests for this very issue.

**Comment by leo816** [comment]
paid out with #1298
