### ISSUE TITLE
Fee reimbursement for trade CZIVON

### ISSUE THREAD

**Issue by lfournier** [bisq-network/support#1297]
![bisq_failed_trade](https://user-images.githubusercontent.com/346365/211704583-8354cb77-a3ac-49f8-9036-d724e9e167ea.png)

Bisq version: 1.9.9
Maker fee transaction ID: 59cf1f9b228a96b3fd869b9a52307b17e2eb27f9036e0e5a74a0b881e51a7b2f
Taker fee transaction ID: fd79e9d47fe69afa2a102e540182ec24bb92e7bf565bce9b768a62c044331490
Deposit transaction ID: N/A

BTC address for reimbursement:
bc1q70846xc87mhx28m94gpsxzks20z9yv2c7xcr8d

**Comment by leo816** [comment]
please provide a full screenshot of the trade details

**Comment by lfournier** [comment]
![bisq_failed_trade_full](https://user-images.githubusercontent.com/346365/211805586-95b56b71-a0f4-4e8b-b4df-ffc7c75a6c62.png)

**Comment by leo816** [comment]
paid out with #1298
