### ISSUE TITLE
Fee reimbursement for trade DJIAC

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1299]
![obraz](https://user-images.githubusercontent.com/63785272/211930602-4837a4fd-409e-40b6-b340-ce1b4b41b3c9.png)

Maker:  4459c650bab4d963a6379619cdf563bb0f520d6ca3a69c085eb5cd2337e4f377
Taker: 530df34076b337be24f5afb5ee597a10add9ccf1a510896b6522c5f8f09fa8d1
Deposit: 9e155b8058585c9e82e9464d3002aea450f19a2615dc1dec8bf2b0d32c7697d6

Bisq version: 1.9.9
BTC address for reimbursement: bc1qd5h7z50mcwmd4z5p3qem4jgackrrr57susw0s8

Other notes: none

**Comment by pazza83** [comment]
Hi @Akira45-0 

Thanks for opening the issue.

I can see you lost trade and miner fees as a result of this failed trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Reimbursement made with #1341
