### ISSUE TITLE
Fee reimbursement for trade 7575105

### ISSUE THREAD

**Issue by rotia37** [bisq-network/support#1300]
>_The 7575105 

![7575105](https://user-images.githubusercontent.com/118468198/211959531-fd42f4d9-52b8-4de3-9196-7db16a8912e4.png)

Maker:  ddd904bc5db317c7bf702c6e63dd79bb93c831b29b2b4b344367b1f1357f155b
Taker: e1943631c51a7ec93844c4717f9ba53b063b72fbeb75061461b9e05f568c73bc
Deposit: N/A

Bisq version :v1.9.8

BTC address for reimbursement: bc1q3ytzc25y60ag436ds0zxm99xrs0n4fa2688vra

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

Estado comercial: TAKER_FEE_PUBLISHED

Other notes:

**Comment by rotia37** [comment]
BTC address for reimbursement: bc1q3ytzc25y60ag436ds0zxm99xrs0n4fa2688vra

**Comment by rotia37** [comment]
@pazza83

**Comment by pazza83** [comment]
Hi @rotia37 thanks for posting.

I can see you lost taker fees (0.0002288 BTC) and mining fees (0.0000233 BTC) as a result of this failed trade.

@leo816 please can you add to your list for reimbursement.

**Comment by pazza83** [comment]
@rotia37 

Please can you also check your DAO is in sync. From the info provided looks like you might be trading with an out-of-sync DAO hence the reason for the failed trade.

Go to DAO > Network monitor to check your DAO status

If it is out of sync there is a button to press to re-sync it

**Comment by leo816** [comment]
Reimbursement made with #1341
