### ISSUE TITLE
Fee reimbursement for trade mNqbOPKE

### ISSUE THREAD

**Issue by rotia37** [bisq-network/support#1301]
>_The mNqbOPKE

![mnqbopke](https://user-images.githubusercontent.com/118468198/211959078-845cb4c8-a07f-4c25-a357-02e19c79b8a1.png)

Maker: 418a43fdfdcb8d32b201937e424bb63635dcea49ac4ff0eaf20967fb764a65a6
Taker:78ffe339b8712858243e5348caa4b6b24a0fd1824a48c70c3291e616b68cbea8
Deposit: N/A

Bisq version: v1.9.8
BTC address for reimbursement: bc1q3kqw2qjvxde5rsdzaajf8gnztvprz72flr23s6

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

Other notes:

**Comment by pazza83** [comment]
Hi @rotia37

thanks for posting.

I can see you lost trade and mining fees as a result of this failed trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Reimbursement made with #1341
