### ISSUE TITLE
Fee reimbursement for trade cniqoysa

### ISSUE THREAD

**Issue by Christian891** [bisq-network/support#1303]
![image](https://user-images.githubusercontent.com/85958076/212126590-3108f632-9071-4292-b132-8d29ae65b36c.png)

Maker:  79b2cfefb733b78bc5440418c3d1e9d5606e18fc84ee5a76d5cf0d4320645bcb
Taker: c04d4123cf24200f3d54fc7344d3acc5b5607959a2c625262e10f646aa66ec05
Deposit: ea939956ce9fec9a066bf6a6fdae8ace0ded0e3d46852a9347773cb4135692f1

Bisq version: 1.9.9
BTC address for reimbursement: bc1qv8yq0nhwv5sfdg6azvcjzah77sq3ytnrx3spk3

**Comment by pazza83** [comment]
Hi @Christian891 

Thanks for posting.

I can see you lost trade and miner fees as a result of this trade.

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Reimbursement made with #1341
