### ISSUE TITLE
Mining fee is not reimbursed when reimbursing failed trades

### ISSUE THREAD

**Issue by oldGrumpyEngineer** [bisq-network/support#1305]
When reimbursing a maker fee for a failed transaction, mining fee for maker fee transaction is not reimbursed. 
This means that if there is a bug in the system that causes trade to fail, the user pays (small portion of) cost of handling the situation, through no fault of their own. 

Expectation: all fees associated with a failed trade are reimbursed, including mining fees for transactions that are part of the trade.

**Comment by oldGrumpyEngineer** [comment]
> transaction

trade

**Comment by pazza83** [comment]
Currently mining fees and trade fees are reimbursed as part of a failed trade reimbursement request. If yours have not been please comment on the corresponding ticket.

**Comment by oldGrumpyEngineer** [comment]
Thanks for the response, @pazza83. 
I've left the comment on the support ticket in question, please take a look here: https://github.com/bisq-network/support/issues/1266

Ticket has been closed though, and I am not sure what the process is. Should the reimbursement ticket be opened? Is someone looking at the comments on a closed ticket?

Please bear with me, a n00b here :).

**Comment by MwithM** [comment]
You can keep commenting on a closed ticket and as leo is still assigned, will get a notification.

I think that only trading fees were reimbursed, not mining fees.
