### ISSUE TITLE
Reimbursement for _trader's onion address_

### ISSUE THREAD

**Issue by Vitalconchon** [bisq-network/support#1306]
SCREENSHOT HERE
![Captura de pantalla 2023-01-14 a las 21 29 55](https://user-images.githubusercontent.com/122700233/212496648-4a20ce39-fc4c-418b-9629-1a4e89f4419c.png)

Reimbursement for trade [TRADE ID]

Maker:  9847713a397260de8dd3611beb899a0d2a9945a893be3cf6027f95d2531768d2
Taker: eff995cd949e9b180386cb627357263c283c3c4281b78dc1101d35edcc3c2fd4
Deposit: No disponible
Delayed payout: No disponible
Depósito   0.001875 BTC
Minado   0.00002450 BTC

Reason for reimbursement: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same

BTC address ownership proof:
bc1q4yygch8tza8kl4w8ffz2527cp79dut0wrjgkt3v49yljtzmq0ghsn9q6hw
Bisq version: 1.9.8

**Comment by pazza83** [comment]
Hi @Vitalconchon 

Thanks for posting.

As you were the maker and the trade failed with no deposit transaction you should not have lost any trade or miner fees on this trade.

Your offer should still be available to be taken.
