### ISSUE TITLE
Fee reimbursement for trade 943940

### ISSUE THREAD

**Issue by felipesocha** [bisq-network/support#1307]
![image](https://user-images.githubusercontent.com/107418776/212558424-4b2a8242-8fc2-4f5c-9e3a-3b65817e78fe.png)

Maker:  9f8d25511ee568edebeb2e500f9a2e2a86ec443e6efe12ac9f6644741e28afc0
Taker: 9e26949d89146b26cb77d7962f32666d0c5827e665f0636f0456f9a0b7e51f97
Deposit: 907f8720365a302a0cfc6ba431180e12b22b5a982f35f79c73f83c65fee95551

Bisq version: 1.9.9
BTC address for reimbursement: bc1q0u56kspw6p49v023p0mjmddy6u6a5xns7daj2l

**Comment by pazza83** [comment]
Hi @felipesocha  

Thanks for opening the issue.

As you were the maker and the maker transaction failed you will have not lost any trade or mining fees as a result of this trade.

You might need to do an SPV resync to make sure your balance is showing correctly and future trades do not fail:

https://bisq.wiki/Resyncing_SPV_file
