### ISSUE TITLE
Fee reimbursement for trade fsrwcfwo

### ISSUE THREAD

**Issue by Krvopije** [bisq-network/support#1308]
![Bildschirmfoto vom 2023-01-16 20-45-27](https://user-images.githubusercontent.com/34864681/212756545-03506489-0c0d-4d97-b12c-bf148f3f0bf5.png)

Maker:  2c512b2c7a53deb44ed15e0cdb15dbbfd1038d220ba2872644f4281078fad70e
Taker: 0657f0468c0353a3f2a5d29b4aeb14f21ad713f31463d87e258cedd58cb5a819
Deposit: N/A

Bisq version: 1.9.9
BTC address for reimbursement: bc1qs6pyadmtvy3n099k0trhat56p46zxndc9985nj

Other notes:
I assume the Taker has the 1.9.7 or 1.9.8 version and if so then the Bisq-Twitteraccount and other SM-Accounts should discourage people to use 1.9.7 and 1.9.8, you guys are getting failed trades in masses currently and could have avoid a lot of this by informing people publicly.

**Comment by Krvopije** [comment]
Fee + Deposit. The 0.02002560 BTC deposit aren't under my control.

**Comment by Krvopije** [comment]
I looked for that address under receive money, send money, reserved money and locked money because I saw it on the blockexplorer in my maker transaction with the deposit amount and I don't know why, but it didn't show previously anywhere, 

I never close the app, its running 24/7 and after your reply I finally realized how fucking dumb I am to post it without trying first and restarted it and for whatever reason it showed after restarting the app.

> Could you attach a copy of the Bisq application message which prompted you to open this ticket?

Sure even though the deposit request of me was bullshit.
![Bildschirmfoto vom 2023-01-19 02-21-45](https://user-images.githubusercontent.com/34864681/213334747-e5a576e2-7a15-420d-8a03-639715b19103.png)

**Comment by leo816** [comment]
Reimbursement made with #1341
