### ISSUE TITLE
Mac Download doesn't work-- says file is damaged. 

### ISSUE THREAD

**Issue by mrslyk** [bisq-network/support#1309]
download of bisq for Mac from bisq download page throws error once moved to application file and tried to open. 

<img width="406" alt="Screen Shot 2023-01-16 at 12 05 19 PM" src="https://user-images.githubusercontent.com/96096806/212758225-29af57d9-ec85-48de-b851-423a024eab30.png">

started_at_UTC:
<_yyyy-mm-dd hh:mm_

github-issue:
>_Please provide a reference issue number to which this case is related. If there isn't one go ahead and create that issue first._

Bisq version:
>_Provide the Bisq client version to help developers identify the causing issue._

Device or machine:
>_Provide the Operating System and Version_

SCREENSHOTS HERE

>_Always when possible share screenshots of the error messages. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

solution:

Other notes:

**Comment by jmacxx** [comment]
Please read https://github.com/bisq-network/bisq/issues/6401 and also the [release notes](https://github.com/bisq-network/bisq/releases/tag/v1.9.9) pertaining to Macs.
