### ISSUE TITLE
Fee reimbursement for trade 4rzri4n

### ISSUE THREAD

**Issue by ccd12** [bisq-network/support#1310]
Maker: 63642ff61fad0196a42b988a2224c7db5d934b45fdfc2b005c4be5f2248dfe14
Taker: 3aeaa06558f5d77ece1b4b8708a9750b174eeab7708950ac221b72aac545aab4
Deposit: 0a12d4d7b812ed578ccb9cdc7be7ecec0234adf3fb667051075d8e18205c1b3f

Bisq version: v1.9.9
BTC address for reimbursement: bc1qcg7uq58hwe3jaxtrp58txhzvy8hqp3w6ctz640

**Comment by jmacxx** [comment]
You need to attach a screenshot of the trade details, showing whether you are maker/taker.
Could you attach a copy of the Bisq application message which prompted you to open this ticket?
Please also include the amount you are requesting refunded.

**Comment by ccd12** [comment]
Hi, 
I am taker :
![image](https://user-images.githubusercontent.com/104859557/213295160-40aa795b-7f16-494c-90d6-81277859a4c7.png)

Bisq application message :
![image](https://user-images.githubusercontent.com/104859557/213294687-d4f901b9-bdd1-4ef4-b5dc-8cc8ff914697.png)

The amount i am requesting refunded is : 0.00007170 BTC

**Comment by leo816** [comment]
Reimbursement made with #1341
