### ISSUE TITLE
Fee reimbursement for trade klfmk

### ISSUE THREAD

**Issue by aphex3k** [bisq-network/support#1311]
<img width="876" alt="Untitled" src="https://user-images.githubusercontent.com/433270/213295168-50cb3935-9e5c-46b3-8e7e-088ce28a93d2.png">

Maker:  55cc38c51c327e1b3be480523dd4a407a3caa9e64904deac83f2edc8eb54fd10
Taker: e8af37764c590def56962f6669d83e3d5e677f6e0ff27a97516d8f314f8185fa
Deposit: 712bc344951aea88be3940d9dd802501b6520552e44abab53eca7ff40e7e8dca

Bisq version: 1.9.9
BTC address for reimbursement: 1Lf2K55uLXnYNqzggTSJzjAGLzA4wmgwf9

**Comment by jmacxx** [comment]
Please update your screenshot to indicate whether you are maker/taker.
Could you attach a copy of the Bisq application message which prompted you to open this ticket?
Please also include the amount you are requesting refunded.

**Comment by aphex3k** [comment]
> Please update your screenshot to indicate whether you are maker/taker.

I am the taker. 

> Could you attach a copy of the Bisq application message which prompted you to open this ticket? Please also include the amount you are requesting refunded.


<img width="566" alt="Screenshot 2023-01-18 at 1 10 36 PM" src="https://user-images.githubusercontent.com/433270/213295572-12d31386-3c37-429d-bbdf-c12b4a609a9b.png">


<img width="799" alt="Screenshot 2023-01-18 at 1 11 07 PM" src="https://user-images.githubusercontent.com/433270/213295601-68aed729-d38b-44ba-9966-59dd00beecb1.png">

**Comment by aphex3k** [comment]
I would like to request the full trade fee amount returned.

**Comment by jmacxx** [comment]
Thanks @aphex3k, you paid [4.87 BSQ](https://bisq.markets/tx/e8af37764c590def56962f6669d83e3d5e677f6e0ff27a97516d8f314f8185fa) trade fees and 0.00002680 BTC miner fees.

**Comment by leo816** [comment]
Reimbursement made with #1341
