### ISSUE TITLE
java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING

### ISSUE THREAD

**Issue by alexorlandi** [bisq-network/support#1312]
>_The XXXXX part are a random string generated with the command `date | shasum | cut -b-6`._

Aviso
A conexão com a rede Bitcoin falhou devido ao erro: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.

Description:

>_Provide a brief description of the bug_

Aviso
A conexão com a rede Bitcoin falhou devido ao erro: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.

started_at_UTC:
<_yyyy-mm-dd hh:mm_
2023-01-17 14:00

github-issue:
>_Please provide a reference issue number to which this case is related. If there isn't one go ahead and create that issue first._

Bisq version:
>_Provide the Bisq client version to help developers identify the causing issue._
64bit-1.9.9

Device or machine:
>_Provide the Operating System and Version_
Linux Ububtu 22.04 LTS

SCREENSHOTS HERE

>_Always when possible share screenshots of the error messages. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

solution:

Other notes:

**Comment by jmacxx** [comment]
That error means your SPV wallet needs to be [resynced](https://bisq.wiki/Resyncing_SPV_file#From_the_file_system):

> Close Bisq, delete the btc_mainnet/wallet/bisq.spvchain from your [data directory](https://bisq.wiki/Data_directory), start Bisq, wait for it to load, and then restart Bisq again.

> Bisq will not prompt you to restart it again—so don't forget to actually do it!

> Depending on the age of your wallet and how many transactions it has, it may take a while to finish syncing. During syncing, it's normal for your machine to reach high CPU usage levels, and Bisq may not be responsive until syncing has finished.

**Comment by alexorlandi** [comment]
error solved, thanks
