### ISSUE TITLE
Reimbursement for wgrib6kfglyxzpyk6fecbxmn6voubap25ydy4uqfudgctptiywmqsgid.onion

### ISSUE THREAD

**Issue by peredeli** [bisq-network/support#1313]
![bisq trade error](https://user-images.githubusercontent.com/122944446/213038316-1728e3fb-c84c-4eca-9168-8dee6abcf1aa.png)

Reimbursement for trade 192017

I am BTC seller as maker for BRL.
Trade amount and asset: 0.01 BTC for 1113 BRL
Deposit amount: 0.0015 BTC

Maker: 99a4531844d0eff7bc36ed4fbf143f3b83e32941961d84731d1db3e9394c3ea0
Taker: 3de46818bf65e4dd7eb176c5fc4a7fdfcd0079547784b0dd972efa9cd84036ce
Deposit: N/D
Delayed payout: N/D
BuyerMultiSigPubKeyHex: 02ca2d57c88a634beeda40b5f13e3535c486bf2608617b5cbc8a717e1377466732
SellerMultiSigPubKeyHex: 02eeeb380bb62dce014fa96e73f3d23227e4120d7086889e8ece98659e76e59149

Reimbursement amount: 0.14 BSQ
Reason for reimbursement: The deposit transaction (the 2-of-2 multisig transaction) is missing. Without this tx, the trade cannot be completed.

BTC address ownership proof:

Maker: 99a4531844d0eff7bc36ed4fbf143f3b83e32941961d84731d1db3e9394c3ea0
Taker: 3de46818bf65e4dd7eb176c5fc4a7fdfcd0079547784b0dd972efa9cd84036ce

Bisq version:

v1.9.9

@refundagent2 @leo816

**Comment by jmacxx** [comment]
Please could you paste a copy of the Bisq message which prompted you to open a reimbursement ticket.

**Comment by peredeli** [comment]
![error](https://user-images.githubusercontent.com/122944446/213425670-3f74d477-95a3-4b30-b96d-6deb2548583f.png)

Atenção
The trade protocol encountered some problems.

The trade contract is not set.

The trade cannot be completed and you might have lost your trade fee. If so, you can request a reimbursement for lost trade fees here: [1]
[https://github.com/bisq-network/support/issues]

**Comment by leo816** [comment]
no btc address information for reimbursement
