### ISSUE TITLE
Fee reimbursement for trade rcivgw

### ISSUE THREAD

**Issue by felipesocha** [bisq-network/support#1314]
![image](https://user-images.githubusercontent.com/107418776/213171201-07068aa3-556c-4bbd-af1b-90493f4defba.png)

Maker:  47c7bb03664caea99f25bcd59351b234b1b98c6d6edc52cd89bcf42610b1a343
Taker: 748e05224f48ded1ac70bdefb73bfb04e5b388169c240591e479eb49053aa48b
Deposit: 

Bisq version: 1.9.9
BTC address for reimbursement: bc1q54vg9ukjy5uc6d6khapqrzlve0hsrcz8t0y68s

Other notes:

**Comment by jmacxx** [comment]
Could you attach a copy of the Bisq application message which prompted you to open this ticket?
Please also include the amount you are requesting refunded.

**Comment by felipesocha** [comment]
Atenção
The trade protocol encountered some problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: [1]

Feel free to move this trade to failed trades.
[https://github.com/bisq-network/support/issues]

 the amount i am requesting refunded is the fees: 0,00002450 BTC (or 0,00002422 BTC + 0,28 bsq)

**Comment by leo816** [comment]
Reimbursement made with #1341
