### ISSUE TITLE
Fee reimbursement for trade sbhwievt

### ISSUE THREAD

**Issue by lewisdwilliams** [bisq-network/support#1315]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

<img width="854" alt="Screenshot 2023-01-19 at 14 58 52" src="https://user-images.githubusercontent.com/30794886/213475935-2743a444-9d0a-4d6f-86d4-a11f68bfa448.png">

<img width="637" alt="Screenshot 2023-01-19 at 14 59 53" src="https://user-images.githubusercontent.com/30794886/213476179-466a3447-4759-4b5a-852c-cc855fe518e5.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  aa8f90da5709765500b90f7b5485d0706472d9334ae1c1cfd1a42419c96cd9ad
Taker: fcca6e9a0af8895197dbc4e0f5e8e19d3f50fbe3cfa24c635a53b07753120b4e
Deposit: a5e1095148d8947acd5efc60162bf06ae7621610de385e295b003632fb1eac25

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.9
BTC address for reimbursement: bc1qc3k09twcar2mnwsuwas33dyg7gjtmfkkn368z9

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @lewisdwilliams 

Please can you include the part of the screen shot that shows if you were the taker or maker

**Comment by pazza83** [comment]
@lewisdwilliams 

Thanks that is great.

I can see you lost miner and trade fees on this failed trade.

@leo816 please can you add this to your list for reimbursement.

**Comment by leo816** [comment]
Reimbursement made with #1341
