### ISSUE TITLE
Fee reimbursement for trade 71341

### ISSUE THREAD

**Issue by eleminity** [bisq-network/support#1320]
![trade fail](https://user-images.githubusercontent.com/123262548/213879411-9ece6c78-2f28-420d-ad7a-573f9cbb7eca.png)

![tradfail](https://user-images.githubusercontent.com/123262548/213879412-73bfaa41-8a4c-46b2-80b1-cfb25ab7d68f.png)

Maker: 6c5567da1dc396cc72dbe4c55d9a3c49fe3a60c0d46a6a4e2e831cbcebf9edd1
Taker: 287e6a7b3eb2d817e3d1f51f868dbec6ef86539f4a47af2f0e64bbb33b1fa385
Deposit: N/A

Bisq version: 1.9.9
BTC address for reimbursement: bc1qwmsngcxumeyknxuum662f456sqx9sq2fdxwh24

Hi I was the taker but trade timed out. First time I've encountered this. I paid trade fee in BSQ but I think I have to provide BTC address for refund? Pls tell me if not & cheers

**Comment by pazza83** [comment]
Hi @eleminity 

Thanks for posting.

I can see you lost miner and trade fees for this trade.

@leo816 please can you add this to your list for reimbursement

**Comment by w0000000t** [comment]
@eleminity  you share the same trade with https://github.com/bisq-network/support/issues/1321
We would find very useful if you  both could come over to https://bisq.chat and send your logs in DM to a support agent, having both sides to examine can be very helping

**Comment by eleminity** [comment]
Hi @leo816 it's been a couple of weeks and I don't think the refund of 4.75BSQ has come through yet https://bisq.markets/tx/287e6a7b3eb2d817e3d1f51f868dbec6ef86539f4a47af2f0e64bbb33b1fa385 . Both my BTC and BSQ balances are unchanged. Do you know if it's still coming / if something went wrong?

My BSQ receive address is Bbc1qdrdx6rfcd87mfrxj2d4kkp22j42u70tqlyg7x7

Cheers

**Comment by pazza83** [comment]
Hi @eleminity 

Reimbursements are made in BTC not BSQ.

Also they are usually made once a month but on occasion they might be made once every other month.

Apologies for the inconvenience

**Comment by eleminity** [comment]
Hi @pazza83 that's great thanks for letting me know, I wasn't sure how it works. My BTC address was already in the original post so all good :)

**Comment by leo816** [comment]
Reimbursement made with #1341
