### ISSUE TITLE
Fee reimbursement for trade 71341

### ISSUE THREAD

**Issue by SantiagoJalapenosAlfajores** [bisq-network/support#1321]
![image](https://user-images.githubusercontent.com/117783713/213879178-2335b569-457a-4a37-91e4-fc421f558e6d.png)

Maker:  6c5567da1dc396cc72dbe4c55d9a3c49fe3a60c0d46a6a4e2e831cbcebf9edd1
Taker:  287e6a7b3eb2d817e3d1f51f868dbec6ef86539f4a47af2f0e64bbb33b1fa385
Deposit: 

Bisq version: 1.9.9
BTC address for reimbursement: bc1qeugsey8sluntlyge8ac8acc3lv4jgesf7nzqu4

Other notes: deposit balance disappeared

**Comment by pazza83** [comment]
Hi @SantiagoJalapenosAlfajores where you the maker or taker?

**Comment by SantiagoJalapenosAlfajores** [comment]
I was the buyer-maker
ignore the other notes, as deposit was back

**Comment by w0000000t** [comment]
@SantiagoJalapenosAlfajores you share the same trade with https://github.com/bisq-network/support/issues/1320
We would find very useful if you  both could come over to https://bisq.chat and send your logs in DM to a support agent, having both sides to examine can be very helping

**Comment by leo816** [comment]
Reimbursement made with #1341
