### ISSUE TITLE
Fee reimbursement for trade MSDTEJTV-3dd01ff1-f9eb-4c69-aebf-da6eda87b74e-199

### ISSUE THREAD

**Issue by ciancaleone** [bisq-network/support#1322]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

![Clip](https://user-images.githubusercontent.com/36314660/213881360-6f20b2b0-e5f7-4434-a9f9-4f4378e175c6.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  79ce781afa6fdbb24e40d4d5d4df1493802437d0a31a790e424a77eb34cc85e5
Taker: 82ba0a49632c7b2f2d076252c97e913c3ca8434b4839388b295428e7b9162c9f
Deposit: 0.0015 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:  1.9.9
BTC address for reimbursement:     bc1qatgzsqx5249uvl5tqx8fuvz6agdsypmkxrdt07

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @ciancaleone 

Please can you post the maker and taker transactions in text format.

Many thanks

**Comment by ciancaleone** [comment]
Maker: 79ce781afa6fdbb24e40d4d5d4df1493802437d0a31a790e424a77eb34cc85e5
Taker: 82ba0a49632c7b2f2d076252c97e913c3ca8434b4839388b295428e7b9162c9f

**Comment by pazza83** [comment]
Hi @ciancaleone many thanks.

I can see you lost miner and trade fees on this failed trade.

@leo816 please can you add to your list for reimbursement.

Many thanks

**Comment by ciancaleone** [comment]
@leo816 usually how long will it take?
thank you

**Comment by pazza83** [comment]
@ciancaleone it can take up to 8 weeks.

You are due:

0.00008800 BTC for your trade fees
0.00002330 BTC for your miner fees

so 0.0001113 BTC in total.

**Comment by leo816** [comment]
Reimbursement made with #1341
