### ISSUE TITLE
Fee reimbursement for trade 72337762

### ISSUE THREAD

**Issue by cointrader1982** [bisq-network/support#1324]
72337762

![72337762](https://user-images.githubusercontent.com/122401313/214077699-5e251f33-87d9-4f24-9837-f64098f13fa5.JPG)

Maker:  fc07319e295be7f09ec2c9c026ab737cd32c96fda67da6b6f9271f984f13231a
Taker: 355d1d11e51f38e6c631b9e1c30afd4596bd40010b71933e94220098e8e00982
Deposit: N\A

Bisq version: 1.9.9
BTC address for reimbursement: bc1qm7n3sjq20dx88z47lqh6jt550zg4aafvr503dz

Other notes:

I really wish I knew why this keeps happening. I am about to give up on Bisq

**Comment by ghost** [comment]
Taker lost: 2330 sats mining + 8800 sats trading fee.  @leo816 FYI

@cointrader1982 its top priority & we're working very hard to fix the issue, sorry it is causing frustration.

If you can supply bisq logs to a [support agent on Matrix](https://bisq.wiki/User_support#Via_Matrix_bisq.chat) it might help, particularly it would be helpful to obtain logs from both peers in a failed trade such as this.

**Comment by cointrader1982** [comment]
I actually solves the issue. Had to delete my bisque directory and restore
everything. After that everything is working again.

**Comment by leo816** [comment]
Reimbursement made with #1341
