### ISSUE TITLE
Fee reimbursement for trade 592676

### ISSUE THREAD

**Issue by smashy211** [bisq-network/support#1327]
![image](https://user-images.githubusercontent.com/123509495/214404232-e52c724a-c3b5-4294-9930-d2be26ef0316.png)

Maker: 1a39f6993ae8df417b592b59e119a1c690349fd6b9f5a24813c92b929c37553b
Taker: c98678081986551d79cd7f67b47de00d5d0cf8da06e57d3d131234fc5c033298
Deposit: 0.0015 BTC
BTC mining fees lost: 0.00003675 BTC
Trade fees lost: 0.00005 BTC (Ty commenter)

Bisq version: 1.9.9
BTC address for reimbursement: bc1qxhlz3hhjsq4qpaltns0squ9tlcmyaaupsc6mew

Other notes: Left trade open as i left for an hour and a half to see if anyone would take, get home and see error has occured
![image](https://user-images.githubusercontent.com/123509495/214405948-2529b00b-edd6-4c88-adaf-8823d6df05b8.png)

Sorry if not formatted correctly, tried to follow the guide but will fix anything if necessary, thanks

**Comment by ghost** [comment]
Looks like you lost 3675 mining and 5000 sats trading fees.  @leo816 FYI.

**Comment by leo816** [comment]
Reimbursement made with #1341
