### ISSUE TITLE
Fee reimbursement for trade Vvh7g4

### ISSUE THREAD

**Issue by prohinig** [bisq-network/support#1328]
![Screenshot 2023-01-26 at 07 56 02](https://user-images.githubusercontent.com/17741517/214775198-9b642a5a-2f5e-4107-9b63-ee827b603b5f.png)

Maker:  1ff45b38e1af1ef41ccde7451a18b47a92645903330189ff33edd0d943c13435
Taker: N/A
Deposit: N/A
BTC mining fees lost: 0.00003675 BTC
Trade fees lost, please state if BSQ or BTC: 0.14 BSQ
![Screenshot 2023-01-26 at 08 05 12](https://user-images.githubusercontent.com/17741517/214776394-4267f206-1743-4f8a-88e7-9518efffa5aa.png)

Bisq version: v1.9.9 macOS
BTC address for reimbursement: bc1qdja5l5hqffa2k9dasdf2d6krrryzqtwtfx3t20

**Comment by ghost** [comment]
@cprohinig looks like your offer Vvh7g4 remained open and eventually resulted in a successful trade: 

deposit tx `39805b7ad44fed853721a1d283321da521821bef9bf3de335cca917d5040bd62` 
payout tx `06e7bcfd5b7dc3f44b1370acf6053df3993b41ef99a448e2ffd608c21c239bb7`

In which case there is no refund necessary.

**Comment by prohinig** [comment]
Apologies, confusion on my side.
