### ISSUE TITLE
Fee reimbursement for trade DDGYTZ

### ISSUE THREAD

**Issue by aphex3k** [bisq-network/support#1329]
<img width="1470" alt="Screenshot 2023-01-30 at 5 09 42 PM" src="https://user-images.githubusercontent.com/433270/215633517-64304a96-c014-4ee6-837a-5eb5e85280ac.png">

<img width="1470" alt="Screenshot 2023-01-30 at 5 09 57 PM" src="https://user-images.githubusercontent.com/433270/215633524-54fd291b-7cf5-4e57-a9cc-abdd227d95bb.png">

Maker:  a2ff0a8429fc5b828696eec27b7a568b9ace4dfc7cec3f707d27a8d7c38fbcdd
Taker: 54a0ee3743256c3917014ca9abfe4d155f745303f1d43f69f088c1c8b1388fff
Deposit: N/A
BTC mining fees lost: 2,390 sat
Trade fees lost, please state if BSQ or BTC: [1.91 BSQ](https://bisq.mempool.emzy.de/tx/54a0ee3743256c3917014ca9abfe4d155f745303f1d43f69f088c1c8b1388fff)

Bisq version: v1.9.9
BTC address for reimbursement: 1Lf2K55uLXnYNqzggTSJzjAGLzA4wmgwf9

Note:

I am the taker of this trade. Seems to be the same issue as #1326 as far as I can tell.

**Comment by pazza83** [comment]
Hi @aphex3k 

Thanks can posting.

I can see you lost

BTC mining fees lost: 2,390 sat
Trade fees lost, please state if BSQ or BTC: [1.91 BSQ]
(https://bisq.mempool.emzy.de/tx/54a0ee3743256c3917014ca9abfe4d155f745303f1d43f69f088c1c8b1388fff)

Please can you also check your DAO is in sync. If your DAO is out of sync it will result in failed trades.

To check the status of your DAO please go to DAO > Network monitor.

If it is out of sync there is a button to press to re-sync it.


@leo816 please add to your list for reimbursement.

**Comment by leo816** [comment]
Reimbursement made with #1341
