### ISSUE TITLE
Fee reimbursement for trade 7575105, 9011281

### ISSUE THREAD

**Issue by crowley-occultist** [bisq-network/support#1330]
![sLKP9qADUD](https://user-images.githubusercontent.com/109865219/215779619-2ee07a8d-ae53-4cc6-8d8c-6c098b08c288.png)
![vauogSfKyN](https://user-images.githubusercontent.com/109865219/215779629-c7be0e74-180e-40e6-858e-494e75522290.png)

Maker:  ddd904bc5db317c7bf702c6e63dd79bb93c831b29b2b4b344367b1f1357f155b
Taker: e1943631c51a7ec93844c4717f9ba53b063b72fbeb75061461b9e05f568c73bc
BTC mining fees lost: Maker: 0.000031 BTC / Taker: 0.00006990 BTC

Maker:  90f3bfff4614df7b20599873c21e898edb6f222d04987b8161bf60ceeb4e15f3
Taker: 6862ecae845993e4f23979dcab6958c6f6ee8401d188385608b82a04c1ae3ff5
BTC mining fees lost: Maker: 0.00002450 BTC / Taker: 0.00006990 BTC

Bisq version: 1.9.9
BTC address for reimbursement: bc1qjmve5ssky5ldv8xy37hsm696zk804hc8neguuq

**Comment by pazza83** [comment]
Hi @crowley-occultist 

Thanks can posting.

I can see you lost...

For trade ID 9011281:

BTC mining fees lost:  0.000031 BTC
Trade fees lost, please state if BSQ or BTC: 0.37 BSQ

For trade ID 7575105:

BTC mining fees lost:  0.00002450 BTC
Trade fees lost, please state if BSQ or BTC: 0.37 BSQ

Please can you also check your DAO is in sync. If your DAO is out of sync it will result in failed trades.

To check the status of your DAO please go to DAO > Network monitor.

If it is out of sync there is a button to press to re-sync it.

@leo816 please add to your list for reimbursement.

**Comment by crowley-occultist** [comment]
> Hi @crowley-occultist
> 
> Thanks can posting.
> 
> I can see you lost
> 
> BTC mining fees lost: 0.000031 BTC Trade fees lost, please state if BSQ or BTC: 0.37 BSQ
> 
> Please can you also check your DAO is in sync. If your DAO is out of sync it will result in failed trades.
> 
> To check the status of your DAO please go to DAO > Network monitor.
> 
> If it is out of sync there is a button to press to re-sync it.
> 
> @leo816 please add to your list for reimbursement.

Hello,

Thank you for your response.
My DAO state appears to be synced correctly.
![Bisq_8bRBpTvf7d](https://user-images.githubusercontent.com/109865219/216661582-674804f5-36ca-4bed-9701-6cf970527c89.png)

**Comment by leo816** [comment]
Reimbursement made with #1341
