### ISSUE TITLE
Fee reimbursement for trade pbdl5

### ISSUE THREAD

**Issue by alvar0suarez** [bisq-network/support#1331]
>_The pbdl5 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/49781176/215973931-8abec24a-50cc-4508-b3fe-865d8c5db107.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  0.000031 BTC
Taker: 0.00007080 BTC
Deposit: 0.0050 BTC
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @alvar0suarez as you were the taker and there is no taker transaction ID you have not lost any funds in this trade.

Please can you also check your DAO is in sync. If your DAO is out of sync it will result in failed trades.

To check the status of your DAO please go to DAO > Network monitor.

If it is out of sync there is a button to press to re-sync it.
