### ISSUE TITLE
QWIYVBC - Timeout reached. Protocol did not complete in 120 sec.

### ISSUE THREAD

**Issue by tnylnng** [bisq-network/support#1334]
§
<img width="886" alt="Screenshot 2023-02-04 at 13 04 34" src="https://user-images.githubusercontent.com/419590/216769265-67994e13-c623-456c-a29b-2b4f520315f3.png">

After over a year all recent trades now fail with a similar message - I'm tempted to think that this is always to the same buyer?

DAO : sync - yes.
Bisq Network piers - 12
<img width="583" alt="Screenshot 2023-02-04 at 13 06 33" src="https://user-images.githubusercontent.com/419590/216769346-65748c82-243d-4c17-93a2-92466a5126b6.png">

Any thoughts on how to resolve this issue pls?

**Comment by ghost** [comment]
Could be a problem with the same buyer as you said, in which case that buyer needs to ensure their DAO is synced.  To prevent having more failed trades from that buyer you could add their onion to banned peers in your Bisq settings - the format is `onionaddress.onion:9999` as shown in the trade detail screen above.  Does your offer remain open afterwards?

**Comment by leo816** [comment]
please copy and past the maker and taker tx id in text format as indicated in the template
