### ISSUE TITLE
Refund Agent reimbursement For cycle 44

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/support#1336]
On Cycle 44, I paid 2.0968 BTC in refunds. 30 day average is 0.00003791 BSQ/BTC.
**56808.84 BSQ**  is the amount I ask the DAO to reimburse me. 2.71% printing cost was included.

https://github.com/bisq-network/roles/issues/93#issuecomment-1422877279
Previous reimbursement:  #1290

**Comment by refund-agent2** [comment]
445cefc1de608ea0d39055a663b9d03a175b14d2627ebaf6c1578c02fbe81181

**Comment by pazza83** [comment]
Hi @refund-agent2 I think you have linked to the wrong report cycle 43. It should be [cycle 44](https://github.com/bisq-network/roles/issues/93#issuecomment-1422877279).

The BTC amount is correct though 2.0968.

**Comment by refund-agent2** [comment]
Link fixed.

**Comment by refund-agent2** [comment]
Was accepted.
