### ISSUE TITLE
Fee reimbursement for trade djetgw

### ISSUE THREAD

**Issue by Nicehashbrown** [bisq-network/support#1339]
trade id: djetgw

![image](https://user-images.githubusercontent.com/125219001/218400520-712fc373-0d3d-4aeb-b3b0-c0bf434eece6.png)

(please follow link above for screenshot the image wont paste in here)

Maker: df0a7350dee81a64297cb6c6c100858f67e39913edb2032a2819e87dc29c5eb5
Taker: a67df5893174f9c46555e907b739dada8bc38ca2551b185b9372e871716cd817
Deposit: 0.002970 BTC 
BTC mining fees lost: 0.00001750 BTC  
Trade fees lost, please state if BSQ or BTC: ?

Bisq version:1.9.9
BTC address for reimbursement: bc1q6dfj6lvh9y7cczknyjww0mq8rny47nmw94tmve

**Comment by leo816** [comment]
fees are paid in btc

**Comment by leo816** [comment]
Reimbursement made with #1341
