### ISSUE TITLE
Fee reimbursement for trade 6224469

### ISSUE THREAD

**Issue by milyway** [bisq-network/support#1344]
![bisq failed trade 02202023](https://user-images.githubusercontent.com/40526863/220165446-6a3e5f2b-ea3f-4b90-96bb-895a085e2e33.jpg)

  

Maker: b18032cd6e34e20e45d6f430422a8ae7e6ae90f23ee0a2603a14b3ef0855b60a
Taker: N/A
Deposit: 0.01 BTC
BTC mining fees lost: 0.00006990 BTC
Trade fees lost, please state if BSQ or BTC: 0.01BTC
 

Bisq version: 1.9.9
BTC address for reimbursement: 1A2rVkaqVShbLVoCrP9GFUqEtNYcaFpyus

"The trade contract is not set" error. Please reimburse fees.
Thanks.

**Comment by pazza83** [comment]
Hi @milyway 

As you are the taker and there is no taker transaction and no deposit transaction you have not lost any BTC on this trade.

See here for more info:

https://bisq.wiki/Failed_Trades_-_Reimbursement_of_Trade_Fees_and_Miner_Fees
