### ISSUE TITLE
Fee reimbursement for trade qcnjrq7y

### ISSUE THREAD

**Issue by mazazz** [bisq-network/support#1345]
![Screenshot from 2023-02-22 09-22-20](https://user-images.githubusercontent.com/40358208/220551194-9c720de6-43c0-48c2-b7f5-ee97ae81c8d4.png)

Maker:  c5ce1b983b9e4b94e69ee8752a05ae3cac552ab8ab581f5c2bb317e130ae2287
Taker: db983ba7e7434cc10a94755e220f1a58b8f0fe78776846c6a739d4147f729c94
Deposit: 356e20add759e554ce9e2223a6e39a99d04c9fc1cbebd2a360c3bfd734550254 (failed)
BTC mining fees lost: 0.00009180 BTC

Bisq version: v1.9.9
BTC address for reimbursement: bc1q3gjcv5rjreruxdzd2et7y95q3a35czps2uw6ne

Thanks

**Comment by pazza83** [comment]
Hi @mazazz 

Thanks for posting.

I can see you lost BTC as a result of the failed trade. The amounts you lost are:

0.00009180 BTC mining fees
0.00006000 BTC trade fees 

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Reimbursement made with #1358
