### ISSUE TITLE
Fee reimbursement for trade 3819521

### ISSUE THREAD

**Issue by bobokiki** [bisq-network/support#1346]
![image](https://user-images.githubusercontent.com/121771146/221328334-6e0ade74-f9a2-4265-b0c4-596d8b007879.png)

Maker:    e5671d7f9dc11943fa9aa331939a97c41bc2cb6ceb1f02685b83d7214a4f49a7
Taker:      790e8f124a14eb32e1ea271c4f37a6fd6b1df47a767c10d93dd1b2e86d60cbf4
Deposit:  5231b27f9804a831d7bf33ccb11fb312ebb51c17fee47b6aad4a486133bb6fa8

BTC mining fees lost:  0.00006990 BTC  (I think this might be .0000233)
Trade fees lost         :  0.00007920 BTC

(I think my "fees lost" are INcorrect, not sure.  I think **TOTAL should be .0001025** )

Bisq version: 1.9.9
BTC address for reimbursement: bc1q6la50xld96hqgm2j8mpt89tzhqul065puf0uwp

**Comment by darawhelan** [comment]
Hi @bobokiki 

For the mining fees you lost 2,330 sats, so 0.00002330 BTC

You are correct for the trade fee loss. You lost 7,,920 sats, so 0.00007920 BTC.

The total sats loss is also correct at 0.0001025 BTC.

I will ask the reimbursement agent to make send you the sats back.

**Comment by bobokiki** [comment]
Sorry, I forgot about this.  It's such a small amount but I guess on principal I made the request.  Thank you for the support.  Bisq support is amazing!

**Comment by leo816** [comment]
Reimbursement made with #1358
