### ISSUE TITLE
Fee reimbursement for trade 693747

### ISSUE THREAD

**Issue by joenakamoto** [bisq-network/support#1348]
<img width="866" alt="Screenshot 2023-02-27 at 09 55 21" src="https://user-images.githubusercontent.com/126467348/221545495-30c43b74-2891-44be-9de0-557d049c5e15.png">

<img width="876" alt="Screenshot 2023-02-27 at 09 56 13" src="https://user-images.githubusercontent.com/126467348/221545681-f23cb03e-b06c-453b-8f3b-6724b652ee50.png">

** TX I.D.**: 693747-a28baa3d-d723-4f9e-8b33-3718ec31752d-199*, 
**Deposit**: 85ef738ce50a99549809ba34e3df3fe2b9a4e95e7b18b2af8033d294c5839f79, 
**Maker**: 1e25f4e1bdb104cca195fdeeac2c3d0beea10e3414e72d1dcdfe82cc2b8aef9e
**Taker**: 199188e0ad05e56ece6df98b44dc273480f4fbfffb757b135a9e00bcdf80a37a
BTC mining fees lost: 0.00006990 BTC
Bisq version: v1.9.9

BTC address for reimbursement:
bc1qzstydv3elp65fuyq2a656c9x8kgygddpt9cx99

**Comment by darawhelan** [comment]
Hi @joenakamoto 

For this trade you lost...

Miner fees 2,330 sats
Trade fees 15,312 sats

Total: 0.00017642 BTC

**Comment by leo816** [comment]
Reimbursement made with #1358
