### ISSUE TITLE
Fee reimbursement for trade BrRRspE

### ISSUE THREAD

**Issue by BLTCCS** [bisq-network/support#1349]
BrRRspE fee reimbursement

![BrRRspE](https://user-images.githubusercontent.com/112088187/221875556-f985fdcb-6dac-4c38-8713-c2acc526d612.png)

Maker:  d8a99e502174bce11a0635c8b518eb598a095971fae3e24de47160d7d00aa08f
Taker: d060c186b6fd8bb7c64cec4a7b2596c556af30f2c1f1e3d681381a7c0d230adc
Deposit: b756032bb5a73ca322aed8d7092be0a95a145763ea99ce622671163966e72134

Bisq version: 1.9.8
BTC address for reimbursement: bc1qveja34dejk2gdpzqyhjpmy7l8hn7llwrdfjv2d
Other info: I was maker

**Comment by darawhelan** [comment]
Hi @BLTCCS 

Your maker fee did not confirm for this trade.

The good news is you have not lost any sats
The bad news is your wallet is likely not in sync with the bitcoin blockchain

You should do an [SPV resync]([https://bisq.wiki › Resyncing_SPV_file](https://bisq.wiki/Resyncing_SPV_file)). Once you have done this your wallet with show the correct amount of BTC in it.

**Comment by BLTCCS** [comment]
Hi,
great, thanks for resolving, I already resynced so this should be fixed
Best
