### ISSUE TITLE
Fee reimbursement for trade 0350758

### ISSUE THREAD

**Issue by zdick** [bisq-network/support#1350]
![bisq](https://user-images.githubusercontent.com/22180386/221932934-cf7266fa-58c1-49ce-9fb8-21ed88d0c91d.png)

Maker:  f4fc2947e9a99e6869787e8df53b974fc6e7b9a65c1c9cc4fb31f8167c0e4a0e
Taker: 53dabab5d7e65b22c3911627a88efabc74ca1c5b8351df61d616cc9730841a96
Deposit: N/A
BTC mining fees lost: 0.00005130
Trade fees lost, please state if BSQ or BTC: BSQ, don't know how much :-/

Bisq version: 1.9.9
BTC address for reimbursement: bc1q0hdn6c7pk7p8vett5ax6u7v4l08prjuds2tqz6

Other notes:

The trade protocol encountered some problems.
The deposit transaction (the 2-of-2 multisig transaction) is missing.
Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: [1]

**Comment by darawhelan** [comment]
Hi @zdick 

Looks like this trade failed as either yourself or the buyer's DAO was out of sync.

You can check the sate of your DAO in the Bisq application. Go to DAO and then click the 'Network monitor' tab. Your DAO status will then be displayed. If it is out of sync it will prompt you to resync.

You lost...

5,130 sats in mining fees
0.14 BSQ in trade fees (you can confirm this on a BSQ explorer should you wish, just look for the bit that says burnt amount to see your fees)

I will ask the reimbursement agent to compensate you.

**Comment by zdick** [comment]
Thank you. My DAO is in consensus, also I made successful trades few minutes after this fail.

**Comment by zdick** [comment]
@darawhelan any updates pls?

**Comment by leo816** [comment]
Reimbursement made with #1358
