### ISSUE TITLE
Fee reimbursement for trade 117705

### ISSUE THREAD

**Issue by ga-moto** [bisq-network/support#1351]
![2023-03-06-100530_891x647_scrot](https://user-images.githubusercontent.com/107431336/223118433-9b89847d-f593-42df-840f-7918a05dff01.png)

Maker: 91aec15cbd31d8e07b3d4936eece3628fb8246f99075dddd8ddbf9ba03a07cb2
Taker: N/A
Deposit: N/A
BTC mining fees lost: 0.00002975 BTC
Trade fees lost: I can't find that
Bisq version: 1.9.9
BTC address for reimbursement: bc1q3x7y3w30v82xtlfgzfyh3k0e2nqm445xu895u6

Other notes:

I think I may have updated Bisq as I saw the error to see if the problem went away automatically.

The DAO says it is in sync now and I've done another trade after this.

The taker for this offer has sent me a message saying that them had deposited the money for me, but from what I could see on my side they have not actually done that. Maybe they were trying to scam me while simultaneously triggering this error?

**Comment by darawhelan** [comment]
Hi @ga-moto 

Thanks for opening this issue.

Either it went though on a subsequent attempt by a taker, or the trade was confirmed and your Bisq UI is not showing the trade as successful.

The successful deposit transaction is: 4f16cdb336201c892d21de7d699febc4104c41d2353594525fc771e75ba56cae

You have not lost any funds on this trade.

I would recommend you do an SPV resync to make sure you wallet is showing the correct info:

https://bisq.wiki/Resyncing_SPV_file

>The taker for this offer has sent me a message saying that them had deposited the money for me, but from what I could see on my side they have not actually done that. Maybe they were trying to scam me while simultaneously triggering this error?

Please can you do the SPV resync and comment back here if you see the trade as successful?
