### ISSUE TITLE
Fee reimbursement for trade 4g2XAa

### ISSUE THREAD

**Issue by lordbah** [bisq-network/support#1352]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/24962539/223123003-ecd0e574-d96a-442e-a5e1-2690fa1c3de8.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  0f9ef96f30deb520971af98795b81cf3a9840151f8ecdb28bb23b59f9a673936
Taker: 0565f46427c0fd07a901ad1a89797ef7214452e7f170d273e16ed0fd78076432
Deposit: cff73d5f02f2fcdc0b7b08c50078f13f544b2da23cf7ab1393164211f01c3151
BTC mining fees lost: 0.00008496 BTC
Trade fees lost, please state if BSQ or BTC: 0.001650 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.9
BTC address for reimbursement: bc1q0frhgd0vugw2z7nre3y777mxwz5q03qs0cqx4u

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:
Warning
There is an issue with a missing or invalid transaction.

Please do NOT send the fiat or altcoin payment.

Open a support ticket to get assistance from a Mediator.

Error message: Deposit transaction is null or has unexpected input count

Maker fee txid was displayed in green but I can't find it on a blockchain explorer.
Tried SPV resync but it didn't resolve the issue.
DAO state is "in consensus".

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @lordbah 

Looks like this trade failed as the makers BTC wallet was out of sync.

You lost...

2,832 sats in mining fees ($.64)
5,000 sats in trade fees ($1.10)

I will ask the reimbursement agent to compensate you.

**Comment by leo816** [comment]
Reimbursement made with #1358
