### ISSUE TITLE
Reimbursement for oqlmdma6mn7kjgxqiicw737qtqlaoosg34h535dlada7cr2pc24u74id.onion:9999

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/support#1355]
![RYVXTY](https://user-images.githubusercontent.com/36059034/224515366-0960fac1-5767-4b14-9471-6e3270920576.PNG)

Reimbursement for trade rYVxty-25a25585-a6b7-4792-959b-ae0aa471e7af-199

I am BTC buyer as maker
Trade amount and asset: 1 BTC for 151.27 XMR
Deposit amount: 0.15 BTC

Maker txid: 8cdb849be8b773a77d5d66f4dadf335b9eb7e1d198fec73e3d8f4524c0e02094
Taker txid: c164765fd9bfffd6a9172df71f598bac1bd431615fab8d1e528adb88cc60f32c
Deposit tx: d3dbef06cd37f3f7a435f0ad22921c276ae04f6f6b62bc3e4dce5c713cd98b50
Delayed payout tx: 56b81322c3de9e3dbc9cd711d96104f8dfb47e5bfb0924c22dfff14dbcdfe9a7

**Reimbursement amount:** 0.65 BTC / 0.00003596 BSQ x 1.0286 = **18592.60 BSQ**
Reason for reimbursement: Trader not responding

#### Mediation suggestion

System message: Mediator's dispute summary:
Mediator's node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Ticket closed on 28 Feb 2023 23:56:14
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: rYVxty-25a25585-a6b7-4792-959b-ae0aa471e7af-199
Currency: XMR
Reason for dispute: Peer was late
Payout suggestion: BTC buyer gets trade amount plus compensation 5%
Trade amount: 1.00 BTC
Payout amount for BTC buyer: 1.20 BTC
Payout amount for BTC seller: 0.10 BTC

Summary notes:
BTC buyer sent XMR (confirmed on-chain)
BTC seller did not confirm payment in trade window and took 2 days to respond to mediator

BTC buyer requested compensation for the seller not releasing in the trade window

-----BEGIN SIGNATURE-----
302c02141f1ab4515bec956ee6340fa3ebfb8be90cf50be602143b224d0a310435049c276eb88ed8ce6f871ca20c
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator

#### Arbitration summary (Arbitrator can't produce proper arbitration summaries as trades can't be closed due to a bug)

Arbitration ticket closed with tx: ccbd4547491e08160688c0d10b9c486eb559d0a6d9fe0113ee5ac0f1a05908ac

BTC buyer receives: 0.5 BTC
BTC seller receives: 0 BTC

Buyer should receive 1.15 (1BTC trade amount, 0.15BC security deposit).

Seller did not release BTC or reply, proof of payment has been provided. As the trade amount is over 0.5BTC, only 0.5BTC are paid from the arbitrator, the 0.65BTC left will have to be reimbursed by the DAO in BSQ. There is no compensation: https://github.com/bisq-network/proposals/issues/386

Arbitration secret: pjv3xgu
@refund-agent2
@pazza83

**Comment by refund-agent2** [comment]
Arbitration secret is correct.

Printing cost is 2.86% and 30D averageg is 3596 sats.
You should claim 0.65 / 0.00003596 * 1.0286 = **18592.60 BSQ**

Edit the first post, submit the reimbursement request to the DAO and share the txid in a comment.

**Comment by onlymarcus** [comment]
> Arbitration secret is correct.
> 
> Printing cost is 2.86% and 30D averageg is 3596 sats. You should claim 0.65 / 0.00003596 * 1.0286 = **18592.60 BSQ**
> 
> Edit the first post, submit the reimbursement request to the DAO and share the txid in a comment.

Proposal transaction ID
5af27af84bb0794759549505b5ccecf0052ecab15d4777a3c5aaf1843b8c4896

**Comment by onlymarcus** [comment]
OK. I received the BSQ. I made an offer to sell them, I would like burningman to buy please at the average price calculated here.
Offer id's:
DRAOY-bcfe5a66-1060-4fa6-9ea6-981c6c13ffa6-199
GmRSp-6e4e1694-d673-46c0-88af-721e5d350689-199
UYYJD-d560e45d-57d6-4fa1-b5b6-528e9496e10d-199
857670-ee41573b-e5ab-4c40-81fb-32748b5991c6-199
465663-82e922cb-c18a-44be-a594-fafc9ecee400-199
qogv0e-51af96f8-3fb4-44dd-ad32-28f5b16c0162-199

@refund-agent2

**Comment by pazza83** [comment]
Hi @onlymarcus 

FYI @burningman3's role is coming to an end.

They are no longer receiving significant amounts of BTC to their donation addresses. Currently they have about 0.33 BTC.

See their recent comment here: https://github.com/bisq-network/roles/issues/80#issuecomment-1465230598

**Comment by onlymarcus** [comment]
My onion address:
rcudj5a57z6bjvukydn4qdmyxvecnaqeuiz2s66fpk7kuooht3c5msyd.onion:9999

**Comment by onlymarcus** [comment]
my onion: rcudj5a57z6bjvukydn4qdmyxvecnaqeuiz2s66fpk7kuooht3c5msyd.onion:9999

I received the BSQ at an average price of 0.00003596 and I couldn't sell it, today it's at an average price of 0.00003229. An 11.36% loss on 18,592.60 bsq. I was harmed by the XMR buyer that stopped responding. I think that BISQ should review this proposal of not reimbursing the maker. It is the maker that makes BISQ have offers and attract customers.
I would like priority to be given to offers to sell bsq from those who were harmed.

**Comment by onlymarcus** [comment]
Since I received this refund in BSQ I have not been able to sell at the average price of 0.00003596. The BSQ has already dropped 33% due to the fact that we no longer have the burningman to make purchases, we only have sales and sales sink the price. I want to propose an update on this refund, or if anyone here buys my bsq for 000003596. I had to change my bsq wallet because it wasn't syncing.
My onion "rcudj5a57z6bjvukydn4qdmyxvecnaqeuiz2s66fpk7kuooht3c5msyd.onion"
