### ISSUE TITLE
Reimbursement for trade FUWSE

### ISSUE THREAD

**Issue by 333shine** [bisq-network/support#1357]
I am BTC buyer as maker
Trade amount and asset: 1 BTC for 153.53 XMR
Deposit amount: 0.225 BTC

Maker txid: 4ee09232fa301a6304fdb6ebcbee5911b6311046842c945b42def951cb9fcbcf
Taker txid: d26f01c8f818b214d50ca0d00a94d66d0d5d4a6f1b7ecad2893f9976f8d15271
Deposit tx: 5da8e1fae4744426bdd9125ae66ff4397d26bfec860697841ba2717b224ecf94
Delayed payout tx: 5504a73ce4a2edf97edfae3dbded0d8282428d6530691a244ad8720b936ed64f

**Reimbursement amount:** 0.725 BTC / 0.00003593 BSQ x 1.0286 = **`20755.22 BSQ`**
Reason for reimbursement: Trader not responding.

#### Mediation suggestion
System message: Mediator's dispute summary:
Mediator's node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Ticket closed on 28 Feb 2023 23:51:26
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: FUWSE
Currency: XMR
Reason for dispute: Peer was late
Payout suggestion: BTC buyer gets trade amount payout
Trade amount: 1.00 BTC
Payout amount for BTC buyer: 1.2250 BTC
Payout amount for BTC seller: 0.2250 BTC

Summary notes:
BTC buyer sent XMR (confirmed on-chain)
BTC seller confirmed payment later

Trade completed successfully

-----BEGIN SIGNATURE-----
302d02143a3109d286bb3ed445ebf1b764416d1b2bd7101b021500802e8950f7fa9b3db5d9f8149cd565c327f1485c
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator

#### Arbitration summary (Arbitrator can't produce proper arbitration summaries as trades can't be closed due to a bug)

Arbitration ticket closed with tx: 7ef20aa6ea30e31ca6929f05feee44f04370cb1f2175d651092e5a0471a85b9f

BTC buyer receives: 0.5 BTC
BTC seller receives: 0 BTC

Buyer should get 1.225BTC (1BTC trade amount + 0.225 BTC security deposit)

Seller did not release BTC or reply, proof of payment has been provided. As the trade amount is over 0.5BTC, only 0.5BTC are paid in arbitration. The 0.725BTC left will have to be reimbursed by the DAO in BSQ. There is no compensation: https://github.com/bisq-network/proposals/issues/386

Arbitration secret: fu7kysi

**Comment by refund-agent2** [comment]
Go ahead with the reimbursement request and publish here the resulting txid.

**Comment by 333shine** [comment]
Proposal transaction ID:
37cf5e0d6ce75718fc3117c88da161d2a08058c721ab5a1d4a6eae9ddd424446

**Comment by 333shine** [comment]
Hi leo816,
I thought this reimbursement issue would last until the reimbursed BSQ would be sold out.
I am sorry to say that I, a casual customer not interested in DAO so much, can't rest assured until then.
Although more than three months have passed since I was reimbursed with BSQ, almost all of them remain unsold.
