### ISSUE TITLE
Fee reimbursement for trade 8071ad6220458164896d125d9a049bd8453b99bd7a5440bcbe5d24cb30ac2094

### ISSUE THREAD

**Issue by criptoxp** [bisq-network/support#1360]
>_The 8071ad6220458164896d125d9a049bd8453b99bd7a5440bcbe5d24cb30ac2094part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/128519935/226703628-5a49c43a-771d-46bd-86f6-e50dc7c1cca8.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
@criptoxp please can you resubmit using the template, please look at other reimbursement issues for examples
