### ISSUE TITLE
Fee reimbursement for trade 9008629-ccdd0841-c104-4474-921e-59b571d27172-199

### ISSUE THREAD

**Issue by criptoxp** [bisq-network/support#1361]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/128519935/226715344-07239b82-85b1-45c2-b7d3-cc753031f113.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 8071ad6220458164896d125d9a049bd8453b99bd7a5440bcbe5d24cb30ac2094
Taker: N/A
Deposit: N/A
BTC mining fees lost: 0.00002695 eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
@criptoxp as you were the taker and there is no taker transaction no fees were lost by yourself in this trade.

You should make sure your wallet is correctly synced to avoid any future trades failing by doing an [spv resync](https://bisq.wiki/Resyncing_SPV_file)
