### ISSUE TITLE
Fee reimbursement for trade ZCrCP

### ISSUE THREAD

**Issue by smith2211** [bisq-network/support#1362]
![image](https://user-images.githubusercontent.com/128532350/226720612-7e62c232-5d05-4c91-bc72-ea4fd5d9ae50.png)

Trade Id: ZCrCP-2c0ddc44-dbab-4b4e-93f7-6dc42726b56f-199
Maker Tx:  0672bef853ab5440c256140d7160762f4ef4ade5fe23ebed2023c5e72058a583
Taker Tx: 2a9aa1407397ce9b59da4fcb43c8bcea44313614e3b4def4f0ead6f7c9a88c31
Bisq version: 1.9.9
BTC address for reimbursement: bc1q9dy5x505e2gryq7lll67cqpeknrf88g26qg5z4

Timeout reached. Protocol did not complete in 120 sec. Please reimburse fees.
Thanks.

**Comment by darawhelan** [comment]
@smith2211 please can you re-submit the image to show if you are the buyer or seller and maker or taker.

**Comment by smith2211** [comment]
Yes sure:

![image](https://user-images.githubusercontent.com/128532350/226757849-b0499545-1586-4b79-9274-ae8e307beff4.png)

Thank you

**Comment by darawhelan** [comment]
Thank you

Looks like this trade failed as either yourself or the buyer's DAO was out of sync.

You can check the sate of your DAO in the Bisq application. Go to DAO and then click the 'Network monitor' tab. Your DAO status will then be displayed. If it is out of sync it will prompt you to resync.

For this trade you lost:

Trade fees: 0.00054120 BTC
Miner fees: 0.00008556 BTC

So a total of **0.00062676 BTC** was lost in this trade.

I will ask the reimbursement agent to make send you the sats back in the next reimbursement cycle (might be in April or May).

**Comment by smith2211** [comment]
There is a state of DAO - Your local node is in consensus with the network.

Thank you. And continue development with this great app :)

**Comment by darawhelan** [comment]
Great, must have been your peer that is out of sync

**Comment by leo816** [comment]
payout made with #1389
