### ISSUE TITLE
Fee reimbursement for trade KkMCNfL

### ISSUE THREAD

**Issue by bisqKkMC** [bisq-network/support#1365]
I'm the maker in this transaction

![image](https://user-images.githubusercontent.com/901536/227348050-980977c7-bbff-437e-9431-d0a111f062ae.png)

Maker:  ab0ea9e3d8ee931ee132cb6696a0805bb68e5744c96000654693f81f169938db
Taker: cafaa3c327ec6f0688606c5b9ac7e9d9c79396217e463c8061bf1f76c0492a7c
Deposit: N/A
BTC mining fees lost: 3,325 sat
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

Bisq version: 1.9.9
BTC address for reimbursement: bc1qw7e89g8mtk3w2qy4c2qk2cyuzte4d4tcrglj5c

**Comment by darawhelan** [comment]
Hi @bisqKkMC 

Looks like this trade failed as either yourself or the buyer's DAO was out of sync.

You can check the sate of your DAO in the Bisq application. Go to DAO and then click the 'Network monitor' tab. Your DAO status will then be displayed. If it is out of sync it will prompt you to resync.

I can confirm you lost funds on this trade.

Miner fee: 0.00003325 BTC
Trade fee: 0.00005000 BTC

**Total lost:  0.00008325 BTC**

I will ask the reimbursement agent to make send you the sats back in the next reimbursement cycle (might be in April or May).

**Comment by leo816** [comment]
payout made with #1389
