### ISSUE TITLE
Fee reimbursement for trade wcQgKfX

### ISSUE THREAD

**Issue by jappl987** [bisq-network/support#1366]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/128808502/227514169-0fc30369-b7ef-4f85-bd61-0b3fcf6c995a.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @jappl987 

Please can you let me know the following:

- Maker transaction ID
- Taker transaction ID
- Deposit transaction ID
- BTC address for reimbursement

**Comment by jappl987** [comment]
Hi I think these are correct but can't find the Deposit transaction ID  

  

regards  

  

StartMail makes private and encrypted email easy. [Try it here for
free](https://www.startmail.com/en/#whystartmail)!  

Receive a 50% discount on a new subscription through the [referral
program](https://support.startmail.com/hc/en-
us/articles/360009662977-StartMail-Referral-Program-share-the-freedom-of-
private-email).

**Comment by darawhelan** [comment]
Can you copy and paste what you have here for them, also include BTC address for reimbursement
