### ISSUE TITLE
Fee reimbursement for trade 47134

### ISSUE THREAD

**Issue by MiamiRetro** [bisq-network/support#1367]
Contract as json:
{
  "offerPayload": {
    "id": "47134-e84bca26-7b32-45e3-9e03-45a8484d0b60-199",
    "date": 1679226213210,
    "ownerNodeAddress": {
      "hostName": "g2gjjs26nmb5jvubbhfcgfxdrcctfao4uplonpimlggvcu6byvvwaaid.onion",
      "port": 9999
    },
    "direction": "SELL",
    "price": 0,
    "marketPriceMargin": 0.029,
    "useMarketBasedPrice": true,
    "amount": 2000000,
    "minAmount": 2000000,
    "baseCurrencyCode": "BTC",
    "counterCurrencyCode": "GBP",
    "arbitratorNodeAddresses": [],
    "mediatorNodeAddresses": [
      {
        "hostName": "6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion",
        "port": 9999
      },
      {
        "hostName": "7hkpotiyaukuzcfy6faihjaols5r2mkysz7bm3wrhhbpbphzz3zbwyqd.onion",
        "port": 9999
      }
    ],
    "paymentMethodId": "FASTER_PAYMENTS",
    "makerPaymentAccountId": "bc861eaa-0738-4333-9395-29e734440783",
    "offerFeePaymentTxId": "d8bf60eb5fd1b44d8b8610c9d7fdefb42f863addb6b2846186cf1e9b4a2fd4d8",
    "versionNr": "1.9.9",
    "blockHeightAtOfferCreation": 781502,
    "txFee": 5264,
    "makerFee": 5000,
    "isCurrencyForMakerFeeBtc": true,
    "buyerSecurityDeposit": 500000,
    "sellerSecurityDeposit": 500000,
    "maxTradeLimit": 12000000,
    "maxTradePeriod": 86400000,
    "useAutoClose": false,
    "useReOpenAfterAutoClose": false,
    "lowerClosePrice": 0,
    "upperClosePrice": 0,
    "isPrivateOffer": false,
    "extraDataMap": {
      "capabilities": "0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17",
      "accountAgeWitnessHash": "b51fb3317424f1ebef0e9eb5d46efc9b295d28c6"
    },
    "protocolVersion": 4
  },
  "tradeAmount": 2000000,
  "tradePrice": 232506934,
  "takerFeeTxID": "60238ffbf56fec395420df8711a736596e9737e65c5c162a7611ba950ef96211",
  "buyerNodeAddress": {
    "hostName": "qz6b3cpg45sc5yuof3klnl6dcaudrkqsubqtfvn2i2o7ueozlvtxhzid.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "g2gjjs26nmb5jvubbhfcgfxdrcctfao4uplonpimlggvcu6byvvwaaid.onion",
    "port": 9999
  },
  "mediatorNodeAddress": {
    "hostName": "6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion",
    "port": 9999
  },
  "isBuyerMakerAndSellerTaker": false,
  "makerAccountId": "1572442522",
  "takerAccountId": "1233438983",
  "makerPayoutAddressString": "bc1qqfnnvt7gwukr7jtlwdfep3xrh4f6s47ezcrpyn",
  "takerPayoutAddressString": "bc1qajjnupfy7revls3zy8xu5kar5enssz56cmhn5w",
  "lockTime": 785344,
  "refundAgentNodeAddress": {
    "hostName": "3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion",
    "port": 9999
  },
  "hashOfMakersPaymentAccountPayload": [
    46,
    -61,
    -51,
    -83,
    -35,
    -79,
    39,
    -101,
    -93,
    48,
    26,
    -95,
    -69,
    121,
    34,
    -78,
    -101,
    -22,
    -40,
    -127
  ],
  "hashOfTakersPaymentAccountPayload": [
    15,
    -79,
    52,
    -53,
    117,
    -120,
    -28,
    37,
    -41,
    -49,
    114,
    48,
    124,
    71,
    -5,
    22,
    77,
    106,
    -34,
    -49
  ],
  "makerPaymentMethodId": "FASTER_PAYMENTS",
  "takerPaymentMethodId": "FASTER_PAYMENTS"
}

Other detail data:

BuyerMultiSigPubKeyHex: 02e40bb23a454fe41d73f6ab5294a7c4583cad613dc4b79de82a68039fa0c3f384
SellerMultiSigPubKeyHex: 0205cf3f721cd4af65461b8082231004f2e97296a07dcb979adbf1ed4d1f1fee08

BuyersAccountAge: Payment account age not known.
SellersAccountAge: Payment account age not known.

Selected mediator: pazza83
Selected arbitrator (refund agent): refundagent2
<img width="901" alt="Screenshot 2023-03-25 at 10 16 14 PM" src="https://user-images.githubusercontent.com/107248822/227726109-fa612ea5-4991-4b01-86f8-ffd10d4a85fe.png">

**Comment by darawhelan** [comment]
Hi @MiamiRetro 

Please can you edit the post to include info from the template: https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX
