### ISSUE TITLE
Fee reimbursement for trade xr8tzf

### ISSUE THREAD

**Issue by owtyahyg6** [bisq-network/support#1369]
![screenshot](https://user-images.githubusercontent.com/120664498/228714717-5f00ee36-0d6c-4d09-93ef-521f5437b988.png)

Maker:  f94dad59403db309b7efc43747c9267fd7a72c3f8c9dd58defbf18f29694ecd6
Taker: N/A
Deposit: N/A
Security deposit: Buyer: 0.0150 BTC / Seller: 0.0150 BTC
Mining fee: Maker: 0.00004025 BTC / Taker: 0.00013725 BTC

Bisq version: v1.9.9

"An error occurred at task: MakerProcessesInputsForDepositTxRequest
Exception message: takersBurningManSelectionHeight does no match makersBurningManSelectionHeight"

Please reimburse fees.
Thanks!

**Comment by owtyahyg6** [comment]
I was able to reactivate the offer, so I guess there is nothing to reimburse? Sorry it is the first time I experience a trade failure... Thanks!

**Comment by darawhelan** [comment]
Yes, it was a problem with the taker so the trade is fine to complete as normal with another taker.
