### ISSUE TITLE
Fee reimbursement for trade rTuuqP

### ISSUE THREAD

**Issue by crtstevens** [bisq-network/support#1371]
![BisqScreenShot](https://user-images.githubusercontent.com/129704439/229392415-8061d265-769c-49af-9e12-0a7927f78fc9.png)

Maker:  dc85d69d7c9f95db6bf88b596444eaa1d9cfc2e538be74efe39791a0fcc2e631
Taker: 6d3e19fbe1453d3e0361719fc60a2709963aca75b5aae808fd0816b3915258ad
Deposit: N/A

Bisq version: 1.9.9
BTC address for reimbursement: bc1q6v3nvuy7vev20rejvmut5eth3uee3nthws47ct

Other notes: "An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same."

Thanks!

**Comment by darawhelan** [comment]
@gittru736 

Please can you edit the screen shot to show if you were the buyer or seller, maker or taker.

**Comment by crtstevens** [comment]
@darawhelan I was buyer (maker)
![Screen Shot 2023-04-09 at 4 54 34 PM](https://user-images.githubusercontent.com/129704439/230798292-98f752f5-85de-44ae-93a8-f2f019b0b83f.png)

**Comment by darawhelan** [comment]
Thanks, you lost on this failed trade:

Miner fees: 0.00003325
Taker fees: 0.00005000 

**Total: 0.00008325 BTC** 

@leo816 please can you add this to your next reimbursement batch

**Comment by leo816** [comment]
Payout made with #1389
