### ISSUE TITLE
Fee reimbursement for trade 76242

### ISSUE THREAD

**Issue by AlexPetzinger** [bisq-network/support#1372]
Greetings:

I attempted to purchase BTC but encountered some issue with Tor connectivity.   I hit "Confirm" to  take offer but could not proceed because Bisq complained I had no incoming Tor client, and thus needed to wait possibly several hours.  This is what I eventually saw:

SCREENSHOT HERE
[4-4-23-transaction-incomplete.pdf](https://github.com/bisq-network/support/files/11150382/4-4-23-transaction-incomplete.pdf)

I am not sure what fees I am missing.  When initiating the purchase I funded my Bisq wallet in .008959 BTC to continue the transaction. Then I tried to proceed until I encountered the Tor problem

**Comment by AlexPetzinger** [comment]
Trade ID:
      76242-31f7cb00-0260-4d94-ac68-c9ee61a3935a-199
Security deposit: 
     Maker: 0.00004136 BTC / Taker: 0.00010485 BTC
Mining fee:
     Maker: 0.00004136 BTC / Taker: 0.00010485 BTC

Bisq version 1.9.9

Error message
Timeout reached. Protocol did not complete in 120 sec.

BTC address for reimbursement:   bc1q820xusjv4f65vq6dmvhu0v5djj6vplev8kqjx5

**Comment by AlexPetzinger** [comment]
Thank you for your attention!

**Comment by darawhelan** [comment]
Hi @AlexPetzinger 

The screen shot you posted shows a failed trade.

Please can you copy and paste the maker transaction ID below so I can check it.

I would also suggest you resync your BTC wallet. See: https://bisq.wiki/Resyncing_SPV_file

**Comment by AlexPetzinger** [comment]
Greetings:

Thank you for trying to resolve this issue.  I am careful to date and take screen shots of every step of any transaction I do to document everything, particularly since I am new to Bisq.  Hopefully what I've included will help you.  In Bisq, under Portofolio, I see a red error to the far right of this deal that suggests that I "move to failed trades".   I guess I should do so?

Thanks again,
Alex
________________________________

**Comment by darawhelan** [comment]
Please can you copy and paste the maker transaction ID starting: 69fd....
