### ISSUE TITLE
Fee reimbursement for trade1a6uqys7

### ISSUE THREAD

**Issue by Bufkat** [bisq-network/support#1373]
![image](https://user-images.githubusercontent.com/129883210/229857150-5a3a7f5a-dc1d-40d6-b946-7b905e9c6158.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........819e3b3a24ba939eb13fc7992e74d6e1e64d919adad5f45754ad56072259483c
Taker: ...........b4bb1b1f90fe491b121d881798f0d3f4c66d5e00b2d0d0d4faa5b825e42f78c9
Deposit: ..........a0ecb3abfa3cde42d1c790b59a27e65480f24c56b392e43ac1568c88e7c3508f
BTC mining fees lost: .......... Maker: 0.00004025 BTC / Taker: 0.00007170 BTC 
Trade fees lost, please state if BSQ or BTC: .......... Buyer: 0.0060 BTC / Seller: 0.0060 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.9
BTC address for reimbursement: bc1quxqhezltmnfk2g2hce4j0hysadz59h4ztc5nh0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @Bufkat 

This trade completed successfully.

Must have been taken by another taker.

Deposit ID: a0ecb3abfa3cde42d1c790b59a27e65480f24c56b392e43ac1568c88e7c3508f
Payout ID: 731763eb75867da71cc1ba9bce87535f9dd5fc86c8d94f7f7009e4cbd765c35e 

No funds were lost
