### ISSUE TITLE
Fee reimbursement for trade sknzlfH6

### ISSUE THREAD

**Issue by iye81** [bisq-network/support#1374]
![imagen](https://user-images.githubusercontent.com/130143293/230584935-27a40bbb-7fd8-4abb-814f-125714ea1131.png)
>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  06ee3def0428520a3f7e7e4667718b223a52f6870f1d2f25a8cce7d2375dee29
Taker: c8629041b92dde61fb92362228a49f0e682734c93744847c8c41dc9377c22757
Deposit: 0.00774876
BTC mining fees lost: Comprador: 0.00774876 BTC / Vendedor: 0.00774876 BTC
Trade fees lost, please state if BSQ or BTC: Creador: 0.00002625 BTC / Tomador: 0.00009087 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.9
BTC address for reimbursement: bc1q6gpzsnv7cv3wua044av2mlc9t4sl47fzelqqd4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

**Comment by darawhelan** [comment]
Hi @iye81 

Thanks for posting.

On this trade you lost:

Trade fee: 0.00037200
Miner fee: 0.00003029

**Total: 0.00040229 BTC**

@leo816 please can you reimburse this user in your next batch.

**Comment by leo816** [comment]
payout made with #1389
