### ISSUE TITLE
Fee reimbursement for trade iVRlF-3e5a332f-caca-49ea-83df-2aa083a01572-199

### ISSUE THREAD

**Issue by greengardengnome** [bisq-network/support#1375]
![bilde](https://user-images.githubusercontent.com/84743701/230586993-8a1ac198-06ad-4366-a0b7-0916cf4d3090.png)

Maker:  eeff26567e680706935b5d69bd54ed5500e8c0d149bdd695dd57ba059d1598d0
Taker: a186ecda4281f0377f29748a0684e225399dc1e1c4b245077e353b4ab19b931e
Deposit: N/A
Trade fees lost: 0.00013029 BTC 

![bilde](https://user-images.githubusercontent.com/84743701/230591421-52856191-fbb9-455e-9bc8-821eb4d42266.png)

Bisq version: 1.9.9

BTC address for reimbursement: 1P43mgSSukm5dgPqNSkwr42U5y3DGZhqKZ

Error message I got:
"An error occurred when taking the offer. Timeout reached. Protocol did not complete in 120 sec."

**Comment by didried** [comment]
![Ekrānattēls 2023-04-07 17-23-40](https://user-images.githubusercontent.com/16423345/230625666-10d71393-71f7-4e1a-bf8e-fc7d1f9da079.png)

Maker:  eeff26567e680706935b5d69bd54ed5500e8c0d149bdd695dd57ba059d1598d0
Taker: a186ecda4281f0377f29748a0684e225399dc1e1c4b245077e353b4ab19b931e
Deposit: N/A
BTC mining fees lost: 0.00006860 BTC
Trade fees lost, please state if BSQ or BTC: 0.14 BSQ / 0.00006846 BTC

![Ekrānattēls 2023-04-07 17-22-03](https://user-images.githubusercontent.com/16423345/230629071-1524909d-594c-4b2d-8429-fb270bf11fa3.png)

Bisq version: 1.9.9
BTC address for reimbursement: bc1qnpp5nzd9p2yp6ym7wfv4fnuppvgx65ufh4nvav

Other notes: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

**Comment by darawhelan** [comment]
@greengardengnome 

Thanks for posting.

I can see this trade failed and you lost miner and trade fees.

Please go to DAO section then click Network Monitor to see the status of your DAO. If it is out of sync please resync it.

You lost:

0.0001 BTC in trade fees and 0.00003029 BTC in miner fees.

Total: 0.00013029 BTC

@leo816 please can you reimburse this user in your next batch.

**Comment by darawhelan** [comment]
@didried 

Thanks for posting.

I can see this trade failed and you lost miner and trade fees.

Please go to DAO section then click Network Monitor to see the status of your DAO. If it is out of sync please resync it.

You lost:

0.14 BSQ in trade fees and 0.00006860 BTC in miner fees.

@leo816 please can you reimburse this user in your next batch.

**Comment by leo816** [comment]
Payout made with #1389
