### ISSUE TITLE
Fee reimbursement for trade vxpvii

### ISSUE THREAD

**Issue by renmp** [bisq-network/support#1377]
>_The vxpvii part in the issue title are the first characters of the Trade ID before the "vxpvii-426b65f8-4d3e-452a-a61d-dc5793f29b57-199" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
@renmp 

Please edit your post to include everything in the template

**Comment by renmp** [comment]
Hi darawhelan, that's all that's left...
![BISQ](https://user-images.githubusercontent.com/128604309/230913371-3bb51f18-fa2b-4e19-a77f-d1c99e2c74ad.jpg)

**Comment by darawhelan** [comment]
Hi please see the example of other reimbursements request here to see what you need to include: https://github.com/bisq-network/support/issues

**Comment by renmp** [comment]
Hi darawhelan
All good
In April/07, only the transaction carried out
![image](https://user-images.githubusercontent.com/128604309/230960578-440b5925-516f-4bba-895e-851b6006863b.png)
