### ISSUE TITLE
Fee reimbursement for trade RQGRZGNV-40774e7e-4ab5-4105-a2c1-43ec7719dd4d-199

### ISSUE THREAD

**Issue by amtexugo** [bisq-network/support#1378]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Capturar_2023_04_06_22_59_29_673](https://user-images.githubusercontent.com/127704297/230704423-ca7fd427-38e4-4b2b-9bd7-648e0e2feae1.jpg)
![Capturar_2023_04_06_22_59_48_471](https://user-images.githubusercontent.com/127704297/230704425-9f319594-ff6f-4d8a-be66-99c8b9e35f5f.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 353220651
Taker: RQGRZGNV
Deposit: 0.00128050 BTC
BTC mining fees lost: 0.00008010 BTC
Trade fees lost, please state if BSQ or BTC: ?(*) BSQ

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.9
BTC address for reimbursement: bc1qwqz6fkcwuf0xehdwhl87rwdl3d298hvrftg7gm

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

(*) I DON'T KNOW THE TRANSACTION FEE BECAUSE IT DOES NOT SHOW IN THE DEAL DETAILS

SECURITY DEPOSIT: 0.00128050 BTC
ONION ADDRESS OF TRADING PARTNERS: g6y6oerhyejbhit5c3nmhdz55k44b6whd6p6uio2ef44zdlkgg7kaayd.onion:9999
BIDDER FEE TRANSACTION ID: 5cacc6b06455815e930b516dc285e71fb69731d620c07a1494f785613099e2d6

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @amtexugo 

You were the taker for this trade.

No taker transaction was present.

You did not lose any funds in this trade.

Your wallet might be corrupted please do an SPV resync: https://bisq.wiki/Resyncing_SPV_file

**Comment by amtexugo** [comment]
Hi @darawhelan 
 
ok I will gona do it
but , can i delete the transaction?

when i gona delete transaction look the message: 
![Capturar_2023_04_10_01_09_06_603](https://user-images.githubusercontent.com/127704297/230824142-447f0fd6-73a5-4e47-8ccb-db4239b8bd27.jpg)

**Comment by darawhelan** [comment]
Yes, it is fine to press 'Sim'

**Comment by amtexugo** [comment]
ok! thanks
And i have 2 transactions open, can i syncronize before or after?

**Comment by darawhelan** [comment]
It is fine to do it before, during or after

**Comment by amtexugo** [comment]
Thanks bro! 
I have one more question: can i ask you?

**Comment by darawhelan** [comment]
Sure fire away!

**Comment by amtexugo** [comment]
Some questions about privacy when i buyer/taker: 

- Is permit i make a transaction without my CPF or my bank data?
- Is permit i pay one transaction by 2 or 3 payments by deposit bank?
- Is permit and i buy by f2f without notebook?  Cliking start payment button in pc and go outside, pay f2f and just a my mobile wallet check?

**Comment by amtexugo** [comment]
> Hi @amtexugo
> 
> You were the taker for this trade.
> 
> No taker transaction was present.
> 
> You did not lose any funds in this trade.
> 
> Your wallet might be corrupted please do an SPV resync: https://bisq.wiki/Resyncing_SPV_file

Hi men!
I do an APC resyng an im wating for more than 10 hours and dont open the bisq platform. My internet is low velocity, but i dont know if it's beacouse this...

thanks for atention

**Comment by darawhelan** [comment]
> * Is permit i make a transaction without my CPF or my bank data?

For Pix yes you can use a Pix Key that does not contain your CPF.

> * Is permit i pay one transaction by 2 or 3 payments by deposit bank?

Yes if you confirm with the seller that you will do this.

> * Is permit and i buy by f2f without notebook?  Cliking start payment button in pc and go outside, pay f2f and just a my mobile wallet check?

Yes, if you agree with your trade partner. You could also use a remote access tool to confirm on your mobile.

**Comment by darawhelan** [comment]
> I do an APC resyng an im wating for more than 10 hours and dont open the bisq platform. My internet is low velocity, but i dont know if it's beacouse this...

The SPV resync can take a while. Is the percentage amount you see increasing over time?

**Comment by amtexugo** [comment]
> The SPV resync can take a while. Is the percentage amount you see increasing over time?

freezes on this screen
![Capturar_2023_04_16_23_05_55_271](https://user-images.githubusercontent.com/127704297/232361372-9b6e31d3-0cac-4176-bece-405d709b04f7.jpg)

**Comment by amtexugo** [comment]
> 

- 

> > * Is permit i make a transaction without my CPF or my bank data?
> 
> For Pix yes you can use a Pix Key that does not contain your CPF.
> 
> > * Is permit i pay one transaction by 2 or 3 payments by deposit bank?
> 
> Yes if you confirm with the seller that you will do this.
> 
> > * Is permit and i buy by f2f without notebook?  Cliking start payment button in pc and go outside, pay f2f and just a my mobile wallet check?
> 
> Yes, if you agree with your trade partner. You could also use a remote access tool to confirm on your mobile.


thanks !

- but with pix the central bank will know about my sensitive data by the pix 
-

**Comment by amtexugo** [comment]
> > The SPV resync can take a while. Is the percentage amount you see increasing over time?
> 
> freezes on this screen ![Capturar_2023_04_16_23_05_55_271](https://user-images.githubusercontent.com/127704297/232361372-9b6e31d3-0cac-4176-bece-405d709b04f7.jpg)

im waiting for 24 hours yet

**Comment by amtexugo** [comment]
> > The SPV resync can take a while. Is the percentage amount you see increasing over time?
> 
> freezes on this screen ![Capturar_2023_04_16_23_05_55_271](https://user-images.githubusercontent.com/127704297/232361372-9b6e31d3-0cac-4176-bece-405d709b04f7.jpg)

im waiting more then 48hours

**Comment by amtexugo** [comment]
> > The SPV resync can take a while. Is the percentage amount you see increasing over time?
> 
> freezes on this screen ![Capturar_2023_04_16_23_05_55_271](https://user-images.githubusercontent.com/127704297/232361372-9b6e31d3-0cac-4176-bece-405d709b04f7.jpg)

IM WAITING MORE THEN 48 HOURS

**Comment by amtexugo** [comment]
I HAVE 2 ORDERS  OPEN

**Comment by amtexugo** [comment]
> > > The SPV resync can take a while. Is the percentage amount you see increasing over time?
> > 
> > 
> > freezes on this screen ![Capturar_2023_04_16_23_05_55_271](https://user-images.githubusercontent.com/127704297/232361372-9b6e31d3-0cac-4176-bece-405d709b04f7.jpg)
> 
> IM WAITING MORE THEN 48 HOURS

![Capturar_2023_04_18_16_23_57_991](https://user-images.githubusercontent.com/127704297/232883768-ee6deeab-ae92-4ea8-bb3f-6d887f62ae3c.jpg)

**Comment by amtexugo** [comment]
I think i know what happen. i looked the bisq log and i see a line: [my ip local node ]:8333: Peer died      (0 connected, 0 pending, 1 max)

i haved configure  a vpn tailscale for my node and before delete the SPV i had configure the  bisq to my vpn.

i dont know why the bisq dont conect my vpn, then ...bisq dont start
 
Do you have a way to configure bisq again by default with out have  start a bisq?

**Comment by amtexugo** [comment]
The problem  is the bisq dont connect to ip mynode, because the bisq is configured with mynode ip

**Comment by darawhelan** [comment]
> but with pix the central bank will know about my sensitive data by the pix

Yes, that is a problem with Pix!

**Comment by darawhelan** [comment]
> Do you have a way to configure bisq again by default with out have start a bisq?

If you delete the SPV file before loading Bisq it will log into the client:

https://bisq.wiki/Resyncing_SPV_file#From_the_file_system

Also see here for about connecting via your own node troubleshooting: https://bisq.wiki/Connecting_to_your_own_Bitcoin_node#Troubleshooting

if you have any issue best to get live in person support on Bisq Matrix chat: https://bisq.wiki/Matrix_bisq.chat

**Comment by amtexugo** [comment]
In troubleshooting i dont see for Windows

**Comment by darawhelan** [comment]
I would recommend reaching out here for live in-person support: https://bisq.wiki/Matrix_bisq.chat
