### ISSUE TITLE
Reimbursement for trade 77529565

### ISSUE THREAD

**Issue by rizarse** [bisq-network/support#1379]
**77529565-8204ca30-57d8-4978-8d22-c4322f1e8dda-199**

<img width="886" alt="Screenshot 2023-04-08 at 17 10 14" src="https://user-images.githubusercontent.com/7756803/230729705-a998a420-4b53-4ec2-aa46-c17a01b67690.png">
<img width="1099" alt="Screenshot 2023-04-08 at 17 11 39" src="https://user-images.githubusercontent.com/7756803/230730289-3ba58c10-6ca7-4136-a807-f4f5dcaa97d9.png">

Maker:  `5b14f089e308647cff1a2a00612225f98624fd88a6153e97130d3ef5de8c6ee8`
Taker: `891fd52b0f47e94d9fe0ba3799b897c94989bd3256dad4383bf4c9425f9be859`
Trade volume (lost): `0.0210 BTC`
Deposit: `0.00670320 BTC`
BTC mining fees lost: `0.00013980 BTC`

Bisq version: `1.9.9`
BTC address for reimbursement: `bc1qthkehgltqe65kyyyy346ahs0hagx3fqt8nyntc`

Other notes: This one of 3 trades failed within last week. Initial issue is related to sync of deposit transaction, that was shown as "non-seen" by any peer and confirmed by no one. After few hours of trade hanging in unconfirmed deposit transaction status .. me proceeded to backup and deletion of SPV-files. When `SPV deletion + re-sync` was over, after restart App suggested to move trade to `Failed` > Trade was moved to `Failed` > Currently trade shown as complete (in transactions) > No any fiat received from the trade.

**Comment by darawhelan** [comment]
Hi @rizarse 

This trade did not fail.

It is active, there are BTC for it in the multisig:

https://mempool.space/tx/6740efae878100c403f5ae80a72e8b32ced70d3364e5c97d7acfe03ffe6956fe

@pazza83 and @leo816 please can you keep a look out for this trade in your mediation.

@rizarse please can you reach out to the support channel on Matrix for additional support: https://bisq.wiki/Matrix_bisq.chat

**Comment by rizarse** [comment]
Thanks bisq-team for the support. The issue has been resolved.
