### ISSUE TITLE
Deposit reimbursement for trade 89060

### ISSUE THREAD

**Issue by rizarse** [bisq-network/support#1380]
Deposit reimbursement for trade `89060-edd0342b-90ec-447a-9bef-6c2e875fe10e-199`

<img width="888" alt="Screenshot 2023-04-09 at 12 30 09" src="https://user-images.githubusercontent.com/7756803/230767760-d3bbfef4-0bcb-4e59-a516-17e773e03a92.png">
<img width="1091" alt="Screenshot 2023-04-09 at 12 34 16" src="https://user-images.githubusercontent.com/7756803/230767809-bb4d4497-4330-4e4a-bf65-51213afd0169.png">

Maker:  `5a6a73c87ac01e2444cd2dbae8956f5bd1efffee4f05d6c176311293c6815e48`
Taker: `ad1d509d1216fa55195c6b7dd57500caad975d4447a725325b7076a28337d391`
**Deposit** lost: `0.0075 BTC`
BTC mining fees lost: `0.00013980 BTC`

Bisq version: `1.9.9`
BTC address for reimbursement: `bc1qq997gecdy43l0ca76xhmv2sv07a9yjcey2wx9c`

Other notes:
```
Trade did not initially move from first `Wait for blockchain confirmation`
status to the next one. Deposit transaction was not seen by peers and not
confirmed. After deletion of SPV-files and re-sync, App suggested to move trade
to the failed ones, that was made as suggested. 

After that the fiat payment was received. With delay of ~1 day or so the item of
-0.05759320 materialized in the list of transactions. However, no deposit pay
out 0.0075 is to be seen there so far, in the list of transactions. 
Delayed payout transaction
fe7d7693369946dfbc2ac7ce6e80cae4b3e2cff32706716c9725add703ec76a3 transaction
cannot be found in mempool either.
```

**Comment by darawhelan** [comment]
Hi @rizarse

This trade did not fail.

It is active, there are BTC for it in the multisig.

@pazza83 and @leo816 please can you keep a look out for this trade in your mediation.

@rizarse please can you reach out to the support channel on Matrix for additional support: https://bisq.wiki/Matrix_bisq.chat

**Comment by pazza83** [comment]
Thanks @darawhelan for making me aware.

@rizarse please can you reach out to me on Matrix my username there is: @pazza83:matrix.org

The buyer says they have sent you payment for this trade and BTC is locked in the multisig.
