### ISSUE TITLE
Fee reimbursement for trade 457870-01da1263-0cc9-4f8a-b4e2-ceb3414beb8f-199 

### ISSUE THREAD

**Issue by thephizzz** [bisq-network/support#1381]
The trade failed due to lost connectivity with the bitcoin servers. I wish to request that my fees are returned. Thank you.

**Comment by darawhelan** [comment]
Hi @thephizzz please can you post with the reimbursement template [here](https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX)
