### ISSUE TITLE
Fee reimbursement for trade 457870

### ISSUE THREAD

**Issue by thephizzz** [bisq-network/support#1382]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

![bisq](https://user-images.githubusercontent.com/56489745/231047848-708423e2-b353-40c3-8f30-79e813f7160e.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Maker Fee TX ID: 08151fca8f3266b255e6e946eea9bd3115f5a8979b2e12073c4fd4f8b51d38fe
Taker Fee TX ID: NA
Deposit TX ID: NA

Bisq version: 1.9.9
BTC address for reimbursement: bc1q8qygjfydgpjwz0kkpzuk4slvlqh6qdvg46mkul

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:
Error: An error occurred at task: CheckIfDaoStateIsInSync
Exception message: DAO state is not in sync with seed nodes

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @thephizzz 

You lost:

Miner fees 0.00005352 BTC
Trade fees 0.34 BSQ

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
Payout made with #1389
