### ISSUE TITLE
Fee reimbursement for trade 47134-e84bca26-7b32-45e3-9e03-45a8484d0b60-199

### ISSUE THREAD

**Issue by MiamiRetro** [bisq-network/support#1383]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

<img width="895" alt="Screenshot 2023-04-11 at 5 28 31 PM" src="https://user-images.githubusercontent.com/107248822/231134280-2dab0cbe-d3f0-464f-a405-e799497d0dcc.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  d8bf60eb5fd1b44d8b8610c9d7fdefb42f863addb6b2846186cf1e9b4a2fd4d8
Taker: 60238ffbf56fec395420df8711a736596e9737e65c5c162a7611ba950ef96211
Deposit: ‎0.002 BTC
BTC mining fees lost: .......... eg 0.00005825 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement: bc1qm5g8wl55dsw3yskqnxd5qkyxnpewx9d0v0sh0y

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @MiamiRetro 

You lost:

Miner fees: 0.00005825 BTC
Trade fees: 0.00020000 BTC

**Total: 0.00025825 BTC**

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Payout made with #1435
