### ISSUE TITLE
Fee reimbursement for trade WVHXIXvO-d8ad32e9-6f84-454e-b4b7-d4958c206c07-194

### ISSUE THREAD

**Issue by Plasmate01** [bisq-network/support#1385]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/124943421/231319529-eab6d291-1a29-4e52-a3e5-3919bd21e63c.png)
![image](https://user-images.githubusercontent.com/124943421/231319606-128da9c4-c34a-42dc-99bd-14974e0584b3.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 4918221cf01a1a30380194846eda48437b432699128960393e2c75be7ccbcb40
Taker: N/A
Deposit: N/A
BTC mining fees lost: 0.00007689 BTC
Trade fees lost, please state if BSQ or BTC: BTC (Security Deposit: 0.0010 BTC)

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.9
BTC address for reimbursement: 
bc1qq2wazjwrlcna7nzdenguxarjmsw9xdfytcza4p
>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:
Sorry I am really a newbie so I apologize if anything I provided was redundant. 

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @Plasmate01 

As the taker fee failed you have not lost any BTC in this trade.

Make sure your wallet is in sync by doing an [SPV resync](https://bisq.wiki/Resyncing_SPV_file). Wallets out of sync can cause trades to fail.
