### ISSUE TITLE
Fee reimbursement for trade shgpen-b04e06b9-9cc3-4001-900b-66dca1c433f6-199

### ISSUE THREAD

**Issue by okuspocus** [bisq-network/support#1386]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT  HERE
![imatge](https://user-images.githubusercontent.com/18405593/231513914-11975e29-13b2-4dcf-a24a-0f7baf45e53e.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... 0.0000690 BTC
Trade fees lost, please state if BSQ or BTC: .......... 0.00022330 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.9
BTC address for reimbursement: bc1qxe9hg059c4cvvmatz857mduz3xjvek4500uzd8

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @okuspocus Please can you update the screen shot to show if you were the buyer or seller and maker or taker.
