### ISSUE TITLE
Fee reimbursement for trade 575457-e98382be-57fe-4bf0-b9bf-1d9f7a68b584-199

### ISSUE THREAD

**Issue by brim001** [bisq-network/support#1388]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/61792660/231604773-0ac77595-2c30-491d-8338-47063e21bea7.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: db7d250dd287d842c0700fb318f9f2d704be9dca98f8cc5ce5f7c04f626ac6dd
Taker: 608ac55f488974aa849973fe1489144fed55736266b2c15539f3757fda1659ca
Deposit: 3ea56394fd8b1963375f97dd243c0f5aa60e5fa86805d2ab6c03a31203b3bc92
BTC mining fees lost: 0.00007170 BTC
Trade fees lost, please state if BSQ or BTC:  0.00002321 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.9
BTC address for reimbursement: bc1q3jc7z5yrj8gk7a4e0km9hnwws6j4khtxaagudh

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Payout made with #1389
