### ISSUE TITLE
Fee reimbursement for trade 542846

### ISSUE THREAD

**Issue by Christian891** [bisq-network/support#1390]
![image](https://user-images.githubusercontent.com/85958076/231795652-00a68d77-2192-4990-ac02-6266d0219049.png)

Maker:  cba4f8f442aa8dfb8a6c6df75637ed642691c4c86e77e4408412d1f38bc5ba98
Taker: ...........
Deposit: ..........
BTC mining fees lost: 0.00004165 BTC
Maker fee BTC ?

Bisq version: 1.9.9
BTC address for reimbursement: bc1quh8ynccxclr5s78cah45ymlqaawe47rxlmr0lk

Other notes:
An error occurred at task: CheckIfDaoStateIsInSync
Exception message: DAO state is not in sync with seed nodes

**Comment by darawhelan** [comment]
Hi @Christian891 

This trade failed on this attempt but should still be available for another user to take. 

Please make sure your DAO is in sync. By checking DAO and then go to Network Monitor.

**Comment by Christian891** [comment]
> Hi @Christian891
> 
> This trade failed on this attempt but should still be available for another user to take.
> 
> Please make sure your DAO is in sync. By checking DAO and then go to Network Monitor.

Status is: **Your node is in consensus with the seed nodes. Some of your peers are not in consensus.**
Is that OK?

**Comment by darawhelan** [comment]
Yes, that is good. As long as you are in consensus that is what matters. 

The taker in this trade probably was not hence the trade failing.

**Comment by Christian891** [comment]
> Yes, that is good. As long as you are in consensus that is what matters.
> 
> The taker in this trade probably was not hence the trade failing.

The escrow is locked yet. How get it unlocked . Do I have to wait as long as the taker takes action?

**Comment by darawhelan** [comment]
There was no escrow created.

If your Bisq client is showing it as locked you should do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file)

No BTC is locked on chain for this trade.
