### ISSUE TITLE
Reimbursement for lost trade fees

### ISSUE THREAD

**Issue by Moune87** [bisq-network/support#1392]
I have made a trade for an amount of 1105 EUR (0.0510 BTC) on Oct 27, 2022 7:07:56 AM JQDOFHVU-3e020c7a-1669-442d-9c29-5d23c7d84e0f-195 unfortunately the trade was never completed and I am not sure if my payment was lost or only the trading fees

started_at_UTC:
Oct 27, 2022 7:07:56 AM

Trade ID:
JQDOFHVU-3e020c7a-1669-442d-9c29-5d23c7d84e0f-195

Bisq version:
>_Provide the Bisq client version to help developers identify the causing issue._

Device or machine:
>MacOS

SCREENSHOTS HERE

>_Always when possible share screenshots of the error messages. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

solution:

Other notes:

**Comment by darawhelan** [comment]
Hi @Moune87 please can you re-post using the correct [template](https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX)

**Comment by Moune87** [comment]
Hi @darawhelan my issue does not necessarily encompasses only trade fees but maybe the whole transaction. Are you sure this is the correct template ?

**Comment by MwithM** [comment]
You opened the issue asking for lost trading fees. 
We can't know if you'll need the whole transaction (very unlikely if the trade [failed](https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1)) without at least the txid's for maker, taker and deposit, which is offered completing that template.

**Comment by Moune87** [comment]
Hi @darawhelan could you please get back to me on the above ?

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by darawhelan** [comment]
> Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

Sounds spammy
