### ISSUE TITLE
Bisq stalled on deposit verification while attempting to Buy BTC.

### ISSUE THREAD

**Issue by mrbill48** [bisq-network/support#1393]
Bisq locked up while attempting to take a trade to Buy BTC. Could not proceed and the trade is locked up and I cannot move forward. This is the window I receive when I opt for moving the trade to Failed status:

Attention
The trade protocol encountered a serious problem.

The trade contract is not set.

The trade cannot be completed and you might have lost your trade fee. If so, you can request a reimbursement for lost trade fees here: [1]

Do you want to move the trade to failed trades?

You cannot open mediation or arbitration from the failed trades view, but you can move a failed trade back to the open trades screen any time.
[https://github.com/bisq-network/support/issues]
16:38

Not sure what to do with this so I have not moved the trade to 'Failed' status yet. Can you offer any recommendation on how to clear the trade from my portfolio? I recently resync'd my DAO and updated my Tor settings. All seems to be in order. My DAO status shows that I am in sync with the network and my screen shows the green DAO indicator. I have contacted Matrix Element with this issue but have not received a reply yet. If I move this to 'Failed Trade" status, will that action clear this issue up so that I may take another Trade?

**Comment by MwithM** [comment]
If you know for sure that the deposit tx did not broadcast, do a backup, move to failed and do a spv resync. https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1
