### ISSUE TITLE
Fee reimbursement for trade JQDOFHVU

### ISSUE THREAD

**Issue by Moune87** [bisq-network/support#1394]
<img width="889" alt="Screen Shot 2023-04-18 at 10 20 41 PM" src="https://user-images.githubusercontent.com/130850587/232895947-6141f4d6-3a55-451b-ab55-b81550c96ad0.png">

Maker:  13a0e93a637bd694b84e6547b99af2d9fb8661246be836e6b5f2aa08bd97049e
Taker: Not available (See as per screenshot attached)
Deposit: Buyer: 0.03 BTC
BTC mining fees lost: Maker: 0.00005140 BTC / Taker: 0.00006990 BTC
Trade fees lost, please state if BSQ or BTC: Buyer: BTC

Bisq version: 1.9.9
BTC address for reimbursement: Not sure where to find this information

Other notes: "Timeout reached. Protocol did not complete in 120 sec." error. Please reimburse fees.
Thanks.

**Comment by darawhelan** [comment]
Hi @Moune87 please can you update the screenshot to show if you were the maker or taker, buyer or seller.

**Comment by Moune87** [comment]
Hi @darawhelan I was the Buyer

**Comment by darawhelan** [comment]
Where you the maker or taker?

**Comment by Moune87** [comment]
I am not sure I understand the difference to be honest. I was the person buying the BTC so I assume it correspond to the taker ?

**Comment by darawhelan** [comment]
Did you make the offer or take someone else's offer?

**Comment by Moune87** [comment]
I was taking someone's else offer

*Manon Labbé*
***@***.***


Le lun. 24 avr. 2023 à 01:04, Dara Whelan ***@***.***> a
écrit :

**Comment by darawhelan** [comment]
Ok, as you were the taker and there is no taker transaction ID you have not lost any funds on this offer.

If your Bisq is showing an incorrect balance you should do an SPV resync: https://bisq.wiki/Resyncing_SPV_file
