### ISSUE TITLE
Case XXXXX

### ISSUE THREAD

**Issue by pprvggc6um** [bisq-network/support#1395]
>_The XXXXX part are a random string generated with the command `date | shasum | cut -b-6`._

Description:

>_Provide a brief description of the bug_
Pressing the "Confirm Payment Receipt" button, then "to complete a trade, an error window pops up with the following:

Error
An error occurred at task: SellerSendPayoutTxPublishedMessage
started_at_UTC:
<_yyyy-mm-dd hh:mm_
approximately 2023-04-25 15:00 UTC

github-issue:
>_Please provide a reference issue number to which this case is related. If there isn't one go ahead and create that issue first._

Bisq version:
>_Provide the Bisq client version to help developers identify the causing issue._
v1.9.10

Device or machine:
>_Provide the Operating System and Version_
Windows 7 Pro
Version 6.1.7601 Service Pack 1 Build 7601

SCREENSHOTS HERE

![error-message](https://user-images.githubusercontent.com/121187130/234300588-1196758b-ebc7-48b8-817e-751bb1af4a2a.PNG)

solution:

Other notes:

**Comment by darawhelan** [comment]
Where you the maker or taker? buyer or seller?

What were the following transactions:

- taker
- maker
- deposit

**Comment by pprvggc6um** [comment]
I was the offer maker, selling btc 
maker fee txid 6e27ff36fd723cf387093838b518e2dd86c98e5f4f10a6f9353aeafc92d609ed
taker fee txid 422c0d1ab5e68374856e6f389515314bbe909584c2a2cae96a879b111afc28e3
deposit txid 2d5710eb40b823facfc31259702748bae6f1b80b68cecf48411bc85e56086a0d

**Comment by darawhelan** [comment]
Ok this trade looks like it completed successfully:

bfda81413d8dab1ec5d6e9e95f04b246e427f581de5ecf8e5daa58e4959655b1

You should see the payout in your funds section in Bisq under transactions.

Is the trade in your history now?

**Comment by pprvggc6um** [comment]
I do see that transaction under Funds > Transactions, and under Confirmations it shows it was confirmed in 144 blocks.  Does that mean the offer taker has received the BTC?  I tried to message them to confirm, but haven't gotten a response.

Under Portfolio, it's still listed under Open Trades, but has the warning icons with links to view trade details and move the trade to failed trades.

**Comment by darawhelan** [comment]
> I do see that transaction under Funds > Transactions, and under Confirmations it shows it was confirmed in 144 blocks. Does that mean the offer taker has received the BTC? I tried to message them to confirm, but haven't gotten a response.

Yes the buyer has received the BTC.

> Under Portfolio, it's still listed under Open Trades, but has the warning icons with links to view trade details and move the trade to failed trades.

I would move it to failed trades.

It might be the trade failed and then someone took it again and were successful on the second attempt

**Comment by pprvggc6um** [comment]
Excellent, thanks.

Do I need to take any further action to close this support issue?

**Comment by darawhelan** [comment]
No problems. You can press close on this ticket, I think it should be at the bottom of the screen.
