### ISSUE TITLE
Refunds of commissions charged ID1861150

### ISSUE THREAD

**Issue by neocpc** [bisq-network/support#1396]
I request a refund of the commissions charged for a failed transaction
![captura pantalla bisq](https://user-images.githubusercontent.com/119758693/234780176-1467662d-6071-4325-a6b8-0c640112d1a9.png)
![captura pantalla bisq1](https://user-images.githubusercontent.com/119758693/234780313-b9464be8-7cc8-41f1-8e00-85536bc01fd4.png)
![captura pantalla bisq2](https://user-images.githubusercontent.com/119758693/234780410-636a281a-2273-406f-b984-bab7a708a721.png)

**Comment by darawhelan** [comment]
Hi @neocpc 

Thanks for posting. Looks like you have lost trade and miner fees on this failed trade.

Please can you copy and paste the taker transaction ID.

Also post a bitcoin address for reimbursement.

**Comment by neocpc** [comment]
ID taker transaction: 024b8e445700dd5268fae49dd3acb24fda80c0810e91054b46e935b1a127feb6
Bitcoin adress: bc1q0805c7sqzgrjvtgvj8jkeyjh5p4q2dxkuqu64s

**Comment by darawhelan** [comment]
Thanks

On this trade you lost:

‎0.00005000 BTC in trade fees
0.00002563 BTC in miner fees

**total 0.00007563 BTC** 

@leo816 please can you add to you list for refunds bitcoin address is posted in comment above. Thanks

**Comment by neocpc** [comment]
bc1q0805c7sqzgrjvtgvj8jkeyjh5p4q2dxkuqu64s

**Comment by leo816** [comment]
Payout made with #1435
