### ISSUE TITLE
Refunds of commissions charged ID 0988408

### ISSUE THREAD

**Issue by ezrabor** [bisq-network/support#1397]
I request a refund of the commissions charged for a failed transaction
![image](https://user-images.githubusercontent.com/132005946/234954989-45bc04e7-c016-44af-b0b6-24a213398f67.png)
![image](https://user-images.githubusercontent.com/132005946/234955760-8b61eba3-5740-4668-927a-5aa6d8cd954b.png)
![image](https://user-images.githubusercontent.com/132005946/234955928-ca9dd953-7602-4da7-b3a6-ccfdcdf95bc5.png)
Security Deposit 0,002262 BTC and  0.00006750 BTC  mining fee

**Comment by darawhelan** [comment]
Hi @ezrabor

As you are the taker you have not lost any funds or fees as no transaction took place.

I would recommend you doing an SPV resync as your wallet might be out of sync: https://bisq.wiki/Resyncing_SPV_file

**Comment by ezrabor** [comment]
Ok
Tank's
