### ISSUE TITLE
Fee reimbursement for trade OHEAK

### ISSUE THREAD

**Issue by roycocup** [bisq-network/support#1404]
OHEAK\

![Screenshot from 2023-05-01 14-05-43](https://user-images.githubusercontent.com/132394/235455468-c00d128d-d163-4cc3-98b0-cdf0be731f98.png)

Maker:  f89cc13889a5c2cb088c9162936b0474566f7c4feb2f828d00e47425c7ffe819
Taker: 99d6a0afd7507595f14b8f12c1c106d690157177bdadfb2c741af9fdd053e17f
Deposit: 6b56f9406f0f87d853b8af221643cd9144be418e53a8460029b3323c30f83f4a
BTC mining fees lost: Maker: 0.00005562 BTC / Taker: 0.00011184 BTC
Trade fees lost, please state if BSQ or BTC: 0.00235976 BTC

BTC address for reimbursement: bc1qws4458vzx3n0mxucn4kq53agqqlyudnsxezgqk

Other notes:

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.
Please reimburse fees.
Thanks.

**Comment by Rednator** [comment]
Hi @roycocup  visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Bisq Support](wikibisq.online)

**Comment by pazza83** [comment]
> Hi @roycocup visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Bisq Support]

SPAM

Please can @Rednator be banned for posting phishing links.

**Comment by darawhelan** [comment]
Hi @roycocup 

Please can you edit the screen shot above with the bit of information that shows if you were the maker / taker and buyer / seller.

**Comment by roycocup** [comment]
Picture updated. Apologies for the delay. Thanks for all the help.

**Comment by darawhelan** [comment]
@roycocup 

Many thanks.

You lost fees in this trade.

Miner fees: 0.00003728 BTC
Trade fees: 0.00008970 BTC

**Total: 0.00012698 BTC**

It might be that either you are the seller's DAO was not synced. I would recommend going to the DAO section in your Bisq app and clicking Network Monitor to make sure your DAO is in sync. If it is not you will see the option to resync and restart Bisq.

@leo816 please can you make a refund for this trade in your next batch.

**Comment by roycocup** [comment]
Much appreciated. 
I have since then retried resetting the whole thing and re-sync everything again and I'm still a little afraid to make any transactions but thank you nevertheless. 
Thanks anyway.

**Comment by roycocup** [comment]
Sorry to reopen this issue, but I think there hasn't been a refund for this yet? Am I correct? 
I was expecting the refund to come back to `bc1qws4458vzx3n0mxucn4kq53agqqlyudnsxezgqk` , is that correct?

**Comment by darawhelan** [comment]
Hi @roycocup 

Refunds are made in batches usually once a month, but sometimes up to two months.

When the refund is issues a comment will be posted here informing you.

**Comment by roycocup** [comment]
Understood! Thank you!

**Comment by leo816** [comment]
Payout made with #1435
