### ISSUE TITLE
Fee reimbursement for trade szvea

### ISSUE THREAD

**Issue by Theoldgits** [bisq-network/support#1409]
![image](https://user-images.githubusercontent.com/132845033/236696945-119eaa63-58b5-484f-bad3-4b6d96fcda87.png)

Trade ID: szvea
Trade date: 7 May 2023 15:44:32
Security deposit: Buyer: 0.001320 BTC / Seller: 0.001320 BTC
Mining fee: Maker: 0.00018025 BTC / Taker: 0.00140499 BTC

Trading peers onion address: i5nmtwmryb6pwhacsbp4aqhecay6kwxvcblg4mw4hyt57tnlywm2zxqd.onion:9999

Maker fee transaction ID: f1de4041fcd081ae7aaf07dfa50849efe0be08781362af7897c3d1e48fa3f7da      
Taker fee transaction ID: 67e51299ab729ad7c6fc6ee94bb83acc4f617f49bafe1c0b2dedfe209d9771f0      

Error: 

The trade protocol encountered problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Trade state: Deposit transaction has been published 

Bisq version: 1.9.10
BTC address for reimbursement: 1BRof3XeuibhRQwdc3kgRzY9YwH5arWu4V

**Comment by darawhelan** [comment]
Hi @Theoldgits 

Please can you post the bit of the screen shot that shows if you were the buyer or seller, maker or taker

**Comment by Theoldgits** [comment]
![image](https://user-images.githubusercontent.com/132845033/236781063-761c3c5e-70ab-41fc-97d2-8a4748a3ad56.png)

**Comment by darawhelan** [comment]
Thanks @Theoldgits 

You lost on this trade:

Miner fee: 0.00046833 BTC
Trade fee:  ‎0.00010120 BTC

**Total: 0.00056953 BTC**

@leo816 please can you add this to your next reimbursement batch. Many thanks

**Comment by Theoldgits** [comment]
@ darawhelan,

The reimbursement fee does not match the amount of losses. 
How do I get the security deposit refunded back to my wallet?

Thanks

**Comment by darawhelan** [comment]
The trade never happened, so no security deposit was sent to a multisig.

Looks like you used the funds in utxo bc1qg8zv30mnkwasqv39k2hap4vjxe30zp674mx6js to do a trade the next day.

Sometimes a failed trade causes a users wallet to appear out of sync.

I would recommend doing an SPV resync

https://bisq.wiki/Resyncing_SPV_file

**Comment by leo816** [comment]
Payout made with #1435
