### ISSUE TITLE
Fee reimbursement for trade f73fnbm

### ISSUE THREAD

**Issue by Theoldgits** [bisq-network/support#1410]
Hi @darawhelan, 

Same thing has happened with another trade. This software seems to have many bugs.

![image](https://user-images.githubusercontent.com/132845033/236888446-77b6610a-7151-4427-b744-c5a872cbfc41.png)

Trade ID: f73fnbm
Trade date: 8 May 2023 16:16:48
Security deposit: Buyer: 0.0015 BTC / Seller: 0.0015 BTC
Mining fee: Maker: 0.00074550 BTC / Taker: 0.00269724 BTC
Trading peers onion address:  fm3xu6mvuz7yvjklqasjcy74j67sr2tvw4fhvffheqo62px2fa33awyd.onion:9999

Maker fee transaction ID: 08e6a982e9a62ad22a12e28986f965e9493bda425a1ab9d08a8d3b641637b6cd
Taker fee transaction ID: 78f578e0069335767a5a90131e7e27cec225e2dc08b77ce592c9d8e59e3f47f

Error:

The trade protocol encountered problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Trade state: Deposit transaction has been published

Bisq version: 1.9.10
BTC address for reimbursement: bc1qg8zv30mnkwasqv39k2hap4vjxe30zp674mx6js

**Comment by darawhelan** [comment]
@Theoldgits 

Please can you copy and paste the deposit transaction ID also.

Thank you

**Comment by Theoldgits** [comment]
@ darawhelan

Transaction ID : 
d322a681f03b4f07000697f673b281ae8bb8dd53237f184bb20f2fc1ee454523

Where can I find info or how to get the security deposits reimbursed for failed trades, the deposits have not returned to my account.

**Comment by darawhelan** [comment]
The deposit will not have left your wallet.

If you cannot see it I would recommend doing an SPV resync

https://bisq.wiki/Resyncing_SPV_file

**Comment by Iyd4raf** [comment]
Hi, I was the btc seller. Can my trade fee be reimbursed too?

Transaction ID: 78f578e0069335767a5a90131e7e27cec225e2dc08b77ce592c9d8e59e3f47f7

![bisq-trade](https://github.com/bisq-network/support/assets/43270055/1a6e57f9-68a2-4d57-8f4c-a90c261b631a)


Trade ID: f73fnbm
Trade date: 8 May 2023 16:16:48
Security deposit: Buyer: 0.0015 BTC / Seller: 0.0015 BTC
Mining fee: Maker: 0.00074550 BTC / Taker: 0.00269724 BTC
Trading peers onion address: ueqgdgjxxtggkrdit2eldwlqpnayb3yw5mhgs3rcvvqluji5shjpf2id.onion:9999

Maker fee transaction ID: 08e6a982e9a62ad22a12e28986f965e9493bda425a1ab9d08a8d3b641637b6cd
Taker fee transaction ID: 78f578e0069335767a5a90131e7e27cec225e2dc08b77ce592c9d8e59e3f47f7

Bisq version: 1.9.10
BTC address for reimbursement: bc1qx673p8cy8s63n0lrlmvdmush4u44pwrzv5a5s9

**Comment by Theoldgits** [comment]
@ darawhelan The above details are another transaction, where I lost the fees. Please could these also be reimbursed. Thanks.

**Comment by darawhelan** [comment]
> Hi, I was the btc seller. Can my trade fee be reimbursed too?

@Iyd4raf Yes, please can you open a new issue to avoid any confusion. Much appreciated

**Comment by darawhelan** [comment]
> @ darawhelan The above details are another transaction, where I lost the fees. Please could these also be reimbursed. Thanks.

@Theoldgits 

Sorry I do not know what you mean by the above details. Please can you specify.

On this trade you have lost:

Miner fees: 0.00074550 BTC
Trade fees: 0.00005000 BTC

**Total: 0.0007955 BTC**

@leo816 can make the reimbursement for this in the next batch to the address you provided for reimbrsement:

> BTC address for reimbursement: bc1qg8zv30mnkwasqv39k2hap4vjxe30zp674mx6js

**Comment by Theoldgits** [comment]
@darawhelan 

I didn't see the message for reimbursement sent to @leo816 in the previous message from a few days ago (meaning the above details). But I can see this has now been sent in your above message. Thanks.

**Comment by leo816** [comment]
payout made with #1476
