### ISSUE TITLE
Fee reimbursement for trade f73fnbm

### ISSUE THREAD

**Issue by Iyd4raf** [bisq-network/support#1414]
Hi, this trade failed, can my trade fees be reimbursed?

Transaction ID: 78f578e0069335767a5a90131e7e27cec225e2dc08b77ce592c9d8e59e3f47f7

![bisq-trade](https://github.com/bisq-network/support/assets/43270055/f2b34700-3fae-454f-93d3-e4d2ab4eb5ac)

Trade ID: f73fnbm
Trade date: 8 May 2023 16:16:48
Security deposit: Buyer: 0.0015 BTC / Seller: 0.0015 BTC
Mining fee: Maker: 0.00074550 BTC / Taker: 0.00269724 BTC
Trading peers onion address: ueqgdgjxxtggkrdit2eldwlqpnayb3yw5mhgs3rcvvqluji5shjpf2id.onion:9999

Maker fee transaction ID: 08e6a982e9a62ad22a12e28986f965e9493bda425a1ab9d08a8d3b641637b6cd
Taker fee transaction ID: 78f578e0069335767a5a90131e7e27cec225e2dc08b77ce592c9d8e59e3f47f7

Bisq version: 1.9.10
BTC address for reimbursement: bc1qx673p8cy8s63n0lrlmvdmush4u44pwrzv5a5s9

**Comment by darawhelan** [comment]
Hi @Iyd4raf 

On this trade you lost:

Mining fee: 0.00089908 BTC
Trade fees: 0.00011500 BTC

**Total: 0.00101408 BTC**

@leo816 please can you reimburse in your next batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1435

**Comment by darawhelan** [comment]
@Iyd4raf please can you delete the screenshot above it has yours and buyer's personal details on.
