### ISSUE TITLE
Fee reimbursement for trade 585082

### ISSUE THREAD

**Issue by maxip2129** [bisq-network/support#1417]
![Screenshot-1](https://github.com/bisq-network/support/assets/133550835/a981c2cf-ab1c-4dde-949c-3d5cfcbca52d)

Bisq version: 1.9.10
BTC address for reimbursement: bc1qd0whrda0tcuwkwc4vnrcskym9cltw6pstgfxmy
BTC Mining fees lost: .00056525 BTC
Trade fee lost: .00218736 BTC

**Comment by darawhelan** [comment]
Maker: 06cdbbe90dae7bf2f28c72eed1954991bd925920d4344f72095132c675c67b4c
Deposit: 2e3ee644faeb782089b361901423ba1250cb3c05b91c2d96f93e062a23b304c5

Hi @maxip2129 

On this trade you lost:

Trade fees: 0.00005000 BTC
Mining fees: 0.00056525 BTC

**Total:  0.00061525 BTC**

@leo816 please can you reimburse in your next batch.

**Comment by leo816** [comment]
Payout made with #1435
