### ISSUE TITLE
Fee reimbursement for trade BXPIVFT

### ISSUE THREAD

**Issue by zdick** [bisq-network/support#1419]
![Snímek obrazovky pořízený 2023-05-22 21-30-18](https://github.com/bisq-network/support/assets/22180386/c5b10878-4bef-40dc-b443-271daafbd489)

Maker: 5150ff7f92f2e10c69e25607b3c07908ed0bcafd9d8b8d3a2bbff4aa9e810efb
Taker: 346b3254f84f1d03844be41f233f6ca54c730e1c0752671007b92ec029b1f6b4
Deposit: N/A
BTC mining fees lost: 0.00052033 BTC
Trade fees lost, please state if BSQ or BTC: 0.26 BSQ

Bisq version: 1.9.10
BTC address for reimbursement: bc1qev0c67nq93k0hlus64wemurzvlgcyhjgywayty

"Timeout reached. Protocol did not complete in 120 sec."

**Comment by darawhelan** [comment]
Hi @zdick 

Thanks for posting. I can confirm you lost miner and trade fees on this failed trade:

Mining fees: 0.00052033 BTC
Trade fees: 0.26 BSQ

@leo816 please can you add the reimbursement to your next batch. thank you.

**Comment by leo816** [comment]
Payout made with #1435
