### ISSUE TITLE
Fee reimbursement for trade 53541833

### ISSUE THREAD

**Issue by chiefnand0** [bisq-network/support#1421]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Screenshot 2023-06-04 141346](https://github.com/bisq-network/support/assets/135545351/e14276c1-b8e1-477f-9bd9-58618b9ec373)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:bc1q48lxd0taxunfyf0d2tn6gf23tk5afpr6d95l9n

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @chiefnand0 

Please can you copy and paste the maker transaction ID into your reimbursement request.

Thank you

**Comment by adrie0** [comment]
> > _The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
> 
> SCREENSHOT HERE ![Screenshot 2023-06-04 141346](https://user-images.githubusercontent.com/135545351/243202157-e14276c1-b8e1-477f-9bd9-58618b9ec373.png)
> 
> > _The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_
> 
> Maker: .......... Taker: ........... Deposit: .......... BTC mining fees lost: .......... eg 0.00005 BTC Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or 0.000088 BTC
> 
> > _A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_
> 
> Bisq version: BTC address for reimbursement:bc1q48lxd0taxunfyf0d2tn6gf23tk5afpr6d95l9n
> 
> > _Provide the Bisq client version to help developers identify the causing issue._
> 
> Other notes:
> 
> > _Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

Hi @chiefnand0 visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Bisq Support](https://bisqwiki.online/)
