### ISSUE TITLE
Fee reimbursement for trade CyvwNR-a7518e8b-2747-4a5d-8b29-9fd221d40304-199

### ISSUE THREAD

**Issue by labaleine** [bisq-network/support#1423]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

<img width="1061" alt="Capture d’écran 2023-06-10 à 01 05 53" src="https://github.com/bisq-network/support/assets/136115907/afa9e75f-bb77-4fcf-849e-ec2c7883d9fd">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.9
BTC address for reimbursement: 3CG7LbrDJsFfkyzqd6tqjGEaFkRrKu11Qr

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @labaleine 

As there was no deposit transaction created you should not have lost any funds on this trade.

Your trade should still be available to take.
