### ISSUE TITLE
Reimbursement for trade SGPE9

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#1427]
Reimbursement for trade SGPE9

I am BTC buyer as maker
Trade amount and asset: 1 BTC for 180.5 XMR
Deposit amount: 0.15 BTC

Maker txid: 06ced46679a02c01511472d8a8e9c377b61af4d1a2a75728145213161d1af7a1
Taker txid: abb5783816fd889c801d76aa7c6d8e9eb96b40c196ff829fc57ff6ae737eb539
Deposit tx: fa1829dbbc99dabb9d8c1411ddace1f482bef93671ee8fe9d5906ea5e2207ea9
Delayed payout tx: 43800aea7cf9a145d72b1f65fd9dc1791aaf1aca788de1a8fe72eced18c74f75

**Reimbursement amount:** 0.35 BTC / 0.00002688 BSQ x 1.0386 = **`13522 BSQ`**
Reason for reimbursement: Trader not responding

#### Mediation suggestion

System message: Mediator's dispute summary:
Mediator's node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Ticket closed on 7 May 2023 16:38:49
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: SGPE9
Currency: XMR
Reason for dispute: Bug
Payout suggestion: BTC buyer gets trade amount payout
Trade amount: 1.00 BTC
Payout amount for BTC buyer: 1.15 BTC (BTC buyer receives trade amount + his deposit)
Payout amount for BTC seller: 0.15 BTC (BTC seller receives his deposit)

Summary notes:
Bug - Mediation ticket did not open on buyer's bisq instance

BTC buyer sent XMR

txid : 0a2f73ed69b6ee05d5ba4a44a2437d791f6ee2deaa33319b8a011ae8563ce80b
key : 0be1425a8278f39164c077596713762469f959503013da12bc57eb93265ae60a

BTC seller confirmed XMR

Proposing trade to  complete as successful

-----BEGIN SIGNATURE-----
302c021461448e1537fe97539887bde7162b6ab1e9d7e9f402147db2b5660ba84d374d15cd18beda0eed04db41a7
-----END SIGNATURE-----

#### Arbitration summary

Seller did not release BTC or reply. 
Payout: buyer gets 1.15 ; seller receives 0 BTC. 
As the total reimbursement amount is too big for the refund agent, only 0.8 BTC are paid. Buyer has to claim an equivalent to 0.35 BTC in BSQ through a DAO reimbursement. Instructions have been provided and further questions should be sent to bisq.chat

Arbitration secret: udkacuy9

**Comment by ghost** [comment]
@refund-agent2 
@pazza83

**Comment by refund-agent2** [comment]
Arbitration secret is correct.
0.8 BTC [payout](https://mempool.space/tx/177f8bfe9e386e5d00176f1ea034ba5cc552f5b481a219861075e8ab957fc0c6) was confirmed.
BSQ reimbursement amount is correct too, submit a reimbursement request to the DAO and copy here fhe txid of the proposal.

**Comment by pazza83** [comment]
Hi @klt12345 

I confirm the seller stopped responding when the mediation proposal was issued.

Sorry for your inconvenience.

It would be worth getting your comments on this issue about trade limits / BSQ reimbursements if you would like to add anything:

https://github.com/bisq-network/proposals/issues/413

**Comment by refund-agent2** [comment]
Don't forget to add the txid of the reimbursement request after submitting it to the DAO.

**Comment by ghost** [comment]
@refund-agent2 Here is the reimbursement request. https://github.com/bisq-network/support/issues/1431
Did I do it correctly?

**Comment by pazza83** [comment]
Hi @klt12345 

You did everything correctly but you did not submit the reimbursement to the DAO.

Here is the guide to how to do it:

https://bisq.wiki/Making_a_reimbursement_request#Submit_your_reimbursement_request_to_the_Bisq_DAO

There might be a new rate now to submit as you missed the June cycle.

You have until 23rd July to submit a DAO reimbursement request for payment at the end of the month.

@refund-agent2 please can you advise how much BSQ should @klt12345 request. Thanks.

**Comment by ghost** [comment]
I understand now, Thanks Pazza.

**Comment by refund-agent2** [comment]
Hi, I have been talking to the @klt12345  via matrix.
Now is a good time to recalculate your request and submit it to the DAO, just let me know if you need help updating the numbers.

**Comment by ghost** [comment]
@refund-agent2 Yes can you help with the numbers please.

**Comment by refund-agent2** [comment]
**13522 BSQ** = 0.35 / 0.00002688 * 1.0386

**Comment by ghost** [comment]
@refund-agent2 @pazza83 
Thanks for the new numbers. I have edited the first post in this thread and submitted a proposal on the bisq app linking to here.
Hopefully I've done it right this time!

**Comment by pazza83** [comment]
Yes, I just checked. Your all reimbursement request is all good. 

The vote result is on ~ 31st July.

**Comment by ghost** [comment]
@pazza83 Great. Thanks for checking @pazza83

**Comment by pazza83** [comment]
This reimbursement request was accepted by the DAO. Will close this issue. Many thanks
