### ISSUE TITLE
Reimbursement fee for 981714

### ISSUE THREAD

**Issue by masterpp99** [bisq-network/support#1429]
![bisq](https://github.com/bisq-network/support/assets/136679248/e7debef9-a906-433b-87ab-ce658d6b4602)

Reimbursement for trade 981714
I am BTC [seller] as [maker] for [0].
Trade amount and asset: [0] BTC for [0 ASSET]
Deposit amount: [0] BTC

Maker:  ..........
Taker: ...........
Deposit: 0.0285
Delayed payout: ..........
BuyerMultiSigPubKeyHex: ..........
SellerMultiSigPubKeyHex: ..........
Trade ID: 981714-7dcb6ff0-b2d2-42f5-a08b-8c905c67bfd9-199
Maker fee Transaction ID: 3c4d02edc28a15a5a03bac9ac68386c9cf227ce40d697d315f7e9bd918ce3e50

Reimbursement amount: [0.0285] BTC
Reason for reimbursement: [REASON]
Error:
An error occurred at task: CheckIfDaoStateIsInSync
Exception message: DAO state is not in sync with seed nodes

BTC address ownership proof: bc1qfgmafan98jn337j7q7rkd9x6a5euvgk5sqxdtm

Bisq version: 1.9.9

>_Ping @refund-agent2 and your mediator_

**Comment by darawhelan** [comment]
Hi @masterpp99 

This trade ended up completing normally:

https://mempool.space/tx/ec294c4b1bb42faa3dda9e56efb91c7158a15e046af4109627faa87de33454dd

It might have failed the first time someone took it but it was still available to be taken and someone did on 8 June.
