### ISSUE TITLE
Reimbursement for xxx

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#1431]

**Comment by ghost** [comment]
@refund-agent2
@pazza83 
Is this right?

**Comment by ghost** [comment]
How much longer does this process take?
No communication from @refund-agent2
Are you there @pazza83 ??

**Comment by pazza83** [comment]
Hi @klt12345 

I recommend keeping all the info on the [previous ticket.](https://github.com/bisq-network/support/issues/1427)

I will reply there and close this one.
