### ISSUE TITLE
Fee reimbursement for trade qx6mirm8

### ISSUE THREAD

**Issue by M9-SD** [bisq-network/support#1436]
![image](https://github.com/bisq-network/support/assets/57565554/f02be76e-0135-490f-8b31-1787b36590ce)

Maker: d1fca91a2aa90bcd542e00fa21c3ffc8accda1b3d78aa846aa4f4ea10490b128
Taker: N/A
Deposit: N/A
BTC mining fees lost: N/A
Trade fees lost: 0.00007245 BTC (~2.22 USD)

Bisq version: v1.9.10
BTC address for reimbursement: bc1q3juuxe4y94q5c6uc85l379jkpt4alaceexrjsa

Other notes:

> Attention
> The trade protocol encountered some problems.
> 
> The trade contract is not set.
> 
> The trade cannot be completed and you might have lost your trade fee. If so, you can request a reimbursement for lost trade fees here: [1]
> [https://github.com/bisq-network/support/issues]

**Comment by M9-SD** [comment]
* mining fee: 0.00003920 BTC

**Comment by M9-SD** [comment]
* trade fee: 0.00007245 BTC

**Comment by Hutchins7** [comment]
Hi @M9-SD  visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Bisq Support](https://bisqwiki.online/)

**Comment by darawhelan** [comment]
Hi @M9-SD  as you were the taker and the taker transaction was not found you have not lost any fees or funds on this trade.

It might be your wallet is out of sync.

I would recommend you do an spv resync:

https://bisq.wiki/Resyncing_SPV_file
