### ISSUE TITLE
Fee reimbursement for trade nlnk8

### ISSUE THREAD

**Issue by Packer0631** [bisq-network/support#1437]
nlnk8-33ae2844-a0e9-49e8-8d11-f7f414ab09d9-199

![image](https://github.com/bisq-network/support/assets/127801727/c3c37f24-cf8f-4ec0-870d-df7bfc6344ac)

Maker:  1e553849020e447e9937cbec7b4733cd5e4fa1fe87a955f37824da85ef94c460
Taker: 8cc1098366078c76059a7c07e6f1f7ddeaaff9d7b5f090dc37f84ee82c3a5fae
Deposit: 647eef02917903c7aaed403f1c4054c3a4b762580a40fc8503a801ffed4435d0
BTC mining fees lost: Maker: 0.00009240 BTC / Taker: 0.00012150 BTC
Trade fees lost n/a

Bisq version: v1.9.9
BTC address for reimbursement: bc1q0aquvfsrl7ghql9n2y2hmrhqs90u5yqqcsrtdm

Other notes: Mempool showed "transaction not found"

**Comment by Packer0631** [comment]
Bump

**Comment by darawhelan** [comment]
Hi @Packer0631 as you were the maker and the maker transaction was not found you have not lost any fees or funds on this trade.

It might be your wallet is out of sync.

I would recommend you do an spv resync:

https://bisq.wiki/Resyncing_SPV_file

**Comment by Packer0631** [comment]
Thank you. I was acting on the automated advice by the client application itself. Yes, I have had to resync several times in the last few weeks. I am having to do this more and more often. I am wondering if it could mean some of the following:

Either my keys have been compromised (there was one incident where this may have happened)
Or my installation is getting bloated with history and needs pruning.

In either case it would be really useful to be able to archive and/or completely remove the current installation and reinstall with a fresh wallet and keys. Failing that remove it from my PC altogether and use another machine, in which case, again, I need to remove all trace of the old installation.

Can you please advise how to do this? I do not wish to leave my PC with hidden data from an old installation about which I forget later on.

Thanks

**Comment by darawhelan** [comment]
Hi @Packer0631 

Having to resync multiple signs is a sign of a corrupted date directory.

It can happen for a number or reasons, but the older your instance, or the more trades you have done, the more likely it is to occur.

It is always good practice to move to a new data directory every 18 months or so.

Here is the wiki guide on how to do so:

https://bisq.wiki/Switching_to_a_new_data_directory

Just make sure you transfer any bitcoin and BSQ from your old instance to your new one.

Also it is often good to export your payment accounts from your old account and import them to your new Bisq instance. This will keep your signed account status.
