### ISSUE TITLE
Fee reimbursement for trade GFSAL

### ISSUE THREAD

**Issue by adidasats** [bisq-network/support#1438]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screen Shot 2023-06-29 at 8 05 40 PM](https://github.com/bisq-network/support/assets/138173943/75b937b1-1f2c-4b0c-a0ad-4ed1e080012a)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  b94f94e885a962c77d223db9c50d25379e3f75a6d363d2e33336c9a5b6456992
Taker: 883803aff6ad4439e069a6440d39d68ca4d65c7074e4bf8e4f60b784b86c84d2
Deposit: N/A
BTC mining fees lost: 0.00026029
Trade fees lost, please state if BSQ or BTC: BTC 0

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v.1.9.9
BTC address for reimbursement: bc1qq577mlrvjkvdddnsewnkh72r260jdcwmkz3n2nd8h7ld2jv0z8qsu5qjq8

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @adidasats 

On this trade you lost:

Mining fees: 0.00003029 BTC
Trade fees: ‎0.00023000 BTC 

**Total: 0.00026029 BTC**

You should make your wallet is synced correctly by doing an SPV resync 

https://bisq.wiki/Resyncing_SPV_file

@leo816 please can you add this to your next reimbursement batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1461
