### ISSUE TITLE
Fee reimbursement for trade tnawkn

### ISSUE THREAD

**Issue by adidasats** [bisq-network/support#1439]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
![Screen Shot 2023-06-29 at 8 49 10 PM](https://github.com/bisq-network/support/assets/138173943/acf044e6-e71c-487a-ab5e-592e7ca35799)

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 8e6bacb59c68c93be10f937ba1928ab2ca7cf0a49b92d1d6445733cb4c425f58
Taker: 3d12337823b88b5e1c3cfc1c9d6da8c28306d478d6e39e98daf3f576caa84f7c
Deposit: N/A 
BTC mining fees lost: 0.00015820
Trade fees lost, please state if BSQ or BTC:

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.9
BTC address for reimbursement: bc1qf4g9g0vnlk4m6zeuufjk2xdpju0nwnl6dnx38lf90vd7ag7mxlasfd8grg

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Not sure why I am getting all these failed trades as it states I am synced to the blockchain / current DAO etc,. Please assist thank you.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @adidasats 

On this trade you lost:

Mining fees: 0.00004320 BTC
Trade fees: ‎0.0.00011500 BTC 

**Total: 0.0001582BTC**

You should make your wallet is synced correctly by doing an SPV resync 

https://bisq.wiki/Resyncing_SPV_file

@leo816 please can you add this to your next reimbursement batch. Many thanks
