### ISSUE TITLE
Fee reimbursement for trade 477522

### ISSUE THREAD

**Issue by adidasats** [bisq-network/support#1440]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screen Shot 2023-06-29 at 8 52 25 PM](https://github.com/bisq-network/support/assets/138173943/e2ff091d-a84b-468b-814f-d7fb076eee5f)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 8c149e6116847ddb8bba1c16392eb437c7b525b37928e30e2c165f5dbecefff4
Taker: cfa220914f4cace3a0e7090502988f866afaa11964d7c8a495fe7afd6e1b0300
Deposit: N/A
BTC mining fees lost: 0.00028940
Trade fees lost, please state if BSQ or BTC:

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.9
BTC address for reimbursement: bc1qj3v74dqfu8zx4efy6xz2ntl67t4fcrmjg6qfzu97g5hdp3j6px6qq2gsd0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @adidasats 

On this trade you lost:

Mining fees: 0.00002695 BTC
Trade fees: ‎1.03 BSQ 

You should make your wallet is synced correctly by doing an SPV resync 

https://bisq.wiki/Resyncing_SPV_file

@leo816 please can you add this to your next reimbursement batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1461
