### ISSUE TITLE
Fee reimbursement for trade 58063

### ISSUE THREAD

**Issue by adidasats** [bisq-network/support#1441]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screen Shot 2023-06-29 at 8 55 25 PM](https://github.com/bisq-network/support/assets/138173943/e1fd721d-627f-405c-a9a6-28d72abc548e)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 50f71c59d68d69a60d8c3fae59fc92a5aa0959b183c73f357135753217d40e83
Taker: f69603a309f9e10489335259d47f6a421de36803e1369ee6992c256cad644f54
Deposit: N/A
BTC mining fees lost: 0.00013052
Trade fees lost, please state if BSQ or BTC:

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v.1.9.9
BTC address for reimbursement: bc1qj5lqycfs40l767h0wme9yph08xetzz94hrmg5c74lp99p8lxuugsf3wqqc

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @adidasats 

On this trade you lost:

Mining fees: 0.00005950 BTC
Trade fees: ‎0.00005000 BTC 

**Total: 0.00010950 BTC**

You should make your wallet is synced correctly by doing an SPV resync 

https://bisq.wiki/Resyncing_SPV_file

@leo816 please can you add this to your next reimbursement batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1461
