### ISSUE TITLE
Fee reimbursement for trade f73fnbm 

### ISSUE THREAD

**Issue by Theoldgits** [bisq-network/support#1442]
Hi,

I had two failed trades, where one has been reimbursed but the other hasn't.  

The above case has been closed, but I have not received reimbursement for this failed trade, only for another failed trade. 

Trade ID: f73fnbm
Trade date: 8 May 2023 16:16:48
Security deposit: Buyer: 0.0015 BTC / Seller: 0.0015 BTC
Mining fee: Maker: 0.00074550 BTC / Taker: 0.00269724 BTC
Trading peers onion address: fm3xu6mvuz7yvjklqasjcy74j67sr2tvw4fhvffheqo62px2fa33awyd.onion:9999

Maker fee transaction ID: 08e6a982e9a62ad22a12e28986f965e9493bda425a1ab9d08a8d3b641637b6cd
Taker fee transaction ID: 78f578e0069335767a5a90131e7e27cec225e2dc08b77ce592c9d8e59e3f47f

Error:

The trade protocol encountered problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Trade state: Deposit transaction has been published

Bisq version: 1.9.10
BTC address for reimbursement: bc1qg8zv30mnkwasqv39k2hap4vjxe30zp674mx6js

**Comment by darawhelan** [comment]
@Theoldgits thanks for posting.

@leo816 Please can you look into this.

Here is the original issue:

https://github.com/bisq-network/support/issues/1414

Many thanks

**Comment by darawhelan** [comment]
This payout is being chased up on issue #1456
