### ISSUE TITLE
Fee reimbursement for trade 410992

### ISSUE THREAD

**Issue by pbr57** [bisq-network/support#1444]
![Trade ID 410992](https://github.com/bisq-network/support/assets/138521530/96a3137f-42de-45cc-8e8a-0943b5cac4ed)

Maker: f729b31838dba1dfdfba72e1f0a980156a8255b363ae1f2290917eddbd2d895b
Taker: N/A
Deposit: N/A
BTC mining fees lost:
Trade fees lost, please state if BSQ or BTC: 

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.10
BTC address for reimbursement: bc1qe9ep5j6n8k2fkjjdhq53ww4xga9v62j2smx67d

Contract error. It's in failed-folder. Please reimburse fees.
Thanks.

**Comment by darawhelan** [comment]
Hi @pbr57 

As there is no taker transaction on this trade no funds / fees were spent.

You have not lost any funds.

It might be worth you doing an SPV resync if you have other trades that are failing:

https://bisq.wiki/Resyncing_SPV_file
