### ISSUE TITLE
Fee reimbursement for trade 26UFZT

### ISSUE THREAD

**Issue by Pesa2023** [bisq-network/support#1445]
![20230704-12](https://github.com/bisq-network/support/assets/138526874/8250c4c3-4ad7-4699-85e6-368ac9e6c423)

Maker: 6489c045a23c1ebc9dd74c06c06de475f655252167a8c0e688785c880a705c4b
Taker: 43c06f1a940293e81fd48c31b10c48c8eab4be08fcdd3bc75019e74f7a7be07c
Deposit: 067c1ca8ad14e4efd9ab78a4e4673996d89f402d493d48e2a9524350bcbe8bba
Payout: 6489c045a23c1ebc9dd74c06c06de475f655252167a8c0e688785c880a705c4b
BTC mining fees lost: 
Trade fees lost:
Trade Lost: 0.02 BTC

Bisq version: 1.9.9
BTC address for reimbursement: bc1q9ctrxytwptf78elpxgj02e4q59syen6luahp3e

Other notes:

Not recieved the amount of the trade (0.02 BTC), payout txid don't have de usual "Multisig 2 of 2" as a output like other transactions.

**Comment by darawhelan** [comment]
Hi @Pesa2023 this is an active trade.

It did not fail.

Who is your mediator for the trade?

Please can you open mediation for the trade. Click on the trade and press 'Ctrl' and 'O'.

**Comment by Pesa2023** [comment]
Hi @darawhelan. 
I can't open mediation anymore. It's shown to me as completed.
![20230707-9](https://github.com/bisq-network/support/assets/138526874/da20d364-6ac3-40c4-9d1f-70924d8b42a2)

**Comment by pazza83** [comment]
@Pesa2023 

I am one of the mediators. I have trade ID: 26UFZT in mediation.

The mediation messages are not being sent to yourself.

Are you on Matrix

https://bisq.wiki/Matrix_bisq.chat

If so please send me a message there. My username is:

@pazza83:matrix.org

**Comment by pazza83** [comment]
Hi @Pesa2023 

Just following up. Please can you reach out to me on Matrix so I can assist you in cancelling this trade and getting you bitcoin back.

My username is:

@pazza83:matrix.org

**Comment by Pesa2023** [comment]
Hi @pazza83, i started a conversation there earlier, did you see ?

**Comment by pazza83** [comment]
Yes, all good chatting to you now on Matrix

**Comment by pazza83** [comment]
This trade has now been completed with a manual payout

https://mempool.space/tx/bfb860ac629c9ad021120a9bef9f7b5ec3e0085081f528fa5915fa51f2ff5a62
