### ISSUE TITLE
Fee reimbursement for trade I1HTFE

### ISSUE THREAD

**Issue by plato3211** [bisq-network/support#1447]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: Buyer: 0.002250 BTC / Seller: 0.002250 BTC
BTC mining fees lost: Maker: 0.000035 BTC / Taker: 0.00006990 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._1.9.10

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._
Maker fee transaction ID: 48eb1632aefa06de60a5c5dbe3a6f8eede86e29249242dda967373db8d2d7ca8
![Screenshot 2023-07-06 194242](https://github.com/bisq-network/support/assets/126491049/6b4e29b2-8cf4-4eab-876a-baa8e71b10ba)

**Comment by darawhelan** [comment]
Hi @plato3211 

As there is no taker transaction on this trade no funds / fees were spent.

You have not lost any funds.

It might be worth you doing an SPV resync if you have other trades that are failing:

https://bisq.wiki/Resyncing_SPV_file
