### ISSUE TITLE
Fee reimbursement for trade 61wci96

### ISSUE THREAD

**Issue by Eldesto** [bisq-network/support#1448]
![Chyba v obchode](https://github.com/bisq-network/support/assets/139342614/22104f3c-21b4-4fa2-81b1-e408c0575739)

>

Maker: 8e4e37d2ea33cc8279ef46a6e1483f983cef2a818710581623d53a9ca800a07e
Taker: acf44ce8e1d27eef22bd99061a09bd3f874159c93573c459802328a30abc991b
Deposit: N/A
BTC mining fees lost:  0,00006990 BTC
Trade fees lost, please state if BSQ or BTC:   0,00006840 BTC
Total BTC trade amount lost: 0,00013830 BTC

>

Bisq version: 1.9.10
BTC address for reimbursement: bc1qlhxnarzkd75s9us9rfr8crf7l7a5l9hlfw8lk9

>

Other notes: THX for the solution.

>

**Comment by darawhelan** [comment]
Hi @Eldesto 

Thanks for posting.

Please check your DAO is in sync. That is likely the reason this trade  failed.

Go to DAO and then click on Network Status.

If your DAO is out of sync you will need to restart Bisq.

You lost on this trade:

Miner fee: ‎0.00002330 BTC
Trade fee:  ‎0.00011500 BTC

**Total: :  ‎0.00013830 BTC**

@leo816 please can you reimburse in your next batch. Many thanks

**Comment by Eldesto** [comment]
Hello, despite the fact that you have closed my case, I still do not register the return of my lost funds.

**Comment by darawhelan** [comment]
Hi @leo816 please can you take a look at this. Many thanks
