### ISSUE TITLE
Fee reimbursement for trade GSTPXHI

### ISSUE THREAD

**Issue by bitdern** [bisq-network/support#1450]
![Screen Shot 2023-07-17 at 1 09 38 PM](https://github.com/bisq-network/support/assets/103206086/01996f2b-e331-4c25-a1ce-82c4b44cdd97)

Maker:  850b4955e1bb2a499b62403642b30e4fe33d22290ed3c972d991eeba6aef9cae
Taker: 987f562af222d461722be41b88a404ba089992fb2c40e481a1ade9826215533b
Deposit: 3779583556c8c0381b424355ebd77e0fa7b096c810a79d93c71abe02fe09b99e
BTC mining fees lost: Maker: 0.00003080 BTC / Taker: 0.00008388 BTC
Trade fees lost, please state if BSQ or BTC: N/A

Bisq version: 1.9.10
BTC address for reimbursement: bc1qu3fv9t0sw3edkafqctkc8pnpuast49pf0tlcwz

Other notes: Looks like there was a timeout on the deposit tx
![Screen Shot 2023-07-17 at 1 06 00 PM](https://github.com/bisq-network/support/assets/103206086/de9c06ad-480e-4855-b79d-d9ae28d94ac4)

**Comment by darawhelan** [comment]
Hi @bitdern 

I confirm you lost fees on this failed trade

Mining fees: 0.00003080 BTC
Trade fees: 0.00005000 BTC

**Total: 0.00008080 BTC**

I would recommend you check your DAO is in sync. Either yourself or the seller's DAO was out of sync resulting in a failed trade. 

Go to DAO, network Status to the see the status of your DAO. If it is out-of-sync a restart will be recommended.

@leo816 please can you add to you list for reimbursement. Many thanks.

**Comment by bitdern** [comment]
Hi @darawhelan -- wanted to follow up here and thank you for suggesting to restart the DAO, I believe that was the source of the issue on my end (since the deposit transaction appears to have never been broadcast)!

**Comment by darawhelan** [comment]
Great to hear. Pleased your issue has been resolved.

**Comment by bitdern** [comment]
Hi @darawhelan @leo816 I haven't yet received reimbursement for these trade fees, can you please action when you get the chance?

Please use this address: bc1q9u8f3stv9v5umsnjjdvfg36zcuyp88tyqzx898

**Comment by leo816** [comment]
Payout made with #1461
