### ISSUE TITLE
Fee reimbursement for errored trade due to software version

### ISSUE THREAD

**Issue by SymmetryStan** [bisq-network/support#1453]
hello,

I raised a bug in the issues section here: https://github.com/bisq-network/bisq/issues/6779

Basically I lost a transaction fee when trying to put an order on the market when using version 1.9.10. The error was:

ul-24 09:45:58.454 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: AddToOfferBook
Please update to the latest Bisq version. A mandatory update was released which disables trading for old versions. Please check out the Bisq Forum for more information.

I did an SPV resync but that fee (0.00006750 bitcoin) has gone.

TX ID showing in my transactions history for the amout of 6750 satoshi: 

ad0e18c4ef25e5ff29a0762ed068c54f5241ec71d4e23103cba90f6d09753722

Address for reimbursement: bc1q3jza0tharuy2777tcfdp6wrcjhkj84axnqfccz

Thanks for considering.

**Comment by Wardism** [comment]
> hello,
> 
> I raised a bug in the issues section here: [bisq-network/bisq#6779](https://github.com/bisq-network/bisq/issues/6779)
> 
> Basically I lost a transaction fee when trying to put an order on the market when using version 1.9.10. The error was:
> 
> ul-24 09:45:58.454 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: AddToOfferBook Please update to the latest Bisq version. A mandatory update was released which disables trading for old versions. Please check out the Bisq Forum for more information.
> 
> I did an SPV resync but that fee (0.00006750 bitcoin) has gone.
> 
> TX ID showing in my transactions history for the amout of 6750 satoshi:
> 
> ad0e18c4ef25e5ff29a0762ed068c54f5241ec71d4e23103cba90f6d09753722
> 
> Address for reimbursement: bc1q3jza0tharuy2777tcfdp6wrcjhkj84axnqfccz
> 
> Thanks for considering.

Hi @SymmetryStan 
visit the official Bisq page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Bisq Support](https://bisqwiki.online/)

**Comment by darawhelan** [comment]
Hi @SymmetryStan 

Thanks for posting.

I can confirm you lost 0.00006750 BTC on this trade.

@leo816 please can you add to your list for reimbursement. Many thanks

**Comment by leo816** [comment]
Payout made with #1461
