### ISSUE TITLE
Fee reimbursement for trade g19Daa5

### ISSUE THREAD

**Issue by zdick** [bisq-network/support#1454]
![Snímek obrazovky pořízený 2023-07-25 15-13-20](https://github.com/bisq-network/support/assets/22180386/167dc065-b353-48d6-8034-916e4f980c1a)

Maker:  50d20b24aaa010e81d676a8ace97d76a820d0a4bae7dda9db3c0c119b3ef1248
Taker: 6ba43703c73e5dd3622438dedd168702bd4e562d709895a12f4606396635ca1c
Deposit: N/A
BTC mining fees lost: 0.00007170 BTC
Trade fees lost: 3.84 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1q50wg8ynwcr65pd4husfz9k6zp3kffrr9fyy0k4

Trade state: TAKER_FEE_PUBLISHED

**Comment by darawhelan** [comment]
Hi @zdick 

Thanks for posting.

On this trade you lost:

Mining Fee: 0.00002390 BTC
Trade fee:  3.84 BSQ

I would recommend you check your DAO is in sync. Either yourself or the seller's DAO was out of sync resulting in a failed trade.

Go to DAO, network Status to the see the status of your DAO. If it is out-of-sync a restart will be recommended.

@leo816 please can you add to you list for reimbursement. Many thanks.

**Comment by leo816** [comment]
payout made with #1476
