### ISSUE TITLE
Fee reimbursement for trade 23911

### ISSUE THREAD

**Issue by SteffenD24** [bisq-network/support#1455]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screenshot 2023-08-13 at 00 54 00](https://github.com/bisq-network/support/assets/142124454/8f0281b0-6693-457b-afc0-3478b9476e0b)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Dear team, thank you for your assistance. Also, I am unable to process the transaction again. I get a warning message which is the following: "Warning - You cannot take this offer because you already took it earlier. It could be that your previous take-offer attempt resulted in a failed trade." - Pls, what could I do? Kindly and gratefully 

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @SteffenD24 as you were the taker and there is no taker transaction you have not lost any miner or trade fees on this trade.

I would recommend you do an SPV resync to make sure your wallet is in sync: https://bisq.wiki/Resyncing_SPV_file
