### ISSUE TITLE
 Fee reimbursement for trade f73fnbm #1414 

### ISSUE THREAD

**Issue by Theoldgits** [bisq-network/support#1456]
I had a failed trade from May and it has still not been reimbursed. It was forgotten about in June and I did send a reminder in July and am still waiting.

the original issue:

[#1414](https://github.com/bisq-network/support/issues/1414)

Please can you reinburse the remaining BTC.

Many thanks.

**Comment by Theoldgits** [comment]
I forgot to mention I am not Iyd4raf (the idiot that that posted my personal details onliner), I was the buyer and maker.

**Comment by darawhelan** [comment]
Hi @Theoldgits thanks for the follow up.

@leo816 please can you process a refund.

The issue can be seen here: https://github.com/bisq-network/support/issues/1442

Miner fee: 0.00074550 BTC
Trade fee: 0.00005000 BTC

**Total: 0.00079550 BTC**

BTC address for reimbursement: bc1qg8zv30mnkwasqv39k2hap4vjxe30zp674mx6js
