### ISSUE TITLE
Fee reimbursement for trade rrqdpCw

### ISSUE THREAD

**Issue by rathulw** [bisq-network/support#1462]
![trade](https://github.com/bisq-network/support/assets/142275767/6317f126-b87a-48b9-845d-199d6cbbc7f0)

Maker: 54270b54bb1a3bfc21359732548b7e2427bc6f70cbd5705587ea2d99cf8488a7
Taker: cea1810007f5fd527a4979e094cd141ffd489c2775adddf8424b9a52e1512e97
Deposit: 5c49f28f761ab37afc47d449139829dc3fa7ada297065b88a54cdf43931b808f
BTC mining fees lost: 0.00006990 BTC
Trade fees lost: 0.00010725 BTC

Bisq version: 1.9.12
BTC address for reimbursement: bc1qvgyyvvytcgtyn7a8euvq0khgstr2k0y45wv0nr

**Comment by darawhelan** [comment]
Hi @rathulw

This trade did not fail. It is an active trade.

Do you have trade ID rrqdpCw in you Open Trades?

I would recommend reaching out for support on Matrix asap if you do not.

https://bisq.wiki/Matrix_bisq.chat
