### ISSUE TITLE
Fee reimbursement for trade EZPVSQ

### ISSUE THREAD

**Issue by rathulw** [bisq-network/support#1463]
![trade2](https://github.com/bisq-network/support/assets/142275767/d4fd5b85-ae29-464f-9f45-1dec870d54f4)

Maker:  686b78d06d7309b0cf553ac828ef73f4738b66d078181b23547b851e2e2ed8c9
Taker: 2dfd9d1fcd344389fdf1e62570228f93d51d4a1a5f61bd9983904da89f91d246
Deposit: 392baf98ddb79698a6b47537d62aa0c820452f7f939d4e0a17198bcba329748a
BTC mining fees lost: 0.00007689 BTC
Trade fees lost: (it doesn't show, i'll explain why)

Bisq version: 1.19.12
BTC address for reimbursement:

Other notes:

I started a trade, and I made the security deposit (0.00186550BTC) with my bisq wallet, after I saw the security deposit in my transactions and saw that it wasn't confirm after a long time, and decided to do an spv resync, After this I didn't see the security deposit and the trade fee in my transactions, I thought it was a bug in bisq I decided to export my wallet in Electrum and see the security deposit but it just disappeared, it isn't even in my wallet and there isn't anywhere, so I lost in the moment I do an spv resync? Before this, I saw that the security deposit wasn't published on blockchain even though the bisq said it was, If it wasn't even 'added' as unconfirmed on blockchain it had to be untouched in my wallet, but it just disappeared.

**Comment by darawhelan** [comment]
Hi @rathulw 

You were the taker for this trade.

There is no valid taker transaction ID.

You have not lost any funds on this trade as a transaction did not take place.

You should do an SPV resync on your Bisq wallet again.
