### ISSUE TITLE
Fee reimbursement for trade endchn

### ISSUE THREAD

**Issue by gbesacier** [bisq-network/support#1464]
![2023-08-26 at 17 17 05](https://github.com/bisq-network/support/assets/2737489/8ceef810-b774-4287-b6bb-f1b326723b87)

Maker:  e983a9a872808a5f82b2b5327c74a35d4911d69bfb11a13d53d46c8adb7ef0b6
Taker: 645a518d3ecc94e780b51b5b9d82c2ad34b45a791ae813051f18b6637949c0a7
Deposit: db4d3f1673c9f0bffb77edd06ccf444b277657564ca9f1d158c1c7c77048f917
BTC mining fees lost: 0.0000175 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005 BTC

Bisq version: 1.9.12
BTC address for reimbursement: bc1qqdh6er32fvl68qn7ucq725rlzavxzgmqj0l7e0

Other notes:

**Comment by darawhelan** [comment]
Hi @gbesacier 

On this trade you lost:

Miner fee: 0.00001750 BTC
Trade fee: 0.00005000 BTC

**Total: 0.00006750 BTC**

@leo816 please can you add to the list of users that require reimbursement. Many thanks

**Comment by leo816** [comment]
payout made with #1476
