### ISSUE TITLE
Fee reimbursement for trade 6450681

### ISSUE THREAD

**Issue by 8888account** [bisq-network/support#1465]
![image](https://github.com/bisq-network/support/assets/143507268/e1c87d26-8042-4bd9-94a2-90b1e483ad3a)

Maker: 017aba5877a958274e4262e75b8fdcfca9648edcba82a8894a9cd3b1c68a8b78
Taker: 6889a8fc58b625d85fd5b3c45ba8ebade6a142d3380227c10597b63a61009beb
Deposit: 3ab853476aac7d18dfce95294755353b03d63c6e12b80a4c1161929f97f8afd1
BTC mining fees lost: Maker: 0.00002450 BTC / Taker: 0.00008388 BTC
Trade fees lost, please state if BSQ or BTC: NA

Bisq version: V1.9.12
BTC address for reimbursement: bc1q89m8rehu52f7q2xnqpuwms03wnd6rnmls3me3d

Other notes:
![image](https://github.com/bisq-network/support/assets/143507268/419d0673-b073-479a-a16f-0d09dc6f3fb5)

**Comment by 8888account** [comment]
mediator advised the issue is the seller hasnt accepted mediator resolution yet....

**Comment by darawhelan** [comment]
Hi @8888account 

Thanks for the post.

You will be able to escalate the trade to arbitration (10 days after the date of the trade) if your trade peer does not accept the mediation proposal.

Please let your mediator know about the error message you received. You might just need to press the button again.
