### ISSUE TITLE
Fee reimbursement for trade FVBYDA

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1466]
![image](https://github.com/bisq-network/support/assets/63785272/64b7aecf-825e-4bfc-8cda-fd0f53034de2)
Maker:  1367f491a6849a264d2efd3089af9de325b8b0a6d5916b53a4b6610bf8930ba6
Taker: 4fad746a7bb9742349cf826edeff1cbe898c15013263df890a14678283659e93
Deposit: 554a6edf8001e8409602429e17f17ebcc79bdd2db2901c3fa22413b473a4f96e
BTC mining fees lost: 0.00003430 BTC
Trade fees lost, please state if BSQ or BTC: 51.32 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1qz40n5tvcj58l86ed02rdc6txsu3df4ftma403m

Other notes: None

**Comment by darawhelan** [comment]
Hi @Akira45-0 

Thanks for posting. I confirm you lost

BTC mining fees: 0.00003430 BTC
Trade fees: 51.32 BSQ

@leo816 please can you make the reimbursement. The BSQ amount for this trade fee is significant.

**Comment by leo816** [comment]
payout made with #1476
