### ISSUE TITLE
Fee reimbursement for trade 151840

### ISSUE THREAD

**Issue by hashkebab1** [bisq-network/support#1467]
![23aug](https://github.com/bisq-network/support/assets/144237565/0de9206d-481f-43a0-94a4-220344eec80e)

Maker:  3cf5978b435bac16e9cb04b6bd12558d830f5b50a58b7c9e42508cb911ad82b7
Taker: 50a0ef6ab1bb11b06121ae31be58a9736807adac47716caaca6323cad467843a
Deposit: 41b1d1ecd7862dd8143129f0b92c658c85aa943b0b5d7ad92e586e2c0b372c70
BTC mining fees lost: 0.00004536 BTC
Trade fees lost, please state if BSQ or BTC: 0.26 BSQ 

Bisq version: 1.9.12
BTC address for reimbursement: bc1qunsgshznz9c7ea97ywp3jhj5hdvnpq3ney79jr
BSQ: Bbc1qakrq6gvvfmnnpvtr7j7pk7r02uhr5fhn3f2fre

**Comment by darawhelan** [comment]
Hi @hashkebab1

I confirm you lost

BTC mining fees lost: 0.00004536 BTC
Trade fees lost: 0.26 BSQ

@leo816 please add to your next batch for reimbursement.

**Comment by leo816** [comment]
payout made with #1476
