### ISSUE TITLE
Fee reimbursement for trade svdgwo

### ISSUE THREAD

**Issue by hashkebab1** [bisq-network/support#1468]
![5sept](https://github.com/bisq-network/support/assets/144237565/16a143ae-f6ae-4bfe-b2ff-636a39845758)

Maker:  a3662a0beb735b56c4b68dc5a69b575d4d9495e2dfa2e507896433535dfc71ab
Taker: 31e5b92cacbc27f81b2f50de050cf033362f53f63588f546bc07da122810d91a
Deposit: 
BTC mining fees lost: 0.000031 BTC
Trade fees lost, please state if BSQ or BTC: 0.26 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1qunsgshznz9c7ea97ywp3jhj5hdvnpq3ney79jr
BSQ: Bbc1qakrq6gvvfmnnpvtr7j7pk7r02uhr5fhn3f2fre

**Comment by darawhelan** [comment]
Hi @hashkebab1

I confirm you lost

BTC mining fees lost: 0.000031 BTC
Trade fees lost: 0.26 BSQ

@leo816 please add to your next batch for reimbursement.

**Comment by leo816** [comment]
payout made with #1476
