### ISSUE TITLE
Fee reimbursement for trade 1kwwh

### ISSUE THREAD

**Issue by hashkebab1** [bisq-network/support#1469]
![6sept](https://github.com/bisq-network/support/assets/144237565/366ddce5-cd47-4fd8-8a99-ae4eed362b49)

Maker:  648e1ab82e0f7694f006d65a7bff5da5fde5586c43d123955ad829f42639219e
Taker: 14aa3101e0c60c03978a57c0281df9521315ae1f2539f835d2806cf01d5a1252
Deposit:
BTC mining fees lost: 0.0000465 BTC
Trade fees lost, please state if BSQ or BTC: 0.26 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1qunsgshznz9c7ea97ywp3jhj5hdvnpq3ney79jr
BSQ: Bbc1qakrq6gvvfmnnpvtr7j7pk7r02uhr5fhn3f2fre

**Comment by darawhelan** [comment]
Hi @hashkebab1 

I confirm you lost

BTC mining fees lost: 0.0000465 BTC
Trade fees lost: 0.26 BSQ

@leo816 please add to your next batch for reimbursement.

**Comment by leo816** [comment]
payout made with #1476
