### ISSUE TITLE
Fee reimbursement for trade 515417

### ISSUE THREAD

**Issue by rapkaalarihindu89** [bisq-network/support#1470]
![trade515417](https://github.com/bisq-network/support/assets/114159123/39a853ad-39b6-4f39-a9a1-616958ecd019)

Maker: 39c4148a1347bf6f17133c6bd52cfe59fb836d3272655128e7cf5a606a4bf73c
Taker: 5d99b6575d7d461c17a30fc1a125ca4419093dc7d110ea4688fbf004d5edd57f
Deposit: 
BTC mining fees lost: 0.00012195 BTC
Trade fees lost, please state if BSQ or BTC: 98.35 BSQ 

Bisq version: 1.9.12
BTC address for reimbursement: bc1qnx0rdum9g4rvuygnr3t63k6s8j4yppnjgpj0h2
BSQ address for reimbursement: Bbc1q6gvx8gkrq5aks9nfyd3036xrv55rnw5akwjjnw

**Comment by darawhelan** [comment]
Hi @rapkaalarihindu89 

On this trade you lost:

Miner fees lost: 0.00004065 BTC
Trade fees lost: 98.35 BSQ

Please make sure your DAO is in sync. Go to DAO and then Network Monitor to see the status.

@leo816 please can you add to your list of reimbursements

**Comment by leo816** [comment]
payout made with #1476
