### ISSUE TITLE
Fee reimbursement for trade uypwwhg

### ISSUE THREAD

**Issue by rapkaalarihindu89** [bisq-network/support#1471]
![tradeuypwwhg](https://github.com/bisq-network/support/assets/114159123/4361ea67-5500-4099-9c6f-d7a4e155b36e)

Maker:  dcdcd0ad3ccc4064b24e562b4a396f28ca4ce0142921fc2537dbf4fddafd8b25
Taker: 23d4214f265a351160cec45fb41333576afd3ffca7823a23289d5e25d84ba496
Deposit: 
BTC mining fees lost: 0.00012582 BTC
Trade fees lost, please state if BSQ or BTC: 19.67 BSQ 

Bisq version: 1.9.12
BTC address for reimbursement: bc1qnx0rdum9g4rvuygnr3t63k6s8j4yppnjgpj0h2
BSQ address for reimbursement: Bbc1q6gvx8gkrq5aks9nfyd3036xrv55rnw5akwjjnw

**Comment by darawhelan** [comment]
Hi @rapkaalarihindu89

On this trade you lost:

Miner fees lost: 0.00004194 BTC
Trade fees lost: 19.67 BSQ

Please make sure your DAO is in sync. Go to DAO and then Network Monitor to see the status.

@leo816 please can you add to your list of reimbursements

**Comment by leo816** [comment]
payout made with #1476
