### ISSUE TITLE
Fee reimbursement for trade bqnph

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1472]
![image](https://github.com/bisq-network/support/assets/63785272/b5102bf3-59f0-425f-adc7-fa920dfcdf31)
Maker:  56f19757b4de082a555d4a557ec5394a8b6120e4a385a80730d55a8ba745a439
Taker: 9efbff5decbf370793175d2f71e1466f7f3d4de90e09a6155c8592cf554fa24c
Deposit: 
BTC mining fees lost: 0.00003430 BTC
Trade fees lost, please state if BSQ or BTC: 6.42 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1q8hf406mzxfpdp70xeythcnzdclgcr8fuztuaku

Other notes: None

**Comment by darawhelan** [comment]
Hi @Akira45-0 

On this trade I confirm you lost:

Miner fees lost: 0.00003430 BTC
Trade fees lost: 6.42 BSQ

Please make sure your DAO is in sync. Go to DAO and then Network Monitor to see the status.

@leo816 please can you add to your list of reimbursements.

**Comment by leo816** [comment]
payout made with #1476
