### ISSUE TITLE
Fee reimbursement for trade 8476963

### ISSUE THREAD

**Issue by hovno666** [bisq-network/support#1473]
![image](https://github.com/bisq-network/support/assets/145274198/7c505d63-27de-4a5e-9463-e4c061e8dece)

Maker:  35b41dd746c9c37cf1bc9f06365c910e7e889a44afa15153d3152c2491c0ad2c
Taker: ecf02a1ea666ac2a77ab7765086d46683f60b67cddc3ed72c642ea8553cac7ed
Deposit: 
BTC mining fees lost: 0.00002275 BTC
Trade fees lost, please state if BSQ or BTC:  0.00005000 BTC

Bisq version:  1.9.12
BTC address for reimbursement: bc1quv8l333halekyre0stllaercsw2cwe4gtf0de4

Other notes: None

**Comment by darawhelan** [comment]
Hi @hovno666 

Thanks for posting I can confirm on this trade you lost:

BTC mining fees lost: 0.00002275 BTC
Trade fees lost: 0.00005000 BTC

**Total lost 0.00007275 BTC**

@leo816 please can you add to your list for reimbursements. Many thanks

**Comment by leo816** [comment]
Payout made with #1531
