### ISSUE TITLE
Fee reimbursement for trade 40183

### ISSUE THREAD

**Issue by dev-lino** [bisq-network/support#1475]
![capture](https://github.com/bisq-network/support/assets/123249237/47da0922-9346-4a16-abf3-18286b831056)

Maker:  116541e9579da866d38babeff0f45a802d5f10025128be74696be7a5d0a96d50
Taker: 
Deposit: 
BTC mining fees lost: 0.00022572 BTC
Trade fees lost, please state if BSQ or BTC: 0.000575 BTC

Bisq version: 1.9.12
BTC address for reimbursement: bc1q708jngz6jca6ylxu23aueug6wc80mpmdljxffu

Other notes:

**Comment by darawhelan** [comment]
Hi @dev-lino 

As you were the taker for this trade you did not lose any miner or trade fees as no taker transaction took place. No funds left your wallet.
