### ISSUE TITLE
Fee reimbursement for trade RymEpuZX

### ISSUE THREAD

**Issue by Kiremai974** [bisq-network/support#1477]
![image](https://github.com/bisq-network/support/assets/44039194/26c69a52-0381-4f56-8dc0-6a31ad93aa9d)

Maker:  f865d01eba658e54b57e60206c5a939b6fa51f9b646e2fe8aaf48998aa5a5898
Taker: 5a4454e85ac084a98d699e8a18f88dde092a68d35feb0a62ebdd85b2742dbbbd
Deposit: N/A
BTC mining fees lost: 0.00004340 BTC
Trade fees lost, please state if BSQ or BTC: 0.00004279 BTC

Bisq version: 1.9.12
BTC address for reimbursement: bc1qexdjmxjm6ktjlajd2nsy042sps6zxsta680npw

Other notes:

**Comment by darawhelan** [comment]
Hi @Kiremai974 

For this trade you lost:

Miner fees:  0.00004340 BTC
Trade fees: 0.61 BSQ

@leo816 please can you add to your list for reimbursement. Many thanks

**Comment by leo816** [comment]
Payout made with #1515
