### ISSUE TITLE
Fee reimbursement for trade ccdwksx

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#1478]
![image](https://github.com/bisq-network/support/assets/141868491/077e344b-1884-4dfa-ade7-480c1c6a47eb)

Maker fee txid: 2465b571263d5d2acf1affb2cd451dba7480d9dab7be4cb89be7dc8315aeb13c
Taker fee txid: 776ca8d492cf3eeb13ad3f26f4115166625533e5e8ebf994dbd5213d80f98043

BTC mining fees lost: 0.00006370 BTC
Trade fees lost: 57.63 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1q3ugwmll9sswcgnjsh0w79cq0lga3e7qf2mhsqs

Error: "An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same."

Please reimburse fees.

**Comment by darawhelan** [comment]
Hi @worminder 

I confirm in this trade you lost:

miner fees: 0.00005896 BTC
trade fees: 57.63 BSQ

@leo816 Please can you add to your list or reimbursements. Many thanks

**Comment by leo816** [comment]
Payout made with #1515
