### ISSUE TITLE
Fee reimbursement for trade PFVIViw

### ISSUE THREAD

**Issue by 1000opentabs** [bisq-network/support#1479]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
<img width="882" alt="Screenshot 2023-10-20 at 2 55 03 PM" src="https://github.com/bisq-network/support/assets/148583426/b184a3e7-8e10-490e-8e39-1d5cad7e0ba7">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........5365e19d154a84f23c810ab0bac63131e35f483066c762bf2dd04dad324404c3
Taker: ...........NA
Deposit: ..........0.0125 BTC
BTC mining fees lost: .......... 0.00002390 BTC
Trade fees lost:2,390 sat

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:1.9.3
BTC address for reimbursement: bc1qp6gdklhn3f0ylwgrc47kd4cks9tvv82s8uqhkn

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi this trade ended up getting completed. 

If the trade fails like this it will stay online for someone else to take and that looks like what happened in this case.

You did not lose any funds.

The trade paid out here with this transaction: 7c675eef89c0463894e7808f18854ee8d3477c7dfabeabe0c42aa0c578aa44fa
