### ISSUE TITLE
Reimbursement for trade 7316228

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#148]
![image](https://user-images.githubusercontent.com/301810/47268948-68af7380-d557-11e8-9f56-fbd3b1014668.png)

Maker: f41cd191bef4d3be9311d8e9ee64c82fe127eb173393c20c5c87fad9f2355b6e
Taker: 3f7d6fefb8683745928158e5924867ddcc155e88d5117676e595a29e724402bb
Deposit: 4579521c349897c1087d534f94ab93df76c3596bdc4c7adb8624354e6efa66b7

Deposit transaction was not broadcast (deposit tx shown above is valid but for a different, earlier trade). Lost maker and taker fees will be reimbursed in #147.

**Comment by KanoczTomas** [comment]
@cbeams closing, as the script did not auto close this one so it seams.
