### ISSUE TITLE
Fee reimbursement for trade YCVGJ

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#1483]
![image](https://github.com/bisq-network/support/assets/141868491/3dabac57-60ff-4992-becd-3a2e2ff8079c)

Maker fee txid: 9591415c90d51de8d16ada879eb057f9882e0e648a67530bb297ecc2eb3ad9b8

BTC mining fees lost: 0.00003708 BTC
Trade fees lost: 12.83 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1q3ugwmll9sswcgnjsh0w79cq0lga3e7qf2mhsqs

Error: "An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same."

Please reimburse fees.

**Comment by darawhelan** [comment]
Hi @worminder 

I can confirm on this trade you lost:

Miner fee: 0.00003708 BTC 
Trade fee: 12.83 BSQ

@leo816 please can you reimburse on you next batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1515
