### ISSUE TITLE
Fee reimbursement for trade ojunc

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#1484]
![image](https://github.com/bisq-network/support/assets/141868491/23d8ee60-9a86-44f0-ae79-afcc2c1335e5)

Maker fee txid: 1d3af747ee81171efccb4041c24df5610c168cb12f86d200e2db7c875480fc83

BTC mining fees lost: 0.00004017 BTC
Trade fees lost: 12.83 BSQ

Bisq version: 1.9.12
BTC address for reimbursement: bc1q3ugwmll9sswcgnjsh0w79cq0lga3e7qf2mhsqs

Error: "An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same."

Please reimburse fees.

**Comment by darawhelan** [comment]
Hi @worminder

This trade ended up being completed.

As you are the maker the trade stayed online for another person to take and this is what happened.

No funds were lost
