### ISSUE TITLE
Fee reimbursement for trade R9DEKN

### ISSUE THREAD

**Issue by tsktp** [bisq-network/support#1485]
![issue](https://github.com/bisq-network/support/assets/6167444/1af579c8-0e9c-4494-b242-0ed9c7076812)

Maker: 30a1d9881e5ae3ad9a1ad78318b0fa8137d772a5fd229c1f1ebd11a3d0dfaee9
Taker: 3b8703aa57d8f285fb5780859508e03a9717dd6a5cc9b732f305d83e714d8682
Deposit: .0030 BTC
BTC mining fees lost: .00009087 BTC
Trade fees lost, please state if BSQ or BTC: 3029 sat

Bisq version: 1.9.9
Error Message: 
```
An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx 
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.
```
BTC address for reimbursement: bc1qaanmqtv3m2g2qzjtwd9yettttmlwfzeg3chvre

**Comment by darawhelan** [comment]
Hi @tsktp 

For this trade you lost:

Miner fee: 0.00003029 BTC
Trade fee: 0.00017250 BTC

**Total: 0.00020279 BTC**

@leo816 please can you add to your list for reimbursement. Thank you

**Comment by leo816** [comment]
Payout made with #1515
