### ISSUE TITLE
Fee reimbursement for trade XWRSWYAM

### ISSUE THREAD

**Issue by Jantje35** [bisq-network/support#1486]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![afbeelding](https://github.com/bisq-network/support/assets/142612862/6f7bca75-356a-4501-9892-3c45154a8e9f)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
  "makerAccountId": "22492418",
    "id": "XWRSWYAM-8c8c132d-5669-479d-8451-0e5fb167e7c8-1910",
    "date": 1698134312001,

Taker: ...........
  "takerAccountId": "457580616",

Deposit: ..........
    "buyerSecurityDeposit": 1036176,
    "sellerSecurityDeposit": 1036176,

BTC mining fees lost: .......... eg 0.00005 BTC
    "txFee": 8192,
    "makerFee": 5000,
    "isCurrencyForMakerFeeBtc": true,
    "buyerSecurityDeposit": 1036176,
    "sellerSecurityDeposit": 1036176,

Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC
BTC 

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

BTC address for reimbursement:

bc1ququ3s0y264lzju9n50wms0hz7pnnxjyya3jhhn

Bisq version: 1.9.10-1

**Comment by darawhelan** [comment]
Hi @Jantje35 

Please can you copy and paste the maker and taker transaction IDs into the comments.

Many thanks
