### ISSUE TITLE
Fee reimbursement for trade NZoJz

### ISSUE THREAD

**Issue by Jantje35** [bisq-network/support#1487]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![afbeelding](https://github.com/bisq-network/support/assets/142612862/8e56ccf0-5da1-4346-b3e1-29ce51c66410)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
624d588a553952574c817051730cd0dcd50746ba1eef64664a1accd5c0a747c1

Taker: ...........
13bc36f50b9878b340527f007a4ceaca0db98723e5dd9b71c2e20371f7bd81ff

Deposit: ..........
    "buyerSecurityDeposit": 364500,
    "sellerSecurityDeposit": 364500,

BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

BTC address for reimbursement:
bc1ququ3s0y264lzju9n50wms0hz7pnnxjyya3jhhn

>_Provide the Bisq client version to help developers identify the causing issue._
Bisq version: 1.9.10-1

**Comment by darawhelan** [comment]
Hi @Jantje35 

For this trade you lost:

Miner fee: 0.00001750 BTC
Trade fee: 0.00005000 BTC

**Total: 0.00006750 BTC**

@leo816 please can you add to your list for reimbursement. Thank you

**Comment by leo816** [comment]
Payout made with #1515
