### ISSUE TITLE
Fee reimbursement for trade on6xcw

### ISSUE THREAD

**Issue by MiamiRetro** [bisq-network/support#1488]
<img width="913" alt="Screenshot 2023-10-24 at 3 17 16 PM" src="https://github.com/bisq-network/support/assets/107248822/4f43fcc6-a814-482f-8080-560e17774a83">

Maker:  04b31cfb32a13b6e790ed0626891bd055275eaf4bd892bc810d640568e76246f
Taker: 96bfd5a5bc5a5adf18720528a62c6b67eeb03280f15cb12b7e89bf768c9fd483

Deposit: 0.006580 BTC
BTC mining fees lost: 0.00006990 BTC

Bisq version: 1.9.9
BTC address for reimbursement: bc1qjdnmequf3rd0tv3cf83yyszws042lvhmep5yra

"An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same."

**Comment by darawhelan** [comment]
Hi @MiamiRetro 

For this trade you lost:

Miner fee: 0.00002330 BTC
Trade fee: ‎0.00046000 BTC

**Total: 0.00048330 BTC**

@leo816 please can you add to your list for reimbursement. Thank you

**Comment by leo816** [comment]
Payout made with #1515
