### ISSUE TITLE
Fee reimbursement for trade LUHICO

### ISSUE THREAD

**Issue by budralston27265** [bisq-network/support#1489]
![Screenshot (9)](https://github.com/bisq-network/support/assets/149159566/c5b93bee-4f31-47f0-b432-ff4cfa2ed7fc)

Maker:  5963a703a470cfd032bcebb94e06474c184c6e1e36e4d8ba76937a67017d0542
Taker: 66b3cb50bb21e563b81dfedafaa14d34457653509a0bed70a256f8e4f58f092a
Deposit: 0.010940 BTC
BTC mining fees lost: 0.00001750 BTC

Bisq version: 1.7.5
BTC address for reimbursement: bc1q7lrfww3rsg9x370gc4g049w0wjkxk56pg6k5x7

**Comment by darawhelan** [comment]
Hi @budralston27265 

On this trade you lost:

Miner fees: 0.00001750 BTC 
Trade fees: 0.00005470 BTC

**Total: 0.00007220 BTC**

@leo816 please can you reimburse in your next batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1515
