### ISSUE TITLE
Deposit TX not transmitted for offer ZSdtM

### ISSUE THREAD

**Issue by brndnng** [bisq-network/support#149]
The offer ZSdtM was published but with no Deposit TX. The maker fee tx is 42aad27ae2c39963884a86447a5a21eeb52fc957b1df9440bdde7105d9d918bc. 

It would be great if you can reimburse me the maker fee tx.

Thanks

**Comment by cbeams** [comment]
Please update the description with a screenshot, and copy and paste the taker and deposit transactions. Use https://github.com/bisq-network/support/issues/150 as a template.

Also, please open a dispute ticket about this (CMD-O) if you haven't already.

**Comment by KanoczTomas** [comment]
@brndnng any update on your side?

**Comment by brndnng** [comment]
Apparently the maker tee tx went through and a trade was completed afterwards. Thanks for the help.
