### ISSUE TITLE
Fee reimbursement for trade 3379064

### ISSUE THREAD

**Issue by Mischa2805** [bisq-network/support#1490]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://github.com/bisq-network/support/assets/149179309/db114d02-5215-47c2-b789-01ead15d9338)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  0e196c96405de4ffd9d0d69c2a0a68632b6d260f2e48aba129459d8f943f6f12
Taker: 075eed4ce6a4b4c363d6259233c1b7fe9c7248741617482a5bf5d24a7dd985b1
Deposit: N/A
BTC mining fees lost: 0,00014995 BTC
![image](https://github.com/bisq-network/support/assets/149179309/03044a9d-6011-44d4-9e85-9d34c1a04e04)

Trade fees lost, please state if BSQ or BTC: At Funds/Transaction I see only one transaction (see screenshot)

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.14
BTC address for reimbursement: bc1qcesd5vnnfwyqal8huq3asq5aa8888vwat54npt

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @Mischa2805 

On this trade you lost:

Miner fees: 0.00003495 BTC 
Trade fees: 0.00011500 BTC

**Total: 0.0001499 BTC**

@leo816 please can you reimburse in your next batch. Many thanks

**Comment by Mischa2805** [comment]
Hello @darawhelan ,
Thank you very much for your help. I assume @leo816  now need to start a batch job so my lost bitcoins will be credited back to my account. For your information - I don't see any receipt yet.

**Comment by darawhelan** [comment]
@Mischa2805 

No problems. 

Yes @leo816 will likely make a batch reimbursement at then end of this month.

A comment will be placed here when complete.

**Comment by leo816** [comment]
Payout made with #1515
