### ISSUE TITLE
Fee reimbursement for trade 86119477

### ISSUE THREAD

**Issue by ferrolive** [bisq-network/support#1491]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![reimbursement](https://github.com/bisq-network/support/assets/7377237/728e50ea-0dad-4250-b563-885f5eb442c4)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  1ff7b390d78d72672b89e50bdde86e442f9262a2cb7c48e03ee275b1069d2884
Taker: 0c72210dc83b5ba525ef7c555357d71a1ede5278b7efcf1c54d1c05fa1f3cb6d
Deposit: c9a22f42c9948e04f904c9d01e3037708209599d7ec803ddce4317606bed810e
BTC mining fees lost: 0.00002450 BTC
Trade fees lost, 0.00002450 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.14
BTC address for reimbursement: bc1qnewj35gv59t4glajrx4uxznljapj23295stnpk

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @ferrolive this is a live trade. You should open mediation for it if you are having issues. You can open mediation by selecting the trade and pressing 'Ctrl' and 'O'.
