### ISSUE TITLE
Fee reimbursement for trade 5ojeti

### ISSUE THREAD

**Issue by jeffsurcess** [bisq-network/support#1493]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://github.com/bisq-network/support/assets/4688654/ba1d2b56-7277-4152-8694-c0ee29a2d7d2)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  e74ad157a7bcd127f68deeb631dba46e32d5322d637b4453591418dd19c8a9ea
Taker: ...........
Deposit: ..........
BTC mining fees lost: 0.0000175 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.14
BTC address for reimbursement: 36vhysVf6w9BpH6zDNhsmYQPE2Jvz5boPc

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

It appears that only the output in address bc1qgjuk0jdgwn3zxy77dmf63yardyqkx8gum3ye4p is what I retained in the transaction.  I lost:

1. the fee of 0.0000175 BTC
2. the output in bc1q5pwauq240t4s946nlfgv42kg48tvgquyrza33m of 0.00005000 BTC
3. the output in bc1qva7czqtu2fcd5xrt2gdh7p0aa7crl8qemuf4su of 0.02300000 BTC

Total loss (for reimbursal): 0.0230675 BTC

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @jeffsurcess 

Thank you for posting.

As the takers attempt to take the trade failed the trade should be available for another user to take.

Is the offer still in your 'Open Offers'?

**Comment by jeffsurcess** [comment]
Yes and I have just re-enabled it.

I can see the 0.0230 BTC in my Reserved Funds, I suppose that remains in reserve for the next successful Taker?

![image](https://github.com/bisq-network/support/assets/4688654/4088d5d4-2156-4de7-a7fc-c440507de735)

So would my loss be limited to the 6750 sats then?
![image](https://github.com/bisq-network/support/assets/4688654/6dea60f9-b0b5-4cfc-be83-9ff23634647f)

**Comment by darawhelan** [comment]
> I can see the 0.0230 BTC in my Reserved Funds, I suppose that remains in reserve for the next successful Taker?

Yes

> So would my loss be limited to the 6750 sats then?

No, that is not a loss. It is just the cost of making the original offer that is still available to be taken.
