### ISSUE TITLE
Fee reimbursement for trade UDKIOP

### ISSUE THREAD

**Issue by user9102** [bisq-network/support#1494]
SCREENSHOT HERE
*_
![trade](https://github.com/bisq-network/support/assets/91982756/3a145986-4d24-4112-888f-6ca1fb45ea35)

Maker:  552ed334616d940873523bd396115ed5e100e472bd61c7ea8241998ed5a822b2
Taker: e14a580f386bd780b1692e1e24441819a7aed8ce8a057bd6cbc2c20c91dd6eae
Deposit: N/A
BTC mining fees lost: 0.00002381 BTC
Trade fees lost, please state if BSQ or BTC: 0.69 BSQ

Bisq version: 1.9.14
BTC address for reimbursement: bc1qmlrk4lru8pdrp7chfaxa8tyz9vtzmtpv9q2m48

Other notes: N/A

**Comment by darawhelan** [comment]
Hi @user9102 Please can you edit the image to include the bit that says amount and if you were maker / taker and buyer / seller.

Many thanks
