### ISSUE TITLE
Fee reimbursement for trade KSZXCLWO

### ISSUE THREAD

**Issue by anonqoder** [bisq-network/support#1496]
<img width="881" alt="bisq-ksx" src="https://github.com/bisq-network/support/assets/76815541/81aeef9f-2ed5-4d90-b041-bccb8187fc91">

Maker:  f4a3a5b5d5738ce4276ef19e29752f2ae1b4a941377fe6e207033179cf0bca90
Taker: 2eb2c06a533c17ce40934deac70b9143e5aabbd5b847a8c281ea2f861e140487
Deposit: N/A
BTC mining fees lost: 0.00015375

Bisq version: 1.9.14
BTC address for reimbursement: bc1qpy2k93zykpeug70dakx740q4fs67t4axr772ud

**Comment by darawhelan** [comment]
Hi @anonqoder Please can you edit the image to include the bit that says amount and if you were maker / taker and buyer / seller.

Many thanks

**Comment by anonqoder** [comment]
Done

**Comment by darawhelan** [comment]
Thanks,

On this trade you lost:

Miner fee: 0.00003120 BTC
Trade fee: ‎0.00010500 BTC

**Total: 0.00013620 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
Payout made with #1515
