### ISSUE TITLE
Fee reimbursement for trade 2IEHV

### ISSUE THREAD

**Issue by anonqoder** [bisq-network/support#1498]
<img width="866" alt="bisq-2I" src="https://github.com/bisq-network/support/assets/76815541/f63cc85d-7300-43c6-baf2-24ab03b040f1">

Maker:  6f74d0bab6eb17f784544da2fcf9ac851f7d68ca6817bad089565f06264791c7
Taker: 45dea74fd6a6e925a9d18beb3c40d19580517448d2c0f84ce04397b9463d15c6
Deposit: 18cd59c8b5177fa743266307449f54f983a90e002f2e87bdacfe0ffb7241e934
BTC mining fees lost: 0.00012250 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qpy2k93zykpeug70dakx740q4fs67t4axr772ud

**Comment by darawhelan** [comment]
Hi @anonqoder 

On this failed trade you lost:

Miner fee: 0.00001750 BTC 
Trade fee: 0.00010500 BTC

**Total: 0.0001225 BTC**

@leo816 please can you reimburse in your next batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1515
