### ISSUE TITLE
Fee reimbursement for trade HTCEAQ

### ISSUE THREAD

**Issue by nixonrichard1971** [bisq-network/support#1500]
Trade failed, some issue with the transaction.

<img width="885" alt="Screenshot 2023-11-04 at 16 08 30" src="https://github.com/bisq-network/support/assets/138620914/6c2cd75b-3c93-4d68-b912-6c5e763fedc5">

Maker:  873f1fdd877e3ff271d60f7fc573f36911cdb2996a5adb716f198fcee01b8d78
Taker: a214cf4ae808c2a72657a345a604d808f6701f2b47a6981e39ed65ade57cb64d
Deposit: 299c2ad3198c3067a65adfa0cec818c8480c9d8e46c04d001a21baac9a28c856
BTC mining fees lost: 0.00003495 BTC
Trade fees lost: 0.00057500 BTC

Bisq version: 1.9.12
BTC address for reimbursement: bc1q6pgneyuq63ryk4etqfw6y2uggk0ql3c5hm53lh

**Comment by darawhelan** [comment]
Hi @nixonrichard1971 

I confirm on this trade you lost:

BTC mining fees lost: 0.00003495 BTC
Trade fees lost: 0.00057500 BTC

**Total: 0.00060995 BTC**

@leo816 please can you add to your list for reimbursement. Many thanks

**Comment by leo816** [comment]
Payout made with #1515
