### ISSUE TITLE
Fee reimbursement for trade qyeuzw

### ISSUE THREAD

**Issue by TheTotalConnector** [bisq-network/support#1501]
![Unbenannt](https://github.com/bisq-network/support/assets/50043671/e8aba943-f026-472a-8989-dc6e366b234b)
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  
Taker: 
Deposit: ?
BTC mining fees lost: 0.00028350 BTC
Trade fees lost, please state if BSQ or BTC: ?

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._: v1.9.14

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by TheTotalConnector** [comment]
Please, reimburse asap. Thank you.

**Comment by darawhelan** [comment]
Hi @TheTotalConnector 

There is no taker transaction for this trade.

No funds left your bitcoin wallet.

You have not lost any miner or trade fees.

**Comment by TheTotalConnector** [comment]
Ok, thanks.
