### ISSUE TITLE
Fee reimbursement for trade CQFFCVWN

### ISSUE THREAD

**Issue by jmj010** [bisq-network/support#1502]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://github.com/bisq-network/support/assets/10714783/aac16f0a-0c9f-4b57-a7b6-bd250c9165da)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.14
BTC address for reimbursement: bc1qjfm2nks2spjhlmtentkun9nlst87jgd8k2urc7

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmj010** [comment]
Please reimburse fees, not sure why it failed when I had enough funded

**Comment by darawhelan** [comment]
Hi @jmj010 please can you copy and paste the maker transaction ID into the comments below. Many thanks

**Comment by jmj010** [comment]
97afd18fc5596df2bae460e322275e84e061b2b49ed38e994f182bdc3f1a2b02

**Comment by darawhelan** [comment]
Hi @jmj010 thanks for posting.

This trade failed but your taker transaction also failed so no bitcoin left your wallet. No funds were lost.

I would recommend you do an SPV resync to make sure your wallet is in sync: https://bisq.wiki/Resyncing_SPV_file

**Comment by jmj010** [comment]
Ah I see, okay thanks for clarifying
