### ISSUE TITLE
Fee reimbursement for trade "id": "702073-d28b0a79-7dd1-4b7e-970e-1bdce0cff0bf-1914  Error: Timeout reached. Protocol did not complete in 120 sec.

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/support#1505]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
Attention
The trade protocol encountered some problems.

There was an error during trade protocol execution.

Error: Timeout reached. Protocol did not complete in 120 sec.

It might be that this error is not critical, and the trade can be completed normally. If you are unsure, open a mediation ticket to get advice from Bisq mediators. 

If the error was critical and the trade cannot be completed, you might have lost your trade fee. Request a reimbursement for lost trade fees here: [1]
[https://github.com/bisq-network/support/issues]
SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @Scoop193 please can you complete the issue using the template with all the information required.

**Comment by Scoop193** [comment]
This  is what it shows on my end

**Comment by darawhelan** [comment]
Have a look at some of the previous compensation requests to see how the template should be completed:

https://github.com/bisq-network/support/issues?q=is%3Aissue+is%3Aclosed
