### ISSUE TITLE
Fee reimbursement for trade GmeIr5ne

### ISSUE THREAD

**Issue by jmj010** [bisq-network/support#1506]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

<img width="897" alt="image" src="https://github.com/bisq-network/support/assets/10714783/21255510-8356-4e0f-93ee-10f91a0bdd36">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.14
BTC address for reimbursement: bc1qjfm2nks2spjhlmtentkun9nlst87jgd8k2urc7

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jmj010** [comment]
Hi, I have another failed transaction with Maker ID: 2b3dfd5b673d28285995630e5ba5ea6ed1974be8bb3225d6347dd8b0a33237ce

Taker Fee: dc1b44e72bf54f51f8ac21454a8682f18184ad84e85b34b980b3c7f4945de7e4

Please reimburse my fees. Thank you

**Comment by darawhelan** [comment]
Hi @jmj010 

On this trade you lost:

Miner fees:  0.00012250 BTC
Trade fees: 0.00005000 BTC

**total:  0.00017250 BTC**

@leo816 please can you add to you list for reimbursement. Many thanks

**Comment by leo816** [comment]
Payout made with #1515
