### ISSUE TITLE
Fee reimbursement for trade htdmbkgf

### ISSUE THREAD

**Issue by woolst** [bisq-network/support#1507]
![image](https://github.com/bisq-network/support/assets/76520635/6121b447-6467-4cda-a294-45f02eb16707)

Maker: 1b4fecf11a60e69a81cca6c22baff21045877c48df578721f45d5a432944e424
Taker: a41dc17b89e265e504bce7b6ea5cb7b8b1246eaa2240e906364de1022197bf4e
Deposit: N/A
BTC mining fees lost: 0.00024063 BTC
Trade fees lost, please state if BSQ or BTC: 15.57 BSQ

Bisq version: v.1.9.14
BTC address for reimbursement: bc1qg9f670k92pnxnaujhm0x7h6j7e462vuc2rdx4l

**Comment by darawhelan** [comment]
@catoptro-mancy 

I can confirm you lost in this trade:

BTC mining fees lost: 0.00025620 BTC
Trade fees lost, please state if BSQ or BTC: 15.57 BSQ

@leo816 please can you add to you list for reimbursement.

**Comment by leo816** [comment]
Payout made with #1515
