### ISSUE TITLE
Fee reimbursement for trade ZbmpX

### ISSUE THREAD

**Issue by Ven32123** [bisq-network/support#1508]
![Screenshot (115)](https://github.com/bisq-network/support/assets/151437769/ce6180fe-ea4c-485f-9015-5ac39aa7b0c4)

Maker:  7763bee2eccd180caa7f34bf212218050843802b0ea7d3c3a3a37c9b0507ad04
Taker: 90e4aeda251df50ddab790359695f640ec10b9c55bf1fb494c3267808757e759
Deposit: n/a
BTC mining fees lost: 0.00006650 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1q9demzxg9tkamasqynmvfn3m44sv0kudthd8xp8

**Comment by darawhelan** [comment]
Hi @Ven32123 

This trade failed but you should still have it in your open offers for someone else to take. Can you see the trade in Portfolio > Open Offers?

**Comment by Ven32123** [comment]
![Screenshot (118)](https://github.com/bisq-network/support/assets/151437769/6d6e4388-6ca7-4a67-abb4-dda0aff3e9e2)
![Screenshot 2023-11-19 210742](https://github.com/bisq-network/support/assets/151437769/0962bf28-4b54-41f6-8c99-3e389d2f18fe)

Hi @darawhelan I have two other trades around this price point that have been executed or in the proccess of being executed.  Both of which I do not believe used the deposit trade ID ZbmpX.  Please correct me if I am wrong, but I don't see any other open trade offers that could be from ZbmpX.

**Comment by Ven32123** [comment]
Hi @darawhelan Did you have a chance to look at the screen shots above? Sorry I can't find the fail trade unless it is one of the trades above and I just don't know how to find the failed transaction.

**Comment by darawhelan** [comment]
Hi @Ven32123 

Thanks for confirming the trade was no longer in your open trades.

Because of this on this trade you lost:

Trade fee: 0.00005000 BTC
Miner fee: 0.00006650 BTC

**Total:  0.00011650 BTC**

@leo816 please can you reimburse in your next batch. Thank you

**Comment by leo816** [comment]
Payout made with #1531
