### ISSUE TITLE
Fee reimbursement for trade GmeIr5ne

### ISSUE THREAD

**Issue by Ven32123** [bisq-network/support#1509]
![Screenshot (116)](https://github.com/bisq-network/support/assets/151437769/26a1772f-f3c6-43c3-99aa-056153e424a9)

Maker:  2b3dfd5b673d28285995630e5ba5ea6ed1974be8bb3225d6347dd8b0a33237ce
Taker: dc1b44e72bf54f51f8ac21454a8682f18184ad84e85b34b980b3c7f4945de7e4
Deposit: n/a
BTC mining fees lost: 0.00010516 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1q9demzxg9tkamasqynmvfn3m44sv0kudthd8xp8

**Comment by darawhelan** [comment]
Hi @Ven32123 

On this trade you lost:

Mining fee: 0.00010516 BTC
Trade fee: 6.49 BSQ

@leo816 please can you reimburse in your next batch.

**Comment by leo816** [comment]
Payout made with #1515
