### ISSUE TITLE
Fee reimbursement for offer NAdjQkUo

### ISSUE THREAD

**Issue by iljah** [bisq-network/support#151]
Would be nice to get reimbursed for maker fee (0.00005 btc I'm guessing) of offer that didn't seem to make it to bisq after all, as suggested in https://github.com/bisq-network/bisq/issues/1804

offer id: NAdjQkUo-37b11094-4544-4f8e-a6f0-1dceda7054fb-080
maker fee id: 87a42ca82fe412ca15952175af002ed98ebd12ba46853043dad1e056d2fe3846

Since I'll probably start with new data dir as suggested in https://github.com/bisq-network/support/issues/150 I'm guessing I won't get the reimbursement if it's sent to any address visible in above tx so please use e.g. this: 16f3ufhDMRK6CPmZcYjnYsZDn2iizuUww7

**Comment by KanoczTomas** [comment]
@iljah please update your comment with a screenshot as in #150. Hopefully you did not nuke your dir already. Thanks!

**Comment by iljah** [comment]
I saved the info so it wouldn't be difficult to recreate but I did also take a screenshot.

**Comment by iljah** [comment]
I just get "Something went really wrong, and we can't process that file" when trying to upload png...

**Comment by iljah** [comment]
![bisq_min](https://user-images.githubusercontent.com/2098356/47575851-ad6a4e80-d94b-11e8-8244-6e1b2d2a915c.png)

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/147#issuecomment-443627102.
