### ISSUE TITLE
Fee reimbursement for trade HAXBKYKK

### ISSUE THREAD

**Issue by TommyGun007** [bisq-network/support#1510]
>_The HAXBKYKK part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Screen BISQ](https://github.com/bisq-network/support/assets/151150716/00301cfa-a1f9-4130-ab35-e3b7c7aea2f2)

Maker: 1d6e1eada9474f791b73c1c5b88c06c060d66bd51e98a8c4529fa2023279bab8
Taker: N/A
Deposit: N/A
BTC mining fees lost: .......... 0.00156465 BTC
Trade fees lost, please state if BSQ or BTC: ..........  8 BSQ

Bisq version: v1.9.14
BTC address for reimbursement: bc1qrtjrgvnkm4xffasuxg7333vukz73leq25v8pla

Other notes:

**Comment by darawhelan** [comment]
Hi @TommyGun007 

As there is no taker transaction ID and you are the taker you have not lost any funds on this trade as not transaction occurred.

**Comment by Zigmoot** [comment]
Hello, @darawhelan, I am in a similar situation.  Does that include the mining fee and the security deposit?  Thank you

**Comment by darawhelan** [comment]
> Hello, @darawhelan, I am in a similar situation. Does that include the mining fee and the security deposit? Thank you

Yes, if you are the taker and there is no taker transaction then no funds left your wallet.  You should do an SPV Sync to make sure your wallet is showing the correct balances https://bisq.wiki/Resyncing_SPV_file
