### ISSUE TITLE
Fee reimbursement for trade 4027510-4d75c52c-dff1-4bf3-9344-bdd3532be253-1914

### ISSUE THREAD

**Issue by Zigmoot** [bisq-network/support#1513]
SCREENSHOT HERE

![Screen Shot 2023-11-21 at 11 01 40 AM](https://github.com/bisq-network/support/assets/105036472/7f72f349-3adc-4244-bf8c-79da9f97a18b)

Maker:  c5a0cba4e3acd9f45eec27d5eae8e759dfa03acf6401c61ee03eb0812dcd21e1
Taker: 697c5117db36ea5642f6791a6119a022e6fb1b0732af7ebc6ea0a8dc4543c3a4
Deposit: 522c1dd19b897b6be56975aec9fb36fadeceedb093993f69fa79d84a519e5441
BTC mining fees lost: 0.00060945 BTC
Trade fees lost, please state if BSQ or BTC: 20,315 SAT

Bisq version: 1.9.14
BTC address for reimbursement: bc1qu9zjw4kynz7urcx69e2x4a6ug4t8qu9q3lrj2z

Thank you

**Comment by leo816** [comment]
Payout made with #1515
