### ISSUE TITLE
Fee reimbursement for trade xxiet

### ISSUE THREAD

**Issue by Zigmoot** [bisq-network/support#1514]
![Screen Shot 2023-11-21 at 11 09 05 AM](https://github.com/bisq-network/support/assets/105036472/8c1b3464-ed2a-4c8d-b55d-e40752edb905)

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  9d31c9a1fc3e4730837c426a4ba578a3aff21fcf8d37367521081e646a1ae468
Taker: N/A
Deposit: N/A
BTC mining fees lost: .......... 0.00045528 BTC
Trade fees lost, please state if BSQ or BTC: .......... NA

Bisq version:1.9.14
BTC address for reimbursement: bc1qu9zjw4kynz7urcx69e2x4a6ug4t8qu9q3lrj2z

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

An error occurred at task: CheckIfDaoStateIsInSync
Exception message: DAO state is not in sync with seed nodes

**Comment by leo816** [comment]
Hi @Zigmoot ,

Taker fee was not published, therefore you haven't lost any funds on this trade. If they appear to be stuck, please go ahead and do an SPV Resync (https://bisq.wiki/Resyncing_SPV_file)

Best
