### ISSUE TITLE
Reimbursement for l4obazn72l2meqdpxyfp647waz2iqdrzlvxpso6dqp2syho4b6tt3iid.onion:9999

### ISSUE THREAD

**Issue by Zigmoot** [bisq-network/support#1516]
SCREENSHOT HERE
![Screen Shot 2023-11-24 at 4 23 23 PM](https://github.com/bisq-network/support/assets/105036472/d8adb2ba-02ed-4a1f-9bb4-cb8bde274624)

Reimbursement for trade 35909979

I am BTC buyer as taker for BTC.
Trade amount and asset: 0.0217 BTC
Deposit amount: 0.0060 BTC

Maker:  15db4f6746cda91cdca83b02e84101b57aa505bbbbba7390a79c6e4b9d141a1e
Taker: edb5623c071644f124a78a6dea8d812d2caf5b6a6bb050a991a4bab9d8065700
Deposit: 248eb4459f6de781cc67631d57798ae044b9150dd07748d8d692b2feff3edd25
Delayed payout: 0d52a150702eeb0c59101e05aeda996fb58977ad3ad8460376fd6d565a131a7d
BuyerMultiSigPubKeyHex: 02befd01eb0f9721b8fa50e713b54e22602b4daff43682fc0ba1d28c7f308a96cf
SellerMultiSigPubKeyHex: 02ff8a3149c7c9956c00f4466116ed5f98c220012695f222aac8f714c8bac705a8

Reimbursement amount: 0.0217 BTC 
Reason for reimbursement: amount not received

Bisq version:

1.9.14

Other notes:

>_Ping @refund-agent2 @leo816

**Comment by refund-agent2** [comment]
Delayed payout 0d52a150702eeb0c59101e05aeda996fb58977ad3ad8460376fd6d565a131a7d is not found at the mempool. It looks like the deposit tx has not been spent yet.
If you already went through mediation, try opening arbitration by rejecting mediation suggestion or Ctrl+O. Go to Matrix if you can't open arbitration or need more help.

https://bisq.wiki/Dispute_resolution

**Comment by Zigmoot** [comment]
It is not an open trade, its completed so I am not sure how to use mediation or arbitration.  Please help

**Comment by darawhelan** [comment]
> It is not an open trade, its completed so I am not sure how to use mediation or arbitration. Please help

Do you mean the trade is in your trade history? The trade has not paid out yet so it should be in your open trades.

I would recommend:

1. Share your trade ID here
2. Press the 'Detail Data' button to find out who you mediator is and share it here https://bisq.wiki/Finding_your_mediator
3. If you are able to send the trade to mediation do so, select the trade and press 'Ctrl' and 'O'

**Comment by Zigmoot** [comment]
yeah it is in my trade history.  I just tried rebroadcasting the delayed payout tx but noticed that it was time locked.  I think low fees on the sellers part was the problem. My mediator was ping'd in the original post.  I have since got some help on matrix so I believe it is just a waiting game until that block then either rebroadcast with bisq or mempool.  Thank you for reaching out

**Comment by darawhelan** [comment]
Sounds like an address reuse bug:

https://github.com/bisq-network/bisq/issues/5725

I would recommend contacting Leo on Matrix asap: @leo816:matrix.org  and letting him know the trade ID. It is likely your trade peer will open mediation at some point so you want to make sure the trade can be completed via a manual payout rather than ending up in arbitration.

> I believe it is just a waiting game until that block then either rebroadcast with bisq or mempool. 

That does not sound correct. The deposit is already confirmed. I would recommend doing the above.

**Comment by Zigmoot** [comment]
thank you for your advice.  Doing this now.  I appreciate your patience.  I just read the thread at https://github.com/bisq-network/bisq/issues/5725 and I had the exact same experience that other users describe here.  I paid the seller

**Comment by Zigmoot** [comment]
this ticket can be closed.  It has been resolved
