### ISSUE TITLE
Fee reimbursement for trade Q0jQLNdF-c8658fcf-2c78-48a3-bb7b-b6d4944d699f-1914 

### ISSUE THREAD

**Issue by D4rKOw3N** [bisq-network/support#1517]
>_The Q0jQLNdF part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

![image](https://github.com/bisq-network/support/assets/152169046/bd166018-fee6-4885-b8a7-544cb26fe926)

(d86ce6a6b650fff6e6ac7db9f2a2e1df2be9cdf7c1219f60b12f42b2163d4392) - my fee

![image](https://github.com/bisq-network/support/assets/152169046/b91f088d-0a77-476d-8edf-5bd94b398cbd)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: d86ce6a6b650fff6e6ac7db9f2a2e1df2be9cdf7c1219f60b12f42b2163d4392
Taker: 267a6b0fc5abd80bc708648bdeb5503960c22efaf71f89b9c70208102c2837f6
Deposit: e2e351605ee5a9421a9d041eee029f5ccc840d0c602d2965d83383c6de39373d
BTC mining fees lost: 0.00024745 BTC
Trade fees lost, please state if BSQ or BTC: 0.0015 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement: bc1q984xjt89scgmlvvdajsm7g4ph093sf3mnl8nky 

>_Provide the Bisq client version to help developers identify the causing issue. - v1.9.14

**Comment by darawhelan** [comment]
Hi @D4rKOw3N 

On this trade you lost:

BTC mining fees lost: 0.00024745 BTC

You have not lost the deposit, it is still in your Bisq wallet in address: bc1qlyvhjck254w4dwa0gfjdfyglcx9pq0c5vu7zhf

You should see this in Funds > Send Funds

@leo816 please can you add to your list for reimbursements

**Comment by D4rKOw3N** [comment]
Hi @darawhelan,

That's correct. Thanks for advice and resolving this quick.

Cheers

**Comment by leo816** [comment]
Payout made with #1531
