### ISSUE TITLE
Fee reimbursement for trades 302534 & 20373012

### ISSUE THREAD

**Issue by Bisq20231127** [bisq-network/support#1518]
![Screenshot from 2023-11-27 17-39-31](https://github.com/bisq-network/support/assets/152208356/5c84c058-5756-4ad0-bc1e-48383bb80383)
![Screenshot from 2023-11-26 12-04-26](https://github.com/bisq-network/support/assets/152208356/d27e3f61-6267-41af-903a-f625c2788c9f)

Trade 20373012

Maker:  iaa23eh6epy252kqskvoxjfpuayezvae3mizt5ech5d6kfpicz2x32qd.onion:9999
Taker: rco3rgfns6k6cim2hmgscpc3baq7eyzsclm7ulq4psj3gsinp56qhiid.onion:9999
Deposit: 0.012 BTC
BTC mining fees lost: 11,903 sats, Trading fees 1.02 BSQ
Bisq version: 1.9.14
BTC address for reimbursement: bc1q830wda95pspjmx2598ht940jug0wla53xzu627

Trade 302534

Maker:  iaa23eh6epy252kqskvoxjfpuayezvae3mizt5ech5d6kfpicz2x32qd.onion:9999
Taker: rco3rgfns6k6cim2hmgscpc3baq7eyzsclm7ulq4psj3gsinp56qhiid.onion:9999
Deposit: 0.012 BTC
BTC mining fees lost 17,538 sats: , Trading fees 1.02 BSQ
Bisq version: 1.9.14
BTC address for reimbursement: bc1q830wda95pspjmx2598ht940jug0wla53xzu627

Please see screenshots hopefully attached alongside this. Please let me know if any other details required?

**Comment by darawhelan** [comment]
Hi @Bisq20231127 

As you are the maker and neither of these trades have a deposit transaction ID they should both still be in your Portfolio > Open Offers.

**Comment by Bisq20231127** [comment]
Hi there cheers for the swift reply. I'm not sure I understand - both trades have definitely failed and have no way of showing in Open offers. They show in open or failed trades according to where I put them but nothing else is possible with them. The attached refers in terms of the error message.
![Screenshot from 2023-11-27 21-55-12](https://github.com/bisq-network/support/assets/152208356/9358c98e-0376-48c3-b293-3df0f51e19bc)

**Comment by darawhelan** [comment]
Ok thanks, I will take a look into it.

Can you post the maker transaction IDs for both offers? You have posted the onion addresses.

**Comment by Bisq20231127** [comment]
Apologies - I think these are the ones?

8bfb6e621205cce366b0a91620d7f769cfe9827625c058def848b91ed1431de3

930a3e9bbdb2098577873b56aabe5e63d5ae9f27d863622808d9873d34fe3d8b

**Comment by darawhelan** [comment]
Thanks

Mining 

Trade ID: 20373012 you lost :

Mining fees: 0.00017640 BTC
Trade fees: 1.02 BSQ

Trade ID: 302534 you lost:

Mining fees: 0.00012005 BTC 
Trade fees: 1.02 BSQ

@leo816 Please can you reimburse these two trades in your next batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1531
