### ISSUE TITLE
Fee reimbursement for trade XFDRMK

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1519]
![image](https://github.com/bisq-network/support/assets/63785272/a36d241b-e71e-447d-897f-7f0b0f19cc96)

Maker:  842339eaf39d46c0ee2933554ef525e8f9e8169e5479f5a83a8dba522fd613f8
Taker: 99aacadc11406841da5baf64c73da48e98cfc24e404d17cae82b1c82803b6393
Deposit: 48ff860b73a31d89ee74f36e71e5812d6c8b9ab50113672cd02cd25773b213fc

BTC mining fees lost: 0.00007105 BTC
Trade fees lost, please state if BSQ or BTC: 33.85 BSQ

Bisq version: 1.9.14
BTC address for reimbursement: bc1qczzy698yp8kxktesvzej36r65rahna6xksvd73

Other notes: None

**Comment by darawhelan** [comment]
Hi @Akira45-0 

I confirm on this trade you lost :

Mining fees: 0.00007105 BTC
Trade fees: 33.85 BSQ

@leo816 please reimburse in your next batch many thanks

**Comment by leo816** [comment]
Payout made with #1531
