### ISSUE TITLE
Fee reimbursement for trade sxwuw

### ISSUE THREAD

**Issue by DrazicXX** [bisq-network/support#1520]
![image](https://github.com/bisq-network/support/assets/152852314/a3654bcd-2ba8-4c27-ad35-b8cf91fd6bc3)

Maker:  1b808a2ccd64bca0f3999dfff15c60ff1f07bc0ddef8cba315d27ba8291a4519
Taker: c5eaf714a03fae6585c7585df4bd99e65c6800be4bc5ba0d3231bf620677aa4b
Deposit: N/A
BTC mining fees lost: 0.00070680 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1q0tg038lumjpz8et9du49gf0l2j8d9z73z6ehe0

Other notes: none

**Comment by DrazicXX** [comment]
Could you please have a look to my Open issue ?
This is what it shows in Open Trades . I already moved to Failed Trades
![image](https://github.com/bisq-network/support/assets/152852314/293e83c0-1365-4bfb-9c79-7062f55d7845)

**Comment by DrazicXX** [comment]
My Open Offer. It doesnt appear the trade id : sxwuw
![image](https://github.com/bisq-network/support/assets/152852314/571f921c-132f-47c4-9166-cacdfcc0c7b2)

**Comment by darawhelan** [comment]
Hi @DrazicXX 

On this trade you have lost:

Miner fee: 0.00070680
Trade fee: 0.00007275

**total: 0.00077955 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
Payout made with #1531
