### ISSUE TITLE
Fee reimbursement for trade 89943

### ISSUE THREAD

**Issue by rofaral** [bisq-network/support#1521]
<img width="676" alt="image" src="https://github.com/bisq-network/support/assets/153119633/bb96e3aa-e444-4604-97d9-4d13c4ab8b8d">

Maker: 76e06ecdd56ab45c9b7ab3473cc0f884844712f1be5df773ceb7e6d3059a0381
Taker: 7c3a08a73c591c0fa0b3274a6553437bcb63b0e5f4b90e78739c78b83dcd176d
Deposit: 56a9c4cc798c19f906bbdfb9c5d2416598339f8cc7d1b96aef3fb5741448027b

BTC mining fees lost: 0.00126519 BTC
Trade fees lost: BSQ, but coudn't find how much???

Bisq version: 1.9.14
BTC address for reimbursement: bc1qmfasunvesappyxe84zrldzaqdhw39xdfcwvxfj

Other notes: None

**Comment by darawhelan** [comment]
Hi @rofaral 

On this trade you lost:

BTC mining fees lost: 0.00042173 
Trade fees: 2.1 BSQ

@leo816 please can you reimburse in your next batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1531

**Comment by rofaral** [comment]
Folks, the issue was closed but I did not received the reimbursement on my bisq account. When and how I will be reinbursed?

**Comment by darawhelan** [comment]
You should be reimbursed to the address you provided: bc1qmfasunvesappyxe84zrldzaqdhw39xdfcwvxfj

@leo816 has this trade been reimbursed?

**Comment by rofaral** [comment]
Dear Whelan,

The address is correct, but I have just check it and still there isn't any
funds.

I appreciate your help.

Regards.

BISQ buyer

Em sáb., 30 de dez. de 2023 às 09:43, Dara Whelan ***@***.***>
escreveu:

**Comment by rofaral** [comment]
My BSQ adress is the following:

Bbc1q8ap3usser9kgv0lwvde0t09d558vss9dxhpy93

Thank you

Em sáb., 30 de dez. de 2023 às 11:54, Rodrigo Almeida <
***@***.***> escreveu:

**Comment by darawhelan** [comment]
Thanks, I have sent @leo816 a DM about the issue

**Comment by darawhelan** [comment]
@leo816 informed me in Matrix that the payout will be made in the next payout batch.

Apologies for the inconvenience.

**Comment by rofaral** [comment]
No problem, thank you for the update.

Em qui., 4 de jan. de 2024 15:24, Dara Whelan ***@***.***>
escreveu:

**Comment by darawhelan** [comment]
@leo816 just a reminder that this payout needs to be processed and the ticket re-opened

**Comment by rofaral** [comment]
Folks, 

I didn't receive the reimbursement yet. Could you check this out please?

**Comment by rofaral** [comment]
@leo816 e @darawhelan , could you help me?

**Comment by darawhelan** [comment]
Hi @rofaral thanks for the chase up. I have sent @leo816 a reminder

**Comment by leo816** [comment]
payout made with #1595
