### ISSUE TITLE
Reimbursement for trade NvyT4B-f7bed0c3-1171-4e7d-9029-0226e7f5ee82-196

### ISSUE THREAD

**Issue by jodyrb** [bisq-network/support#1522]
Shortly after my offer was taken on November 17, I received a Bisq error message stating that my SPV file needed to be re-synced. 
So, I deleted the SPV file, but Bisq did not start back up normally. It was taking a very long time to synchronize. I was checking it every day and had no way to communicate with the trade partner. I was even writing down the bitcoin block number every day as reference to make sure it was making progress. Here are a few examples: 27 Nov 812,728, 28 Nov 813,516, 29 Nov 814,244, 30 Nov 815135, etc. 
I had no way to tell what the status of the trade was, where it was in Mediation or Arbitration. The first day I was able to see the app was 4 Dec (I was locked out for ~17 days). As of today (6 Dec), the trade still does not show on my Arbitration List. In other words, it is showing as still in Mediation. I really did not know that I had trade-specific communication options outside of the bisq app, so I was anxiously waiting for the resync to finish. I want to be able to rely on the app and continue using it, but I cannot afford to lose 0.015 BTC due to what seems to be a glitch. That said, I am willing to do whatever I need to do to minimize the chance of this happening again. My mediation support agent is pazza83.  The trade ID is NvyT4B and I am the maker. Thank you for your consideration.

**Comment by pazza83** [comment]
Hi @jodyrb 

Thanks for documenting this issue.

For this trade you were the buyer / maker .

- Trade was taken on 17th November 2023
- The BTC seller / taker opened mediation on 18th November 2023 as they did not receive the payment from yourself.
- No reply was received by yourself by 21st November so mediation proposal was issued

---

Summary:
Trade ID: NvyT4B
Currency: DOGE
Reason for dispute: Trader not responding
Payout suggestion: BTC seller gets trade amount plus compensation 25%
Trade amount: 0.10 BTC
Payout amount for BTC buyer: 0.0050 BTC (BTC buyer receives a penalty on his deposit)
Payout amount for BTC seller: 0.1250 BTC (BTC seller receives trade amount + his deposit + compensation from buyer)

Summary notes:
BTC buyer did not send payment or respond to mediation
BTC seller confirmed no payment received

---

- BTC seller took trade to arbitration on 26th November as you had not responded to mediation
- Arbitrator made payout to the BTC seller on 30th November, no payment was made to yourself as you were unresponsive in mediation and arbitration 
- You contacted me on 4th December to let me know you had been doing an SPV resync and what would the next steps be. I informed you that the trade has already been sent to arbitration and that your deposit was lost. 

17 days is a long time to be doing an SPV resync. I think once SPV resyncs start to take more than a few hours you should look at moving to a new data directory: https://bisq.wiki/Switching_to_a_new_data_directory

Also if you do experience issues in the future it is best to immediately contact Bisq support in https://bisq.wiki/Matrix_bisq.chat to make them aware as they can support you while you do not have access to Bisq. 

Whilst sympathetic to your loss of your security deposit for this trade I think it could have been avoided by your reaching out a lot earlier once you realized you were experiencing issues connecting to Bisq.

I do not think your situation warrants a reimbursement.

You can however still put the reimbursement to a vote from the DAO should your wish. To do this please feel free to put forth any additional points you feel make you eligible for a reimbursement, you would also need to submit a DAO reimbursement request. The process for doing so is documented here: https://bisq.wiki/Making_a_reimbursement_request#Submit_your_reimbursement_request_to_the_Bisq_DAO

**Comment by jodyrb** [comment]
Pazza,
From your perspective, it is easy to understand that there was a problem with the re-sync. But, from the user's perspective, there was no problem. Every day, I was watching the status bar 47.0%, 48.0%, 49.0%, etc. If the re-sync is supposed to be quick, then what is the purpose of the percentage status bar? Why would the software not "timeout" after a few minutes and give the user an error message with the instructions that you have given me after the fact? This is obviously an issue with the software, so it would make sense for the user to be reimbursed for loses. If people can make money at the users' expense by having software with glitches, then there is not much incentive to de-bug the software. It would actually make more sense for user to be reimbursed AND given a small reward for finding a bug in the software. But instead, I have to keep going down this path that consumes your time and my time...

**Comment by pazza83** [comment]
> Every day, I was watching the status bar 47.0%, 48.0%, 49.0%, etc. If the re-sync is supposed to be quick, then what is the purpose of the percentage status bar? 

I agree that 17 days is far too long for an SPV resync. Your suggestions are valid and would improve the process for users.

The first support messages users receive in mediations says the following:

> System message: Your trading peer has requested mediation.
> 
> Please enter a description of your problem in the text field below. Add as much information as possible to speed up dispute resolution time.
> 
> Here is a check list for information you should provide:
> 	● If you are the BTC buyer: Did you make the Fiat or Altcoin transfer? If so, did you click the payment started button in the application?
> 	● If you are the BTC seller: Did you receive the Fiat or Altcoin payment? If so, did you click the payment received button in the application?
> 	● Which version of Bisq are you using?
> 	● Which operating system are you using?
> 	● If you encountered an issue with failed transactions please consider switching to a new data directory.
> 	  Sometimes the data directory gets corrupted and leads to strange bugs. 
> 	  See: https://bisq.wiki/Switching_to_a_new_data_directory
> 
> Please make yourself familiar with the basic rules for the dispute process:
> 	● You need to respond to the mediator's requests within 2 days.
> 	● Mediators will generally reply to you within 24 hours.
> 	  If you have not had a reply after 48 hours please feel free to reach out to your mediator on Matrix.
> 	  Mediators usernames on Matrix are the same as their usernames within the Bisq app.
> 	  Your mediator is: https://matrix.to/#/@pazza83:matrix.org
> 	● The maximum period for a dispute is 14 days.
> 	● You need to cooperate with the mediator and provide the information they request to make your case.
> 	● You accepted the rules outlined in the dispute document in the user agreement when you first started the application.
> 
> You can read more about the dispute process at: https://bisq.wiki/Dispute_resolution#Level_2:_Mediation
> 
> Bisq version: 1.9.14

I understand that you never received this message but I do think as a decentralized exchange there is onus on the users themselves to reach out for support. I suppose the SPV process taking so long is unusual but I do think that most users would reach out for support in this time.  

You can put the issue to a DAO vote. I am just sharing my thoughts from the perspective of the contributor that mediated this trade.

I will discuss this in support to see what can be done to avoid users being affected by this issue again.

**Comment by pazza83** [comment]
Hi @jodyrb this reimbursement request was approved in DAO vote 54.  You will see the BSQ reimbursement in your Bisq instance. 

I will close this issue now.
