### ISSUE TITLE
Fee reimbursement for trade mflcfc

### ISSUE THREAD

**Issue by Ven32123** [bisq-network/support#1523]
![Screenshot 2023-12-09 000025](https://github.com/bisq-network/support/assets/151437769/6ae9efe1-ede1-492e-99fb-297befc8d345)

Maker:  3ba7acde08fd3560718e8cb8e17f1fd9da6968a99c095756be36ba6313a4a81a
Taker: 306c5ae9ce9f73a2b8397105af1b12af6fe0945bee2e15144193438757088c86
Deposit: N/A
BTC mining fees lost: 0.00006125 BTC
Trade fees lost, please state if BSQ or BTC:    How do you calculate BSQ amount?

Bisq version: v1.9.14
BTC address for reimbursement: bc1q732chnpjse7rajp0ccgffylf38s6v0pzrhj9w9

Other notes:
Failed trade

**Comment by darawhelan** [comment]
Hi @mflcfc 

As no deposit was created for this trade you should still have the trade available in your 'Open Offers'.

Can you see trade ID: mflcfc  in your Open Offers?

**Comment by Ven32123** [comment]
I do not have any "my open offers" currently.  There was only this trade which I moved from failed back to "Open trades"
![Screenshot (182)](https://github.com/bisq-network/support/assets/151437769/c53721c1-44aa-4f43-9725-b040cd21c9a9)

**Comment by Ven32123** [comment]
My open offers
![Screenshot (183)](https://github.com/bisq-network/support/assets/151437769/9cd84df6-759d-42da-9402-7740578d1921)

**Comment by darawhelan** [comment]
@Ven32123 

Thanks for posting.

Looks like this trade completely faile.d

You have losr:

BTC mining fees lost: 0.00006125 BTC
Trade fees lost: 2.54 BSQ 

FYI you can see the BSQ amount lost by looking up the maker transaction ID amount of BSQ burnt on a BSQ explorer. Eg in this example it is: https://bisq.markets/tx/3ba7acde08fd3560718e8cb8e17f1fd9da6968a99c095756be36ba6313a4a81a

@leo816 please can you reimburse @Ven32123 in your nxt reimbursement batch. Thank you

**Comment by leo816** [comment]
Payout made with #1531
