### ISSUE TITLE
Fee reimbursement for trade 4995287

### ISSUE THREAD

**Issue by hacs55** [bisq-network/support#1525]
![Screenshot from 2023-12-09 13-29-05](https://github.com/bisq-network/support/assets/151097288/5ea788f5-7c52-47b4-8649-6f12d7faf148)

THIS HORRIBLE HORRIBLE APP STOLE PLENTY OF BITCOIN FROM ME.  3 SEPARATE ATTEMPTS, 3 FAILURES, TOTAL OF 0.00413987 BTC STOLEN FROM ME.  PLEASE MAKE ME WHOLE.

Bisq version: Latest
BTC address for reimbursement: bc1qvmqg70mqs9ple72cmsaztlu8ha4rh8j9x8x6d3

See screenshot, and below offer id that I funded TWICE

offer id: 07713283-ca197e88-d159-4dd2-8011-27d3c39a2fdf-1914

**Comment by darawhelan** [comment]
Hi @hacs55 

As you were the taker and the taker transaction failed you have not lost any bitcoin on this trade.

An SPV resync https://bisq.wiki/Resyncing_SPV_file will help your Bisq wallet display the correct balance.
