### ISSUE TITLE
Fee reimbursement & security deposit for trade 33914-14c1d192-6b8a-4b34-9332-cc585bec09e1-1914

### ISSUE THREAD

**Issue by crazy973pepper438** [bisq-network/support#1526]
On this failed trade the 0.01BTC security deposit has not been returned.

Maker:  ceab01c0663cba7a6583923c1873539b5fe6be3f4be369538ad155d858d23a7e
Taker: 68156830cdb266be0c85338da2a8f3dd0f819896fa68c48a558113b581accd75)
Deposit: 4b4475fb7b7cc9a66e52e4e8fef1ce7bb0ee31efd0a84bed8b1a30b1849b8385 --> security deposit not returned

BTC mining fees lost: 0.00008820 BTC 
Security deposit lost: 0.01BTC 

Bisq version: 1.9.14
BTC address for reimbursement: bc1q75cc92e0kaa26q4ace33wdkdfcv2y4093ln622

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._
[33914-14c1d192-6b8a-4b34-9332-cc585bec09e1-1914.ods](https://github.com/bisq-network/support/files/13627030/33914-14c1d192-6b8a-4b34-9332-cc585bec09e1-1914.ods)
[33914-14c1d192-6b8a-4b34-9332-cc585bec09e1-1914.pdf](https://github.com/bisq-network/support/files/13627048/33914-14c1d192-6b8a-4b34-9332-cc585bec09e1-1914.pdf)

**Comment by darawhelan** [comment]
Hi @crazy973pepper438 

Please can you also post the screenshot of your trade information screen, redacting any personal information. It will help show who was the buyer / seller etc.

Thank you

**Comment by crazy973pepper438** [comment]
Hi,

Please find trade information attached:

Thanks

[trade information.pdf](https://github.com/bisq-network/support/files/13708174/trade.information.pdf)

**Comment by darawhelan** [comment]
![33914](https://github.com/bisq-network/support/assets/121062323/66f90f53-b1d3-4a3f-a54d-62624277a5dc)

**Comment by darawhelan** [comment]
Hi @crazy973pepper438 

Trade ID 33914 is an active trade. Your deposit has entered the multisig.

It was taken on 3rd December.

What made you think this trade failed?

I would reach out to [Pazza83 or Leo816](https://bisq.wiki/Finding_your_mediator) on [Matrix](https://bisq.wiki/Matrix_bisq.chat)

You should do so soon as the trade can be sent to arbitration on 23rd December.

cc: @pazza83 / @leo816

**Comment by pazza83** [comment]
Hi @crazy973pepper438 

I have your ticket in my mediations.

Please can message me on Matirx ASAP.

My username there is @pazza83:matrix.org

**Comment by pazza83** [comment]
This trade has now been sent to arbitration. Here is a link to the delayed payout transaction:

https://mempool.space/tx/5e6d2218d00f4ac1e6ba2caa8c8fb418b51abf09872a1eaedb87f45221b5e38c

@crazy973pepper438 you should reach out on Bisq Matrix chat to contact the arbitrator ASAP. 

https://bisq.wiki/Matrix_bisq.chat

**Comment by crazy973pepper438** [comment]
Hi pazza83, I sent a DM on matrix

**Comment by pazza83** [comment]
ok, will continue the chat on Matrix with you.
