### ISSUE TITLE
Fee reimbursement for trade tuqskl

### ISSUE THREAD

**Issue by bisqfeereimbursement** [bisq-network/support#1527]
![image](https://github.com/bisq-network/support/assets/154454105/cd1b4769-8608-4743-afa1-dedbfa172312)

Maker: 0.00047950 BTC
Taker: 0.002097 BTC
Deposit: 0.00102285 BTC
BTC mining fees lost: 0.002097 BTC
Trade fees: 0.000699 BTC

Maker: 70316a2ce92e6cdf2641a8e9824844d7ed06fbb0911a3bc4d555863d26486382
Taker: 3c2b4767aed809d046a94742c678eb40eeefc16788b421ad3a5603fee679697b
Deposit: b8b5a5e455143e2944a21fe9bd840ca8fec16e7593ccbc8b5c93cf08309a8b7c

Bisq version: v1.9.14
BTC address for reimbursement: bc1qjsrtk3qv8074wtp6xy4zyaafvk0a0rmd9g7ugw

Other notes:

Please reimburse trade fees, but not sure about mining fees yet (i.e. are they lost too?), as I can't see them in "Funds > Transactions" – please double check! Bisq didn't update the "Portofolio" screen (i.e. ongoing trades, in order to initiate the payment process), so I went to "Settings > Network Info > 'Delete SPV file and resync' " (as suggested by Bisq; maybe this is somehow related to the issue.

Due to privacy I newly created this GitHub account just for this reimbursement

**Comment by pazza83** [comment]
@bisqfeereimbursement 

Bisq is giving you a false error.

The deposit transaction was successful.

It is fine to send payment and complete this trade normally.
