### ISSUE TITLE
Fee reimbursement for trade 99964

### ISSUE THREAD

**Issue by Chalice3785** [bisq-network/support#1528]
![Screenshot_2023-12-21_09-33-05](https://github.com/bisq-network/support/assets/154518310/1da14c96-f7ae-4fdb-b753-461c42d6a865)

![Untitled](https://github.com/bisq-network/support/assets/154518310/ab6c89c2-c2b8-4f93-a456-a2be634681cb)

Maker:  b9fe02cf40d0626be86b4e8769a0f5176d1593ed8ab85561fb48a193af8729e6
Taker: ...........
Deposit: ..........
BTC mining fees lost: 0.00012750 BTC
Trade fees lost, please state if BSQ or BTC: ..........

Bisq version: 1.9.14
BTC address for reimbursement: bc1qf5lqqdlz6ee76zk9dwmhhuex4jzsenppdp2ssu

**Comment by Chalice3785** [comment]
I cancelled it and am awaiting it to go back to my electrum wallet.

**Comment by darawhelan** [comment]
Hi @Chalice3785 

Although this trade failed as their was no deposit transaction it was kept in the offer book and later taken by another BTC seller.

You have not lost any funds on this trade
