### ISSUE TITLE
Fee reimbursement for trade "lecfxzsi"

### ISSUE THREAD

**Issue by lewys66** [bisq-network/support#1530]
Trade: lecfxzsi 

 Trade ID: lecfxzsi-35af8844-39e2-4b2a-9a95-ccdfaa264268-1914

SCREENSHOT HERE - TWO SCREENSHOTS BELOW 

![Screenshot 2023-12-27 at 12 07 47](https://github.com/bisq-network/support/assets/154983296/aa564f7f-d6bf-48d8-b0da-269b8af6c84b)

![Screenshot 2023-12-27 at 12 10 35](https://github.com/bisq-network/support/assets/154983296/7c2664d5-8b15-49bd-ace1-a239e9f16c33)

![Screenshot 2023-12-27 at 12 18 50](https://github.com/bisq-network/support/assets/154983296/a26880ee-efc4-421a-a96f-fee2a94ee678)

Maker:  0.000091 BTC
Taker: 0.00068502 BTC 
Deposit: 0.015862 BTC
BTC mining fees lost:  0.00068502 BTC
Trade fees lost: 0.015862 BTC

Bisq version:
BTC address for reimbursement:
bc1qdvkxq8ygz4slkkxhfag7vzkyd3kqllg6vzrke7

Version: 1.9.14

Other notes:

Issue: [#197](https://github.com/bisq-network/support/issues/197)

**Comment by leo816** [comment]
please copy the format of other reimbursement requests (past the deposit tx id as well as the maker and taker's)

**Comment by lewys66** [comment]
Hi, thank you for messaging. Copy it to where?

**Comment by lewys66** [comment]
I think I have done that correctly. Hope you have a good day :)

**Comment by darawhelan** [comment]
Hi @lewys66 

Please can you post the following:

- maker transaction ID
- taker transaction ID
- deposit transaction ID

You can paste them below in the comments to this issue

**Comment by lewys66** [comment]
Marker Transaction ID: d1e64767e9b0d250f45b6357093419b2e0d6545892435d90c8eb6a300bc51ea5
Taker Transaction ID: 96cb9f675c2bb2d007d7d6527b806a219a58a608b6ab8d28f168af15a67eb715
Deposit Transaction ID: 401de635d05a39efacae7cb18f9af1dffd7a01beb8d3345fcb1813e6f58c7c71

**Comment by lewys66** [comment]
Hi, any progress with this?

**Comment by darawhelan** [comment]
Hi @lewys66 

Thanks for providing the info.

The trade is not failed. 

The taker took the offer with a very low miner fee rate for the current fee levels.

The taker and deposit confirmation are both not confirmed.

Looks like it might be a while before they are.

**Comment by darawhelan** [comment]
You should open mediation for this trade.

Select the trade and press 'Ctrl' and 'O' 

A mediator will be able to support you with  completing this trade

**Comment by lewys66** [comment]
Thank you
