### ISSUE TITLE
Reimbursement for _trader's onion address_

### ISSUE THREAD

**Issue by lewys66** [bisq-network/support#1532]
SCREENSHOT HERE

![Uploading Screenshot 2023-12-27 at 12.10.35.png…]()

Reimbursement for trade ID: lecfxzsi-35af8844-39e2-4b2a-9a95-ccdfaa264268-1914

I am BTC [buyer] as [maker/taker] for [ASSET].
Trade amount and asset: 0.07 BTC for £2433
Deposit amount: 0.015862  BTC

Maker: 0.000091 BTC
Taker: 0.00068502 BTC
Deposit: 0.015862 BTC

Reimbursement amount: 0.015862 BTC BTC /
Reason for reimbursement: Transaction Error

BTC address ownership proof:

![Screenshot 2023-12-27 at 12 07 47](https://github.com/bisq-network/support/assets/154983296/ab1acb4b-8a38-4398-8eca-2d274d873dad)
![Screenshot 2023-12-27 at 12 10 35](https://github.com/bisq-network/support/assets/154983296/905a6ca6-8fb7-48fc-9c68-8c9f50d41b52)

Trade: lecfxzsi
Trade ID: lecfxzsi-35af8844-39e2-4b2a-9a95-ccdfaa264268-1914
Maker: 0.000091 BTC
Taker: 0.00068502 BTC
Deposit: 0.015862 BTC
BTC mining fees lost: 0.00068502 BTC
Trade fees lost: 0.015862 BTC

BTC address for reimbursement:
bc1qdvkxq8ygz4slkkxhfag7vzkyd3kqllg6vzrke7

Bisq version:: 1.9.14

Other notes:

Issue: https://github.com/bisq-network/support/issues/197

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

>_Ping @refund-agent2 and your mediator_

**Comment by darawhelan** [comment]
Hi @lewys66 

Please can you post the following:

- maker transaction ID
- taker transaction ID
- deposit transaction ID

**Comment by lewys66** [comment]
Marker Transaction ID: d1e64767e9b0d250f45b6357093419b2e0d6545892435d90c8eb6a300bc51ea5
Taker Transaction ID: 96cb9f675c2bb2d007d7d6527b806a219a58a608b6ab8d28f168af15a67eb715
Deposit Transaction ID: 401de635d05a39efacae7cb18f9af1dffd7a01beb8d3345fcb1813e6f58c7c71

**Comment by darawhelan** [comment]
Hi @lewys66 this is the same problem as the other trade.

The trade is not failed.

The taker took the offer with a very low miner fee rate for the current fee levels.

The taker and deposit confirmation are both not confirmed.

Looks like it might be a while before it is confirmed.

You should open mediation for this trade.

Select the trade and press 'Ctrl' and 'O'

A mediator will be able to support you with completing this trade

**Comment by lewys66** [comment]
Thank you
