### ISSUE TITLE
Reimbursement for lwilxvfeudufwtasc5yuuufj5443y7zkp3dt6h5dycpxwtcz7tl5urid.onion:9999

### ISSUE THREAD

**Issue by bisqusr** [bisq-network/support#1533]
![Screenshot 2023-12-30 142802](https://github.com/bisq-network/support/assets/155239577/2c69b9b9-cf2a-466b-aa93-bd361a9e44b9)

Reimbursement for trade 70151726-e85e788a-026e-44d7-bb58-6b82ecc4d941-1914

I am BTC buyer as taker for Revolut.
Trade amount and asset: 0.05 BTC for 1979 eur
Deposit amount: 0.07 BTC

Maker: 90a85ec028546f3e34a7fc3370aa54ac17762134b01ee3c27c5e851ef2798fd4
Taker: 72f1214415874fa7afe51adaa7ba14020ffc55e5a288da138753ed06a9f9114f
Deposit: 91e681f065cd12f64a3fab053a057d1722d2860049eeebd5bd6d08c1ba752269
Delayed payout: bb615e4f9738ff5f6b892090673a8dedd563a13966f296038891a05cbbeb7ea3
BuyerMultiSigPubKeyHex: 028d9ab4adef928e1406b068e8bcf6d311270d933d0a4886128e7f5672f403d96d
SellerMultiSigPubKeyHex: 021053160b0670163d6e0f0426e873a8e04386d5c240869e42a439b591d0fe19d2

Reimbursement amount: 0.07 BTC / 0.00002929 BSQ = 2389.89416183 BSQ
Reason for reimbursement: Trade failed fot technical reasons

BTC address ownership proof (use ctrl+G to sign/verify):
Message: "70151726-e85e788a-026e-44d7-bb58-6b82ecc4d941-1914 bisqusr"
Address: "bc1qwnystnym847n0r7ssgzuscmmwgq2z6r6h7xsu2"
Signature: "IAy69q+9WMND/mjGUeaa9y9FBG7XRLFQvzFQHxfA6eiFcT49JGBuISWTGhAIKy+nSFj5Rhb1bmj152dxCgrf+u0="

@refund-agent2 @leo816

**Comment by bisqusr** [comment]
BTC address ownership proof (use ctrl+G to sign/verify):
Message: "70151726-e85e788a-026e-44d7-bb58-6b82ecc4d941-1914 bisqusr"
Address: "bc1qwnystnym847n0r7ssgzuscmmwgq2z6r6h7xsu2"
Signature: "IAy69q+9WMND/mjGUeaa9y9FBG7XRLFQvzFQHxfA6eiFcT49JGBuISWTGhAIKy+nSFj5Rhb1bmj152dxCgrf+u0="

**Comment by darawhelan** [comment]
Hi @bisqusr 

The trade has not failed. The deposit is locked in the multisig.

Have you opened mediation for this trade?

To do so make sure the trade is in your open trades and press 'Ctrl' and 'O' to send the trade to mediation.

This trade should be able to be paid out through mediation.

**Comment by bisqusr** [comment]
problem was explained by buyer in mediation to @leo816 

he has been waiting days for answer and wrote me this.

> Hi, So we finally got a "response" from Support saying just this: "did you make the payment?" that's it. Nothing else!  Despite me responding within 5 mins or so & stating that there was no option to make payment or anything as the transaction crashed completely & asking if there was a way to continue or resprocess etc.  Very poor support in my opinion! Perhaps this is the support person's way of saying "forget it and just claim back lost funds"??  I think we've waited for "assistance" long enough.  Perhaps it's just time to set it as a "failed trade" and claim back from support, whatever we can individually, as we originally thought?  Are you okay with this?  If so please respond here & I will mark it as a failed trade my end also, you do the same & we can move on.  Sorry for this, I would have hoped support by mediators would have been better than this.

i share the frustration

**Comment by bisqusr** [comment]
@leo816 solved the problem. thanks.
