### ISSUE TITLE
Fee reimbursement for trade zYSsE

### ISSUE THREAD

**Issue by ClownReference** [bisq-network/support#1535]
![Screenshot 2024-01-01 193629](https://github.com/bisq-network/support/assets/155382752/a0405617-21ad-496f-b7a5-e5466867a2a0)

Maker: 67be3677c6032870974f8422083c66f90ec4834462e02c09f546b28253dae726
Taker: 663882e6ccdb26e97501150479ec74f2f162ddff3a422805c800d29507328419
Deposit: 8e906f90bddfb3d5d84b264a4166f33343ecc94ead94c43c4046c2b72628a19f
Delayed Payout: 46d3c1c9dfa7398e3abff594d76b2b96f2f6634296b74167806ad46db7b3af5b
BTC mining fees lost: 0.00034717
Trade fees lost: 0.00012650 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1q62yytrfkvjgmun6dyckhwprq78rstnt5mhtscl

**Comment by darawhelan** [comment]
Hi @ClownReference 

This is not a failed trade.

The trade deposit transaction has confirmed successfully. 

I would recommend moving the trade back to 'Open Trades' and opening mediation for the trade to get support from a mediator. 

To do this make sure the trade is in 'Open Trades' then select the trade and press 'Ctrl' and 'O'.
