### ISSUE TITLE
Fee reimbursement for trade 773022

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/support#1538]
>_The 773022 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 0.00027104 BTC
Taker:  0.00047532 BTC
Deposit: 0.004165 BTC
![2024-01-04](https://github.com/bisq-network/support/assets/77167690/2b8b51dd-b3e0-4c08-904b-152069509f21)

BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:
bc1qgygejmes3fp803qspqfqng6q070reaa26urwma
>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:
An error occurred at task: CreateTakerFeeTx
Exception message: Insufficient money,  missing 0.0008483 BTC
>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @Scoop193 please can you post using the following [reimbursement template](https://github.com/bisq-network/support/issues/new?assignees=&labels=&projects=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX)
