### ISSUE TITLE
Can't move failed trade to open trades

### ISSUE THREAD

**Issue by a3ronin** [bisq-network/support#1539]
I attempted to take an offer to sell BTC but the trade failed due to insufficient funds. There are adequate funds in my wallet and I attempted to move the trade to open trades but it won't move. Included is a screenshot of the trade.
![Screenshot at 2024-01-06 17-03-36](https://github.com/bisq-network/support/assets/8469073/25d19d0e-da3f-4896-9650-daf324175312)

**Comment by darawhelan** [comment]
Hi @a3ronin 

See the post here on the forum for instructions on how to remove a stuck trade:

https://bisq.community/t/how-to-get-rid-of-a-trade-that-is-stuck-in-open-trades/12218
