### ISSUE TITLE
Fee reimbursement for trade 41UKUC

### ISSUE THREAD

**Issue by vycoreb** [bisq-network/support#154]
hi,

i lost 2x 0.000238 (total 0.000476 BTC) in fees because i tried to take an offer twice and it failed. attaching screenshots and notes

[notes.txt](https://github.com/bisq-network/support/files/2544533/notes.txt)

![img1](https://user-images.githubusercontent.com/44715956/47946663-1125e600-df0f-11e8-9ce3-3e013b627d15.png)
![img2](https://user-images.githubusercontent.com/44715956/47946664-1125e600-df0f-11e8-86da-502c67680734.png)
![img3](https://user-images.githubusercontent.com/44715956/47946665-1125e600-df0f-11e8-8284-b2770f9d47a7.png)
![img4](https://user-images.githubusercontent.com/44715956/47946666-1125e600-df0f-11e8-8782-94cc3fbe03cc.png)
![img5](https://user-images.githubusercontent.com/44715956/47946667-1125e600-df0f-11e8-9242-044757f740f1.png)
![slack_manfred](https://user-images.githubusercontent.com/44715956/47946668-11be7c80-df0f-11e8-8d68-a7439c51bdf3.png)

.the other trade which i opened before the failed one with the same person was opened successfully, and i already paid him (not finished yet). i hope that one completes successsfully as usual.

41UKUC is the failed one.

i would appreciate it if you could refund the 0.000476 BTC to:
1HzDRF2bTreaoXBjdixDYgwbAKrUHovJ2M
to avoid errors: this address starts with 1H and ends with 2M

my last 17 trades went fine without serious issues. i hope my luck didnt just run out lol

**Comment by cbeams** [comment]
Acknowledged, thanks. Will be reimbursed with #147. In the future, please try to open a dispute with ctrl/cmd-o with the trade selected in your Bisq client.

**Comment by cbeams** [comment]
@KanoczTomas, I've assigned you. As part of transitioning to the primary @bisq-network/support-maintainers role owner, please put a watch on this repository (if you haven't already), and assign yourself to these issues if you like. Note that with just one person processing these issues, assignment isn't strictly necessary. Just do whatever you see fit to handle them in a timely fashion. One argument for assigning yourself is that it's a simple way of signifying to others that you've seen an acknowledged the issue, i.e. so that people know the lights are on. Again, your call though.

**Comment by vycoreb** [comment]
@cbeams thank you. i also tried ctrl+o/alt+o but it requires a deposit tx id, but there isnt one (see details column details_col.png, there is "Taker and tx fee" twice but no "Multisig deposit" for this trade).

![select_deposit](https://user-images.githubusercontent.com/44715956/47953624-6e0db480-df80-11e8-8bcb-4b2cf7249777.png)
![details_col](https://user-images.githubusercontent.com/44715956/47953623-6e0db480-df80-11e8-8d00-37e7e5fc9592.png)

**Comment by vycoreb** [comment]
@cbeams there was another user on slack with a failed trade, i collected his trade details and reimbursed him myself for now so he has the money immediately in this tx https://live.blockcypher.com/btc/tx/520b8afc6a81958b8189f5ef319e14661a9e89a880cda18d239361e6e89bcd29/

please add the amount of 0.0002638 BTC to my reimbursement. his trade id was trade id 2395360-99b9d7da-c57e-4758-8aa5-647f800990ad-080, here is a screenshot
<img width="604" alt="stuck" src="https://user-images.githubusercontent.com/44715956/47964906-454cf400-e040-11e8-939f-6d6ec87f70d7.png">

i guess it might go to arbitration, we should make sure the arbitrator knows whats up so he doesnt get reimbursed again.

i have his trade contract and more info, if there are any questions let me know.

**Comment by cbeams** [comment]
> there was another user on slack with a failed trade, i collected his trade details and reimbursed him myself

That was very kind of you, thanks. Could you provide a link to the Slack chat?

> please add the amount of 0.0002638 BTC to my reimbursement.

@KanoczTomas, this should be fine to do when you're processing this. Would be good to see the Slack chat, and/or confirm that the trade did eventually go to arbitration, i.e. to get some kind of proof on this. I'm sure @vycoreb is on the up-and-up here, but we shouldn't set a precedent that users can just report something like this without any proof; it would be easy to just transfer one's own bitcoin to oneself, and then claim the tx was actually reimbursing someone else.

> his trade id was trade id 2395360

Ok. I haven't seen anything on this one come into my queue yet. @keo-bisq, if you see it, please let us know here. Thanks, all.

**Comment by vycoreb** [comment]
@cbeams he sent me his trade contract in private and asked for confidentiality since it contains personal information. the relevant part based on which i paid him the fee, while also considering that it is only around 1.44$ was his maker fee tx (offerFeePaymentTxId) https://www.blockchain.com/btc/tx/4dab375a8c063fd8e12de74f8ee0836e1d8832b57feef1d57798e565968ed9c5

**Comment by KanoczTomas** [comment]
@vycoreb thanks, the txid of the trade to reimburse is sufficient I think, I have it recorded in the csv file with the trade id as well. Your taker fees are added, too. The address you have provided was used as the reimbursement address. Let me know if I need to change it.

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/147#issuecomment-443627102.
