### ISSUE TITLE
Fee reimbursement for trade oxGWbhP

### ISSUE THREAD

**Issue by Takoyakirorista** [bisq-network/support#1541]
![oxgwbhp](https://github.com/bisq-network/support/assets/156135029/a71e1161-c1fa-4d24-94f8-fac0b7a577ee)

Maker fee transaction ID - ba6133f90bb8f15c340ecc4c888e8aea9c6946af2b8e63b90c2ceeecc4f1c245

Taker fee transaction ID - 990dc4de5bb8493d11b52c56e004502744015ee2c5a30a013946df9a35cc1629

Deposit transaction ID - 4e546139bb2d2464c1843dd37ca6f3151778f89fd64accfa00e1133693633f10

Delayed payout transaction ID - 8f0cf11f2605c040780f41dbbcb44532befd8c8f86c6039a432a451259a22c81

Bisq version: 1.9.14

BTC address for reimbursement: bc1quad3kj3seyga968x8eztpxjukkkgryuq4xsk96

**Comment by darawhelan** [comment]
Hi @Takoyakirorista 

On this trade you lost:

Miner fee: 0.00018960 BTC
Trade fee: 0.00005000 BTC

**Total: 0.0002396 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
Payout made with #1557
