### ISSUE TITLE
Fee reimbursement for trade 70950-3becbeb6-1e3b-49be-b498-e8f934074a26-1914

### ISSUE THREAD

**Issue by Zigmoot** [bisq-network/support#1543]
![Screen Shot 2024-01-16 at 1 01 42 PM](https://github.com/bisq-network/support/assets/105036472/58f37fc6-4f9e-45e4-866f-0481a1dd93ee)

Maker:  a12f32418ffac7618993ddf587a3f6b5df648e49c5a01a70327c8c0685b55c42
Taker: 36884f5499f9e52b22fc16a045a5b7679a45672223d917ee9c1bd31a06737112
BTC mining fees lost: 0.00018910 BTC
BSQ trade fees lost

Bisq version: 1.9.14
BTC address for reimbursement: bc1qhualhrjafqnj8jwpqfwk7addstpd29s65cxkyc

I also have the security deposit locked which is the reason for the ticket. 0.0015 BTC. @pazza83 is the selected mediator. Thank you

**Comment by Zigmoot** [comment]
I also have the security deposit locked which is the reason for the ticket. 0.0015 BTC  Thank you

**Comment by pazza83** [comment]
Hi @Zigmoot 

Thanks for the post.

This trade paid out:

https://mempool.space/tx/4263582f918efb349753e40f2aecd02ddfe1aa8886c703d4045a9bef0cb409ef

There are no locked funds.

You mentioned you were getting an error showing locked funds.

Go to Funds > Locked Funds 

Can you see anything there that relates to the locked funds?

**Comment by Zigmoot** [comment]
Thank you @pazza83.  That is empty.  It is listed in the top right corner of the application and I cannot seem to find what it relates to whatsoever.  Any advice would be much appreciated.  Thank you for verifying this one for me.

**Comment by pazza83** [comment]
Sounds like your wallet is out of sync and showing the incorrect amount. I would suggest you do an SPV resync: https://bisq.wiki/Resyncing_SPV_file
