### ISSUE TITLE
Fee reimbursement for trade TTKRS4S

### ISSUE THREAD

**Issue by benthadura** [bisq-network/support#1544]
![TTKRS4S_Bisq](https://github.com/bisq-network/support/assets/156913708/d6a19e9d-63cf-4c2c-b489-10292c7d8f5d)

Selected mediator: leo816
Selected arbitrator (refund agent): refundagent2

Maker:  04418fbcfe9fa6e8fb39595f5b159c708f6de43b13100848311b985f48b5cd51
Taker: 355f5ae3e6d1e2ac162d92245e8c3c0ac838c23c2c2aa471448f39d6455dcaee
Deposit: n/a
BTC mining fees lost: n/a
Trade fees lost, please state if BSQ or BTC: 0.000565 BTC

Bisq version: v1.9.14
BTC address for reimbursement: bc1qede4th9nusqye0mtndyqvsuwe94v2ua9zmkg5q

Other notes:

**Comment by darawhelan** [comment]
Hi @benthadura 

On this trade you lost:

Miner fees: 0.00011650 BTC
Trade fees: 0.00044850

**Total: 0.000565 BTC**

@leo816 please can you reimburse in your next batch. Thanks

**Comment by leo816** [comment]
Payout made with #1557
