### ISSUE TITLE
Fee reimbursement for trade RYDSIXQ

### ISSUE THREAD

**Issue by bieber-t-beaver** [bisq-network/support#1545]
I am the taker

![image](https://github.com/bisq-network/support/assets/107782777/c5fce101-927f-43b5-a344-c18c2b6f1731)

Maker fee tx: 0b4c7820e7eacacaaf768c92374b25e9df05e47a01dc32861c1752bc4f2bebc2
Taker fee tx: 071c2a95fe3ba495a9f271a4ee2e25dc3de169351ddc20adb6508e8fa0d8c2e8

Error: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

Bisq version: v1.9.14
BTC address for reimbursement: bc1q70klzerncv46066a008klguwrxrqzltcpnc6xx

BTC mining fees lost: 0.00028680 BTC
Taker and tx fee: 0.00009415 BTC
Trade fees lost, please state if BSQ or BTC: 1.45 BSQ

**Comment by darawhelan** [comment]
Hi @bieber-t-beaver 

On this trade you lost:

Miner fee: 0.00009560 BTC
Trade fee: 1.45 BSQ

@leo816 please can you reimburse in your next batch. Thank you

**Comment by leo816** [comment]
Payout made with #1557
