### ISSUE TITLE
Fee reimbursement for trade rtajn

### ISSUE THREAD

**Issue by bieber-t-beaver** [bisq-network/support#1546]
I am the maker

![image](https://github.com/bisq-network/support/assets/107782777/15c5ca36-2228-4fe7-a84e-bc0b48b4af0c)

Maker fee tx: 4ba561d583f0111041f9f3c26ac485d8409d951f32d6cc6562ba90916654e7bd
Taker fee tx: 6bde79a3ea65348b1b9f87c6f64c812e50e5c6342dee884cfac5d2e0d21970d3

Error: Timeout reached. Protocol did not complete in 120 sec.

Bisq version: v1.9.14
BTC address for reimbursement: bc1q70klzerncv46066a008klguwrxrqzltcpnc6xx

BTC mining fees lost: 0.00023821 BTC (as the maker)
Maker and tx fee: 0.00023643 BTC
Trade fees lost, please state if BSQ or BTC: 1.78 BSQ

**Comment by darawhelan** [comment]
Hi @bieber-t-beaver 

On this trade you lost:

Miner fees: 0.00023821 BTC
Trade fees: 1.78 BSQ

@leo816 please can you reimburse in your next batch. Many thanks

**Comment by leo816** [comment]
Payout made with #1557
