### ISSUE TITLE
Fee reimbursement for trade NHBDWZ

### ISSUE THREAD

**Issue by Capivara69** [bisq-network/support#1547]
I am the taker

![image](https://github.com/bisq-network/support/assets/157431683/a183d3f7-aa94-4349-82f5-30a290ba82da)

Maker: aa3d027d0dd738fb9acb4826365801cb65a929e07d426681b447f1e0351aba53
Taker: ed7962a91db0e760160312059a0db03bcb24d34154146a657baa50c882743d2f
Deposit: N/A
BTC mining fees lost: 0.00034251 BTC
Trade fees lost: 0.00068917 BTC
Bisq version: 1.9.14
BTC address for reimbursement: bc1qxvrsv043e44x0rpv3suntzua4js4yukd6x9clp
Other notes: none

**Comment by darawhelan** [comment]
Hi @Capivara69 

On this trade you lost

Mining fees: 0.00011417 BTC
Trade fees: 0.00057500 BTC

**Total: 0.00068917 BTC**

@leo816 please can you add to your list for reimbursement. Thank you.

**Comment by leo816** [comment]
Payout made with #1557
