### ISSUE TITLE
Fee reimbursement for trade TAMPC

### ISSUE THREAD

**Issue by citadel0wner** [bisq-network/support#1548]
![image](https://github.com/bisq-network/support/assets/157433166/acb80ac3-9edf-4ef9-954b-b37c2599d84b)

Maker: aae2262aedc6ade3896d19c41820b738cd2bc1434f199196a19b20252fe47bf5
Taker: b0bb36b97d6893482b08f7b6fdcebd2d9430f096224b9d2f1b61e9d4210d179b
Deposit: 38fa83d7156f0c89bba648105a9abd7a0d4eb40af779b4debf9578cf314a8172
BTC mining fees lost: 0.00010197 BTC
Trade fees lost, please state if BSQ or BTC: 1 BSQ

Bisq version: v1.9.14
BTC address for reimbursement: bc1qrtdlqu39nc5qfvlqggtk7l65hg8g5qjl8mhrhj

0.012985 BTC security deposit locked and "timeout reached. Protocol did not complete in 120 sec." error message. Please reimburse fees. Thanks.

**Comment by darawhelan** [comment]
Hi @citadel0wner 

This trade did not fail.

It was completed. Here is the payout transaction:

https://mempool.space/tx/5f126007a0ec9352ed74d9411f9fd02f2b13be4599cea3940126c7f698c2e018

**Comment by citadel0wner** [comment]
Thanks. Just noticed the locked funds which still appear as locked were included in the transaction.

**Comment by darawhelan** [comment]
Doing an resync should make your Bisq display the correct balances: https://bisq.wiki/Resyncing_SPV_file
