### ISSUE TITLE
Case XXXXX

### ISSUE THREAD

**Issue by hannesur** [bisq-network/support#1549]
Attention
The trade protocol encountered some problems.

The trade contract is not set.

The trade cannot be completed and you might have lost your trade fee. If so, you can request a reimbursement for lost trade fees here: [1]
[https://github.com/bisq-network/support/issues]
Device or machine:
>_Provide the Operating System and Version_
Ubuntu 22.04.3 LTS

![Screenshot from 2024-01-23 13-49-45](https://github.com/bisq-network/support/assets/157487047/fc8e04ee-91c8-4c50-ab9b-620dc12bdb55)

solution:

Other notes:

**Comment by darawhelan** [comment]
@hannesur 

Please can you edit your post to follow the template found here:

https://github.com/bisq-network/support/issues/new?assignees=&labels=&projects=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX

**Comment by hannesur** [comment]
Hi!

This trade looks good from my side. Screenshot attached.
It took a loooong time to confirm, seemingly because of low fees. Is there
anything at all to do about that?


cheers,

Hannes Urbanik

**Comment by darawhelan** [comment]
I would check the deposit transaction on a block explorer. 

Is it valid?

If it is then I would recommend doing an SPV resync as your Bisq client is showing the trade as failed.

https://bisq.wiki/Resyncing_SPV_file

**Comment by hannesur** [comment]
Hi!

On Fri, Jan 26, 2024 at 9:40 AM Dara Whelan ***@***.***>
wrote:

> I would check the deposit transaction on a block explorer.
>
> Is it valid?
>
> Deposit transaction has 15 confirmations. So it must be valid?



> If it is then I would recommend doing an SPV resync as your Bisq client is
> showing the trade as failed.
>
Where does my Bisq show it as failed?
Maybe you mean payout transaction - that has only a few confirmations on
the screenshot and the circle was not full. Now it has 7 confirmations.

All the transactions have confirmations, except the delayed payout
transaction which is not found on the mempools.

(not trying to argue, just to learn. :))

Will resync the SPV file anyway. :)

cheers,

Hannes

**Comment by darawhelan** [comment]
> Where does my Bisq show it as failed?

The little red arrow on the right side of the trade in your posted screenshot indicates Bisq thinks the trade failed. 

If everything has confirmed it is a false error.

Yes it would be good to for you to do the SPV resync

**Comment by hannesur** [comment]
Hi!




On Fri, Jan 26, 2024 at 8:31 PM Dara Whelan ***@***.***>
wrote:

> Where does my Bisq show it as failed?
>
> The little red arrow on the right side of the trade in your posted
> screenshot indicates Bisq thinks the trade failed.
>
> I am really sorry but i see no little red arrow?
Everything confirmed, did the resync, all seems OK.
