### ISSUE TITLE
Fee reimbursement for trade 7998323

### ISSUE THREAD

**Issue by dfein38347g** [bisq-network/support#1550]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screenshot from 2024-01-23 09-27-51](https://github.com/bisq-network/support/assets/79952941/755ba7d4-25ce-4716-9965-9c131e77f688)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  3e6dff6be81c3d60f5088b0a454d67c1fbaa2ff3bf03ee2f0f9a02f0bc11cecf
Taker: ...........
Deposit: 0.0132 BTC
BTC mining fees lost: 0.00039144 BTC
Trade fees lost, please state if BSQ or BTC: 0.00019838 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.14
BTC address for reimbursement: bc1qjt487urua9nys4eu8wedehjyjdyj58wtw6263v

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @dfein38347g 

As you are the taker and there is no taker transaction no funds left your wallet. 

You have not lost any funds on this trade.
