### ISSUE TITLE
Reimbursement for  trade 5273251-df2e8c37-fc51-4d0a-a490-40306c59c23a-1914

### ISSUE THREAD

**Issue by AKtheDragon** [bisq-network/support#1552]
Reimbursement of Mining Fee Taker: 0.00024465 BTC for trade 5273251-df2e8c37-fc51-4d0a-a490-40306c59c23a-1914

I am BTC buyer as taker for EUR.
Trade amount and asset: 0.0050 BTC for 203 EUR
Trade Price: 40513.9915 
Trade date: 20 Jan. 2024 11:36:01 am 

Trading Peers Onion Address: 7t3nzw77z7fencmw46gxzhawaxtlzr52eh2jsqubardhvbpjmxkxz3qd.onion:9999

Error Message: Timeout reached. Protocol did not complete in 120 sec. 

Bisq version: 1.9.14

>_Ping @refund-agent2 and your mediator_

**Comment by darawhelan** [comment]
@AKtheDragon 

Please can you edit your post to follow the template found here:

https://github.com/bisq-network/support/issues/new?assignees=&labels=&projects=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX
