### ISSUE TITLE
Reimbursement for trade GPBOZGYD

### ISSUE THREAD

**Issue by Morocotas4life** [bisq-network/support#1553]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![GPBOZGYD_FailedTradeED](https://github.com/bisq-network/support/assets/157741123/841f286a-5550-4ab9-82f2-196ff9968c6d)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: ebd5a480417c7aa5fa7f896f915316607d3672d549124e1cf942acb5d97e152f
Taker: 2833049511b0d55c254504c69f0b9cb61805abaa683565ef721ff0f4feb60049
Deposit: 4e57ab418c7c2ce55c2f1d6118ec03ee2767f255248b454db2879cbc7b036829
BTC mining fees lost: 0.00010703 BTC
Trade fees lost: 0.52 BSQ

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.14
BTC address for reimbursement: bc1qeas2e5sm3gd23zzfxv3lxqdx9m9yefaj8z5tsd

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:
Transaction failed. BTCs and BSQs were decuted although the trade never took place. I was the Taker. 

Selected mediator: leo816
Selected arbitrator (refund agent): refundagent2
@refundagent2

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
@Morocotas4life 

This trade did not fail.

It is good to complete.

If the trade is showing as failed on your Bisq please do an SPV resync 

https://bisq.wiki/Resyncing_SPV_file

**Comment by Morocotas4life** [comment]
Hi darawhelan and thank you for your prompt reply.

A picture is worth a thousand words

![GPBOZGYD_FailedTrade_ReplyCOLLAGE](https://github.com/bisq-network/support/assets/157741123/8d99f88a-216c-4caf-963c-11317010c2df)

As you can see, the transaction is shown as failed, and although the deposit, the mining fee and the trading fee were deducted from my balance, I was given no info to send the corresponding payment, and I do not have the "purchased" BTC.

I had already done the Resyncing before posting the issue, but that did not reimbursed anything. If, as you say, the Tx is good to complete, how exactly could it be done?

Thanks in advance for your help and advice.

**Comment by darawhelan** [comment]
> As you can see, the transaction is shown as failed, and although the deposit, the mining fee and the trading fee were deducted from my balance, I was given no info to send the corresponding payment, and I do not have the "purchased" BTC.

The transactions were all successful, including the deposit transaction. The trade did not fail. Bisq is showing the trade as failed but that is an error.

If the trade is in Failed trades I would recommend moving it back to open trades (click arrow to the right of the trade)
After this I would then do an SPV resync.
You can then open mediation for the trade.

@leo816 / @pazza83 do you have Trade ID: GPBOZGYD  in your meditations

> I had already done the Resyncing before posting the issue, but that did not reimbursed anything. If, as you say, the Tx is good to complete, how exactly could it be done?

The resync will help show the deposit as confirmed and not failed.

I think you will also benefit from seeking support from the Bisq Matrix support room ASAP as the trade is live. 

https://bisq.wiki/Matrix_bisq.chat

**Comment by Morocotas4life** [comment]
Once again, thanks for you support and guidance :)

I have already done the corresponding payment and I have also joined the matrix.

Hoping this can all be sorted out soon and properly :)
