### ISSUE TITLE
Fee reimbursement for trade w6Y3SPe

### ISSUE THREAD

**Issue by beaver6919** [bisq-network/support#1556]
SCREENSHOT HERE
![image](https://github.com/bisq-network/support/assets/73044458/3a24a7ce-c7e1-415c-8238-730eb7cfc6ae)
![image](https://github.com/bisq-network/support/assets/73044458/e8b9e643-8e66-405e-bfdf-8ea50eeb8f0d)

Maker:  88801f49b4c0e4966c0015bedf6d73c26f269d115022f8164f41a8e471f1b8e5
Taker: 70dbbdb10594f9880bd54f903f9c9204fc8bb5d27d08562df297c0198a21a8ea
Deposit: f73f806837d92c09c5218da38fbeb16a508b4b6b31a3bd748a4702bd76a68a00
BTC mining fees lost: 0.00021240 BTC
Trade fees lost, please state if BSQ or BTC: 
amount to spend- 0.0470BTC
security deposit- 0.0111 BTC

I thought i had slightly more in my bisq wallet before the trade commenced but maybe not?

Bisq version: 1.9.14
BTC address for reimbursement: bc1qcd7vyd6ecz0cmkdj2388qclyrx8urgtq6krqqe

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @beaver6919 

This trade has not failed.

While the trade is in progress the funds are moved to 'locked' as they have entered the multi-sig.

Let me know if you have questions
