### ISSUE TITLE
Fee reimbursement for trade 3a9fa128871198693a269d8757639c2f085dbf91f1d6b1688b77a04fb696172d

### ISSUE THREAD

**Issue by cpascotto** [bisq-network/support#1558]
BUYER 89656834

![image](https://github.com/bisq-network/support/assets/31831985/fa1d84cb-6b68-4fe6-80e1-311ef2fd6e5b)

Maker: 3a9fa128871198693a269d8757639c2f085dbf91f1d6b1688b77a04fb696172d
Taker: N/D

Mining fees lost: 0.00005950 BTC

"Timeout reached. Protocol did not complete in 120 sec." error. It's in failed-folder. Please reimburse fees.
Thanks.
![fee](https://github.com/bisq-network/support/assets/31831985/d46babc4-3a2b-4f70-84dc-28e2acc03c76)

**Comment by darawhelan** [comment]
Hi @cpascotto 

As you are the taker and there are no taker transactions present you did not lose any funds or fees on these trade. Nothing left your wallet.

I would recommend you do an SPV resync and your wallet might be out of sync.

https://bisq.wiki/Resyncing_SPV_file
