### ISSUE TITLE
Fee reimbursement for trade nCNTOd

### ISSUE THREAD

**Issue by ghost** [bisq-network/support#1559]
![image](https://github.com/bisq-network/support/assets/141868491/707fe333-ed56-48f3-8d0a-1043dfda540a)

Maker fee txid: a1d95cae3b49d0704b5a2a416a3ab9cda56a0e6b17da89f6c5216a4e492faed7

BTC mining fees lost: 0.00007840 BTC
Trade fees lost: 6.73 BSQ

Bisq version: 1.9.14
BTC address for reimbursement: bc1qlk88a9y50647lytu8k4peth5wkxllryqzp4wkw

Please reimburse fees.

**Comment by darawhelan** [comment]
Hi @worminder 

on this trade you lost:

Miner fee: 0.00007840 BTC
Trade fee: 6.73 BSQ

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
payout made with #1595
