### ISSUE TITLE
Fee reimbursement for trade LGVPT5M

### ISSUE THREAD

**Issue by SteveOTC45890** [bisq-network/support#1561]
![image](https://github.com/bisq-network/support/assets/158324602/587a272e-5ce0-4b8f-b57e-e1b0f32ed88b)

Maker:  1fac074d2a70b096afc9bbde4e63ecefa29030e3812bafd29cc6a12caf35bdce
Taker: fc84959dc2df6811f5324cc3b81f5d88b6dd1c18e5f784fa96c7ceb8707053c0
Deposit: N/A
BTC mining fees lost: .0.00006240 BTC
Trade fees lost: 0.00005 BTC

Bisq version: 1.9.14
BTC address for reimbursement:  bc1qrwggqf2j4z08p3l6wxcxgfnxd62dj3jycce95q

**Comment by darawhelan** [comment]
Hi @SteveOTC45890 

Please can you include the top of the screen shot that shows if you were buyer / seller and maker / taker.

**Comment by SteveOTC45890** [comment]
![image](https://github.com/bisq-network/support/assets/158324602/f207d2db-dab0-4ef0-8ab0-628ed909c92d)

**Comment by darawhelan** [comment]
Hi @SteveOTC45890 

On this trade you lost:

**Total: 0.00011240 BTC**

@leo816 please can you add to your reimbursement list

**Comment by leo816** [comment]
payout made with #1595
