### ISSUE TITLE
Fee reimbursement for trade XNVEH

### ISSUE THREAD

**Issue by gamaweliton** [bisq-network/support#1562]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

![image](https://github.com/bisq-network/support/assets/59203069/c9eddc5a-66a9-4652-9fa1-014da417a0f9)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  2984e337d2ab49536bd1a66f34f90a7b0e0be0f052ca5a4433f555a97aa1e5a0
Taker: N/D
Deposit: N/D
BTC mining fees lost: 0.00039144  BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement: bc1qnxue58j8ujsrf8t4mhuju30glpey69ujqte5c3

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @gamaweliton 

As you are the taker and there are no taker transactions present you did not lose any funds or fees on these trade. Nothing left your wallet.

I would recommend you do an SPV resync and your wallet might be out of sync.

https://bisq.wiki/Resyncing_SPV_file

**Comment by gamaweliton** [comment]
Thanks @darawhelan !
I will resync in my wallet to fix balance.

Thanks your patience I'm noob in the market yet.

Taking advantage of the opportunity, I would like to know if you could suggest some content for studying transactions on the blockchain and bisq

**Comment by darawhelan** [comment]
No problems I am not aware of a good place that explains everything that happens on Bisq with the blockchain .

Have a look at these posts here:

https://www.reddit.com/r/bisq/comments/104tcry/anatomy_of_a_transaction_as_it_looks_on_the/
https://bisq.community/t/anatomy-of-a-bisq-trade/10979

**Comment by gamaweliton** [comment]
Thanks!!!
