### ISSUE TITLE
Fee reimbursement for trade gcvrqnn

### ISSUE THREAD

**Issue by h13458** [bisq-network/support#1564]
![Screenshot from 2024-02-04 07-59-01](https://github.com/bisq-network/support/assets/112901072/bdae5a2f-9f94-4d61-9734-c6d7b5cb64c0)
![Screenshot from 2024-02-04 08-00-03](https://github.com/bisq-network/support/assets/112901072/8b958702-41ea-4ad3-8cde-605912d0107c)

Maker:  b2ae275bd2b1c4b1859ab29c4a5aa55d7833dcc4421aed512e086ac4bdfa7bf1
Taker:  4243dbfdcb4e555e9ef9bc065fd917444f8e78d70896b7995a1d4612084dc74a
Deposit: d1c18de4f53aa2759ec8bb78bb0a6b6ba15084e75908f7122089c2e2ccfa471f
BTC mining fees lost: 0.000042 BTC
Trade fees lost, BTC: .......... .000050

Bisq version: 1.9.14
BTC address for reimbursement: bc1qhtzzf9r6hgp5guanufepmqfa4krlr4hscdas3r

**Comment by darawhelan** [comment]
Hi @h13458 

On this trade you lost:

**Total: 0.00009200 BTC**

@leo816 please can you add to your reimbursement list

**Comment by leo816** [comment]
payout made with #1595
