### ISSUE TITLE
Fee reimbursement for trade ucmQEi

### ISSUE THREAD

**Issue by user9102** [bisq-network/support#1566]
![image](https://github.com/bisq-network/support/assets/91982756/1db85a1a-6d54-4d48-bff7-1bee7ce2b6bd)

Maker:  3366b7209f6a339d32b52dab43b532962b54ef9ce6d248579e7dc7976603fecb
Taker: 24fcc11f60e25a647d231a7f8be509753a1c4b1d596b70bdfab4935b6609ffa6
Deposit: 
BTC mining fees lost: 0.00006125 BTC
Trade fees lost, please state if BSQ or BTC: 0.30 BSQ

Bisq version: 1.9.14
BTC address for reimbursement: bc1pzma73fmc3pva92urmpujls55w0fyv4rlax0ygcp43rcp6nggwnfs5alekr

Other notes:

**Comment by darawhelan** [comment]
Hi @user9102 

This trade failed. 

But it should still be in your open offers for another user to take.

**Comment by user9102** [comment]
It's not in my open offers anymore. It doesn't seem to return locked fund from this trade after it failed.

**Comment by darawhelan** [comment]
ok, in that case for this trade you lost:

Trade fee: 0.30 BSQ
Miner fee: 0.00010540 BTC

The locked funds, never ended up being locked. You spent what would have been the locked funds on a subsequent trade.

https://mempool.space/tx/ca96df92ac6bab6ca676bd2887d3317b09f95c2551e97a97d0d2847d0d1496c7

@leo816 please can you add this to your list of reimbursements

**Comment by leo816** [comment]
payout made with #1595
