### ISSUE TITLE
Fee reimbursement for trade JSKYMBN

### ISSUE THREAD

**Issue by user9102** [bisq-network/support#1567]
![image](https://github.com/bisq-network/support/assets/91982756/382b376a-f192-4fab-bd56-bff285fdd772)

Maker:  92e6124d9058c098a0dfc8a9c0439970a2cc8bf26559b106a06084b40bcb21db
Taker: b9e9b0dca4e7ba76c51e96893b2310e1bdd74a8785c90cd7a881ff611f637827
Deposit: 
BTC mining fees lost: 0.00010540 BTC
Trade fees lost, please state if BSQ or BTC: 0.30

Bisq version: 1.9.14
BTC address for reimbursement: bc1p0muzexvydj32cuwm0krwa7eud7z50h7kujgntu7ukema7mcatqfqclc7xl

Other notes:

**Comment by darawhelan** [comment]
Hi @user9102 

This trade failed. 

But it should still be in your open offers for another user to take.

**Comment by user9102** [comment]
Same as the other trasanction:
It's not in my open offers anymore. It doesn't seem to return locked fund from this trade after it failed.

**Comment by darawhelan** [comment]
Ok, in that case for this trade you lost a total of **0.0002697 BTC**

The locked funds, never ended up being locked. You spent what would have been the locked funds on a subsequent trade.

https://mempool.space/tx/c896f9ebfeb0e02c2e4b35ca8e6343cf91d088af25b084ee37f7bfb492de7caf

@leo816 please can you add this to your list of reimbursements

**Comment by leo816** [comment]
payout made with #1595
