### ISSUE TITLE
Fee reimbursement for trade 6429242

### ISSUE THREAD

**Issue by fox78205** [bisq-network/support#1568]
![image](https://github.com/bisq-network/support/assets/159450390/c88254c6-1e55-44b7-8f4c-0382d62cb058)

Maker:  f0dc3fe96e63195e1a9981d14ab417dfc2615856cba6c7572f4e4309b79051a0
Taker: 9b1e838e53deb0493f6d15c795fdcf15c6be98ff45a14094557889cdcb4312f1
Deposit: ..........
BTC mining fees lost: 0,00019572 BTC
Trade fees lost, please state if BSQ or BTC: 0.000575 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qx9ypleaenaqj0v37p88vgndssglg8u78j5ea95

Other notes:
I would like to know if the Security deposit (0.0075 BTC) has returned to my funds. Tks!

**Comment by darawhelan** [comment]
Hi @fox78205 

On this trade you lost:

Miner fees: 0.00006524 BTC
Trade fees: 0.00057500 BTC
**Total: 0.00064024 BTC**

The security deposit was returned to you and subsequently spent

@leo816 please can you add to your reimbursement list

**Comment by leo816** [comment]
payout made with #1595
