### ISSUE TITLE
Fee reimbursement for trade 4Hf1j8-13e0c939-26dc-4972-ae0e-20d4f780c4c8-1914

### ISSUE THREAD

**Issue by JuneSites** [bisq-network/support#1569]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![ss 2024-02-09 at 7 53 51 PM](https://github.com/bisq-network/support/assets/661252/e91d785f-0bc3-470b-a8c4-db4097e558e1)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  fcd10c95bb94440702c6ad4907d07d4e2f78bdac233cb0a715d96be6c0ba827e
Taker: 87453bfcdc0980018688a0809f84d0f11f38d476f04d297e77d06cdb3570694b
Deposit: n/a
BTC mining fees lost: Maker: 0.00005019 BTC / Taker: 0.00014679 BTC
Trade fees lost, please state if BSQ or BTC: 0.00011500 BTC / 0.00005000 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.14
BTC address for reimbursement: bc1qwqqk5j3a4snddv9y6p5jr7tg0x40m3844g7d8h

>_Provide the Bisq client version to help developers identify the causing issue._ 1.9.14

Other notes:
Timeout reached. Protocol did not complete in 120 sec. Moved to failed folder. Please reimburse mining and trading fees.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @JuneSites 

On this trade you lost:

**Total: 0.00016393 BTC**

@leo816 please can you add to your reimbursement list

**Comment by leo816** [comment]
payout made with #1663
