### ISSUE TITLE
Fee reimbursement for trade fkxlz

### ISSUE THREAD

**Issue by nlroberts** [bisq-network/support#1573]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://github.com/bisq-network/support/assets/38364146/97824947-7b64-441f-88ac-1825a4cadc68)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  7713b757c0c817e056f0d431c39c3d2903450ca044f079ce3e952e2abf1df870
Taker: N/A
Deposit: N/A
BTC mining fees lost: 0.00007182 BTC
Trade fees lost, please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.9.14
BTC address for reimbursement: bc1q6nwsetp65xu8asrlq7zl9vvuxjchz997nrnat3

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: This is the first time I've had a trade fail like this. Unsure what the cause is. Just looking to get my trade fees and deposit back. Thanks,

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @nlroberts as you were the taker in this trade and there was no taker transaction you have not lost any miner fees, trade fees or deposit.

If the correct balance is not showing in your Bisq wallet please do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file)

**Comment by nlroberts** [comment]
> Hi @nlroberts as you were the taker in this trade and there was no taker transaction you have not lost any miner fees, trade fees or deposit.
> 
> If the correct balance is not showing in your Bisq wallet please do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file)

Thank you for taking a look and informing me. 
Is the best action for me to take to "move trade to failed trades"?
Thanks again

**Comment by darawhelan** [comment]
Happy to help. It is fine to move the trade to failed
