### ISSUE TITLE
Fee reimbursement for trade tukoybfg

### ISSUE THREAD

**Issue by Jchristopherrr** [bisq-network/support#1575]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
<img width="852" alt="Screenshot 2024-02-24 at 10 34 12 AM" src="https://github.com/bisq-network/support/assets/156599218/9d9f73a7-adb4-4342-9272-2a050afa0968">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 19f7899b1a2a0df75a85916e0e46f090b86b9f24cf9a7021b3078839514874f4
Taker: 896ad12bf984c704bad68ede5290f604bbfd0e9f2ea368f2660875e04c681678
Deposit: N/A
BTC mining fees lost: 0.00015378 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005126 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.14
BTC address for reimbursement: bc1qy7szdxy4nl65ak69qcaaynueqlqwax7arkuc2u

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @Jchristopherrr 

On this trade you lost:

Mining fee: 0.00005126 BTC
Trade fee: 0.00011615 BTC

**total loss:  0.00005126 BTC**

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
payout made with #1595
