### ISSUE TITLE
Fee reimbursement for trade LJmXBplI

### ISSUE THREAD

**Issue by Jchristopherrr** [bisq-network/support#1576]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
<img width="848" alt="Screenshot 2024-02-24 at 10 39 01 AM" src="https://github.com/bisq-network/support/assets/156599218/f1a6d3c6-d6bc-4e55-82a0-338a2e72690b">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  3f7c1f1e3bb940864ffc3ee4b675a787eaeee938d272e2971b9eda62668aba24
Taker: 54e2bd1fa9a14f1254cc509af8c5ed4a5d938e0fd04b706928934a53edc79804
Deposit: N/A
BTC mining fees lost: 0.00016077 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005359 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.14
BTC address for reimbursement: bc1qy7szdxy4nl65ak69qcaaynueqlqwax7arkuc2u

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @Jchristopherrr 

On this trade you lost:

Mining fee: 0.00005359 BTC
Trade fee: 0.00011615 BTC

**total loss:  0.0.00016974 BTC**

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
payout made with #1595
