### ISSUE TITLE
Fee reimbursement for trade TC25ZE

### ISSUE THREAD

**Issue by eothahn** [bisq-network/support#1577]
SCREENSHOT HERE
![image](https://github.com/bisq-network/support/assets/161184867/a1d0e9eb-728b-4d3b-bae1-5cc9665684c3)

Maker:  901826e7339b1fdb3b2289ff4192c463581e7b8f4515ca185a975a6d4af9fa56
Taker: 082cde25e48d909a3111fe1bceac45dd5b921a933ca30935b8dd5ea8015fbd04
Deposit: N/A
BTC mining fees lost: 0.00009087 BTC
Trade fees lost, please state if BSQ or BTC: 0.000115 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qn6cmklx606s52apgj9ww6w8ccpyyzgmz68q9qc

error: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.
Please reimburse fees.
Thanks

**Comment by darawhelan** [comment]
Hi @eothahn 

On this trade you lost:

Mining fee: 0.00003029 BTC
Trade fee: 0.00011500 BTC

**total loss:  0.00014529 BTC**

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
payout made with #1595
