### ISSUE TITLE
Reimbursement for cjtkaurzv4h5t4u5dfm6dyqvhhjebcsi4i3ql4mepjhgsgyodzc336ad.onion:9999

### ISSUE THREAD

**Issue by natcrypto** [bisq-network/support#1578]
SCREENSHOT HERE

<img width="898" alt="image" src="https://github.com/bisq-network/support/assets/34958724/868af132-dd90-483b-8775-ddad1310c125">

Reimbursement for trade IBBVM

I am BTC [seller] as [maker] for [GBP].
Trade amount and asset: [0.05] BTC for [GBP]
Deposit amount: Buyer: 0.01 BTC / Seller: 0.01 BTC

Maker: 039be5a63873a4e524e50df811e1fd29d0319745e0f37a88f6c591f7b5645329
Taker: N/A
Deposit: 0.01 BTC
Delayed payout: ..........
BuyerMultiSigPubKeyHex: ..........
SellerMultiSigPubKeyHex: ..........

Reimbursement amount: [AMOUNT] BTC / [30 day BSQ average] BSQ = [TOTAL AMOUNT] BSQ
Reason for reimbursement: transaction failed - prior to this Bisq stalled on "Take offer in progress..." when I try to take an offer. Prior to this I receive an error saying, "Warning: You cannot take this offer because you already took it earlier. It could be your previous take offer resulted in a failed trade. I am unable to leave this screen and have to forcibly close Bisq.

BTC address ownership proof:

Bisq version: 1.9.14

Other notes:

<img width="807" alt="image" src="https://github.com/bisq-network/support/assets/34958724/d37491fb-8b87-43ef-b0d8-8e02d511815c">

>_Ping @refund-agent2 and your mediator_

**Comment by darawhelan** [comment]
Hi @natcrypto as you were the taker and there was no taker transaction you have not lost any bitcoin on this trade.

Your wallet looks out of sync. You should do an SPV resync.

https://bisq.wiki/Resyncing_SPV_file
