### ISSUE TITLE
Fee reimbursement for trades hfwonq, VKIVCOQ, 129471, S7FD1Y, 00144, 2wfsvj, HTXMQT and PMSIXSWV

### ISSUE THREAD

**Issue by triskovac-zasmat-0g** [bisq-network/support#1579]
hfwonq
![hfwonq](https://github.com/bisq-network/support/assets/161212012/1b32ecf9-459b-455d-b03e-9bff7a82d484)

Maker: 2d860468ef81bb3945980766748cd04093438796457ae2af8eb44b5d9959bd83
Taker: 456a04d7688fa3714794a099f747d6454cf5a8f37dc3d6d1c632a446f3e73f52
Deposit: N/A
BTC mining fees lost: 0.00002100
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

Timeout reached. Protocol did not complete in 120 sec.

===================================================================================

VKIVCOQ
![VKIVCOQ](https://github.com/bisq-network/support/assets/161212012/fe6a6fa1-bec9-4c4c-83b3-c8585a37b2ec)

Maker: aad164f324191a167d50392687f5d6c85a46cbf05e5921c93ebb67950b80b2d9
Taker: fa23255d1cb090bbed002fc9d9c368adeea72fb59ba55f5a1ec274fb32e2aa20
Deposit: N/A
BTC mining fees lost: 0.00008685 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

Timeout reached. Protocol did not complete in 120 sec.

===================================================================================

129471
![129471](https://github.com/bisq-network/support/assets/161212012/381cba1f-2f2b-4766-95ae-9b719611eae8)

Maker: bff0fc96b1927bafb5762e553dfbe1295b94e5d802fd5c7e20e6a267c1487027
Taker: cd340d6be751c2f952e82469792eb5248c30322a9b662063348032ac31012356
Deposit: N/A
BTC mining fees lost: 0.00002625 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

Timeout reached. Protocol did not complete in 120 sec.

===================================================================================

S7FD1Y
![S7FD1Y](https://github.com/bisq-network/support/assets/161212012/8a64e40e-df4a-4df5-a86a-5ce5e4eeecd0)

Maker: 76126f907595e35acc9619becfa598c31e92ecd5c40e0133af55db9a76f7f658
Taker: 95ad902d0094aacd03498d1c7b78a2b54e528384ad74bc41cb3f42dd72e0f899
Deposit: N/A
BTC mining fees lost: 0.00002625 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

Timeout reached. Protocol did not complete in 120 sec.

===================================================================================

00144
![00144](https://github.com/bisq-network/support/assets/161212012/9f0529e3-76cd-4a3e-b0f5-cbeb63fa4207)

Maker: 61d39e173c5ee12eb32aa7b4135a55e403d12fd3666fd3b9af40e35d92623ac1
Taker: 691da55c15ee1434790e006ec53783e50f46d02f2b2611febd5f38877c3a475e
Deposit: N/A
BTC mining fees lost: 0.00002275 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

===================================================================================

2wfsvj
![2wfsvj](https://github.com/bisq-network/support/assets/161212012/c936cd64-1331-4ac2-999c-9a26017f901c)

Maker: 8eba9801744f4e281366539413be9ec340d9ffded2f4b0ff083783dbff4d6f79
Taker: d528c7a49c8f76a166f0be113a617289c855da03076cb31e86b8e0c26b885893
Deposit: N/A
BTC mining fees lost: 0.00002275 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

===================================================================================

HTXMQT
![HTXMQT](https://github.com/bisq-network/support/assets/161212012/153a831d-80b1-46a4-b664-9ded8ff94185)

Maker: b48ce0104861b81edab744d5a02c241f12b965313587a31a90afdc5fbdaccd33
Taker: 6e07b57cb4c88a1b84cc2dd63c97e51133bd090b580cca48b556b8d9bed0b88e
Deposit: N/A
BTC mining fees lost: 0.00003120 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

===================================================================================

PMSIXSWV
![PMSIXSWV](https://github.com/bisq-network/support/assets/161212012/9f9f8dd9-b078-4db3-a159-af6bc6109ff1)

Maker: 9c4d988a6034483638399e5bc1ec332cb098c7d5ff31593feb43c04db4c29e95
Taker: 1f3893859971f14677637d97c7a620ad178cd95d0a54d3028a2b9c0787671d26
Deposit: N/A
BTC mining fees lost: 0.00002880 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qrccujqhfuudrfxa45u9p5lzhskauy2wr46kc3t

Timeout reached. Protocol did not complete in 120 sec.

===================================================================================

Total mining and trade fees lost: 0.00066585 BTC
BTC address for reimbursement is same for all trades, please send in one transaction to lower treansaction fees.

**Comment by darawhelan** [comment]
Hi @triskovac-zasmat-0g 

You have lost the following:

hfwonq
BTC mining fees lost: 0.00002100
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

VKIVCOQ
BTC mining fees lost: 0.00008685 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

129471
BTC mining fees lost: 0.00002625 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

S7FD1Y
BTC mining fees lost: 0.00001925 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

00144
BTC mining fees lost: 0.00002275 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

2wfsvj
BTC mining fees lost: 0.00002275 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

HTXMQT
BTC mining fees lost: 0.00003120 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

PMSIXSWV
BTC mining fees lost: 0.00002880 BTC
Trade fees lost, please state if BSQ or BTC: 0.00005000 BTC

**Total: 0.00065885 BTC**

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
payout made with #1663
