### ISSUE TITLE
Fee reimbursement for trade rhcrnqd

### ISSUE THREAD

**Issue by jeffsurcess** [bisq-network/support#1580]
![image](https://github.com/bisq-network/support/assets/4688654/57fbb638-3eea-461a-9c34-3973d64e197e)

Maker:  4a90030740ddc56d913d4c45c2456568b69de4e324b2b208b01591be5ea495c5
Taker: 752e9c93fd8281c5dc098da325cf82909ef946b1af278b59caab5b115872f89e
Deposit: ..........
BTC mining fees lost: .......... eg 0.00005 BTC
Trade fees lost, please state if BSQ or BTC: I'm not clear from looking at the Maker fee transaction what my loss is, but I suspect it's 0.025948BTC + 0.00005BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qaef2dzum74a5azur4r3k5gftn24kdyqzr24hay

**Comment by darawhelan** [comment]
Hi @jeffsurcess 

On this trade you lost:

Miner fee 0.00001925
Trade fee 0.00005000

**total: 0.00006925 BTC**

Your deposit/trade amount is not lost. If you cannot see it please do an SPV resync: https://bisq.wiki/Resyncing_SPV_file

**Comment by leo816** [comment]
payout made with #1595
