### ISSUE TITLE
lost deposit on unsuccessful offer

### ISSUE THREAD

**Issue by DanielAndrascik** [bisq-network/support#1581]
Hello

I tried to sell btc in trade ID 014663 Feb 18, 2024. After several hours, the offer began to be deactivated. The deactivation condition was fine. After a few days, a message popped up that it was necessary to delete the SPV file and resynchronize bisq. After this action, the reserved funds for this offer were lost.

I deleted the SPV file and resynchronized bisq about 5 times in the last week, but the result is still the same, the deposit is lost.

Offer type: Maker as BTC seller / Taker as BTC buyer
BTC amount: 0.0150BTC
Offer ID: 014663-563fd557-18d4-4b3c-bef2-7e11b84491fe-1914
Makers onion address: wv5fxtbkr3lwfxs7lhamrmksofl3ejp7uoae7qw25xu6pqm4vxp3geqd.onion:9999
Creation date: 18 Feb 2024 02:15:48
Deposit: 0.006912BTC/0.006912BTC
Maker fee transaction ID: 2423cf490d715a68dbc3979846d5b39b55bbeea2749406a37acffa89bbe7c135

Bisq version:
1.9.14

Device or machine:
Ubuntu

SCREENSHOTS HERE
![obrázok](https://github.com/bisq-network/support/assets/89410631/2d884dc2-cce8-40bb-8d66-4098fb9b80dc)

**Comment by darawhelan** [comment]
Hi @DanielAndrascik as you were the maker in this trade and there was no valid maker transaction you have not lost any miner fees, trade fees or deposit.

If the correct balance is not showing in your Bisq wallet please do an [SPV resync](https://bisq.wiki/Resyncing_SPV_file)

**Comment by DanielAndrascik** [comment]
> as you were the maker in this trade and there was no valid maker transaction you have not lost any miner fees, trade fees or deposit.
> 
> If the correct balance is not showing in your Bisq wallet please do an

Unfortunately, even 8 SPV resynchronizations did not help. Should I use a emergency wallet tool?

**Comment by darawhelan** [comment]
There are a few options. Not sure is emergency wallet would work if you are out of sync.

I would recommend contacting support on Matrix https://bisq.wiki/Matrix_bisq.chat

**Comment by DanielAndrascik** [comment]
I probably already investigated what happened.

After a longer time, I opened the BISQ and i wanted to sell some btc

I wanted to finance the business offer from the bisq wallet

However, I only had about half of the necessary funds in my bisq wallet

So I replenished my bisq wallet with a transfer from another wallet

But I entered the slow transaction

I forgot about it and created a trade offer but I still didn't have the transaction confirmed by the miners

Although the offer was created correctly, btc was requested and the caution was made with a deposit

But my offer was deactivated by itself, I believe that because some peer showed interest in it and apparently bisq found out that the reserved funds have not yet been completely confirmed by the miners

At this moment, I still had the correct balances, both available and reserved

But two days later, when the miners confirmed my initial transaction to bisq wallet, bisq declared problems and wanted to resynchronize

After finishing the resynchronization, a significant part of the reserved resources disappeared

The trade offer has been cancelled, no transfer has taken place, but my wallet balance has not recovered even after repeated resynchronisations

**Comment by darawhelan** [comment]
Thanks for extra information. The process described matches the type of occurrences that cause a wallet to get corrupted. 
Have you solved the issue? If not please support on Matrix.
