### ISSUE TITLE
Fee reimbursement for trade ﻿pKTVSqC

### ISSUE THREAD

**Issue by nerd023** [bisq-network/support#1584]
My BTC buy transaction failed and following are two (2) issues to resolve.
1. Maker fee was deducted though. Please refund maker fee to my reimbursement address, details below
2. Release security deposit as trade is failed

Screenshot:
![29-Feb-buy-err-1](https://github.com/bisq-network/support/assets/161706357/bf38fda0-a107-4d82-9c68-b35fbf102873)

Maker:  d234fee0b0661e647546911c9c623f47fba4de020ed588d36e0147ae64e48950
Taker: N/A
Deposit: N/A
BTC mining fees lost: 0.00003675 BTC
Security Deposit: 0.0015 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qwxke6mx9lvts4jdnye6yaf5l8k2sjzf9aw66y4

Error Message: An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 835350, myLockTime=835385

**Comment by darawhelan** [comment]
Hi @nerd023 

The trade was later taken by someone else and completed successfully:

https://mempool.space/tx/bca45113861164c35bb188a3091cd9bcc66ef7ac8554787369f547a7ea63bea2

There is no reimbursement needed for this trade. If you are the maker and a trade fails (and no deposit transaction is created) it remains in the offer book for another user to take.

**Comment by nerd023** [comment]
Ok thanks for researching this quickly @darawhelan
