### ISSUE TITLE
Fee reimbursement for trade JOekmcJ

### ISSUE THREAD

**Issue by bieber-t-beaver** [bisq-network/support#1585]
![Screenshot from 2024-03-02 10-12-03](https://github.com/bisq-network/support/assets/107782777/973844fc-7ee5-41e8-940f-dcb80183a4a4)

I am the maker

Maker:  f58901937b779eb1ca332d11ed9311069d38abcdfc0c4220dda2c93b13d96a3e
Taker: N/A
Deposit: N/A
BTC mining fees lost: 0.00033345 BTC
Trade fees lost, please state if BSQ or BTC: 11.14 BSQ

Bisq version: v1.9.14
BTC address for reimbursement: bc1q7we06t4yxkf2tj8r230tegj3hqfwywzc4lf08e

**Comment by darawhelan** [comment]
Hi @bieber-t-beaver 

The trade was later taken by someone else and completed successfully:

https://mempool.space/tx/0cb68d466a8ae6b2c4b5950508cade47294225fbe3c4e984e733760f606e5e63

There is no reimbursement needed for this trade. If you are the maker and a trade fails (and no deposit transaction is created) it remains in the offer book for another user to take.

**Comment by bieber-t-beaver** [comment]
@darawhelan - thanks for diagnosing.

It would've helped if the Bisq client allowed users to search by Trade ID (via the Funds -> Transactions) screen.  I did find the trade through a different screen (via Portfolio -> History).

Please close the issue.
