### ISSUE TITLE
Fee reimbursement for trade VIIKXKX8

### ISSUE THREAD

**Issue by FunnyPear23** [bisq-network/support#1586]
![failed-trade](https://github.com/bisq-network/support/assets/162730236/e77ffee4-eb45-491c-8a76-dfdaf4223577)

Maker: 0.00005950 BTC 
Taker: 0.00034959 BTC 

Maker: f43f3e5c72b098e0b6aaf6ea0634ceabbbd9a8fff13e0b610aa20222a68ab928

Bisq version: 1.9.14
BTC address for reimbursement: bc1qdp8xvw4py60vk6ax2jxwp3ppwphk84j067grt2

Other notes: I am Maker. Trade was not confirmed because of too big price difference during sync.
Please reimburse Fees.

**Comment by darawhelan** [comment]
Hi @FunnyPear23 

The trade was later taken by someone else and completed successfully:

https://mempool.space/tx/36ae7145971955f88d02e18855604e77474011cd07bcb84c87d9be36bc5a5a87

There is no reimbursement needed for this trade. If you are the maker and a trade fails (and no deposit transaction is created) it remains in the offer book for another user to take.
