### ISSUE TITLE
Fee reimbursement for trade ETMQLtDv

### ISSUE THREAD

**Issue by kuro5uke** [bisq-network/support#1587]
![image](https://github.com/bisq-network/support/assets/39413087/c6a0ec3b-cce2-4341-88e6-a0ef6be88658)

Maker:  d696f3ec779ec747d9c87acd69f25adedeaef9417b9d933b3f63a8eaf3746c4b
Taker: e9260fc0e695b315babcb6260c11a144dd783761c5005c2e7d551457c8b030c7
Deposit:
BTC mining fees lost: 0.00060858 BTC
Trade fees lost: 0.00020286 BTC

Bisq version: v1.9.14
BTC address for reimbursement: bc1qw52wfjcdhptddl8as7cg0ltj0g55yye927neg6

Other notes: Any help is appreciated.

**Comment by darawhelan** [comment]
Hi @kuro5uke 

On this trade you lost:

Miner fees: 0.00020286 BTC 
Trade fees: 2.56 BSQ

@leo816 please can you reimburse in your next batch. Thank you.

**Comment by leo816** [comment]
payout made with #1595
