### ISSUE TITLE
Fee reimbursement for trade eqdrtuf

### ISSUE THREAD

**Issue by bieber-t-beaver** [bisq-network/support#1588]
![image](https://github.com/bisq-network/support/assets/107782777/6330c353-96df-4c69-bd87-065e38e52615)

I am the Maker

Maker: d36fb80cb20f4bc9045f6ac0c858dbf2fc1c3600ee644bccfefdf62e688c2758
Taker: 30b501baccf4b23791fbc21b741cc00b9d3835fcb7ec42de44c40bb6d23850ef
Deposit: d91f6b578150e6dd8fc10ac29070b3590b021ea08d0322c5dec0bcb224b02062

BTC mining fees lost: .......... 0.00007107 BTC
Trade fees lost, please state if BSQ or BTC: 5.57 BSQ

Bisq version: v1.9.14
BTC address for reimbursement: bc1qzjqxnw5dzex488pqxga5reyhhgj2jt04x5g2a3

The deposit transaction failed to post on the BTC network.  The transaction is "invalid", according to mempool, and has been rejected.

** Thanks to darawhelan for diagnosing the problem

**Comment by darawhelan** [comment]
Hi @bieber-t-beaver 

Happy to help.

I confirm on this trade you lost:

BTC mining fees lost: 0.00007107 BTC
Trade fees lost: 5.57 BSQ

@leo816 please can you reimburse in your next batch. Thank you.

**Comment by leo816** [comment]
payout made with #1595
