### ISSUE TITLE
Fee reimbursement for trade HIGSU

### ISSUE THREAD

**Issue by bieber-t-beaver** [bisq-network/support#1589]
![image](https://github.com/bisq-network/support/assets/107782777/22a597de-f665-4d76-bc97-71972e5f8b57)

I am the Maker

Maker:  f499ba0852e2e76e868f788c6dfc67859fd8abe03541cee25bb8926492a316ca
Taker: 8ea5f8d85f2b71e5c19112d4f3df9fab0dd3b6b2aade84a61b47940db1030dcc
Deposit: 3085eb0104d39b8585944b4f694bb52c59a1077e9117c370be53c73ebb733fae
BTC mining fees lost: 0.00005390 BTC
Trade fees lost, please state if BSQ or BTC: 11.14 BSQ

Bisq version: v1.9.14
BTC address for reimbursement: bc1qd3dgwxkgfdfj2ejqruuvtr02x329ndx735k0yv

The deposit transaction failed to post on the BTC network. The transaction is "invalid", according to mempool, and has been rejected.

** Thanks to darawhelan for diagnosing the problem

**Comment by darawhelan** [comment]
Hi @bieber-t-beaver 

Happy to help.

I confirm on this trade you lost:

BTC mining fees lost: 0.00005390 BTC
Trade fees lost: 11.14 BSQ

@leo816 please can you reimburse in your next batch. Thank you.

**Comment by leo816** [comment]
payout made with #1595
