### ISSUE TITLE
Fee reimbursement for trade 35901

### ISSUE THREAD

**Issue by mateus-ferreira93** [bisq-network/support#1591]
![Screenshot from 2024-03-22 13-33-53](https://github.com/bisq-network/support/assets/164064880/e85cb955-3d13-4656-b1fb-df6adf154a1a)

Maker:  8ea09a2d0d232d15ff30e0351a20b639b9a06da4ec7c0e571e835d41ff06fca2
Taker: 2809cfdaa00a943d9bb6bfa5045bb13a5badf14619723a00727061a3271dfc04
Deposit: d0557ae2213bffbddc7cec6c06def3f9abbcee460a9f6418ed979fe1a5c03f51
BTC mining fees lost: 0.00019567 BTC

Bisq version: v1.9.14
BTC address for reimbursement: bc1qzfa75hkcsy0w3ru3wzygd52mz8d8zukuqml4zj

**Comment by darawhelan** [comment]
Hi @mateus-ferreira93 

This trade did not fail. 

It is a false error message.

@leo816 and @pazza83 

Do either of you have trade ID: 35901 in your meditations?

**Comment by leo816** [comment]
@mateus-ferreira93 please answer your mediation ticket (if you can't see it please click on the trade and do cmd + o)

**Comment by mateus-ferreira93** [comment]
Good morning, thank you for your reply. I'm not exactly sure about what happened, but I had an issue when transferring to the BISQ wallet to initiate a transaction. This transaction not only didn't happen, but also the withdrawal of funds from the BISQ wallet has not been processed yet. Can you suggest what to do? The bitcoin purchase would happen on March 18th, and the withdrawal of funds from the wallet would happen on March 20th.

**Comment by darawhelan** [comment]
Hi @mateus-ferreira93 if you do not have the trade in mediation please reach out to leo816 on Matrix.

https://bisq.wiki/Matrix_bisq.chat

Leo's user name on Matrix is `@leo816:matrix.org`
