### ISSUE TITLE
Fee reimbursement for trade 7vopn

### ISSUE THREAD

**Issue by pfornaroli** [bisq-network/support#1592]
![image](https://github.com/bisq-network/support/assets/58956367/9400616a-0eeb-44d9-93c9-fd87e7c43239)

Maker:  ee4658b8a6c1fbd0676d8b00151244e083aac73c7fdd4c1d744265e3b325317d
Bisq version: v1.9.14
BTC address for reimbursement: 198LumPBwJ1oce8W62VjzpENscaD5YJM3f

Please reimburse fees.

**Comment by darawhelan** [comment]
Hi @pfornaroli 

As the taker you did not lose funds on this trade as there was no taker transaction.

Your wallet might be out of sync. You should do an SPV resync: https://bisq.wiki/Resyncing_SPV_file
