### ISSUE TITLE
Fee reimbursement for trade 894687

### ISSUE THREAD

**Issue by a1denvalu3** [bisq-network/support#1594]
![Screenshot from 2024-03-26 21-09-45](https://github.com/bisq-network/support/assets/43107113/3ed3835c-eb83-4cc6-94f2-c64502948d4e)

Maker:  cc2defd19c8f24270daaf4c1b976f9cd84d817913c55028316a42c3e51d98830
Taker: 4da147a720ae3e635b7ca2367f6319e0969755047063ae357dc76e10e3d97208
Deposit: N/A
BTC mining fees lost: 0.00002640 BTC
Trade fees lost:  0.00008175 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qsd7t9zq52u0kdenufcqcrjquq7l2l9c0fqprnj

Notes:
Taker probably had to perform a SPV resync before taking the offer.

**Comment by darawhelan** [comment]
Hi @lollerfirst 

I confirm on this trade you lost a total of **0.00010815 BTC**

@leo816 please can you add to your list for reimbursement. Thank you

**Comment by leo816** [comment]
payout made with #1595
