### ISSUE TITLE
Fee reimbursement for trade yJ9Gm4

### ISSUE THREAD

**Issue by Ondrasak3** [bisq-network/support#1596]
![Snímek obrazovky 2024-04-02 121803](https://github.com/bisq-network/support/assets/79156927/82e2cdc7-7b32-4a8f-a28c-2c4bd891642e)

Maker:  fe87c27f6c550b41361e85b748c962fd9bceb4e086131c657b8feb787a9ef9e9
Taker: 1b011125912e6205073328f7ffc1402f287080479771cceb3d2996df812c9a66
Deposit: 
BTC mining fees lost: 0.00008604 BTC
Trade fees lost, please state if BSQ or BTC: 0.97 BSQ

Bisq version: 1.9.14
BTC address for reimbursement: bc1q95asu3l3jzkmgjprkn4cda63z8z9q4en4gfrce

Other notes:

**Comment by darawhelan** [comment]
Hi @Ondrasak3 

On this trade you lost

BTC mining fees lost: 0.00002868 BTC
Trade fees lost, please state if BSQ or BTC: 0.97 BSQ

@leo816 please can you add to your next batch for reimbursement.

**Comment by leo816** [comment]
payout made with #1623
