### ISSUE TITLE
Fee reimbursement for trade pzotwy

### ISSUE THREAD

**Issue by bowtiedstack** [bisq-network/support#1601]
![Screenshot 2024-04-03 at 08 56 25](https://github.com/bisq-network/support/assets/130357382/bc610eaa-df13-4e82-970d-524b3f09fc74)

Maker: `5891b60ee739a37a0c2b3095de080db78e7ec511a75e3a813e3189ea21d986fb`

The transaction failed, I'd like any applicable fees reimbursed. Thanks!

Bisq version: 1.9.14
BTC address for reimbursement: `bc1qtez62ys7lzwq42vd3yyqddjd3w5vr9xph3h09v`

**Comment by darawhelan** [comment]
Hi @bowtiedstack 

As you where the taker you did not lose any fees as there was no taker transaction
