### ISSUE TITLE
Fee reimbursement for trade NAQP2KXQ

### ISSUE THREAD

**Issue by cybrpnk192984** [bisq-network/support#1603]
![1](https://github.com/bisq-network/support/assets/166520499/6f966419-f623-42aa-b423-91bffdaf559f)

Maker:  c2211981b311d455d6a01d410c464f9871e93deec399aa35eb6ae57e3998fb68
Taker: 53cd47a38b119dfacbd7591b1c5de0d83eb10a6a60753032d433cfdb54ebc769
Deposit: n/a
BTC mining fees lost: 0.00005126 BTC
Trade fees lost: 0.00033235 BTC

Bisq version: 1.9.14
BTC address for reimbursement: bc1qw3nqekfpsytz0q55mrwqgux7f6lu2a3ada2l52

**Comment by darawhelan** [comment]
Hi @cybrpnk192984 on this trade you lost a total of **0.00038361 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
payout made with #1623
