### ISSUE TITLE
Fee reimbursement for trade CcLtcUg

### ISSUE THREAD

**Issue by davidg47** [bisq-network/support#1604]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  d6384c15c9e6ba7ef56c81b20ce7ce8f1100124fadd78d29d555431dd100f0e9
Taker: 
Deposit: 0.0025 BTC
BTC mining fees lost:   0.00066405 BTC
Trade fees lost is  0.0025 BTC.

Trade ID:  CcLtcUg-7eafcfed-b81b-40b7-a036-459ef2b670d9-1914

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:  v1.9.14
BTC address for reimbursement:  bc1qn6ugzva2t3x732t5g534f594lzw0ggldkpyhfm

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @davidg47 

Please can you edit the post to include the trade screenshot
