### ISSUE TITLE
Fee reimbursement for trade 3V6q4E

### ISSUE THREAD

**Issue by michelMoteam** [bisq-network/support#1606]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://github.com/bisq-network/support/assets/7152298/e25b55fd-1f66-44b2-ba6d-5f511fee321d)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  03ae4987ef8defe29a955bc68163f04fe2c6dd37e55ee763785a5041784b8e89
Taker: a655402e41811fd4c5036e77b8e8902e5dfdec5557ce3fcf9af35b3ffe0fe0c5
Deposit: 437529bab9a0ab86ba8ecac944a4e8cc7df125549219dcb844353b899662b57c
BTC mining fees lost: 0.00023625
Trade fees lost: 0.00215693 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.15
BTC address for reimbursement: bc1qp50k65wemq3eakcdyk29rtq2kcrkrlhq75gn5u

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @michelMoteam 

This trade did not fail.

The funds are in the multisig.

You should open mediation for this trade.

Please make sure the trade is in your open trades and then select the trade and press 'Ctrl' and 'O' to open mediation.

**Comment by michelMoteam** [comment]
Hi @darawhelan 

The trade did fail and i lost the funds, here is what was written about the trades on top of the above:

I didn't lose the security deposit but i lost the miner and trade fees, and that is why i request a refund.
Also, mediation was not possible, only fail trade was an option and it has been a week that the trade is failed and closed now.

![Screenshot 2024-04-17 215650](https://github.com/bisq-network/support/assets/7152298/79024319-25dc-4ae2-8487-0dc3565fd3b5)

**Comment by darawhelan** [comment]
Hi @michelMoteam 

The trade is still able to be completed. It did not fail. Unfortunately Bisq is giving you a false error. 

Please open mediation for the trade and the mediator will be able to assist you.

**Comment by michelMoteam** [comment]
Hello @darawhelan 
Indeed, it was a false error and got it resolved through mediation. Thank You for your help!
