### ISSUE TITLE
Fee reimbursement for trade lKPkuIpA

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1607]
![image](https://github.com/bisq-network/support/assets/63785272/152b9d20-2728-44b7-b460-91b781ce94df)

Maker:  11481ede1c58278e8e446a150304b4b4e14ba405822c610e454d9cbae7704076
Taker: c2ea13a76742b348a9d032063546f456d982d08e2eb23a2f4cb623270e211def
Deposit: N/A
BTC mining fees lost: 0.00027440 BTC
Trade fees lost, please state if BSQ or BTC: 4.83 BSQ

Bisq version: 1.9.15
BTC address for reimbursement: bc1qdy3nshuevr6878440cy9dz2cdmv37s98sujtw3

Other notes: None

**Comment by darawhelan** [comment]
Hi @Akira45-0 

I confirm on this trade you lost:

BTC mining fees lost: 0.00027440 BTC
Trade fees lost, please state if BSQ or BTC: 4.83 BSQ

@leo816 please can you add to this list for reimbursement

**Comment by leo816** [comment]
payout made with #1623
