### ISSUE TITLE
Fee reimbursement for trade 79659678

### ISSUE THREAD

**Issue by BohGit** [bisq-network/support#1608]
![bild](https://github.com/bisq-network/support/assets/168065932/c4c0944a-67d2-4472-80c8-2988e955bfc3)

Maker:  a17d15e941e95b393e9f6ed5a7b92a2805b2041e455f9f5c0ac57ec50da9159a
Taker: 3c6adbd26281249f5aabfac330fc4b2bbabcfa3e4873a40ab06ec2f9cf7d830c
Deposit: N/A
BTC mining fees lost: I am a bit unsure. As per the screenshot above, it states "Mining fee [...] Taker: 0.00257232 BTC". However, checking transactions log in Bisq, I see an amount of 0.00102419 BTC, see below screenshot.
Trade fees lost, please state if BSQ or BTC: None, I think.

![bild](https://github.com/bisq-network/support/assets/168065932/310d16b2-96ad-4266-999e-17cba1142846)

Bisq version: v1.9.15
BTC address for reimbursement: bc1qrqlwyyrmtu80gv2rgp25gl0vd58d3guu5sls8p

**Comment by darawhelan** [comment]
Hi @BohGit 

On this trade you lost:

Mining fee: 0.00085744 BTC
Trade fee: 0.00016675 BTC

Total: 0.00102419 BTC

@leo816  please can you add to your list for reimbursement.

**Comment by leo816** [comment]
payout made with #1623
