### ISSUE TITLE
Fee reimbursement for trade 826104

### ISSUE THREAD

**Issue by ataraxia76** [bisq-network/support#1609]
![trade](https://github.com/bisq-network/support/assets/168236480/7efb440b-e546-42c6-ae1a-016d75edae2c)

Maker:  d45673ad185b4faf9e1fb2920314e420acacbfdaaf700f3549cc3092158cc9fa
Taker: a3664da0ec07b84da8251b1a90ca0f3ffe5ebddf11fce2cfb5882c4c8743d915
Deposit: 0.00512083 BTC
BTC mining fees lost: 0.00027960 BTC
Trade fees lost, please state if BSQ or BTC: 0.00009320 BTC

Bisq version: v1.9.15
BTC address for reimbursement: bc1q8306y075ep863r77p3e9l6m4tnx7n745gl4s45

Other notes:

i suppose maker's node was out of sync. thank you!

**Comment by darawhelan** [comment]
Hi @ataraxia76 

On this trade you lost

BTC mining fees lost: 0.00009320 BTC
Trade fees lost, please state if BSQ or BTC: ‎0.00016445 

**Total: 0.00025765 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
payout made with #1623
