### ISSUE TITLE
Fee reimbursement for trade gXIooAcY

### ISSUE THREAD

**Issue by Muggy123** [bisq-network/support#1611]
![image](https://github.com/bisq-network/support/assets/168389147/3fa9721e-81fd-487e-a811-b01924fc201c)

Maker: 8178dbba336b0d4da50417b8de7354fd0b019e2d670e73accb75c77a7d8323b0
Taker: 7cd888e3d863917db33ed5242af2ce08eac925987c9a729832fd25346dcb666a
Deposit: 0.0150 BTC
BTC mining fees lost: 0.00005359 BTC
Trade fees lost, please state if BSQ or BTC: 0,00115000 BTC 

Bisq version: v1.9.15
BTC address for reimbursement: bc1qxuztdkfnkdfef782ep83dlckfuxcjcjmy50r39

Other notes:

not sure why the transaction failed, i'm new in the platform. thank you.

**Comment by darawhelan** [comment]
Hi @Muggy123 

On this trade you lost a total of:

**0.00120359 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
payout made with #1623
