### ISSUE TITLE
Fee reimbursement for trade 593996

### ISSUE THREAD

**Issue by ataraxia76** [bisq-network/support#1612]
![image](https://github.com/bisq-network/support/assets/168236480/a0d0b38d-f5f8-4c6f-8f0e-7b07c20e8db7)

Maker:  244512e8ad8614592c71d8e9ac0bce55fca100f15baf6dab302fde15a83c7e7e
Taker: 6df13ce046b2fdf83d77bfd6368cc8d0049c48c35155cd508562c8680b740ca9
Deposit: 0.005
BTC mining fees lost: 0.00020271 BTC
Trade fees lost, please state if BSQ or BTC: 0.00006757 BTC

Bisq version: 1.9.15
BTC address for reimbursement: 

Other notes: second time in a row this happened. error message: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

what can I do to prevent this? 

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by ataraxia76** [comment]
BTC address for reimbursement: bc1q5pkun5fpj6qqlmza0y7gn8gx3cu3w889ezwm43

**Comment by darawhelan** [comment]
‎Hi @ataraxia76 

On this trade you lost:

Miner fee: 0.00006757 BTC
Trade fee: 0.00017250 BTC

**total: 0.00024007 BTC**

@leo816 please can you make a reimbursement in your next batch.

@ataraxia76 please check your DAO in in consensus by going to DAO > Network > Monitor

**Comment by leo816** [comment]
payout made with #1623
