### ISSUE TITLE
Fee reimbursement for trade 593996

### ISSUE THREAD

**Issue by Switcheroo56** [bisq-network/support#1613]
![Screenshot from 2024-04-29 19-35-08](https://github.com/bisq-network/support/assets/168495220/e57a14a4-233b-427e-95cc-8fda1f78fb2a)

Maker:  244512e8ad8614592c71d8e9ac0bce55fca100f15baf6dab302fde15a83c7e7e
Taker: 6df13ce046b2fdf83d77bfd6368cc8d0049c48c35155cd508562c8680b740ca9
Deposit: N/A
BTC mining fees lost: 5,600 sat

Bisq version: 1.9.15
BTC address for reimbursement: bc1qmx3l9v64l8hxcz60l9ar4vk2ped9p63rg60ahp

Other notes:
"Timeout reached. Protocol did not complete in 120 sec." error. Please reimburse fees.

**Comment by darawhelan** [comment]
‎Hi @Switcheroo56 

On this trade you lost:

Miner fee: 0.00005600 BTC
Trade fee: 0.00005000 BTC

**total: 0.00011000 BTC**

@leo816 please can you make a reimbursement in your next batch.

@Switcheroo56 please check your DAO in in consensus by going to DAO > Network > Monitor

**Comment by leo816** [comment]
payout made with #1623
