### ISSUE TITLE
Reimbursement for trade VVNEYSMH-d3cb12f0-b5dd-47ea-8bba-0d964acf5d8b-1914

### ISSUE THREAD

**Issue by hgeral** [bisq-network/support#1615]
* full trade ID
*      VVNEYSMH-d3cb12f0-b5dd-47ea-8bba-0d964acf5d8b-1914
* dispute details: what happened
*      The BUYER never made the payment nor responded to mediation. After the mediation the arbitrator also never replied to me (I waited more than 5 days).
*  (arbitrator: https://matrix.to/#/@refundagent2:matrix.org)
* 
* GitHub handle of mediator:
*   MEDIATOR: @pazza83 (https://matrix.to/#/@pazza83:matrix.org)
*   ARBITRATOR: @refundagent2 (https://matrix.to/#/@refundagent2:matrix.org)
* 
* any other details that would help to convince bisq stakeholders that your request is a legitimate one
   TXID OF TIMELOCKED TRANSACTION: 9a721e6cbf6f2d0961a23505a875d1d52728b8171fb60e250b1e8697ee9a7841
   
There was also an error encountered:

An error occurred at task: SendMediatedPayoutSignatureMessage
Sending message failed: message=MediatedPayoutSignatureMessage{
     txSignature=304402205a4c927f3daeda2d322e24e57c9f625c1622dd42436e8621e316edfa95c1786d02207b4833c686d0ebfa9ca306357ab4ec029d8bc969e6e235e0480a3f75564f1a69,
     tradeId='VVNEYSMH-d3cb12f0-b5dd-47ea-8bba-0d964acf5d8b-1914',
     senderNodeAddress=5bhsu2jou7yjzlah3azrjfcnd4aixp3bnocmapzzwgyshcqrgunjlxqd.onion:9999
} TradeMailboxMessage()
errorMessage=There are no P2P network nodes connected. Please check your internet connection.
There are no P2P network nodes connected. Please check your internet connection.

**Comment by darawhelan** [comment]
@hgeral 

Are you the buyer or seller for the trade?

Have you responded to the arbitrator for reimbursement? The trade went to arbitration so the first step for reimbursement for you is from communicating with the arbitrator.
