### ISSUE TITLE
Fee reimbursement for trade xyekusa

### ISSUE THREAD

**Issue by Plsaipe** [bisq-network/support#1616]
<img width="853" alt="Captura de Tela 2024-05-15 às 09 50 21" src="https://github.com/bisq-network/support/assets/122633175/1954228f-1cc1-468f-961e-6718e50e395e">

Maker:  309d52ca57f788539dfefa3fa44a439fdd9fcc740a610f4d7f7b0d9d9ea69ae9
Taker: 58e46aa33eec658d372dfcf6a8e75d3cb120fb99bfec8e0830c735c6ff90422d
Deposit: N/D
BTC mining fees lost: 0.00003262 BTC
Trade fees lost, please state if BSQ or BTC: 0,00013800 BTC

Bisq version: v1.9.15
BTC address for reimbursement: bc1qug4dfe7vsrsfancns3aulpsacc3hu7ua4xwdmr

Other notes:

Error: An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Exception message: TxIds of buyersPreparedDelayedPayoutTx and sellersPreparedDelayedPayoutTx must be the same.

TAKER_FEE_PUBLISHED

**Comment by darawhelan** [comment]
Hi @Plsaipe 

On this trade you lost:

Mining fee: 0.00003262 BTC
Trade fee: 0.00013800 BTC

**Total: 0.00017062 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
payout made with #1623
