### ISSUE TITLE
Fee reimbursement for trade TIQuYve

### ISSUE THREAD

**Issue by oelf12** [bisq-network/support#1618]
![bisq1-fehler-258eu-franze-bisq-screenshot](https://github.com/bisq-network/support/assets/64707887/77a26bd0-4e22-4107-9c95-d394cafb83a7)

Handel:
Sie sind: BTC Käufer (Abnehmer) / Ersteller ist: BTC Verkäufer
BTC-Betrag erhalten: 0.0042 BTC
EUR Betrag ausgeben: 258 EUR
Handelspreis: 61498.0936
Zahlungsmethode: SEPA

Details:
Handels-ID: TIQuYve-094d5262-06f4-4f4e-a3b2-0772d6f59867-1915
Handelsdatum: 19.05.2024 16:21:35
Deposit: Käufer: 0.0010 BTC / Verkäufer: 0.0010 BTC
BTC mining fees: Ersteller: 0.00004906 BTC / Abnehmer: 0.00007170 BTC
Trade fees lost, please state if BSQ or BTC: XXX? BSQ ?? - cant find fees anywhere

Onion Adress seller: v6rj6roa5t7ycal3hs7hzdp6n7qnuogdgu2fbb6izatawebpm6o4ebad.onion:9999
Transaction-ID fees from seller: 9c62da2aa3d6ea321118caa8290225fa3a8014fb33747f3092a8c0ddafb887f2

Bisq version: 1.9.15
BTC address for reimbursement: bc1qe3ns97rarn8zl38rrpcnds5wthc58yxsalkn2g

Error message.:
An error occurred at task: CreateTakerFeeTx
Exception message: Insufficient BSQ,  missing 0.6 BSQ

Other notes:
My comment: but I have 31.85 BSQ... missing on sellers side?

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @oelf12 

As you are the taker and there is no taker transaction ID you did not lose any funds on this trade as no transaction was created
