### ISSUE TITLE
Fee reimbursement for trade 969382

### ISSUE THREAD

**Issue by sukiwa** [bisq-network/support#1619]
TradeID: 969382-20be1580-516e-416c-a947-0399c1be7d33-1915

SCREENSHOT HERE
![Screenshot at 2024-05-17 13-57-52](https://github.com/bisq-network/support/assets/36377452/266783d7-e655-4ddb-8ee0-383333452075)

![Screenshot at 2024-05-17 09-59-37](https://github.com/bisq-network/support/assets/36377452/e015c6cc-6529-4d8c-b3b3-1a8d7c7024e2)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  831c8d9a58b2eaf4a580dc5878e12db4696f348a4059d97a53aa39780be47741
Taker:  fa736f9b89b2335783a95abd343d43b6fedac8243a516e0e2bbc656645eaf589
Deposit: N/A - The deposit transaction (the 2-of-2 multisig transaction) is missing

BTC mining fees lost: 0.00009087 BTC
Trade fees lost:  0.000115 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.9.15
BTC address for reimbursement: bc1q5pl65lg77unhglkgzjvjd4v3ejjsxxuya3q57s

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @sukiwa 

On this trade you lost:

Miner fee: 0.00003029 BTC
Trade fee: 0.00011500 BTC 

**Total: 0.00014529 BTC**

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
payout made with #1623
