### ISSUE TITLE
Fee reimbursement for trade JTAPTCIQ

### ISSUE THREAD

**Issue by Reveill3** [bisq-network/support#1620]
![FailedTrade](https://github.com/bisq-network/support/assets/38196983/7dc99160-adcd-47cb-83aa-a88a7d28d287)

Maker:  bcf28ace704449d3e059dccdca1d2cfea000624e577640a2d584ee3a13546bf1
Taker: ........
Deposit: .0015 BTC
BTC mining fees lost: 0.00001750 BTC
Trade fees lost, please state if BSQ or BTC:  0.0015175 BTC

Bisq version: 1.9.15
BTC address for reimbursement: bc1qcjs5l3j2a79qdmruq4meq9h5mu2gvx6dzmezaj

**Comment by Reveill3** [comment]
Misunderstood what i deposited. The fees were actually never taken out. All is good

**Comment by darawhelan** [comment]
@Reveill3 yes as the taker you did not lose any funds on this trade as no transaction was created.
