### ISSUE TITLE
Fee reimbursement for trade NACQSUR

### ISSUE THREAD

**Issue by a-safonau** [bisq-network/support#1624]
<img width="891" alt="image" src="https://github.com/bisq-network/support/assets/3219729/1a55db34-981b-4802-a61f-3c213125eb5d">

Maker:  fb4da405c2847abe2f477a1e257c4c7afcd79691ee2306b29e3b755bc9c41cb6
Taker: 6e322ecdab35f5622c563731879dab3f178aae44927dd422a800f1b68fe9a256
Deposit: ..........
BTC mining fees lost: 0.00015555 BTC
Trade fees lost, please state if BSQ or BTC:  0.0002875 BSQ

Bisq version: 1.9.15
BTC address for reimbursement: bc1q7wrfswn2h54mn7evrm5ma9nyjq9yl0qssm5rze

Other notes:

**Comment by darawhelan** [comment]
Hi @a-safonau 

On this trade you lost:

Miner fees: 0.00005185 BTC
Trade fees: 7.12 BSQ

@leo816 please can you add to your list of reimbursements

**Comment by leo816** [comment]
payout made with #1663
