### ISSUE TITLE
Fee reimbursement for trade 4lwie

### ISSUE THREAD

**Issue by pbr57** [bisq-network/support#1627]
<img width="439" alt="image" src="https://github.com/bisq-network/support/assets/138521530/a72af631-f301-4439-9d40-ca0a47069b7b">

Bisq version: v1.9.15
BTC address for reimbursement: bc1q7luggmlc32dl5nf6p95nqd5fym3tmv2uvvl6kg

**Comment by darawhelan** [comment]
Hi @pbr57 

Please can you copy and paste the maker and taker transaction IDs
