### ISSUE TITLE
Fee reimbursement for trade m7jdvh8

### ISSUE THREAD

**Issue by behodl** [bisq-network/support#1629]
SCREENSHOT HERE
<img width="798" alt="Screenshot 2024-06-08 at 09 45 52" src="https://github.com/bisq-network/support/assets/87386449/4086e021-701c-422e-8e84-f7dde4b5eff9">
<img width="871" alt="Screenshot 2024-06-08 at 09 46 15" src="https://github.com/bisq-network/support/assets/87386449/7cdb961c-9882-439b-8a84-752052d16847">

Maker:  51f7d698e7025799536e9e7e72d2f7da5edb7bab6457b29b8f2363ca62af7ea6
Taker: 83bf834c4d52debb865c35ac4a2cd809335a5cf98b8b7c6642c879a8360cd92f
Deposit: 1c1a5da6773b4354aa097a08cc0cbbf5c93b444db5e8f900bd8013d26e3e4af0
Trade fees lost, please state if BSQ or BTC: 0.001350 BTC

Bisq version: v.1.9.15
BTC address for reimbursement: bc1q750dg0zjf99x4v8lte8c0rytpzlpz9h7sndmra

Other notes:

Seller sent this message – the transaction has disappeared from the block explorer. "I speed up from electrum (increase fee) now dissapear from deposit transaction ID. Any ideas how to fix never had this problem before."

**Comment by darawhelan** [comment]
Hi @behodl 

This trade failed.

You lost a total of 0.00041805 BTC

@leo816 please can you reimburse in your next batch.

**Comment by leo816** [comment]
payout made with #1663
