### ISSUE TITLE
Fee reimbursement for trade YMDOQYXS

### ISSUE THREAD

**Issue by bisquser99** [bisq-network/support#1631]
![screen](https://github.com/bisq-network/support/assets/171730560/16a38dea-6cdb-4f4f-97e6-c99bb3c8aeab)

Maker:  2a485a9820de2ae47b744a12e687041e31342d84fc990cee0caa50df6c6bdc2e
Taker: a0c0740b04be2861b6e868695a23c199540ddec926f3eb41908bcd4874a2e9b4
Deposit: 05ffcebff373fdd1b046d8c87b0aa465603c72f3da1b4fc8bc94231ed664a6e2
BTC mining fees lost: 0.00006370 BTC please state if BSQ or BTC: .......... eg 5.43 BSQ or  0.000088 BTC
Trade fees lost:  0.74 BSQ

Bisq version: v1.9.15
BTC address for reimbursement:  bc1q4lq5c7nu7mq2h3hx6ffk28t63xe2xce3nfmzs6

Other notes:

Hello, I am a new trader on Bisq so it took me a while to figure out what was happening and how to request a refund.  The trade was taking several days so I looked up the taker transaction in a block explorer and it had failed.  Thanks for your help!

**Comment by darawhelan** [comment]
Hi @bisquser99 

On this trade you lost:

Mining fees: 0.00006370 BTC
Trade fees: 0.74 BSQ

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Payout made with #1663
