### ISSUE TITLE
Fee reimbursement for trade MPumh

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#1633]
![image](https://github.com/bisq-network/support/assets/63785272/ab383b69-75ed-4fd9-9a23-4b7b6c84d371)

Maker:  50e0cda60e9291ece27f949378297b17370a649267197eba688c96dbb1fd1311
Taker: 9ee7666a5ec2e54a0eb8b63ecdcf3116826cf554a3839788ea0c2170d9559d8a
Deposit: 
BTC mining fees lost: 0.00009065 BTC
Trade fees lost, please state if BSQ or BTC: 2.56 BSQ

Bisq version: 1.9.15
BTC address for reimbursement: bc1qe4ajrtzhglyh9m44r9py68wc84a45tjzvg5hvg

Other notes: None

**Comment by darawhelan** [comment]
Hi @Akira45-0 

On this trade you lost

Mining Fees: 0.00009065 BTC
Trade Fees: 2.56 BSQ

@leo816 please can you add to your list for reimbursements

**Comment by leo816** [comment]
Payout made with #1663
