### ISSUE TITLE
Fee reimbursement for trade apffg5

### ISSUE THREAD

**Issue by ONC420** [bisq-network/support#1634]
![Screenshot 2024-06-15 040322](https://github.com/bisq-network/support/assets/172893178/2f9ae1e3-83c0-47fc-a45b-c86972def02b)

Maker: 5e21b4bb45a73fb85d8426213142a44baba4bff9db9e8c1aba68f9c51cd597eb
Taker: 5248da30de63c14f4cb1d5e9b4da956ca98de186168f219208b31beb98ea7de5

Mining fees lost: 0.00027612 BTC
Trade fees lost: 0.00020704 BTC

Bisq version: 1.9.15
BTC address for reimbursement: bc1qgtgay5tjsrhj3lujn2yghh89e6nuv0889zkfu9

**Comment by darawhelan** [comment]
Hi @ONC420 

On this trade you lost a total of: 0.00020704 BTC

@leo816 please can you reimburse in your next batch payment

**Comment by leo816** [comment]
Payout made with #1663
