### ISSUE TITLE
Fee reimbursement for trade SnlZctc

### ISSUE THREAD

**Issue by ONC420** [bisq-network/support#1636]
![Screenshot 2024-06-15 234740](https://github.com/bisq-network/support/assets/172893178/5f400089-e9aa-471d-99fb-72b28fcd5107)

Maker: 925af17d0fcf8d6a53d98a0b406e745adb784f59218334fdd9ea512c0b6ce192
Taker: 8fcd16cc35d405e642e0de7c5913bf740af3ec314ae0c6b267e2c2b2257cb87a
Deposit: N/A
BTC mining fees lost: 0.00012584 BTC
Trade fees lost: 0.00015694 BTC

Bisq version: 1.9.15
BTC address for reimbursement: bc1qgtgay5tjsrhj3lujn2yghh89e6nuv0889zkfu9

**Comment by darawhelan** [comment]
Hi @ONC420 

On this trade you lost: 0.00015694 BTC

@leo816 please can you add to your next batch of reimbursements

**Comment by leo816** [comment]
Payout made with #1663
