### ISSUE TITLE
Fee reimbursement for trade SKQ7Ojx

### ISSUE THREAD

**Issue by tamerhijjawi** [bisq-network/support#1637]
![Capture-11](https://github.com/bisq-network/support/assets/30754380/bbaea63a-dc20-4a91-a359-8fa90d9d6692)

Maker:  5e902e415260129ed8a04d4d2e1c35d5e2b86ef2d6557d7104d267f5edef5663
Taker: 3374000bd17b850ba67608cb6fe30096186489adb313db3a94c46823e9b94244
Deposit: NA
BTC mining fees lost: 0.00009912 BTC
Trade fees lost, please state if BSQ or BTC: 0.00023000 BTC

Bisq version: 1.9.15
BTC address for reimbursement: bc1q5y4uh45f7jgcqnjmnujm2lmwjk3jzkagz8pqn8

**Comment by darawhelan** [comment]
Hi @tamerhijjawi 

On this trade you lost a total of 0.00026304 BTC

@leo816 please can you reimburse in your next batch

**Comment by leo816** [comment]
Payout made with #1663
