### ISSUE TITLE
Fee reimbursement for trade mwVrs

### ISSUE THREAD

**Issue by Blast2056** [bisq-network/support#1638]
![image](https://github.com/bisq-network/support/assets/173238384/3278b4ae-bfd2-44e9-8c01-4edfecaae483)
![image](https://github.com/bisq-network/support/assets/173238384/2927b25b-7e99-4f85-b36b-07d48a25c802)

Maker:  337471f7827e167707d82f25e59e71a7e173a440ff38d723d791d4b8ffb616ce
Taker: 783d52bf00320365e0554406a95eef71f9aea6749db648d56a80121c9569a9a1
Deposit: 0.0015 BTC
BTC mining fees lost: 0.00018636 BTC

Bisq version: 1.9.15
BTC address for reimbursement: bc1qj99483rumufmxuw3vl6csnr0jckcz49z9rgk9r

**Comment by darawhelan** [comment]
@Blast2056 

As you were the taker and there was no taker transaction, you have not lost any fees on this trade.

Please make sure your wallet is correctly synced if this issue happens again.

https://bisq.wiki/Resyncing_SPV_file
