### ISSUE TITLE
Fee reimbursement for trade 33901326

### ISSUE THREAD

**Issue by Ven32123** [bisq-network/support#1639]
![Screenshot (360)](https://github.com/bisq-network/support/assets/151437769/8acd5530-c3b6-44bf-a8ae-672fc3de12ed)

Maker: 2689c975993f844d877b5181c92c4e7218e40af70c8b2ce6e7b97adeabbf55ae
Taker: b627f75abdf3ffd4e5af44f83437338d2049d55be43d6934d0c73cb59295d176
Deposit: n/a

BTC mining fees lost: 0.00021 BTC
Trade fees lost: 0.84 BSQ

Bisq version: v1.9.15
BTC address for reimbursement: bc1qahm8yesat79lud6e6nu2k2rft8gekftrwklvt2

Other notes:

**Comment by darawhelan** [comment]
Hi @Ven32123 

This trade should still be in your open offers for another user to take.

Can you see this trade in your open offers?

**Comment by Ven32123** [comment]
![Screenshot (364)](https://github.com/user-attachments/assets/5abc6679-b0e3-4d2a-b654-8ac08f6a0bd9)
![Screenshot (365)](https://github.com/user-attachments/assets/ae463679-32d1-443e-a495-8fc35d609bfe)

If I move it to my open trades, I can't move it to My Open Offers.  All it tells me to do is move it to failed trades.

**Comment by darawhelan** [comment]
Ok, move it to failed trades.

On this trade you lost:

BTC mining fees lost: 0.00005145 BTC
Trade fees lost: 0.84 BSQ

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
Payout made with #1663
