### ISSUE TITLE
Fee reimbursement for trade 85758

### ISSUE THREAD

**Issue by Bunwa01** [bisq-network/support#1640]
<img width="884" alt="failed-trade-85758" src="https://github.com/bisq-network/support/assets/173291817/c97b3270-2a5d-41ee-8909-ebe6818d7681">

Maker:  b9cda4712cb687763e5ab5e54dd2ed83d4c4426bb527b1709217c9ddbafab28d
Taker: 59ffcd38d94d2f9e9581b69261055bf35035210d925a38f0d59d978d331bf39e
Deposit: n/a
BTC mining fees lost: 0.000062 BTC
Trade fees lost: 0.06 BSQ

Bisq version: 1.9.15
BTC address for reimbursement: bc1ql9x8lwgtrqpm3zyuuvz3r0w8ajrj2w3rxnm4eq

**Comment by darawhelan** [comment]
Hi @Bunwa01 

On this trade you lost:

BTC mining fees lost: 0.000062 BTC
Trade fees lost: 0.06 BSQ

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
Payout made with #1663
