### ISSUE TITLE
Fee reimbursement for trade joFQpsx

### ISSUE THREAD

**Issue by Bunwa01** [bisq-network/support#1641]
<img width="888" alt="failed-trade-joFQpsx" src="https://github.com/bisq-network/support/assets/173291817/c559f512-de8a-4da6-946a-8ee3fb5234db">

Maker: 5f85a9d8f6426708d9edc4019b7e1481fb14c05690b0e45f70de1978ca39d23c
Taker: c19b8abbfcf5874d2fd6d04b37a17c2592be371c5edfb65af92a57bafe771b5e
Deposit: n/a
BTC mining fees lost: 0.000098 BTC
Trade fees lost: 0.06 BSQ

Bisq version: 1.9.15
BTC address for reimbursement: bc1ql9x8lwgtrqpm3zyuuvz3r0w8ajrj2w3rxnm4eq

**Comment by darawhelan** [comment]
Hi @Bunwa01 

I agree on this trade you lost:

BTC mining fees lost: 0.000098 BTC
Trade fees lost: 0.06 BSQ

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
Payout made with #1663
