### ISSUE TITLE
Fee reimbursement for trade V8PKX1C

### ISSUE THREAD

**Issue by bsqfees24** [bisq-network/support#1648]
![V8PKX1C](https://github.com/bisq-network/support/assets/173741545/e41e6db8-938c-4256-92dd-6432897b6628)
![V8PKX1C_BSQ](https://github.com/bisq-network/support/assets/173741545/e6ab87a0-46ef-4903-8e9f-9a3f20996717)

Maker: 691bd20ba4cc73adeeffb8eb069917d673eaab44661ddc2a5fd96fbba4ed73b2

BTC mining fees lost: 0.0000637 BTC
Trade fees lost: 22.28 BSQ
BTC address for reimbursement: bc1qpydyhrdmzpc42448tymgmckvxd4d0ajltd5ykj

Offer was cancelled due to new trade limits

**Comment by leo816** [comment]
please copy and paste the maker fee

**Comment by bsqfees24** [comment]
> please copy and paste the maker fee

isn't 691bd20ba4cc73adeeffb8eb069917d673eaab44661ddc2a5fd96fbba4ed73b2 the maker fee?

**Comment by darawhelan** [comment]
@bsqfees24 

on this trade you lost:

Miner fees: 0.00006370 BTC
Trade fees:  22.28 BSQ

@leo816 please can you add to your next batch for reimbursement

**Comment by leo816** [comment]
Payout made with #1663
