### ISSUE TITLE
Fee reimbursement for trade a4azn

### ISSUE THREAD

**Issue by bsqfees24** [bisq-network/support#1649]
![a4azn](https://github.com/bisq-network/support/assets/173741545/7a60f672-312b-482a-b287-e054ef12a4d1)
![a4azn_BSQ](https://github.com/bisq-network/support/assets/173741545/eefbd429-0b16-4f9d-a778-e7187a54dc54)

Maker: 4c01bfbf883d6090c4172857d983d6749c75978eaae3c68c1858bb3ac8031e69
BTC mining fees lost: 0.00007595 BTC
BSQ Trade fees lost:   37.14  BSQ
BTC address for reimbursement: bc1qpydyhrdmzpc42448tymgmckvxd4d0ajltd5ykj

Offer was cancelled due to new trade limits

**Comment by darawhelan** [comment]
Hi @bsqfees24 

Your loss for this trade totals

Mining fees: 0.00007595 BTC 
Trade fees: 37.14 BSQ

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Payout made with #1663
