### ISSUE TITLE
Fee reimbursement for trade NXDNFQT

### ISSUE THREAD

**Issue by bsqfees24** [bisq-network/support#1651]
![NXDNFQT](https://github.com/bisq-network/support/assets/173741545/8ccb1a32-7135-42a5-84aa-030967c52b03)
![NXDNFQT_fees_btc](https://github.com/bisq-network/support/assets/173741545/5022461f-d513-4b3e-84c4-cf9a38770f67)

Maker: f90d6b3f2b4bf4ac4881398ccb31a5c44e108d9627b0a031cb60a1dd0714f342
BTC mining fees lost: .000434 BTC
BSQ trade fee lost : none
BTC Trade fees lost:   .0018  BTC
BTC address for reimbursement: bc1qpydyhrdmzpc42448tymgmckvxd4d0ajltd5ykj

Offer was cancelled due to new trade limits

**Comment by darawhelan** [comment]
Hi @bsqfees24 

Your loss for this trade totals: 0.002234 BTC

@leo816 please can you add to your list for reimbursement.

**Comment by leo816** [comment]
Payout made with #1663
