### ISSUE TITLE
Fee reimbursement for trade BOHW6X

### ISSUE THREAD

**Issue by nv-ab** [bisq-network/support#1652]
![image](https://github.com/bisq-network/support/assets/174207279/3c879f05-3475-469e-9798-fb8c3e610454)

Maker: 1e431ece1bda60bb15621f4132575aa5ba292c35dd5f1397093ae8a4a4bb448d
Taker: 8c543b269dd5e0534a3436ffcad5ed781e517960a1e62e94f0a3153f7c423d49
Deposit: 0.001964 BTC
BTC mining fees lost: 0.00025164 BTC
Trade fees lost, please state if BSQ or BTC: 0.00008388 BTC

Bisq version: v1.9.16
BTC address for reimbursement: bc1qdkss7zahsns4ejc29rqklvz6a23lz7l7cmkqc4

**Comment by darawhelan** [comment]
Hi @nv-ab 

On this trade you lost a total of: 0.00019888 BTC

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
Payout made with #1663
