### ISSUE TITLE
Fee reimbursement for trade MPMZL

### ISSUE THREAD

**Issue by nv-ab** [bisq-network/support#1653]
![image](https://github.com/bisq-network/support/assets/174207279/247f1c51-273f-4667-a822-c70f0aa4d5b1)

Maker: 531c00773f89b3ff17e2f10b4b5e63e34c0c168004c5b80f4995872e728c394e
Taker: dc8323785c89df181bcdaef7b39fc6719ce439efe853476bc4ba95c93f14f062
Deposit: 0.0010 BTC
BTC mining fees lost: 0.00013980 BTC
Trade fees lost, please state if BSQ or BTC: 0.00004660 BTC

Bisq version: v1.9.16
BTC address for reimbursement: bc1qmc93jrsy9nw4zwr8a5dsl7pdwswrw0y24n0m8l

**Comment by darawhelan** [comment]
Hi @nv-ab

On this trade you lost a total of: 0.00010065 BTC

@leo816 please can you add to your list for reimbursement

**Comment by leo816** [comment]
Payout made with #1663
