### ISSUE TITLE
Fee reimbursement for trade qnyvc

### ISSUE THREAD

**Issue by uskrusader** [bisq-network/support#1658]
![Screenshot from 2024-07-08 22-40-55](https://github.com/bisq-network/support/assets/77032141/a0a5af47-a768-4386-8754-003369755b11)

I am buyer/maker ==>  offered to buy
qnyvc-6f7e4668-e61d-4dce-940c-61380a9c4ed0-1917
security: Buyer: 0.003030 BTC / 
mining fee: Maker: 0.00002450 BTC / 

BSQ trading fee: ??  
https://bisq.mempool.emzy.de/tx/17830afb05971c6fc38bd2095dfdbb011a51b2a0a48ee64cab2784119f36d474
Error loading Bisq transaction
200: Transaction is confirmed but not available in the Bisq database, please try reloading this page.

Bisq version: v1.9.17
BTC address for reimbursement: bc1quaysaxq0ajfha33w60r4np5rpyxm6xn50wm428

Other notes:
I can't find what my BSQ trade fee was using instructions in app/website link

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by darawhelan** [comment]
Hi @uskrusader 

This trade failed. 

It should be still available in your open offers for another user to take. Is is there?

**Comment by uskrusader** [comment]
It is not in "open offers".  
It is in "open trades"

I have not moved it to "Failed" yet.
waiting for reimbursement?

**Comment by darawhelan** [comment]
Ok, in that case you lost on this trade:

Miner fee: 0.00002450 BTC 
Trade fee: 0.19 BSQ

> Other notes: I can't find what my BSQ trade fee was using instructions in app/website link

It is an issue with the BSQ explorer used, it is no longer being updated

@leo816 please can you add to the list for reimbursement

**Comment by leo816** [comment]
Payout made with #1663
