### ISSUE TITLE
Fee reimbursement for trade BVPXNGM

### ISSUE THREAD

**Issue by blob42** [bisq-network/support#1692]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![20241113_12h36m07s_grim](https://github.com/user-attachments/assets/a22421e4-7606-45d6-be80-2ab9c2254b3b)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  b04c91df5a1155fddba197ce75162741e22ab64bd57f424be478da789344ac7f
Taker: c75ce4633b887726fe6bee6f4b4f720942c1e82117a08bd2e14c4fa364e0da5c
Deposit: a95a49809511af2045b08bad5ca305fad5478f7342f7d8e85d0ebb4094479807
BTC mining fees lost: 0.0050 BTC
Trade fees lost, please state if BSQ or BTC: 0.01 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: Issue was on Bisq 0.9.7. I am now running 1.9.17. I have all logs from that time.
BTC address for reimbursement: bc1q29wcry07uy5jccemz9r76mgfmug56cexl02gpd

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: This was an old trade I forgot about as the mediator never replied. I currently have 0.015BTC locked because of that failed trade.  

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
It seems that the deposit tx was confirmed correctly, therefore this is not elligible for refund. 

If the trade appears as failed please open mediation, he will make a proposal or a manual payout if needed.

Let me know if you need help with anything else,

**Comment by blob42** [comment]
Ok noted thanks
