### ISSUE TITLE
Fee reimbursement for trade azdorx

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#170]
![image](https://user-images.githubusercontent.com/29404408/49173603-7ae5b400-f344-11e8-876e-f1065fe2ef1a.png)
Maker: 58527508cd35fc0fd0d246762053f8f09edcb6568e585c6de490dcc20a543f0b
Taker: 139d592589475639bf6eefc8ec8fa5a67dd0c885397c338a7dbc925d2e4dcd63
in "Failed" folder, cmd-o not working.

**Comment by KanoczTomas** [comment]
note: Maker TX was published as well, added to https://github.com/bisq-network/support/issues/147

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/147#issuecomment-443627102.
