### ISSUE TITLE
Fee reimbursement for trade 70D2QFE

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#171]
![image](https://user-images.githubusercontent.com/29404408/49173816-fc3d4680-f344-11e8-87ef-2ca714c132aa.png)
Maker: 1bd9efb149478a8d266ad5d201246c10f1ff274c1926d934a1e01f9091e8bf7e
Taker: fc8406d6bf2fac4e6a3c10c9abd91cae97f4e9e3d63f7339bd13bd58ead548b2
in "Failed" folder, cmd-o not working.

**Comment by KanoczTomas** [comment]
note: Maker TX was broadcast, too. Added to csv https://github.com/bisq-network/support/issues/147

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/147#issuecomment-443627102.
