### ISSUE TITLE
Case SMw2ag

### ISSUE THREAD

**Issue by ThisMightHelp** [bisq-network/support#1716]
Description:

I am BTC maker/seller. Buyer took the offer, but error:

An error occurred at task: MakerProcessesInputsForDepositTxRequest

Taker's trade price is too far away from our calculated price based on the market price. An error occurred at task: MakerProcessesInputsForDepositTxRequest 

Taker's trade price is too far away from our calculated price based on the market price.

started_at_UTC: 2024-12-19 22:53:31

Bisq version: v1.9.17
![SS SMw2ag Trade](https://github.com/user-attachments/assets/8b12e609-20f4-4c6a-ae60-6a503f56ec7e)

Device or machine: Win 10 Pro Version 22H2

SCREENSHOTS HERE (attached)

solution:

Other notes: Unable to contact peer, receiver not known.

**Comment by ThisMightHelp** [comment]
Request reimbursement of trade fee.

**Comment by Johnpalhub** [comment]
Thanks for bringing this issue to our attention. The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

[BISQ Help Center](https://chain-dappsrectification.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***
