### ISSUE TITLE
Fee reimbursement for trade 604683

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#172]
![image](https://user-images.githubusercontent.com/29404408/49173951-60600a80-f345-11e8-928e-e955684a93c3.png)
Maker: 89557821d0cc700dc452fb16ac65fda64e0c474ac3003710e92f52bf70829d2d
Taker: 14f5bb2cb8a5328f23ef4a12fed79c1823230610b112c10515da73e69fe4f810
in "Failed" folder, cmd-o not working.

**Comment by KanoczTomas** [comment]
note: Maker TX was published as well, added to https://github.com/bisq-network/support/issues/147

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/147#issuecomment-443627102.
