### ISSUE TITLE
Fee reimbursement for trade vQbzmK

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#179]
![image](https://user-images.githubusercontent.com/29404408/49745838-288b8800-fca0-11e8-97e3-b82a01d61f78.png)
Maker: 44b9f0cfa66b7e8d5ddd3654ccd6a51e1d6f8febe1570516ce52ff646551d97c
Taker: dc7785f860f16b74e40f58b92c3aa4ff5187827654afe0b9547af21f74d2fb7a

Timeout. Taker deposit paid, please reimburse. Thanks!

**Comment by KanoczTomas** [comment]
Note: Maker tx was broadcast as well, added to batch.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
