### ISSUE TITLE
Fee reimbursement for trade vafqwcf

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#180]
![image](https://user-images.githubusercontent.com/29404408/49746063-a780c080-fca0-11e8-848a-39f55aedb946.png)
Maker: 2d2a0d5763104aa8631c19825e65ebfb3d2145f3833379ec7ad9a145cc92cf68 
Taker: e1658e9202263cd5bbab05077933b7cc4a00ef10904dd019ba3b44bfbc0ffc34

In failed folder, taker deposit was done, please reimburse. Thanks!

**Comment by KanoczTomas** [comment]
Note: Maker added to reimbursement as well.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
