### ISSUE TITLE
Fee reimbursement for trade 333283

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#181]
![image](https://user-images.githubusercontent.com/29404408/49746233-08a89400-fca1-11e8-979f-bd4e2cec54c0.png)
Maker: 6c4e4101fb17dbe597b5bea7ae2f705041cb4f5991ab1296349a8148723c0707
Taker: 2c8b2c136d227c34d786c43fa62e40261f698772520606f84e026a11f1342435

Error. Taker deposit was paid, please reimburse. Thanks!

**Comment by HarryMacfinned** [comment]
@marco4444 , which Bisq version do you use ?

**Comment by KanoczTomas** [comment]
@invertedbobb please open a separate issue for those transactions for reimbursement.

**Comment by marco4444** [comment]
@KanoczTomas 
this above was done with 8.0. In the meantime I upgraded to 9.0, but still happening at about 10%-20% of trades. May be when two people at similar time try to catch the same trade?
As son as I have my queue empty I plan to upgrade to 9.1.

**Comment by marco4444** [comment]
@HarryMacfinned 
this above was done with 8.0. In the meantime I upgraded to 9.0, but still happening at about 10%-20% of trades. May be when two people at similar time try to catch the same trade?
As son as I have my queue empty I plan to upgrade to 9.1.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
