### ISSUE TITLE
Fee Reimbursement for RSEJ4WZ

### ISSUE THREAD

**Issue by buzztiaan** [bisq-network/support#182]
maker 6e38854fd6eaa162e5d0d419c2370da3281ade5146c5380643b8e53a7bd60cab
taker 3c4f457e88b9e70b490fa01d7feeba10f97b669d0037cdc39d28928bb6611af7

An error occurred at task: SellerAsTakerCreatesDepositTxInputs
Exception message: org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.011392 BTC

TAKER_FEE_PUBLISHED 

(related to https://github.com/bisq-network/bisq/issues/2112)

**Comment by KanoczTomas** [comment]
@buzztiaan please upload a screenshot of the failed trade - please use #176 as an inspiration.

**Comment by KanoczTomas** [comment]
@buzztiaan yes, we required screenshots from all, so want it to be consistent. Thanks, adding you to the todo stack.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
