### ISSUE TITLE
Fee reimbursement for NVZ5HMPI

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#183]
![image](https://user-images.githubusercontent.com/29404408/50008874-bd022d00-ffb5-11e8-9a24-58d3e0993692.png)
Maker: 01f472801653b683314b40c012b5f441deecb2b4792a2ba7270ac82f2f01a37d
Taker:  9240979d5e80cf259e11572a52ec41531fdd222f56cb0aa06dc61e00d25c0f96

Please reimburse, not progressing due to timeut error, it's in "Failed" tab.
Thank you.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
