### ISSUE TITLE
Fee reimbursement for AKHjK2

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#184]
![image](https://user-images.githubusercontent.com/29404408/50046173-4e999980-009f-11e9-8309-5052e694693b.png)
Maker:  3e798aa63f606078f00140d0ac7bcc8a7e3d84c2ed3990114811048a9f0ae828
Taker:  a738021e1861d53ab6cd34de4e72b689398370f2a66928868804348528159595
Timeout error, please refund.
Thank you.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
