### ISSUE TITLE
Fee reimbursement for #37304

### ISSUE THREAD

**Issue by Yummis** [bisq-network/support#185]
Trade from 21 Nov failed no idea why, please refund deposit, somehow it is still shown in open trades, unable to cancel it, how can I remove it?

Maker: 2b961b0d92c1c0a4f3f410234ec842268a762213f70dcc68e7c991b8b00fc95c
Taker: 06df7534a4e713f58b70d3f0c69dd7d62b6186f779adbc57165ef9753597c29c

<img width="1312" alt="screenshot 2018-12-15 at 20 58 24" src="https://user-images.githubusercontent.com/34694228/50047406-3e3beb80-00ac-11e9-8a04-3663f8381158.png">

<img width="1268" alt="screenshot 2018-12-15 at 21 02 04" src="https://user-images.githubusercontent.com/34694228/50047438-d4701180-00ac-11e9-87fc-5a10a0fe74f6.png">

**Comment by Yummis** [comment]
Maker: 2b961b0d92c1c0a4f3f410234ec842268a762213f70dcc68e7c991b8b00fc95c
Taker: 06df7534a4e713f58b70d3f0c69dd7d62b6186f779adbc57165ef9753597c29c

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.

**Comment by Yummis** [comment]
> @Yummis is it still showing as open now? Could you share logs from that day?

Yes it is still showing open

**Comment by Yummis** [comment]
@KanoczTomas @cbeams It is still showing as a open trade impossible to close in any way, please help, thanks 
<img width="1312" alt="screenshot 2019-01-07 at 19 57 33" src="https://user-images.githubusercontent.com/34694228/50790290-7bb02500-12b6-11e9-960e-118683228dd2.png">
