### ISSUE TITLE
fee reimbursement for LfIpr

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#186]
![image](https://user-images.githubusercontent.com/29404408/50048552-ae0f9d80-00cf-11e9-85a3-7758a8fb8ef5.png)
Maker:  201c317ef6da7faa953f5dd8f0454856cdceec6d7f6cf1d5e071f91d96db3e44
Taker:  dae458c476e3bdd79c6dea48989edf52b4eb048bb9d863a6e066bce599ebee31
Timeout error, thanks for reimbursing!

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
