### ISSUE TITLE
fee reimbursement for iigb3xe6

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#187]
![image](https://user-images.githubusercontent.com/29404408/50122821-94e92700-025e-11e9-9d19-ac4caafe98ef.png)
Maker:  2edeb89d4712be388e0ae9437a139f164763706f2435479d62977cf9aa9640ed
Taker:   30c731cbc5390127f17d20a939d1d46bb59136704f7e967e203a502ed0e81955
Don't understand the error, please reimburse. Thanks!

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
