### ISSUE TITLE
Fee reimbursement for COCQJO

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#188]
Version 9.0, will upgrade to 9.1. a.s.a.p.

![image](https://user-images.githubusercontent.com/29404408/50122951-12ad3280-025f-11e9-8100-1827c009e6dc.png)
Maker:  d7ce01891dae618b2c2e3e39313647168d3dfbdbd159d8f1eadb1b08448b83dc
Taker:   cdfd0410757eb676f914481b254f4d4d7600283348caecd95c01d2d4b866767e
Timeout error, please reimburse.
Thanks.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
