### ISSUE TITLE
fee reimbursement for jThM9U

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#189]
![image](https://user-images.githubusercontent.com/29404408/50123035-7df70480-025f-11e9-8644-6dc0a1b26c13.png)
Maker:  bca4a3544a6a4f2f1ee9ab81622b9d65716523b757f20be8efd69258c96dc5ea
Taker:   beb817428e32a23c7952379eeb8d4c1064e9a0c7949bf88b60010b7c5d948ede
Timeout error, please reimburse.
Thanks.

**Comment by KanoczTomas** [comment]
Maker & Taker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
