### ISSUE TITLE
2x fee reimbursement for Dbwh1Iz

### ISSUE THREAD

**Issue by marco4444** [bisq-network/support#190]
![image](https://user-images.githubusercontent.com/29404408/50123358-9e738e80-0260-11e9-8320-92febb56fc8a.png)

![image](https://user-images.githubusercontent.com/29404408/50123452-ff02cb80-0260-11e9-829d-989ec1b0d4d8.png)
Maker:  99a686b378bab538db616df76802cfcf79b77a58964e2bc1423ab003bbb2f69b
Taker:   eaf593bc1fac5f5e56834e8d6436a32298fff9c130a1feb6ec36a301d92215f8

![image](https://user-images.githubusercontent.com/29404408/50123484-2fe30080-0261-11e9-888a-9b06435d24be.png)
Maker:  99a686b378bab538db616df76802cfcf79b77a58964e2bc1423ab003bbb2f69b
Taker:   8d9f24d524783858b1b04e1640831d88b3d970ae5591baa3ac4d2decb4f35496

Strange error, double entry in the failed list. Maker transaction in both cases the same, but two different taker transactions.
Please reimburse.
Thank you!

**Comment by KanoczTomas** [comment]
@ManfredKarrer are you aware of the above issue?

**Comment by ManfredKarrer** [comment]
Yes the double entry is expected if there are repeated failures. Seems the peer has a corrupted wallet database.

**Comment by KanoczTomas** [comment]
Maker & 2xTaker transaction will be reimbursed in #173

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/173#issuecomment-450818949.
