### ISSUE TITLE
19x Failed trades, reimbursement.

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#198]
I still have 20+ trades that failed from the past two months while the trade and transaction fee were published.

The reimbursement process is overly complicated and confusing, additionally it handles all the trades one by one. Is there any way i can request reimbursements in one big batch so only one time transaction fee has to be paid?

**Comment by KanoczTomas** [comment]
@invertedbobb you can add the 20+ trades to this issue if you want, but I will need a screenshot and copy of the deposit, maker, taker tx id to process them. You can give us a refund address here and all reimbursements would go to that address.

**Comment by invertedbobb** [comment]
Reimbursement can be sent to: 3GcDAvSWhkqTVRgxbQrdfUynFEyu3PGCpC

Please note that there are duplicated trade IDs, i've tried to take an offer several times and it failed repeatedly, losing fee every time.

Screenshots from 2018 batch: https://imgur.com/a/WL7uNj9
Screenshots from 2019 batch: https://imgur.com/a/rRDXcgK

Old ones from late 2018:

Date: 10 Dec 2018 02:33:57
TradeID: cwnbppai-948a0f97-1aff-4416-a172-1b6ba109cb02-090
Maker fee txid: 4a14fbd87a8127ce322f25a72752dd6b11dec5306f5a21907521145332aa17d1
Taker fee txid: d5bf09795fc7b7d6c780fe9d3a083372a7685bfb81586177015560efaa26a13f
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 10 Dec 2018 02:37:41
TradeID: cwnbppai-948a0f97-1aff-4416-a172-1b6ba109cb02-090
Maker fee txid: 4a14fbd87a8127ce322f25a72752dd6b11dec5306f5a21907521145332aa17d1
Taker fee txid: d20f3562abc41a4afc2254a4b8db672171cf3a8b0800bd2ee2634abca0a369ef
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 10 Dec 2018 02:52:17
TradeID: cwnbppai-948a0f97-1aff-4416-a172-1b6ba109cb02-090
Maker fee txid: 4a14fbd87a8127ce322f25a72752dd6b11dec5306f5a21907521145332aa17d1
Taker fee txid: 79dbc53ad9273184957bb208d0e0c07c9c323481152a2362e5494ca98d97d7b4
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 10 Dec 2018 18:52:09
TradeID: 36406751-18641de8-1d7a-49ee-a9fb-5230b1e98e5c-090
Maker fee txid: c2e8814bdf747967d766a695a87f5d0aa380f57867eeeda5357e56d1a3bb0976
Taker fee txid: 952d5893ef7a7634d669e4785f64110cc627e479f875e1d7f207c1ca62c36ef2
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 10 Dec 2018 20:23:48
TradeID: 639309-121663cc-ecb3-487a-a9df-5d4420c3b866-090
Maker fee txid: b7212eeac9841acbad8591c3ed10b0690d0ba57585bb1bb0dba292bcaff999c5
Taker fee txid: 545a69f8d1ebff9c1e0666f87cba76edb9b1feb0d1038251eb517f940af81a3b
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 11 Dec 2018 01:28:09
TradeID: pusqyhv-d287bf1a-a35c-4a9d-8936-e1ebafc31585-090
Maker fee txid: e486a4b58fa9930f5dab391367541b839984ce6793f7add61f84ccdd2887dadc
Taker fee txid: 684f34e1af6df1bd27a1884111fb235b88efd7750c630f3cbbeed373441803a6
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 11 Dec 2018 12:38:16
TradeID: pusqyhv-d287bf1a-a35c-4a9d-8936-e1ebafc31585-090
Maker fee txid: e486a4b58fa9930f5dab391367541b839984ce6793f7add61f84ccdd2887dadc
Taker fee txid: 24fe989e282e34735747af3360b6e8754c460294f7ace95145fddccacf6a2920
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 11 Dec 2018 12:40:56
TradeID: 05747836-a32b4ae5-c7d4-40fe-aca9-6157e9d80328-090
Maker fee txid: 2e8674f9211323edc0a75a38d492ea8ebb2ee950b7928682cc26a5bfae7ffc55
Taker fee txid: 4c0b2de9dd4aa4dbab2fa14da9fca9f6224bf935bf9ba2e355f4a828f45aa019
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 11 Dec 2018 19:35:51
TradeID: 29337-7199ff10-ed4a-4693-bafa-905e4c2b84d4-090
Maker fee txid: c06499701c8e9260f5c6de16ccd37baf96cafbcae4b98fc750ffc5e00519e3f5
Taker fee txid: 5b26dc6ebd730a6c4b5118eed9498989671f84dfe47e7ca0144b8b7f1d92f3fa
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 15 Dec 2018 01:30:45
TradeID: LWDNZA-16dcf948-1071-4bca-86bc-4bbe80035425-090
Maker fee txid: 5bd86acd216bed0de510db21e13ecf59c1f395b33f8b514edfbcfc93c3a4a2e9
Taker fee txid: 1325a9833fcee21193a5fb306e5f697eeeffc65c012795becca247d8c18679d0
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 15 Dec 2018 01:32:58
TradeID: LWDNZA-16dcf948-1071-4bca-86bc-4bbe80035425-090
Maker fee txid: 5bd86acd216bed0de510db21e13ecf59c1f395b33f8b514edfbcfc93c3a4a2e9
Taker fee txid: 27f235467e2ef44349609906367906a06d22eb1485a5fbca5fac76f294166f6c
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 16 Dec 2018 22:09:56
TradeID: 5799866-1e95454f-afa7-4fa4-af42-5d7722c2af28-090
Maker fee txid: 972b679772609dc871878e4e4b91eef13344d46d431eb528cda923c1591b2bb9
Taker fee txid: cda1a52c9061f2c250adb917c5f856c88a141fe63b9c23b683fc48de98aaf204
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 18 Dec 2018 12:12:45
TradeID: ZT0QFq-87b73fe3-5649-475d-83c5-7cccfc428e2a-090
Maker fee txid: 1774e3ba774b6bccfe1a7e3f698887aa86b76adffd289150f9255208aaf85d00
Taker fee txid: 29b98b1c16ae01c0ef20d312e23f013f21cdafc1c43ce4f60e1515cc1ba239a8
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 27 Dec 2018 16:13:26
TradeID: ui1ke-c5b57ac6-7618-433b-8fc3-fdd0bb2672b9-090
Maker fee txid: ec9e9808a1c9b0f3b6e801ef87fc9927d94144f385cebac395b38696260584a6
Taker fee txid: b11f4a1b3000182140b69477b4f198228bc973b031fa3e0a3a0bdfa2e215afaa
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 29 Dec 2018 11:53:22
TradeID: 207997-d1a9e7a0-6362-461d-84b7-823244de2581-090
Maker fee txid: cfd92d6da534a67e32b4d4ac7cdd3fcd0e875220c91051ecb0cedd7946972acb
Taker fee txid: cb9b6b3ef14e481d789edbd0be3a9e27c4ef03ee2f414a0bfeebfa2aba6af722
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 30 Dec 2018 16:29:13
TradeID: 41C1ZY-ea5bf4f3-2533-4f6f-99e1-fd49620e1cc6-090
Maker fee txid: dd3b7d512fe4af2700a9097b51e9dcc1dc144c33c1d7e6477265416a17dffff9
Taker fee txid: 2ebc0ed92fe3e369fbcca8068979f1bf010bc14420152ba39c50422caac9c284
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 30 Dec 2018 16:40:55
TradeID: TS29KW2G-afccef78-040a-4569-ace2-bad516a80ae1-090
Maker fee txid: e5d524855f497db49c08bafc8de57fe943830907b7d64802c7049314a6e05bb8
Taker fee txid: 6b4b8f03bdae2f5671e9be68a56e3b7fe07959d0e4f2511447b77a200c7e38c1
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED


More recent ones from 2019:

Date: 10 Jan 2019 14:16:43
TradeID: 72137-9edb45b6-b0db-41b4-b5a5-061abf61c543-090
Maker fee txid: 4932c603a92c34876cecacffc4953416cca7ebb565ad938111727b46976b2dc3
Taker fee txid: 7eda48219a63a38aa9360529ef18e2a75de1ade51207adb2630523e9d6bff654
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 10 Jan 2019 14:18:52
TradeID: 72137-9edb45b6-b0db-41b4-b5a5-061abf61c543-090
Maker fee txid: 4932c603a92c34876cecacffc4953416cca7ebb565ad938111727b46976b2dc3
Taker fee txid: 858bf136a539b737d781612eba6a68b7a7469a62e9ea9d7bd195226f1f013d21
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 11 Jan 2019 01:30:09
TradeID: 4zYsL-a560009d-e20c-4f89-b0d4-bb620c7e9b26-090
Maker fee txid: 3c224c201c4e1071c594c6664dddec496851d8252faf282ef9703a739e5b65b9
Taker fee txid: defda82f8a870d982e64c1086a8e15035b727931b2d3275515e92d6f602763d3
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 12 Jan 2019 03:30:26
TradeID: 4zYsL-a560009d-e20c-4f89-b0d4-bb620c7e9b26-090
Maker fee txid: 4932c603a92c34876cecacffc4953416cca7ebb565ad938111727b46976b2dc3
Taker fee txid: 567a84c49c4dd7dbb01d88454386010857f91d08bb475cb558a962eeb1bcd275
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 13 Jan 2019 18:05:46
TradeID: SaEDfnD-1d1ae073-2bb6-4f53-ae90-24d046bfe6e9-090
Maker fee txid: 0fbc87f3fece06b0968662b86f3cee339d35842e836dd747803350ba02813e06
Taker fee txid: ab42625f1b83f973019bb30608d5d8b0952d916d67ef9fde934c94f782bf5ebe
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 13 Jan 2019 18:40:03
TradeID: 948745-9dae6cc9-ddc3-4a3c-8d9f-18a137377af1-090
Maker fee txid: 7bfd6bba7d40ae040d1fbad23bf25e3ed80bf18b4ddbcd788e0ef254f15cbe1c
Taker fee txid: f02aededb100fdbc70329b5397dcb2e26c9ea11c10b2b05a1360fbd5214ba809
Error message: An error occurred at task: TakerVerifyAndSignContract
Exception message: Contracts are not matching
Trade state: TAKER_FEE_PUBLISHED

Date: 17 Jan 2019 15:22:30
TradeID: SMKDHK-fe224e6f-5b09-4ef6-810e-017d976c0207-090
Maker fee txid: 9be25bcab0224e7488bc345bba45f6f64e1c1ea2854e7c0cd761b9f38d85244b
Taker fee txid: 905febbed7a976fed6583b900b5f39dcb753f4841be190fa8b30d6b4411e84bd
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 18 Jan 2019 12:26:54
TradeID: SMKDHK-fe224e6f-5b09-4ef6-810e-017d976c0207-090
Maker fee txid: 9be25bcab0224e7488bc345bba45f6f64e1c1ea2854e7c0cd761b9f38d85244b
Taker fee txid: c8b5bb3d8d0a25f42f03992ac65bd8c10d42245400b80c62f3c342c577b5c8f9
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 18 Jan 2019 12:29:52
TradeID: SMKDHK-fe224e6f-5b09-4ef6-810e-017d976c0207-090
Maker fee txid: 9be25bcab0224e7488bc345bba45f6f64e1c1ea2854e7c0cd761b9f38d85244b
Taker fee txid: 4f3510ae0a3b535d3b69f9894ab838564f1d016895a753c3b8a6af01eba3dbdd
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 18 Jan 2019 12:50:40
TradeID: MHdWr-d02f5284-0e63-4740-9c90-078624dabab9-090
Maker fee txid: cd677117f63455592794bb1b2e2e0a286dc28b6874312547941c7640004c0e69
Taker fee txid: b3c544791444521ebc9aebd95d486a3ffbf2c61f9c41360dc64d5780f28f4da6
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

Date: 18 Jan 2019 13:09:54
TradeID: SMKDHK-fe224e6f-5b09-4ef6-810e-017d976c0207-090
Maker fee txid: 9be25bcab0224e7488bc345bba45f6f64e1c1ea2854e7c0cd761b9f38d85244b
Taker fee txid: f3b1754cad63ce311af1680dd7f7a1ed9cc4baffc8ac507463a75d0f71f97259
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

**Comment by KanoczTomas** [comment]
@invertedbobb I inlined the screenshots with every trade, I am missing one screenshot. Please upload the one for this trade:
Date: 12 Jan 2019 03:30:26
TradeID: 4zYsL-a560009d-e20c-4f89-b0d4-bb620c7e9b26-090
Maker fee txid: 4932c603a92c34876cecacffc4953416cca7ebb565ad938111727b46976b2dc3
Taker fee txid: 567a84c49c4dd7dbb01d88454386010857f91d08bb475cb558a962eeb1bcd275
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

**Comment by KanoczTomas** [comment]
Will be reimbursed with #195

**Comment by ManfredKarrer** [comment]
@invertedbobb 
Are you using the latest version? If not please update there have been many bug fixes.
If you have repeated issues please consider to switch to a new data directory. 
See:
https://bisq.community/t/how-to-switch-to-a-new-data-directory/6753/

In case some local data in your data directory are corrupted that would help to start over clean.
