### ISSUE TITLE
https://market.bitsquare.io/api/trades/?market=btc_usd

### ISSUE THREAD

**Issue by loeken** [bisq-network/support#199]
your endpoints are returning some stacktraces ( or did untill thehy went down ) maybe you guys should look into this

Ouch! Encountered PHP Fatal Error. Shutting down. Array ( [type] => 1 [message] => Out of memory (allocated 18874368) (tried to allocate 33554432 bytes) [file] => /home/websites/bitsquare_market/lib/filecache.class.php [line] => 92 ) WARNING: ALERTS_MAIL_TO not defined in config. alert not sent with subject: [markets] [index.php] PHP Fatal Error! [pid: 12421]

**Comment by KanoczTomas** [comment]
@loeken please kindly open an issue with https://github.com/bisq-network/bisq/issues, this repository is for reimbursements. I will close this here to stay organised.

**Comment by KanoczTomas** [comment]
@loeken by the way, the bisquare.io is the old webpage, check out  https://bisq.network/markets/ instead.

**Comment by KanoczTomas** [comment]
never mind, the same end point is from the old one ... it works for me now.
