### ISSUE TITLE
Can't select Trading account when taking an offer

### ISSUE THREAD

**Issue by BSQman** [bisq-network/support#201]
I'm using Version 0.9.3.

When I select an offer to Buy, the application gives me half a second to select trading account before it greys the box out and gives me options to fund the trade. I can't choose which of my trading accounts to use. I have multiple payment accounts and up until a few hours ago, I've never encountered this issue. I've attached screen shot
![screen shot 2019-02-01 at 2 54 22 pm](https://user-images.githubusercontent.com/40665327/52130146-50a8bf00-2631-11e9-8241-30edcb5827c1.png)

**Comment by ripcurlx** [comment]
This is related to following issue bisq-network/bisq#2276 and fixed on master already. Will be released with 0.9.4 mid of February.

**Comment by pazza83** [comment]
Closing as stale
