### ISSUE TITLE
Fee reimbursement for trade IOXOJC

### ISSUE THREAD

**Issue by BSQman** [bisq-network/support#205]
Taker Fee was taken but order did not go through. I got this error message , 
![screen shot 2019-02-14 at 9 39 16 pm](https://user-images.githubusercontent.com/40665327/52819854-532ffd80-30a2-11e9-9eb2-17104de6697c.png)

Trade ID :IOXOJC-d37539e8-b8be-419d-b86a-cc50fe5453b5-093
Maker Fee Trans ID : 7b8541826149424d20e06fad099164f6782626e14397f9375b5a4ffec39c9b25

Taker Trans ID :9d37d5b0adac33f9f6694886a121539e3bfd7d34cff0383bfd94e648926e1cad

Error Message : A timeout occurred.

**Comment by BSQman** [comment]
It appears it took more then the taker fee from my account.

**Comment by KanoczTomas** [comment]
@BSQman please upload a screenshot of the trade. See #204 for an inspiration.

**Comment by BSQman** [comment]
![screen shot 2019-02-15 at 1 52 52 am](https://user-images.githubusercontent.com/40665327/52829374-6f449680-30c4-11e9-8154-f9d9406c0df1.png)

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
