### ISSUE TITLE
Fee reimbursement for trade DDEVM

### ISSUE THREAD

**Issue by loryhuz** [bisq-network/support#206]
Hello, since grin support has stopped can you reimburse maker fee for my trade:

ID : DDEVM-e5755db0-5c2a-4a3f-a00d-b753d5cf6141-093

Thanks

<img width="1059" alt="capture d ecran 2019-02-22 a 15 46 47" src="https://user-images.githubusercontent.com/3198863/53249757-3a82a180-36b9-11e9-93e7-fcc31c96b24e.png">

**Comment by KanoczTomas** [comment]
@loryhuz please copy the both the maker and taker tx as well. I can not copy from a picture and rewriting it is tedious and error prone. Thanks!

**Comment by loryhuz** [comment]
_760a1e62f32d21926f3e790b662c5003c4d90ed8127ebc6bca5bab49b5c30a90_

@KanoczTomas  This is the only TX I have as the trade didn't go to the end, I just posted an buy offer

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
