### ISSUE TITLE
Fee reimbursement for trade 99097

### ISSUE THREAD

**Issue by zufenihu** [bisq-network/support#207]
![image](https://user-images.githubusercontent.com/47923087/53288677-f87a5e00-3793-11e9-9278-c88d8c7d84b3.png)
Maker: a6149176b201eb5f69a83968fe493696af8f2c5cb199ff6aba31db8b70e85012
Taker: 82adc142df3112b96fdf8305c74ff867ffd6c75554e3d1bdddf9245b51c42fc7

Used version v0.9.4, trade is in "Failed" folder, please reimburse, thanks!

**Comment by KanoczTomas** [comment]
@zufenihu please upload an image where the trade ID is visible as well. Make sure to cut out all private information from the image. Thanks!

**Comment by KanoczTomas** [comment]
@zufenihu any update?

**Comment by KanoczTomas** [comment]
@zufenihu any update?

**Comment by cbeams** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
