### ISSUE TITLE
Fee reimbursement for trade: nUe3SN4

### ISSUE THREAD

**Issue by GustavoFrag** [bisq-network/support#208]
Used version v0.9.4, trade **nUe3SN4** was canceled by support, please reimburse the fee buyer/maker, thanks.

<img width="1133" alt="screen shot 2019-02-26 at 5 33 55 pm" src="https://user-images.githubusercontent.com/43123095/53444871-0b886a80-39ee-11e9-98ea-0e2d0c9bf317.png">
Maker: 940bb03ceaaf79786c09daaf6a6e367dc774c429fdd3a40f626593d053af2c72

Support messages:

1. System message: Your trading peer has requested support due technical problems. Please wait for further instructions.

2. The txs were not published and the trade has to be cancelled. You can get reimbursed for your fee at: https://github.com/bisq-network/support/issues/. No other funds left your wallet, but it might show a wrong balance. If so you can correct it by deleting the SPV-chain file under Settings/Network Info.

3. Ticket closed on Feb 26, 2019 6:45:04 PM

Summary:
BTC buyer/Maker delivered tamper proof evidence: No
BTC buyer/Maker did ID verification: No
BTC buyer/Maker did screencast or video: No
Payout amount for BTC buyer: 0.0013 BTC
Payout amount for BTC seller: 0.2530 BTC

Summary notes:
Not published txs.

**Comment by KanoczTomas** [comment]
@GustavoFrag please upload a picture where the tradeid is visible as well. Thanks!

**Comment by GustavoFrag** [comment]
> @GustavoFrag please upload a picture where the tradeid is visible as well. Thanks!

<img width="890" alt="screen shot 2019-02-27 at 10 44 21 am" src="https://user-images.githubusercontent.com/43123095/53494571-d6772900-3a7c-11e9-925a-ade76d76d33d.png">

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
