### ISSUE TITLE
Fee reimbursement for 28683

### ISSUE THREAD

**Issue by liquidso** [bisq-network/support#209]
![bisq](https://user-images.githubusercontent.com/48312754/53942845-b04f1b80-4070-11e9-8250-5467da3d0952.jpg)

Maker: d57bdc4eefe2c0825fb31fbc04f8ee551356a8764de162a5e05300a3071f695d
Taker: 948ebdc53f7e4a817c068f18d63e5399acadf5ff772ecdfb4d966b0fba9ccf9d

Please reimburse. Thanks

Dispute summary notes: The trade fee transaction did not lead to the deposit tx, so no deposit tx has been created.

**Comment by KanoczTomas** [comment]
@liquidso please include a screenshot where the trade ID is visible as well. Please cut out private information. thanks!

**Comment by liquidso** [comment]
![image](https://user-images.githubusercontent.com/48312754/54416481-bf5f4a80-46bc-11e9-8639-ae8ee2ca4fc6.png)
