### ISSUE TITLE
Fee reimbursement for trade LWDBOKE

### ISSUE THREAD

**Issue by nunyabidnes** [bisq-network/support#210]
![image](https://user-images.githubusercontent.com/48492119/54227137-aa749280-44d5-11e9-90d3-bd5b68fce7cc.png)
Maker: ae7b9225e326320cd058052615b4c86708207446511149e9c6e1a9fb1a77bc8f

The Deposit Tx never got published. Could I get the Maker Fee re-imbursed?

**Comment by nunyabidnes** [comment]
Deposit TxID: 75e96c8840869dffb940164b656a91e80d6ca92951f80b5600c938b4fd312ec4

**Comment by KanoczTomas** [comment]
@nunyabidnes please paste all addresses maker, taker, deposit. We always check if those did not get published as well and refund them.

**Comment by nunyabidnes** [comment]
Taker: 27114a888f059baefe6612a43e51340f891f233d1246f1716ac92cff1b682e35

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
