### ISSUE TITLE
Fee reimbursement for trade jnvmc

### ISSUE THREAD

**Issue by nunyabidnes** [bisq-network/support#211]
![image](https://user-images.githubusercontent.com/48492119/54227730-ef4cf900-44d6-11e9-84eb-ae8814032777.png)
Maker: 96c82d6431669f2a83b055aa047d32331188fb6b6792039f338804a15bf10386
Deposit transaction not published. Could I get the TX fees reimbursed?

**Comment by nunyabidnes** [comment]
Deposit TxID: 44b5bef670d2863898cae4ab924644eee44ae65621515d26b1fdc158b2c65751

**Comment by KanoczTomas** [comment]
@nunyabidnes the same, will need you to paste all 3 transactions, thanks!

**Comment by nunyabidnes** [comment]
Taker: 16130029ff8c47b3733069aca4c66474d5790195b0ec6ed4772915cf29cab8fc

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
