### ISSUE TITLE
Fee reimbursement for trade ejnfhlc

### ISSUE THREAD

**Issue by ncstdc** [bisq-network/support#213]
![Screen Shot 2019-03-18 at 12 17 26 AM](https://user-images.githubusercontent.com/2712736/54508578-41957c00-4914-11e9-90b8-4b521d1c3a3b.png)

Maker:  af0c847154debe95220f9ce2c3aeb6027d4558f0032e7111c280a5f1bdb0f7da
Taker: 074c7cc4fbb7aa984a97bb2676c6347e938f4c562c91e5b64d1aea90aa23008c
Deposit: 8bff560c4d54738e62f4126f0ff6a531f52d487f4010363a21855f1a7eb7a3c3

Bisq version: 0.9.5

Other notes:

From support:
> The peer used an older version and it seems he had a bug. As no deposit tx has been created I will close.
Ticket closed on 17 Mar 2019 23:59:08
Summary:
BTC buyer/Maker delivered tamper proof evidence: No
BTC buyer/Maker did ID verification: No
BTC buyer/Maker did screencast or video: No
Payout amount for BTC buyer: 0.0010 BTC
Payout amount for BTC seller: 0.0410 BTC
Summary notes:
Deposit tx was not created

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
