### ISSUE TITLE
Fee reimbursement for trade rg27w

### ISSUE THREAD

**Issue by PeterSurda** [bisq-network/support#214]
![Screenshot from 2019-03-18 13-54-31](https://user-images.githubusercontent.com/3815204/54531748-56125c80-4986-11e9-9a51-8103191ac351.png)

Maker:  6f51b5cae13ba054035cf0d7004387e917ae5cfc36d8b6514b03695deed8402d
Taker: 5f857e436775cf382866e7b9ab3367279958fc0944d9e4b5a35e71627822ba88
Deposit: N/A

Bisq version: 0.9.5

Other notes:

From support:

> I can see that the peer has an older Bisq version and probably a bug happend on his side.
As no deposit tx has been created no funds beside the trade fee has left your wallet. You can ask for reimbursement for the lost trade fee at https://github.com/bisq-network/support.
I will close but no payout tx will be created as no deposit had been created.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
