### ISSUE TITLE
Fee reimbursement for trade 639309

### ISSUE THREAD

**Issue by croissantss** [bisq-network/support#215]
![Screenshot from 2019-03-22 16-47-37](https://user-images.githubusercontent.com/48837188/54839420-baa12480-4cc2-11e9-921b-77f5a768abcd.png)

![Screenshot from 2019-03-22 16-47-55](https://user-images.githubusercontent.com/48837188/54839405-b6750700-4cc2-11e9-869f-7c6280fff198.png)

Maker:  b7212eeac9841acbad8591c3ed10b0690d0ba57585bb1bb0dba292bcaff999c5
Taker: 09a64f1ebbc1de67001886e7fe790e7ed6e5835af4346fa1e4ff73b706038313

Maker: b7212eeac9841acbad8591c3ed10b0690d0ba57585bb1bb0dba292bcaff999c5
Taker: 02f3031952ad703a7356c7bc680d479d301257f5fcadf32baa16df1b0ec47eef

"A timeout occurred. TAKER_FEE_PUBLISHED"
Please reimburse fees. Thanks!

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
