### ISSUE TITLE
Fee reimbursement for trade 46734667

### ISSUE THREAD

**Issue by croissantss** [bisq-network/support#216]
![Screenshot from 2019-03-23 14-59-12](https://user-images.githubusercontent.com/48837188/54867811-87bb6700-4d7c-11e9-90a5-0744fc6f315a.png)

Maker:  5b8a1d652995b67061be6cbd73e58cb248a3d6114c93a17df68b5860695641cb
Taker: 3a048b1557943db05a1edb13c42d705be18a6d5972173ec26406ebbfd7b27fe9

Bisq version:
0.9.5

Other notes:

"An error occurred at task: BuyerAsTakerSignAndPublishDepositTx
Exception message: arbitrator must not be null"

Please reimburse fees

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
