### ISSUE TITLE
Fee reimbursement for trade mnhnhtb

### ISSUE THREAD

**Issue by KanoczTomas** [bisq-network/support#217]
![image](https://user-images.githubusercontent.com/15045051/54940671-84b2a900-4f2b-11e9-97b2-ea8edd4161f5.png)

Maker:  d26dd7934acb747b10e8cce3ef829307a615b1d32ac437ca68474cf874b8eff4
Taker: 2bf3c65e3134ed1cf298d3cd09afd5a027650cbb06b75f2284b4a113e061cdb1
Deposit: N/A

Bisq version: 0.9.5

Other notes:
Trade still visible in open trades, but the taker TX was never published. How to delete it from trades?

Asking to return maker fee.

**Comment by KanoczTomas** [comment]
@ManfredKarrer could you please answer the question of the user?
Other notes:
Trade still visible in open trades, but the taker TX was never published. How to delete it from trades?

**Comment by ManfredKarrer** [comment]
You can delete the PendingTrades file in the db folder inside the data directory if you don't have any other trades open.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #200

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/200#issuecomment-478079552
