### ISSUE TITLE
Warning message - "Connecting to the P2P network failed"

### ISSUE THREAD

**Issue by chewmagroo** [bisq-network/support#218]
I get the following warning (See attached img) just before the application fully loads. Bisq seems to function ok after I close this window although I haven't actually completed a trade. I have tried restarting.
<img width="621" alt="Screen Shot 2019-03-26 at 14 34 07" src="https://user-images.githubusercontent.com/28259233/55007804-f0525000-4fd7-11e9-8623-0658922f9c89.png">

**Comment by chewmagroo** [comment]
Running V 0.9.5

**Comment by HarryMacfinned** [comment]
How many bitcoin network peers and P2P network peers do you have ?
(On the bottom left and right corners).

**Comment by chewmagroo** [comment]
> How many bitcoin network peers and P2P network peers do you have ?
> (On the bottom left and right corners).
Bitcoin - 9
P2P - 2

**Comment by HarryMacfinned** [comment]
2 is not enough P2P network peers for Bisq to work properly.
Max is 12, and generally a well working appli has at least 8  P2P network peers.

Would be nice if you could show us the last 100 lines from you logfile.
This smells like an issue with Tor.
The next Bisq release will be ready probably next week, and addresses some Tor issues. So maybe if you wait till monday, the next Bisq may solve your issue.

**Comment by chewmagroo** [comment]
> Would be nice if you could show us the last 100 lines from you logfile.
I'm looking at my logfile and being non-technical dont feel comfortable posting this info.
I'll wait and try the new release. Thanks

**Comment by chewmagroo** [comment]
I have installed the latest update but still get this warning message. Only difference now is the application doesn't load at all now.

**Comment by chewmagroo** [comment]
Fixed with update v0.9.7

**Comment by KanoczTomas** [comment]
Thanks @chewmagroo, closing issue then. Please reopen  if needed.
