### ISSUE TITLE
Fee reimbursement for multiple ZOC/BTC offers

### ISSUE THREAD

**Issue by deadthings** [bisq-network/support#220]
Wish to have multiple ZOC/BTC offers canceled due to delisting of market, with maker fees refunded. The affected offer IDs are:

DZTTQMQV
ONWNCIE
mxiz2
cfcteei
dul52tQ
usaco
HlYN3TS
Q2uWVB
VEJYCZ
SUNBHSH

SCREENSHOT HERE:
![image](https://user-images.githubusercontent.com/33961641/55191276-1f9fc300-5178-11e9-9655-71d7f7d47fda.png)

Bisq version: 0.9.5

**Comment by deadthings** [comment]
Okay - so perhaps more info is needed...

Offer ID - Maker fee tx ID
DZTTQMQV - a7eb2202d4dae6bf8e81e1136fb8a30a5918fea4906f9904a0a8795001ea5142
ONWNCIE - 13ce38a1a63c99e667f8da32a63f8b8daf61e84794bd751c27356699dfd7e698
mxiz2 - 5c11c08066ff4838e5e767392c1d9386768956e55cb65754bf565d3e4507004e
cfcteei - a1aac1cc765beeb2cde666b180ce42c35483727b0e7991990b060a1d4dd30034
dul52tQ - 494c13273013084a0b0531261e5f5fdb8a53f8f34453ad5d087abffc5afbca59
usaco - 35870e9076a4ef631dfdb649bd0b8d958897a4c57696f072bb28a1e8fed9f521
HlYN3TS - c56313ddebd0d3139296d2cf020296a55061e5f04638e6bdda0cb97ef26f1221
Q2uWVB - dd0611da872357c38b5921cb750e4827f14b36ac141acc631b5b74cc7c8ca459
VEJYCZ - 048294843b992119488c3c49d911616adadb7a9ee4f548a35bb8cc3bfb7563c9
SUNBHSH - 1f028200d522b400dc7a5dc82e115460af4ddb66d1bbbe7587de431f6e3701fd

Please let me know if any additional info is needed.

**Comment by deadthings** [comment]
Hello (hello, hello), is there anybody out there?

**Comment by KanoczTomas** [comment]
@deadthings I am sorry, I somehow missed this request. Could you please edit the issue to be as per template - inspire yourself with #251. I will process your request after that and att it to the batch.

**Comment by deadthings** [comment]
Thanks @KanoczTomas - here's the information. Please let me know if you need anything else.

---

Overview of transactions:

![image](https://user-images.githubusercontent.com/33961641/59163466-9d187580-8acf-11e9-8d4b-249e9753057f.png)

Details:

1.
![image](https://user-images.githubusercontent.com/33961641/59163480-cafdba00-8acf-11e9-8d2a-8cdf6524aa54.png)

Offer ID: DZTTQMQV-a176c8e7-8ee1-41fb-a7af-f28999ee9f19-080
Creation date: Nov 22, 2018 10:09:41 AM
Maker fee txid: a7eb2202d4dae6bf8e81e1136fb8a30a5918fea4906f9904a0a8795001ea5142

2.
![image](https://user-images.githubusercontent.com/33961641/59163527-5d05c280-8ad0-11e9-9427-65d7ab280ee5.png)

Offer ID: ONWNCIE-0fdf1ca8-1bd7-49b5-ba92-c87a9fce326f-080
Creation date: Oct 29, 2018 9:24:45 AM
Maker fee txid: 13ce38a1a63c99e667f8da32a63f8b8daf61e84794bd751c27356699dfd7e698

3.
![image](https://user-images.githubusercontent.com/33961641/59163555-afdf7a00-8ad0-11e9-9def-e37539f3f6e4.png)

Offer ID: mxiz2-b163ae54-cdb2-4afb-a252-07d70cce402e-080
Creation date: Oct 29, 2018 9:24:08 AM
Maker fee txid: 5c11c08066ff4838e5e767392c1d9386768956e55cb65754bf565d3e4507004e

4.
![image](https://user-images.githubusercontent.com/33961641/59163585-e1f0dc00-8ad0-11e9-9a0f-72b4c0ff589f.png)

Offer ID: cfcteei-81d3360a-08aa-4922-8011-f8e89785a182-080
Creation date: Sep 20, 2018 5:10:44 AM
Maker fee txid: a1aac1cc765beeb2cde666b180ce42c35483727b0e7991990b060a1d4dd30034

5.
![image](https://user-images.githubusercontent.com/33961641/59163597-16649800-8ad1-11e9-995b-12846deb87a9.png)

Offer ID: dul52tQ-151620a7-3248-4d57-9c19-c9ff01b2a05f-080
Creation date: Sep 20, 2018 5:08:40 AM
Maker fee txid: 494c13273013084a0b0531261e5f5fdb8a53f8f34453ad5d087abffc5afbca59

6.
![image](https://user-images.githubusercontent.com/33961641/59163611-4744cd00-8ad1-11e9-826e-2a274193831b.png)

Offer ID: usaco-ce0b355d-fe8d-4d8e-b707-0773063359f4-080
Creation date: Aug 27, 2018 6:30:05 PM
Maker fee txid: 35870e9076a4ef631dfdb649bd0b8d958897a4c57696f072bb28a1e8fed9f521

7.
![image](https://user-images.githubusercontent.com/33961641/59163627-765b3e80-8ad1-11e9-92ab-641a1bbab369.png)

Offer ID: HlYN3TS-5b7e499d-f6c5-4204-890f-9e97440f8d5c-071
Creation date: Aug 20, 2018 5:24:59 PM
Maker fee txid: c56313ddebd0d3139296d2cf020296a55061e5f04638e6bdda0cb97ef26f1221

8.
![image](https://user-images.githubusercontent.com/33961641/59163637-a30f5600-8ad1-11e9-8406-ab9fd5a81f28.png)

Offer ID: Q2uWVB-4d0b6db2-283e-4296-a9c5-ba1bf3655c41-071
Creation date: Aug 1, 2018 11:17:13 AM
Maker fee txid: dd0611da872357c38b5921cb750e4827f14b36ac141acc631b5b74cc7c8ca459

9.
![image](https://user-images.githubusercontent.com/33961641/59163653-d225c780-8ad1-11e9-92db-7ff65fc725bd.png)

Offer ID: VEJYCZ-b8275ded-99f6-4dab-bbb0-09b27ffb9858-071
Creation date: Jul 21, 2018 12:06:18 PM
Maker fee txid: 048294843b992119488c3c49d911616adadb7a9ee4f548a35bb8cc3bfb7563c9

10.
![image](https://user-images.githubusercontent.com/33961641/59163667-0bf6ce00-8ad2-11e9-94e7-02aa3e4e54f8.png)

Offer ID: SUNBHSH-633a7123-fc19-4ea1-845e-b37397c85b95-071
Creation date: Jul 5, 2018 7:06:57 AM
Maker fee txid: 1f028200d522b400dc7a5dc82e115460af4ddb66d1bbbe7587de431f6e3701fd

**Comment by KanoczTomas** [comment]
@deadthings that is enough info so it seems, thanks.

**Comment by deadthings** [comment]
May I ask, politely of course, what in $deity's green hell is taking so long?

**Comment by ripcurlx** [comment]
@KanoczTomas Could you please have a look at the request above ^^ - Thanks!

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by deadthings** [comment]
Thank you, guys!

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
