### ISSUE TITLE
Fee reimbursement for trade LBUGUGC

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/support#222]
![LBUGUGC](https://user-images.githubusercontent.com/45130468/55357746-0aa39680-54ce-11e9-822b-c146b0046f72.PNG)

Maker:  626f6f2a639cbca7829c9b1caec8bd46c51a2182aad1835da2ada4514939209a
Taker: 6b7e4da1cf04dab59c7efc3b014550db95cfd202c207128b362de152a55ed531

Bisq version: 0.9.4

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
