### ISSUE TITLE
Fee reimbursement for trade 82826

### ISSUE THREAD

**Issue by EvilGeniusTechnologies** [bisq-network/support#223]
>82826

![bad-transaction](https://user-images.githubusercontent.com/3246877/55809316-8b4c2f00-5a9a-11e9-8ebd-dec0ffe84c62.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

See image above.

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version:  I am using the latest Bisq, and update frequently.  At the time the transaction was initiated, there was a different version.

>_Provide the Bisq client version to help developers identify the causing issue._

I have no reason to think this was a technical issue.  

However, the seller's committing to the transaction and then no-showing means that I should get the amount put up as a deposit, right?  

Currently the unconsummated transaction has just been sitting in my "Open Trades" for weeks.

Thanks for your help.  :)

**Comment by KanoczTomas** [comment]
@EvilGeniusTechnologies could you please update the versioin of Bisq to a number please? The "latest" is always different and is hard to look back for developers when they want to find a pattern. Is the transaction sitting in opened trades and looks stuck? Btw just FYI, you will get back the fee for the maker tx, deposit was not broadcast.

**Comment by EvilGeniusTechnologies** [comment]
My current app version is v0.9.8.  But I don't know what the version was when the transaction was initially agreed to, because this was a few weeks ago and there have been updates since then.

And yes, it's sitting in "Open Trades" with all of the 4 "Trade process" steps grayed-out, and no clickable buttons or anything that's available to do within the UI.

**Comment by EvilGeniusTechnologies** [comment]
Bumping this... any feedback on how I can close out this transaction?

**Comment by KanoczTomas** [comment]
@EvilGeniusTechnologies you can delete the PendingTrades file in the db folder inside the data directory if you don't have any other trades open.

**Comment by EvilGeniusTechnologies** [comment]
Will this lose the funds that I put up as my security deposit?  Or will those UTXOs revert back to my primary Bisq wallet somehow?

Also, how do I find the "data directory" on the MacOS implementation?

**Comment by EvilGeniusTechnologies** [comment]
Bumping this again.  A little feedback on how I can close out this stillborn transaction and get my deposit funds back?

**What I've been told:**
"you can delete the PendingTrades file in the db folder inside the data directory"

**My questions:**
- Will this lose the funds that I put up as my security deposit?
- Or will those UTXOs revert back to my primary Bisq wallet somehow?
- Also, how do I find the "data directory" on the MacOS implementation?

**Comment by HarryMacfinned** [comment]
Mac OSX: /Users/username/Library/Application Support/Bisq 

I prefer let an arbitrator answer for the rest.

**Comment by EvilGeniusTechnologies** [comment]
Thanks @HarryMacfinned.  Could some arbitrator chime in on whether doing the manual deletion as outlined above will preserve my funds that were set aside as a security deposit for this trade?

**Comment by EvilGeniusTechnologies** [comment]
**Bumping this again.** A little feedback on how I can close out this stillborn transaction and get my deposit funds back?

**What I've been told:**
"you can delete the PendingTrades file in the db folder inside the data directory"

**My questions:**

Will this lose the funds that I put up as my security deposit?
Or will those UTXOs revert back to my primary Bisq wallet somehow?
Also, how do I find the "data directory" on the MacOS implementation?

**Comment by HarryMacfinned** [comment]
Data directory on Mac OSX = /Users/username/Library/Application Support/Bisq

**Comment by HarryMacfinned** [comment]
In this 3 weeks old issue, we are speaking about a 0.002498 BTC amount ?
am I right ?

**Comment by EvilGeniusTechnologies** [comment]
Yes, correct.

**Comment by KanoczTomas** [comment]
@EvilGeniusTechnologies please paste the maker/taker txid as typing it from a screenshot is error prone and tedious. The issue template requests this anyways, my bad I did not catch it earlier.
