### ISSUE TITLE
Fee reimbursement for trade reunhrcf

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/support#225]
![reunhrrcf](https://user-images.githubusercontent.com/45130468/55985217-b784cd00-5c9f-11e9-9460-18defc2cc74d.PNG)

Maker:  e32b3ab53202ab64b1f03a4b843a659c4dfe984274ea7e91e5a6b8d5739ce0bc
Taker: 5b814e03961672448afcfa184335d57e76400911c005a4393a6696581fa3e8c9

Bisq version:
0.9.4

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
