### ISSUE TITLE
Fee reimbursement for trade ipuqygj

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/support#226]
![ipuqygj](https://user-images.githubusercontent.com/45130468/55986084-f0bd3d00-5c9f-11e9-8975-51a7b461b503.PNG)

Maker:  536ffed37f88db4a8460c667661a8b2153c298a0ca777ed8fdf0acca81c788fe
Taker: 625336bd916561fc8b127be06de382d725cc78a15380f285bf1e135e98a4145b

Bisq version:
0.9.3

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
