### ISSUE TITLE
Fee reimbursement for trade HWMVH

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/support#228]
![HWMVH](https://user-images.githubusercontent.com/45130468/55986767-60cbc300-5ca0-11e9-8443-1fa110af3427.PNG)

Maker:  d7c38997fac201b263042e28173245755c6ca9df1e9a3df2a2eafb622da5a5c6
Taker: 4b2557d35ee51480f698a7356cdd6896df7c77dd2139c9a8012fd5e9d91d02d9

Bisq version:
0.9.3

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
