### ISSUE TITLE
Fee reimbursement for trade gdxajqq

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/support#229]
![gdxajqq](https://user-images.githubusercontent.com/45130468/55988779-0aad4e80-5ca5-11e9-9ca8-ff6f90d7725e.PNG)

Maker:  f7d3d89a9957aea6938f15799a036e0ef5eb6133ba25aaedb84bcbe685b959f9
Taker: a84852e7882477b83449850b668543240a95eb6642408eaf688515c52353f3b6
Deposit: c60d9f68ad22355eef5d64832f4a2bbafd45578c9dda955b6f29452c3c9fcb72

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version:

0.9.5

Other notes:

tx not issues, closed by arbitrator

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
