### ISSUE TITLE
Fee reimbursement for trade QWORiPP

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/support#231]
![QWORiPP](https://user-images.githubusercontent.com/45130468/55989095-cc645f00-5ca5-11e9-8cd4-2ecb225d60cf.PNG)

Maker:  7a2b3c8c17b6a9aaa17a15a49769d94a68c6ea7586cfb4f08ba270fe0e5deafe
Taker: 4d75d95d963855d846f2774e079c0b43d63e88bcb448d1770e98a7eb4b70c132
Deposit: 129906a0cbe6232f1bdf3a03165b70a8578c3487fc1c6caf0cd60a8827c645cc

Bisq version:

0.9.5

Other notes:

no tx fee from taker, resolved by arbitrator

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
