### ISSUE TITLE
Fee reimbursement for trade AQAZMH

### ISSUE THREAD

**Issue by izzytdi** [bisq-network/support#232]
![AQAZMH](https://user-images.githubusercontent.com/45130468/55989721-41d02f80-5ca6-11e9-8838-075307dca959.PNG)

Maker:  c679114e33a242d5a4b440c86d6904099556d54c8413635a79b4a16f1dfa9783
Taker: b919ea5cc7bbdfb7e33ab6e52928af4af06b046808621c042c8657b9d81c2baf
Deposit: 386285d451a3e5197c7a79e40845bda8e306effa57570a4251680962989a2410

Bisq version:

0.9.3

Other notes:

Bug would not show tx or trade info, closed by arbitrator

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
