### ISSUE TITLE
Fee reimbursement for trade qRmuN

### ISSUE THREAD

**Issue by bioelite** [bisq-network/support#233]
![Skärmklipp](https://user-images.githubusercontent.com/49633823/56113360-ee880680-5f5d-11e9-8e5a-e08921828920.JPG)

Maker:  d2483af8c492b246c851d1f1469e2ad05a7ad2c5c05b93f07d463cc172476855
Taker: e605b67d76fb0ffbaa8f5502d869f8a79ab2621d7ca2c9d15b36c6d710990dc8

Bisq version: 0.9.7

Other notes: Taker fee tx was never published, arbitrator told med to ask for reimbursement here.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
