### ISSUE TITLE
Fee reimbursement for trade 10441

### ISSUE THREAD

**Issue by skibitsky** [bisq-network/support#234]
<img width="861" alt="Screenshot 2019-04-13 at 09 34 59" src="https://user-images.githubusercontent.com/15127974/56216668-896e0700-606a-11e9-8cb0-45d003106ca9.png">

Maker: 867e3c86572778da4e14ad7dd7a7e2d8f62ec69c7677f894437424cdef6301ef
Taker: 24e10178050fe4fd2edeab602478fea1c47ff39a43ab1c597a4bd68be098022c

Bisq version: v1.0.0 (transaction was created on the previous version)

Other notes:
No transaction was published. Orbiter asked me to open an issue here

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
