### ISSUE TITLE
Fee reimbursement for trade PVByYn

### ISSUE THREAD

**Issue by inpharmaticist** [bisq-network/support#237]
![image](https://user-images.githubusercontent.com/49789899/56452787-f1328500-62ea-11e9-8b16-45c914efab90.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 00d928e67735e52596b93f5863bb552a058ba5a116b70ffdc3781a3f04752584
Taker: f65ff1764c0f041dc05b08475ec67ab41c751eb1e17b7f01d41c435bf9aed64a
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version: 1.0.1

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: From the arbitrator "The taker fee tx was not created and therefor no deposit tx. I will close. No funds have left your wallet beside the maker fee. You can ask for reimbursement for the fee at https://github.com/bisq-network/support

Ticket closed on 19 Apr 2019 23:22:11

Summary:
BTC buyer/Maker delivered tamper proof evidence: No
BTC buyer/Maker did ID verification: No
BTC buyer/Maker did screencast or video: No
Payout amount for BTC buyer: 0.003725 BTC
Payout amount for BTC seller: 0.0751 BTC

Summary notes:
Taker fee tx was not created"

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052

**Comment by inpharmaticist** [comment]
Thanks!
