### ISSUE TITLE
Fee reimbursement for trade NN7Xq

### ISSUE THREAD

**Issue by 66300** [bisq-network/support#238]
![Annotation 2019-04-21 165718](https://user-images.githubusercontent.com/49838895/56471855-8ce10400-6457-11e9-8581-e4073025edf8.gif)

Maker: a9f20416a6c8c709ceb073cc4448098ba76824267c4b773d3bd28ccb8eee6236
Taker: e4223847df802ec80e32643f7d6547529fa8d02f9a46360742d326fb56221479
Deposit: 8f9a82d17ea7722b4ac0878848106c6d7d8b58803394fe8d3aedb8df288221e1

Bisq version:

1.0.1

Other notes:

No TX published

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
