### ISSUE TITLE
Insufficient.Money.Exception

### ISSUE THREAD

**Issue by ZedZeroth** [bisq-network/support#240]
![bisq-error](https://user-images.githubusercontent.com/27917163/56550350-500f2d00-657d-11e9-8ef3-d3026d2ea595.png)

Thanks

**Comment by ManfredKarrer** [comment]
Seems your wallet database file is corrupted. Can you withdraw the funds to an external wallet with cmd+e (if you dont have oipen offers, trades or disputes) and start over with a new data directory?

## How to setup a new data directory? 
There are several reasons why users might want to start over newly with a new data diretory:
 - Privay
- Stability
- Performance

### Privay
If you trade a lot and use always the same data directory your onion address is connected with all offers and you might leak more information as you want to. Beside that the wallets transactions easily leak privay on the blockchain level (coin merge).

### Stability
The internal wallet-database can get messed up in certain situations (hard to reproduce issues but there are some open known bugs). This can lead to failed take-offer attempts or failed payouts. Starting over newly cleans up a messed-up wallet-database.

### Performance
BitcoinJ - the SPV wallet library Bisq uses - is not built for high performance use cases and the more transactions you have done with Bisq the heavier the wallet gets. The wallet file becomes larger and writing to disk can become more vulnerable to disk write errors which could lead to a corrupted wallet (there are automatic backups though). SPV sync at startup can take very long if you have not started Bisq for longer time.

## Downsides
There is one main downside if you start over newly: You lose your **local reputation** which is based on your onion address. Beside that, you can only do that if you have **no open offers, trades and disputes**. You can export your accounts and trade history but other data will be also lost in case you make a reset to a new data directory. You should always backup your data directory before doing that, so in case you need to go back you still have access to the old data. You also need to send out the BTC funds to the new wallet. It is NOT recommended to reuse the seed words for the new wallet (you would lose the privacy benefits on the wallet side).

Here are postings about how to switch to a new data directory and how to make sure that you don't lose your account age witness data (for Fiat accounts): 
https://bisq.community/t/switching-to-a-new-data-directory/1697
https://bisq.community/t/carry-over-account-age-witness-to-new-data-directory/5605

### How to keep my onion address and with that my local reputation?
If you prefer to keep your local reputation (other peers see how often they have traded with you) you can copy over the onion key to the new data directory.

Copy the hiddenservice folder from the old data directory and paste it to the new data directory. The data directory structure gets created at startup, so you can quit Bisq quickly after staring up and then copy over the folder and restart again.
```
[PATH TO DATA DIR]/btc_mainnet/tor/hiddenservice
```

### Using multiple Bisq instances
If you want to start up with the old data directory without renaming or copying the data directories you can start Bisq with the program argument `--appName`  (e.g. /opt/Bisq/Bisq --appName=Bisq_old on Linux). By default the data directory name is `Bisq`. You can run multiple Bisq instances in parallel and they are completely separated. All data is kept in side the data directories.

**Comment by ZedZeroth** [comment]
Hi, thanks for the response. I currently have 6 open offers though, so what should I do about those? I have disabled them for now. Somebody here ( https://bisq.community/t/insufficient-money-exception-help-please/7473/7 ) suggested resyncing my SPV file, but it sounded like it might risk messing up my laptop...? Cheers

**Comment by ManfredKarrer** [comment]
Sent you a PM on the Forum....

**Comment by pazza83** [comment]
Closing as stale
