### ISSUE TITLE
Fee reimbursement for trade 84595

### ISSUE THREAD

**Issue by RestartingAdmin** [bisq-network/support#241]
>_The XXXXX part in the issue title are the first 5 characters of the Trade ID._

SCREENSHOT HERE
![Bildschirmfoto vom 2019-04-24 22-34-41](https://user-images.githubusercontent.com/45339461/56692377-5965da00-66e2-11e9-949a-f84e90615367.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: b21df7d0e51bd065d2dce7947b073a609527d872887e73877249ed092baaf098
Taker: 398a9211803f39db0f7364e2fb51016e0c43cc20a53275501904d8d712f2e75d
Deposit: 0.007505

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version: 1.0.1

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
