### ISSUE TITLE
Fee reimbursement for trade 3940305

### ISSUE THREAD

**Issue by 66300** [bisq-network/support#242]
![Annotation 2019-04-28 160624](https://user-images.githubusercontent.com/49838895/56865534-aa6e1a80-69cf-11e9-8ae1-7fba46d4b5b5.jpg)

Maker: 9975c92ce6e0af64986376c0d36861de24f150abd86cd1c78565e5792b53c834
Taker: 9845fe9fc935c5492698f65d965154ae0f51d7eecc1ebe2ba926fc2364566203
Deposit: n/a

Bisq version:

1.0.1

Other notes:

No TX published.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
