### ISSUE TITLE
Fee reimbursement for trade kd3mUhm

### ISSUE THREAD

**Issue by 66300** [bisq-network/support#243]
![Annotation 2019-04-28 193534](https://user-images.githubusercontent.com/49838895/56868008-fda29600-69ec-11e9-8a56-76b0925a0d75.jpg)

Maker:  081a5e2ca4958db8d2a4ac5fbadf27f837856b93f5acd2fd35d0d70eb0ae4a6e
Taker: 3ff590eada08a9c289bd1e5d64ed4d78c56e35e605a033e78398be6685eb2220
Deposit: n/a

Bisq version:
1.0.1

Other notes:
No TX published

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
