### ISSUE TITLE
Fee reimbursement for trade HSJPIRO

### ISSUE THREAD

**Issue by timschabe** [bisq-network/support#244]
>_The XXXXX part in the issue title are the first 5 characters of the Trade ID._

![bisq](https://user-images.githubusercontent.com/40414617/56869184-8fb29a80-69fd-11e9-91c6-59d8dfd18861.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  d317f0dce82b7a9c3929c88af7969cf9337508c7d4b4e6ad544c2dfc0b4ff274
Taker: dd971253dcbe8cd0b1042b9c872b49fa42f07e63025c23464310ce12dc032f5f
Deposit: 0.001120

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version:

v1.0.1

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
