### ISSUE TITLE
Fee reimbursement for trade 5901411

### ISSUE THREAD

**Issue by jojojojojojojojoq** [bisq-network/support#245]
>_The XXXXX part in the issue title are the first 5 characters of the Trade ID._

![image](https://user-images.githubusercontent.com/50211853/57092307-f666db00-6cbf-11e9-8547-eb8f6fcccd30.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by jojojojojojojojoq** [comment]
Additional info: 
Maker: edaf09109d76c6a553ff4e3248447a1f4fbea8aa2c3d7f558ee0560e9e58040f
Taker: 71a1ca7413aecdee8ec30ce7f07f0f7257007f7827d201192836080f9259d93c
Deposit: 0.008561
BISq VERSION: v1.1.0

**Comment by KanoczTomas** [comment]
@jojojojojojojojoq please supply the deposit transaction ID. The amount is not needed, it is on the blockchain if the tx got published.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
