### ISSUE TITLE
Fee reimbursement for trade PJGJtVg

### ISSUE THREAD

**Issue by BitcoinTraderWorld** [bisq-network/support#246]
>_The XXXXX part in the issue title are the first 5 characters of the Trade ID._

![Fee reimbursement for trade PJGJtVg](https://user-images.githubusercontent.com/50214091/57102762-8b032480-6d24-11e9-8e98-d61b09d1924a.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  9a508ba070a84eb1604cee0309abf0c368e78acbf286a7eb163ec80b3a2e9e1a
Taker: dc4fac11cde048fe2da27223547d01296a4945285977666f138276ee34ae75ec
Deposit: 0.002350 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version: v1.0.1

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
