### ISSUE TITLE
Can't start Bisq. Duplicate transaction error.

### ISSUE THREAD

**Issue by yourwpguy** [bisq-network/support#247]
v1.0.1 Windows,

![screen-008](https://user-images.githubusercontent.com/16023758/57110234-792f7a80-6d40-11e9-90c5-34a37faa65d6.jpg)

**Comment by HarryMacfinned** [comment]
I suggest you go to settings/network info -> delete SPV file and resync.
(Backup etc before).

Please be aware that if your wallet is old this make take time (hours) and eat all the CPU.

**Comment by yourwpguy** [comment]
I have two open disputes and one open trade. When I delete SPV file and resync, will I be able to see these open disputes and trade? I'm afraid to lose something.

**Comment by HarryMacfinned** [comment]
Theoretically you shouldn't lose anything.
But maybe it's however better to wait that the open trade is closed.
(in any case, backup, backup better too often than not enough).

**Comment by yourwpguy** [comment]
That open trade was expired and the buyer didn't send any fiat, but I didn't open a dispute on this.

**Comment by yourwpguy** [comment]
Which directories should I backup? And how can I go to settings/network info to delete SPV file, if Bisq doesn't start normally or doesn't load further. I can only delete old Tor files.

**Comment by HarryMacfinned** [comment]
ah yes. I didn't read properly the title. Sorry.

on Windows, the Bisq data directory is at:
Windows 7,8,10: C:\Documents and Settings\username\AppData\Roaming\Bisq 
Windows XP: C:\Documents and Settings\username\Application Data\Bisq 
or something like that.
...
I'll post the detailed path to go in minutes.

**Comment by m52go** [comment]
Deleting and rebuilding the SPV file will definitely _not_ affect open disputes or open trades. But still, make sure you make a full backup of the directory before doing anything.

Data directory locations are listed here:
https://docs.bisq.network/backup-recovery.html#back-up

The specific location of the SPV file is also [specified](https://docs.bisq.network/backup-recovery.html#resync-spv-chain) in that doc: 
`btcmainnet/wallet/bisq.spvchain`

If that doesn't work, you might want to try restoring a wallet backup as HarryMacfinned described above (further detailed [here](https://docs.bisq.network/backup-recovery.html#restore-wallet-backup)).

**Comment by yourwpguy** [comment]
Just deleting bisq.spvchain didn't work. The same warning: "Wallet contained duplicate transaction".
Then copied/pasted the last backuped wallet I know which was working.
Now I can start Bisq and resync.
And also getting now:
1) the error in the image bellow - "Inconsistent wallet sizes". This error showed up after I had a failed trade with a blocked scammer and before this warning: "Wallet contained duplicate transaction".
2) "Error at traderSignAndFinalizeDisputedPayoutTx"

Bisq is running, but what to do now to be sure everything is fine?

![screen-003](https://user-images.githubusercontent.com/16023758/57136151-8d14c400-6db4-11e9-801d-5e0681cbd271.jpg)
![screen-015](https://user-images.githubusercontent.com/16023758/57136162-9867ef80-6db4-11e9-8c9c-79e27e8d64fd.jpg)

**Comment by pazza83** [comment]
Closing as stale
