### ISSUE TITLE
Bisq wont connect to peers-cant mark payment started

### ISSUE THREAD

**Issue by jojojojojojojojoq** [bisq-network/support#248]
Im working on bisq 1.1.0; 
Versions of subsystems - Network version: 1; P2P message version: 10; Local DB version: 1; Trade protocol version: 1
Windows 10 Pro

I accepted an offer to buy and put through the bank transfer. The issue that occurred is that when I opened Bisq up to confirm payment started the app is stuck on trying to connect with peers(gets to 8 and falls down again). I try to open an issue but of course it wont allow me until I'm fully connected to the network. I'm stuck in a permanent limbo it seems.

The latest update was released around the time the trade was initiated it seems and Isince went ahead updated, but to no avail. i cleared the SPV file & resynced to no avail. I used provided bridges and custom bridges on Tor and nothing. I left bisq running a many hours and nothing. I also backed up bisq, uninstalled and then reinstalled with no change.-Id like to see if theres corrupted files in there or something.

A curious aspect is that when I click on the info button on the trade it indicates that FIAT is SENT, yet I still have the option to click on payment started option. The trade is 4 days old now and Im worried I may lose my money.
I also have a separate support issue on here where a trade stalled due to connection issues and I have btc locked, im waiting for help with it. 
Any help would be greatly appreciated.

**Comment by pazza83** [comment]
Closing as stale
