### ISSUE TITLE
Fee reimbursement for trade hkuthz

### ISSUE THREAD

**Issue by PeterSurda** [bisq-network/support#249]
![Screenshot_debian9_bisq2_2019-05-06_13:23:25](https://user-images.githubusercontent.com/3815204/57222380-9dba7980-7002-11e9-88bd-940d0c78a04c.png)
SCREENSHOT HERE

Maker:  2f661bfafd067ca779903994463d45d12b1013fe24a7149e6c0e4de2585be1e0
Taker: 7b1e0bf10f5fa587b1f54b2a18b5ac7cee1c27dfff33c2db8affe9766b0e00d9
Deposit: N/A

Bisq version: 1.1.1

Other notes: Taker TX not broadcasted

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
