### ISSUE TITLE
Fee reimbursement for trade 9296273

### ISSUE THREAD

**Issue by PeterSurda** [bisq-network/support#250]
![Screenshot_debian9_bisq2_2019-05-06_13:20:12](https://user-images.githubusercontent.com/3815204/57222454-e7a35f80-7002-11e9-8068-abf1de5921ad.png)

Maker:  d3d7edadd482caf18f40282bd273aebab325dfa99bbafd0af2775a07e877b217
Taker: 5b12cfb19cd2bae6b38c819c04b5cdf65dfc8b66d5ae0bb8c0f8a7fc92ee7049
Deposit: N/A

Bisq version: 1.1.1

Other notes: Taker TX not broadcasted

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
