### ISSUE TITLE
Batch Fee reimbursement for 20 trades

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#251]
Overview of failed transactions:

![](https://images2.imgbox.com/95/95/HuaL8zXR_o.png)

Details:

![](https://images2.imgbox.com/b5/2d/ZvYSwJp3_o.png)
Trade ID: hjgv9-fd295b12-fc7a-44b4-8b57-fbff2d0860e8-094
Trade date: 26 Feb 2019 22:08:26
Maker fee txid: 3b24babc0223b0df21f48f7cd0416fc4dfba6d2ac18278365ad7b346448d47b6
Taker fee txid: 1bae604aba42a426acc2cdeb5abf28af1bea6260384a38e87f7b40c22a702333
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED
____________________________________

![](https://images2.imgbox.com/99/27/C5Gpvmao_o.png)
Trade ID: YGRVRT-6ed2d7d4-ccb3-4d3c-82ab-c0a95f311e38-094
Trade date: 27 Feb 2019 00:39:44
Maker fee txid: a2b0cdebd2dfa9e2652c3af00b49395b55aaed7351b618c15168857e9fc64471
Taker fee txid: 0a0c89673f7643b711677b14cc55c2e62426b66ac1d41f47fff3e8845655ad5c
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED
____________________________________

![](https://images2.imgbox.com/a9/dd/AnF7yFZY_o.png)
Trade ID: JGFYOF-3fcb9cde-1aaf-4614-bc9a-6b04dd2d1dfa-094
Trade date: 4 Mar 2019 19:44:21
Maker fee txid: 3f63328356a209516e688971bdf283c5f6f1932bcbcc960c40058066f1e23609
Taker fee txid: 938df91988b239bb37c7a77fb8e2842066db477d96732912b35cc3cc1affccff
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED
____________________________________

![](https://images2.imgbox.com/02/c4/udxIVnCV_o.png)
Trade ID: 79961-638d6b87-5d5c-4db0-bee2-0eff6512f32b-094
Trade date: 4 Mar 2019 19:49:42
Maker fee txid: 5724b202a983afc92ebc6965203ce8284cd964f084384a271d33acafe84d1e4d
Taker fee txid: 216b7881627abdcdc8b86604b7a35b101a25c37b86235ea80194b7fb00703a3d
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED
____________________________________

![](https://images2.imgbox.com/e1/10/fH0S4hyC_o.png)
Trade ID: 17946-a1615c11-ade9-4399-ba7d-e31ea8d9aab7-094
Trade date: 4 Mar 2019 19:53:38
Maker fee txid: 8be41a5eada9cb01717f9185ba201ca6f3a434d475e02a000ac63bb3cd3143ec
Taker fee txid: e78d820963515396119e3885d93e6cd3f0337b1cc1aa3d98a06e765e90713f07
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED
____________________________________

![](https://images2.imgbox.com/4b/6a/QCiPGk4w_o.png)
Trade ID: 64136721-de38492e-d19b-4820-85a2-90f7d10b38df-094
Trade date: 4 Mar 2019 19:56:26
Maker fee txid: 9ac06d710fdb2442c7bf856374dd5856774252cf5b268e3b7dfadb3e9fdd5b70
Taker fee txid: 0f7aa29b14d69203307ffaa1b9748c30d5630ed3290bef7ccb2de5d431c670ad
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED
____________________________________

![](https://images2.imgbox.com/23/d2/GyEUFXMF_o.png)
Trade ID: onanux3-5c2a68ca-a389-4eec-8be9-425754f00412-101
Trade date: 26 Apr 2019 01:17:48
Maker fee txid: deadbe4032137ea73d1c894c2537a7e98f533c6eaf86b8880f8c6b65da6c4784
Taker fee txid: 6abbfdc3e86f846c6126bda640355389924c8361b17e74e060116671a4739684
Error message: An error occurred at task: TakerVerifyAndSignContract 
Exception message: Contracts are not matching
Trade state: TAKER_FEE_PUBLISHED
____________________________________

Trades that failed and had a support ticket opened with faulty fees or deposit tx but did not show up under the failed tab.

![](https://images2.imgbox.com/ac/94/yq6t9n9k_o.png)
Trade ID: 87732-b2e0e5e7-f48b-4c14-bcd0-6ebd93833d86-101
Trade date: 17 Apr 2019 23:54:27
Maker fee txid: 7836c361e38fa45c55752d186f3738951420167e0379823d99403b3aabcecfd8
Taker fee txid: 0c77e57ef84e72b7a7ed5472ca27a2c5fb75f08cbf03f0b2c5899748d49aa5ef
Deposit txid: 031f9b6a4b24c112d90453686d1cca6e31ce899f9408d4fb7b60d46ff55bb023
Contract hash: f2bb22459c16cc9e6024546b5067383f6d141db29cab5c2b9fd4215b2cb69457
Note: Trade failed because deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/eb/bc/TQydZRCZ_o.png)
Trade 1815987-00b4eff2-fe9b-45b5-af4c-64654c33c2a3-101
Trade date: 18 Apr 2019 00:15:08
Maker fee txid: f1c12356f098d0a41f12640c7058b3c2da3baddba608684dd2060986bf8056bf
Taker fee txid: bf85035fe02953f9c194e46dbb34ac1a3868d25717bf78ce50fcf62d29e39795
Deposit txid: 435e485bbe68d2f5f6b03723e1b3a667b0d720b49a7ec43d5f94cd9745e57717
Contract hash: d726a517c99e7c010fefa9f48cf28016453d63bbac45ee4a8a151b49ee78f056
Note: Trade failed because deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/83/83/6YQKYyCl_o.png)
Trade 85560987-cce0838c-5dcb-4631-a225-8adcfa7a3180-101
Trade date: 18 Apr 2019 20:38:31
Maker fee txid: 6b9d7279f211c7b883d99a102dcceaea46d869170ff1e72507a01d69c5d232fb
Taker fee txid: b119540611b156071309df33509f7ad61be69157b9822d4319a0009a48cb0b05
Deposit txid: c822509531e4ea3f0498c58b9a756816b9f2d283f6b42d000948eb24931fa02d
Contract hash: 37febaffc49098e92bf24d50fb7ec215d98f57ccbc06057350f3bbd9266cc10c
Note: Trade failed because deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/ca/5e/h3jA4uR0_o.png)
Trade xl0VNZ-38b191a7-b199-46b8-9385-5feb787a7b0e-101
Trade date: 18 Apr 2019 20:38:58
Maker fee txid: 97ef2c003c948f4d629266e6dc73caf9b1be437e0ec93d748dd1766beb7f3c87
Taker fee txid: 903452c36aa8cda128371ea9fab6b86d5c6d2924cc8e3c353e6fe6294c98f920
Deposit txid: f30affb13245a52df20bf5c922cc63ccd8a617fffc84d56855753d44b93360c7
Contract hash: 247711e3cf511b2b249aef0aa70c3f1e703d1006594695f451d65d065c00e20e
Note: Trade failed because deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/4a/2c/6O9EaeGy_o.png)
Trade 928287-c85304cf-099d-44b3-9b45-c422427bc164-101
Trade date: 22 Apr 2019 22:51:24
Maker fee txid: 403e34a2c1997fa644ef5d6fd42d5566e24d204ea56b5de199a894e7eca4b1dd
Taker fee txid: 0b53a462ddc9c65a1371a8cd1505dd3b49be948161e75fe4ab6bba1296c91b61
Deposit txid: db8d28149076f862064d5f91201ecbcbee9b5324762cef07779df96b17ec2d9d
Contract hash: dbf6be1a0e9d9c7f2198ab09fdfc8d346a34c8ed2873986b132c302ff7822122
Note: Trade failed because maker fee and deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/1f/1d/HUZPo0wR_o.png)
Trade 81178-0d7bb1e9-0b89-4fe9-b343-24a51b2d84f2-101
Trade date: 22 Apr 2019 22:36:10
Maker fee txid: e69232e72d5af97727ef57c738e350db337c049ebc6c786702d450370d043d6d
Taker fee txid: 252948cff676db4748e839a681903b6680113868a6ad8d0a8a16e990f8016344
Deposit txid: a50bb0d8db456a2e72f3bb7c061f68df8e0d1cdbbb14ed14137b83ca2af0f031 (randomly selected to be able to open support ticket)
Contract hash: 3bf690aaa7968a67834d7fa77354c10db7e94388e97b76f0ee84e18a842c7c15
Note: Trade failed because maker fee and deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/83/10/VOWbPfFT_o.png)
Trade 08425-50d254ba-8900-4616-843f-096086bc4534-101
Trade date: 22 Apr 2019 22:36:24
Maker fee txid: 5769723a51c9355f6112af170a0fcbdcca5fd9cab5ae03418f09fb388266c523
Taker fee txid: 9b56114fd9a14cccd28092a673a56cfbb3ff2cb172b0c9cc641f0de942fa2e81
Deposit txid: a50bb0d8db456a2e72f3bb7c061f68df8e0d1cdbbb14ed14137b83ca2af0f031 (randomly selected to be able to open support ticket)
Contract hash: 7a8fd2f5d24c59645ff8eaebd322835ff3e58527e99f80d18e7357ea1476e13f
Note: Trade failed because deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/7b/3c/wa0UndKu_o.png)
Trade owijphe-f374ab29-41ef-4e48-8bc5-472cd05b1b72-101
Trade date: 22 Apr 2019 22:36:43
Maker fee txid: 04d3b8e856d267dd971acfe038598bf331cf8152e7087baba6b2e7071d28d8da
Taker fee txid: ef3783c699337c31e4e2ab467096294607e986859c9c5f11ab547d64f792c6cf
Deposit txid: a50bb0d8db456a2e72f3bb7c061f68df8e0d1cdbbb14ed14137b83ca2af0f031 (randomly selected to be able to open support ticket)
Contract hash: bd18eaf8b3484b26b38c12004168fca6a631e951eefae4f02a0b030dc258a3b2
Note: Trade failed because maker fee and deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/5b/39/cLMhF55f_o.png)
Trade G3qge-3d20c802-fc1c-47b8-a60c-ca115a12701d-101
Trade date: 22 Apr 2019 22:51:38
Maker fee txid: 707d3bd5f84fb8325966f621c904a25a0075e33ace6a5c08c13185e6fa387dd6
Taker fee txid: 276f7064fb545f1df197a6036cd783f19f03dd5b7bbcff13cff81019bfa6b178
Deposit txid: a50bb0d8db456a2e72f3bb7c061f68df8e0d1cdbbb14ed14137b83ca2af0f031 (randomly selected to be able to open support ticket)
Contract hash: 873637577cb9be63336ef23d880d89e382b366cd49b0fb16c2078400eb85763c
Note: Trade failed because maker fee and deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/a3/a6/jmNfHmKK_o.png)
Trade 806594-3efc1624-0f06-4fc9-a306-415dd2b3f724-098
Trade date: 16 Apr 2019 20:34:44
Maker fee txid: cef192a42c5a6cbc13401550182bc29aa1b39121b65e60153831193fda1e78da
Taker fee txid: 3cbf86f7ce5da7fed116bb90ca8ec24ba8b41593a923a59656f165ef3807bd76
Deposit txid: a50bb0d8db456a2e72f3bb7c061f68df8e0d1cdbbb14ed14137b83ca2af0f031 (randomly selected to be able to open support ticket)
Contract hash: b17e92e321a79d31b196f657d84f6587a07547c65a1b45b3892d57a163994391
Note: The trade fee transactions did not lead to the deposit tx. So no funds ended up in the MultiSig. 
____________________________________

![](https://images2.imgbox.com/af/6f/iJWlIVFj_o.png)
Trade ROCD7U-616fd94e-229e-46d5-b2fd-23d9b24c41b9-101
Trade date: 22 Apr 2019 23:35:38
Maker fee txid: 182f3addd7ac93ebc75bf64acbeb2183c217860a1238adaeb90b039c4deb0b2f
Taker fee txid: 6b137b40e014893596232f3a4526c8e9cfb6c80ee3972656276025d7e494a37f
Deposit txid: db8d28149076f862064d5f91201ecbcbee9b5324762cef07779df96b17ec2d9d
Contract hash: cc55253676d51167ac32a39c8f2d0b3b01d254ebf4e1edb67dc77c2d4b1f2eec
Note: Trade failed because maker fee and deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/04/2e/cJr00tHP_o.png)
Trade OIDOMNPQ-32056c9e-23a4-4a44-8066-08bcf6aa0f29-101
Trade date: 23 Apr 2019 19:42:46
Maker fee txid: 8067efceda5bdc3f52e9b8a8ebda57a08c81cbe934a4f6cefaaf354b12e653b3
Taker fee txid: 5cd5420df0a051037175d3d733845152ee06beed53bf399e696776b73269a9b9
Deposit txid: a8a4ca09bdb3ca478bfcd57e510fe9c924288361401d1aa2288aa69be11450bc
Contract hash: 361c287cca3ad3275f0472819ac028e857e4e6dd1e95723434ab4c0fe8cefbad
Note: Trade failed because deposit tx was not published.
____________________________________

![](https://images2.imgbox.com/6a/0b/a9sn5NaU_o.png)
Trade onanux3-5c2a68ca-a389-4eec-8be9-425754f00412-101
Trade date: 26 Apr 2019 01:16:32
Maker fee txid: deadbe4032137ea73d1c894c2537a7e98f533c6eaf86b8880f8c6b65da6c4784
Taker fee txid: 6abbfdc3e86f846c6126bda640355389924c8361b17e74e060116671a4739684
Deposit txid: 3e64d9a08540e1cce98e0e95ee02363ba249102361534b935a6fa4bb798e8d11
Contract hash: 50db5fb976adf8ca6be1e6b2d1e82230eb4772c344bf6081ebbaf89a53594f10
Note: Trade failed because deposit tx was not published.
____________________________________

**Comment by KanoczTomas** [comment]
The last screenshot was duplicate,ignoring.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
