### ISSUE TITLE
Fee reimbursement for trade 2235044

### ISSUE THREAD

**Issue by R5fan** [bisq-network/support#252]
![image](https://user-images.githubusercontent.com/1439530/57697469-95da8500-7653-11e9-9b8c-00a0142ec413.png)

offer ID 2235044-c5d0fb54-f1bd-4813-890f-4ebe74127de4-111
Maker: 4ee9b9ec515549d72fa1b3e859ab6ea750930631cce0d661da17a5b3357475ca
Taker: 24099c85c7592124255ae7fcb4ea688d60af3a6822b4d898a9f990cad0641ea7
Deposit tx: 1f76cec2ab80e9eda195cdb774e668e3bcd6fc06f040e3a60104d9333f35fca7

Taker fee transaction was never broadcast, according to the arbiter because we were not both using v1.1.1. This may be true, but its also worth pointing out I made that payment account that very day (0 days old), and I suspect that may be the real reason

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
