### ISSUE TITLE
Fee reimbursement for trade mWpvw

### ISSUE THREAD

**Issue by R5fan** [bisq-network/support#253]
>_The XXXXX part in the issue title are the first 5 characters of the Trade ID._

![image](https://user-images.githubusercontent.com/1439530/57697927-a0e1e500-7654-11e9-813e-f7fa9f8e3226.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ace769e8478639937ba0ef80eb85d6665dea6ae0fad95cc84d194243aa9dbc67
Taker: 1c4a42d8f565f28a7ca3769df02432d2ac10311ed26b8cd6e06e56329e5c36ab
Deposit: 1f76cec2ab80e9eda195cdb774e668e3bcd6fc06f040e3a60104d9333f35fca7

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version: 1.1.1

>_Provide the Bisq client version to help developers identify the causing issue._

Taker fee transaction was never broadcast, according to the arbiter because we were not both using v1.1.1. This may be true, but its also worth pointing out I made that payment account that very day (0 days old), and I suspect that may be the real reason

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
