### ISSUE TITLE
Fee reimbursement for trade gposgy

### ISSUE THREAD

**Issue by R5fan** [bisq-network/support#254]
![image](https://user-images.githubusercontent.com/1439530/57698190-51e87f80-7655-11e9-81e0-6ead379e02f6.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 6002ddeed26de4bdf557fd8cb660d9923c158fd2ecde79733b0e6cad62d6d994
Taker: 45d7489f64e98f0a2498bc394abc662d5c96e07b4ae4b7cf572767f4b6068843
Deposit: 1f76cec2ab80e9eda195cdb774e668e3bcd6fc06f040e3a60104d9333f35fca7

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version: 1.1.1

>_Provide the Bisq client version to help developers identify the causing issue._

Taker fee transaction was never broadcast, according to the arbiter because we were not both using v1.1.1. This may be true, but its also worth pointing out I made that payment account that very day (0 days old), and I suspect that may be the real reason

**Comment by KanoczTomas** [comment]
Will be reimbursed with #221

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/221#issuecomment-497958052
