### ISSUE TITLE
Two trades stuck for 4 days.

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#256]
I have two open trades that have been stuck (unconfirmed by seller) for 4 days now!
I've opened a dispute to the arbitrator twice and provided proof of payment but i'm not getting any reaction.
There's a considerable amount of funds locked up which i'm unable to trade right now, causing notable losses.

Can anybody assist?

**Comment by HarryMacfinned** [comment]
@invertedbobb ,
Look at the onion address of the concerned arbitrator, do a search on the forum with this onion address, and you'll find who the arbitrator is, and then you can ping him.
Or you can mention the onion address here, and we'll tell you the arbitrator is, and ping him for you.
(From time to time some messages are lost and then the arbitrator got nothing, and he must be contacted from outside the appli).

**Comment by invertedbobb** [comment]
Selected arbitrator is: g72ouph23eznvpuz.onion

**Comment by HarryMacfinned** [comment]
I sent a message to the concerned arbitrator.

**Comment by invertedbobb** [comment]
I've sent a direct message to the arbitrator too on bisq.community. Still no reply, not here, not on the Bisq community, not in the dispute ticket.
I see the last activity was June 5th, this is getting me quite worked up and concerned. 
How can i get this resolved???

**Comment by HarryMacfinned** [comment]
I sent a personal message to Arbitrator2.
Arbitrators are not (always) on the deck 7days/7, sometimes they took their weekend off.

**Comment by arbitrator2** [comment]
@invertedbobb Hi, I'm really sorry for the delay, for some reason when you reopened the dispute it never opened on my end. The ticket was closed on the 18th (6 days ago) and as you can see on the dispute itself the btc was in fact sent to you on the first place (the btc buyer). If it's still locked on your end you can delete SPV file and resync on your settings and see if it shows correctly from then on. If not, please notify me. I hope I could help and I'm sorry you had this inconvenience.

**Comment by invertedbobb** [comment]
Thanks for the reply, i've responded on the bisq community page.

**Comment by KanoczTomas** [comment]
Closing as resolved, feel free to reopen when needed.
