### ISSUE TITLE
Error starting Bisq: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by MwithM** [bisq-network/support#257]
OS: Windows 10.
Error displayed at inicialization (after asking password): java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.

![imagen](https://user-images.githubusercontent.com/50149324/60086364-39cb4c00-973b-11e9-9b6f-70e5c1512be1.png)

I tried to copy and paste Bisq directory to Ubuntu and the same error appers. Also removing Tor archives as Bisq suggested, but it looks a java mistake.

**Comment by sqrrm** [comment]
That looks like a bitcoinj exception. As always, start by making a backup and then try 'delete spv file and resync" under settings > network info.

**Comment by MwithM** [comment]
The issue is before introducing the password and after this message, I get the option to erase Tor files or connect to a bridge. I can't get to network info to delete spv file.

**Comment by sqrrm** [comment]
Right, that makes it hard to delete the file through the UI. Then, after making a backup, delete wallet/bisq.spvchain and start again.

**Comment by MwithM** [comment]
Solved deleting wallet/bisq.spvchain.
Thanks a lot.

BTC/EUR over 10.000!
