### ISSUE TITLE
BSQ explorer stuck at june 5th

### ISSUE THREAD

**Issue by MwithM** [bisq-network/support#258]
First of all, sorry if this is not the correct place to report this.

https://explorer.bisq.network/index.html#here is displaying only transactions until june 5th. It was reported by someone on #general slack channel.

**Comment by sqrrm** [comment]
@MwithM Thanks for the report. The seednode crashed and had to resync from genesis so it's still working on catching up. There is also https://explorer.sqrrm.net/ which is working fine.

**Comment by m52go** [comment]
https://explorer.bisq.network is stuck again.

**Comment by sqrrm** [comment]
@m52go It's parsing from genesis and that takes a while. Catching up slowly. Something will have to be done to make it more stable and probably good to make it parse faster as well. There is always https://explorer.sqrrm.net/ as a backup.
