### ISSUE TITLE
Fee reimbursment for 4 trades.

### ISSUE THREAD

**Issue by humblekant** [bisq-network/support#259]
Overview of failed transactions:

![image](https://user-images.githubusercontent.com/52288167/60273852-4dbbad00-98f7-11e9-8eed-a317c083bb7c.png)

Details
![image](https://user-images.githubusercontent.com/52288167/60273896-62984080-98f7-11e9-988b-19e0259dd99f.png)

Trade ID: cpdenK-8e0476d9-8d18-4356-aa7d-cf02ea1ef927-112
Maker fee txid: 101f599e49b5d58ff5b28910f46310dc39e00476d08862b5494cf8f87a98975a
Taker fee txid: fbd3c01f5c85b90f90b4637fb82afe6ed990141b166ea646409f7ba745b5bf83
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

![image](https://user-images.githubusercontent.com/52288167/60274011-970bfc80-98f7-11e9-973d-d21e95517573.png)

Trade ID: cpdenK-8e0476d9-8d18-4356-aa7d-cf02ea1ef927-112
Maker fee txid: 101f599e49b5d58ff5b28910f46310dc39e00476d08862b5494cf8f87a98975a
Taker fee txid: 590b6f4dbcad92c2d7d11281b34edf4bc51c91e3d557b9f972d99d0667c25214
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

![image](https://user-images.githubusercontent.com/52288167/60274098-c0c52380-98f7-11e9-8fba-f31d9cb9b60d.png)

Trade ID: cpdenK-8e0476d9-8d18-4356-aa7d-cf02ea1ef927-112
Maker fee txid: 101f599e49b5d58ff5b28910f46310dc39e00476d08862b5494cf8f87a98975a
Taker fee txid: fdeccac854f0e2164279da18a8d2f0b3d5735bfbcc37c168d1e565137b5d9e5a
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

![image](https://user-images.githubusercontent.com/52288167/60274151-dc302e80-98f7-11e9-8682-3f2e1ab5159a.png)

Trade ID: cpdenK-8e0476d9-8d18-4356-aa7d-cf02ea1ef927-112
Maker fee txid: 101f599e49b5d58ff5b28910f46310dc39e00476d08862b5494cf8f87a98975a
Taker fee txid: 83328552a5725ed12b7784bbfa4e91491731c4689a117bfd9b0fdb76541a0672
Error message: A timeout occurred.
Trade state: TAKER_FEE_PUBLISHED

BISQ Version.  0.9.1 

Cheers

**Comment by humblekant** [comment]
Hello?

**Comment by arbitrator2** [comment]
hi, it looks like I'm your arbitrator but I can't see the dispute for some reason. I need you to go on the dispute and click on cmd + o (ctrl + o if its not a Mac)

**Comment by humblekant** [comment]
Hello, I didn't open a dispute as the trade was never actually taken. I am missing a total of 0.00164518 BTC.

**Comment by arbitrator2** [comment]
did you download the latest version of Bisq? or are you still using the 0.9.1?

**Comment by a123b** [comment]
No need for arbitration. The trades never happened, but trading fees were paid.
@KanoczTomas is the one who needs to look at this, right?

**Comment by humblekant** [comment]
> did you download the latest version of Bisq? or are you still using the 0.9.1?

I am waiting to complete my active trades before updating to avoid any risks.

**Comment by KanoczTomas** [comment]
@a123b correct ... I added this to my todo.

**Comment by humblekant** [comment]
> @a123b correct ... I added this to my todo.

Hello, were the funds even reimbursed? They never showed up on my account.

**Comment by humblekant** [comment]
Hello?

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
