### ISSUE TITLE
Popup window does not close (keeps popping up)

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/support#260]
In the "create offer" window (when clicking on "create new offer to buy BTC with USD"), if I enter an invalid amount in the "amount of BTC to buy" field, I get a popup message with an error (see below).

When I close the error message, it closes but then pops up again. This happens repeatedly, so I can't really close that window, and have to force quit the Bisq app.

![bisq err](https://user-images.githubusercontent.com/52383635/60411332-07a36980-9bd5-11e9-9742-b0693440d4f8.PNG)

**Comment by HarryMacfinned** [comment]
Thanks for reporting.
Under which OS does this happen ?

**Comment by arbitrator2** [comment]
do you have the latest version of Bisq installed?

**Comment by Drazen-V** [comment]
Win 10, latest version: 1.1.2

**Comment by devinbileck** [comment]
Potential duplicate of https://github.com/bisq-network/bisq/issues/2835
