### ISSUE TITLE
Cannot place order - error "Could not decrpyt bytes"

### ISSUE THREAD

**Issue by R3ktl355** [bisq-network/support#261]
My Bisq was running very slow so I decided to switch to a new data directy.
I backed up everything then imported new accounts into Bisq. I also copied over sig.key so I could keep my account ages. I also copied over Bisq_bsq.wallet after I noticed all my BSQ was missing, that fixed that issue.

Now when I try to make a new order I get error "Could not decrypt bytes". Any idea what the issue is?

EDIT: It appears this is related to BSQ ..I do not get the error if I choose BTC as fee payment. Did I move the BSQ wallet over incorrectly?

**Comment by sqrrm** [comment]
@R3ktl355 Could you describe the steps you took to move to a new data directory in more detail? Looks like the signing of the BSQ fee transaction fails. Are you using the same wallet seed?

**Comment by R3ktl355** [comment]
I just sorted this out. I had to reinsall the old directory and send all my BSQ over from the old wallet to the new BSQ wallet.

**Comment by sqrrm** [comment]
Indeed, the BTC and BSQ wallets use the same seed so it's not possible to just move the wallet file if you generate a new wallet. Glad it worked out.
