### ISSUE TITLE
Fee reimbursement for trade sffoee5

### ISSUE THREAD

**Issue by xandermccormick** [bisq-network/support#262]
![Screen Shot 2019-07-18 at 12 43 38 PM](https://user-images.githubusercontent.com/52983020/61475845-b4157780-a959-11e9-92d5-f4910edf860d.png)

Maker: f8f6786288eb92db15712186388763a00215e79d9213e66132d6118c57efb120
Taker: a7096f5761fb5af7589b7f9cb07625cb9666df7788ae6daa4034a3c4e0a1023c
Deposit: de8eb88462aa2d4d94ab9e5534152af7910637ef8c7c1dc6d6bc1a985ed8770b

Bisq version: 1.1.3

Other notes:

I contacted the support team and they told me the tx was "buggy", and needed to be cancelled.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
