### ISSUE TITLE
Fee reimbursement for trade 74972

### ISSUE THREAD

**Issue by savyasachi16** [bisq-network/support#263]
<img width="901" alt="Screen Shot 2019-07-20 at 4 18 25 PM" src="https://user-images.githubusercontent.com/25380661/61596319-87aa6700-abb6-11e9-8a81-3e945975b38b.png">
<img width="1191" alt="Screen Shot 2019-07-20 at 5 51 39 PM" src="https://user-images.githubusercontent.com/25380661/61596308-72cdd380-abb6-11e9-898a-2c59a9bae721.png">

Maker:  43809fb7f06af14cb3b837a3083f25dde9028c0eca8c7acfd5599c72f214a904
Taker: 2e0c9fd2869c597f7d1d5e20589bced522b05d4490385ace63699fcfbbcf0dd9 [Visible but does not exist on blockchain].
Deposit: 9c18bb8eaa2d630da89fad2576697d661ff4e8770d0779d6908ba21aaf18c094

Bisq version: v1.1.3
Other notes:
 Deposit Transaction ID was not generated/shows as blank as seen in screenshot.
Raised support request, resolved, and got back the locked up BTC for the trade.

**Comment by savyasachi16** [comment]
Update: I noticed that it happens only with the latest version of Bisq v1.1.3.
Downgraded to earlier version v1.1.2. Opened a new trade it has worked without issues. Opened another trade on v1.1.3 and the issue repeated itself. I will raise reimbursement request for the second buggy trade once the ticket for it is closed.

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
