### ISSUE TITLE
Fee reimbursement for trade 18112

### ISSUE THREAD

**Issue by savyasachi16** [bisq-network/support#264]
<img width="1263" alt="trade 2" src="https://user-images.githubusercontent.com/25380661/61674498-f667ed00-aca8-11e9-8d8b-1f863299dba4.png">
<img width="1146" alt="trade2" src="https://user-images.githubusercontent.com/25380661/61674499-f7008380-aca8-11e9-847d-f634ab11cdac.png">

Maker:  2a59f099c450335cdf66bd109a47e259ad81795cd3fe698f2dfa220b28521033
Taker: d6a86891fec7140ffc6568349d1d1fbc32f2331e923b8b366a97b150a8052eb2
Deposit: 73f536fee12fa4168e7d0425c8cd95bcf739a178444399837d815d52534de22d

Bisq version: v1.1.3
I faced the same issue twice on 1.1.3. Reverted back to 1.1.2 and I was able to proceed with the trade without any hassle

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
