### ISSUE TITLE
Fee reimbursement for trade anY1E34k

### ISSUE THREAD

**Issue by Thiagojm** [bisq-network/support#265]
![Negocio Bisq3](https://user-images.githubusercontent.com/30575561/62476349-2f11c700-b77d-11e9-83cc-a4594ae7c169.jpg)

Maker:  3eca853eb70a38cab6548ac8c43510c4f8b2a123396a223502e3a18ac203ae5d
Taker: e31d392d1ed6f4fe1b5ca239b6fd4ad440994a7afbba664e71bc756a99a7cbc1
Deposit: d384517ed6579824b5f3d378477a5c95af7ffd71c54a43cbd75fa954f1f83d9b

Bisq version: v1.1.4

"The deposit transaction has not been created because of a bug. No funds have left your wallet even if the UI shows that. After the dispute is closed you should have all your funds as expected. You can ask for reimbursement for the lost trade fee at: https://github.com/bisq-network/support/issues/"

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
