### ISSUE TITLE
Fee reimbursement for trade MgleVh1g and 575613

### ISSUE THREAD

**Issue by 333shine** [bisq-network/support#268]
**===MgleVh1g===**
![screenshot2019-08-19 9 38 46](https://user-images.githubusercontent.com/16625035/63233938-d870b680-c26d-11e9-893b-270f56600842.png)

Maker: a8fc637e9f9ad43c329c88d3310b3f97c2a63be3d3b9d2bcb81e9389a53386d4
Taker: 4699725a68fb3225837842180897257e2e6660f258a1202b5e668f04bedd5bfd

Bisq version: v1.1.4

An error occurred at task: BuyerAsTakerSignAndPublishDepositTx
Exception message: We got an onFailure from the peerGroup.broadcastTransaction callback.

**===575613===**
![screenshot2019-08-19 10 25 53](https://user-images.githubusercontent.com/16625035/63233965-fccc9300-c26d-11e9-9738-50cefbed1808.png)

Maker: 4cc28e8f95ff331aaa08cffc0ceb4d91372e8b23c7386a40a2eb968bf0c7e4eb
Taker: 8cb6e407cd7eda9afc95630a73de370835b59a12bf669d7be27986b070cd4b35

Bisq version: v1.1.4

There are no error messages in the details information but an error popup was appeared when I take this offer.
![screenshot2019-08-19 7 20 51](https://user-images.githubusercontent.com/16625035/63234364-ee7f7680-c26f-11e9-97d0-4136be63f7ec.png)

And there are no contents in the open trade page.
![screenshot2019-08-19 10 58 34](https://user-images.githubusercontent.com/16625035/63234530-8d0bd780-c270-11e9-8469-dc84605113ea.png)

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
