### ISSUE TITLE
Fee reimbursement for trade VHTecEd

### ISSUE THREAD

**Issue by xbyvee** [bisq-network/support#270]
![Screen_Shot_2019-08-25_at_7_33_13_pm](https://user-images.githubusercontent.com/22661489/63650845-329dda00-c78e-11e9-908c-015fef5337b0.jpg)

Maker: 837e20fda9e48b5f17ec5e7e5854e5ae07978ca668f90c11ff2cd6c4176f2571
Taker: N/A
Deposit: N/A

Bisq version: 1.1.4 / UBUNTU

Other notes: Bisq client froze when creating the offer, left it for 10mins and had to force quit. When I reopened Bisq the offer was not in "My Open Offers" but I noticed the maker deposit/fee transaction had been broadcast.

**Comment by KanoczTomas** [comment]
@xbyvee please upload a screenshot where the maker TX is visible. Thanks!

**Comment by xbyvee** [comment]
I can't screenshot the maker fee TXN for this because Bisq crashed during offer creation so it wasn't in "my offers" to be able to screenshot it but it definitely broadcast a maker fee TXN.

The maker fee TXN I have listed "837e20fda9e48b5f17ec5e7e5854e5ae07978ca668f90c11ff2cd6c4176f2571" I got from the transactions area of Bisq

**Comment by KanoczTomas** [comment]
@xbyvee ok thanks!

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
