### ISSUE TITLE
Fee reimbursement for trade 95264

### ISSUE THREAD

**Issue by brndnng** [bisq-network/support#271]
![95264](https://user-images.githubusercontent.com/21734054/63697555-bcfa4280-c84f-11e9-89fa-2d864be61dc7.jpg)

Maker:  29261dc95fd5c5608d095f675f4c47d7ebd318ec7d2503b2dd662ca3063d3c26
Taker: 8d62004f172e668d74442d518927ff3cd519ab41d2174631a93265a5cbdd33ee
Deposit: 55d7e2f4621cf56531c38f87d8a3b1da3a64857b692314fb3fa6495617345606

Bisq version:

1.1.5

Other notes:
Trade fees paid in BSQ (76 BSQ in total). Would like reimbursement of BSQ

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
