### ISSUE TITLE
Batch Fee reimbursement for 16 trades

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#275]
![ZyilENaJ](https://user-images.githubusercontent.com/45833017/64481987-a3aaac00-d1e8-11e9-9ccb-7c8e12796756.png)
Trade ID: ZyilENaJ-ecee52d7-78a1-4e1a-b5f6-7974d8b9de07-115
Trade date: 12 Aug 2019 17:30:57
Maker fee txid: ce4e2446adc121bb6653ad2316f897babb24b1b767beea0d39e3a75530ae9e9a
Taker fee txid: 194aa1efd2aa86df1de424b626308f2cdd8d68ccf5751a36ceddd0bfd22c25b4
Deposit txid: 5942b7c91de894c045061629490d7a765caf4812ca5ba8cb60a5583be8a77c14
Error message: -
Contract hash: d57644eae0bc2e509eaf13bb6280cd0f00399508acdd3026cdae239e4ea3435b
Trade State: Closed in dispute, deposit tx not published.

![8ddt5d](https://user-images.githubusercontent.com/45833017/64481981-8c6bbe80-d1e8-11e9-9a0e-cb918e1a1ed0.png)
Trade ID: 8ddt5d-eaeacd83-ffcc-4724-8e94-f40b77655a2d-115
Trade date: 12 Aug 2019 17:31:20
Maker fee txid: 3f91d5622f6e2fbe2435629d9d17dcfa621a2532a013f47507acb72703313e95
Taker fee txid: dc2b347f68fec086af662f5637839b7392cc46d0e75c8d05273b090140a4f582
Deposit txid: 67da5d3b4ea11ab794c85850f4acbbc6e6c9f1e6043dad1f3123c0cd0f640208
Error message: -
Contract hash: eea70fcdb4cad777fb310f1fab9c6f56d0312f1c3aeebcce9307fab95b6953df
Trade State: Closed in dispute, deposit tx not published.

![GJJVSXE](https://user-images.githubusercontent.com/45833017/64482090-0dc45080-d1eb-11e9-8ff1-4305b045ab18.png)
Trade ID: GJJVSXE-0d014222-fc45-4612-a26d-4abe7b856aa1-115
Trade date: 12 Aug 2019 17:32:26
Maker fee txid: 7a85bae2fae5ea9f933cf8d8d887cda7bd4a169678172306a927d29150dd17a4
Taker fee txid: fb0e6331d5bacf52591e6464c990b6302a17cf4e6c6f37e3655dd6faf2d57b71
Deposit txid: 6fec29823083cec5fc3e1876abfc410209dadddd389685a62eec7ed43de5fe61
Error message: -
Contract hash: 2709356059d13bbcdf4cfe6f99d783d938d93512ce76fd96f03a21301ad4764b
Trade State: Closed in dispute, deposit tx not published.

![77955363](https://user-images.githubusercontent.com/45833017/64482091-13ba3180-d1eb-11e9-91d3-31a6b7682a3f.png)
Trade ID: 77955363-0355986d-7aa9-4494-8b85-d1e318a0ad89-115
Trade date: 12 Aug 2019 17:32:42
Maker fee txid: a0b234476443e732c1bcaa37e10a3733db0e97379c463c217d287c576241e6db
Taker fee txid: 5a95502113eadd242001bdb8aad6b529ab9d4fb993d1ee710e88aa9352b2b374
Deposit txid: 37a1b1ab5e4c35b6dda8a0bc535c6c248cb5f7a94e85cf70ea9325fb224bc7a3
Error message: -
Contract hash: e900e773593904f339ad32d4863100005762bd43a5129146377fe0cdbdefd45e
Trade State: Closed in dispute, deposit tx not published.

![CADUMWWE](https://user-images.githubusercontent.com/45833017/64482092-19177c00-d1eb-11e9-8e68-4584fbd0845e.png)
Trade ID: CADUMWWE-519846b8-9a7e-404e-8332-b5cb21e92e5c-115
Trade date: 12 Aug 2019 17:34:15
Maker fee txid: b75a79d798a945d74d9c80d36da5cc3ea062c7c74c2ac1a638e382c50c5adee3
Taker fee txid: 1b126c8edac2b869a6e1f1037cde778ccdbfae8f6e1539fcae4484ee0ce56da6
Deposit txid: 1ce11b50218238e747f72be8a85810663c861459acfa7f677da0a4364515d30b
Error message: -
Contract hash: bd05240cd0d3042fe3c1f6553b1d5227af2dd45acb30b9b6ec01dc6b62029c25
Trade State: Closed in dispute, deposit tx not published.

![goloxks](https://user-images.githubusercontent.com/45833017/64482093-1ddc3000-d1eb-11e9-902d-60e753c00f05.png)
Trade ID: goloxks-ad895fa4-a740-486c-8844-f72cf795689a-115
Trade date: 12 Aug 2019 17:34:32
Maker fee txid: b6d5eafb3980ced80aa317a443ab740e787933f7b6a634ba932f1ad842b20a86
Taker fee txid: 88e1689cd36092201474fe654fc3e4494054b884d2b5267620e702a48ef6cdea
Deposit txid: 6b062b6f624db5f1c6542380f6ec8ab0312998bbf8af92a2661524921f7c9fb5
Error message: -
Contract hash: 41860403f2295c9a657c783411754693eb6842d8f3a961a81b2bf0f5bdbf02b9
Trade State: Closed in dispute, deposit tx not published.

![108210](https://user-images.githubusercontent.com/45833017/64482094-23397a80-d1eb-11e9-8257-f5f7c098b690.png)
Trade ID: 108210-1880961b-b260-4cfd-aed9-382e3f550475-115
Trade date: 12 Aug 2019 17:35:36
Maker fee txid: 817e0d31e2d3705d9b49033154377085d0e975d786ccf6df239bf1c577037876
Taker fee txid: 78d4f7be6aefe3d3b7199a25f41a632b3640255cf2de97927a4b9fe81696adfa
Deposit txid: 2e9de4ccc73d6d8e3abce1395710a9148f616982ab2a38f6b29633c443831a90
Error message: -
Contract hash: f3bbecaefde183c9f641e97172f86d09022ab928718d81fcfa6026b09f735244
Trade State: Closed in dispute, deposit tx not published.

![824549](https://user-images.githubusercontent.com/45833017/64482096-27fe2e80-d1eb-11e9-808b-5eca523d09e7.png)
Trade ID: 824549-15651cca-703b-422a-adec-51d30046c000-115
Trade date: 12 Aug 2019 17:36:50
Maker fee txid: 74818ebb61c797174f93827fbff1fdabbd7f1bc156382a8d94773c4141c8b155
Taker fee txid: bfb92315d442d85a586c3ad4e95e95c14c048633dc45c3ec24ada173f006c90c
Deposit txid: 83a3ea6fd508cdea7d5f95fca529939429617a56358a54d6114c2482fdcdcd1b
Error message: -
Contract hash: 23676607de437b75b0a2a34667dc733236b5bc75522b0ce8a551b395f99be261
Trade State: Closed in dispute, deposit tx not published.

![AVRELT3R](https://user-images.githubusercontent.com/45833017/64482099-2cc2e280-d1eb-11e9-99b3-b60e824116ef.png)
Trade ID: AVRELT3R-d53c9258-2e5a-41c2-9917-5b417d92c24d-115
Trade date: 12 Aug 2019 17:37:09
Maker fee txid: 72e96167084e301fe612a46b90e4de04ed38d93ec45c91ff5f5eb74f82e3a10b
Taker fee txid: 6cd8f1b47e272083a270262ea919bcb5790e16abead3f150dbf22f1ca584255e
Deposit txid: 9c24bdc914bdec081cc48b10bf83f688660c52c071565906781cf2c60733ced4
Error message: -
Contract hash: edb161e814a75af0cc8b0154d23f32c5cd401db07fa24a6c851c0e03dd4d394f
Trade State: Closed in dispute, deposit tx not published.

![pwm0mae](https://user-images.githubusercontent.com/45833017/64482101-32202d00-d1eb-11e9-9b9a-70935719008d.png)
Trade ID: pwm0mae-039cfb5d-675b-443c-bd49-b423897b6811-115
Trade date: 18 Aug 2019 22:34:46
Maker fee txid: 6e096276b274b3a4a81d247d934cfe411f016408b349f03d8cc52ae80c370402
Taker fee txid: 5b38b241e4c7e599b5845e5c60ae1ac698ca5e7ad8ac2747a3e50f9ba8f43c41
Deposit txid: 22168003a36bcf80f21cfbcffd39a033d50c1a6dc6a02e7e2581a69748efba08
Error message: -
Contract hash: 338458bd6b2d68cdf0dc5f5bf7499bd02e114755d79f49aea27e1c6f7ca002ea
Trade State: Closed in dispute, deposit tx not published.

![KFNVP](https://user-images.githubusercontent.com/45833017/64482103-377d7780-d1eb-11e9-82b6-7a3dcf0dea4a.png)
![KFNVP-2](https://user-images.githubusercontent.com/45833017/64482104-3b10fe80-d1eb-11e9-8163-a7cb912fa92a.png)
Trade ID: KFNVP-8525c52a-b320-421b-80d2-863fcd86ef24-115
Trade date: 19 Aug 2019 00:36:44
Maker fee txid: 888e1a190c04aed7b59c3417ae0741e147047a0ec1a0a5d9ae4ce54a47d9190b
Taker fee txid: c01b583ab5401ac0fcc7c007ab3a8d9eddcab41a717c2815475628549743849a
Deposit txid: 82786cf96c22b984c3680651128aeff6a1f90aae1414084796ebee8f3e3864a8
Error message: An error occurred at task: BuyerAsTakerSignAndPublishDepositTx
Exception message: We got an onFailure from the peerGroup.broadcastTransaction callback.
Contract hash: 0496674c7a10d671e954fee532c1cf5df59addd314424fab3fc5f0be458646b5
Trade State: Closed in dispute, deposit tx not published.

![MTYoEN](https://user-images.githubusercontent.com/45833017/64482105-4106df80-d1eb-11e9-8af3-f496e6fab2a7.png)
![MTYoEN-2](https://user-images.githubusercontent.com/45833017/64482108-449a6680-d1eb-11e9-8950-508db8f4c3ed.png)
Trade ID: MTYoEN-fb782738-9bbf-4264-9cf1-95ec0a3c242d-115
Trade date: 19 Aug 2019 00:38:58
Maker fee txid: b452e31a5afaa372621d08267619e858701b4fa6a22343dea35c8fc7461a2227
Taker fee txid: 9eeb7529602e424456a2b42c2976969e38b6b18c5b05998549e62a03b444bbfa
Deposit txid: 170d3ca1cf0d9573f48b24ba33ab12db4848644db871d874d3bf53abc426116b
Error message: An error occurred at task: BuyerAsTakerSignAndPublishDepositTx
Exception message: We got an onFailure from the peerGroup.broadcastTransaction callback.
Contract hash: 59acb79c3d8acd2ec8201d276a2a019ca3e97786c42b57b6ff58382a1e7c9133
Trade State: Closed in dispute, deposit tx not published.

![06116](https://user-images.githubusercontent.com/45833017/64482111-4bc17480-d1eb-11e9-9f29-ac817985f8a5.png)
Trade ID: 06116-bff617a6-36b5-4a04-a529-3f0b9bd3866d-114
Trade date: 26 Aug 2019 07:53:34
Maker fee txid: 4661de4a68d9254ffa9935dec1a5e95e43cc21e5c56533340937121e5e404c9c
Taker fee txid: e3c64000258e5e78300f27482d632461b9f86b06fa767a2b70f3e9a7d48b16c2
Deposit txid: 786b2aed2df1e592bf11bc9f81ec0ce2c826a69862e736882a1193f3c74c4327
Error message: -
Contract hash: -
Trade State: Closed in dispute, deposit tx not published.

![QCkgUE](https://user-images.githubusercontent.com/45833017/64482112-50862880-d1eb-11e9-950b-0998cf8ad447.png)
Trade ID: QCkgUE-5c1cb511-56fa-46a9-a148-06685a0f9fb3-115
Trade date: 5 Sep 2019 13:11:00
Maker fee txid: 70aa4804019154431f2f3d6f1d73c0eeabae1eb5a968d0c67b2c01598f8be343
Taker fee txid: 490d3b9e5f34cc83bac363a1d7169f6d902ed245f4b44a8e25df11361e729bfb
Deposit txid: 068e00724bc0d207ce51f82c5b4c07471aeb59ee55e056be7f6875215c038567
Error message: -
Contract hash: eb95fb055074c505983334ee45d948a8002170ccd7d759146439ef8db3caeccc
Trade State: Closed in dispute, deposit tx not published.

![910061](https://user-images.githubusercontent.com/45833017/64482113-5714a000-d1eb-11e9-9c9f-ec0ed1cc4d08.png)
Trade ID: 910061-0610b42d-7bce-4613-8d64-719997bd32fa-115
Trade date: 22 Aug 2019 22:47:49
Maker fee txid: d46a9f62b5f2279e7b7f9f5d2df0aa194903709e95df0894a14b0886448308b2
Taker fee txid: 1996f46f3c12540cdfe68926297a5073a8e3ae114de6749fc5f0d3a818067870
Deposit txid: 6e541204bc4c9c83cdbb89865dfe978e19549f1944f7040500e0a339586651ee
Error message: An error occurred at task: BuyerAsTakerSignAndPublishDepositTx
Exception message: We got an onFailure from the peerGroup.broadcastTransaction callback.
Contract hash: -
Trade State: TAKER_FEE_PUBLISHED

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by invertedbobb** [comment]
> 
> 
> Will be reimbursed with #300

Should i post an address somewhere?

**Comment by huey735** [comment]
@invertedbobb There's no need for an address.

**Comment by KanoczTomas** [comment]
@invertedbobb by default it goes to the input of the failed trade (to an address you control). Of course you can send an address if you want to be reimbursed to it (you can send it to my email, or on keybase, or on slack) You can find my email based on pgp (check out my sig, all commits are signed by it).

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116

**Comment by invertedbobb** [comment]
66 Confirmations on that transaction now. I haven't received anything...?

**Comment by KanoczTomas** [comment]
@invertedbobb
