### ISSUE TITLE
Fee reimbursement for trade 50215814

### ISSUE THREAD

**Issue by Ponchito2** [bisq-network/support#276]
![bisq](https://user-images.githubusercontent.com/55201010/64711903-5c424b00-d488-11e9-9b54-9d7275ba4680.jpg)

Maker:  4b10ed247610291473327c153a6c246acc91f4f16ade86897d843f357a32c56c
Taker: c41f7c558d4d1822c6fe3706ca3b61f59932c3cfafb24b236d1ff9c9fe01928f
Deposit: .0010

Bisq version: v1.1.5

Other notes:

Trade has been stuck on step 1 - wait for blockchain confirmation status since inception.

**Comment by Ponchito2** [comment]
Hello, any updates?  Not familiar with how this works.  Thanks!

**Comment by KanoczTomas** [comment]
@Ponchito2 I am working on it now, you will be added to a csv file in this repo and later will receive a payout. Should take a few days max from now.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by Ponchito2** [comment]
Perfect, thank you!

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
