### ISSUE TITLE
Fee reimbursement for trade vnqw78lz

### ISSUE THREAD

**Issue by cryptopayserver** [bisq-network/support#279]
![imagen](https://user-images.githubusercontent.com/55004944/64819317-3a42e880-d5ae-11e9-8114-d20850cb62ac.png)

Maker:  7934360e93d1e90df89c22e70a83ab719cf61394de2a54b67b5b2dbda6e6dd5d
Taker: 4604f83e0606caba1e560e2232e26e00f9f4eb2219e73c198cc38afdf0aa9a70
Deposit: 7be27cb563f477c48cd693ceed3d1db12278a0d58f4f8f639536fb7b04737206

Bisq version: 1.1.5

Other notes:
tx bugged

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116

**Comment by cryptopayserver** [comment]
Sorry in which address will receive reimbursement ??
I don't know how to view reimbursement.
thanks.

**Comment by cryptopayserver** [comment]
> Closing as reimbursed via the batch transaction documented at [#300 (comment)](https://github.com/bisq-network/support/issues/300#issuecomment-544468116)

Sorry in which address will receive reimbursement ??
I don't know how to view reimbursement.
thanks.

**Comment by KanoczTomas** [comment]
@cryptopayserver look in the wallet you used to fund the bisq trade. If you used Bisq go to the transactions tab and look for an incoming payment on the date of reimbursement.
