### ISSUE TITLE
Fee reimbursement for trade vqssi

### ISSUE THREAD

**Issue by xandermccormick** [bisq-network/support#280]
<img width="500" alt="vqssi" src="https://user-images.githubusercontent.com/52983020/64922896-e694f280-d799-11e9-994a-f31978c7a91c.png">

Maker:  06073d1259a1897b1bb95736d51350ba7257b586821c99296fad1c011f76764b
Taker: c65276d6334c42ed86a3a832afd3d9683ce642c75a367846bc350843185ad0b9
Deposit: Believed bugged

Bisq version: 1.1.5

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
