### ISSUE TITLE
Fee reimbursement for trade NSITB

### ISSUE THREAD

**Issue by delmonte91** [bisq-network/support#281]
![image](https://user-images.githubusercontent.com/55715475/65456883-9b8a7780-de4a-11e9-9918-7b08a061da91.png)

Maker:  8e93a2227dc4abcee181cc716cee3108a802826100d10fc79bc11d31865e5d60
Taker: 8e31212dcd91e2e5aa2ffd9adb41e0a69be46c78353b4cd25ff770729a63f130
Deposit: 1466d9862f5f69b49341204cc2d78b6ef8c5f85ac53cabe1b90b088d2c67499e

Bisq version: 0.9.8

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
