### ISSUE TITLE
Fee reimbursement for trade avqya

### ISSUE THREAD

**Issue by delmonte91** [bisq-network/support#282]
![image](https://user-images.githubusercontent.com/55715475/65457142-2ff4da00-de4b-11e9-8ccd-74641956a468.png)

Maker: 0de0eead5fd2aaa0c083c63ad6470084d4dda4105f7cf330cbf7b7650cbcf47b
Taker: 6f5e23bae9c660a635589339841e91b6ef6d38787013834afa6727017e64bb50
Deposit: 0addf82106b3136817976c60558dc3f2dce09b93d5464b312afbce3005654f11

Bisq version: 0.9.8

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
