### ISSUE TITLE
Fee reimbursement for trade HQDBFOBD

### ISSUE THREAD

**Issue by xbyvee** [bisq-network/support#285]
![HQDBFOBD](https://user-images.githubusercontent.com/22661489/65575674-8aa74680-dfaf-11e9-9ccb-e5fa24fc45bb.jpg)

Maker: c87aeba489167a83c0495b260e1f8fa8a92627a05be67cb925e5fb7cbaeb0112
Taker: e7065d8ac906a71067f93bff2e6f24d05e27849036c84a338fcd86fc2e1fd4e0
Deposit: 5cc706ec5a6c4290f53dda218f6cdf9f8c4a290e0f7c8f5449121e7630b77438

Bisq version: 1.1.6
Other notes: No deposit TXN broadcast

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
