### ISSUE TITLE
Fee reimbursement for trade OEDBDUN

### ISSUE THREAD

**Issue by xbyvee** [bisq-network/support#287]
![OEDBDUN](https://user-images.githubusercontent.com/22661489/65575816-d528c300-dfaf-11e9-8bd0-bead208eca36.jpg)

Maker: fe64f53f9949105a8faa724b407c06414abe4bef125fd8993efb78a2d352cd77
Taker: 70d9bf1f178de87970f678df20b77c40737177ef4b865908d9b8bcfac9713b26
Deposit: 5cc706ec5a6c4290f53dda218f6cdf9f8c4a290e0f7c8f5449121e7630b77438

Bisq version: 1.1.6
Other notes: No deposit TXN broadcast

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
