### ISSUE TITLE
Fee reimbursement for trade erVZayET

### ISSUE THREAD

**Issue by 333shine** [bisq-network/support#290]
![screenshot2019-09-26 05 31 05](https://user-images.githubusercontent.com/16625035/65637909-fde8a100-e01f-11e9-9eec-6b2103f09e08.png)

Maker: 20fbcc1e03b4b6d101e683c64b6c7d1734b272aa68435799bc2ca8c20f96038b
Taker: df91acccbae96c826f0db25f2e1990d9010eab19c9125f90584d64ce963e3daf

Bisq version: v1.1.6

Maker fee transaction and deposit transaction did not been published.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
