### ISSUE TITLE
Fee reimbursement for trade KZGCG

### ISSUE THREAD

**Issue by danielv1234** [bisq-network/support#294]
![Screenshot 2019-09-28 at 20 27 32](https://user-images.githubusercontent.com/26386779/65820183-b5eb9900-e22e-11e9-87f3-24793ce47bf7.png)

Maker:  979dac96d2c2819083b300aaac156b7b6aff55b9528c4540fd6cdcd9dd64fdb9
Taker: dbe39d47f5657a2a73289c9b6bb59225b174426e5647bf742da846000e46ba98
Deposit: 3da3e6c36648f5d998e50ec0e93f825a37d4891c5b859512c9361b224341bc08

Bisq version:1.1.7

not published tx.

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
