### ISSUE TITLE
Fee reimbursement for trade CEKMQ

### ISSUE THREAD

**Issue by danielv1234** [bisq-network/support#297]
![Screenshot 2019-09-28 at 20 36 41](https://user-images.githubusercontent.com/26386779/65820297-b7699100-e22f-11e9-8d45-18909b2c019c.png)

Maker:  d362f128042df239070fde5f1b973b769f219546e7ba1360da830d1cc2826cd4
Taker: 3d24771c9feaee7889561af80cc06eb4210f6a6c5741c06ce58deb1f8b88b275
Deposit: d71c417d3c609cb36fef17a13747089df6b486ffadbe8461ee66afbd3691bf69

Bisq version:1.1.7

not published tx

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
