### ISSUE TITLE
Fee reimbursement for trade 162734

### ISSUE THREAD

**Issue by abjea** [bisq-network/support#298]
![image](https://user-images.githubusercontent.com/56129598/66148069-1d626980-e5de-11e9-9da9-75e8ea9c8c20.png)

Maker:  848df2f166e16b8dfeaa9511980f5b40d9287bec7582679e9bfe48af9733b774
Taker: 27b0777ab08cf8d2686a305b48e931b38e174f4ea31c2ca9664a2c31f3296a43
Deposit: a20134762fd9af7bf94b2fecd197cf2567454cf3ac16dcdb7796eb470029bda7

Bisq version: 1.1.6

Other notes:

![image](https://user-images.githubusercontent.com/56129598/66148226-6d413080-e5de-11e9-9ca9-fff20252f28e.png)

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
