### ISSUE TITLE
Fee reimbursement for trade 5398758

### ISSUE THREAD

**Issue by Olugbo** [bisq-network/support#299]
>_The XXXXX part in the issue title are the first 5 characters of the Trade ID._

SCREENSHOT HERE
![Screenshot from 2019-10-08 18-53-53](https://user-images.githubusercontent.com/34590148/66446024-a3771980-e9fd-11e9-86ba-39b059701b5a.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 8141c942a25834285f054c089370c47f5ec30ef184cbf9aac9b0122193461b36
Taker: a4af5c9f7c89f2a031ee571f41c4fa8061c6afc55274bc3372f89fde4caa6bcc
Deposit: ..........Buyer [0.001BTC] Seller [0.005BTC]

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form!**_

Bisq version: 1.1.7

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
Will be reimbursed with #300

**Comment by huey735** [comment]
@Olugbo why was this reimbursement requested?

**Comment by Olugbo** [comment]
...because my transaction was sitting in limbo. See screenshot.

**Comment by KanoczTomas** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/300#issuecomment-544468116
