### ISSUE TITLE
Deanonyzing transactions

### ISSUE THREAD

**Issue by sneurlax** [bisq-network/support#30]
There seems like a lot of info here for tagging transactions as Bisq Network transactions.

**Comment by sneurlax** [comment]
"""
How Bisq keeps data private

...

    **Bisq has no central servers or databases to record data**

    **Data is encrypted such that trade details are readable only by counterparties**

"""
(emphasis added)

That's all

**Comment by cbeams** [comment]
I didn't get your point above, @sneurlax. What do you mean by "here" when you say "a lot of info here?"
