### ISSUE TITLE
Fee reimbursement for trade AiDVT

### ISSUE THREAD

**Issue by jhdfvcbiw** [bisq-network/support#303]
![bisq1](https://user-images.githubusercontent.com/56731121/67118731-6a992a80-f1dd-11e9-8a32-c4f3362fbf02.png)

Maker: b05ff2dd027e40260dd2e40dad729fcec7ec0437740cec18f92248049c985aa8
Taker: 334e2658236426537c8bd58c8bbc53821003f9da29aec11d9cc3722ac3292a22
Deposit: 908218203f28c743dd04628b3903d7b4e899142076d359a9d1eaf9d00c136513

Bisq version: 1.1.7
Other notes: No deposit TXN broadcast

**Comment by huey735** [comment]
@jhdfvcbiw please remove the personal payment info

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
