### ISSUE TITLE
Fee reimbursement for trade VftyDShZ

### ISSUE THREAD

**Issue by jhdfvcbiw** [bisq-network/support#304]
![bisq2](https://user-images.githubusercontent.com/56731121/67118771-83a1db80-f1dd-11e9-987d-eb27ba059deb.png)

Maker: 89ec5e6d0d17ef9f7e6293663caa265ed22fd156f9bb5ce10d6438a4295e9ab4
Taker: 323d65ba1c7fe463ed415f2ae3a5d46f83ed0b81037a28fac76bedc58a206ccc
Deposit: ba2e2a262679a2add8f59aac4518ac7b0f9d27b0cce74a9c00f4190b802150ac

Bisq version: 1.1.7
Other notes: No deposit TXN broadcast

**Comment by huey735** [comment]
@jhdfvcbiw please remove the personal payment info

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968

**Comment by jhdfvcbiw** [comment]
Bisq says my deposit transaction funds are still locked. How do I get this returned?

**Comment by jhdfvcbiw** [comment]
![screen](https://user-images.githubusercontent.com/56731121/101286217-27cf5300-37e1-11eb-8c5b-d1427ffa814e.png)
