### ISSUE TITLE
Fee reimbursement for trade YECMGAG

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/support#306]
![YECMGAG](https://user-images.githubusercontent.com/36059034/67161075-5d8b5100-f32d-11e9-9f07-7f245c271f2b.PNG)

Maker: cbe5e46b07550570388c4052e5c3ca9d9ae4722225f9cd5ec48822e2a8fb48c9
Taker: 3140a8195187304c1652c9f155c3c868640a3da578fa179900b5f7cc50c0b916
Deposit: 6da22a62111ef472c74d6e285bc39ec0ab8e47a98694b9b5adea151d5b4c3372

Bisq version: v1.1.7

Not published tx

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
