### ISSUE TITLE
Fee reimbursement for trade xq5vn7n

### ISSUE THREAD

**Issue by zanetti74** [bisq-network/support#308]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
@zanetti74 see comments in issue #309

**Comment by zanetti74** [comment]
Maker: ..........026800597c06e54027c92700d03d03d7236f0b29c73c8f2883eb5454b4d19c5e
Taker: ...........fad80bcca75e62e25a59676f5f20d941d30f41a7312b0b99f7865aba4a6edca6
Deposit: ..........f5e7c49c84966444fc9e72a89a7565bf2bc2307f710053af92f7ec7d465eb1ae

**Comment by KanoczTomas** [comment]
@zanetti74 if you click on your first comment you (on the 3 dots) you can edit it. Please move the maker/taker/deposit part there and remove the dots, those are meant as a place holder.

Once editing remove the last line with `![reinbursement](https://user-images.githubusercontent.com/35078118/67162834-76503280-f33e-11e9-9ff2-fdd4e3466275.JPG)` to remove the screenshot.

**Comment by zanetti74** [comment]
Ok, now what should I do? I´ve seen reimbursements that are more than 21 days open, why so long to do that? How can I have my BTC that are stucked on these 4 trades back to my account? It´s been a nightmare to fix this issue on these 4 trades, there is nobody responsible for nothing on Bisq, if there is no payment for any service on this platfoorm I see no future on it.

**Comment by zanetti74** [comment]
Hi, how do I move forward? What I am supposed to do?

**Comment by zanetti74** [comment]
Hi, I am trying to work with the arbitrator, so far no news. Only that there are now 2 locked trades and the coins from the other 2 trades are not more on my panel. What should I do?

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
