### ISSUE TITLE
Fee reimbursement for trade njfpkyk

### ISSUE THREAD

**Issue by zanetti74** [bisq-network/support#309]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

njfpkyk
Maker: 8df5c9f43becc352573adbb6a5085c799bc6987828105f54e0d1116ac50246d8
Taker: 80073cb919993d599938de1232cb014e00f0c2223309ba0c5b0a667da61ae199

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
@zanetti74 please follow the format of the support ticket, it will not be processed like this.
Mistakes:
The issue topic is not correct: should be njfpkyk
Maker/Taker is not copied as requested

YOU HAVE PERSONAL INFORMATION VISIBLE ON THE SCREENSHOT, please do not do that!

**Comment by zanetti74** [comment]
How do I delete the screenshot?

**Comment by KanoczTomas** [comment]
@zanetti74 see #308 for how to remove screenshot. The deposit field is not always there, so it you do not have it just leave it blank.

**Comment by zanetti74** [comment]
Hi, how do I move forward? What I am supposed to do?

**Comment by zanetti74** [comment]
Hi, I am trying to work with the arbitrator, so far no news. Only that there are now 2 locked trades and the coins from the other 2 trades are not more on my panel. What should I do?

**Comment by leo816** [comment]
deposit tx id information is still missing from this trade

**Comment by zanetti74** [comment]
It was not confirmed

Em sáb, 28 de mar de 2020 15:51, leo816 <notifications@github.com> escreveu:

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
