### ISSUE TITLE
Resend Transaction?

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#31]
@doffing81 commented on [Mon Jan 15 2018](https://github.com/bisq-network/exchange/issues/1194)

I believe my unconfirmed transaction has disappeared from the mempool as later transactions with smaller sat/byte fees are now being confirmed. My transaction is from Bisq to an exchange. What are my options here? Am I able to get the private key? I know Bisq uses HD wallets, but not exactly sure what standard, for which I could probably extract them and create a new transaction. Bisq says I have 0 funds, so I can't even fill in the "Withdraw from address" field. I'm coming up on two weeks waiting for this transaction, so I'd like to figure out a way to get it confirmed. Suggestions?

**Comment by cbeams** [comment]
Have you checked your transaction in a block explorer like https://bitaps.com? If it's there, it's still in the mempool.

Does the wallet you transferred the funds into show the transfer? i.e. do you have an unconfirmed balance showing up on that address in that wallet?

If you do, and your wallet allows spending unconfirmed utxos, then you can get the original transaction confirmed using the "child pays for parent" (CPFP) technique. Send a transaction from the address in question with a fee high enough to cover both child and parent transactions at the current market rate. This will cause miners to include both transactions in an upcoming block.

**Comment by doffing81** [comment]
Some block explorers still show it, others not apparently. The exchange that I sent it to does not show unconfirmed amounts.

Looks like I have found that Bisq uses the BIP 44 standard, and am able to extract the private key this way. May just have to look into trying my first double spend if nothing else.

**Comment by cbeams** [comment]
See also the wallet tool with CMD-J, which will show you your keys (and private keys if you check the box). Note that to see privkeys unencrypted, you'll need to remove the password from your wallet in `Account->Wallet password` (assuming you have one in place already).

**Comment by doffing81** [comment]
Ha, Nice! Found the key myself, but good to know!

**Comment by cbeams** [comment]
Closing as complete.
