### ISSUE TITLE
Fee reimbursement for trade QZIOEAFM

### ISSUE THREAD

**Issue by zanetti74** [bisq-network/support#310]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
@zanetti74 see comments in issue #309

**Comment by zanetti74** [comment]
Maker: ..........084528d1487a4e3744b5ce74f3e5aafc7e3d56ab9c4c53141072addbfae16c23
Taker: ...........53c5b8e6475e2536462a94e03ab15aeefbd1f3defc7d5ecdc1a431bbd156c0ab
Deposit: ..........084528d1487a4e3744b5ce74f3e5aafc7e3d56ab9c4c53141072addbfae16c23

**Comment by m52go** [comment]
Who has admin rights on this repository? That screenshot should be edited immediately. 

Or @zanetti74 can you do it?

**Comment by zanetti74** [comment]
Hi, how do I delete the screenshot?

**Comment by zanetti74** [comment]
I think I got it! What´s next?

**Comment by zanetti74** [comment]
Hi, what is the next step? Quick question, do you do this service as a “pro bono” or you are paid by the trades we do?

**Comment by zanetti74** [comment]
Hi, how do I move forward? What I am supposed to do?

**Comment by zanetti74** [comment]
Hi, I am trying to work with the arbitrator, so far no news. Only that there are now 2 locked trades and the coins from the other 2 trades are not more on my panel. What should I do?

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
