### ISSUE TITLE
Fee reimbursement for trade EVOHESYS

### ISSUE THREAD

**Issue by zanetti74** [bisq-network/support#311]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by KanoczTomas** [comment]
@zanetti74 see comments in issue #309

**Comment by zanetti74** [comment]
EVOHESYS
Maker: ..........df44a5910f9253c41a474c3418c3648585ff65a274e2c393fd7ac07c1980bf42
Taker: ...........b46f3a5d2739a2511e93a025de2a4f0c1177babbe257203c4b2e4ca79c755fc3
Deposit: ..........f5e7c49c84966444fc9e72a89a7565bf2bc2307f710053af92f7ec7d465eb1ae

**Comment by zanetti74** [comment]
Is that ok now on my 4 reimbursements? I got all the value of the trade stuck for more than 20 days and the arbitrator did nothing so far. He got in contact but did not move forward. I am with my 4 trades value stucked. How do I revert these 4?

**Comment by zanetti74** [comment]
Hi, how do I move forward? What I am supposed to do?

**Comment by zanetti74** [comment]
Hi, I am trying to work with the arbitrator, so far no news. Only that there are now 2 locked trades and the coins from the other 2 trades are not more on my panel. What should I do?

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by zanetti74** [comment]
Sorry
I am not understanding
Please update me
Rafael

Em qui, 2 de abr de 2020 12:44, leo816 <notifications@github.com> escreveu:

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
