### ISSUE TITLE
Wallet withdrawal - Not published

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/support#312]
I have withdrawn my bisq wallet to another wallet of mine and still have no confirmation.
![levantamento](https://user-images.githubusercontent.com/36059034/67238811-26e43200-f424-11e9-98a2-f372ee614a94.PNG)
https://blockstream.info/tx/08dfd40a2b21bab410ccbacaf58bfef9fe716bc352ce9e0a3296b6112550b846

**Comment by onlymarcus** [comment]
I transferred to this wallet: 32emT3d31NWQwKkNHFqXKeA4QrrPQRyjfZ

, nothing has arrived yet, and the bitcoins don't appear in my bisq. Do I need to provide any additional information?

**Comment by pazza83** [comment]
Closing as stale
