### ISSUE TITLE
For Cycle 7 BSQ Trade Fee Reimbursement Request (Failed Trades)

### ISSUE THREAD

**Issue by xbyvee** [bisq-network/support#313]
I am requesting 434.6 BSQ reimbursement due to failed trades. All of the trades below either failed due to no deposit TXN or no deposit TXN broadcast. I have included a link to the BSQ explorer for each trade, a link to the original reimbursement request for each trade, the amount of BSQ that was paid/burnt and a screenshot of my transaction history in Bisq DAO showing the particular BSQ transaction and the fact it was confirmed.

**FAILED MAKER TRADES**

Maker 080879
[Original Issue](https://github.com/bisq-network/support/issues/272)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=a5928d92aa0a2faa550d768e2b1072b0596898bef4074046c50ce520d13c8b23)
Maker TXN: a5928d92aa0a2faa550d768e2b1072b0596898bef4074046c50ce520d13c8b23
BSQ Burnt: 2.6

![WALLET-080879](https://user-images.githubusercontent.com/22661489/67342706-789ed080-f57a-11e9-8e3e-9be11055df5e.jpg)

Maker xsBPY3
[Original Issue](https://github.com/bisq-network/support/issues/273)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=57f1bee9a47a5e4a4ed766db8d34bb6f4f250ca49e0bc29d2e3cef3816983728)
Maker TXN: 57f1bee9a47a5e4a4ed766db8d34bb6f4f250ca49e0bc29d2e3cef3816983728
BSQ Burnt: 26.0

![WALLET-xsBPY3](https://user-images.githubusercontent.com/22661489/67342726-87858300-f57a-11e9-91f2-4eac7ddb09ee.jpg)

Maker 41777
[Original Issue](https://github.com/bisq-network/support/issues/274)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=6513b40b2185c6b8f4ae6de5285b8441616a06e5d92cd6337321edd234df9d29)
Maker TXN: 6513b40b2185c6b8f4ae6de5285b8441616a06e5d92cd6337321edd234df9d29
BSQ Burnt: 26.0

![WALLET-41777](https://user-images.githubusercontent.com/22661489/67342743-98ce8f80-f57a-11e9-8d59-fa175e257570.jpg)

**FAILED TAKER TRADES**

Taker HQDBFOBD
[Original Issue](https://github.com/bisq-network/support/issues/285)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=e7065d8ac906a71067f93bff2e6f24d05e27849036c84a338fcd86fc2e1fd4e0)
Taker TXN: e7065d8ac906a71067f93bff2e6f24d05e27849036c84a338fcd86fc2e1fd4e0
BSQ Burnt: 76.0

![WALLET-HQDBFOBD](https://user-images.githubusercontent.com/22661489/67342766-a84dd880-f57a-11e9-96ff-9516727b60b4.jpg)

Taker 1809978
[Original Issue](https://github.com/bisq-network/support/issues/283)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=c96953d11679267addd02710317e5a177415a0ed9cb761074908dcd656edd9e2)
Taker TXN: c96953d11679267addd02710317e5a177415a0ed9cb761074908dcd656edd9e2
BSQ Burnt: 76.0

![WALLET-1809978](https://user-images.githubusercontent.com/22661489/67342774-ae43b980-f57a-11e9-9d90-b9462638ce55.jpg)

Taker 862992
[Original Issue](https://github.com/bisq-network/support/issues/284)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=112bba751cf484b87d924a02f0aa2ab0654818b029d5915d03747b46f9af9d7c)
Taker TXN: 112bba751cf484b87d924a02f0aa2ab0654818b029d5915d03747b46f9af9d7c
BSQ Burnt: 76.0

![WALLET-862992](https://user-images.githubusercontent.com/22661489/67342779-b3a10400-f57a-11e9-9505-d09595fa65c7.jpg)

Taker 92196912
[Original Issue](https://github.com/bisq-network/support/issues/289)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=15124d4449084686a458d156ef1c7aac2ea86eba68f15ace4656ca137a71a314)
Taker TXN: 15124d4449084686a458d156ef1c7aac2ea86eba68f15ace4656ca137a71a314
BSQ Burnt: 76.0

![WALLET-92196912](https://user-images.githubusercontent.com/22661489/67342788-bac81200-f57a-11e9-91a0-6d060cd3e285.jpg)

Taker 408634
[Original Issue](https://github.com/bisq-network/support/issues/291)
[BSQ Explorer](https://explorer.bisq.network/tx.html?tx=d22aa9c1acd721c2c0268a913c44b41bf9144adbe7a09d3b0465c0cd7f5a6ad3)
Taker TXN: d22aa9c1acd721c2c0268a913c44b41bf9144adbe7a09d3b0465c0cd7f5a6ad3
BSQ Burnt: 76.0

![WALLET-408634](https://user-images.githubusercontent.com/22661489/67342794-c0bdf300-f57a-11e9-9c0b-7ee724f80305.jpg)

**Comment by chimp1984** [comment]
Seems you got reimbursed (or scheduled for) by @KanoczTomas 
https://github.com/bisq-network/support/issues/291

**Comment by xbyvee** [comment]
Reimbursements only return BTC, not BSQ trading fees. This github issue I have created to link to my DAO reimbursement request so I can have my BSQ returned.

**Comment by danielv1234** [comment]
I have same issue, i have been Reimbursed with N/A amount of BSQ.
