### ISSUE TITLE
Arbitrator unable to see dispute OGWQAOV

### ISSUE THREAD

**Issue by gofastandpray** [bisq-network/support#314]
I contacted arbitrator regarding this trade and they told me they are unable to see the dispute I opened. I have re-opened it twice (ctrl+o) but arbitrator was still not able to see.

For this trade I was maker/BTC buyer. I sent funds within a few hours of trade execution. Taker/BTC seller never confirmed receipt and has not been back on to read chat messages since receiving money. Messages to arbitrator are a mix of "message arrived at receiver" and "message saved in receivers mailbox" 

BISQ 1.1.17

TRADE ID: OGWQAOVL-e7865822-1280-4231-ac36-41e0bbb83069-117
mediator: exihmfza5343eh7q.onion:9999
Trade date Oct 14, 2019

please let me know if other info is needed to help resolve this. Trade is still unresolved.

**Comment by gofastandpray** [comment]
[bisq.log](https://github.com/bisq-network/support/files/3769245/bisq.log)
Thanks @ripcurlx log attached

**Comment by gofastandpray** [comment]
FYI, earlier messages in the support chat still say "arrived at receiver" but later messages (repeated messages sent again) now say "message arrival confirmed by receiver"
It has been 24 hrs since latest batch of messages (5 days since opening support request). No response received from the mediator/arbitrator. 

Yesterday after a reboot, Bisq said "connecting to Bisq network failed" java.io.FileNotFoundException ...tor\.tor\control_auth_cookie but then that message went away after restarting Bisq.

OS: Windows 10

**Comment by pazza83** [comment]
Closing as stale
