### ISSUE TITLE
Withdrawn from wallet, trade does not appear, BTC locked

### ISSUE THREAD

**Issue by danielsantos86** [bisq-network/support#315]
I made 2 transactions to sell BTC, but instead of Multisig details, I received “Withdrawn from wallet” messages as you see at the figure, My BTC are locked and no sign of the traders at the Portfolio Tab.

Please help me!!

![bisq](https://user-images.githubusercontent.com/15613361/67412511-cecd3d00-f595-11e9-92f1-fb93adf7a957.png)

**Comment by wiz** [comment]
@danielsantos86 sorry this issue is affecting you - a "delete SPV and re-sync" may help you and please join #support channel on Keybase team Bisq to discuss further

**Comment by pazza83** [comment]
Closing as stale
