### ISSUE TITLE
Timeout error when confirming as taker

### ISSUE THREAD

**Issue by moogdummy** [bisq-network/support#317]
After accepting a trade as taker, and paying security deposit, the loading icon appeared for a couple minutes until I got an timeout error that said

"Funds never left your wallet"

My security deposit was refunded into my bisq wallet so all I paid was the tx fee for the multisig.

I got this error when trying to accept 2 different trades. I cannot find my screenshot of the error so please forgive me.

Here is the log: 
[bisq error timeout.txt](https://github.com/bisq-network/support/files/3775302/bisq.error.timeout.txt)

**Comment by pazza83** [comment]
Closing as stale
