### ISSUE TITLE
Locked funds disappeared after arbitration 90546

### ISSUE THREAD

**Issue by gussulliman** [bisq-network/support#319]
I took a trade, the deposit transaction never went through, so went to moderation, then arbitration. 

The trade amount was locked when in arbitration. The trade amount left 'locked' but is not in 'Available balance' or elsewhere. 

![image](https://user-images.githubusercontent.com/32939482/67683784-e3d91000-f989-11e9-9bac-11d59f551dde.png)

Maker:  77914d03bef85fa895e4cacd95b53a366941ef122c81a34d427a24aa1c6dcb93
Taker: 33bce884a77939cf807fbf6d04fa26b869cf8cfad07e2dd7b4397cfa61364b2d
Deposit: 0f731845b75db44a6f3e3401993871bf9253f45cab913d03186d06ded5c03a3b

Bisq version: v1.1.7

Other notes:

**Comment by gussulliman** [comment]
![image](https://user-images.githubusercontent.com/32939482/68117062-471bf280-fef4-11e9-8bfc-912e02eccaae.png)

The ticket was closed, and was told that the 0.0299 should be returned to seller (me), but this has yet to happen.

**Comment by pazza83** [comment]
Closing as stale
