### ISSUE TITLE
Fee reimbursement for fee paid with BSQ

### ISSUE THREAD

**Issue by danielv1234** [bisq-network/support#320]
What can i do to receive BSQ paid as fee, for failed transaction?
Thanks.

https://github.com/bisq-network/support/issues/267 can be used as a good example of a correct reimbursement request._

**Comment by xbyvee** [comment]
You need to read the instructions in #267 essentially you need to:
-Create a reimbursement request issue with evidence of BSQ spent like #313 
-Open a "reimbursement request" proposal on the Bisq DAO and link to your issue
-Wait for the proposal to be voted on and if it succeeds you'll get your BSQ back.

**Comment by danielv1234** [comment]
Thanks @xbyvee !

**Comment by xbyvee** [comment]
In case you've missed it the best instructions are this comment: https://github.com/bisq-network/support/issues/267#issuecomment-544945554
