### ISSUE TITLE
Fee reimbursement for trade paid with BSQ

### ISSUE THREAD

**Issue by danielv1234** [bisq-network/support#321]
I have made fee reimbursement request for trades below , was approved, but i have receive nothing.
Fees were paid with BSQ, not BTC. 
Please approve BSQ reimbursement, or BTC value for buying tokens.
Total paid 143 BSQ.

>_Issue [#269 ](https://github.com/bisq-network/support/issues/269) 
>_Issue [#293 ](https://github.com/bisq-network/support/issues/293) 
>_Issue [#294 ](https://github.com/bisq-network/support/issues/294) 
>_Issue [#295 ](https://github.com/bisq-network/support/issues/295) 
>_Issue [#296 ](https://github.com/bisq-network/support/issues/296) 
>_Issue [#297 ](https://github.com/bisq-network/support/issues/297)

**Comment by leo816** [comment]
these reimbursement requests were made with Tomas as Fee reimbursement agent and they seem to have been closed. You should have received the funds through btc. If not please contact us through Keybase on the support channel. (my handle is @leo816 )
