### ISSUE TITLE
Fee reimbursement for trade aOoHOuC

### ISSUE THREAD

**Issue by nicebug5** [bisq-network/support#323]
![reimbursement](https://user-images.githubusercontent.com/57108783/68018600-6bc46000-fc91-11e9-97fd-c39e909f7578.png)

Maker: 9eb76927e4329d5f6d9623c685667abde1812528759214e256bb54c2f1127591
Taker: dcea137879069dcf709cfb19f854c96e2aa120c119a1c3ff8058c6f039e20dc9
Deposit: null

Bisq version: v.1.1.7

Other notes:
Trade was never conducted cause transaction failed to be broadcasted.

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
