### ISSUE TITLE
Fee reimbursement for trade 581049

### ISSUE THREAD

**Issue by naternater** [bisq-network/support#324]
![bisq_dispute2](https://user-images.githubusercontent.com/16222875/68092249-2a92a280-fe81-11e9-9a61-acd1879151ac.jpg)

Offer ID: 581049
Maker: a34467193dbd1c6332486248d1a228a209a6cbf152e21de906ca1e471fff3c69
Taker: edc02e93e18533ba23872ed99993d133901db3242c71f9cf0aa3a0a0d489b90c
Deposit: e7e598e7fc6349cbb3cd3839323eab31c0291fcc29a218e38421aee7acced46b

Summary notes: Bug caused the deposit TX to not confirm. Please reimburse fees. Thanks.

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
