### ISSUE TITLE
Reimbursement from batch #300 not received

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#325]
I've commented in the batch reimbursement ticket and in the original reimbursement claim, but no reply yet.
I have not received any funds related to this reimbursement to any of my addresses.
Any assistance would be highly appreciated.

@KanoczTomas

**Comment by KanoczTomas** [comment]
@invertedbobb reopened your issue, please lets keep it there.
https://github.com/bisq-network/support/issues/275

Thanks for opening the issue though, it got on top of my huge inbox this way.
Closing this one, please comment on the reopened one, so we keep organized. Thanks!
