### ISSUE TITLE
For Cycle 7 BSQ Trade Fee Reimbursement Request (More Failed Trades)

### ISSUE THREAD

**Issue by xbyvee** [bisq-network/support#326]
Further to #313 I have two more failed trades I'm claiming BSQ reimbursement for via the DAO. I am claiming 30BSQ reimbursement in this request.

**WrTIElJ** (Maker)
Amount of BSQ Burnt: 10
Maker TXN: 3344c2d5c4d2cbbb2a36f263517213bd82cd18c2915d7469c6bfbecde45a1430
![WrTIElJ-tradeinfo](https://user-images.githubusercontent.com/22661489/68556093-bb204280-0480-11ea-9dea-564a736082b6.jpg)
![WrTIElJ-BSQdepost](https://user-images.githubusercontent.com/22661489/68556097-bd829c80-0480-11ea-9038-130c42adb127.jpg)

**DOVOy** (Maker)
Amount of BSQ Burnt: 20
Maker TXN: ddb497db286c57a08a1c290b35b3aa1aaeb308b9d51474431bbad03beb6c9079
![DOVOy-tradeinfo](https://user-images.githubusercontent.com/22661489/68556147-f15dc200-0480-11ea-9210-30374879dfd0.jpg)
![DOVOy-BSQdepost](https://user-images.githubusercontent.com/22661489/68556149-f458b280-0480-11ea-8d17-d1fb7e96b4e5.jpg)

**Comment by leo816** [comment]
information missing

**Comment by xbyvee** [comment]
This reimbursement has been made by the DAO a long time ago so I'm closing this issue. I will be sure to put maker fee txid in the future.
