### ISSUE TITLE
Fee reimbursement for trade alntlvk

### ISSUE THREAD

**Issue by jinusean** [bisq-network/support#327]
![image](https://user-images.githubusercontent.com/6874981/68922284-c8ee0480-07ad-11ea-8134-d05ff5b89dd4.png)

![image](https://user-images.githubusercontent.com/6874981/68923340-aa3d3d00-07b0-11ea-8ab1-aaaf183e7650.png)

Maker: c9bc0f22412a629c99b02336a25f496706a88c8eed239a624c782e1745594ff9
Taker: f925c836cc6f0628611213362bf640341577b2e7a5d840bb20306658ac0da01b
Deposit: 4a13541f77c783746b71a54424adc1a8832d3ef25f9530f15ab879a6e6b9d18e

Bisq version: v1.2.3

Other notes: Transaction failed after deposit was made. How can I get the deposit back as well?
In the log it states, 
```
We found a failed trade with locked up funds. That should never happen
```

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
