### ISSUE TITLE
Trade stuck at step 1

### ISSUE THREAD

**Issue by Krvopije** [bisq-network/support#328]
I took a open offer to buy Bitcoin on saturday and after it didn't get a confirmation in 15 minutes I thought it was just stuck in the mempool for the moment and closed the app and today as I looked it up again it is still at step 1 of the trade process waiting for the confirmation of the deposit_tx

If someone can't follow my explanation, I am talking about the third tx_id that is listed when you look the trade up. As you can see in the picture:
![693251d3-a188-4ced-be02-333ca949678e](https://user-images.githubusercontent.com/34864681/69972659-4f327680-1522-11ea-8dbc-d88d6a27f086.jpg)

Now I did following things so far:
-) Looked it (tx_id) up in different explorer to see if any has it in the mempool. None does.
-) As I am always connected to my full node with bisq I called my bitcoin-cli with getrawtransaction and the tx_id to get the raw transaction so I can rebroadcast it, but got the error "error code: -5 error message: No such mempool or blockchain transaction. Use gettransaction for wallet transactions."
-) To be sure that my bitcoin full node isn't in a broken state or stuck somehow I called different new transactions I made after saturday and always get a succesfull result with the command getrawtransaction.
-) Someone on keybase said he had a similiar issue and he fixed it with a SPV resync that is taking some hours (3-4) now and isn't finished yet (but I have actual backups) 

My questions:
-) Has this happend already to someone? If so, can someone link me to the issue so we don't have the same issue open multiple times, I couldn't find one.
-) If not, has someone an idea how this could have happened and what details/logs do you guys need to make an assumption?
-) How can I initiate the creation of the deposit transaction again?

I didn't post any informations about the fee tx_id from the seller, buyer or other stuff as I am not interested in doxxing the seller until you say that you can't help at all without the informations.

**Comment by Krvopije** [comment]
Ok, I so far just looked at the issues with trade stuck and so on in the titel to see if someone had the same issue, out of boredom waiting for the SPV resync to finish I looked at issues of people asking for a fee reimbursement and seems like this happend to a lot of people. My bad, sorry, should have looked at those first as well!

So it seems like I can only give up fixing it, accept it as it is and ask for reimbursement of the fees, right?

**Comment by chimp1984** [comment]
Please use the keybase support channel if you still have problems.
