### ISSUE TITLE
Fee reimbursement for trade 0930567

### ISSUE THREAD

**Issue by maxkoda-cpu** [bisq-network/support#329]
![bisq-reimbursement-screenshot](https://user-images.githubusercontent.com/59777196/72286536-f2d77200-360a-11ea-84d6-4c3bd614be2b.png)

Maker fee transaction ID: cdfc7b7bb73b899b671bfe0272d9da8ba77fdb40f048899b702d3a7011dcb304

Taker fee trasaction ID:
340cc518994925bc496e6f29e31c7f8f449817fe0d011241436f8b4e83a239a4

Bisq version:
v1.2.5

It looks to me that fee transaction is valid and the fee amount lost.

Here is a screenshot of the Warning I received in the Bisq application:
![Bisq-Trade-Warning](https://user-images.githubusercontent.com/59777196/72286928-c2440800-360b-11ea-933d-d7c4bc2e5922.png)

**Comment by leo816** [comment]
Deposit tx Id information is missing

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
