### ISSUE TITLE
Order failed, see error screenshot

### ISSUE THREAD

**Issue by nagarjuns** [bisq-network/support#33]
![Uploading Screen Shot 2018-01-15 at 6.29.26 PM.png…]()

But 0.00126 BTC deducted from wallet. Have tried deleting and resyncing SPV but no luck.

**Comment by nagarjuns** [comment]
<img width="619" alt="screen shot 2018-01-15 at 6 29 26 pm" src="https://user-images.githubusercontent.com/4080705/34945129-36143c40-fa28-11e7-870f-bfa34148abad.png">

**Comment by cbeams** [comment]
What version of Bisq are you running?

And please go to `Funds->Transactions` and copy and paste here the IDs of the transaction involved.

**Comment by nagarjuns** [comment]
<img width="878" alt="screen shot 2018-01-15 at 7 20 43 pm" src="https://user-images.githubusercontent.com/4080705/34945400-3bd456fa-fa29-11e7-8be4-a43c2705e9ba.png">

**Comment by cbeams** [comment]
Please upgrade to v0.6.3 before making or taking any other offers.

When you post the transaction involved in the timed-out trade, I'll get it queued up for reimbursement.

**Comment by nagarjuns** [comment]
b70f64f80aa9027302e1d334c1c1f1e158c67e1f9c168f438e7c08124dd853cf

**Comment by cbeams** [comment]
> b70f64f80aa9027302e1d334c1c1f1e158c67e1f9c168f438e7c08124dd853cf

Thanks, @nagarjuns. See https://github.com/bisq-network/support/issues/28#issuecomment-358448994, where I've staged this tx for reimbursement. I'll be in touch about the actual reimbursement, which will happen via batch transaction later.

**Comment by cbeams** [comment]
Closing as superseded by #28.

**Comment by cbeams** [comment]
This reimbursement is complete, please see https://github.com/bisq-network/support/issues/28#issuecomment-358533448.
