### ISSUE TITLE
Fee reimbursement for trade 465618

### ISSUE THREAD

**Issue by Sethadon** [bisq-network/support#330]
![image](https://user-images.githubusercontent.com/25136457/72309517-0945f380-3634-11ea-949c-ff7332203ad3.png)

Maker:  65697adc5b81a005bcae6b2889e28daaeea0ed3ccbdadaf9e50da0b025ff727c
Taker: 484824114017ed1f135d474a5689cf368d6aefea93e8b39726589f0f7264d729

Bisq version: 

>v1.2.5

Other notes:

>As the buyer/maker of this failed transaction, I will need my fees reimbursed. Thank you.

**Comment by leo816** [comment]
deposit tx id information is missing

**Comment by Sethadon** [comment]
> deposit tx id information is missing

where do i find that information in Bisq?

**Comment by leo816** [comment]
My mistake, not needed your case. thank you

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
