### ISSUE TITLE
Fee reimbursement for trade 17080362

### ISSUE THREAD

**Issue by appideias** [bisq-network/support#331]
Fee reimbursement for trade 17080362

<img width="879" alt="Screen Shot 2020-01-16 at 11 48 23" src="https://user-images.githubusercontent.com/17833655/72534957-7a64f100-3856-11ea-94d9-a8ba2aaf1f6f.png">

Maker:  728474daa0e1001e249ba9daf10df0a91174976d52fec7cc85b7a8612dd7f049
Taker: 836099e3869364f7bb29431876e90b4c4db5b8a14c1bfd592e4866eece46671c

Bisq version: v1.2.5

Other notes:

Tried SVP resync with no luck.

**Comment by leo816** [comment]
deposit tx id information is missing

**Comment by appideias** [comment]
Sorry. What tx id?

**Comment by leo816** [comment]
nothing, all information is there thanks

**Comment by appideias** [comment]
Oh! Great. Thank you. And congrats on the wonderful work. Bisq is my favorite crypto project.

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by appideias** [comment]
Thanks.

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
