### ISSUE TITLE
@bisq_knight 00001

### ISSUE THREAD

**Issue by Bisq-knight** [bisq-network/support#335]
BEGIN KEYBASE SALTPACK ENCRYPTED MESSAGE. kiaJtA57gQd9eiw WIqKKfcWxVAoNhi 3Zyt9ovjiF3vgrg DZMHSlBJSX38J7l M4ndkMhPUSVVzoR swnP8bTwQFp4Nwt 7b3MLaAsyoJjwU4 A5DPVp7PrjAeHH5 uffJxQd8dKEAqKK AtZQGpTASUoubK7 iv9qEqP2Pb6kdQI FNzal24Nj2RBGuw Mh3oniUuRy3SHIm 7kIykfoavoPeqVx 8nxXIatTjpqYoY2 LQeS1roek0r6Rql jk8rCvgZJhu5TLu MrNNNX29kKEM3Y3 nxq7aXFaZqBXTnf vD67p9ZbXKTHSg6 4XKjq1UkeCfpUrz dsrlwwle9wR1GZy wxac12ZseqEPaiQ hBzRKVU0eoBKNUW ADTTaztIDzwWvju EWteYqDmzS0Dold AeMvJw9EwwDQy8t J4vTKs7jfzdseDe CGN6kWyLfYUOl2U vTgZOEaJ8oraQ4T 7qi4g5lrOrLGHpg Fyg6lRweJUWLnWd UMkLkgkYDwOVTGw uBflqTvrhiot43p j4siIlkA9wlXB3f gXwsnjjKFwOyI0N NDeuMnhMuPgoLvB AESht6D4uN6r0YN BpvAwdyaiVBabbG haa1uCV1LW8NSKq wbv0zORlCWpoN7C 4zKEJ3eBTjQVODs 0avwJLqp74iObtZ bR4MJ3lr6M4jBMk F0niTMywTGrAsq5 i7dsRGdh9w2jhQy Ha7Qg8LrSlsyWot b88eK9m5lB3HDus ccDGNRMeiXrTjSX bDNhUP9TaPug55y l37z6iEgwZvrywV fVpBw8GSy0FG2G2 7rPsxflvv7MMJMm G8xAsvDrPatuMXG k0nx9BWKH7eTIbv GK2r1m2YDppUitW cCe1GlLElY0HmkD XUBfvqD90Ux33IG jmgKC0mm0JvgKcN jOqVKw38KaQIK6n HVDCFblf3fUzG2K R9vnlL1DNBfzS9X 2zzUuFDW1VVAbQB CCsbwdl3Q80jJVq vz8oECSpqXybc0A RCiZRMY0wK342Pt lDLIB83Lm5DbAwt SbSU3RgpezAkxGB gmd5Y5DLB9eEF0I cCc3nQStQFmMKKA 6mghBnAF1yJhA6J H9Cb5rs6PTt0Lr2 UMSChEAlfWnsAHj qu62y59aCBFwTPn QbGiUxdrxBnEbQ3 SVTmpfY1guthZsZ 5XO6pgaK0HySxuG aplxgI4X0kr8NYZ EIjRAB9TzYOhWdp QpQEk497qQvRoMz 16PZrPZ3L1LfUth 02iRnATcL17XE26 9iUcveFzrr1kReH CY4MwntZQc9yqoZ diiB7JoZjKhaB9J VkbjlNwLTvajhvF voXhRy2xRSt8vJz RVKXihr3fgJsK9B gVZbkwwA5URZjFU JXESaMzhS4Cnk1e F2DehVA9QhgvFaG Mq8YNalXjosWXqS QcZBu9Bb50PLhNg StKWrBVNh7AVzXY 1vUxrFYK86858id 7Ro2R39PyjHor70 ohke2vGcVKp9YEG CnwQsPO1bYchHpf yhwvYKDcusavp6K JPHHf88n3DGPK0f DqS4TJx8N6fQjB9 UKmkj8iquVPuE22 DNHvNwbtXeSdswM hFaqQyNdqPB40SO uWq4uzA7mM60M7Z YXq1afjq9qN94W2 Yl16xnH7F0HGCRY Z3CpuAMG2Exlsb3 JEkSODXiuX1SoFp 23GYa8sb1Hy1WWc K4zXpeVc1vNfW3x VE35oEmvrMGtEsc 2WVanPzP2KNII3T nxfsINeeTxbgYZQ QFkOIaLPyCmQhGo FsnAXm0lATAEg4v S6AKAkRaRCrgqPa lM72fzhLsaxrbeA uazaRF1zOvvinwm jyKjWDQRip64MM2 WZcUzBie5l5Pcli jNykRVXqRrKuiHp QJM8jgIaLvIXSmQ TAssLmwkLpOHnNV tfPdjk3a1mnSElx qEpNBpbT7loLRrY 0RjfQoq9cJxijqn voYv32OqXC3k5Ok HIdvbpwh4k9A4Uy nhGYDTw8JVmDwXx GBJwdzlq3H1O1je 8fhL3l1tEFoOFQC Ht0NJzCnE6UgmkN 4vbrZLlelj0H2Xc 9emXZcUCRmjV2nP ILR3ANggrl132wD SEntZJeWoOVkWe2 E2bioLvkwTiIAtw abNG38GrEJncZCJ ltqcFF6gvfMLzE6 uuYDrobVZ0h7lqZ pzH5J9vn2lzfjvp pLHAVdyg658qWQ4 lFl6uNfMqshfXFN qktv1jr5YYSPFQf OlaW1DDb1C8YAGF LclNZF1evB2dVzM E4eBLaPy3Tu7BCJ byj6RBIZotF7i4d QdhbB7T1JNaxlz3 kUwUelE6PQlngvJ Ug035Tx7qoQjw01 qVfNEGQTrFymTfr MNRfnAdI5z. END KEYBASE SALTPACK ENCRYPTED MESSAGE.

**Comment by cbeams** [comment]
@Bisq-knight, I saw that you transitioned this to the `Closed` column without actually closing the issue. In the future, please click Close (as I'm doing now) and you'll notice that on the board the card automatically transitions to `Closed`.
