### ISSUE TITLE
Fee reimbursement for trade qyucsmla

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#341]
![image](https://user-images.githubusercontent.com/57514423/74299813-d159cb00-4d1b-11ea-848c-b190c3900d0c.png)

Maker:  55df4d511138e6b9c12b6296bcc084545d55a398cef0090d14a4844d72ffc659
Taker: 174a6f96a4c1f722c9b4604798def8d43f59d4239177365dd8196418a5bf87a3

Bisq version: 1.2.4

Please reimburse fees

**Comment by leo816** [comment]
deposit tx id information is missing

**Comment by maurobeltran** [comment]
there was not a deposit tx id generated, only maker and taker

**Comment by leo816** [comment]
you are right, thanks

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
