### ISSUE TITLE
Fee reimbursement for trade JHDIYVO

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#342]
![image](https://user-images.githubusercontent.com/57514423/74299936-331a3500-4d1c-11ea-820e-e2f8bfe24acb.png)

Maker:  9166b51ca24401969d0fcb278aa72d115477e344333bb2cb8af510d591de2e04
Taker: 56d57f2fb6d413cbd26b8f153ea4ebb175a07a4e264586a3906768c185c3c0f5

Bisq version: 1.2.5

 Please reimburse fees

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
