### ISSUE TITLE
Fee reimbursement for trade glyclkc

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#343]
![image](https://user-images.githubusercontent.com/57514423/74300029-87bdb000-4d1c-11ea-90ce-e26ea7a1a4ed.png)

Maker:  8585c69ead2b8e1741932b91528261bda9aeaeb3d3d613d85f58d60be8be924e
Taker: 78da89edfc9d5be35c18d64318f38fa999c3a3aa927ed94f2ddda6a210f236f1

Bisq version: 1.2.5

Please reimburse fees

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
