### ISSUE TITLE
Fee reimbursement for trade BAAXII

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#344]
![image](https://user-images.githubusercontent.com/57514423/74300116-d3705980-4d1c-11ea-9b04-17ad43a706fe.png)

Maker:  798f18b68e016b60320ded663da667ab4435c63a99e2f0ca7d354b41cc3cb1f9
Taker: 120cd91845aa0d2a270a518105d6187d54c03b4da1595042fe7049313b5de5cd

Bisq version: 1.2.5

Please reimburse fees

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
