### ISSUE TITLE
Fee reimbursement for trade SKUNBQ

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#347]
![image](https://user-images.githubusercontent.com/57514423/74300447-bd16cd80-4d1d-11ea-8161-4cfd1200abd5.png)

Maker:  448452d753967922e867e05b0742c01ca152ccd9e2966911c39f5f17cb28bf5d
Taker: ca68556449dc0a4323af0c1435cb22735a02398f8003431cb739c7ae1c0ac995

Bisq version: 1.2.5

Please reimburse fees, thanks

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
