### ISSUE TITLE
Reimburse fees lost due to timeouts and transaction broadcast failures

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#35]
# Background

This epic, like #1, captures a set of fee reimbursements, to be paid out in a batch transaction.

At time of writing, there are two types of reimbursement cases we're dealing with:

1. A few remaining "timeout" reimbursements that needed more info and couldn't make it into the batch tx that closed #1.
2. A number of "tx broadcast failure" cases, where trades had to be cancelled because of missing maker/taker/deposit transactions. See bisq-network/exchange#1193 and bisq-network/exchange#1195 for details.

Reimbursements will be staged in `support-35.csv` in the root of this repository, similar to the way `support-1.csv` was used in #1.

## Reimbursement Process

For any remaining _timeout_ cases (like those processed in batch reimbursement #1), @cbeams to follow the same process as was followed in #1, this time adding entries to `support-35.csv` in the root of this repository.

For _transaction broadcast failure_ cases, @cbeams and @keo-bisq to follow the steps below, as originally written up in https://github.com/bisq-network/exchange/issues/1195#issuecomment-357917974:

 1. @cbeams / @keo-bisq to **log the ID of each affected trade** immediately upon arrival in their arbitration queues with a comment in bisq-network/exchange#1193;
 2. @cbeams / @keo-bisq to **create a new issue in bisq-network/support** to track reimbursing whichever transaction(s) _did_ successfully get broadcast for that trade:
   a. add a comment with a screenshot of the Maker/Taker/Deposit section of the trade details and copy and paste the text values of the Maker/Taker/Deposit transaction IDs. See https://github.com/bisq-network/support/issues/37#issuecomment-358646820 for an example of how this should be done.
 3. **Send arbitration chat messages to both buyer and seller** explaining what happened and what to expect next. Here is a copy-and-paste template, but BE SURE TO REPLACE THE `FIXME` TEXT BELOW IN THE GITHUB ISSUE URL, EMAIL ADDRESS AND PGP KEY URL:

> ATTENTION: This trade will be closed shortly, in favor of handling the reimbursement process via the GitHub issue at `https://github.com/bisq-network/support/issues/FIXME`
> 
> WHAT YOU NEED TO DO NOW: 
> 
> 1. Subscribe for updates on the GitHub issue. There are instructions how to do this in the description of the issue. If you had a transaction get successfully broadcasted to the Bitcoin network as part of this trade, you will be reimbursed for your Bisq trading fee and for your Bitcoin mining fee. The reimbursement will be paid to the address originally used as input to the transaction.
> 
> 2. Delete and resync your SPV file. This can be done at `Settings->Network info->Resync SPV chain`, and it will ensure that any failed transactions related to this trade no longer affect your available balance.
> 
> FURTHER QUESTIONS?
> 
> If you have any further questions, you have two choices:
> 
> 1. Ask them on the GitHub issue linked above. Just keep privacy implications in mind if you do.
> 2. Ask me via email to FIXME. If you prefer to encrypt, my PGP key is available at https://FIXME
> 
> You can also ask any follow-up questions here before I close the issue. But I will close it soon!
 4. **Close the arbitration ticket,** using "BTC seller gets trade amount payout". Note that this will have no effect, but you have to provide _some_ value here in order to close the ticket, so we may as well be consistent in our approach and this is the safest option to choose anyway.
 5. **Assign the GitHub issue** to @cbeams (if it is not already).
 6. @cbeams to **stage each transaction for reimbursement** in [`support-35.csv`](https://github.com/bisq-network/support/blob/master/support-1.csv) and comment on the GitHub issue accordingly.
 7. Repeat steps 1–6 until @ManfredKarrer has a fix for the issue and has shipped a new release
 8. Announce the release and wait a few days for everyone to upgrade and for any in-flight trades suffering from this problem to make their way into arbitration.
 9. Craft and **send a batch transaction that reimburses all staged transactions** from step (6).
 10. **Close all the GitHub issues** created in step (2) with a comment linking to the batch reimbursement transaction in step (9).

**Comment by cbeams** [comment]
I've updated the description of this issue with detailed instructions as to how we'll process these reimbursements. I'll have some examples ready shortly.

**Comment by cbeams** [comment]
@keo-bisq, you'll find that issues have been created and assigned to you for reimbursing each of the trades you've reported in bisq-network/exchange#1193 so far. You can see and manage them at https://github.com/bisq-network/support/projects/1.

From the **Reimbursement Process** section of the description at the top of this issue, please start with step 2(a) for all existing trades, and please start at step 1 for any _new_ trades that come into your arbitration queue affected by this problem.

My trigger to act on and stage your trades for reimbursement will be step (5) when you have completed your steps and you assign the issue to me.

Thanks!

**Comment by cbeams** [comment]
@keo-bisq, note that for new issues (like `bVPHQa`, which just came in), I'm moving to closing the issue immediately, and using the following message when I do:

> ATTENTION: This trade is affected by a networking bug that is currently under investigation, and this arbitration ticket is being closed immediately in favor of handling it for reimbursement via the GitHub issue at `https://github.com/bisq-network/support/issues/53`.
> 
> WHAT YOU NEED TO DO NOW:
> 
> 1. Subscribe for updates on the GitHub issue. There are instructions how to do this in the description of the issue. If you had a transaction get successfully broadcasted to the Bitcoin network as part of this trade, you will be reimbursed for your Bisq trading fee and for your Bitcoin mining fee. The reimbursement will be paid to the address originally used as input to the transaction.
> 
> 2. Delete and resync your SPV file. This can be done at `Settings->Network info->Resync SPV chain`, and it will ensure that any failed transactions related to this trade no longer affect your available balance.
> 
> FURTHER QUESTIONS?
> 
> If you have any further questions, you have two choices:
> 
> 1. Ask them on the GitHub issue linked above. Just keep privacy implications in mind if you do.
> 
> 2. Ask me via email at chris@beams.io. If you prefer to encrypt, my PGP key is available at https://chris.beams.io/pgp.txt
> 
> Thank you.

**Comment by cbeams** [comment]
Here is an easier to copy and paste version of the "close ticket" message I posted above:

```
ATTENTION: This trade is affected by a networking bug that is currently under investigation, and this arbitration ticket is being closed immediately in favor of handling it for reimbursement via the GitHub issue at https://github.com/bisq-network/support/issues/53.

WHAT YOU NEED TO DO NOW:

1. Subscribe for updates on the GitHub issue. There are instructions how to do this in the description of the issue. If you had a transaction get successfully broadcasted to the Bitcoin network as part of this trade, you will be reimbursed for your Bisq trading fee and for your Bitcoin mining fee. The reimbursement will be paid to the address originally used as input to the transaction.

2. Delete and resync your SPV file. This can be done at `Settings->Network info->Resync SPV chain`, and it will ensure that any failed transactions related to this trade no longer affect your available balance.

FURTHER QUESTIONS?

If you have any further questions, you have two choices:

1. Ask them on the GitHub issue linked above. Just keep privacy implications in mind if you do.

2. Ask me via email at chris@beams.io. If you prefer to encrypt, my PGP key is available at https://chris.beams.io/pgp.txt

Thank you.
```

**Comment by cbeams** [comment]
Here is an updated version of the "close ticket" message I'm using, now that the fix for this issue is out with v0.6.4:

```
ATTENTION: This trade is affected by a networking bug in Bisq v0.6.3 that has been fixed in v0.6.4. This arbitration ticket is being closed immediately in favor of handling it for reimbursement via the GitHub issue at https://github.com/bisq-network/support/issues/54.

WHAT YOU NEED TO DO NOW:

1. Subscribe for updates on the GitHub issue. There are instructions how to do this in the description of the issue. If you had a transaction get successfully broadcasted to the Bitcoin network as part of this trade, you will be reimbursed for your Bisq trading fee and for your Bitcoin mining fee. The reimbursement will be paid to the address originally used as input to the transaction.

2. Delete and resync your SPV file. This can be done at `Settings->Network info->Resync SPV chain`, and it will ensure that any failed transactions related to this trade no longer affect your available balance.

FURTHER QUESTIONS?

If you have any further questions, you have two choices:

1. Ask them on the GitHub issue linked above. Just keep privacy implications in mind if you do.

2. Ask me via email at chris@beams.io. If you prefer to encrypt, my PGP key is available at https://chris.beams.io/pgp.txt

Thank you.
```

**Comment by jenechka1** [comment]
Hello. My "Close Ticket" message referenced issue 53, which is obviously someone else's transaction. I understand this is a blanket message, but it would be better if it said as much.

Anyway, my transaction is in the same boat as the rest of the ones mentioned here. How do I get reimbursed? Trade: BLobJUX

**Comment by cbeams** [comment]
@jenechka1, sorry for the confusion. Please see #60, which I've just created to track your case, and where I'll have a request for you in the comments shortly.

**Comment by cbeams** [comment]
Closing as complete. The following batch transaction has just been broadcast and should confirm within a few blocks. From https://tradeblock.com/bitcoin/tx/0af2f3a4af6c66adc8b98112515363c3278c077e22a4d7148e7104a23fdecbfd:

![image](https://user-images.githubusercontent.com/301810/35642005-186026c2-06c2-11e8-9c69-bc937122f9af.png)

The set of addresses and amounts was produced by running the following command against `support-35.csv` in the root of this repository at commit 8931f7c:

`awk -F, '{print $3 "," $4+$5}' support-35.csv | grep -v address | sort > reimbursements.csv`

This prints out the address to reimburse (3rd field), then the sum of the trading fee (4th field) and minining fee (5th field), eliminating the first line of the file which consists of headers.

The resulting CSV file was then fed into Electrum in the `Send` screen after selecting the `Tools->Pay to many` menu option.

Thanks to everyone involved, and if you haven't heard the news, the bug that wes at the source of most of these failed trades have been fixed in Bisq v0.6.4. Trade on!

**Comment by regnarock** [comment]
Hi there!

It seems, like @jenechka1, that I have been redirected to issue #54, which is clearly someone else reimbursement. 

My trade id's: kcjfky

**Comment by cbeams** [comment]
@regnarock, details for trade `kcjfky` can be found at #61.
