### ISSUE TITLE
Fee reimbursement for trade 062481

### ISSUE THREAD

**Issue by grahamf21** [bisq-network/support#353]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Bisq trade 062481](https://user-images.githubusercontent.com/18185111/76398446-cde64d80-6374-11ea-826b-e0dd9e15abc4.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  2c1d963bc4e3084e77911fa9bff665d68742b97f1392641a11c347b365a80dd6
Taker: b4f4871fa10e14664634b879b5a13474e491536e397cd40d51ce112d14f22558
Deposit: 0.017235

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.2.7

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:
Maker fee transaction not found, 2c1d963bc4e3084e77911fa9bff665d68742b97f1392641a11c347b365a80dd6
Taker fee transaction found, b4f4871fa10e14664634b879b5a13474e491536e397cd40d51ce112d14f22558

No blockchain confirmations received, transaction seems to have failed.

Please refund fees.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Maker: 2c1d963bc4e3084e77911fa9bff665d68742b97f1392641a11c347b365a80dd6
Taker: b4f4871fa10e14664634b879b5a13474e491536e397cd40d51ce112d14f22558

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968

**Comment by grahamf21** [comment]
Many thanks.

Regards,

Graham
