### ISSUE TITLE
Fee reimbursement for trade 197644

### ISSUE THREAD

**Issue by muaawiyahtucker** [bisq-network/support#354]
![Screenshot 2020-03-11 11 42 20](https://user-images.githubusercontent.com/35174370/76413569-98019300-638d-11ea-8570-5e551160a42b.png)

Maker:  7bfd9da078eded3ec3c970717a3339f601e07453881bea1eb6c25d4fc12fd82f
Taker: 5d0dc7012ca2f4355fef2c405443b604736cf981aa8f4865d0e5f381b5cae67f
Deposit: 0.0375 BTC

Bisq version: v1.2.7

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
