### ISSUE TITLE
Fee reimbursement for trade 97877666

### ISSUE THREAD

**Issue by SirLaffalot** [bisq-network/support#355]
Trade ID: 97877666-174ec7e2-f5cf-498b-a75b-cae78649468b-127

![Screenshot_2020-03-11_09-32-00](https://user-images.githubusercontent.com/9166635/76428836-37b62580-637c-11ea-87fc-15fcb44e9593.png)

Maker: 3312c5e63fef4d8b7e1a74ef13962356a946e4fd0922e8cb4c52b5975a055154
Taker: 69e33858ee37fa5a043fbbd2b5f90553cbb636805f80f2e660e51eac2b19f9b7
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:  v1.2.7

Other notes: 
I already tried deleting the SPV file and resyncing, and I got this screen:

![Screenshot_2020-03-11_09-02-38](https://user-images.githubusercontent.com/9166635/76430112-ef980280-637d-11ea-997e-7880359d10b7.png)

The taker fee is missing from my wallet and the TX for it is confirmed.

Please reimburse.

**Comment by leo816** [comment]
Maker: 3312c5e63fef4d8b7e1a74ef13962356a946e4fd0922e8cb4c52b5975a055154
Taker: 69e33858ee37fa5a043fbbd2b5f90553cbb636805f80f2e660e51eac2b19f9b7

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
