### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by Sethadon** [bisq-network/support#356]
**QUESTION**: Is Bisq expected to use more memory over time, as it stays open on the network? I notice at startup that my memory usage is one value, and then when I check again in the morning the next day, it's memory usage is significantly higher:

**Memory at startup:**
![bisq-memory-at-startup](https://user-images.githubusercontent.com/25136457/76708237-93511d80-66b2-11ea-82ff-3794464ce6fa.png)

**Memory next day:**
![bisq-memory-overnight](https://user-images.githubusercontent.com/25136457/76708242-9ba95880-66b2-11ea-8cf3-f7ca94f7f85f.png)

**Comment by pazza83** [comment]
Closing as stale
