### ISSUE TITLE
BTC Disappear from my BISQ 

### ISSUE THREAD

**Issue by green41k** [bisq-network/support#357]
everything was allright til today. all balances at zero
but cmnd+e show my balance. and deleting SPV didn't help to fix the problem.
What also can I do to see my balance

**Comment by Bayernatoor** [comment]
Hey there, odd that SPV re-sync wouldnt fix the balance issue since the funds are clearly in your wallet. Have you upgraded to v 1.2.9 ? I'd also recommend that you backup your entire Bisq directory.

**Comment by green41k** [comment]
> Hey there, odd that SPV re-sync wouldnt fix the balance issue since the funds are clearly in your wallet. Have you upgraded to v 1.2.9 ? I'd also recommend that you backup your entire Bisq directory.

Yeah! i tried 2 times to re-sync... and have last updated version 

as soon as i updated everything was good, but 2 days late - same problem...
