### ISSUE TITLE
Create payment methods wiki page

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/support#359]
Looking for suggestions for the Payment methods wiki page. The https://docs.bisq.network/payment-methods.html contains quite a bit of information so this would make for a long wiki. 

My plan is to break it up into the following pages:
1. Payment methods
2. Account signing
3. How to have your account signed
4. Altcoin payment methods 

Regarding #1,  the payment option table is very informative so i was planning on including that as is. 

I would consider these pages to be features and would include them under the feature category.

Any suggestions/feedback is appreciated!

Thanks

**Comment by MwithM** [comment]
To me, there's three points, the one is explaining two payment methods with their own place to create accounts for: national payment methods and altcoins. There's no need to separate betweeen points 1 and 4.

**Comment by Bayernatoor** [comment]
Sounds good, I'll go that route.
