### ISSUE TITLE
My offer shows in my portfolio but not in the market

### ISSUE THREAD

**Issue by olgierdsh** [bisq-network/support#36]
I've made an offer to sell BTC for Euro - can see it under My Portfolio tab, but not in the actual market for BTC-EUR or in the Offer Book for Euro (BTC/EUR).

And in History, I see an old BTC/GBP offer that I had cancelled showing as 'Available' under Status.

Bisq is fully synced.

**Comment by cbeams** [comment]
Have you looked under the "Buy BTC" tab?

Also check your settings. Make sure you haven't disabled showing your own offers.

**Comment by olgierdsh** [comment]
Thanks - I think I changed the Filter by Currency to Euro, but didn't then click the Buy BTC button above again.


Shouldn't the old cancelled GBP offer show as Cancelled rather than Available in My Portfolio--> History


________________________________

**Comment by cbeams** [comment]
> Shouldn't the old cancelled GBP offer show as Cancelled rather than Available in My Portfolio--> History

Not sure. Screenshot?

**Comment by cbeams** [comment]
Closing as dropped / out of date
