### ISSUE TITLE
Reimbursement for Refund Agent: Cycle 11

### ISSUE THREAD

**Issue by RefundAgent** [bisq-network/support#360]
Amount requested 91866.27 BSQ

As the Refund Agent I ask for 91866.27 BSQ in reimbursement. This is the amount of BSQ I have sold in order to cover my BTC payouts to the traders as a Refund Agent.

See https://github.com/bisq-network/roles/issues/93 for the report detailing this.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by Bisq-knight** [comment]
Cycle 11
Approved
