### ISSUE TITLE
Fee reimbursement for trade P5r7qirx

### ISSUE THREAD

**Issue by chyork** [bisq-network/support#361]
![Screenshot from 2020-03-18 11-21-29](https://user-images.githubusercontent.com/62352805/76994026-05bc3a80-690b-11ea-85f7-bc016035a973.png)

Maker: c207f9e0542d98c968ff2fe5cbf7c2be31fdeef4c43b364187c6a3e370fabda5
Taker: b646e4d992db6709ff34bf9364e578ca2c6bf6d615a1d9e140315ac07d6e3507

Bisq Version 1.2.9
Please reimburse fees

**Comment by chyork** [comment]
If I could also get an email or a way to send a PM here I have a concern regarding this transaction I'd like to discuss.

**Comment by chyork** [comment]
Deopsit ID:
1CFHUiQnQXUyKPofgdcFsDxXfdk5PVxRuS

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
