### ISSUE TITLE
Fee reimbursement for trade PCFSX

### ISSUE THREAD

**Issue by chyork** [bisq-network/support#362]
![Screenshot from 2020-03-18 22-15-54](https://user-images.githubusercontent.com/62352805/77038382-e657f880-6970-11ea-81b9-98f5163b2185.png)

Maker:  380c4f2d17f561cc9b337d8aa02738c79ffbd5497be68b03551ed240a3041194
Taker: 7857e69fa378412886843fa9257eec0a3366fe03301e4921e29c471c9e4269b9

Bisq version: 1.2.9

Please reimburse fees

**Comment by leo816** [comment]
deposit tx id information is missing

**Comment by chyork** [comment]
Deposit ID:
1CFHUiQnQXUyKPofgdcFsDxXfdk5PVxRuS

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
