### ISSUE TITLE
Error message as MEDIATOR

### ISSUE THREAD

**Issue by leo816** [bisq-network/support#363]
Got this error message when I initiated the app this morning
SCREENSHOT HERE

<img width="1014" alt="Captura de pantalla 2020-03-20 a las 10 06 46" src="https://user-images.githubusercontent.com/54798241/77149962-0d0e5000-6a93-11ea-848b-3c78fac6639d.png">

Other notes:

**Comment by cbeams** [comment]
This is something that (likely) only @bisq-network/bisq-devs can solve, and so it should be opened in as an issue in the main bisq-network/bisq repository. Being opened here in the support repository, it runs the risk that the right people won't see it / prioritize it accordingly.

**Comment by wiz** [comment]
I would guess it was because someone testing the Australian Pay ID payment method was testing on mainnet and opened a mediation support ticket for payment method that doesn't exist in Leo's app so it throws an exception

**Comment by ripcurlx** [comment]
> I would guess it was because someone testing the Australian Pay ID payment method was testing on mainnet and opened a mediation support ticket for payment method that doesn't exist in Leo's app so it throws an exception

Yes, that is exactly what happened. It tried to resolve the payment account payload and went into the default case (Australian Pay ID was not found), which throws this exception. As this is nothing that would be triggered for everyone, like the broken offer case, I think we shouldn't silence this exception.

**Comment by pazza83** [comment]
Closing as stale
