### ISSUE TITLE
Fee reimbursement for trade JZYNPC

### ISSUE THREAD

**Issue by webintelligence** [bisq-network/support#364]
<img width="900" alt="Screen Shot 2020-03-21 at 10 09 57 PM" src="https://user-images.githubusercontent.com/4423846/77241603-86589080-6bc2-11ea-89d8-dcb90bfff9bf.png">

Maker: d5cde5094b4aeae321cc07a0ea8bf8e0f3a1d987d2905015e0159cc206160eaf
Taker: 3557d11736b575e553a39b2a16a3cb64158c2af2b27c6107523201460b7e4d5d

Bisq Version 1.2.9
Please reimburse fees

**Comment by leo816** [comment]
deposit tx id information is missing

**Comment by webintelligence** [comment]
Where can I find that? Not seeing it in Transactions...may have been a casualty of my failed upgrade and rollback (Mac OS)--pretty sure that was the cause of the failure. I posted the offer prior to that. Thx.

**Comment by leo816** [comment]
yes you are right, all the information is there thanks

**Comment by webintelligence** [comment]
Thx. Please let me know if you need anything else to facilitate refund of fees and deposit (0.03121310 BTC).

**Comment by webintelligence** [comment]
Hello any update on this?

**Comment by leo816** [comment]
we are working on it, please be patient. thank you

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by webintelligence** [comment]
Why is this taking so long?

**Comment by leo816** [comment]
> Why is this taking so long?

Hi, right now waiting for the previous fee reimbursement agent to walk through the final steps, hopefully will be done soon

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/366#issuecomment-625274968
