### ISSUE TITLE
Stuck trades no mediator or trader response.

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#369]
Since 3 days i have several trades stuck. Opened support ticket with mediators. 
They don't reply. The trade partners also don't reply or confirm my payment.

Any way i can get this resolved? 

For cross reference https://bisq.community/t/trolls-scammers-active-on-the-xmr-btc-market/9158/4

(sorry, it's not clear to me what is the appropriate place to ask for support)

**Comment by leo816** [comment]
what is the onion address of the mediator?
