### ISSUE TITLE
Fee reimbursement for trade 4794340

### ISSUE THREAD

**Issue by bobbyonbisq** [bisq-network/support#370]
SCREENSHOT HERE

![image](https://user-images.githubusercontent.com/63121369/78393546-552c8700-75ea-11ea-8683-9b7dbd04f0cd.png)

Maker: 471264a1d21d2e8960408bb42ca9c46e790f60ac28e56e33674afc4f7272eaab
Taker: f2e793f0252636bb24516c5e608df26b9785eb26dec5e091e9e7642d83313df7

Bisq Version 1.2.9
Please reimburse fees

Deposit: where to find?

This was the error message (remaining the same after some restarts):

![image](https://user-images.githubusercontent.com/63121369/78394900-c4a37600-75ec-11ea-9e87-1cdc39749bb7.png)

**Comment by bobbyonbisq** [comment]
Thank you for not forgetting my issue.
Please let me know if anything else in needed.
Bobby

**Comment by leo816** [comment]
Will be reimbursed with #366

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by bobbyonbisq** [comment]
Thank Yoe

leo816 <notifications@github.com> schrieb am Di., 30. Juni 2020, 14:41:

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
