### ISSUE TITLE
Request reimbursement in the form of BSQ

### ISSUE THREAD

**Issue by joergsen** [bisq-network/support#371]
Apparently, I'm supposed to be the victim of a rare bug. At least the moderators Bisq Keybase think I should open an issue here - the request for reimbursement in the form of BSQ.

Obviously never again contact the seller. Payment was made as the rule. Didn't get anything. Deposit's gone, too. 

"id": "94885-ff49c3a8-1a7f-4dae-94b7-c904d0ad9870-124",
"tradeAmount": 6500000,
"buyerSecurityDeposit": 750000,
"txFee": 4070,
 "makerFee": 15000,

**Comment by sqrrm** [comment]
This reimbursement is quite lacking in information. Is there a mediator that was involved in this case that can verify these claims?

@leo816 Do you have an opinion on this request?

**Comment by joergsen** [comment]
Yeah, leo is the mediator. He and wiz are in charge of the case and have advised me to create this issue and a reimbursement request in bisq. 
Unfortunately, I cannot explain the exact cause of this failed trade. According to wiz and leo it was a bug that caused it.
Fact is only: the full amount was verifiably paid. but the seller never contacted me again. With is missing the trading amount + deposit.

**Comment by leo816** [comment]
> This reimbursement is quite lacking in information. Is there a mediator that was involved in this case that can verify these claims?
> 
> @leo816 Do you have an opinion on this request?

Yes, the reimbursement request is correct and was approved by wiz and myself. The question is if this is the right place to post it and what information should be displayed here from the trade. I believe this is the first time this has happened, but if there have been others let me know for reference.
