### ISSUE TITLE
Fee reimbursement for trade 025766

### ISSUE THREAD

**Issue by 2goodtraders** [bisq-network/support#373]
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/63383093/78852993-22a6e200-7a61-11ea-8ca0-994ba87747f8.png)

Maker:  ef5a8562d04420386b4b5f06891fde6a7103cd6155c257fbc4f20af087611f21
Taker: d8c964e0d21160621df196bc10ce95ff9b5791c36f2863ea87ebb7b878740c29
Deposit: 4fc8cf59ed921ce884c1ee53426443dd465b319aba11f7a49390b157aaa61b54

Bisq version: 1.2.9  

Other notes:  mediation resolution was accepted, but no response from other party.  After learning of bug, I upgraded to v1.3.1 shortly before trade went to arbitration.  and resynced SPV to unlock deposit funds.
Seeking reimbursement of fees.  Additionally, BTC is now 20% more expensive than the agreed trade price which failed, so any reimbursement of this difference would also be much appreciated.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
