### ISSUE TITLE
Payout reimbursement for trade hjKwrMp

### ISSUE THREAD

**Issue by danielv1234** [bisq-network/support#374]
![Screenshot 2020-04-09 at 14 14 47](https://user-images.githubusercontent.com/26386779/78889575-94385d80-7a6c-11ea-9f0c-3379c8d4b591.png)

Maker:  1c0f90342f3d388cae48528013896ad9b2b40001150e5fb89d59548d63ff7d3d
Taker: 18dea8e07b56844b113daab56a99f0020dd80fafa30574f22acec893eea9337e
Deposit: a49e8910e3b22e37e3b38c88531ec0d5d2690ae611d68852816c5f3c34f2d9c5

Bisq version:1.2.9 when happened 1.3.1 now

Other notes:
MOnero payment details :

Tx ID:
71bafabd646dd68c1c10a757c38af1ed4b7a019fa80e620bca5224201f287ec9
Date:
2020-04-07 19:39:12
Amount:
248.6996119 XMR
Address:
4853tNcQtdRWH2oTKr5dqF6cmkk886oRo8c59155hikTP1gmpqusorsZUrwxcMwUVzJqxuGyNp872YidrC3ccYU346rfRK8
Payment ID:
0000000000000000
Tx key:
813969095ca34bb2d86906b220283ca023b718abfad14998f2668eb42996c104
Destinations:
248.699611900000: 8614NfAqHpSDUebMz4cufpQwjpy4zopqXWiq8xFvsjkufF3WKZrpenm6DF9ivn3HNYLKWHfxL8DJs8axZrC6KhwU5rShqZJ
Rings:
d3862e84bffc14526e6246365eef1f301e57a54c70bff78534cab591f50b1d61 absolute 15553559 15930525 16054677 16069827 16111704 16115264 16124368 16132605 16133166 16134734 16135246

**Comment by cbeams** [comment]
@danielv1234, are you on the Bisq Keybase team? If not, could you join and contact me (@cbeams) to discuss this? https://keybase.io/cbeams

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
