### ISSUE TITLE
Fee reimbursement for trade 649083

### ISSUE THREAD

**Issue by githubclear** [bisq-network/support#375]
![Screen Shot 2020-04-12 at 3 33 51 PM](https://user-images.githubusercontent.com/63559055/79077986-35c0e880-7cd3-11ea-9075-8a4037dba4b7.png)

Maker:  a27b5bd637a47fbf5002ae70dc76cea83f9c7037176fc986ed6e5fe227ea3ff7
Taker: 197d4342feb152b8e87e40e94b0999ffe703415da936904513ccaa09c2e6f626
Deposit: ..........

Bisq version:

v1.3.1

Other notes:

After update to v1.3.0 and then to v1.3.1, the offer that was made in v1.3.1 and then taken is in the failed folder.  There was never a failed trade before this update. Please reimburse fees.

**Comment by githubclear** [comment]
Still patiently waiting on resolution for this, thank you.

**Comment by githubclear** [comment]
Still patiently waiting for resolution of this 1.5 months later. Thank you.

**Comment by leo816** [comment]
This will get reimbursed on the net cycle

**Comment by githubclear** [comment]
When is this supposed "net cycle", it has been 2 months with still no reimbursement.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
