### ISSUE TITLE
Fee reimbursement for trade 244780

### ISSUE THREAD

**Issue by githubclear** [bisq-network/support#376]
![Screen Shot 2020-04-12 at 3 42 19 PM](https://user-images.githubusercontent.com/63559055/79078151-576e9f80-7cd4-11ea-8a8d-62af13c35483.png)

Maker:  2769620f179aa80791ff42c74633310fea229c1b198db095c2bc83ce2358a3ab
Taker: 8db7a271c949701f0e53c6e5daec52e427b03ba8f1f0b26656c674472ace1b55
Deposit: ..........

Bisq version:

v1.3.1

Other notes:

After update to v1.3.0 and then to v1.3.1, the offer that was made in v1.3.1 and then taken is in the failed folder.  There was never a failed trade before this update. Please reimburse fees.

**Comment by githubclear** [comment]
Still patiently waiting on resolution for this, thank you.

**Comment by githubclear** [comment]
Still patiently waiting for resolution of this 1.5 months later. Thank you.

**Comment by leo816** [comment]
hi, this will get reimbursed on the net cycle (14)

**Comment by githubclear** [comment]
When is this supposed "net cycle", it has been 2 months with still no reimbursement.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
