### ISSUE TITLE
Taker Fee Reimbursement for trade 430499

### ISSUE THREAD

**Issue by bisqgithub** [bisq-network/support#377]
Details below
![bisqfailed](https://user-images.githubusercontent.com/63674613/79269590-f40e7a00-7e59-11ea-85ff-4958a470dc67.png)

Maker: 6248b22f1b7212f89f563a7458685139deb63698e3e13c8a7452bc60b8321b09
Taker: d1e67cd389572907014cfb176a9da523b19766c2ddc5259ee2c1fc280ecce730

Most recent version of bisq (1.3.1). Thanks.

**Comment by bisqgithub** [comment]
Well, happened again. What's up with bisq? The following is another, SEPARATE request for fee reimbursement:

![bisqfailed2](https://user-images.githubusercontent.com/63674613/79270658-c296ae00-7e5b-11ea-9d35-f8ce9aff5949.png)

Same application details as above.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
