### ISSUE TITLE
Fee reimbursement for trade pxoutpnb

### ISSUE THREAD

**Issue by archerchik** [bisq-network/support#378]
<img width="878" alt="Screen Shot 2020-04-15 at 12 21 34 AM" src="https://user-images.githubusercontent.com/63704596/79310360-a7a25900-7eb0-11ea-8997-d3a74abcff3d.png">

Missing fees for failed transactions.

1st failed transaction:
Maker:  0907824b8c92a7fc107788630b058ab92f3b492189b4cafbb11497b58bd3e7b0
Taker: 0f81eb586d1d17ecccbd0c517cd55d4b84506145df5e7c733d7e5dafb6bcf9b4
Deposit: ..........

Most recent version of bisq (1.3.1)

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
