### ISSUE TITLE
Fee reimbursement for trade 0640030 

### ISSUE THREAD

**Issue by archerchik** [bisq-network/support#379]
<img width="877" alt="Screen Shot 2020-04-15 at 12 21 45 AM" src="https://user-images.githubusercontent.com/63704596/79310506-ed5f2180-7eb0-11ea-8a66-eb0fbecc25d2.png">

Missing fees for failed transactions.

failed transaction:
Maker: 21ba075420881cdfb44b23b86ce59b1494ab9f7efaa4fe6cb3780483ded28f9c
Taker: ac61f9b54b658616b9103725c1b698f8ee40a1a7e554f841b2d3c188f412b9e2
Deposit: ..........

Latest bisq version: 1.3.1

**Comment by archerchik** [comment]
I also can't withdraw my funds I keep getting an error and then have to delete the SPD file to see my funds again. Have tried this several times now. What the hell is going on???

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
