### ISSUE TITLE
Maker Fee Reimbursement for BNNZC

### ISSUE THREAD

**Issue by gitman23** [bisq-network/support#380]
Maker fee transaction id:  b0fb81f86d59c15848fb248f4041a24de4c1b637e8955caa301e57f6358f0e63
Taker fee transaction id:  095a269cb81604891e92425cf1450b5555f78c81b810e9a4abbe213e443df359

An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Donation address is invalid.

Thank you!

**Comment by leo816** [comment]
information required is missing. you have to post a screenshot of the trade without revealing the private information

**Comment by pazza83** [comment]
Closing as no additional info provided.
