### ISSUE TITLE
Fee reimbursement for trade NI4CCID4

### ISSUE THREAD

**Issue by guest32840** [bisq-network/support#382]
![Screen Shot 04-14-2020 at 05 01 PM_2](https://user-images.githubusercontent.com/63875596/79605861-8787bb00-80a5-11ea-8be6-ae16f398c723.png)

Maker:  fbf987e83671a6efb407a0a4197b7b072c62588de34ea1d94e24c25f3a89f2aa
Taker: e07d35ed2e6e60decbf0aeb3fcd9e1fa63dcec0c30d0c056bb80d23786a5b7f9
Deposit: ..........

Bisq version: 1.3.1

Other notes:

Error Message:
>An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
>Donation address is invalid.
>Address used by BTC seller: 3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp
>Recent donation address:3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV
>Default donation address: 1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7
>Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

Trade state: TAKER_FEE_PUBLISHED

Screenshot of first error screen included:
![Screen Shot 04-14-2020 at 04 55 PM](https://user-images.githubusercontent.com/63875596/79606531-97ec6580-80a6-11ea-8648-dfbb893a357c.png)

Log attached:
[bisq_1 2020-04-14.log](https://github.com/bisq-network/support/files/4494841/bisq_1.2020-04-14.log)

It's in failed-folder. Please reimburse fees.
Thanks.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
