### ISSUE TITLE
Fee reimbursement for trade KS2BB9O

### ISSUE THREAD

**Issue by thorie7912** [bisq-network/support#383]
![image](https://user-images.githubusercontent.com/869094/79685787-39cb9980-81f0-11ea-8f5e-9759869b1081.png)

Maker: 5fca003f4eaf89280eb902481f1f92a5ac52741283b7bc324407e4ff1021e98a
Taker: c51ff12e6fd4af3e96d00a08e36816d58c1fdb0a609babdba9e57d97348e8b74
Deposit: ..........

Bisq version: 1.3.1

Other notes: The other side immediately got an error when they tried to take my offer. This is the 3rd attempt that failed. I think something is very much bugged. I might have to re-install Bisq or something, I'm not sure right now.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
