### ISSUE TITLE
Fee reimbursement for trade YYPUKN

### ISSUE THREAD

**Issue by thorie7912** [bisq-network/support#384]
![image](https://user-images.githubusercontent.com/869094/79685857-a6469880-81f0-11ea-9cf7-b8f390a84b82.png)

Maker:  b9f6ae16315978df3ddf7681aef91fe16ead2c50854c6f1351edae197cba3b88
Taker: 652355464336095a6fc49f139dcb61b721ac9848d44cae4867be6ce73064dbfc
Deposit: ..........

Bisq version: v1.3.1

Other notes:

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
