### ISSUE TITLE
Fee reimbursement for trade ub60IpJP

### ISSUE THREAD

**Issue by thorie7912** [bisq-network/support#385]
![image](https://user-images.githubusercontent.com/869094/79685876-d4c47380-81f0-11ea-96f9-9b24bc88e5af.png)

Maker:  effc5703b2305b394029be757a05ef63f07b0ed0d20b1904129dcbd6741848c8
Taker: dca31a1b7267b0c6b93a8a43f79dddae69791ef123f97ce29610c0a58a80c0ad
Deposit: ..........

Bisq version: v1.3.1

Other notes:

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
