### ISSUE TITLE
Fee reimbursement for trade Skqga

### ISSUE THREAD

**Issue by gitman23** [bisq-network/support#386]
Trade id: Skqga-3855cdbc-aeae-46f0-b938-dca6d82fbf27-131
Maker: 2ddb4e2816610d8b30a308d708d7b02d4419c9ac9b5b188ff436e1195bca324e
Taker: d9a5e7dc031f0bae0377a656ab5ef012ed3c47b86f7bb125221a98caf3c128e6

Bisq version: 1.3.1

Other notes: 
Trade state:  TAKER_FEE_PUBLISHED
Error message:
"An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Donation address is invalid.
Address used by BTC seller: 3E......
Recent donation address:3A.....
Default donation address: 1B....."

No screenshot because it includes private data

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
