### ISSUE TITLE
Fee reimbursement for trade 140259

### ISSUE THREAD

**Issue by dgyg** [bisq-network/support#387]
Trade id: 140259-57fe5be4-84de-4601-bf93-2ecc64c7dedc-131

![140259](https://user-images.githubusercontent.com/7886722/79695370-04619300-8266-11ea-8b50-e55756d5f4bf.png)

Maker: d06402483be36f0075701d293d770047faebd4f7cf7112f79472e3d7b78a736e
Taker: 15c9febec9dc28e269d71e36855f63d19dedbd923164d203022e7c1ebf75af7c
Deposit: <not published>

Bisq version: v1.3.1

Other notes:

Error message
```
An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
Donation address is invalid.
Address used by BTC seller: 3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp
Recent donation address:3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV
Default donation address: 1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()
```

Can you please reimburse the trading fees. 
Thanks

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
