### ISSUE TITLE
Fee reimbursement for trade SYM0NEKA

### ISSUE THREAD

**Issue by spx4000** [bisq-network/support#390]
![image](https://user-images.githubusercontent.com/64005249/79734044-be0c4280-82fe-11ea-8757-dd81b3a49d08.png)

Maker:  6cce0cb5f29b1ac54f90ca96c034c160abe63fff70b06111c598099f09f8b3de
Taker: 68a29d91b66b904a0958771276edbc575adaa1fef991ba8e7976ba7dcdaf0b0e
Deposit: 

Bisq version: 1.3.1  (donation address error fixed for 1.3.2)

Other notes:
I was the taker in this situation and paid fees in BSQ.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
