### ISSUE TITLE
Fee reimbursement for trade hvpcfuy

### ISSUE THREAD

**Issue by epbtc** [bisq-network/support#395]
![image](https://user-images.githubusercontent.com/64215112/80121574-c5488000-858c-11ea-9472-816ba6b78ba6.png)

Maker: 129031e5db59b603aebb952c878b5e86e8ac383af1166f5ecae4ac411f90f812
Taker: a6b51a82255eed0ef51e7d136c697281cb7753f030dc3c34752764246d2420ad
Deposit: n/a

Bisq version: 1.3.2

Other notes: It's in failed trade tab. ctr+y command does not work and display error message : deposit transaction null.
That was my 4th try.
First was 140259 #392
Second was 624515 #393
Third was 762477 #394

**Comment by epbtc** [comment]
![image](https://user-images.githubusercontent.com/64215112/80122791-4d7b5500-858e-11ea-8814-2b8c393a91e0.png)

here is the error message I got for all 4 failed trades (https://github.com/bisq-network/support/issues/392, https://github.com/bisq-network/support/issues/393, https://github.com/bisq-network/support/issues/394, https://github.com/bisq-network/support/issues/395).

Have done the SPV resync right from failed trade 392.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
