### ISSUE TITLE
Fee reimbursement for trade giio5op

### ISSUE THREAD

**Issue by BisqTor** [bisq-network/support#396]
![](https://user-images.githubusercontent.com/64381948/80320673-32a71b80-87ee-11ea-82eb-38a1d568a259.jpg)
Trade ID: giio5op
Maker: 4fc440a091291fd6ab57af89df0481b2d70ef1b8d7e2ce340cc58e97e4b99821
Taker: 3bcd8733a967d26b16642fa8eeafd700ade80975f8dfdaae60c24bc03caf3071
Deposit tx id: 49b2767538914b62b4eb16ae9bd9bcc00fa2a1a4bedfe48a1dc22882eae420f

Deposit: 0.006

Bisq version: 1.3.2

**Comment by BisqTor** [comment]
How long i should wait?

**Comment by BisqTor** [comment]
Hey, any update? Still no  reimburse.

**Comment by BisqTor** [comment]
Still waiting

**Comment by leo816** [comment]
hi, thank you for your patience, I have taken over the role and your reimbursement will be made this cycle.

**Comment by leo816** [comment]
please post your btc address where you would like to be reimbursed

**Comment by leo816** [comment]
something is not right about this trade. Is not being processed. @KanoczTomas when you could please take a look

**Comment by TorBisqTor** [comment]
Hey, 5 months since this trade.
And STILL no return.
Did I lost my funds?
Where are my funds?
Please help me, i need it.

**Comment by BisqTor** [comment]
@leo816 
I am unemployed, i need my money back.
This is a lot for me.
How can i be sure Bisq stole my money or not?
Please, fix it.

**Comment by leo816** [comment]
> please post your btc address where you would like to be reimbursed

@BisqTor

**Comment by BisqTor** [comment]
1NQPnVxYmsA3sxHC23rjbHS3hta65xc4FA

**Comment by BisqTor** [comment]
@leo816 
1NQPnVxYmsA3sxHC23rjbHS3hta65xc4FA

**Comment by BisqTor** [comment]
@leo816 
Any feedback?

**Comment by BisqTor** [comment]
@leo816 
I posted the address and deleted.
Did you saved?

**Comment by leo816** [comment]
no, please re-post it and the reimbursement will be made near the end of the cycle

**Comment by BisqTor** [comment]
@leo816 

1NQPnVxYmsA3sxHC23rjbHS3hta65xc4FA

**Comment by BisqTor** [comment]
@leo816 
Ok, sir.
When is the end of the cycle?

**Comment by leo816** [comment]
We are now on the next cycle. we are facing some issues and the payout will be made asap.

**Comment by BisqTor** [comment]
@leo816
I hope so, please don`t forget.
I need my money back before christmas.
I am unemployed because this pandemic.

**Comment by BisqTor** [comment]
@leo816 

I've been waiting for my money back for 239 days.
I always indicated Bisq to everyone, but now I started to suspect whether or not there is bad faith in Bisq.

Please tell me a date.

**Comment by leo816** [comment]
All Reimbursements have been made every cycle since I took over. On this last one we’ve had an issue and relied on the previous role holder to take care of this but everything is still the same. I will make the payout manually in the next 24 hrs. Thank you for your patience

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833

**Comment by BisqTor** [comment]
Fee NOT reimbursement for trade giio5op

Are you kidding me??? 
I waited 8 months to get my money back and BISQ returns 10% of what I had? Then that's it? Is that BISQ? Stealing money?
@leo816 paid me 0.0007 btc and closed the issue?
My security deposit was 0.006 btc.
Where are my money? On @leo816 wallet or in any Bisq wallet?

If you don't want to be robbed, don't use BISQ?

Link of my issue:
https://github.com/bisq-network/support/issues/396
