### ISSUE TITLE
Request reimbursement for trade 94885

### ISSUE THREAD

**Issue by joergsen** [bisq-network/support#398]
In this trade, obviously due to a bug, everything went wrong. My money was traceably wired to the seller. But the seller never got back to me. The mediator (leo) decided in my favour. During the following arbitration phase, obviously something went wrong. 
Fact is: I lost the trading amount and the deposit. Therefore this request for reimbursement.

"id": "94885-ff49c3a8-1a7f-4dae-94b7-c904d0ad9870-124",
"tradeAmount": 6500000,
"buyerSecurityDeposit": 750000,

**Desired amount to be paid out: 921 BSQ**

Calculation:
0.0725 / 0.00007889 = **919** 
(cycle 13->  https://github.com/bisq-network/compensation/issues/551)
and **2** BSQ fees for the previous request in bisq DAO  (see also issue #371) that was rejected.  (Whatever for?)
= 921 BSQ

**Comment by leo816** [comment]
I approve the request. funds were stuck, unable to get to the donation address.

**Comment by sqrrm** [comment]
@joergsen I rejected it and basically no one else voted on it. It's not due to the claim being a bad claim, just that we didn't have a process and without any verification I can't support the claim. I think this cycle will do you better.

Thanks leo for getting on top of this.
