### ISSUE TITLE
i can't withdraw my btc

### ISSUE THREAD

**Issue by Ringue** [bisq-network/support#400]
when i try to withdraw my btc from bisq to my wallet. I have an error message saying : Warning The address is not correct. Please check the address format.
I check like 20 times and it is matching the address for receiving BTC on my wallet which is samourai wallet. 
Can somebody tell me what i did wrong or if it is a bug?
Thanks a lot for those who have taken the time to read me.

**Comment by Bayernatoor** [comment]
@Ringue  Are you trying to withdraw to a bc1 (bech32) address? Bisq does not support Native Segwit addresses and therefore you cannot send to those. You can only send to addresses starting with a 1 or 3.

**Comment by Ringue** [comment]
yes thank you for your answer. That was the problem ! issue solved!
