### ISSUE TITLE
Fee reimbursement for trade 606887

### ISSUE THREAD

**Issue by no2nicu** [bisq-network/support#402]
Trade ID: 606887 *After accepting the trade and accepting the deposit amount to start the offer an error popped up. (It might have restarted bisq, I don't remember.) But now this trade is sitting under the failed tabs in portfolio, and I lost my deposit since I can't move forward with this trade. Can I please get a refund for my deposit.

 I am running Bisq version 1.3.4 btw. And attaching a link to the screenshot that is showing on my Bisq file.

![bisq_error_606887](https://user-images.githubusercontent.com/61289958/82853861-d3175b00-9ed4-11ea-96aa-cc41fd59da17.JPG)

If you need anything else from me please feel free to ask.
Thank you so much for your time.

**Comment by leo816** [comment]
have you tried clicking cmd + y
or ctrl + y in case you are not using a Mac

**Comment by no2nicu** [comment]
I am getting a warning The trade cannot be completed, Delayed payout
transaction is null.

**Comment by leo816** [comment]
what is the tx id?

**Comment by no2nicu** [comment]
The trade id is 606887 and there was just a mediation started yesterday I
replied with the situation that after the initial deposit the transaction
failed and I have had no access to the transaction ever since. and in my
portfolio the transaction is under the failed section.

**Comment by leo816** [comment]
do you see the onion address of the mediator?

**Comment by pazza83** [comment]
Closing as no additional info provided.
