### ISSUE TITLE
Request reimbursement for trade KWREWOD

### ISSUE THREAD

**Issue by atpblas** [bisq-network/support#403]
>_The KWREWOD part in the issue title are the first characters of the Trade ID before the "-" (dash)._

Bisq version:

1.3.4

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by m52go** [comment]
@atpblas your screenshot is showing both traders' payment details. Please remove them ASAP.

**Comment by leo816** [comment]
maker and taker fee missing
