### ISSUE TITLE
Fee reimbursement for trade 78638

### ISSUE THREAD

**Issue by atpblas** [bisq-network/support#404]
>_The 78638 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

<img width="1177" alt="Captura de pantalla 2020-05-29 a las 20 06 25" src="https://user-images.githubusercontent.com/66116505/83291021-f1889980-a1e7-11ea-85df-95a7019b74e3.png">

Bisq version:

1.3.4

**Comment by m52go** [comment]
@atpblas your screenshot is showing both traders' payment details. Please remove them ASAP.

**Comment by leo816** [comment]
maker and taker fee missing
