### ISSUE TITLE
Fee reimbursement for trade 19886399

### ISSUE THREAD

**Issue by bounhun** [bisq-network/support#405]
![imagen](https://user-images.githubusercontent.com/60184319/83381834-003aa080-a3e2-11ea-9b49-f27b33168600.png)

Maker:  27363ca7733cd944fba70907059e6b05ff6d5ee23b5ee6de1ce361ee931c89d6
Taker: 79e1d82668b93e0e4f691e8e79d5e8eec8b6c970e084f142eebf601134a2816b
Deposit: NULL

Bisq version:

1.3.4

Other notes:

No deposit tx, unfail trade fails after SPV resync.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
