### ISSUE TITLE
Fee reimbursement for trade 57721

### ISSUE THREAD

**Issue by eddie333016** [bisq-network/support#406]
<img width="901" alt="Screen Shot 2020-06-06 at 9 47 23 pm" src="https://user-images.githubusercontent.com/1611760/83943453-9ede5b80-a83f-11ea-9b6f-eda635fe0cce.png">

Maker:  3a05a627dd3255d40be1d29723d595e850bedd23fd550d3b1afb7994ee90d172
Taker: 11acd308f55715ced3a1cb899028f973ac01945f13b1103a2a9343b6bc6b1a66
Deposit: .......... - Not created 

Bisq version: 1.3.4

Other notes:

**Comment by eddie333016** [comment]
Jun.-06 10:21:56.312 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We move the trade with ID '57721-aea574e5-e113-4df0-9926-00604d31d49f-134' to failed trades 
Jun.-06 10:21:56.316 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade 57721-aea574e5-e113-4df0-9926-00604d31d49f-134: entry=AddressEntry{offerId='57721-aea574e5-e113-4df0-9926-00604d31d49f-134', context=MULTI_SIG, address=1MoQZ1NoHw8GZp9SV61Q8GWfsHrz6rZnCe} 
Jun.-06 10:21:56.322 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade 57721-aea574e5-e113-4df0-9926-00604d31d49f-134: entry=AddressEntry{offerId='57721-aea574e5-e113-4df0-9926-00604d31d49f-134', context=TRADE_PAYOUT, address=17zt3YnJjmv9vHqiKtii4tEsjvRLqKgfE4}

**Comment by eddie333016** [comment]
Jun.-05 22:14:57.942 [JavaFX Application Thread] INFO  b.c.o.CreateOfferService: offerId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, 
Jun.-05 22:14:57.943 [JavaFX Application Thread] INFO  b.c.o.CreateOfferService: 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 AUD SELL 144978141 true 0.033 6250000 6250000 0.15 5016a006-daef-48aa-a51c-0cdc5368864c 
Jun.-05 22:15:09.057 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address 1MoQZ1NoHw8GZp9SV61Q8GWfsHrz6rZnCe and offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 from context OFFER_FUNDING to available 
Jun.-05 23:24:10.688 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from ns2u5jt3d6c4m45p.onion:9999 with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid a6771ac3-05f8-4ed3-9a2a-5c37f2699150 
Jun.-05 23:24:10.986 [JavaFX Application Thread] INFO  b.c.offer.Offer: Price at take-offer time: id=57721, currency=AUD, takersPrice=143223281, makersPrice=143223281, deviation=0.0% 
Jun.-05 23:24:10.986 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid f7978abf-e893-4d0a-b64e-bab88eb8922a to peer ns2u5jt3d6c4m45p.onion:9999 
Jun.-05 23:24:10.988 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer ns2u5jt3d6c4m45p.onion:9999 with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and sourceUid a6771ac3-05f8-4ed3-9a2a-5c37f2699150 
Jun.-05 23:24:11.011 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134; uid=f7978abf-e893-4d0a-b64e-bab88eb8922a 
Jun.-05 23:24:14.650 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityResponse with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid f7978abf-e893-4d0a-b64e-bab88eb8922a 
Jun.-05 23:24:23.160 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: AckMessage for OfferAvailabilityRequest arrived at takersNodeAddress ns2u5jt3d6c4m45p.onion:9999. offerId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, sourceUid=a6771ac3-05f8-4ed3-9a2a-5c37f2699150 
Jun.-05 23:24:53.166 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received OfferAvailabilityRequest from ns2u5jt3d6c4m45p.onion:9999 with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid 1fc58534-bd23-424a-b764-e3d820919007 
Jun.-05 23:24:53.313 [JavaFX Application Thread] INFO  b.c.offer.Offer: Price at take-offer time: id=57721, currency=AUD, takersPrice=143223384, makersPrice=143223281, deviation=7.191568247577607E-5% 
Jun.-05 23:24:53.314 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send OfferAvailabilityResponse with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid fec753b2-07af-42de-a110-11107379c216 to peer ns2u5jt3d6c4m45p.onion:9999 
Jun.-05 23:24:53.315 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Send AckMessage for OfferAvailabilityRequest to peer ns2u5jt3d6c4m45p.onion:9999 with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and sourceUid 1fc58534-bd23-424a-b764-e3d820919007 
Jun.-05 23:24:53.317 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: OfferAvailabilityResponse arrived at peer: offerId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134; uid=fec753b2-07af-42de-a110-11107379c216 
Jun.-05 23:25:13.368 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: AckMessage for OfferAvailabilityRequest arrived at takersNodeAddress ns2u5jt3d6c4m45p.onion:9999. offerId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, sourceUid=1fc58534-bd23-424a-b764-e3d820919007 
Jun.-05 23:25:43.185 [JavaFX Application Thread] INFO  b.c.o.OpenOfferManager: Received AckMessage for OfferAvailabilityResponse with offerId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid fec753b2-07af-42de-a110-11107379c216 
Jun.-05 23:25:43.195 [JavaFX Application Thread] INFO  b.c.t.TradeManager: Received PayDepositRequest from ns2u5jt3d6c4m45p.onion:9999 with tradeId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid ab0bf593-1631-43f5-b9c9-dabef09b3006 
Jun.-05 23:25:43.197 [JavaFX Application Thread] INFO  b.c.n.a.TradeEvents: We got a new trade. id=57721-aea574e5-e113-4df0-9926-00604d31d49f-134 
Jun.-05 23:25:43.198 [JavaFX Application Thread] INFO  b.c.offer.Offer: Price at take-offer time: id=57721, currency=AUD, takersPrice=143223281, makersPrice=143223384, deviation=7.191563076158758E-5% 
Jun.-05 23:25:43.224 [JavaFX Application Thread] INFO  b.c.trade.Trade: Set new state at SellerAsMakerTrade (id=57721): MAKER_SENT_PUBLISH_DEPOSIT_TX_REQUEST 
Jun.-05 23:25:43.225 [JavaFX Application Thread] INFO  b.c.n.a.MyOfferTakenEvents: We got a offer removed. id=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, state=RESERVED 
Jun.-05 23:25:43.225 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: Send message: 'Your offer with ID 57721 was taken' 
Jun.-05 23:25:43.225 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: sendMessage message=MobileMessage(sentDate=1591363543225, txId=57721, title=Your offer was taken, message=Your offer with ID 57721 was taken, mobileMessageType=OFFER, type=OFFER, actionRequired=, version=1) 
Jun.-05 23:25:43.225 [JavaFX Application Thread] INFO  b.c.n.MobileNotificationService: json {"sentDate":1591363543225,"txId":"57721","title":"Your offer was taken","message":"Your offer with ID 57721 was taken","type":"OFFER","actionRequired":"","version":1} 
Jun.-05 23:25:43.230 [JavaFX Application Thread] INFO  b.c.t.p.t.m.MakerSendsInputsForDepositTxResponse: Send InputsForDepositTxResponse to peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, uid=29bc9599-a834-438f-8138-d87737d3b31f 
Jun.-05 23:25:43.315 [JavaFX Application Thread] INFO  b.c.t.p.t.m.MakerSendsInputsForDepositTxResponse: InputsForDepositTxResponse arrived at peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, uid=29bc9599-a834-438f-8138-d87737d3b31f 
Jun.-05 23:25:43.315 [JavaFX Application Thread] INFO  b.c.trade.Trade: Set new state at SellerAsMakerTrade (id=57721): MAKER_SAW_ARRIVED_PUBLISH_DEPOSIT_TX_REQUEST 
Jun.-05 23:25:43.315 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: Send AckMessage for InputsForDepositTxRequest to peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, sourceUid=ab0bf593-1631-43f5-b9c9-dabef09b3006 
Jun.-05 23:25:43.318 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: AckMessage for InputsForDepositTxRequest arrived at peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, sourceUid=ab0bf593-1631-43f5-b9c9-dabef09b3006 
Jun.-05 23:32:13.198 [JavaFX Application Thread] INFO  b.c.t.p.SellerAsMakerProtocol: Received DepositTxMessage from ns2u5jt3d6c4m45p.onion:9999 with tradeId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid 3a00b98e-6d16-4d7a-a8b8-3e15e26d1d49 
Jun.-05 23:32:13.200 [JavaFX Application Thread] INFO  b.c.t.p.t.s.SellerSendDelayedPayoutTxSignatureRequest: Send DelayedPayoutTxSignatureRequest to peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, uid=667dc4b9-522e-4613-a7d5-ab5bc8b726e8 
Jun.-05 23:32:13.209 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: Received AckMessage for InputsForDepositTxResponse from ns2u5jt3d6c4m45p.onion:9999 with tradeId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid null 
Jun.-05 23:32:13.210 [JavaFX Application Thread] INFO  b.c.t.p.t.s.SellerSendDelayedPayoutTxSignatureRequest: DelayedPayoutTxSignatureRequest arrived at peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, uid=667dc4b9-522e-4613-a7d5-ab5bc8b726e8 
Jun.-05 23:32:13.210 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: Send AckMessage for DepositTxMessage to peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, sourceUid= 
Jun.-05 23:32:23.167 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: AckMessage for DepositTxMessage arrived at peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, sourceUid= 
Jun.-06 00:08:53.178 [JavaFX Application Thread] INFO  b.c.s.t.TraderChatManager: Received ChatMessage with tradeId 57721-aea574e5-e113-4df0-9926-00604d31d49f-134 and uid c17c4853-78fc-40d9-a014-f812981e463a 
Jun.-06 00:08:53.179 [JavaFX Application Thread] INFO  b.c.s.SupportManager: Send AckMessage for ChatMessage to peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, uid=c17c4853-78fc-40d9-a014-f812981e463a 
Jun.-06 00:09:10.263 [JavaFX Application Thread] INFO  b.c.s.SupportManager: AckMessage for ChatMessage stored in mailbox for peer ns2u5jt3d6c4m45p.onion:9999. tradeId=57721-aea574e5-e113-4df0-9926-00604d31d49f-134, uid=c17c4853-78fc-40d9-a014-f812981e463a

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774

**Comment by eddie333016** [comment]
@leo816  THanks for this but how do I see the reimbursement it doesnt seem to show up in my BSQ transactions?

**Comment by leo816** [comment]
you will receive it as btc, it is the only way we reimburse fees

**Comment by eddie333016** [comment]
> you will receive it as btc, it is the only way we reimburse fees

@leo816 ok thank you - How do I find out how much the reimbursement is and how do I find it in the transaction record I can't see a reference too it anywhere in my BISQ client.
