### ISSUE TITLE
Fee reimbursement for trade 57721

### ISSUE THREAD

**Issue by Conza88** [bisq-network/support#407]
![image](https://user-images.githubusercontent.com/51952482/83957925-71c99180-a8af-11ea-9284-5ae3b95ac3cb.png)

Maker:  3a05a627dd3255d40be1d29723d595e850bedd23fd550d3b1afb7994ee90d172
Taker: 11acd308f55715ced3a1cb899028f973ac01945f13b1103a2a9343b6bc6b1a66
Deposit: .......... not created.

Bisq version: 1.3.4

Took trade, 'hung as accepting for ages'. Then got the following when logging back in.

![image](https://user-images.githubusercontent.com/51952482/83958277-2d3ff500-a8b3-11ea-8237-93ba96882913.png)

Was not able to salvage trade. Had engaged #support straight away and weren't able to help.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the funds

**Comment by Conza88** [comment]
Thanks, I do that here?

**Comment by leo816** [comment]
You can write it down here

**Comment by Conza88** [comment]
PM'd via keybase.
