### ISSUE TITLE
Fee reimbursement for trade YnGjojg

### ISSUE THREAD

**Issue by Conza88** [bisq-network/support#408]
![image](https://user-images.githubusercontent.com/51952482/83958348-d71f8180-a8b3-11ea-9254-78c13b14d5ca.png)

Maker:  a06623159a56afc6221a5caf49a9825240501915e13e89dd2490b1c581e7c5a8
Taker: 589b632ebaae8c5d64cec608e1f69f5fa426927888ac010d25bca1d7a465885c
Deposit: .......... not created.

Bisq version: 1.3.4 I believe.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
