### ISSUE TITLE
Fee reimbursement for trade 31578971

### ISSUE THREAD

**Issue by Conza88** [bisq-network/support#409]
![image](https://user-images.githubusercontent.com/51952482/83958465-7a24cb00-a8b5-11ea-8a66-3bf825851028.png)

Maker:  0229b1d58d1c95647de05ea19e6c156e2635fbd4e0f89f76e14198af29af6c91
Taker: 4ab9a40eabdb523b5da1701b84dcf49de11d87f3c731980ae5710e6aef7b6205
Deposit: .......... not created

"An error occurred at task: BuyerAsTakerSignAndPublishDepositTx
Exception message: addressEntryOptional must be present"

Bisq version: 1.2.4 maybe? :\ 

Only just figured I can get reimbursed now. Apologies for delay.

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
