### ISSUE TITLE
Fee reimbursement for trade dSWNbJq

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#411]
![image](https://user-images.githubusercontent.com/57514423/84101474-a6cf0480-a9d3-11ea-8800-360cefe51a3d.png)

Maker:  d6b02755336984a73ca1c2ace53c362e20affaf4d1a9f8c5cf3de8a22a21ac89
Taker: 7bfbacaa7728aa80f083918ab03711c715a5147366c54cea08116f343501f8e4
Deposit: ..........

Bisq version: v1.3.4

A timeout occurred.
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
