### ISSUE TITLE
Fee reimbursement for trade lenutx

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#417]
![image](https://user-images.githubusercontent.com/57514423/84102357-da129300-a9d5-11ea-8ca3-5bd4c45dfc80.png)

Maker:  80988817697b6406e73fcfca64406779421571a9f9970ed5e6e6887b19b8b083
Taker: eb57d868340f61cc2f2f7cb900cce6a1037d803749cc14aee1ddec28c548e247
Deposit: ..........

v1.3.4

A timeout occurred.
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by leo816** [comment]
something is clearly wrong with your bisq account, no one has this many invalid transactions

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
