### ISSUE TITLE
Fee reimbursement for trade TMYNIU

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#418]
![image](https://user-images.githubusercontent.com/57514423/84102432-0d552200-a9d6-11ea-979a-4275431b5243.png)

Maker:  39d52f46d9d05359545981efb52fd1cc68ad038728da08aefcc5fd5e4b80bd1f
Taker: eebe6ff5172207ae3081a961696655eda4a13cf1a22be7883a067ac1f59b4892
Deposit: ..........

v1.3.4

A timeout occurred.
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
