### ISSUE TITLE
Fee reimbursement for trade oclykfa

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#419]
![image](https://user-images.githubusercontent.com/57514423/84102592-85bbe300-a9d6-11ea-9859-06c3a3d6fc72.png)

Maker:  a0ffab81e8f97da2a9733f753f54440eaa8eb675fc9781261d407cdc58b39a1f
Taker: 33306917c38aa97dd68199bc20ef89f017a210e41fadfd6025551bf48daa88eb
Deposit: ..........

v1.3.4

A timeout occurred.
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
