### ISSUE TITLE
Fee reimbursement for trade abzphlpw

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#42]
This issue has been created per the process detailed in bisq-network/support#35 to track the reimbursement of trading and mining fees lost due to the 'failed transaction broadcast' problem being tracked at bisq-network/exchange#1193 and under investigation at bisq-network/exchange#1195.

If the trade ID in the title of this issue is yours, then please click the `Subscribe` button in the right menu of this issue to be notified about the status of your reimbursement.

If you do not see a `Subscribe` button, then you are not logged in to GitHub. Please log in or create an account if necessary. You'll then be able to `Subscribe` to this issue and you will get updates by email.

**Comment by meapistol** [comment]
![image](https://user-images.githubusercontent.com/10008813/35152793-dfbbf8d2-fd34-11e7-9d22-555ed1d05aa5.png)
Maker: 7f49903972e18e202db8f8a2c86975162bf402d60b8851dbfff6a1c7c47a05d8
Taker: 30efbb4281fe914b92bcf4439c95dddbbafe921b35e4a940e1a0c2300f5eb9a2
Deposit: 9f488029df29c998fba435da96c050e006262c920ff3ec5ea71b5172eb30e4c5

**Comment by cbeams** [comment]
_The following information was provided to me by @keo-bisq via email:_

![35152793-dfbbf8d2-fd34-11e7-9d22-555ed1d05aa5](https://user-images.githubusercontent.com/301810/35283605-00b2de1c-0059-11e8-8613-5d617441e628.png)

Maker: 7f49903972e18e202db8f8a2c86975162bf402d60b8851dbfff6a1c7c47a05d8
Taker: 30efbb4281fe914b92bcf4439c95dddbbafe921b35e4a940e1a0c2300f5eb9a2
Deposit: 9f488029df29c998fba435da96c050e006262c920ff3ec5ea71b5172eb30e4c5

I have just double-checked, and indeed only the Maker fee has been confirmed. The other two transactions were never broadcast.

**Comment by cbeams** [comment]
Staged for reimbursement in 070fa1b

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/35#issuecomment-362038006.
