### ISSUE TITLE
Fee reimbursement for trade PCFSX

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#421]
![image](https://user-images.githubusercontent.com/57514423/84103421-94a39500-a9d8-11ea-958a-95725aa06f4c.png)

Maker:  380c4f2d17f561cc9b337d8aa02738c79ffbd5497be68b03551ed240a3041194
Taker: 7857e69fa378412886843fa9257eec0a3366fe03301e4921e29c471c9e4269b9
Deposit: ..........
 
v1.3.4

A timeout occurred.
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
