### ISSUE TITLE
Fee reimbursement for trade QRBKHEI

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#422]
![image](https://user-images.githubusercontent.com/57514423/84103523-e6e4b600-a9d8-11ea-8476-0a4e812e688b.png)

Maker:  9445ca3055ac412568030bf18125b48e99190956c7309593308090af2a76ac72
Taker: b41700a8b69789434f77dba492f8842f5c005567081bf846c44c466e353b8992
Deposit: ..........

v.1.3.4

Deposit transaction not available

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
