### ISSUE TITLE
Fee reimbursement for trade mUySGQ

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#424]
![image](https://user-images.githubusercontent.com/57514423/84105509-26fa6780-a9de-11ea-8a5e-be357b70f7ae.png)

Maker:  e65a143ada63db9c3af7ff7ffbac2596814be592e3c892c90e02684816d9477e
Taker: c851276aef5f9a0c588f1fa175a457c583598c8ffaac74f9baee8004ec1a28d6
Deposit: ..........

v1.3.4

A timeout occurred.
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
