### ISSUE TITLE
Fee reimbursement for trade WiMWGAtF

### ISSUE THREAD

**Issue by maurobeltran** [bisq-network/support#426]
![image](https://user-images.githubusercontent.com/57514423/84105876-3e862000-a9df-11ea-84bf-de442f4b3b9f.png)

Maker:  a9e2e7f4ba6c5fe95ac3c4d33431d864180e842978f0d36463fef78d01c55e56
Taker: 48cbaf9cb766d8cc6bc7c1af5b16b45eb6c7abd725e6bd177a06c942b1298296
Deposit: ..........

V.1.3.4

An error occurred at task: SellerSignAndFinalizePayoutTx
Exception: java.lang.NullPointerException
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
