### ISSUE TITLE
Fee reimbursement for trade XsbvUAe

### ISSUE THREAD

**Issue by PatVers** [bisq-network/support#429]
![image](https://user-images.githubusercontent.com/66955857/84807362-072afb00-afff-11ea-965f-dfd5fceb791f.png)

Maker: b9a3ee73522f0cb95ec52aad820426c5c36bc89ec56f78335fcde2f3927f8129
Taker: 0d376ff4b1d78cc2932dd3bff3d544640767da98b820ad68e833af6db0a0f657
Deposit: .....

Bisq version:

1.3.4

**Comment by leo816** [comment]
Will be reimbursed with #430

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/430#issuecomment-660882774
