### ISSUE TITLE
Blocked at "Wait for blockchain confirmation"

### ISSUE THREAD

**Issue by fabio552** [bisq-network/support#433]
![transaction error](https://user-images.githubusercontent.com/67288938/85327466-e5ca8300-b4c6-11ea-8be8-5766cf194264.png)
My transaction got stuck at "Wait for blockchain confirmation"

Make fee transaction ID: 468294914d908fe0439fc6cbf2827e6ebb30977830a31a97d8ae5e92704a57cf
Taker fee transaction ID: 6e9a55c9c743504346daa29cc8c74c3cd4c5235cb6f804af25b9066d28ebc86c
Deposit Transaction ID: 6c0a24cd2fbb3675f8040311760a0a138a8549ead36ec3bd4e3f7642fa441a27 (it's not confirming)

The money are locked and I can't do anything from my end.

**Comment by MwithM** [comment]
According to www.mempool.space it will be confirmed i one hour. It's just an estimation, but I think it will confirmed soon.
I think there's a way to make it faster, but seeing the mempool, it's better to just wait.

**Comment by fabio552** [comment]
Ok. I will. Thank you very much for your input.

**Comment by fabio552** [comment]
It's not confirmed even now. And it's been 5 hours already. What can I do?

**Comment by fabio552** [comment]
It's all ok now. Thank you
