### ISSUE TITLE
Fee reimbursement for trade 95359483

### ISSUE THREAD

**Issue by ncstdc** [bisq-network/support#434]
95359483-d15918fa-b87f-469d-813e-659719a2d445-113
![](https://user-images.githubusercontent.com/2712736/84809489-bc45bf00-afcf-11ea-8d24-56de5a65b3f3.jpg)
Maker: f34080a68a026c57672bdb181c6a3e025a2d0cb379494cd3ea8bac14ff198772
Taker: 3e5b4a9b1f5c761f3bb9312317a74369dcbcd5bacb02aea2f87a86bf6407994d
Deposit: b6a570e4fc42a1f4dbe1b43163ca4a738b1f1781e035217a23a239a799300df7
Summary: The deposit transaction has not been created because of a bug. No funds have left your wallet even if the UI shows that. After the dispute is closed you should have all your funds as expected. You can ask for reimbursement for the lost trade fee aTaker: https://github.com/bisq-network/support/issues/

**Comment by leo816** [comment]
payout was made correctly here
