### ISSUE TITLE
Fee reimbursement for trade lxFhS

### ISSUE THREAD

**Issue by PatVers** [bisq-network/support#438]
![Captura de pantalla 2020-07-04 a las 22 14 30](https://user-images.githubusercontent.com/66955857/86521069-caa33000-be43-11ea-9e35-da66f9d8d18b.png)

Maker:  064e82d2fcffe32ec420443337808fb4e9f2852e0e9f203663b7e55d28355c51
Taker: 186844616a8b03391a83af109070d0df586106748a19414651f91ed8feed6461
Deposit: ..........

Bisq version:

1.3.5

Other notes:

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
