### ISSUE TITLE
Fee reimbursement for trade jfhow due a bug

### ISSUE THREAD

**Issue by roundrobin42** [bisq-network/support#440]
![bisq-trade-2](https://user-images.githubusercontent.com/68111827/89729511-b94ad600-da36-11ea-9a7c-f8154c7f9460.png)

Maker:  c297c81f6b62f11938a7c5c2bb1b854648a43e4c65abe4c9ddb2e71c4d435a25
Taker: 1b16db80eab431e960d488d4ca768e314dadbd697b53911eab55bb27e2c86891
Deposit: d4003d40c944d0f35b022b2a03664ffbeb1aebdd56854427fc871c0e082d0388 

Bisq version:

1.3.5

IMPORTANT NOTES:

I am the taker.

I have payed a big tx fee due a bug already fixed (https://github.com/bisq-network/bisq/pull/4354)

Bisq client used a wrong output adress (of Taker transaction) to create the deposit transaction, in consecuence It payed a wrong and big tx fee.

I have lost 0.08823538 BTC (= 0.12581138 − 0.03757600).

I ask for 1379.97 BSQ  (using 30 days average BSQ/BTC price 0.00006394)

**Reimbursement request TXID**: 2dbe2871a0744834808233c104f649caafa5489dbbbfdea7af330d22db008227

UPDATES:
**I have replaced the screenshot by another including the Taker info**

I have resubmitted another reimbursement request

**Comment by MwithM** [comment]
I see that this has been asked as a DAO reimbursement request. It should have the TXID posted here, to avoid confusions.

**Comment by ripcurlx** [comment]
@leo816 Could you please confirm that this reimbursement request is legit so it could be accepted or rejected? Thanks!

**Comment by leo816** [comment]
@roundrobin42 I see there is a clear error with the fee amount, To approve this request I need a screenshot as proof to know if you are the btc seller or the buyer. If you see above the details you should see "Taker as BTC seller"

**Comment by ripcurlx** [comment]
> @roundrobin42 I see there is a clear error with the fee amount, To approve this request I need a screenshot as proof to know if you are the btc seller or the buyer. If you see above the details you should see "Taker as BTC seller"

@roundrobin42 As the voting is already taking place and this fee reimbursement request is not approved yet by the team lead (@leo816) I fear you'll need to apply for reimbursement again for next cycle.

**Comment by roundrobin42** [comment]
> @roundrobin42 I see there is a clear error with the fee amount, To approve this request I need a screenshot as proof to know if you are the btc seller or the buyer. If you see above the details you should see "Taker as BTC seller"

Hi @leo816 the reimbursement request has been declined because the screenshot isn't complete? I think we need include this precision into template because is missing (the screenshot of https://github.com/bisq-network/support/issues/197 has not taker or maker info).

**Comment by roundrobin42** [comment]
Can I have a response to know how to do to be compensated?

**Comment by leo816** [comment]
that is correct, thank you for adding all the info

**Comment by roundrobin42** [comment]
I have submitted the request again

**Comment by roundrobin42** [comment]
I close the issue because Compensation request has been accepted
