### ISSUE TITLE
Fee reimbursement for trade ZyilENaJ

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#441]
![ZyilENaJ](https://user-images.githubusercontent.com/45833017/64481987-a3aaac00-d1e8-11e9-9ccb-7c8e12796756.png)

Maker:  ce4e2446adc121bb6653ad2316f897babb24b1b767beea0d39e3a75530ae9e9a
Taker: 194aa1efd2aa86df1de424b626308f2cdd8d68ccf5751a36ceddd0bfd22c25b4
Deposit: 5942b7c91de894c045061629490d7a765caf4812ca5ba8cb60a5583be8a77c14

Bisq version: 1.1.4

Other notes: Part of BSQ Fee reimbursement proposal #368, split in separate issues at the request of @leo816

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
