### ISSUE TITLE
Fee reimbursement for trade GJJVSXE

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#443]
![GJJVSXE](https://user-images.githubusercontent.com/45833017/64482090-0dc45080-d1eb-11e9-8ff1-4305b045ab18.png)

Maker: 7a85bae2fae5ea9f933cf8d8d887cda7bd4a169678172306a927d29150dd17a4
Taker: fb0e6331d5bacf52591e6464c990b6302a17cf4e6c6f37e3655dd6faf2d57b71
Deposit: 6fec29823083cec5fc3e1876abfc410209dadddd389685a62eec7ed43de5fe61

Bisq version: 1.1.4

Other notes: Part of BSQ Fee reimbursement proposal #368, split in separate issues at the request of @leo816

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
