### ISSUE TITLE
Fee reimbursement for trade CADUMWWE

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#445]
![CADUMWWE](https://user-images.githubusercontent.com/45833017/64482092-19177c00-d1eb-11e9-8e68-4584fbd0845e.png)

Maker: b75a79d798a945d74d9c80d36da5cc3ea062c7c74c2ac1a638e382c50c5adee3
Taker: 1b126c8edac2b869a6e1f1037cde778ccdbfae8f6e1539fcae4484ee0ce56da6
Deposit: 1ce11b50218238e747f72be8a85810663c861459acfa7f677da0a4364515d30b

Bisq version: 1.1.4

Other notes: Part of BSQ Fee reimbursement proposal #368, split in separate issues at the request of @leo816

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
