### ISSUE TITLE
Fee reimbursement for trade goloxks

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#446]
![goloxks](https://user-images.githubusercontent.com/45833017/64482093-1ddc3000-d1eb-11e9-902d-60e753c00f05.png)

Maker: b6d5eafb3980ced80aa317a443ab740e787933f7b6a634ba932f1ad842b20a86
Taker: 88e1689cd36092201474fe654fc3e4494054b884d2b5267620e702a48ef6cdea
Deposit: 6b062b6f624db5f1c6542380f6ec8ab0312998bbf8af92a2661524921f7c9fb5

Bisq version: 1.1.4

Other notes: Part of BSQ Fee reimbursement proposal #368, split in separate issues at the request of @leo816

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
