### ISSUE TITLE
Fee reimbursement for trade KFNVP

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#451]
![KFNVP](https://user-images.githubusercontent.com/45833017/64482103-377d7780-d1eb-11e9-82b6-7a3dcf0dea4a.png)
![KFNVP-2](https://user-images.githubusercontent.com/45833017/64482104-3b10fe80-d1eb-11e9-8163-a7cb912fa92a.png)

Maker: 888e1a190c04aed7b59c3417ae0741e147047a0ec1a0a5d9ae4ce54a47d9190b
Taker: c01b583ab5401ac0fcc7c007ab3a8d9eddcab41a717c2815475628549743849a
Deposit: 82786cf96c22b984c3680651128aeff6a1f90aae1414084796ebee8f3e3864a8

Bisq version: 1.1.4

Other notes: Part of BSQ Fee reimbursement proposal #368, split in separate issues at the request of @leo816

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
