### ISSUE TITLE
Fee reimbursement for trade MTYoEN

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#452]
![MTYoEN](https://user-images.githubusercontent.com/45833017/64482105-4106df80-d1eb-11e9-8af3-f496e6fab2a7.png)
![MTYoEN-2](https://user-images.githubusercontent.com/45833017/64482108-449a6680-d1eb-11e9-8950-508db8f4c3ed.png)

Maker: b452e31a5afaa372621d08267619e858701b4fa6a22343dea35c8fc7461a2227
Taker: 9eeb7529602e424456a2b42c2976969e38b6b18c5b05998549e62a03b444bbfa
Deposit: 170d3ca1cf0d9573f48b24ba33ab12db4848644db871d874d3bf53abc426116b

Bisq version: 1.1.4

Other notes: Part of BSQ Fee reimbursement proposal #368, split in separate issues at the request of @leo816

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
