### ISSUE TITLE
Fee reimbursement for trade QCkgUE

### ISSUE THREAD

**Issue by invertedbobb** [bisq-network/support#454]
![QCkgUE](https://user-images.githubusercontent.com/45833017/64482112-50862880-d1eb-11e9-950b-0998cf8ad447.png)

Maker: 70aa4804019154431f2f3d6f1d73c0eeabae1eb5a968d0c67b2c01598f8be343
Taker: 490d3b9e5f34cc83bac363a1d7169f6d902ed245f4b44a8e25df11361e729bfb
Deposit: 068e00724bc0d207ce51f82c5b4c07471aeb59ee55e056be7f6875215c038567

Bisq version: 1.1.4

Other notes: Part of BSQ Fee reimbursement proposal #368, split in separate issues at the request of @leo816

**Comment by leo816** [comment]
payout made
