### ISSUE TITLE
Fee reimbursement for trade KAKSAMD

### ISSUE THREAD

**Issue by PatVers** [bisq-network/support#456]
![Captura de pantalla 2020-07-14 a las 20 54 38](https://user-images.githubusercontent.com/66955857/87470307-7d2d7c80-c614-11ea-8309-f6f881e7b750.png)

Maker: 68914c1983a6b748b3a1bec1a609f0482b401af32d9d0cf9dcc8058ce36f39e0
Taker: d90c4a22a501c6c8c83a9be7cec3ef3c23eb400b2a62ad92cd9df7eea9a94184
Deposit: .............

Bisq version:

1.3.6

Other notes:

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
