### ISSUE TITLE
Fee reimbursement for trade AkqlsC

### ISSUE THREAD

**Issue by jenechka1** [bisq-network/support#457]
![Screen Shot 2020-07-15 at 1 32 39 PM](https://user-images.githubusercontent.com/35736319/87577419-e0fd8700-c6a0-11ea-8753-0319ed1b3bb8.png)

Maker: 507482966e51199bac26139df7405522e767d55da7efb07e0f2d03639708d34a
Taker: 6ef8e6f1d63a69bd61ddaae25705fdb8db61c3cf6837f6a4cff65faecad4e0f6
Deposit: ..........

Bisq version: 1.3.5

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
