### ISSUE TITLE
Fee reimbursement for trade 7cqubcj

### ISSUE THREAD

**Issue by Jan877** [bisq-network/support#459]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
<img width="666" alt="7cqubcj" src="https://user-images.githubusercontent.com/44270690/87868675-ac3b4980-c998-11ea-91b4-4563103b69a1.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Trade ID: 7cqubcj
Maker fee transaction ID:  41518ad62e31e132dd04ab9dc58de4d4c2485abe2aee316e47523c0e813619d6
Taker fee transaction ID: 2c5841db09b74c7fcfcb7d3407dbe6d4f64e48a96b26cd623eedf775a8470fe4
Security deposit: Buyer: 0.0180 BTC / Seller: 0.0180 BTC
"buyerSecurityDeposit": 1800000,
"sellerSecurityDeposit": 1800000,

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.3.6

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by Jan877** [comment]
<img width="543" alt="Warning 7cqubcj" src="https://user-images.githubusercontent.com/44270690/87868855-beb68280-c99a-11ea-8dbd-3e166695ff85.png">

**Comment by leo816** [comment]
please erase the faded indications under each section.
