### ISSUE TITLE
Fee reimbursement for trade KWX4G

### ISSUE THREAD

**Issue by Jan877** [bisq-network/support#460]
<img width="960" alt="KWX4G" src="https://user-images.githubusercontent.com/44270690/87868730-616e0180-c999-11ea-921a-967d42a6e3df.png">
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker fee transaction ID:  0b800ef87a393d376d7cf87496bec489dc953c22ab2470a8645c22868a49c0ff
Taker fee transaction ID: de10716aadac15996bfc1cb64b22e2c75bf9727e2695f61932c38548d2d2634e
Deposit:
Security deposit Buyer: 0.014990 BTC
Security deposit Seller: 0.007495 BTC

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please erase the faded indications under each section.

**Comment by leo816** [comment]
provide btc address where you would like your funds to be released

**Comment by pazza83** [comment]
Closing as no additional info provided.
