### ISSUE TITLE
Reimbursement for double refund payout

### ISSUE THREAD

**Issue by RefundAgent** [bisq-network/support#461]
I ask for reimbursement for the 2.14 BTC = 34141.7 BSQ that was paid out twice and explained in https://github.com/bisq-network/roles/issues/93.

I don't think this mistake can simply be attributed to carelessness, but can be attributed to a bug or quirk in the messaging system. If it is approved it will dilute the tokens by about 0.8%. In a system without refund agents mistakes such as this one would be socialised to all stakeholders.

I leave the decision to the stakeholders and will refrain from voting in this matter since I don't know the correct line of reasoning here.

Refund Agent

**Comment by sqrrm** [comment]
There are obvious issues with the accounting going from trade -> mediation -> refund agent -> reimbursement. I think a lot of this could be improved a lot with proper tracking, and verification, of all the steps from trade to reimbursement. Steps that need a human opinion to proceed, basically the mediation, should have that signed and opinion included.

I think this is not a completely unreasonable reimbursement request considering the poor tracking and procedures we have.

**Comment by RefundAgent** [comment]
TxID:  702fd*******d0198

**Comment by wiz** [comment]
With all due respect, I don't see how you can blame the messaging system for accidentally doing a double payout. As a casual observer, I spotted your mistake because it was obviously wrong. As the guy doing the payouts, it is your responsibility to verify all transactions and properly account for them. I am honestly quite surprised you would ask for reimbursement from the DAO for what you admitted was your own mistake.

Additionally, if the DAO approves this proposal, what's to stop the Refund Agent from making more double payouts and getting the DAO to pay him back, either accidentally or intentionally?

**Comment by leo816** [comment]
I agree with Wiz here, I know that mistakes have been made in the past with old arbitrators and they've had to pay it back with their own money. It is also true that they had higher salary. I would say we could find some common ground but 100% reimbursement doesn't seem right in my opinion.

**Comment by Bayernatoor** [comment]
It's an unfortunate situation but I don't believe the DAO should be responsible for a mistake that should have been (in my opinion) easily avoided. No doubt, you provided a necessary (at this time) service to the platform but this is hefty amount and as Wiz mentioned above it could set a dangerous precedent.

**Comment by sqrrm** [comment]
I will accept this request as I think it's an essential task of the DAO. The mistake is part of a bad structure and going forward it looks like we will have to do the reviews and voting through the DAO for each larger refund, an extra cost that we have so far avoided.

If this is not accepted it sends a signal to contributors that they should not assume any personal risk as they can see that the DAO won't be there to support them in bad times. That, to me, sends the wrong signal to contributors in general.

The refund agent has taken on perhaps the least rewarding role with the highest personal risk within the bisq DAO. Who would be interested in continuing this work after a rejection of this request?
