### ISSUE TITLE
Reimbursement and compensation for trade GEOM1

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#462]
Hello. I would like to get my coins and a compensation from the trade partner's deposit for the trade GEOM1. I am the maker and BTC seller of this offer. More than two weeks have passed from the trade, and the trading partner has not sent me the XMR he should have and is unresponsive. I would like to get a refund of my funds and a compensation from the BTC buyer's deposit, as suggested by the mediator. 1.752 BTC by current price 0.00006272 BTC per BSQ makes 27933.67 BSQ total refund.

![grafik](https://user-images.githubusercontent.com/63785272/88193392-e6794500-cc3d-11ea-9346-c4dab4b4c62e.png)

Secret agreed with the arbitrator is "xqwrts".
Thank you

**Comment by wiz** [comment]
I was the mediator for trade GEOM1, and I can confirm the suggested payout to the seller is 1.752 BTC. The funds were donated to Bisq in this TX: https://mempool.space/tx/d38b03240539c5dd7f521432b959d257eab15947aab725cedb53f5bdd273d9cc

@Akira45-0 to verify your identity, I have just sent you a secret hex string using the Bisq in-app support chat, can you please post it here?

As for the current price, the 30 day average is 0.00006272 BTC, I believe you should use that instead.

**Comment by Akira45-0** [comment]
The string is d960b7d01e4697813a08b6ca852a9458.
I have modified the price in concordance with your suggestion.
Thank you.

**Comment by wiz** [comment]
> 1.752 BTC by current price 0.00006272 BTC per BSQ makes 27933.67 BSQ total refund.

Okay, I have verified @Akira45-0 is the seller of trade GEOM1, so I approve this reimbursement request.

**Comment by RefundAgent** [comment]
The secret is correct and I also approve this reimbursement request..

**Comment by ripcurlx** [comment]
@Akira45-0 Could you please post the transaction ID of the reimbursement request, as there are two with your GitHub username and the same reimbursement link:
- `d57c1c3876aba36d62116f347ae7d8c2c11026e66d4941ad04c7e4d8cbe6b301` with the amount of 29200.00 BSQ
- `1d66c2e37bb245e77acb635d6205615f11e6d18a428724f9bc248613756e695e` with the amount of 27933.67 BSQ

I do assume that `d57c1c3876aba36d62116f347ae7d8c2c11026e66d4941ad04c7e4d8cbe6b301` was a mistake or an impersonator so I'll reject this reimbursement request. Please confirm if `1d66c2e37bb245e77acb635d6205615f11e6d18a428724f9bc248613756e695e` is the correct reimbursement request.

**Comment by Akira45-0** [comment]
The 1d66c2e37bb245e77acb635d6205615f11e6d18a428724f9bc248613756e695e with the lower amount is correct. The other transaction was me, but I took the BSQ price from the moment of posting. Wiz suggested to use the 30-day average price, hence the new request with lower amount. I thought I have removed the first request, I don't know why it appears in the DAO.

**Comment by ripcurlx** [comment]
> I thought I have removed the first request, I don't know why it appears in the DAO.

Unfortunately there is a bug with the proposal removal that can't be easily fixed ATM. I just wanted to confirm that this is such a case so not both of your requests get rejected.

**Comment by chimp1984** [comment]
@Akira45-0 

Here again is one of the trade fee txs paid to the trader himself:
https://mempool.space/address/18ZHdui3aNhvbaZuisAFk44RN68QHCcKBC

As that happens with same user as in https://github.com/bisq-network/support/issues/492 I assume you are the scammer here and free-ride Bisq by not paying the trade fee. Greedy bastard!

**Comment by Akira45-0** [comment]
What?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chimp1984** [comment]
> What? ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

Was a mistake. Sorry. Thought we have found the April scammer, but was false positive ;-)
