### ISSUE TITLE
Fee reimbursement for trade vBGFuSbp

### ISSUE THREAD

**Issue by Meta-Realms** [bisq-network/support#463]
**![image](https://user-images.githubusercontent.com/68752567/88434994-a801a700-ce44-11ea-82cc-f959d4fca7d4.png)**

**Maker:  d981110db701aeee0da808fe1912c4205119c17517d8ed4e330f8e348379e0e5
Taker: 234ebfc61cb183ae49c641eac570de62ef9617711b0a875dddd457b616fdf374
Deposit: 599429d0b221260cd53c0374fb77c2aefe925651714669e76c86b3b3a4647179**

**Bisq version: v1.3.5**

Other notes:

**The order failed for some unknown reason. Please reimburse the fees.
Thanks.
Note I'm going to create anew Bisq wallet to be sure this doesn't happen again.**

**Comment by leo816** [comment]
payout was made here
