### ISSUE TITLE
Fee reimbursement for trade O51xo

### ISSUE THREAD

**Issue by Meta-Realms** [bisq-network/support#464]
![image](https://user-images.githubusercontent.com/68752567/88436495-bf8e5f00-ce47-11ea-8487-6a9995cab324.png)

**Maker:  0db54af3bc481e56a2f71fa3b463ad72026aeda0b9de93e9a7047a7859c59fd9
Taker: 94671e806346ee88ed6dafc3fe1f42af969b630966c7eb21c10872aeabfab66b
Deposit: e3531a04915ccca0dff1deb2f62e644894a17ba3fdb9f23bb19623ecfd445618**

**Bisq version: v1.3.5**

Other notes:

**The order failed for some unknown reason. Please reimburse the fees.
Thanks.
Note I'm going to create anew Bisq wallet to be sure this doesn't happen again.**

**Comment by chimp1984** [comment]
NACK

There is no delayed payout tx publsihed:
https://mempool.space/address/38U2EdV8iYRrr781kZTgbhDgppznfoCY6F

Funds are still locked in the deposit tx. You need to open an arbitration case.
