### ISSUE TITLE
Fee reimbursement for trade 12203

### ISSUE THREAD

**Issue by Meta-Realms** [bisq-network/support#465]
![image](https://user-images.githubusercontent.com/68752567/88436893-a1752e80-ce48-11ea-9d3e-195d6e313866.png)

**Maker:  92b3d9a11ed34b9e19e8bb2cde2e40c255864114ddad49946a060efa21faa83b
Taker: 29debf13fc65d792c2035e1008dc2478f471328ef8e1ca5e2804322668f52557
Deposit: 7e8a9c9576b2aaca76400fec8748c91dc6811f3f4ebb57666d5b242e26ceed58**

**Bisq version: v1.3.5**

Other notes:

**The order failed for some unknown reason. Please reimburse the fees.
Thanks.
Note I'm going to create anew Bisq wallet to be sure this doesn't happen again.**

**Comment by chimp1984** [comment]
NACK
The trade has been paid out:
https://mempool.space/address/32t2G6zRCZ22W19A1o8BpnYBDS4shPBzgt
