### ISSUE TITLE
Fee reimbursement for trade XEBTOF2

### ISSUE THREAD

**Issue by Meta-Realms** [bisq-network/support#466]
![image](https://user-images.githubusercontent.com/68752567/88437139-2b24fc00-ce49-11ea-9eb7-390eb716554a.png)

**Maker:  18e8169e33e0a2ad8c77879f34ba261bbce21671ce7861fb9a94b2436c147e06
Taker: 1282615102751e4175c9bd5217f1492120e24ad6b45eee7e048f8af07fccd28c
Deposit: a459d2e8ebbeed638c03ac51ece7edd1e86094601abfb7391fe3cc1fbefc407b**

**Bisq version: v1.3.5**

Other notes:

**The order failed for some unknown reason. Please reimburse the fees.
Thanks.
Note I'm going to create anew Bisq wallet to be sure this doesn't happen again.**

**Comment by chimp1984** [comment]
NACK

The trade got paid out as you can see here:
https://mempool.space/address/3CHnPFmZrRNWppfeY4pMxXXj91RBFeZHYU

You should have received the fund on 1LbTnpZyPisGwu8trziYTU1tD5YVHC6cpj or 1MS2rnA6uHzxvhsjdiSidQXE2Z7aVjXrRu
