### ISSUE TITLE
Some SEPA banks are requiring street and city details to send a transaction

### ISSUE THREAD

**Issue by built2df5** [bisq-network/support#467]
I'm selling to an unsigned account, he requested me on the chat to provide my address and city. I refused encouraged him to open a dispute.
Mediator displayed the proof (image) that this was a real request from the bank, but still feel unfair to have to provide unexpected data. I requested to cancel the trade with a small compensation for fees and time lost, and the funds are still on hold without mediator's suggestion.

In my opinion, it's buyer's fault if his bank decides to implement additional stupid measures. I'm not going to tell the buyer where I live just because he took my offer.

I think my mediator is @leo816 but I opened this issue so you can decide what course of action to take if this happens again.

**Comment by Bisq-knight** [comment]
It wasn't clear from the description, but did you try putting the seller bank's address? As in the one registered with the BIC number?

I've seen cases where that was sufficient. I hope that is the case here too

**Comment by pazza83** [comment]
I agree user sellers bank address if required.

Google seller's BIC number, that will pull up bank details.

Google bank address

Use address for Seller's details.
