### ISSUE TITLE
Fee reimbursement for trade OqbUAF

### ISSUE THREAD

**Issue by nicebug5** [bisq-network/support#469]
![failed_trade](https://user-images.githubusercontent.com/57108783/88695535-9264d980-d0f1-11ea-9e5b-a471285f4580.png)

Maker:  a515890d61402858ed859ad45edd936c85c00795d15b564a0032567cd7130641
Taker: 088c9b47e3cf155e2b6e679ec3785d39b478757c85d224b7caf21d225d6dd0a9
Deposit: NULL

Bisq version: 1.3.6

Other notes:

Second time this happened to me. Trade moved to Failed trades cause deposit transaction is null, please refund fees and try to improve Bisq. Thanks!

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
