### ISSUE TITLE
Fee reimbursement for trade: kahca & 747621

### ISSUE THREAD

**Issue by joee007** [bisq-network/support#470]
>_The kahca & 747621 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

<img width="579" alt="Failed Trade" src="https://user-images.githubusercontent.com/69259676/89444526-cfe3eb00-d71f-11ea-8c62-6128dec51178.png">

<img width="1192" alt="Screen Shot 2020-08-05 at 1 30 50 PM" src="https://user-images.githubusercontent.com/69259676/89444573-e68a4200-d71f-11ea-82fd-de3d21bf390c.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

<img width="900" alt="Screen Shot 2020-08-05 at 1 32 31 PM" src="https://user-images.githubusercontent.com/69259676/89444820-48e34280-d720-11ea-99b1-e3505124576d.png">

<img width="897" alt="Screen Shot 2020-08-05 at 1 32 59 PM" src="https://user-images.githubusercontent.com/69259676/89444822-497bd900-d720-11ea-9bd0-54c4e7a12958.png">

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

<img width="70" alt="Screen Shot 2020-08-05 at 1 34 15 PM" src="https://user-images.githubusercontent.com/69259676/89444867-61ebf380-d720-11ea-9b54-2f2f04895922.png">
Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please write down the maker and taker fee as all the other reimbursement requests
