### ISSUE TITLE
Fee reimbursement for trade RDVd7

### ISSUE THREAD

**Issue by userbisq** [bisq-network/support#471]
>_The RDVd7 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/69260167/89446555-0c691400-d72b-11ea-962c-fdce6d5ea23f.png)

>
Maker:  8f6142b7bb3e2c99677d60fad9212e29a8d21665fe1f0fe05a58d70417b3fe6b
Taker: 8dc74867ec0b772d6a1f9e2e8c20181a4b85664b679f80f403d71d8a7e53d2d6
Deposit: NULL

Bisq version: v1.3.6

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
