### ISSUE TITLE
Fee reimbursement for trade pwhnsmce

### ISSUE THREAD

**Issue by ceilican** [bisq-network/support#475]
![Screen Shot 2020-08-07 at 11 51 52](https://user-images.githubusercontent.com/1809436/89658153-8ffa4080-d8a4-11ea-9079-17d499678ad1.png)
![Screen Shot 2020-08-07 at 11 52 03](https://user-images.githubusercontent.com/1809436/89658159-91c40400-d8a4-11ea-9ddc-c1ec3d10b635.png)

Maker: 91482f63953626c2af8be74de0d2de610905d3e1ee431684bba7996a0e0a7970
Taker: 9c96de7764775f726b4b7328e3b478aa1e44a2b54293cb6a348d50f28d0c8824

Bisq version: 1.3.6

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913

**Comment by ceilican** [comment]
@leo816 , although I see the confirmed transaction (https://blockstream.info/tx/598753ba993a31ccf6a7c260b889965d5f96407aea4c837756a396d8bb57027a), I don't see any of the addresses of the failed trade included there and the transaction doesn't appear in my Bisq wallet.

Could you tell me to which address the fee of this trade was reimbursed?
