### ISSUE TITLE
Fee reimbursement for trade 049252

### ISSUE THREAD

**Issue by bisquit45** [bisq-network/support#478]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/69520596/89911896-f5f60900-dbbf-11ea-9580-ac8a1dfc8a82.png)

Maker:  32ddab93290b01ad18211f332bd19e61512cb46d497db2b7d04e1e36a76a7442
Taker: cab1b0dc3bc9cc3416b2ec48880f5c14432d6d29da99b39fb4554534f9d93737
Deposit:   none

Bisq version: v. 1.3.7

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by bisquit45** [comment]
My maker fees were taken, but it seems there was an issue on the taker (buyer) side.

![image](https://user-images.githubusercontent.com/69520596/89912907-1a9eb080-dbc1-11ea-8310-39aeb8604111.png)

**Comment by leo816** [comment]
Please delete the information below the first image right before the maker and taker. Otherwise it won't get processed.

**Comment by bisquit45** [comment]
> Please delete the information below the first image right before the maker and taker. Otherwise it won't get processed.

I just removed the info as instructed, please process the refund request.

**Comment by bisquit45** [comment]
Can someone please take a look at this? I've been waiting for almost 3 months, since Oct 15, 2029.

**Comment by leo816** [comment]
please provide a btc address where you would like to receive the payment

**Comment by bisquit45** [comment]
Thanks.  BTC address to receive payment is, triple checked: (Native segwit). 

bc1qg8a9ep5npphl8v7fmq7vuxg53xjezdzfd63x80

**Comment by bisquit45** [comment]
Hi leo816, any updates regarding the payment?

**Comment by leo816** [comment]
will be reimbursed this cycle

**Comment by bisquit45** [comment]
Thanks leo816
