### ISSUE TITLE
Fee reimbursement for trade 4954830

### ISSUE THREAD

**Issue by delistandecrypt** [bisq-network/support#480]
<img width="912" alt="bisqfee" src="https://user-images.githubusercontent.com/49699337/89988504-89d6dc00-dc77-11ea-8259-38d3b949b0cf.png">

Maker: e15240be0fc6fa46373df9458aac0d9717bc78ea6df7fb9034a5c06202af995b
Taker: ba5f2a1022d66a24faed06c3a00a88b774d5f91327efa08cd1f7573b50f497d3
Deposit: ?????
Value: 0.00017800
Bisq version:
v1.3.7

**Comment by MwithM** [comment]
The [deposit tx](https://mempool.space/tx/ba5f2a1022d66a24faed06c3a00a88b774d5f91327efa08cd1f7573b50f497d3) is valid and already confirmed! Have you tried to unfail this trade? https://bisq.wiki/Failed_trades

It also might be relevant for other failed trades to read this: https://bisq.wiki/Deposit_transaction

**Comment by delistandecrypt** [comment]
Cannot unfail

"The trade cannot be completed. Deposit transaction is null"

**Comment by Bayernatoor** [comment]
You posted the Taker TxId twice above. You should have a deposit transaction ID as well. Can you post that one?

**Comment by delistandecrypt** [comment]
Where do I get it from?

**Comment by delistandecrypt** [comment]
I can only see this in my TX history, something was subtracted from me and the trade failed.

<img width="1643" alt="Screenshot 2020-08-12 at 16 23 25" src="https://user-images.githubusercontent.com/49699337/90034199-3c2e9380-dcb8-11ea-9221-be7ea65b3113.png">

**Comment by delistandecrypt** [comment]
The fact that the error is "The trade cannot be completed. Deposit transaction is null" when I tried to restart the trade shows that Bisq screwed up with the deposit tx

**Comment by delistandecrypt** [comment]
What is the ETA on this?

**Comment by delistandecrypt** [comment]
Seriously, how long this is gonna take? It's been 1 fucking month already...

**Comment by chimp1984** [comment]
I can confirm that both trade fee txs do not lead to a deposit tx. The lost trade fee should be reimbursed in the batch reimbursement. @leo816 Can you take care of it?

**Comment by leo816** [comment]
yes, planning on finishing the batch reimbursement today

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
