### ISSUE TITLE
Fee reimbursement for trade eAkES [WIP]

### ISSUE THREAD

**Issue by thiagopaesm** [bisq-network/support#482]
![PrintBisq](https://user-images.githubusercontent.com/8849975/90300009-75a50180-de66-11ea-878e-d598fdb709f5.png)

## Summary
- **BSQ requested**: 10370.134 BSQ
- BTC requested: 0.65 BTC 
- BSQ rate: 0.00006268 BTC per BSQ 

## Trade details
TradeID: eAkES-e5413106-8731-4181-bf98-62748047f534-134
Trader code: htr459
Deposit transaction id: 2443df589ea0569b562b2e37a98c6f7a9849e3c3f55b320f64db0eb2d52e87aa

## motivation & payout suggestion
I, the buyer (code  htr459) propose to receive the whole payout for the trade as 1) I sent the XMR to the specified address (and the mediator verified) and 2) the seller did not reply a single one of mine nor the mediator's messages in over 10 weeks

## mediator suggestion 
The mediator made a spurious suggestion at first so we would push the trade into arbitration. He confirms that he believes I should receive the payout for this transaction 

Total transaction amount:
BTC Buyer payout:0.6470 BTC
BTC Seller payout:0.0030 BTC

**Comment by Bisq-knight** [comment]
I mediated this trade and I confirm:

- The seller did not show up and didn't reply neither my messages nor the trader's
- The buyer produced evidence of paying the XMR to the address in the contract
- The mediation suggestion I published was one for the buyer to reject and thus push the trade to arbitration. (which didn't work. The only way we got it to get the amount moved to the donation address was by following the [Dump Delayed Transaction guide](https://bisq.wiki/Dumping_delayed_payout_transactions) )

and I agree that the Buyer should get the whole multisig amount, his deposit, the trade amount and the seller's deposit as a reward for his trouble and time spent on this

**Comment by RefundAgent** [comment]
The secret htr459 is correct and identifies thiogopaesm as the buyer in this trade.

**Comment by leo816** [comment]
did you make the request on the DAO?

**Comment by thiagopaesm** [comment]
Yes. Transaction ID 62fc31916b720b5569f8ba0620ad28fc9f42af93b45ccb1f0a2251713fd2747b (Reimbursement request)

**Comment by thiagopaesm** [comment]
Yes. Transaction TX ID 62fc31916b720b5569f8ba0620ad28fc9f42af93b45ccb1f0a2251713fd2747b (Reimbursement request)

**Comment by sqrrm** [comment]
Cases that have to be taken to the DAO should not get the deposit from the other party paid out to them in my opinion. The cost to the DAO of doing the refund is already high and rewarding extra funds to the aggrieved party could act as an incentive to take cases to the DAO. While I understand that the aggrieved party doesn't feel good about having to wait so long to get their funds back, it's a matter of building a healthy Bisq as a whole.

I will still vote approval for this case, but going forward I don't think it's the right thing for the DAO.

**Comment by wiz** [comment]
@sqrrm Bisq only allows mediators to award a maximum of 50% of the other party's security deposit. The remaining 50% is kept by the DAO. I'm not sure why @Bisq-knight is awarding 100% in this case, maybe there are special circumstances, but I agree the DAO should keep some for the trouble.

**Comment by sqrrm** [comment]
I am specifically talking about the refunds from cases that have spent their 2of2 to the donation address. In those cases the refund can be anything, either the refund agent awards it, or it's requested from the DAO through a vote.

For mediation cases I think there is already a discussion ongoing somewhere which will likely come up with a reasonable process.

**Comment by chimp1984** [comment]
> @sqrrm Bisq only allows mediators to award a maximum of 50% of the other party's security deposit. The remaining 50% is kept by the DAO. I'm not sure why @Bisq-knight is awarding 100% in this case, maybe there are special circumstances, but I agree the DAO should keep some for the trouble.

This in not correct. It is 0.003 BTC as min refund independent of the sec. deposit to keep some incentive that the losing peer accepts the mediated payout suggestion. The arbitrator can set any amounts also 0.

I am not sure if I agree with @sqrrm to not give the peers deposit in such cases to the victim. The hassle and time loss to to a DAO reimbursement as well as the volatility and liquidity risk should be compensated. As well the DAO should suffer from such cases to have enough incentive to bring those cases down to the min. number.

**Comment by chimp1984** [comment]
Confirm that the delayed payout tx was done: https://mempool.space/tx/78cfa9deb163f215f6ab6f998fce352698e3e4e7bb25d1481a39023d018ddf54

**Comment by Bisq-knight** [comment]
Bringing this back.

The proposal in the DAO was accepted on cycle 16:

> Result: Accepted; Threshold: 100.0% (required > 50.01%);  Quorum: 1004895.40 BSQ (required > 20000.00 BSQ)

and can also be seen in the [chain](https://mempool.space/bisq/tx/62fc31916b720b5569f8ba0620ad28fc9f42af93b45ccb1f0a2251713fd2747b)
