### ISSUE TITLE
Fee reimbursement for trade bexqna

### ISSUE THREAD

**Issue by PatVers** [bisq-network/support#483]
![Captura de pantalla 2020-08-19 a las 19 25 02](https://user-images.githubusercontent.com/66955857/90675125-f80c3780-e251-11ea-93cd-2ca46f7fcdac.png)

Maker:  0060052a973b9bc8e25d023c4e4d7f5307b4d5a93a2b04bd57539f51e471a96a
Taker: 8781f7900c367a80d847a3d8bfeabeba0881274c7c5cb76190d20cc89b58c535
Deposit: ..........

Bisq version:

1.3.7

**Comment by leo816** [comment]
please post the btc where you would like the funds to be sent

**Comment by leo816** [comment]
Will be reimbursed with #515
