### ISSUE TITLE
Fee reimbursement for trade 0RGLLIRL

### ISSUE THREAD

**Issue by mexicaliblues** [bisq-network/support#484]
![Screenshot (2)](https://user-images.githubusercontent.com/70115976/90991090-177acb80-e596-11ea-8fd2-e38f5d73d142.png)

![Screenshot (3)](https://user-images.githubusercontent.com/70115976/90990924-af77b580-e594-11ea-9ae0-878b1dd87f71.png)

Maker:  85017441b8ce4fbf6dfff9e9121d7d53e51559b780e0e304bd353b832667effc
Taker:  6eaf6bec5056d45bfe343f2803f0ab6ae8a59381bb3e33523d026e61e97ddd3c
Deposit: n/a

Bisq version: 1.3.7

Other notes:

Status:  Failed

An error occurred at task: BuyerAsTakerSendsDepositTxMessage
Sending message failed: message=DepositTxMessage{

errorMessage=java.io.IOException: Cannot connect to hidden service
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()

**Comment by chimp1984** [comment]
Can you please post the onion address of the peer?

**Comment by mexicaliblues** [comment]
Trading peers onion address
gljhnomfr6d2e6b3.onion:9999

**Comment by leo816** [comment]
please post the btc address where you would like to receive the funds

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
