### ISSUE TITLE
Fee reimbursement for trade WNZNMW

### ISSUE THREAD

**Issue by randomzen2020** [bisq-network/support#487]
![bisq2](https://user-images.githubusercontent.com/70361515/91522610-4b206300-e8c0-11ea-83a0-567a5f689395.JPG)
Maker: e05ad8ee1d28e396f2aedd8e63b9c39c4469d6641791144684819e7283cb0115
Taker: a89a2536ca507a0b4eb8ada1f17f20ab51af07213fb8af015f8475e76bf6d02f
Deposit: 35a1c4a73655f75d2708707afadd8954496278332d9dd1b5ea512d107654faf1

Bisq version:1.3.7

Other notes: Trade failed, deposit spinning forever. please refund

**Comment by chimp1984** [comment]
Taker fee tx and deposit do not exist. Fee reimbursement is justified.

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
