### ISSUE TITLE
Fee reimbursement for trade e7a57ihi

### ISSUE THREAD

**Issue by cddc123** [bisq-network/support#488]
![Annotation 2020-09-03 152508](https://user-images.githubusercontent.com/70724116/92163987-2d8c5580-edfa-11ea-94ff-36ba3f9e568a.png)

Maker:  3466590f7f070e5487c5f35738ed4ac8ec9991bcb657cd3979abad52fa31dcdd
Taker: 2af67acee78d0901e3aa5c8da61b6b6662c08346f5ed55dc65e6be25bda3b091
Deposit: b7f9d0112253a04c30e4db935f9e32580d944a8d7cea50741f9ec9bee7ffbdfc

Bisq version: 1.3.7

Other notes:
Buyer's taker fee was never broadcasted

**Comment by chimp1984** [comment]
Taker fee tx and deposit tx do not exist. Fee reimbursement is justified.

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
