### ISSUE TITLE
Fee reimbursement for trade FKQPH

### ISSUE THREAD

**Issue by delistandecrypt** [bisq-network/support#489]
<img width="895" alt="Screenshot 2020-09-05 at 19 17 47" src="https://user-images.githubusercontent.com/49699337/92311168-af23e500-efac-11ea-924f-a4732d625c29.png">

Maker: 71756b228dce4f1bd6c4e4d1382af88543cdf05d37a649b3690f2b234b036e7f
Taker: 0db014b1e11de52f4dd55aae8d97ad41ce10d0fcaea1213f1a416633c95d7bf8
value: 0.00020920

Bisq version: v1.3.7

I need reimbursements of the Maker tx:  20920 sats

**Comment by leo816** [comment]
information provided is not being processed, please take another accepted reimbursement request as an example and edit this one.

**Comment by delistandecrypt** [comment]
What do you need?

**Comment by delistandecrypt** [comment]
What extra info do you need?

**Comment by delistandecrypt** [comment]
@leo816 What info more do you need?

**Comment by delistandecrypt** [comment]
So this means the 20k satoshi are gone forever? I have asked for a month what info do you need, no response in this ticket, so I've been scammed? WTF

**Comment by delistandecrypt** [comment]
WTF @leo816

**Comment by leo816** [comment]
Hi, sorry for the late reply I did not see your response. Please make another fee reimbursement request using the example as reference. Something is wrong with this one. Is not getting processed. Thank you for your patience and im sure it will get reimbursed on the next cycle

**Comment by delistandecrypt** [comment]
Look, I provided all info in the screenshot and added all the fields as text, now I should figure out why your broken script and not processing it?

**Comment by delistandecrypt** [comment]
WTF

**Comment by leo816** [comment]
The information is there, I don’t know why is not being processed which is why I mentioned that solution. It will be faster if you just create another one copying #480

**Comment by delistandecrypt** [comment]
Opened https://github.com/bisq-network/support/issues/510
