### ISSUE TITLE
Fee reimbursement for trade WRDIRWV

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#49]
This issue has been created per the process detailed in bisq-network/support#35 to track the reimbursement of trading and mining fees lost due to the 'failed transaction broadcast' problem being tracked at bisq-network/exchange#1193 and under investigation at bisq-network/exchange#1195.

If the trade ID in the title of this issue is yours, then please click the `Subscribe` button in the right menu of this issue to be notified about the status of your reimbursement.

If you do not see a `Subscribe` button, then you are not logged in to GitHub. Please log in or create an account if necessary. You'll then be able to `Subscribe` to this issue and you will get updates by email.

**Comment by meapistol** [comment]
![image](https://user-images.githubusercontent.com/10008813/35152867-38c62ac4-fd35-11e7-978a-094e0b18dd64.png)
Maker: 6906a5c39712208910550b89b45aaf75bbc9da600d1c26e7e80dd1dd0616edfa
Taker: e6d1a4c982e8e26ba1a9a5c72a5b7043e70f705109569a1f95289026bda37a67
Deposit: ef428b66c276940bbcf6a6c5171ca0e78a69f452254ae023400e7a324bc3c44e

**Comment by Nousmaintiendrons** [comment]
Hi ! Here is my log file.
[bisq.log](https://github.com/bisq-network/support/files/1656880/bisq.log)

**Comment by cbeams** [comment]
_The following information was provided to me by @keo-bisq via email:_

> ![35152867-38c62ac4-fd35-11e7-978a-094e0b18dd64](https://user-images.githubusercontent.com/301810/35336313-4d937f38-0118-11e8-9707-c20f1f300e70.png)
>
>Maker: 6906a5c39712208910550b89b45aaf75bbc9da600d1c26e7e80dd1dd0616edfa
>Taker: e6d1a4c982e8e26ba1a9a5c72a5b7043e70f705109569a1f95289026bda37a67
>Deposit: ef428b66c276940bbcf6a6c5171ca0e78a69f452254ae023400e7a324bc3c44e

Something is odd about the deposit transaction, however. It does not follow the typical pattert of a Bisq deposit transaction being followed by a payout transaction. Perhaps @keo-bisq can provide more information about what happened here.

It seems that both maker and taker transactions should be reimbursed, but I'll wait for more info from @keo-bisq before moving on.

@Nousmaintiendrons, if you can provide more information, that would be welcome, too. What was the final status of this trade from your side?

**Comment by cbeams** [comment]
Staged for reimbursement in 69f2cfe

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/35#issuecomment-362038006.
