### ISSUE TITLE
Fee reimbursement for trade Y1W1HTL

### ISSUE THREAD

**Issue by Bitcoinseller1** [bisq-network/support#490]
![image](https://user-images.githubusercontent.com/70901424/92394524-fed7ed00-f121-11ea-8d28-b74b045aea16.png)

Maker:  1827915aa46ceee1e3314bbe653bbaff96cf2472eb1ccc5d2e90880bac621b01
Taker: c820a418b127307e83aef0a803bf08fef9181a61695135bef2216f1f248908e4
Deposit: a42d42502a91aaa120c9dba9ca5ba4e7467fe54b540d5f62d8aca216514d1e2b

Bisq version: v.1.3.7

It's in failed folder. But there is no error message. Please reimburse fees.
Thanks.

**Comment by chimp1984** [comment]
The deposit tx is not paid out to the delayed payout tx. So it is not ready for reimbursement.
@Bitcoinseller1 can you select the trade in failed trades and click 'cmd+y' that will revert the trade so it is in pending trades again. After that open arbitration (click button review mediation result) and reject. If it was not in mediation yet you need to first go in mediation, once they closed it you can reject and that will open arbitration. With that the delayed payout tx gets published which is a precondition for reimbursement.

**Comment by Bitcoinseller1** [comment]
Unfortunately this does not work. When I press ctrl+y I only get the error message: "The trade cannot be completed. Delayed payout transaction is null" It is still located in failed trades. Btw the mediator leo816 had already suggested this.

**Comment by chimp1984** [comment]
@Bitcoinseller1 With the next release we change the handling of failed trades, then you can simpoly move it back to pending trades. If you can wait until the release is out (or run from that PR branch if you are a developer https://github.com/bisq-network/bisq/pull/4566) would be easiest.

**Comment by Bitcoinseller1** [comment]
I have installed the new version of Bisq v.1.4.2. Now I could move it back to the pending trades.  As mentioned above I have tried to reject the arbitration and start the arbitration procedure. But this obviously didn't work because it was not moved to the support screen as it should be.
Now it says _"Meditation requested, You opened already a dispute. Please communicate in Support screen with the mediator."_
But this is not possible because the meditation has already been closed.
![Bisq1](https://user-images.githubusercontent.com/70901424/97281393-be514180-183d-11eb-9bb1-49f975e16b1e.JPG)
