### ISSUE TITLE
Fee reimbursement for trade Y0RCUV

### ISSUE THREAD

**Issue by takeeatback** [bisq-network/support#491]
![fail](https://user-images.githubusercontent.com/65305927/92400514-e693ae00-f0e0-11ea-9350-f64487bcb837.PNG)

Maker:  fb109a0c21b274a3ceb3cc44483d56d0b73fd54e16e66e0ebecb963a0b007dce
Taker: ee3e146a70a69d29102bf1651ca7bdf104e0592e4b88224bbba1d16fcffd8cdc

Bisq version: v1.3.6

Other notes: trader said in chat he lost connection or something while making the trade. The confirmation thing never happened, and no payments were made. In failed folder, please reimburse fees.

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
