### ISSUE TITLE
Fee reimbursement for trade hl3mk

### ISSUE THREAD

**Issue by ajchess** [bisq-network/support#493]
![snippet](https://user-images.githubusercontent.com/71101888/92806393-94bc8380-f37f-11ea-9af7-0b257d92590a.PNG)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  0.00005720
Taker: 0.00017160
Deposit: 0.01566250

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.3.7

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by chimp1984** [comment]
Please post the 2 tx IDs as text strings as well, so reviewers can easier check them on block explorers.

**Comment by Bisq-knight** [comment]
@ajchess we're waiting on info from you. Can you provide it?

**Comment by pazza83** [comment]
Closing as no additional info provided.
