### ISSUE TITLE
Fee reimbursement for trade PULIEWO

### ISSUE THREAD

**Issue by patrihito** [bisq-network/support#494]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![20200910_bisq](https://user-images.githubusercontent.com/60511939/92883140-e3662e00-f410-11ea-9e39-bad37994d1c2.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: b803068025873769256e3efac0df63c65e6db03b947c5a92a4399493429cf9ae
Taker: a21314d9866aeea21247aebce81241f9114bfbb721010cf743737773c577500c
Deposit: 30a186cbc5c418b2746d68fca6c15e9f3e9d37acd400b156e692b3c2f14f9cc4

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.3.7

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Trade failed due to network issues. How could I retrieve funds from a failed trade? I've got two transactions that were published: 'deposit' and 'taker and tx fee' but the trade cannot be completed 'Delayed payout transaction is null'.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by chimp1984** [comment]
@patrihito Please post the peers onion address. That can help us to figure out why the delayed payout transaction was not set.

**Comment by chimp1984** [comment]
NACK

The funds from the deposit tx have been paid out:
https://blockstream.info/address/39JBENPXhSpKFuuMHtyGjwWuV7eNCMcJKr

@patrihito Did you get the funds on your wallet? Seems the peer accepted late your acceptance or the like.
You should have received the funds on either 1E3wiTTFVjq2r3Qd94ngkPM1BG9BAdrwnd or 1P7n9HHd5cXZs5k8Qvp1Jzyn1b9gPdmR1t .
