### ISSUE TITLE
Fee reimbursement for trade 53309238

### ISSUE THREAD

**Issue by Ke4e5** [bisq-network/support#495]
![imagen](https://user-images.githubusercontent.com/71121045/92883551-41931100-f411-11ea-9f8b-2edebf970319.png)

Maker:  f585fcfa16868fdbf24a8bedda71332e3495d01c63a968fd12f3587ff89798c8
Taker: ed5d193d4f4401e19f7e15b0f5e0f775850025b30c43835866de3d1f440cd10f
Deposit: NA

Bisq version: v1.3.7 (offer created long time ago)

Other notes:

**Comment by chimp1984** [comment]
@Ke4e5 Please post the peers onion address. That can help us to figure out why deposit txs are not set.

**Comment by Kg44545** [comment]
gpcfgtj2na7zpt67.onion:9999

![imagen](https://user-images.githubusercontent.com/71665814/93807017-54e08080-fc4a-11ea-8595-9f28da542a9f.png)

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
