### ISSUE TITLE
Fee reimbursement for trade knoemlr

### ISSUE THREAD

**Issue by slegaP** [bisq-network/support#496]
![image](https://user-images.githubusercontent.com/71106999/93003989-42ab6780-f511-11ea-9f54-46c47296bc8d.png)

Maker:  ea8b530ebf1c4b487ac7c666d006e271de130058c49aee15e0f4922dc93012b6
Taker: 26e183a8e96d4bb14cfe9b691bf665c9a95e8a0200af28a55d90914fa02719f0
Deposit: 06d903da682f31f6f3e9911d2da9ae1096d3271eab965024c341b70ff75f1704

Bisq version: 1.3.4

Other notes:
The transaction ended up in failed. 

"Trade could not be completed. Delayed payout transaction is null." 

Please reimburse fees/deposit.

**Comment by chimp1984** [comment]
@slegaP Can you PM me on keybase (same user name as here) and send me the log files so I can investigate the issue?
If there is no delayed payout tx we cannot do a normal reimbursement. We need to verify how that could happen.

Did you sent the USD?
