### ISSUE TITLE
Fee reimbursement for trade 7129251

### ISSUE THREAD

**Issue by MinimalStructure** [bisq-network/support#497]
7129251

>_Provide the Bisq client version to help developers identify the causing issue._
![BisqReimbursment](https://user-images.githubusercontent.com/69333458/93366258-c0b48a80-f7ff-11ea-9272-1fbf5f11e54c.png)

Maker transaction id: 039fe173f5c045001637bea46f19cf8dbbfbe399947095766e9717c2cddeedec
Taker Transaction id: f101de7b81a08fcd5a5a34766f302494d0e38a03b48883ae46a798cc07e9ca50
Bisq version:1.3.4

Other notes:

There was a failed transaction: The trade could not be completed. Deposit Transaction is null.  **The deposit transaction failed to create/broadcast.

**Comment by leo816** [comment]
format is not correct and is not getting processed, please take a look at other reimbursement requests and take them as example.

**Comment by leo816** [comment]
please provide your preferred btc address where you would like to receive the payment
