### ISSUE TITLE
Fee reimbursement for trade wpudgin

### ISSUE THREAD

**Issue by scubasound** [bisq-network/support#498]
<img width="838" alt="Screen Shot 2020-09-16 at 12 20 36" src="https://user-images.githubusercontent.com/8582004/93366916-d040cd00-f819-11ea-8b3b-7ab22d59eb7e.png">

Trade id: wpudgin-6ada0ae2-e5a8-4c6d-91c9-2610127617f4-137
Maker: fb04e25dd7fab4a160b236fee323fc5028fb9c54e8730af4d4f207458fd20d26
Taker: 2c9c5a9eec83efc73103f385e58e5b35b08597ae388b4202f251a15e32dd2baf

Bisq version: v1.3.7 

Please reimburse fees/deposit.

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
