### ISSUE TITLE
Fee reimbursement for trade KQMPQZ

### ISSUE THREAD

**Issue by scubasound** [bisq-network/support#499]
<img width="846" alt="Screen Shot 2020-09-16 at 21 29 50" src="https://user-images.githubusercontent.com/8582004/93409528-1707e480-f865-11ea-8508-07b297d41653.png">
Trade ID: KQMPQZ-f62f3016-17df-489d-a027-95bad8e97632-137

Maker:  97c527e0e8199f44d98585c04c536fb2436b646871e2e14332bbaaa094c7ef12
Taker: 2c9c5a9eec83efc73103f385e58e5b35b08597ae388b4202f251a15e32dd2baf

Bisq version:
1.3.7

**Comment by leo816** [comment]
Will be reimbursed with #481

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/481#issuecomment-699182913
