### ISSUE TITLE
Fee reimbursement for trade mjdkabdz

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#50]
This issue has been created per the process detailed in bisq-network/support#35 to track the reimbursement of trading and mining fees lost due to the 'failed transaction broadcast' problem being tracked at bisq-network/exchange#1193 and under investigation at bisq-network/exchange#1195.

If the trade ID in the title of this issue is yours, then please click the `Subscribe` button in the right menu of this issue to be notified about the status of your reimbursement.

If you do not see a `Subscribe` button, then you are not logged in to GitHub. Please log in or create an account if necessary. You'll then be able to `Subscribe` to this issue and you will get updates by email.

**Comment by meapistol** [comment]
![image](https://user-images.githubusercontent.com/10008813/35152941-792b0904-fd35-11e7-9778-07e4a00fb1eb.png)
Maker: 54890b13561bd9dc4c648f59873fd87e153e11f71a197230c262ab5b78c3116d
Taker: b39e6ae7de962e64531691d60493196ca5c9551e7dfb247303691176e1f75f8f
Deposit: 3177934854da284bbef6baa2da951e658a34296f7f6aa5b471cf3305144bbcda

**Comment by cbeams** [comment]
_The following information was provided to me by @keo-bisq via email:_

![35152941-792b0904-fd35-11e7-9778-07e4a00fb1eb](https://user-images.githubusercontent.com/301810/35335860-f6c3270e-0116-11e8-8615-dd36e486172e.png)

Maker: 54890b13561bd9dc4c648f59873fd87e153e11f71a197230c262ab5b78c3116d
Taker: b39e6ae7de962e64531691d60493196ca5c9551e7dfb247303691176e1f75f8f
Deposit: 3177934854da284bbef6baa2da951e658a34296f7f6aa5b471cf3305144bbcda

_And now, after checking all three of the above, I see they have each confirmed and that a payout transaction has been completed as well:_

Payout: de88aed3ac9fb2ab20134f836b2a28ae2b0b5ab18a8b86095945f2e55639bf73

This means that each of the maker and taker transactions should be staged for reimbursement.

**Comment by cbeams** [comment]
Staged for reimbursement in ab97bf8

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/35#issuecomment-362038006.
