### ISSUE TITLE
Fee reimbursement for trade nAEPJO

### ISSUE THREAD

**Issue by aamirazh** [bisq-network/support#504]
![image](https://user-images.githubusercontent.com/11139415/94442865-740f6e80-0172-11eb-9e70-6d5175107f0f.png)

Maker: 2c4370ae9c0598cf04ac89f5f19630dda18b0748116d4d1a31a0e1552b20e05d
Taker: 4310bbe835181913e1e806c075bc82a1e5aaf024a1b4debb27d857d35a469850

Bisq version: v1.3.9

Other notes: Trade was spinning forever, BTC deposit was never published in mempool. Resynced SPV and trade was in failed folder. Maker fee transaction ID is valid, taker fee transaction ID is invalid. Lost deposit/fee, requesting reimbursement.

**Comment by leo816** [comment]
please post the btc address where you would like your funds to be sent

**Comment by aamirazh** [comment]
Sorry for the late response. Here is the address:

bc1qsym7upqay4ynnl402dgs5xhz6gx59xwlqzuupy

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
