### ISSUE TITLE
Fee reimbursement for trade uprarl

### ISSUE THREAD

**Issue by nolim13** [bisq-network/support#505]
![imagen](https://user-images.githubusercontent.com/72128378/94661028-ce413880-0306-11eb-96ba-adea06c782c0.png)

Maker:  5f2181f5da64df2f931b16ed9ba16f64126dcea5b41e3c87fea0dba21842fe0a
Taker: 39cf42f64aa1f360dcbc6dfeb2da2a5a0196b55df80e52b27620ad63ca3f37c8

Bisq version: 1.3.9

Other notes: This deposit tx was for a few time waiting in the mempools, and then it was considered invalid.

**Comment by leo816** [comment]
please provide the btc address where you would like your fees to be sent

**Comment by nolim13** [comment]
1GUBeL6i5FmiMDfVhPYpFPSBFzmq3FzYkE

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
