### ISSUE TITLE
Fee reimbursement for trade 8594209

### ISSUE THREAD

**Issue by mexicaliblues** [bisq-network/support#506]
![image](https://user-images.githubusercontent.com/70115976/94753320-68dc5e80-037d-11eb-8dec-5d13375f0e23.png)
![image](https://user-images.githubusercontent.com/70115976/94753626-50207880-037e-11eb-9957-b93861dfbebf.png)

Maker:  496f6a21c9961275ac9f8bb5a0ee490b5dbb42d77cb1594235c66d873cb22a35
Taker: a72914682cc84722e6a639269b8f71ec5b8271e8f4025571d045bb6ce8c6b566
Deposit: Buyer: 0.0060 BTC / Seller: 0.0060 BTC

Bisq version:  v1.3.9

**Comment by leo816** [comment]
please provide the btc address where you would like your fees to be sent

**Comment by mexicaliblues** [comment]
3QXitdnwhZ8X2WPHmNRjNoEBCHzWBX2J1Z

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
