### ISSUE TITLE
Fee reimbursement for trade 80891

### ISSUE THREAD

**Issue by cmcnulty** [bisq-network/support#507]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Capture-anon](https://user-images.githubusercontent.com/638534/95275947-7d9e7380-080f-11eb-894f-eb1eacdbc459.png)

Maker:  dcf6192b144f124c6b194790375161816de260cbbb52646d74c632f47810f3a8
Taker: 3b4c3d84ab168d98def7bc7ffd5490aef481de2d34d6b55ed8ea17adf5a36b5f
Deposit: ..........

Bisq version: v1.3.9

Other notes:
Error message:
`An error occurred at task: BuyerVerifiesPreparedDelayedPayoutTx
delayedPayoutTx.getLockTime() must match trade.getLockTime()
Invalid state: trade.isTakerFeePublished() && !trade.isFundsLockedIn()`

Please provide refund to: 1AHrQNEVHxRER1q1DsmjtZLp6uSjsAN3cr

**Comment by leo816** [comment]
please provide the btc address where you would like your fees to be sent

**Comment by cddc123** [comment]
@leo816 i am the maker/seller on this trade - do i need to create an issue also?

**Comment by cmcnulty** [comment]
> 
> 
> please provide the btc address where you would like your fees to be sent

1G17x7thrReNeWoo71sYgpZYYMBsZ35RpY

**Comment by cmcnulty** [comment]
@cddc123 I don't know if there was some way of salvaging the trade - didn't look like there was much to be done about the error message on the trade.

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
