### ISSUE TITLE
Fee reimbursement for trade 9749404

### ISSUE THREAD

**Issue by e9zcdR2uDU5xp4E** [bisq-network/support#508]
![image](https://user-images.githubusercontent.com/72713965/95692827-f5620900-0c28-11eb-913e-9cc1f472b090.png)

Maker:  d6e476930614e52a9f78d4549798f88d40470daf0d9985e2ba0303130ebb90ad
Taker: 2bd717da1d45ec08be165f2cbf83c3508639ab7549b16e2224202f93846c1f93
Deposit: ..........

Bisq version: v1.3.9

Other notes: Provide reimbursement to address `1PtAZqaqwDErAf9FYsbvPBTG7YRVmAYNDs`

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
please provide the btc address where you would like to receive your payment

**Comment by e9zcdR2uDU5xp4E** [comment]
1PtAZqaqwDErAf9FYsbvPBTG7YRVmAYNDs

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
