### ISSUE TITLE
Reimbursement and compensation for trade 09687320

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#509]
Hello. I would like to get my coins and a compensation from the unresponsive trade partner's deposit for the trade 09687320. I am the maker and BTC buyer in this offer. I sent the XMR to the trading partner correctly. I would like to get a refund of my funds and a compensation from the unresponsive BTC seller's deposit. 1.206060 BTC by 30-day average price 0.00005671 BTC per BSQ makes 21267.15 BSQ total refund. The secret is "werfs".
![Clipboard01](https://user-images.githubusercontent.com/63785272/95959855-51808500-0e03-11eb-9190-97a517ba3d73.png)

**Comment by MwithM** [comment]
Who was the mediator if this trade?

**Comment by Akira45-0** [comment]
> Who was the mediator if this trade?
sjlho4zwp3gecspf

**Comment by leo816** [comment]
Payment was made to the donation address, Just contacted the Refund Agent about this case.

**Comment by wiz** [comment]
instead of posting a screenshot, can you please post the new cryptographically signed mediator's summary using v1.4.0

**Comment by Akira45-0** [comment]
> instead of posting a screenshot, can you please post the new cryptographically signed mediator's summary using v1.4.0

Where do I find it? The mediation looks exactly the same in 1.4.0 for me.

**Comment by Akira45-0** [comment]
OK, so I have reopened the trade, @leo816 closed it, but I still see it as opened, and without any signature. Maybe it's a bug, I don't know.

**Comment by RefundAgent** [comment]
The secret is correct.

**Comment by Akira45-0** [comment]
> 
> 
> The secret is correct. I cannot judge if the claim is correct since I have essentially no information, but the little information I have agrees with the screenshot. The mediator should evaluate the claim.

Nothing has changed, after reopening I still see the mediation as opened, though @leo816 says he closed it.

**Comment by Akira45-0** [comment]
Ticket closed on Nov 1, 2020 12:13:00 PM
Mediator node address: sjlho4zwp3gecspf.onion:9999

Summary:
Trade ID: 09687320
Currency: XMR
Trade amount: 0.9662 BTC
Payout amount for BTC buyer: 1.206060 BTC
Payout amount for BTC seller: 0.05 BTC

Reason for dispute: Other

Summary notes:
btc buyer made the payment correctly. btc seller never confirmed or answered.

-----BEGIN SIGNATURE-----
302d02150083600a749fcaebc732580e815fe877992cc7195802140eea5bef55892a5ae584569f3d4447d7e97dd4d0
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator
@wiz

**Comment by leo816** [comment]
I can confirm the information on this reimbursement request is correct

**Comment by RefundAgent** [comment]
The Refund Agent has not paid out anything for this dispute.

**Comment by Akira45-0** [comment]
> 
> 
> The Refund Agent has not paid out anything for this dispute.

Indeed. So what should I do to receive the compensation?

**Comment by ripcurlx** [comment]
@Akira45-0 Can you please post the the `Proposal transaction ID` linked to this reimbursement request? Thanks!

**Comment by Akira45-0** [comment]
> 
> 
> @Akira45-0 Can you please post the the `Proposal transaction ID` linked to this reimbursement request? Thanks!

https://bsq.vante.me/tx.html?tx=5e58eb57ecbcd77b1160f49a33d129805ed0ecacdf27665fee4d851d3077002f

**Comment by chimp1984** [comment]
Verified:
<img width="955" alt="Screen Shot 2020-11-02 at 12 26 40" src="https://user-images.githubusercontent.com/54558767/97898998-afb7ce00-1d06-11eb-8136-9e251f914f6b.png">

**Comment by Akira45-0** [comment]
I have multisig payout fot this trade in my transaction list, but the transaction id does not appear in the network. What's going on?

**Comment by chimp1984** [comment]
Maybe seller finally confirmed and by that published the payout tx. Was the delayed payout tx publihsed? Can you post all tx IDs of the trade?

**Comment by Akira45-0** [comment]
The multisig payout is e62e61ecd6cbf39e21c172c2e8de423ef4548284e2a7e71424497661a87bd62d. It's not published, but I see it in my transactions list
![Clipboard02](https://user-images.githubusercontent.com/63785272/98445819-09ab0000-211a-11eb-88f1-ee7848eedc22.png)
![Clipboard01](https://user-images.githubusercontent.com/63785272/98445810-00219800-211a-11eb-9766-a88a88876f72.png)

**Comment by chimp1984** [comment]
Can you post the other 4 txs, so its easier to copy paste to look up explorers?

**Comment by Akira45-0** [comment]
2bdc86ec83634f69c373fd183f3e40623e86c63e0b03b2f8cdafb64443dc72a3
e327fe8cfe3f49eb6db5e55ea29023bb34b4e859da31453feaaa928bbd79ce2e
4087ec3e73898bc9025a0bbd53b58484154c534b28d9ca18529a5421d8c1126d
0c7457fb395470006fbfd12575cc633f4eaf320db4cc47eafcb52c58a2b7210d

**Comment by chimp1984** [comment]
I can confirm that the delayed payout tx was published and e62e61ecd6cbf39e21c172c2e8de423ef4548284e2a7e71424497661a87bd62d is not found on explorers.

@RefundAgent Have you done the refund for that trade? If so it seems the miner fee was low and its still not confirmed. We can wait a few days more and if still not confirmed a CPFP tx could be made to push the tx, otherwise it would require a spv resync for the refund agent if he paid from the bisq app.

**Comment by Akira45-0** [comment]
As I understand it, I should receive the compensation in BSQ, right? So how is the Refund Agent supposed to know my BSQ address if I never sent it to him?

**Comment by chimp1984** [comment]
If the refund agent has paid you its in BTC. If not you need to make a reimbursement request (in BSQ).

**Comment by Akira45-0** [comment]
> 
> 
>  If not you need to make a reimbursement request (in BSQ).
Again?? I already made one in the DAO.

**Comment by chimp1984** [comment]
Oh, then I hope the refund agent did not pay out to you otherwise you would get it twice... Lets see what he responds...

**Comment by Akira45-0** [comment]
Being paid once would have been enough for me, but so far I didn't receive anything.

**Comment by RefundAgent** [comment]
I did not do any payout for trade: 09687320

**Comment by chimp1984** [comment]
So then its weird why u got a tx (e62e61ecd6cbf39e21c172c2e8de423ef4548284e2a7e71424497661a87bd62d) to that trade. Can you search the logs for that tx and PM me the full tx details? and your payout address in the trade details (or json data) to see if that tx was sent to your address.

**Comment by Akira45-0** [comment]
I sent it on Keybase.

**Comment by Akira45-0** [comment]
Now I see that I have an extra amount on my BSQ banalce that looks like I had received the 21267.15 BSQ, but I don't see any incoming BSQ transactions in the list. @RefundAgent did you do the refund?

**Comment by chimp1984** [comment]
Your reimbursement request got accepted, so the btc you put into there got magically converted to BSQ ;-). There is no exta tx for that.

**Comment by Akira45-0** [comment]
Oh, OK, thank you very much.

**Comment by pazza83** [comment]
Closing as resolved
