### ISSUE TITLE
Fee reimbursement for trade yhfnpo

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#51]
This issue has been created per the process detailed in bisq-network/support#35 to track the reimbursement of trading and mining fees lost due to the 'failed transaction broadcast' problem being tracked at bisq-network/exchange#1193 and under investigation at bisq-network/exchange#1195.

If the trade ID in the title of this issue is yours, then please click the `Subscribe` button in the right menu of this issue to be notified about the status of your reimbursement.

If you do not see a `Subscribe` button, then you are not logged in to GitHub. Please log in or create an account if necessary. You'll then be able to `Subscribe` to this issue and you will get updates by email.

**Comment by meapistol** [comment]
![image](https://user-images.githubusercontent.com/10008813/35153669-81bf5d06-fd38-11e7-8294-faf37e84418e.png)
Maker: 3951b93b3f874ce391463a53cab09d81b70f128a73500b4a9ebe8e5b54a78acd
Taker: 2c760813923bc1e684a75a0a40addcc43f8274e51b0b4b8de3c2bc57e64d2447
Deposit: 84fe3ddb053c3ab214aeb81c8ca7a9db0bd45396db307c4366ac9859d8da348a

**Comment by cbeams** [comment]
@keo-bisq, I need a screenshot and plain text of Maker / Taker / Deposit transaction IDs for this trade. Please provide this info and I'll get them staged for reimbursement as appropriate. Thanks.

**Comment by cbeams** [comment]
Any update on transactions here?

**Comment by keo-bisq** [comment]
Correct tradeID is yhfnpo. I made a typo before.
![image](https://user-images.githubusercontent.com/33939632/35592257-b7d26118-060c-11e8-9939-37dca46208de.png)
Maker:    3951b93b3f874ce391463a53cab09d81b70f128a73500b4a9ebe8e5b54a78acd
Taker:     2c760813923bc1e684a75a0a40addcc43f8274e51b0b4b8de3c2bc57e64d2447
Deposit:  84fe3ddb053c3ab214aeb81c8ca7a9db0bd45396db307c4366ac9859d8da348a

**Comment by cbeams** [comment]
Staged for reimbursement in efa97af

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/35#issuecomment-362038006.
