### ISSUE TITLE
Fee reimbursement for trade FKQPH

### ISSUE THREAD

**Issue by delistandecrypt** [bisq-network/support#510]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/49699337/96253942-5f253e80-0fac-11eb-8e5a-d6f31079470c.png">

Maker: 71756b228dce4f1bd6c4e4d1382af88543cdf05d37a649b3690f2b234b036e7f
Taker: 0db014b1e11de52f4dd55aae8d97ad41ce10d0fcaea1213f1a416633c95d7bf8
Deposit: ?????

Bisq version: 

v1.3.7

**Comment by leo816** [comment]
please post the BTC address where you would like to receive te reimbursement request

**Comment by delistandecrypt** [comment]
bc1qxnzy4tg7d3scyanlnftxwzlaj5u64yea88tgfj

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
btc address is not valid

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
