### ISSUE TITLE
Fee reimbursement for trade kvkrfpa

### ISSUE THREAD

**Issue by Brakon21** [bisq-network/support#511]
![image](https://user-images.githubusercontent.com/66847697/96338023-53438600-1059-11eb-8a55-1d9c9694abbd.png)

Maker:  8dd687a42349898d73490cff5fcd06da96790c7d8203d2724c9685214569e7c3
Taker: fd67bad48b48cad4efaa87d48c05e7473ebf177a2b121d20c47efa55a07d87fe
Deposit: 

Hi, my trade as a Maker failed, a received a request to restart BISQ, when I did transaction has disappeared and shown as failed. Please help me to get back my found and deposit.  

Bisq version: 1.3.6

Other notes: Issue #197

**Comment by Brakon21** [comment]
Hi, Can anyone help me to get refund?

**Comment by huey735** [comment]
@Brakon21 the refund is done once a month/cycle.

**Comment by Brakon21** [comment]
Noted

**Comment by leo816** [comment]
please post the BTC address where you would like to receive the reimbursement request

**Comment by Brakon21** [comment]
Hi, use the below one:

bc1q3tkhl9kzar3z0xcxtamdkhgraeuesy695ftg50

thanks.

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
is this a btc address? :

bc1q3tkhl9kzar3z0xcxtamdkhgraeuesy695ftg50

**Comment by huey735** [comment]
What do you mean @leo816 ??

**Comment by leo816** [comment]
btc address wasn't showing up on the explorer

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
