### ISSUE TITLE
Fee reimbursement for trade KJVEg

### ISSUE THREAD

**Issue by ypt0** [bisq-network/support#514]
![trade_KJVEg_2020-10-23_19 42 43](https://user-images.githubusercontent.com/73359715/97036421-194a1680-1568-11eb-8876-d9dea19c4d1b.png)

Trade ID: KJVEg
Maker:  57b7b89a33a9103a0e808ce2781370375d8ab1198381a2a894c0f5e754da4834
Taker: 92bba9aa5056edc1479bc9c05859409d65e22e067e664b523c1b9cd6b1b1d9bc
Deposit: 0.0060

Bisq version: 1.4.2

Moved to failed folder. Please reimburse fees.
Thank you.

**Comment by leo816** [comment]
please post the BTC address where you would like to receive the reimbursement request

**Comment by ypt0** [comment]
Please reimburse to address 1NQDKR1MjgB99bdKvAYtCUc8fvbmqmTezC
Thank you.

**Comment by leo816** [comment]
Will be reimbursed with #515

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/515#issuecomment-716412953
