### ISSUE TITLE
Fee reimbursement for trade 01PVOJQC

### ISSUE THREAD

**Issue by arborr** [bisq-network/support#516]
![reimburse](https://user-images.githubusercontent.com/73502631/97235433-dcbd2b80-17b0-11eb-86ae-9417f10312dd.png)

maker: 6ac8025b045162b92e1d706d0c94a9c776c5ca87655b18c1b4ba183cd33c1f6d
taker: e657c2c6398a1cd2fd61f2be73acb086f033eca8e36b7148afec66ca41956af4
deposit: 9fb012e1645cb6e2964f03b32d81e25e95971ed708da95af899e85243b6fb9c9

Bisq version: 

1.4.2

Other notes:

Delayed payout tx missing. Security deposit locked.

EDIT: Had to move to a new wallet due to bug, refund can be processed to new address: 17eehe1bHCzeT99z642pUKz1T4eZwtU5hD

**Comment by Bisq-knight** [comment]
Can you tag your mediator on this issue? I checked my cases and yours was not one of them.

**Comment by arborr** [comment]
@huey735

**Comment by arborr** [comment]
Any update to this?

**Comment by huey735** [comment]
Hi @arborr , sorry for being late to this. Your security deposit isn't locked. At most it's "reserved". This is to say that it's on your wallet under your control. You may need to [Resync your SPV](https://bisq.wiki/Resyncing_SPV_file) file to see the funds on your wallet.

**Comment by arborr** [comment]
It says that it's locked, not reserved. I get 2 popups when I load up that says it's locked. Resync'd the SPV and still have the funds showing up as "locked".
![s](https://user-images.githubusercontent.com/73502631/99002802-ab5b9400-2502-11eb-9da8-23102702657a.png)

![a](https://user-images.githubusercontent.com/73502631/99002603-4acc5700-2502-11eb-8b0d-e2870ceeaf56.png)

**Comment by huey735** [comment]
DM me on Keybase, I'm huey735.

**Comment by leo816** [comment]
payout made correctly
