### ISSUE TITLE
Fee reimbursement for trade hybwgnye

### ISSUE THREAD

**Issue by Jan877** [bisq-network/support#517]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

<img width="633" alt="Message 2_hybwgnye" src="https://user-images.githubusercontent.com/44270690/97363319-b081d780-18a2-11eb-95e7-051b9ee1778c.png">
<img width="612" alt="Message 1_hybwgnye" src="https://user-images.githubusercontent.com/44270690/97363376-c42d3e00-18a2-11eb-84c8-7a9a7abeac41.png">

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  298c74015f7fe17b5d31efcecbd9d703cf66852c7b9b074ff794352c79bfb14c
Taker: 306ea8364472db1c7a5c47ce4b9f65964eadd7c7522dc021ebe154a2779a75c2
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by pazza83** [comment]
Closing as no response
