### ISSUE TITLE
Fee reimbursement for trade dc8g5r

### ISSUE THREAD

**Issue by stakoholic** [bisq-network/support#519]
![bisq1](https://user-images.githubusercontent.com/42588964/97605756-50f50a80-1a0f-11eb-91c4-9a36dd8d36b6.png)

Maker: 0ad7999a6679ecc625e13cf504067b06bc0ca067180ef529e18ec081280af6f3
Taker: na
Deposit: na

Bisq version: 1.4.2

Other notes:

**Comment by wiz** [comment]
looks like a failed trade, you should be able to do an SPV re-sync and recover your funds. there were no funds lost.
