### ISSUE TITLE
Fee reimbursement for trade HYyDj

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#52]
This issue has been created per the process detailed in bisq-network/support#35 to track the reimbursement of trading and mining fees lost due to the 'failed transaction broadcast' problem being tracked at bisq-network/exchange#1193 and under investigation at bisq-network/exchange#1195.

If the trade ID in the title of this issue is yours, then please click the `Subscribe` button in the right menu of this issue to be notified about the status of your reimbursement.

If you do not see a `Subscribe` button, then you are not logged in to GitHub. Please log in or create an account if necessary. You'll then be able to `Subscribe` to this issue and you will get updates by email.

**Comment by meapistol** [comment]
![image](https://user-images.githubusercontent.com/10008813/35153732-ce3ec950-fd38-11e7-980c-c27c81babff9.png)
Maker: 6c9838158171e2c4211b0f9d0415d02de71c9c1738e2dd03261efc932e559f87
Taker: e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c
Deposit: 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a

**Comment by cbeams** [comment]
@ManfredKarrer wrote in https://github.com/bisq-network/exchange/issues/1193#issuecomment-359067087:

> @MGMGS Can you post me the trade fee and deposit tx ID and if you are maker or taker?

@MGMGS wrote in https://github.com/bisq-network/exchange/issues/1193#issuecomment-359095267

> @ManfredKarrer I am btc buyer as taker 
> security deposit 0.03 btc
> taker mining fee 0.002574 btc
> taker fee transaction id e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c
> deposit transaction id 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a

@ManfredKarrer wrote in https://github.com/bisq-network/exchange/issues/1193#issuecomment-359123303:

> @MGMGS 
> 
> Taker fee tx e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c was broadcasted, though deposit tx not.
> 
> Taker fee tx :
> There have been 9 connections but we did not hear back from any, so timeout got triggered.
> 
> Jan-12 11:53:09.898 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: Waiting for 4 peers required for broadcast, we have 9 ... 
> Jan-12 11:53:17.908 [JavaFX Application Thread] WARN  i.b.c.b.w.Broadcaster: Broadcast of tx e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c not completed after 8 sec. We optimistically assume that the tx broadcast succeeded and call onSuccess on the callback handler. 
> 
> Tx got into the blockchain:
> Jan-12 11:55:16.073 [BlockingClient network thread for 3r44ddzjitznyahw.onion:8333] INFO  o.b.w.Wallet: Received tx for -0.001288 BTC: e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c [1] in block 000000000000000000825a77e37d51f02f361e1b3c5cee3c452efbb47aa31600 
> 
> 
> Deposit t:
> Deposit tx 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a had 286 Satoshi/Byte.
> 
> Jan-12 11:53:20.070 [JavaFX Application Thread] INFO  i.b.c.b.w.WalletService: 
> depositTx:
>   7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a
> in   PUSHDATA(71)[3044022011a2b925ec192673902c961b6678f8f26d11c9ca65542c70c3603dad74bcf872022015497b55e74383a85a161627e24ce9a52154d630bd41c65b56a1d1abc3c45d9501] PUSHDATA(33)[020164412d9bf7d366c0bf55c51173402e304dfbd3391f90b3a4c1c37df55a54ac] 0.032176 BTC (3217600)   
> outpoint:e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c:1 hash160:fd4b58e00d01a549e5b66865d404d16c6cb8dd9e
> in   PUSHDATA(72)[30450221009a426d7c379f2e99f184b9fc4abfc523f8743f2737b687ab962438f3a044d91402206fc01678c277016e77d8b279f4472b5c8fa1d152b7476b82ee1ce027ee07fd5301] PUSHDATA(33)[036e3266973fc025363dfe36e49f49543179a5e3aecdec26c8961f6c445b16baff] 0.053 BTC (5300000)
> outpoint:6c9838158171e2c4211b0f9d0415d02de71c9c1738e2dd03261efc932e559f87:1 hash160:cc2b62416e7f69e266547d0cd395a8895446380b
> out  HASH160 PUSHDATA(20)[23de9f8c3443da5e5300c7e4c85e79fd52c73f6c] EQUAL 0.084088 BTC (8408800) ScriptPubKey: a91423de9f8c3443da5e5300c7e4c85e79fd52c73f6c87 Address:34xgGPeM3mNACHuMmcdC6yxXTFsL7UB1ih 
> out  RETURN PUSHDATA(32)[b8d0307e72292026e791bc566b091258825d7380835889159dfd03d6e7043ba2] 0.00 BTC (0) ScriptPubKey: 6a20b8d0307e72292026e791bc566b091258825d7380835889159dfd03d6e7043ba2 
> Address:[exception: Cannot cast this script to a pay-to-address type]
> fee  0.001088 BTC for 380 bytes (286 Satoshi/Byte) 
> prps UNKNOWN
> 
> Jan-12 11:53:20.071 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: Waiting for 4 peers required for broadcast, we have 9 ... 
> 
> Jan-12 11:53:28.084 [JavaFX Application Thread] WARN  i.b.c.b.w.Broadcaster: Broadcast of tx 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a not completed after 8 sec. We optimistically assume that the tx broadcast succeeded and call onSuccess on the callback handler. 
> 
> Jan-12 11:53:20.071 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: We have 9 peers, adding 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a to the memory pool 
>  
> Never heard back from peers.
> 
> Several re-broadcasts but without hearing back:
> 
> Jan-14 13:14:50.536 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: We have 4 peers, adding 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a to the memory pool 
> Jan-14 13:14:50.537 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: Sending to 4 peers, will wait for 1, sending to: 
> 
> Jan-14 21:42:30.672 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: We have 4 peers, adding 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a to the memory pool 
> Jan-14 21:42:30.672 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: Sending to 4 peers, will wait for 1, sending to: ....
> 
> Jan-15 08:43:31.584 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: We have 4 peers, adding 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a to the memory pool 
> Jan-15 08:43:31.584 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: Sending to 4 peers, will wait for 1, sending to: ...
> 
> Jan-16 09:17:39.966 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: We have 5 peers, adding 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a to the memory pool 
> Jan-16 09:17:39.995 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: Sending to 5 peers, will wait for 1, sending to: [fz6nsij6jiyuwlsc.onion]:8333,[c6ac4jdfyeiakex2.onion]:8333,[i3a5xtzfm4xwtybd.onion]:8333,[lgkvbvro67jomosw.onion]:8333,[r3dsojfhwcm7x7p6.onion]:8333 
> 
> Turns out that maker fee tx 6c9838158171e2c4211b0f9d0415d02de71c9c1738e2dd03261efc932e559f87 was not in the blockchain, thus preventing the deposit tx to get accepted.
> 
> 
> @cbeams, @keo-bisq If you had that dispute could you request from the maker the full log file?
> Trade ID HYyDj
> 
> 
> Summary:
> Maker fee tx failed. Require log file from maker.

**Comment by cbeams** [comment]
> @cbeams, @keo-bisq If you had that dispute could you request from the maker the full log file?
> Trade ID HYyDj

This trade is @keo-bisq's.

**If you are reading this and you were the maker of this trade (`HYyDj`), could you please upload your `bisq.log` file in order to help @ManfredKarrer analyze it? Thank you!**

@keo-bisq, could you re-open the maker's ticket and ask them to do this as well?

**Comment by MGMGS** [comment]
Opened bisq today and have notification that at least 1 confirmation has been received on this trade. Also downloaded and installed new version.

**Comment by cbeams** [comment]
@MGMGS, I assume this trade is already in arbitration, yes? Have you been in communication with @keo-bisq there? Have all the transactions now been confirmed for this trade?

**Comment by cbeams** [comment]
_The following is Information provided to me by @keo-bisq via email:_

![35153732-ce3ec950-fd38-11e7-980c-c27c81babff9](https://user-images.githubusercontent.com/301810/35279361-316b1828-004d-11e8-8f24-f14f08e5791a.png)

Maker: 6c9838158171e2c4211b0f9d0415d02de71c9c1738e2dd03261efc932e559f87
Taker: e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c
Deposit: 7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a

**Comment by MGMGS** [comment]
@cbeams The deposit transaction has been confirmed now. The maker transaction has not.

I am taker.

Last communication with @keo-bisq  in chat was...

Can you please upload your logfile such that Manfred can find the problem. I am not sure where but presumably https://github.com/bisq-network/exchange/issues/1195 is a good place.

Me: He evaluated my log file as taker. He needs maker log file

**Comment by cbeams** [comment]
> @MGMGS, I assume this trade is already in arbitration, yes? Have you been in communication with @keo-bisq there? Have all the transactions now been confirmed for this trade?

Nevermind this earlier question. I have just checked and confirmed that indeed all of these transactions are now confirmed. It appears that this trade was never actually suffering from the failed transaction broadcast problem.

This now appears to be a "normal trade" that can be completed or cancelled per usual arbitration procedures.

Since I am not the arbitrator, you'll need to work with @keo-bisq directly on this within the Bisq app (and/or here via GitHub as necessary). But assuming you and your countparty are still willing to complete the trade, I don't see any reason why you couldn't from this point forward.

**Comment by cbeams** [comment]
> @cbeams The deposit transaction has been confirmed now. The maker transaction has not.

All three: maker, taker and deposit transactions have indeed been confirmed:

Maker: https://bitaps.com/6c9838158171e2c4211b0f9d0415d02de71c9c1738e2dd03261efc932e559f87
Taker: https://bitaps.com/e7b0a29ebb51b65ba4dbe2f4e4d175ec3302af3758f82dfae5ede297294a281c
Deposit: https://bitaps.com/7b57ebb2f9fbd7405b7a6b83bca90f7516f5e50f96d6ddd662304f0931e19d5a

**Comment by cbeams** [comment]
Closing as unnecessary. In the end this trade completed with a [payout transaction](https://bitaps.com/29e87b9d3f0060650e525b46c463bbff12b22b822f6d7fa8a84617cea1dda925) in which the buyer received the BTC trading amount, i.e. completed normally, requiring no refund.
