### ISSUE TITLE
Fee reimbursement for trade xxxx (no trade id but security desposit taken)

### ISSUE THREAD

**Issue by guizmoau** [bisq-network/support#522]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

 
![image-1765541670](https://user-images.githubusercontent.com/5398689/97845572-a3bb1480-1ce4-11eb-9de0-e606a79261c6.jpg)

![image-3490654470](https://user-images.githubusercontent.com/5398689/97845592-a9185f00-1ce4-11eb-903a-3a22b72fa620.jpg)

![image-4018465714](https://user-images.githubusercontent.com/5398689/97845616-b1709a00-1ce4-11eb-935d-cac2d7aabcc7.jpg)

![image-4012285987](https://user-images.githubusercontent.com/5398689/97845599-ac134f80-1ce4-11eb-8b9a-fdf6da74a847.png)

I want to get refund my security deposit.
I try to do a trade and when it was at step 2, I had to close my computer.
When I started bisq again, they were no trade active but my security has been taken..

What can I do to get my security deposit back for a trade that didn't happen ?

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by guizmoau** [comment]
this is the transaction id of the security deposit withdraw transaction

https://mempool.space/tx/625daacbd3a93f1569f6b46f5c2ca54a29531ff94c5cc21dfc16e783bea916d2

**Comment by Bisq-knight** [comment]
Can you reach us on keybase so we better understand what happened here?

https://keybase.io/team/bisq

**Comment by Bisq-knight** [comment]
Look for the #support channel
