### ISSUE TITLE
Fee reimbursement for trade HbQCWcpJ

### ISSUE THREAD

**Issue by agrizzlybear** [bisq-network/support#524]
![Screenshot 2020-11-02 at 11 12 23 pm](https://user-images.githubusercontent.com/73832641/97871945-f4705300-1d60-11eb-9e81-f301984d3d64.png)
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  f2b5e348ccbd99936d270ec0932c5a0aa44c3140382e13111aae7e23f8584cc8
Taker: 84a195c8eb44ea1635f13e236020c830eaab8419042440ce33c254bc406ce255
Deposit: c6630e2e1cbc6ba5133f3ba874b981ae525808babd953fabd0e87f4123543fb7
![Screenshot 2020-11-02 at 11 12 23 pm](https://user-images.githubusercontent.com/73832641/97872473-d0614180-1d61-11eb-8efc-06ee97fd0ee5.png)

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please edit all the personal information. Delete these images and reupload them without phone numbers and names

**Comment by pazza83** [comment]
Closing as no response
