### ISSUE TITLE
Fee reimbursement for trade HbQCWcpJ

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/support#525]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![2020-11-02 19_06_09-](https://user-images.githubusercontent.com/4820683/97903135-d72a8d00-1d3e-11eb-83d5-40598c566557.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  `f2b5e348ccbd99936d270ec0932c5a0aa44c3140382e13111aae7e23f8584cc8`
Taker: `84a195c8eb44ea1635f13e236020c830eaab8419042440ce33c254bc406ce255`
Deposit: `N/A`

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.4.2
>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @FKrauss 

Apologies for the late reply.

In order to consider reimbursement please can you post the screen shot again showing if you were the taker or maker.

Many thanks

**Comment by FKrauss** [comment]
hey @pazza83 . 

I've lost and recovered my Bisq instance multiple times after that and I'm confident I lost the trade details of this one. 

Then feel free to close this one and we'll consider it a micro donation to bisq ;)

**Comment by pazza83** [comment]
Many thanks
