### ISSUE TITLE
Fee reimbursement for trade 707714

### ISSUE THREAD

**Issue by ron87in** [bisq-network/support#526]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/73856827/97923464-a4bf6680-1d23-11eb-8543-5dc6aa8fce44.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  47c047a595be7ce7acf83ccc2f657c048c18a845dbbb15abe9a8e8b38920742e
Taker: n/a
Deposit: n/a

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Perhaps related to this issue, I made another trade after this trade mentioned above with the funds I was going to use for it. I accepted the offer to sell my BTC for this other trade and shut down BISQ. However, upon turning on BISQ the next day after my bank hadn't receive a payment for it, BISQ asked me to re-confirm a previous trade that I already confirmed the day before (trade ID: znynepll-36bc3bb3-4e30-49da-9e8a-8da246d02f96-142), and more worrying, the subsequent trade was no longer visible. This missing trade included the .01 BTC I was selling, a .006 BTC safety deposit, and ~.000304 BTC BISQ fee. None of this can be found anywhere on my BISQ platform and I am out more than $200 USD. I have since deleted my SPV and resynced - it is still not viewable. Is there anything you could do to find my missing BTC? Thank you for the help.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by ron87in** [comment]
Regarding my other notes - I have received funds from the next trade, but the trade is still not viewable on my Bisq client. The poor chap I am trading with sent his funds and I cannot confirm to release my bitcoin, and also, my security deposit is also lost. Can I possibly have some assistance with this?

**Comment by ron87in** [comment]
Hello, could I please have assistance with this? I tried to make a trade and the other trader asked why I did not complete transaction "R5HCO", which is what I believe the missing trade is.

**Comment by leo816** [comment]
hi, could you contact us via Keybase with regards to the other trades? my handle is @leo816 there and the support team can help too. regarding this issue (trade 707712) you are only missing the fees right?

**Comment by ron87in** [comment]
Hello and thank you. I will make a Keybase account and contact you directly. I am missing both the fees, and the security deposit from the missing trade. I also was unable to confirm the missing trade, so I am unsure if the person I was trading with ever got my bitcoin.

**Comment by huey735** [comment]
@ron87in Can you reach out to me. I'm huey735 on Keybase and your mediator.

**Comment by ron87in** [comment]
Of course, @huey735. I just sent you a message. Thank you for offering to help.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by pazza83** [comment]
closing as duplicate
