### ISSUE TITLE
Fee reimbursement for trade grcmorw

### ISSUE THREAD

**Issue by git953** [bisq-network/support#527]
![8989k](https://user-images.githubusercontent.com/73860689/97933743-89784980-1d6b-11eb-952d-f40f9c43bd60.PNG)

Maker:  2b035ada35458fa607664fc6655e32f1507b16ef32a62dc9e59b6034c77eb335
Taker: 3beb146b9d7bb03bfa2c51173ec5cc0b9604172e0a8e2a415db570a2d76c80be
Deposit: ee6535bc3f1881c04fa74b5a97b4cdca18decf8296d8057302185a15ee4dc990

Bisq version: 1.3.9

Other notes: The deposit is locked in the multisig wallet.
The trade shows up under failed trades. When I press ctrl + y it shows : Warning the trade cannot be completed, delayed payout transaction is null.

**Comment by RefundAgent** [comment]
This dispute is paid out by the Refund Agent and should be rejected by the DAO.
