### ISSUE TITLE
Add footer row with totals to repayment tracking report

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#528]
@jmacxx, could you modify `track-repayments.html` to add a footer row with totals and percentages as seen in the sketch below?

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/301810/98008935-5084b700-1df5-11eb-8e3c-ef86070ad211.png">

Could you also add a note indicating the date that the repayments began (i.e. the date of the earliest transactions against the listed addresses)? The intention of these changes is to be able to get an at-a-glance understanding of how much has been repaid so far, and roughly how much longer it'll take until repayment is complete.

/cc @ripcurlx who is responsible for the overall repayment project at https://github.com/bisq-network/projects/issues/31.

**Comment by jmacxx** [comment]
Done:
![image](https://user-images.githubusercontent.com/47253594/98066482-b2a4e280-1e1c-11eb-933e-d4d828006b9a.png)
