### ISSUE TITLE
Transaction stuck because very low minner fees set by bisq

### ISSUE THREAD

**Issue by bsqproblems** [bisq-network/support#530]
I sent the bitcoin from my wallet 8 hours ago using a decent miner fee " 447.5 sat/vB – 100,677 sat ($15.10)" When I check the transaction in mempool.space I see that there are two transactions, one small which is confirmed and another one with the amount I sent that is not confirmed and the miner fee is  17.0 sat/vB – 3,800 sat ($0.57). At this moment with this fee,  17.0 sat/vB – 3,800 sat ($0.57), THE TRANSACTION WEILL NEVER CONFIRM! 

WHAT DO I DO NOW?!

**Comment by bsqproblems** [comment]
Your soft/service is broken. Fix it, you mess with peoples money and nerves! This is not nice!

**Comment by bsqproblems** [comment]
And as it turns out you couldn't care less about our problems!

**Comment by Bisq-knight** [comment]
can you please join Keybase to get the appropriate support? 

https://keybase.io/team/bisq  (look for the #support channel)
