### ISSUE TITLE
Fee reimbursement for trade 46190

### ISSUE THREAD

**Issue by frrckfrr** [bisq-network/support#531]
![image](https://user-images.githubusercontent.com/74044224/98343358-00367080-2012-11eb-84c0-a845d3f88447.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  a99fc5a68dcaab99bb50df772c35dac370f8f14081f3e2f2a8f188e5b3c9fa09
Taker: 2b1bc916bcf5d13149035d2c73d70aa33a2b3164de1538960280722e1d93419d
Deposit: n/a

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

I've discussed this issue on Keybase #support channel, this was the recommendation I've got after providing screenshots:
_Well there's no deposit tx, this is a failed trade.
I guess that's why there's no trade id. Trade can't continue without deposit tx.
https://bisq.wiki/Failed_trades
Both of you can submit a trading fee reimbursement at https://github.com/bisq-network/support/issues/_

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by frrckfrr** [comment]
I also have the issue, that the funds still remain in my "locked" account balance.
![image](https://user-images.githubusercontent.com/74044224/98344479-97e88e80-2013-11eb-8a2c-9d02f3a302d9.png)


Do I need to do another SPV resync?

**Comment by frrckfrr** [comment]
Update from me - another SPV resync did not help and I still have locked funds in my account. Can anybody help?

**Comment by leo816** [comment]
hi, did you try contacting our support team on Keybase? did you open a mediation for that trade?

**Comment by frrckfrr** [comment]
@leo816 yes I submitted this request after discussing this on Keybase support channel

Unfortunately the app does not allow me to open mediation, as the deposit transaction ID is missing.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by frrckfrr** [comment]
@leo816 3Enx3T78nCAVfN6paqyouE31x6vkw6PDir
thanks

**Comment by frrckfrr** [comment]
@leo816 any update on this, please?

**Comment by pazza83** [comment]
Hi @leo816 does this now have all the info you need to make a reimbursement?

**Comment by leo816** [comment]
@frrckfrr sorry for the late response, Reimbursement will be made soon. Regarding your funds locked: if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades
