### ISSUE TITLE
Fee reimbursement for trade 46190

### ISSUE THREAD

**Issue by atpblas** [bisq-network/support#532]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Captura de pantalla 2020-11-06 a las 10 38 33](https://user-images.githubusercontent.com/66116505/98350912-45f83680-201c-11eb-96e2-71bf684f4928.png)

Maker: a99fc5a68dcaab99bb50df772c35dac370f8f14081f3e2f2a8f188e5b3c9fa09
Taker: 2b1bc916bcf5d13149035d2c73d70aa33a2b3164de1538960280722e1d93419d
Deposit: n/a

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.4.2

Provide the Bisq client version to help developers identify the causing issue.

Other notes:

I've discussed this issue on Keybase #support channel, this was the recommendation I've got after providing screenshots:
Well there's no deposit tx, this is a failed trade.
I guess that's why there's no trade id. Trade can't continue without deposit tx.
https://bisq.wiki/Failed_trades
Both of you can submit a trading fee reimbursement at https://github.com/bisq-network/support/issues/

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by pazza83** [comment]
Closing as no additional info provided.
