### ISSUE TITLE
Fee reimbursement for trade 23718758

### ISSUE THREAD

**Issue by JasekN** [bisq-network/support#534]
![Clipboard01](https://user-images.githubusercontent.com/74115606/98450467-34f31680-213d-11eb-9b90-5b1e8bb30832.png)
Maker: c70a19ea185828bc3903b2f913c3f2611fdaf432fb9299b833cb4a689caa62d7
Taker: f9fab0c120572675c84eee945ad71ab8dd1dd114c9ec4fba190e0f7a703dfcc9
Deposit:

Bisq version: v1.4.2

Other notes:

the trade is in an invalid mode, the deposit transoction is missing, please reimburse fees. thank you

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by JasekN** [comment]
17Yuqu7ReqLW8hCHnGUm8PRdZP8bxgPrBe

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
