### ISSUE TITLE
Fee reimbursement for trade tunxc

### ISSUE THREAD

**Issue by rogueserious** [bisq-network/support#535]
![Untitled3](https://user-images.githubusercontent.com/74083368/98455628-20f0ea00-2128-11eb-8ef9-de8a7ef9750d.png)

Maker:  fba5f698f269a43fe78e5b656c703999ae125995a988e508cfe52a5bac2783b1
Taker: 746ffb0c1b3e2edc6392c8a5a528dd7af7348dfed6a489a1fc277f007e248ad0
Deposit: N/A

Bisq version: v1.4.2

Other notes: The deposit transaction (the 2-of-2 multisig transaction) is missing error. Please reimburse the trade fee.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by rogueserious** [comment]
> 
> 
> please provide the btc address where you would like to receive the payout

bc1q7ve78szdt5nmrp3738u6r23ac7c5lqufq3aa6c

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
