### ISSUE TITLE
Fee reimbursement for trade etffra

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#536]
![grafik](https://user-images.githubusercontent.com/63785272/98533212-f798a100-2282-11eb-940d-a3d8732a55d8.png)

Maker:  5010fa68b6e5f7a870a5d41c683d12dcbc52547ba6d95116f4d74dea2f30c46c
Taker: 71b8f7ed9e378d137f21ba12f88487440e643e55fe9822c71706777408d68998
Deposit: 447b9d82bff0c9aa598edab091512ae98bab5a22ca3daa0c52a9d743252cc54a

Bisq version: 1.4.2

Other notes:

Please send the reimbursement to the BTC address 1MNSo8FTNVJe3ajqbqwucbREhBokvGyV23

I would also like to ask how can I move the trade to failed trades when there's no exclamation mark near the trade? Thank you.

**Comment by chimp1984** [comment]
Taker fee tx and deposit tx are not found on explorer. As maker fee tx was already spent (https://www.blockchain.com/btc/address/1LHbXMJajHGHb1wFeAaXoewH6A1JhuR8es) the trade is failed.

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833

**Comment by Akira45-0** [comment]
I have received 0.00010575 BTC reimbursement instead of 0.00043197 BTC. Why is that?

**Comment by leo816** [comment]
> I have received 0.00010575 BTC reimbursement instead of 0.00043197 BTC. Why is that?

yes, I reached out because I saw something wrong with the payout. Now solved.
