### ISSUE TITLE
Fee reimbursement for trade zkravjz8

### ISSUE THREAD

**Issue by jesgeo** [bisq-network/support#537]
Trade ID: zkravjz8-9e8c689e-0400-4a83-a9e9-c9157c03ad3d-142

![image](https://user-images.githubusercontent.com/5832932/98542513-f4a0af00-2288-11eb-9a2b-82a52fcf0991.png)

Maker: 765daf0efb0107c9cf6acb3a3371fdd2c5bb098ab93fedef8b5f884b93b5754a
Taker: b146c953a858bb47629c5028f99b477c917dbf3bd7ff6966b5e4106a3c6b7a8c
Deposit: N/A

Bisq version: 1.4.2

Reimburse to address: bc1qva8qszz45p3l2ar4pqx936u7scesgdadkm74rr

Thanks

**Comment by jesgeo** [comment]
@leo816 update? timelline?

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
