### ISSUE TITLE
Fee reimbursement for trade 0227356

### ISSUE THREAD

**Issue by thetimechain** [bisq-network/support#538]
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/74207976/98583941-c9b75a80-228a-11eb-85c8-80e2fbfd27d6.png)
Maker: 341da961666f530ac866c5bdb5482735677016dc9de14d529a5f73c307c01aa1
Taker: b192c10509cc7d594ed8a4c6b9ca791c9b1aec56783ca759d492cd8e468327d9
Deposit: 

Bisq version: 1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:  The deposit transaction (the 2-of-2 multisig transaction) is missing.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by thetimechain** [comment]
3Qepbv31xvYN6Si3PzvTZ6cYyE8tam14AF

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
