### ISSUE TITLE
Fee reimbursement for trade 0494188

### ISSUE THREAD

**Issue by brndnng** [bisq-network/support#539]
![screenshot](https://user-images.githubusercontent.com/21734054/98860598-ed68d500-2431-11eb-9ab7-1527bf2c49ab.png)

Maker: c10d6055fec0303bc5fdc86aea52ff4a68e075991051caaaf115c6c9ea8baf6c
Taker: e24fead657122e6a22155493a2a0d29f07256747560d9bc7490a60f9d88cfaca
Deposit:

Bisq version: 1.4.2

Other notes:
BSQ address: B1Yrw6krVP8Mjy4KQrUiqPfeHnpzZxaUNP

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by brndnng** [comment]
I paid my taker fee in BSQ. This is a btc address that I have bc1q3m9ue0cnck9m5n26gkutu6x7kj9sxdt4qht972

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
