### ISSUE TITLE
Fee reimbursement for trade lzudcf

### ISSUE THREAD

**Issue by rogueserious** [bisq-network/support#540]
![trader-fee3](https://user-images.githubusercontent.com/74083368/99016302-ae0eb700-250b-11eb-81cc-380ffbfd32cf.png)

Maker:  ee0158dc09f54f738e13d72faa98a267d4f3cfbed38aa1bf1463f1bd66ff7274
Taker: 83355a2391cdf55bef48506fe8e5fdbc8313176bcbfdca9cf8a84b098051f74b
Deposit: N/A

Bisq version: v1.4.2

Other notes: The deposit transaction (the 2-of-2 multisig transaction) is missing error. Please reimburse the trade fee.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by rogueserious** [comment]
> 
> 
> please provide the btc address where you would like to receive the payout

bc1q7ve78szdt5nmrp3738u6r23ac7c5lqufq3aa6c

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
