### ISSUE TITLE
Fee reimbursement for trade SwVysv9

### ISSUE THREAD

**Issue by threehill** [bisq-network/support#541]
![image](https://user-images.githubusercontent.com/74426290/99313522-fb6a8b80-285f-11eb-8b16-d2c986608940.png)

Maker: 92d0a0b007540acc42cb2f6562cc3c4d759607efc90183b1dacde3c436815151
Taker: a80e3f83ff2aa3e6056129f8d1c139f812b1378a495de1cd9b56f936456413b3
Deposit: 3af03d2dd50ba9930368e57b26c3d6f9c8e5f98bb7b180ee56c6c13d8456e1b1

Bisq version: 1.4.2

**Comment by Bisq-knight** [comment]
Was this trade cancelled or did you complete it?

**Comment by threehill** [comment]
This is a failed trade otherwise I wouldn't ask for reimbursement. I have also locked funds in this failed trade and the mediation is ongoing for that issue.
Mediator node address: sjlho4zwp3gecspf.onion:9999

**Comment by threehill** [comment]
The mediator on bisq (node address: sjlho4zwp3gecspf.onion:9999) is suggesting manual payout (for the locked funds). It seems to be a very complicated solution for me. Is there any chance to solve this problem in an other way? (An other mediator suggested "batch transactions" in a similar case).

**Comment by threehill** [comment]
I want to emphasize that the lost fee is the smaller problem, the main problem is locked funds in this failed trade.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by threehill** [comment]
I´m sending an adress to you on Keybase.

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
