### ISSUE TITLE
Fee reimbursement for trade 23718758

### ISSUE THREAD

**Issue by threehill** [bisq-network/support#542]
![image](https://user-images.githubusercontent.com/74426290/99313287-8e56f600-285f-11eb-8c7c-29408023df41.png)

Maker: c70a19ea185828bc3903b2f913c3f2611fdaf432fb9299b833cb4a689caa62d7
Taker: f9fab0c120572675c84eee945ad71ab8dd1dd114c9ec4fba190e0f7a703dfcc9
Deposit: 476d5b5baddbf350f57b497cd12be67f84dd8cd39f8cb298dfb8ad83a1c96dc3

Bisq version: 1.4.2

**Comment by threehill** [comment]
I have locked funds in this failed trade. It's not just about trade fee.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by threehill** [comment]
I´m sending an adress to you on Keybase.

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
