### ISSUE TITLE
Fee reimbursement for trade FGRGWC-e542ac48-5ede-4d3c-a516-dad9c23b8e88-142

### ISSUE THREAD

**Issue by Baiskey** [bisq-network/support#543]
SCREENSHOT HERE

![image](https://user-images.githubusercontent.com/25394185/99303013-8479c680-2850-11eb-886a-c32076aaf6f6.png)

Maker:  0130c42f3c62791a422b43219647aa7a68cff70e7ea150debc81c90bd07e8708
Taker: N/A
Deposit: N/A

Bisq version:

v.1.4.2

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by calvaquality** [comment]
Hi @leo816 

bc1q0t6u3at42wc6uu90neyl4eunhpua38f8kmnkhv

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
