### ISSUE TITLE
Fee reimbursement for trade QALCMH

### ISSUE THREAD

**Issue by threehill** [bisq-network/support#544]
![image](https://user-images.githubusercontent.com/74426290/99312823-e6d9c380-285e-11eb-8219-f04c43d2d5de.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: d2c7562313c614ff939e307e2595fbeecd060c28ced6e988964fe112e94f1bf0
Taker: 4d0c9f3ae65419cf966ddb504b776086f5793931511b575642061efc2a61d5b0
Deposit: 71429f7bfbb7c4563cb561f19390e525ad5b569c55669faa2675c9994f68f8b3

Bisq version: 1.4.2

**Comment by threehill** [comment]
I have locked funds in this failed trade. It's not just about the trade fee.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payout

**Comment by threehill** [comment]
I´m sending an adress to you on Keybase.

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
