### ISSUE TITLE
Fee reimbursement for trade qrqAQJ

### ISSUE THREAD

**Issue by coolcoconut123** [bisq-network/support#545]
![image](https://user-images.githubusercontent.com/74676509/99568039-d5abc680-29c6-11eb-881f-ac6a23bd7c5f.png)

"the delayed payout transaction is missing" 

Deposit Transaction ID: 93a71f254faa8ae51b84ce93f8b0fcd49cdcbd2f0821dd997172313438fdd207

**Comment by coolcoconut123** [comment]
Q: If nothing happens in the next 23 hours, 46 minutes, is the security deposit refunded?

**Comment by coolcoconut123** [comment]
![image](https://user-images.githubusercontent.com/74676509/99568617-95007d00-29c7-11eb-96b5-b9eec23c4462.png)

**Comment by coolcoconut123** [comment]
Delayed Transaction ID still highlighted. Reinbursement is still required for the deposit.

**Comment by leo816** [comment]
did you open a mediation ticket? please provide all the information as all the other fee reimbursements as well as your preferred btc address

**Comment by coolcoconut123** [comment]
Yes, I just checked and it says to open and accept/reject - I just went now and there was no option to accept/reject anything, moved back to failed trade. 

![image](https://user-images.githubusercontent.com/74676509/100674269-cb8dae80-335c-11eb-9ddb-c240d4522f26.png)

" Ticket closed on Nov 19, 2020 8:50:41 PM
Mediator node address: sjlho4zwp3gecspf.onion:9999

Summary:
Trade ID: qrqAQJ
Currency: GBP
Trade amount: 0.0050 BTC
Payout amount for BTC buyer: 0.0060 BTC
Payout amount for BTC seller: 0.0110 BTC

Reason for dispute: Other

Summary notes:
delayed payout tx null

-----BEGIN SIGNATURE-----
302d02147e4442bc34bd866cf45fb839abdefdabc3d8c2cc02150080607c86023238836ba97b9427c8b78d55dd6cee
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator "

Info from screenshot at beginning of thread in text: 

Trade ID: qrqAQJ-829ff3c2-060a-4c9d-a949-800359a2f438-142
Trading peers onion address: piklfjo4bb4eqcfh5iqsb7plc4ue6y2sy6y45d72lw3uwnxvpzleixyd.onion:9999

Maker: 11c386b8a3a6f0a396f582ad23204208f64344e860697891167061d4380c55a6
Taker: 017e8143fbd53b4acdb791fa956429a01401deeb631d6a5a0382d943e16218e5
Deposit ID: 93a71f254faa8ae51b84ce93f8b0fcd49cdcbd2f0821dd997172313438fdd207

Funds locked: 0.0060 BTC
Preferred btc address: 12h6eL9VgntYNxFVZLGY2VA4yminPjenuz

**Comment by coolcoconut123** [comment]
@pazza83 My funds are still locked? I have provided the information and a preferred btc address. 

Is there a delay or something?

**Comment by pazza83** [comment]
Hi @coolcoconut123 looks like your mediator for this trade is @leo816 

@leo816 do you know the status of this trade.

It appears that the funds in the multisig have already been paid out. I assume the trade was cancelled and @coolcoconut123 will have received there deposit back?

I imagine any locked funds are a result of a GUI error?

**Comment by coolcoconut123** [comment]
Hey, not to be that guy but it's still locked... 

If there's a GUI error as @pazza83 has mentioned, how can I correct this issue? Bisq is updated and the preferred BTC address I gave is empty. 

![Locked Funds Nov 2021 message](https://user-images.githubusercontent.com/74676509/141862934-74ae01f7-9908-44c6-89f6-63a1db1f75ef.jpg)
![Locked Funds Nov 2021](https://user-images.githubusercontent.com/74676509/141862936-345ffeb6-a7aa-4614-8913-e4a33983a4cf.jpg)

**Comment by pazza83** [comment]
Hi @coolcoconut123 

I am not seeing the funds as locked

Looks like it paid out on 18.11.20 and was then used to fund another trade the next day:

https://mempool.space/address/12KqPdUM6gXTbZgCSVQ8MDSpHQfqZ96Hte

**Comment by coolcoconut123** [comment]
I’ve not traded since the first lock. Everytime I’m using bisq I get the same message, locked funds. The address I provided the locked funds to be sent I haven’t seen. 

Did the transaction repeat once it was released the first time thus causing it to lock again? 

Any idea what I can do?

**Comment by coolcoconut123** [comment]
![image](https://user-images.githubusercontent.com/74676509/212399072-06bdf9ea-eb24-42db-8893-e6c5035104ba.png) (Image taken on (13/01/2023)

This message everytime I open Bisq ever since, even after this was closed. 

@pazza83 could you or @leo816 be able to look into this please. Thanks
