### ISSUE TITLE
Fee reimbursement for trade qrqAOJ

### ISSUE THREAD

**Issue by boyofbow** [bisq-network/support#546]
>_The part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._
qrqAQJ-829ff3c2-060a-4c9d-a949-800359a2f438-142
maker fee trans 11c386b8a3a6f0a396f582ad23204208f64344e860697891167061d4380c55a6
taker fee trans   017e8143fbd53b4acdb791fa956429a01401deeb631d6a5a0382d943e16218e5
deposit .0060 BTC

**Comment by boyofbow** [comment]
![99568617-95007d00-29c7-11eb-96b5-b9eec23c4462](https://user-images.githubusercontent.com/20277263/99575966-4c4dc180-29d1-11eb-813b-14b827c32df4.png)

**Comment by coolcoconut123** [comment]
Hi, is this trade this: https://github.com/bisq-network/support/issues/545 ??

If so, the Trade ID is qrqAQJ not qrqAOJ   (Q not O)

**Comment by boyofbow** [comment]
yes you are correct

**Comment by leo816** [comment]
please provide all the information as other fee reimbursements, as well as your preferred btc address.

**Comment by pazza83** [comment]
Closing as no additional info provided.
