### ISSUE TITLE
Fee reimbursement for trade gpRKlgID

### ISSUE THREAD

**Issue by SatStackr** [bisq-network/support#547]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screenshot](https://i.imgur.com/2yrI7pH.jpeg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  82494edf090104fdc7e0b36243135ea1bc57e224bbdbbc0ecfb4a1d9dae422ae
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: (none)

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by SatStackr** [comment]
> please provide the btc address where you would like to receive the reimbursement

Much appreciated, that would be `bc1qnzyenl7z8cfn9k4v7pjyrkw4ah8jnpu2j0n4le` please.
Thanks in advance.

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
