### ISSUE TITLE
BTC transaction unconfirmed for more than 10 hours!

### ISSUE THREAD

**Issue by bbqqqt1er000** [bisq-network/support#548]
BTC transaction unconfirmed for more than 10 hours! How can I get my coins back? The trade does not make any sense at this point!

**Comment by MwithM** [comment]
When an offer starts, Bisq uses a fee estimation to try to get into the next couple blocks, but BTC when it will be confirmed depends on miners finding blocks and demand for block space.
Once the trade gets the 1st confirmation, you'll have to complete it.
