### ISSUE TITLE
Trade fegnXbj - BTC seller is unable to confirm payment

### ISSUE THREAD

**Issue by huey735** [bisq-network/support#549]
See https://github.com/bisq-network/bisq/issues/4748 for overall description of the issue.

To add to the above, the BTC seller here apparently also can't send confirmation that they've accepted the mediation payout suggestion. They say that they get a message saying `You have accepted the mediators suggestion. Waiting for peer to accept as well`.

BTC seller-maker view
![btcSellerMaker-mediationAcceptedMessage](https://user-images.githubusercontent.com/44140017/99806409-e75fac00-2b35-11eb-9c4d-1a34ffc172ab.png)

BTC buyer-taker view
![btcBuyerTaker-mediationAcceptedMessage](https://user-images.githubusercontent.com/44140017/99806459-f47c9b00-2b35-11eb-9676-3dab6ffbe670.JPG)

**Comment by cyplo** [comment]
got exactly the same problem, also accepted mediation and the other side can't get the payout
