### ISSUE TITLE
Fee reimbursement for trade 98K01

### ISSUE THREAD

**Issue by mateuszmp** [bisq-network/support#551]
![image](https://user-images.githubusercontent.com/19210834/99919982-fbb3cc80-2d20-11eb-8e89-ecc32352e031.png)

Maker: ba06f9caa28fde41122a4e0a28be6f0a99eb86af554387428bb6726369de9bad
Taker: 896c4f3a698315ef4aaed04bd496dbfd548f9077d31ce5ee82cbeb8869491e44
Deposit: N/A failed to announce

Bisq version: 1.4.2

Other notes:
Mediator said after resyncing SPV the trade should appear under failed trades. It does not. It is still under open trades.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by mateuszmp** [comment]
bc1qe70jj78327p87gx6a2yc4p850j9kz3rgh8weck

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
