### ISSUE TITLE
Fee reimbursement for trade omjkdj 

### ISSUE THREAD

**Issue by haritarak** [bisq-network/support#552]
Key base --- huey735

![Captura de pantalla 2020-11-23 a las 22 12 59](https://user-images.githubusercontent.com/74642609/100016582-efd81100-2dd9-11eb-8c31-5f5aed3c8446.png)
![Captura de pantalla 2020-11-23 a las 22 17 31](https://user-images.githubusercontent.com/74642609/100016596-f36b9800-2dd9-11eb-82cc-661d6dae6a5f.png)

>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: "offerFeePaymentTxId": "693a34de17b0b3a466ab91db3e665bbad3c65e0980ff57f90a96acb362e3dad1", 
    "versionNr": "1.4.2",
Taker: "takerFeeTxID": "92e1ea43fbd7e344adf77fe347df57346354002f9bbf6611fb0685e290a62a1d",
version at the moment of the contract 1.4. version at this moment 1.5.0
Deposit: "buyerSecurityDeposit": 600000,
    "sellerSecurityDeposit": 600000
ID deposit: eb426c219208d4e209c14599d0c5282e9bd5fcd412ad436f0b9185ae1c5afbb2

Hi huey735, thanks for your help, i hope ist everything ok
>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copie
>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:d to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

> @haritarak You need to fill in the information regarding the Maker fee, Taker fee and Deposit transaction ids and your Bisq version. Also remove everything after the trade id from the title of the issue. You can mention me in the body of the issue.

It is giving an error of fail tx, in others it happened the same issue but i did tx the amount and at the end, depite the mistake trade was completely. I did not complete this one because the error appears before of been able to do the payment.
![Captura de pantalla 2020-11-26 a las 15 54 45](https://user-images.githubusercontent.com/74642609/100365457-d0223200-2fff-11eb-976f-b90a5eef9c4d.png)

**Comment by huey735** [comment]
@haritarak You need to fill in the information regarding the Maker fee, Taker fee and Deposit transaction ids and your Bisq version.

**Comment by haritarak** [comment]
Hi, I left all the info I think is what you been asking for. Hope everything is oki
Thanks

**Comment by huey735** [comment]
@haritarak Please keep it simple. Look at other issues in this repository for reference. It should look something like:

```
Maker:  693a34de17b0b3a466ab91db3e665bbad3c65e0980ff57f90a96acb362e3dad1
Taker: 92e1ea43fbd7e344adf77fe347df57346354002f9bbf6611fb0685e290a62a1d
Deposit: eb426c219208d4e209c14599d0c5282e9bd5fcd412ad436f0b9185ae1c5afbb2

Bisq version: <your Bisq version>

And the title doesn't need to mention Keybase or me. `Fee reimbursement for trade omjkdj` is enough.
```

**Comment by haritarak** [comment]
Maker:  693a34de17b0b3a466ab91db3e665bbad3c65e0980ff57f90a96acb362e3dad1
Taker: 92e1ea43fbd7e344adf77fe347df57346354002f9bbf6611fb0685e290a62a1d
Deposit: eb426c219208d4e209c14599d0c5282e9bd5fcd412ad436f0b9185ae1c5afbb2

Bisq version: <your Bisq version>1.5.0

Many Thanksss

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by haritarak** [comment]
bc1qdkc03u2nlvkx85yft4t98w3sleyvuer3x75mxq

Thanks for the support given

**Comment by haritarak** [comment]
oki thanks

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
