### ISSUE TITLE
Trade ID ysnixazi

### ISSUE THREAD

**Issue by Hudhuranfushi** [bisq-network/support#553]
Ticket closed on Nov 23, 2020 10:06:49 PM
Mediator node address: apbp7ubuyezav4hy.onion:9999

Summary:
Trying to recover my trading fee as a taker buyer after there wes an issue with the multi-sig

Trade ID: ysnixazi
Currency: GBP
Trade amount: 0.01 BTC
Payout amount for BTC buyer: 0.0060 BTC
Payout amount for BTC seller: 0.0160 BTC

Reason for dispute: Bug

Summary notes:
Problem with the delayed payout tx. traders were instructed to ask for a fee reimbursement on github and trade will be cancelled

-----BEGIN SIGNATURE-----
302d0214523522f49d004a8722f021a5b7c6f8fac1e12b3e02150083dbfc1e97a210dfa57b1df540daa57abc93ebe8
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator

**Comment by huey735** [comment]
Please create a new issue following the [Reimbursement template](https://github.com/bisq-network/support/issues/new/choose).
Take a look at the other issues in [this repository](https://github.com/bisq-network/support/issues) for guidance.
