### ISSUE TITLE
Fee reimbursement for trade ysnixazi

### ISSUE THREAD

**Issue by Hudhuranfushi** [bisq-network/support#555]
ysnixazi

![IMG_E5128](https://user-images.githubusercontent.com/49436236/100091705-e2a83a00-2e4c-11eb-9e82-0231f64b821c.JPG)

Maker: 9ca7c750d162bf67126aaa90d41f49e3bde1f8cc88be479f57a3857a1a6ff332
Taker: 8295fbacc0d3fb4f5051a8ff63b64a3772c1e379a98ae83dfbfc5296d4f8576f
Deposit: c2ef5a95882d8c3b34188ff60c244efe42ec7db9e8c59179958dbb37c62e6ab1

Bisq version: 1.4.2

Other notes:
Ticket closed on Nov 23, 2020 10:23:19 PM
Mediator node address: apbp7ubuyezav4hy.onion:9999

Summary:
Trade ID: ysnixazi
Currency: GBP
Trade amount: 0.01 BTC
Payout amount for BTC buyer: 0.0060 BTC
Payout amount for BTC seller: 0.0160 BTC

Reason for dispute: Bug

Summary notes:
Problem with the delayed payout tx. traders were instructed to ask for a fee reimbursement on github and trade will be cancelled

-----BEGIN SIGNATURE-----
302c02144bf925a3555b07a3b439fbaf59ad03600dd7a5bb02145236ce4600b8b940527283625a81acab6a585f3d
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by Hudhuranfushi** [comment]
Ok thanks

**Comment by leo816** [comment]
payout was made correctly, reimbursement is not justified. if your deposit is locked: "if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades"

**Comment by leo816** [comment]
Reimbursed with #862
