### ISSUE TITLE
Request to reimburse trade fee - trade id - emnjpkfw

### ISSUE THREAD

**Issue by airfrank** [bisq-network/support#556]
Hi! I got a trade with a protocol error.

"The deposit transaction /the 2-of-2 multisig transaction) is missing.
Without this tx, the trade cannot be completed. No funds have been locked, but your trade fee has been paid. You can make a request to be reimbursed the trade fee here: github.com"

trade id: emnjpkfw-a961b5d0-a41e-43ba-8d6a-1406eced6f71-137

thanks and best regards

**Comment by huey735** [comment]
Please create a new issue following the Reimbursement template.
Take a look at the other issues in this repository for guidance.
Reach out to your mediator for this trade: https://bisq.wiki/Finding_your_mediator.
