### ISSUE TITLE
Fee reimbursement for trade emnjpkfw

### ISSUE THREAD

**Issue by airfrank** [bisq-network/support#557]
![grafik](https://user-images.githubusercontent.com/5376944/100095603-0d00f400-2e5b-11eb-95b9-fbc1336202b3.png)

Maker: cb8c5d26f55e60d67495c265201b431a353863457111dda5ad0fc4dbb036c990
Taker: 17356044b8d84683010c99f4617b4a665af9fdf5f6d88862a5c20d9fb09649c7
Deposit: missing

Bisq version: 1.4.2

Other notes:

Ticket closed on Nov 02, 2020
Mediator node address: a56olqlmmpxrn5q34itq5g5tb5d3fg7vxekpbceq7xqvfl3cieocgsyd.onion

Summary:
Trade ID: emnjpkfw
Currency: EUR
Trade amount: 0.0260 BTC

Reason for dispute: The trade protocol encountered some problems.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by airfrank** [comment]
bc1qqtn7v4zk5mxca30tsv4hcr5vqwwxh7r5kyyy44

thanks for your time and help!!

**Comment by Hudhuranfushi** [comment]
1DpM2VkWyts41uJAfhyQFmbKfSii53NAoW 
Many thanks 👍

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
