### ISSUE TITLE
Fee reimbursements did not work

### ISSUE THREAD

**Issue by ceilican** [bisq-network/support#560]
The fee reimbursements from the following issues did not work:

* https://github.com/bisq-network/support/issues/477
* https://github.com/bisq-network/support/issues/476
* https://github.com/bisq-network/support/issues/475
* https://github.com/bisq-network/support/issues/474
* https://github.com/bisq-network/support/issues/473
* https://github.com/bisq-network/support/issues/472

Although I can see that the reimbursement transaction sent funds to addresses that are associated with the failed trades, I can see neither the addresses nor the reimbursed funds in my Bisq wallet.

Could you anyone please help?

**Comment by leo816** [comment]
please create them again and provide the btc address where you would like to receive the reimbursement
