### ISSUE TITLE
Fee reimbursement for trade ui9nf

### ISSUE THREAD

**Issue by IronBitcoinHodl** [bisq-network/support#562]
![image](https://user-images.githubusercontent.com/73696029/100241252-c92ded80-2f33-11eb-8360-dfe879c7b5d5.png)

Maker: dee6309022bf42b7241fc915656b33afec467cc257985238f442337683dc702a

Bisq version: v1.5.0

Other notes:

The trade exited with the following error:

![image](https://user-images.githubusercontent.com/73696029/100241335-e2cf3500-2f33-11eb-847d-4b2804aa0912.png)

Did not copy log, sorry.

Please reimburse the taker fee. Thanks

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by IronBitcoinHodl** [comment]
Hello,

please reimburse to the following address:

3PCz5aJVye3M79WquPVe1xPG5dBAQ3tJsX

**Comment by leo816** [comment]
please provide all the details from the trade, were you the maker or the taker?

**Comment by pazza83** [comment]
Closing as no additional info provided.
