### ISSUE TITLE
Fee reimbursement for trade qcigqSLD

### ISSUE THREAD

**Issue by appideias** [bisq-network/support#563]
SCREENSHOT HERE
![Image of the Issue](http://gestobom.com/images/bisq%20qcigqSLD-b53feea9.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  eb4ae2d26a868d248b9cc19ab88e298bfbdcd9132e97f501fc31e2246f2a190e
Taker: ...........
Deposit: ..........

Bisq version:

v1.5.0

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by appideias** [comment]
Thanks!

1FWHVKhapae1wHVx9C3bWmAtnvJvTwUg2L

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
