### ISSUE TITLE
Case 37259e - Bank doesn't recognize sort code for Faster Payments

### ISSUE THREAD

**Issue by huey735** [bisq-network/support#564]
### Description:

BTC buyer's bank doesn't recognize BTC seller's sort code for Faster Payment. When verified against [Faster Payments' official Sort Code Checker](https://www.fasterpayments.org.uk/sort-code-checker) it came back as valid. Which leads me to believe that this is a problem on the BTC buyer's bank side.

### Started at:

2020-11-24 07:25

### Github-issue:

Not a Bisq issue

### Bisq version:

Not a Bisq issue

### Device or machine:

Not a Bisq issue

### SCREENSHOTS HERE

![sortCodeChecker](https://user-images.githubusercontent.com/44140017/100276649-c940e400-2f59-11eb-94eb-04a8e840a5a7.png)

### Solution:

I made a payout suggestion returning the funds to both traders and suggested both to request reimbursement for fees spent on the trade.

**Comment by huey735** [comment]
@bisq-network/support 
1. Should Bisq reimburse the trading fees given that it’s not a Bisq issue?
2. How to avoid this issue given that it’s likely to repeat?

**Comment by pazza83** [comment]
> * Should Bisq reimburse the trading fees given that it’s not a Bisq issue?

- Yes for Buyer
- No for Seller

> * How to avoid this issue given that it’s likely to repeat?

- Create a policy for what happens to security deposits in the event of failed trades make this available to traders and part of the trading protocol. 
- Create a policy for what happens to fee reimbursements in the event of failed trades make this available to traders and part of the trading protocol. 
- Add requirement to Faster Payments wiki that sort codes must be verifiable against Faster Payments' official Sort Code Checker

**Comment by leo816** [comment]
> Create a policy for what happens to security deposits in the event of failed trades make this available to traders and part of the trading protocol.
Create a policy for what happens to fee reimbursements in the event of failed trades make this available to traders and part of the trading protocol.
Add requirement to Faster Payments wiki that sort codes must be verifiable against Faster Payments' official Sort Code Checker

@pazza83 was this implemented? and can this be closed?

**Comment by pazza83** [comment]
Hi yes these have been implemented.

Closing.
