### ISSUE TITLE
Fee reimbursement for trade 68507

### ISSUE THREAD

**Issue by SatStackr** [bisq-network/support#565]
![Screenshot](https://funkyimg.com/i/38URb.png)

Maker:  e560e5e4717f95f55c6e51fdba6fc6e2c5ae3b6baab330b5b4af08ef23f9692f
Taker: N/A
Deposit: N/A

Bisq version: 1.5.0

Other notes: (none)

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the reimbursement

**Comment by SatStackr** [comment]
> please provide the btc address where you would like to receive the reimbursement

Thanks, `bc1q45838w5uyl8xksx3slx2c6jqg2rxhzpx47t3fe`

**Comment by leo816** [comment]
Will be reimbursed with #576

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
