### ISSUE TITLE
Fee reimbursement for trade EQJPPNWQ

### ISSUE THREAD

**Issue by Strata13** [bisq-network/support#568]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/75181250/100524438-d807e080-317d-11eb-9633-0eeb15937de2.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 56e227d69b918c94c1e52335d2101aaaeb5c332bcf6f3ba46ae8b053840e4bfa
Taker: ca32ca4138330a4b994fa0825eb00398538bb72ccb1221c5de49af06d488d468
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the btc address where you would like to be reimbursed

**Comment by Strata13** [comment]
bc1qza39p9lhzl6pv6t7tlw9jt0qhdhpx8f9nzulf9

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
