### ISSUE TITLE
Fee reimbursement for trade ZDXQES

### ISSUE THREAD

**Issue by mylesofsmiles** [bisq-network/support#569]
> The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash).

![Screenshot from 2020-11-28 16-09-50](https://user-images.githubusercontent.com/49426214/100528686-30e27380-3194-11eb-83d0-5da9c05c22dc.png)

> The screenshot from the Bisq client must have the Trade ID, Deposit, Maker and Taker TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). Do not upload images where sensitive private data is visible!

Maker: 91b374df2ac55cf4555315f1437f407b4f6d38855a8aa8dd2f073f42faf08385
Taker: N/A
Deposit: N/A

> A reimbursement request has to contain textual representation of Maker, Taker and Deposit TXIDs (copy them from the client to the issue). All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid

Bisq version: 1.5.0

> Provide the Bisq client version to help developers identify the causing issue.

Other notes:

> Issue #197 can be used as a good example of a correct reimbursement request.

**Comment by leo816** [comment]
please provide the btc address where you would like to be reimbursed

**Comment by mylesofsmiles** [comment]
bc1qfa3lr7qus55rpfcmhkkhslwrjflx9js6wrkdz6

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
