### ISSUE TITLE
Fee reimbursement for trade 67967110

### ISSUE THREAD

**Issue by takashifujimoto** [bisq-network/support#570]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/8863377/100559560-b9d2db00-3278-11eb-9094-5e320d9627ae.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  e40c2a7ad9fd4cbd0c9c46a44cbd9ee3e85e135b53f5a0521000b856bf7dd43c
Taker: 602d69f796878f016fd8f1a7cc15cb92b48bb7922664cee7b54f8b31685b488f
Deposit: ae3c333196d146f08d4179a5d2e2013bddf5fff580432b73d40cdd6a3438d8c2

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:  The support Date Nov 27, 2020 (:11:37 PM

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the btc address where you would like to be reimbursed

**Comment by pazza83** [comment]
Closing as no additional info provided.
