### ISSUE TITLE
Reimbursement for trade IDOIJOHR

### ISSUE THREAD

**Issue by senfisura** [bisq-network/support#572]
>_The IDOIJOHR part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/75276345/100659309-34f6c880-332f-11eb-9516-676f479b9afd.png)
![image](https://user-images.githubusercontent.com/75276345/100659471-6f606580-332f-11eb-826d-61838c483666.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  89e92ff57770bc47c0c64822693d67b1869aa65050cad79afb050a154ab70a72
Taker: 9afced2217d9f96512cda3b95cd76b741bac0c16cd14698ebcd98090dc0b9158
Deposit: 27596111b68d206ac98dd4f17fefcc82e9457bdfdfbeb8a160a11c6e50b8a457

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v.1.4.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

I paid Bitcoin to the Seller and I need to be refunded.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by senfisura** [comment]
The trade amount is 0.01 BTC

**Comment by huey735** [comment]
Bisq used a previous Payout transaction from the offer taker as the Deposit transaction, resulting in a failed trade. From the BTC buyer point of view, the Deposit transaction had been confirmed and they could start the payment. They did so.
The other trader remained unresponsive to all my attempts and I'm not sure if they did in fact get the Mediation message.
So this is a special case where the BTC buyer is owed the trade amount (and only the trade amount, no fees).

**Comment by leo816** [comment]
Then the title should be changed to just "Reimbursement for trade ..." and the reimbursement should be done through the DAO. I'm only in charge of fee reimbursements.

**Comment by senfisura** [comment]
I changed the title as requested

**Comment by huey735** [comment]
This has been solved by me.
