### ISSUE TITLE
Fee reimbursement for trade Q4OiP

### ISSUE THREAD

**Issue by hadilosacrat** [bisq-network/support#573]
Hi,  I was buyer of bitcoins. I sent bitcoins to an escrow account. Trade was later cancelled, I need to get 0.0175 bitcoin refunded, currently locked in an escrow account.

![image](https://user-images.githubusercontent.com/75205282/100673990-56ba7480-335c-11eb-9acf-0ff1d04286e8.png)

Trade ID: Q4OiP-4d4d22b4-6681-44eb-b147-0997aa579a05-142
Security deposit: 0.0175
Maker fee trx ID: cea5389098d85180eadb15d9a1c718075057a6f2d6551025385f25f137f4c3ab
Taker Fee trx ID: 93b973ae8f486ad0cdbb7f2b0eaa86872f34baa48856bd1f0dddc07505322205
Deposit trx ID: d301daba32aa04b06e28cc075f8c62f9f0fe4c38b4e00cff80c58ce4151eb1d6
Delayed payout trx ID: f52fb6460372c818da892a516e946093072564afe7482dbc612835772822b2a1

Bisq version: 1.5.0

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request.

**Comment by leo816** [comment]
please provide btc address where you would like to receive the payout

**Comment by pazza83** [comment]
Closing as no additional info provided.
