### ISSUE TITLE
Fee reimbursement for trade FVWBISU

### ISSUE THREAD

**Issue by rogueserious** [bisq-network/support#574]
![fvwbisu](https://user-images.githubusercontent.com/74083368/100807564-6763fc80-33e7-11eb-9fdb-9d7d19ac782a.png)

Maker:  c68b54ca0b54c2638408ec860219cf5380e42078ea4eeb3624b5635d167a6ddc
Taker: 81ec6f43c8b932e0ed35420b047933e456642a5d7799a157826d576786790e8e
Deposit: N/A

Bisq version: v1.5.0

Other notes:

**Comment by pazza83** [comment]
Hi @rogueserious apologies for the late reply.

I can see you have lost fees as a result of this failed trade.

Please can you provide a BTC address for compensation.
