### ISSUE TITLE
Fee reimbursement for trade ZDXQES

### ISSUE THREAD

**Issue by rogueserious** [bisq-network/support#575]
![zdxqes](https://user-images.githubusercontent.com/74083368/100807790-cc1f5700-33e7-11eb-9601-e76137ed7327.png)

Maker:  91b374df2ac55cf4555315f1437f407b4f6d38855a8aa8dd2f073f42faf08385
Taker: N/A
Deposit: N/A

Bisq version: v1.5.0

Other notes:

**Comment by pazza83** [comment]
Hi @rogueserious apologies for the late reply.

As you were the taker for this trade and no taker transaction took place you have not lost any fees for this failed trade.

Let me know if you have any questions.
