### ISSUE TITLE
Fee reimbursement for trade mpSMJFhz

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#579]
SCREENSHOT HERE
![grafik](https://user-images.githubusercontent.com/63785272/100902498-38bc5380-34c5-11eb-8903-f4c67fda0081.png)

Maker:  4e052726b1508a983fc3dccfdd943c2cca6f784a7347288617b4942f96535a4c
Taker: 973ff449eeec98ddd9e7e894c65e5fce4e3d038b2c7f404896e25c354c7bbf76
Deposit: ..........

Bisq version: 1.5.0

Other notes: Please refund to bc1q5e9lh6l82fv82qgk74hxhtepd0znt6ckxeevs9

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833

**Comment by Akira45-0** [comment]
I have received 0.0001708 BTC instead of 0.00015925 BTC. How are the reimbursement values computed?
