### ISSUE TITLE
Fee reimbursement for trade FVWBISU

### ISSUE THREAD

**Issue by Kariba1812** [bisq-network/support#580]
>_The FVWBISU part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/75386018/100908993-025ce500-3481-11eb-82a6-45bf15a555b7.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  c68b54ca0b54c2638408ec860219cf5380e42078ea4eeb3624b5635d167a6ddc
Taker:  81ec6f43c8b932e0ed35420b047933e456642a5d7799a157826d576786790e8e
Deposit: b29f63d50177465e94972e11f479af85b3ec8120c7d3162990c090b9a685a2f3

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v.1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide a btc address where you would like to receive the payment

**Comment by Kariba1812** [comment]
bc1qcg6w3lh85w7kgrawmtsutpyspsqsnckegu0acu


Thank you!

**Comment by Kariba1812** [comment]
** I had the same issue with the below trade and opened a fee reimbursement.  Any chance you can send them both at the same time?  Thank you!

Fee reimbursement for trade 09944980 #586

**Comment by pazza83** [comment]
Hi @Kariba1812 

This trade appears successful as the Deposit Tx id confirmed: https://mempool.space/address/bc1q2m7ge2yq269m2cztsvsxyf9gzhauk7txwajlse

Therefore closing. Let me know if I am missing anything.
