### ISSUE TITLE
Fee reimbursement for trade pgnmDL9

### ISSUE THREAD

**Issue by Kariba1812** [bisq-network/support#581]
>_The pgnmDL9 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/75386018/100911366-fa527480-3483-11eb-900f-f3ed344bcad3.png)
![image](https://user-images.githubusercontent.com/75386018/100911707-7056db80-3484-11eb-9135-842b60ccb666.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v.1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: 
Bisq will not let me close this trade.  I do not want to keep this trade open and would like my deposit back.  Bisq is preventing this.  Please close out trade pgnmDL9 and return my deposit.  Thank you.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
information missing, please check the template as guidance
