### ISSUE TITLE
Fee reimbursement for trade 18513

### ISSUE THREAD

**Issue by haritarak** [bisq-network/support#582]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: d08f4b5584f3da27e5b07a201c4e8544585d58989cbd5e01b48f0f3c2e74e830
Taker: db22bd121c34b3c9c0edde8e59b84f03b3f9a6160671a29272390544e3f11fe0
Deposit: d1f670a9a31640f407ed3c0bc65b2d260653461b80c20b9457624e97c9d50e42

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: The deposit TX has lots of confirmations but the Bisq does not confirm it to allow me to pass to the payment step. Please reimburse fees.
Thanks.
![Captura de pantalla 2020-12-03 a las 7 13 33](https://user-images.githubusercontent.com/74642609/100971425-2aa71b00-3537-11eb-8fa2-8364900639c5.png)
![Captura de pantalla 2020-12-03 a las 7 13 58](https://user-images.githubusercontent.com/74642609/100971433-2ed33880-3537-11eb-83ed-2f60e61fa497.png)

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
hi, did you update to the new version (1.5.4) and Resync? https://bisq.wiki/Resyncing_SPV_file . please open a mediation ticket and get in contact with your mediator.
