### ISSUE TITLE
[Reimbursement] Payout has 0 peers & 0 confirmations, Txid not found for trade qrnbiub

### ISSUE THREAD

**Issue by Slimmmmmmmmm** [bisq-network/support#583]
(December 31, 2020): Hello. I would like to ask for reimbursement and compensation. I have sent the FIAT correctly. 30 days have passed already & I have not received my payout. The peer is no longer cooperating and not reachable by an means, so I ask to reimburse me 0.0238 BTC of the trade amount + 0.006 BTC of my security deposit + 0.006 BTC from the seller's deposit as a compensation, that is 0.0358 BTC total. The 30-day average BSQ/BTC price is 0.00004198 BTC, so I ask for 852.8 BSQ total.

(December 1, 2020): The payout has 0 peers and has 0 confirmations, when clicking the txid it says transaction not found. Also the wallet that says the coin is in shows nothing on the explorer.

<img width="1171" alt="Screen Shot 2020-12-02 at 3 58 10 PM" src="https://user-images.githubusercontent.com/75394475/100930505-2f2bef00-34b7-11eb-94e7-c5b33ed022ae.png">

update (Dec. 3, 2020): 2 days later, still says " Seen by 0 peers / 0 confirmations." 

Trade: qrnbiub

txid for the payout: https://blockstream.info/tx/94387a7db611249999b302944819be4fa281c04d9dfb5582f30b7b2445ccd1df

address that says received: https://blockstream.info/address/bc1qknde88snysjttmsv4txg9pm7vgvxzw4vnqpeg4

**Comment by chimp1984** [comment]
Can you post the maker fee tx id and taker fee tx id?

**Comment by Slimmmmmmmmm** [comment]
maker fee txid: https://blockstream.info/tx/de64a628fd76dc079a825a2ea0d6958e82a7e41431811fb47140c718095763b7

taker fee txid: https://blockstream.info/tx/6a9275608756d12c22ba88541bb8c8142d06d4d2f2ed8694086c3ef53a0ba020

**Comment by chimp1984** [comment]
Can you post a screenshot of the trade details window (click on trade id)?
Thats the real deposit tx: https://mempool.space/de/tx/aa23028e2a6cdf5f8eff9efb838586ccebfd9247d7c97b4d3e6a82a3dc0ce403
And its not paid out.

**Comment by Slimmmmmmmmm** [comment]
Trade Details Window:
<img width="893" alt="Screen Shot 2020-12-03 at 1 13 29 PM" src="https://user-images.githubusercontent.com/75394475/101070785-ccdff680-3569-11eb-9e4d-9f40f1388701.png">

Open trades screen empty:
<img width="1148" alt="Screen Shot 2020-12-03 at 1 14 07 PM" src="https://user-images.githubusercontent.com/75394475/101070791-cea9ba00-3569-11eb-8f85-7264cd437840.png">

at first the trade got stuck before step 1, then it opened the trade again and withdrew the deposit from my wallet, which was odd to me. (shown below)

<img width="1166" alt="Screen Shot 2020-12-03 at 1 19 17 PM" src="https://user-images.githubusercontent.com/75394475/101071146-34964180-356a-11eb-8eb6-7e51b46a66d2.png">

**Comment by chimp1984** [comment]
Can you PM me the log files (all 11 log files in a zip) on keybase (same username)?

**Comment by Slimmmmmmmmm** [comment]
I sent you a PM on keybase.

**Comment by chimp1984** [comment]
There was a bug where past transactions got set as deposit tx. It is fixed for a hotfix release we will do in a few days (monday probably). This caused the other follow up issues. 
Open a dispute with cmd+o and tell the mediator that it requires a manual payout. He will guide you further. Tell the mediator that the real deposit tx is: aa23028e2a6cdf5f8eff9efb838586ccebfd9247d7c97b4d3e6a82a3dc0ce403 not the one shown in the app!

**Comment by chimp1984** [comment]
I could move the trade back from closed to open trades and set the correct deposit tx id. With that the user can open mediation. The mediator should close in favor to the seller as he has not received the btc. I hope the buyer will get the dispute ticket as well and can still accept the mediated payout. If not we can do either a manual payout if the buyer is available, or wait until arbitration can be opened.

**Comment by Slimmmmmmmmm** [comment]
Mediator closed out the case and funds still stuck at 0 peers / 0 confirmations.

**Comment by chimp1984** [comment]
So you did accept mediated payout. Did peer accept as well already?

**Comment by Slimmmmmmmmm** [comment]
I accepted mediated payout. Peer had/has no support tickets open so there is nothing for him to accept.

**Comment by chimp1984** [comment]
Confirming that I am the keybase user chimp1984: "dsf9235ldfsgdsaykhdsfg"

**Comment by Slimmmmmmmmm** [comment]
In support doing manual payout. Still stuck at 0 peers / 0 confirms. (Dec 14, 2020) 

<img width="1169" alt="Screen Shot 2020-12-14 at 8 52 07 AM" src="https://user-images.githubusercontent.com/75394475/102089004-a6338280-3de9-11eb-9b42-33f9fb31dd2d.png">

**Comment by 3cola** [comment]
It looks like that I have the same issue.

**Comment by Slimmmmmmmmm** [comment]
Re-sync failed with v1.5.2. Peer has given up on deposit. Waiting on more solutions.

**Comment by jmacxx** [comment]
@Slimmmmmmmmm from the above it looks like a manual payout was attempted on Dec 14.  What happened, why did the manual payout not succeed?

**Comment by Slimmmmmmmmm** [comment]
@jmacxx both me and peer sent the mediator privHEX and privWIF for manual payout which couldn't be completed after waiting 5 days for a response. This is what caused the other peer to delete his wallet, start over & became unresponsive. 
<img width="372" alt="Screen Shot 2021-01-02 at 11 41 15 AM" src="https://user-images.githubusercontent.com/75394475/103461867-6d534300-4cef-11eb-9d45-f1dab7cf399e.png">

**Comment by jmacxx** [comment]
@leo816 can you comment on why the manual payout has not been made?

**Comment by chimp1984** [comment]
The delayed payout tx has not been made:
https://mempool.space/de/address/bc1ql5us359ssydugtqg6wd4k4z0wavp4dtd6lw2nvxaewyvj79z5eaqls5kd8

So that cannot be reimbursed before that is done. Otherwise the traders could do a payout at any time later and would have received 2 times the funds. The DAO can only reimburse once the funds on the multisig address are send via the delayed payout tx to the burningman where it gets converted to burned BSQ.

@Slimmmmmmmmm Did you open a arbitration ticket (by rejecting the suggested payout)?

**Comment by jmacxx** [comment]
This issue has been solved finally by doing a manual payout.  Thanks to all involved!  

@Slimmmmmmmmm please can you close this issue.

**Comment by chimp1984** [comment]
NACK. Fund have been paid out at the end with a manual payout
