### ISSUE TITLE
Fee reimbursement for trade 707714

### ISSUE THREAD

**Issue by ron87in** [bisq-network/support#584]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/73856827/101090909-feae8880-357c-11eb-8aba-64b6515468a2.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 47c047a595be7ce7acf83ccc2f657c048c18a845dbbb15abe9a8e8b38920742e
Taker: n/a
Deposit: n/a

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: This trade was previously mentioned here (https://github.com/bisq-network/support/issues/526). On this other page, I also mentioned a trade that disappeared from my platform, which has now been resolved with help from that trade's mediator. The mediator does not have the power to help with the trade this post is about, so I am making another post about it. My username is ron87in on keybase - feel free to reach out there if that is easier.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide a btc address where you would like to receive the payment

**Comment by pazza83** [comment]
Closing as no reply
