### ISSUE TITLE
Fee reimbursement for trade 09944980

### ISSUE THREAD

**Issue by Kariba1812** [bisq-network/support#586]
>_The 09944980 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/75386018/101197058-74b2fe00-3616-11eb-8e33-8b7e79bec407.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  dd50fcb1394c80670f6118116a3d53f59cbb8317bcb5dc349c5e1b7ff931d8a6
Taker: 10978d92f2227eed01796f0113d705aeec8a236ec8473f944fc78cc0685b4488
Deposit: 007fbdcfb270ac97c9b84170be719c4abe25e587a2376009d99699da99055101

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v.1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:  Delayed Payout Transaction ID did not fill.  Please reimburse deposits.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by Kariba1812** [comment]
Delayed transaction ID did not properly fill by protocol.  Please reimburse deposits.

**Comment by pazza83** [comment]
Hi @Kariba1812 

This trade appeared successful. Therefore no delayed deposit transaction ID is required (this is only needed when a trade moves to arbitration).

If I am missing anything please comment below and I will look into it.

Many thanks
