### ISSUE TITLE
Security deposit reimbursement for trade VftyDShZ

### ISSUE THREAD

**Issue by jhdfvcbiw** [bisq-network/support#588]
![image](https://user-images.githubusercontent.com/56731121/101286337-d07db280-37e1-11eb-955b-6fd54fbaa51c.png)

Maker: 89ec5e6d0d17ef9f7e6293663caa265ed22fd156f9bb5ce10d6438a4295e9ab4
Taker: 323d65ba1c7fe463ed415f2ae3a5d46f83ed0b81037a28fac76bedc58a206ccc
Deposit: ba2e2a262679a2add8f59aac4518ac7b0f9d27b0cce74a9c00f4190b802150ac

Bisq version: 1.5.0

![image](https://user-images.githubusercontent.com/56731121/101286367-04f16e80-37e2-11eb-9d69-86da1a41203f.png)

Bisq says my deposit transaction funds are still locked. This is due to a missing delayed payout transaction ID.

**Comment by chimp1984** [comment]
Maker fee tx is not in the mempool. Taker fee is spent on other tx:
https://mempool.space/de/address/1GSy5A7vhAkTv6BmJDyurvGtrKZAzBtF96
Please move the trade to failed trades and you can request a reimbursement for the lost fee.
