### ISSUE TITLE
Fee reimbursement for trade 64423

### ISSUE THREAD

**Issue by helleaven-lab** [bisq-network/support#590]
>_The 64423 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/75671089/101472176-22d4e580-3940-11eb-9378-983829e98bd7.png)

TradeID: 64423-f2a4239d-1ae2-4b26-b2bf-ce4e4bcd908f-150
Maker:  b2e0d4da39c3a5fbda63f61ab070bd0c292c73d833f9104ee80d2f5ff15e1e34

```
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 663356, myLockTime=659942
```

Bisq version: 1.5.0 Windows

Other notes:
I have security deposit block with funds
btc address: bc1qkn3pey3c8vwuj8nhpk5ru085k9tt7nv9d05pn7
Thanks in advance!

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
