### ISSUE TITLE
Fee reimbursement for trade fxsluggg

### ISSUE THREAD

**Issue by bitcoin-heru** [bisq-network/support#594]
![Screenshot 2020-12-11 at 13 53 29](https://user-images.githubusercontent.com/75846872/101915335-64be8f80-3bbd-11eb-801c-321d1be8de41.png)

Maker:  066932653cff64ba6c4fafd82b66b2cfb91b58891e3ca22c8d34b5491fde1841
Taker: 457113f61a98a10887defc5b3147fbb211e7eeedc654932af04c163c352ac15c
Deposit: N/A

Bisq version: 1.5.1

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by ConorOkus** [comment]
3EfgzhxqfNg9GHDVFTePWYsU2DLCSV4mGi

**Comment by bitcoin-heru** [comment]
3EfgzhxqfNg9GHDVFTePWYsU2DLCSV4mGi

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
