### ISSUE TITLE
Fee reimbursement for trade FPBOy

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#599]
![grafik](https://user-images.githubusercontent.com/63785272/102064209-51970400-3df7-11eb-9d04-74249662deaf.png)

Maker:  7440c094c2510e534e08f10f982c19192b4c6fbca39ee236c94597b355a5a904
Taker: 3a37dcccb45d7ec53a29b068b96bc51efbbefc4d63d13dd44e68d3eb28c66e03
Deposit: ..........

Bisq version: 1.5.1

Other notes:

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by Akira45-0** [comment]
bc1qdtq5w5pfuc92gtfaxrsyrcdqqvlzle5x9m0ha2
Thank you.

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
