### ISSUE TITLE
Fee reimbursement for trade BLobJUX

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#60]
This issue has been created per the process detailed in bisq-network/support#35 to track the reimbursement of trading and mining fees lost due to the 'failed transaction broadcast' problem tracked at bisq-network/exchange#1193, investigated at bisq-network/exchange#1195, and now fixed in Bisq v0.6.4 with the resolution of bisq-network/exchange#1244.

**IMPORTANT: If you have not yet upgraded to Bisq v0.6.4, please do so immediately at https://bisq.network/downloads.**

If the trade ID in the title of this issue is yours, then please click the `Subscribe` button in the right menu of this issue to be notified about the status of your reimbursement.

If you do not see a `Subscribe` button, then you are not logged in to GitHub. Please log in or create an account if necessary. You'll then be able to `Subscribe` to this issue and you will get updates by email.

> NOTE: this issue was created in response to @jenechka1 at https://github.com/bisq-network/support/issues/35#issuecomment-359835452, not as part of the usual process laid out in #35. This trade appears to belong to @keo-bisq as I do not have it in my arbitration queue, and because @jenechka1 mentioned that they'd already seen a "blanket" close mention that referenced a different reimbursement issue (`#53`)—I imagine that was due to copy-and-paste error when @keo-bisq was closing this trade out.

**Comment by cbeams** [comment]
@jenechka1, could you please paste a screenshot of the trade details screen where it shows the Maker, Taker and Deposit transaction IDs, and also paste those transaction IDs here as text? Thanks.

**Comment by cbeams** [comment]
And for an example of the information I'm requesting above, see https://github.com/bisq-network/support/issues/53#issuecomment-358799056

**Comment by jenechka1** [comment]
@cbeams, my screen is a small one, so it does not all fit, but here it is anyway.
![screen shot](https://user-images.githubusercontent.com/35736319/35335329-4411136a-00e3-11e8-8764-f3aa558dff78.png)

Maker: e46ad0efeecb48d3f0151404aaf13c86074f06783e15367f4ffbe9b30deb4a99
Taker: 821f7324acc86f41f02d4a55ac9bcf376a03d8c5cc8a81020e8ed7712cb56698
Deposit: ff888a5747c325529c17cb6573c82c541a6c221d34c585c819379b226b4f873b

**Comment by cbeams** [comment]
Perfect, thank you.

**Comment by jenechka1** [comment]
The trade is still open and shows a little over 20 hours remaining. Do I need to do anything else at this time? Or do I wait for further instructions?

**Comment by cbeams** [comment]
@jenechka1, I was under the impression (from your comment in #35) that this trade had already gone to arbitration and already been closed. Yet above, you say it is still open with 20 hours remaining. What am I missing?

**Comment by cbeams** [comment]
And in any case (regardless the answer to the question above), the maker and deposit transactions for this trade have not been broadcast, meaning it is impossible to complete this trade. The only thing left to do is to reimburse the maker fee transaction, which will be done as part of the resolution of this issue. You can just stand by for that.

But I am curious as to why this issue is "still open" on your client. If you saw a "close ticket" message in arbitration chat, this trade should be closed. Feel free to share screenshots of your `Portfolio` screens so we can track this down. And you can send these to me via email to chris@beams.io or via Keybase to `@cbeams` if you prefer for privacy.

**Comment by jenechka1** [comment]
The trade did not go to arbitration. I didn't know it could before the time ran out. Instead, I opened a support ticket, having read about the bug on bisq.community forum.

I'm sending screenshots to your email in a few.

**Comment by cbeams** [comment]
Staged for reimbursement in b902362

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/35#issuecomment-362038006.

**Comment by cbeams** [comment]
@manfredkarrer, any ideas?

**Comment by ManfredKarrer** [comment]
@jenechka1 Please try to delete the spv chain file. Use the just released 0.6.5 version as there is an important fix regarding spv file deletion on Windows.

**Comment by jenechka1** [comment]
Do I have to be in the app in order to do that? Because I can't get into the app. After I dismiss that warning about duplicate transactions, here is what I see:
![screen shot 2018-01-31 at 11 12 52 pm](https://user-images.githubusercontent.com/35736319/35660806-4bfe764a-06dc-11e8-8363-622908fad1ce.png)

I did download the latest, but just so you know, I'm on MacOS High Sierra (10.13.2)

**Comment by jenechka1** [comment]
Found a file "bisq.spvchain" in "~/Library/Application Support/Bisq/btc_mainnet/wallet".
Deleted it, then attempted to restart the app. Same warning followed by "connection failed".

What do I do? I have trades, which are paid for, but which I suspect will not complete because of another issue (referenced here: #1174). They may be in arbitration, but I have no way of checking.

Is now a good time to panic?

**Comment by jenechka1** [comment]
Not to rush you guys, but time is of the essence. Is there anything else you can think of that I could do to gain access to my wallet and trades?

**Comment by cbeams** [comment]
@jenechka1, what happens if you do the following?

```
$ /Applications/Bisq.app/Contents/MacOS/Bisq --appName=Bisq-Test
```

This will start Bisq against a completely fresh application data directory (at `~/Library/Application Support/Bisq-Test`), and won't have any effect on your earlier installation.

Based on what you discover here, we can see about next steps.

P.S.: We should really be managing this in a separate issue, but for now I'm just quickly re-opening this one. Hopefully we can sort this out quickly and re-close.

**Comment by jenechka1** [comment]
It started up fine, but without any information about my trades / wallet / settings. What exactly are we looking for?

**Comment by cbeams** [comment]
Ok, good. This proves that your machine / network is capable of running Bisq, connecting to the network etc.

Here's what we should do next:

1. Close the Bisq-Test instance if it's still open. You won't need it anymore.
2. Download and install Bisq v0.6.5 from https://bisq.network/downloads
3. Try to run the newly installed version just as you usually do, i.e. by double clicking on the Bisq icon
4. Let it try to start up for at least 3 minutes
5. If Bisq has not correctly started up by that time, then please attach your `bisq.log` file here. You can find it at `~/Library/Application Support/Bisq/bisq.log`. I'll then analyze the log and get back to you.

**Comment by jenechka1** [comment]
So, still get this message:
![screen shot 2018-02-02 at 10 36 45 am](https://user-images.githubusercontent.com/35736319/35741338-8eae6a20-0805-11e8-899b-03fb8a1928c3.png)

When I dismiss it, the app just hangs here for a few minutes:
![screen shot 2018-02-02 at 10 39 08 am](https://user-images.githubusercontent.com/35736319/35741366-9d5224ae-0805-11e8-8931-a901316853d4.png)

And then eventually goes here:
![screen shot 2018-02-02 at 10 39 42 am](https://user-images.githubusercontent.com/35736319/35741372-a3d9497e-0805-11e8-97ad-0224d20829e6.png)

I tried deleting Tor files, going with bridges... nothing changes.

I'm attaching the log file you requested. There is another one there: bisq_1.log; let me know if you need it.
[bisq.log](https://github.com/bisq-network/support/files/1689896/bisq.log)

**Comment by cbeams** [comment]
@ManfredKarrer, it still seems to me that this "duplicate transaction" problem has to be solvable by resyncing SPV. @jenechka1 said in https://github.com/bisq-network/support/issues/60#issuecomment-362156005 that he tried manually removing the SPV file. Could you double-check that comment and provide any advice? Thanks.

**Comment by cbeams** [comment]
@jenechka1, I've just gone through the code and verified that deleting `bisq.spvchain` manually should be all that you need to do. I've just tested this myself as well, and I was able to get back into the app as expected.

Let me double-check something here: when you deleted the `bisq.spvchain` file before, was the Bisq application *already closed*, or did you close it *after deleting the file*?

My recommendation is this: Make sure Bisq is shut down fully, remove the `bisq.spvchain` once more, and start the app once more. Let me know what happens. Thanks.

**Comment by jenechka1** [comment]
With Bisq app closed I am moving bisq.spvchain from /Bisq/btc_mainnet/wallet to the Desktop with this command: mv bisq.spvchain ~/Desktop/

Then attempt to start the Bisq app.

The behavior is exactly as described in my previous message above.

Also, you may find this useful: the bisq.spvchain file does not get regenerated.

**Comment by jenechka1** [comment]
Guys (@cbeams, @ManfredKarrer) , any chance finding a solution to this may get a higher priority? I am unable to access neither my wallet nor the trades for three days now. As I'm sure you understand - time is of the essence.

**Comment by cbeams** [comment]
I've pinged @ManfredKarrer about this off-thread, @jenechka1. We'll get back to you, thanks.

**Comment by ManfredKarrer** [comment]
@jenechka1 Can you send me the log file (manfred at bitsquare dot io - please reference to that GH issue)? Which OS are u using? On Windows you cannot delete the file if Bisq is running. After you have deleted it was the file newly created and did have the current date?
If the file was really newly created and the issues did not disappear you can try to restore from seed words.
First make a backup then go to account/seed words and copy the seed words and date. Then use the same to restore it in the same screen. After restore the spv file will be resynced as well.
Hope that helps.

**Comment by jenechka1** [comment]
The log file was attached to an earlier message in this thread. Do you need
the latest?
I'm on Mac OS
When you say "after you deleted it" are you referring to the log file or
the SPV file? Because I never deleted the log file, and the SPV file did
not recreate. I.e. there is no "newly created" file to speak of.
Do I need to be in the app in order to make a backup? Because I can't get
into the app!

Best regards,

Jean

**Comment by jenechka1** [comment]
@ManfredKarrer, so I moved the Bisq directory from ~/Library/Application Support/Bisq, then I started the app again and it opened up with all the startup dialogs etc. Then I made a backup and restored with my seed words from before. Now, the only thing that appears to have re-synched is the list of transactions.

I had a number of open trades, but none of them appear under "Portfolio". I had an open offer, it's not there anymore. All of "Available balance", "Reserved in offers", "Locked in trades" are showing 0.0, even though they all had non-zero values before.

What else can I do?

**Comment by jenechka1** [comment]
@cbeams, @ManfredKarrer 

I think I have gotten it back to where I want it to be. Here are the steps:

- Removed the spvchain file. Actually, I don't think this did anything for this particular issue, because the warning kept appearing and I was still unable to enter the app, even after it was removed, but, for the sake of completeness I thought it important to mention that it was removed.

- Made a backup copy of the ~/Library/Application Support/Bisq directory, and then deleted this directory from ~/Library/Application Support/

- Ran Bisq and restored the wallet from seed words.

- Once the wallet completed its synchronization, copied the BTC.wallet file to the backup, created in step two above, replacing the corrupt one.

- Removed the ~/Library/Application Support/Bisq directory again, but this time, put the backup, created in step two, back to take its place.

- Ran the Bisq app again. It took a few minutes to synchronize, but it appears to have picked up all the changes to my wallet, including from the trades that were opened when the problem began and that completed while I was still unable to access the app.

Thank you for your help.

**Comment by cbeams** [comment]
Excellent! Very glad to hear that. I'll respond to you via our email thread as well. All the best.

**Comment by cbeams** [comment]
Re-closing as @jenechka1's issues are now resolved.
