### ISSUE TITLE
Fee reimbursement for trade 2tyuw

### ISSUE THREAD

**Issue by peterbaricic** [bisq-network/support#601]
<img width="926" alt="bisq" src="https://user-images.githubusercontent.com/6643903/102375668-10534f80-3fc3-11eb-8011-40c81d47d602.png">

Maker:  e689bdedb0b9def2d911a2014bd13ddd713a88d158d8b063f678ab8257ec79e5
Taker: ...........
Deposit: ..........

Bisq version: 1.5.1

This is the error message:
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 664500, myLockTime=664513

Please reimburse the fees. Thank you.

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by peterbaricic** [comment]
bc1qqhrrvx3au9yjewq5af6jtte22y49xlpucvh8ew ... thank you

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
