### ISSUE TITLE
Fee reimbursement for trade L4ZBOHUC

### ISSUE THREAD

**Issue by Scandelq** [bisq-network/support#602]
![image](https://user-images.githubusercontent.com/76119998/102379013-b48ac580-3fc6-11eb-8742-8ebf9e154644.png)

Maker:  29ae1e23e5385d059ae1dcb3716d3958eb91402823d0cbc7ca05f89f876f0b60
Taker: N/A
Deposit: 0.0060 BTC

Bisq version: v1.5.1

Other notes:

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by Scandelq** [comment]
> please write down the btc address where you would like to receive the fee reimbursement

bc1q37e8rqgmay0kzdnja0spvm85yrme3spje2w7tx

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
