### ISSUE TITLE
Fee reimbursement for trade L4ZBOHUC

### ISSUE THREAD

**Issue by rodrigocorral** [bisq-network/support#603]
![image](https://user-images.githubusercontent.com/6072095/102388551-392f1100-3fd2-11eb-8975-c801b8575d35.png)

Maker: 29ae1e23e5385d059ae1dcb3716d3958eb91402823d0cbc7ca05f89f876f0b60
Taker: N/A
Deposit: 0.0060 BTC

Bisq version: v1.5.1

An error occurred at task: CreateTakerFeeTx
Exception message: Insufficient money,  missing 0.00213794 BTC

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by rodrigocorral** [comment]
1Ppq6vMWP6dGYVztQsK7LFckcZiUEn18FK

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
