### ISSUE TITLE
Fee reimbursement for trade V29SLR7E

### ISSUE THREAD

**Issue by hashkebab** [bisq-network/support#604]
![V29SLR7E](https://user-images.githubusercontent.com/24438885/102397371-b445f680-3fd5-11eb-9fd5-9b5736436445.JPG)

Maker: 59f4f744337714bbe7d5a5694e703baa48cf5a676c513c416f504f1248e1f0d5
Taker: 339539cbe6b19c05710b7bed9e063b7739bd5fb27793417c50ce53edaf56ce60
Deposit: n/a

Bisq version: 1.51

Other notes: Issue with deposit TX not being funded correctly

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by hashkebab** [comment]
bc1qwwfv6w85rwnzqgazfeh0nxylmk3ae8z7jvglw4

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
