### ISSUE TITLE
Fee reimbursement for trade 64704

### ISSUE THREAD

**Issue by hashkebab** [bisq-network/support#605]
![64704](https://user-images.githubusercontent.com/24438885/102398533-4f8b9b80-3fd7-11eb-8dd4-e58e59d78517.JPG)

Maker:  99b4199cebb034eb4497123c0fa803a98d98a5638caf87f588adcbd324d75b10
Taker: 0e6c5624bb754e10a48c0d4dea362b6bc41a3c5d6db205174c17e7e79ecf77df
Deposit: N/A

Bisq version: 1.5.1

Other notes: Issue with deposit TX not being funded correctly

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by hashkebab** [comment]
1HsCizgcP2s4AZnpL1HffDxTUq2zv8k4hn

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
