### ISSUE TITLE
Fee reimbursement for trade 2656985

### ISSUE THREAD

**Issue by hashkebab** [bisq-network/support#606]
![2656985](https://user-images.githubusercontent.com/24438885/102417636-fa11b780-3ff3-11eb-9ea4-03c05c599a2b.JPG)

Maker:  4ecdac7c50e161ce2a0fe2a0db1504f6f0391df14fba06b50cbc23a70e1558ec
Taker: unknown
Deposit: unknown

Bisq version: 1.4.8

Other notes:

This is an older trade and have resynced SPV since so maybe missing info 

Error reported
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 653768, myLockTime=656725

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by hashkebab** [comment]
1Lbt7mUBqwqrMzrPiFHg7d5AYZQNAnS4mX

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
