### ISSUE TITLE
26517

### ISSUE THREAD

**Issue by walter400** [bisq-network/support#607]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/75341071/102420317-bb114100-3fb6-11eb-9dc8-d14233a9b4c0.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_
![image](https://user-images.githubusercontent.com/75341071/102420394-e6942b80-3fb6-11eb-9315-ef70cbe362d4.png)

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._
![image](https://user-images.githubusercontent.com/75341071/102420360-d2502e80-3fb6-11eb-81bf-af38594cc724.png)

**Comment by huey735** [comment]
Doesn't follow the template and contains sensitive information. Please`edit the post and:

- blank out the trader's personal info
- copy and paste the transaction ids for:
```
Maker: ..........
Taker: ...........
Deposit: ..........
```

Again look at [this issue](https://github.com/bisq-network/support/issues/604) for an example.
