### ISSUE TITLE
Fee reimbursement for trade LKCbEW

### ISSUE THREAD

**Issue by a-safonau** [bisq-network/support#608]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/3219729/102425941-7b079800-4062-11eb-8c51-25a7f39eb77d.png">

Maker: d5bb9c74359a7b7ecb6e585a7f1891cc75b167ca77308799081b3d788fe621fd
Taker: ...........
Deposit: ..........

Bisq version: 1.5.1

Other notes: An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=213325207
makersPrice=216263738

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by a-safonau** [comment]
bc1qaxv4mah8dcmc0ttzthr0d6ywdpynvme2477yu6

**Comment by a-safonau** [comment]
after you send the fee, can you delete the ticket and the history associated with it?

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
