### ISSUE TITLE
Fee reimbursement for trade kcjfky

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#61]
This issue has been created per the process detailed in bisq-network/support#35 to track the reimbursement of trading and mining fees lost due to the 'failed transaction broadcast' problem tracked at bisq-network/exchange#1193, investigated at bisq-network/exchange#1195, and now fixed in Bisq v0.6.4 with the resolution of bisq-network/exchange#1244.

**IMPORTANT: If you have not yet upgraded to Bisq v0.6.4, please do so immediately at https://bisq.network/downloads.**

If the trade ID in the title of this issue is yours, then please click the `Subscribe` button in the right menu of this issue to be notified about the status of your reimbursement.

If you do not see a `Subscribe` button, then you are not logged in to GitHub. Please log in or create an account if necessary. You'll then be able to `Subscribe` to this issue and you will get updates by email.

Source: @pimato in https://github.com/bisq-network/exchange/issues/1193#issuecomment-360513980

**Comment by cbeams** [comment]
@keo-bisq, @pimato, I need a screenshot and plain text of Maker / Taker / Deposit transaction IDs for this trade. Please provide this info and I'll get them staged for reimbursement as appropriate. Thanks.

**Comment by cbeams** [comment]
Nevermind on this one, @keo-bisq. To my surprise, `kcjfky` just showed up in my arbitration queue today. I'll take it from here.

![image](https://user-images.githubusercontent.com/301810/35553887-efd2e51a-0599-11e8-9f35-731af66e5098.png)

Maker: 8db2786611dec939df91b1d8fddb79b8ee5a285ddcb41d85b55b8081f46ee182
Taker: ff4e50d4bb1ead4d78d1178375d6e755ca551bb5d5a2410fbf49e0b9b75d41b8
Deposit: 4a290504042d17680b08660e6755d0071db113220ca8ddfa17e3ced8a462acb6

**Comment by cbeams** [comment]
Staged for reimbursement in 20b8746

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/35#issuecomment-362038006.

**Comment by regnarock** [comment]
Thanks a lot @cbeams!

It seems I have an issue when following what was asked in the support ticket ([related issue](https://github.com/bisq-network/exchange/issues/1078))
