### ISSUE TITLE
Confirmation deposit transaction is stuck for trade 00781

### ISSUE THREAD

**Issue by Alvaato** [bisq-network/support#610]
<img width="881" alt="tx00781" src="https://user-images.githubusercontent.com/76105040/102484809-11d65380-4067-11eb-844c-1e5626689895.png">

Maker:  [7f0e170326efd3e9a152df9df6444d812a69032b632afbbf68fe908c68fc0e54](https://mempool.space/de/tx/7f0e170326efd3e9a152df9df6444d812a69032b632afbbf68fe908c68fc0e54)
Taker: [0753f090139dfebab82382b728e0b9dbf6665955cabfff06142859cc800fce20](https://mempool.space/de/tx/0753f090139dfebab82382b728e0b9dbf6665955cabfff06142859cc800fce20)
Deposit: [6f2251f146fa7afa37ab5ba8342668471a08e25678cfd0d5563ea70e04174773](https://mempool.space/de/tx/6f2251f146fa7afa37ab5ba8342668471a08e25678cfd0d5563ea70e04174773)

Bisq version: v1.5.1

Other notes:
The deposit transaction is mined in block 661677 but the trade information says "Seen by 9 peers / 0 confirmations"
Any ideas? Thanks in advance.

**Comment by Alvaato** [comment]
<img width="988" alt="tx00781-2" src="https://user-images.githubusercontent.com/76105040/102487139-5c0d0400-406a-11eb-96f7-58d0a5bb8e5c.png">

**Comment by MwithM** [comment]
The deposit tx is ok.
Have you tried a [spv resync](https://bisq.wiki/Delete_and_resync_SPV_file)?

**Comment by Alvaato** [comment]
> The deposit tx is ok.
> Have you tried a [spv resync](https://bisq.wiki/Delete_and_resync_SPV_file)?

Well, thanks for that.
