### ISSUE TITLE
Fee reimbursement for trade LKCbEW

### ISSUE THREAD

**Issue by technonerd33** [bisq-network/support#611]
![image](https://user-images.githubusercontent.com/14337797/102556170-e9ae1b00-408d-11eb-9727-6aa7a0087121.png)

Maker:  d5bb9c74359a7b7ecb6e585a7f1891cc75b167ca77308799081b3d788fe621fd
Taker: ...........
Deposit: ..........

Bisq version: 1.5.1

This is the error message:
Timeout reached. Protocol did not complete in 60 sec.

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by technonerd33** [comment]
bc1qr9wdwmyd6vyfcd42ls4gytvjlwmvrdl0dgddgf

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
