### ISSUE TITLE
Fee reimbursement for trade UDV2W

### ISSUE THREAD

**Issue by endurance1968** [bisq-network/support#612]
![image](https://user-images.githubusercontent.com/38796027/102579249-65df4780-40fc-11eb-9504-9bfcd293b17c.png)

Maker: 29d3554357e2c71915ef194628d59531776ef903a8aa1798a0e769880159968e
Taker: ...........
Deposit: ..........

Bisq version:
1.5.1
Error:
Timeout reached. Protocol did not complete in 60 sec.

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by endurance1968** [comment]
196xKfPAhkCB5hPAYZUJ7UZhmUcy7VWEgs
thx

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
