### ISSUE TITLE
Fee reimbursement for trade 6iqejl

### ISSUE THREAD

**Issue by marcsmith1279** [bisq-network/support#613]
Trade ID: 6iqejl

![Screenshot from 2020-12-18 12-44-36](https://user-images.githubusercontent.com/76212074/102616275-339b0d80-412f-11eb-8553-5f1dafba86e9.png)

Bisq Version - 1.5.1

**Comment by leo816** [comment]
information missing, please take a look at other requests as example

**Comment by pazza83** [comment]
closing as no reply
