### ISSUE TITLE
Trade ID - 695564. Trade stuck with no deposit broadcast txid. Buyer and seller deposit stuck

### ISSUE THREAD

**Issue by marcsmith1279** [bisq-network/support#614]
![Trade ID - 695564](https://user-images.githubusercontent.com/76212074/102620756-6d234700-4136-11eb-8735-080819c45a70.png)
Bisq Version - 1.5.1

**Comment by MwithM** [comment]
Please submit in plain text maker and taker fee tx ID.

**Comment by marcsmith1279** [comment]
Maker - e44d21cd96a33ad00d7539ba69f5daa829b1c8fcaa8edd76f0863fa08b9ec579
Taker - b938f5a5d0e1c7640491b2782c0d2f6f8facd281d3cc96a2314905b75d1c3865

**Comment by MwithM** [comment]
Maker tx failed to broadcast. There's no deposit tx, so no funds are really locked.
I suppose there's locked funds in your wallet. Try a SPV resync and if it doesn't work, please use the emergency wallet or export seed to a new Bisq instance and claim for fee refund here in a new issue (follow the template instructions).

**Comment by marcsmith1279** [comment]
Thank you for your advise. All resolved now.

Case can be closed.
