### ISSUE TITLE
Trade ID - 7377320. Trade stuck with no deposit broadcast txid. Buyer and seller deposit stuck

### ISSUE THREAD

**Issue by marcsmith1279** [bisq-network/support#615]
![Trade ID - 7377320](https://user-images.githubusercontent.com/76212074/102620856-9b088b80-4136-11eb-9966-4cd083d089e6.png)

Bisq Version: 1.5.1

**Comment by MwithM** [comment]
Please submit in plain text maker and taker fee tx ID.

**Comment by marcsmith1279** [comment]
Maker - f6ba21945b5508380ed34f455c98b8d4720c1e763e50c8964fad1dfe15a01d1a
Taker - bbb9b62ce6a36d8f0eeb6f4ef274d07b0d8a092673be35988285c2d9a5b734b9

**Comment by MwithM** [comment]
https://github.com/bisq-network/support/issues/614#issuecomment-748475000

**Comment by marcsmith1279** [comment]
Thank you for your advise. All resolved now.

Case can be closed.
