### ISSUE TITLE
Trade ID - AjHLg7y0. Trade stuck with no deposit broadcast txid. Buyer and seller deposit stuck

### ISSUE THREAD

**Issue by marcsmith1279** [bisq-network/support#616]
![Trade ID - AjHLg7y0](https://user-images.githubusercontent.com/76212074/102620930-b6739680-4136-11eb-87c4-1da33ec8c6d8.png)

Bisq Version: 1.5.1

**Comment by MwithM** [comment]
Please submit in plain text maker and taker fee tx ID.

**Comment by marcsmith1279** [comment]
Maker - 7e2105e180a2dfefdb3153f7a35a44b88aaf0a99515a46a95cc92667f011a8a0
Taker - f2d5cba7f049aa5ccec8d6e78667a0ac5bdd5dfcdac9e75466e49731c66afd62

**Comment by MwithM** [comment]
Same as: https://github.com/bisq-network/support/issues/614#issuecomment-748475000

**Comment by marcsmith1279** [comment]
Thank you for your advise. All resolved now.

Case can be closed.
