### ISSUE TITLE
Fee reimbursement for trade fpcfpdq

### ISSUE THREAD

**Issue by thespear256** [bisq-network/support#617]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/76235859/102679145-85698500-417b-11eb-971c-d30787a3b0e6.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  a7d82cfba1bfe9f51ed88deff343ce82f3b566d5bb93630623931ea2b8effa6d
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.5.1

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Thanks for helping, this was a real head scratcher.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by thespear256** [comment]
bc1qnzm9hqe77z9l4zce3cdz9m845zq76kh870yznj

**Comment by thespear256** [comment]
bc1qyn2nz3ajfs3tg25s8pdzax7q5d5g35kkf8q6w2

**Comment by pazza83** [comment]
Hi there is no taker tx id, so no fees were incurred. Therefore there is nothing to refund.
