### ISSUE TITLE
Trade FPLcUuX. Deposit tx is missing.

### ISSUE THREAD

**Issue by Alvaato** [bisq-network/support#618]
<img width="874" alt="FPLcUuX" src="https://user-images.githubusercontent.com/76105040/102684582-1bcc9380-41da-11eb-8f7c-14e6dde781e0.png">

Maker:  0c5ca27c61b0e43ffc584bef8f1a605ea86a0103d0e2af647697af0a13fe6428
Taker: a3c702263f5ced765d4686d398d4a4ce46c8540827c972c8ee3389bcc824497a
Deposit: N/A

Bisq version: 1.5.1

Other notes:
The desposit transaction is stuck. I read in an other issue that there is a bugfix for that in v1.5.2. #4911
Is this the same issue? thx

**Comment by MwithM** [comment]
Your deposit tx is valid: bc1q9lewwlcq8nrn2ult3lnamzx4mwkqvn86392vq9l9tjjwaj5jw4pq2dkv70
Try a spv resync and if possible, open moderation with ctrl+O. You can contact support at Keybase https://keybase.io/team/bisq
