### ISSUE TITLE
Fee reimbursement for trade 42096

### ISSUE THREAD

**Issue by ke6X33f** [bisq-network/support#619]
![reimbursement_42096](https://user-images.githubusercontent.com/76434189/102786053-31d78100-439f-11eb-9d26-a818af124484.png)

Maker:  b61ff94758f41b6cd4ba7ee534b18bd8eea61b1bd6c8b6ab12ffa62074255031
Taker: N/A
Deposit: N/A

Bisq version: v1.5.1

Other notes:

An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 664106, myLockTime=664473

Please reimburse fees.

**Comment by leo816** [comment]
please write down the btc address where you would like to receive the fee reimbursement

**Comment by ke6X33f** [comment]
bc1qy3qj72z4teukn2u5yl77dt6w8k7kl6mglkk8r0
Thanks.

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
