### ISSUE TITLE
Reimbursement for locked up FUNDS from failed trade QALCMH

### ISSUE THREAD

**Issue by threehill** [bisq-network/support#621]
I have locked up **funds** from a failed trade. This message pops up all the time:

![image](https://user-images.githubusercontent.com/74426290/102935724-02ac3700-44a7-11eb-936e-987da18d7bec.png)

Here are the details regarding the failed trade:

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/74426290/102934622-cd9ee500-44a4-11eb-8f95-a6742f510dad.png)

Maker: d2c7562313c614ff939e307e2595fbeecd060c28ced6e988964fe112e94f1bf0
Taker: 4d0c9f3ae65419cf966ddb504b776086f5793931511b575642061efc2a61d5b0
Deposit: 71429f7bfbb7c4563cb561f19390e525ad5b569c55669faa2675c9994f68f8b3

Bisq version: 1.4.2 when the issue occurred (now 1.5.1)

**Comment by pazza83** [comment]
Hi @threehill 

The screenshot of the trade posted does not look like a failed trade. It seems to have been successfully completed. 

Please let me know if you are seeing any locked funds that shouldn't be locked in the GUI.

**Comment by pazza83** [comment]
closing as no response
