### ISSUE TITLE
Reimbursement for locked up FUNDS from failed trade SwVysv9

### ISSUE THREAD

**Issue by threehill** [bisq-network/support#622]
I have locked up **funds** from a failed trade. This message pops up all the time:

![image](https://user-images.githubusercontent.com/74426290/102936024-9c73e400-44a7-11eb-8791-82f5c7f4b72c.png)

Here are the details regarding the failed trade:

SCREENSHOT HERE

![image](https://user-images.githubusercontent.com/74426290/102936057-ae558700-44a7-11eb-8875-7bfa8245804c.png)

Maker: 92d0a0b007540acc42cb2f6562cc3c4d759607efc90183b1dacde3c436815151
Taker: a80e3f83ff2aa3e6056129f8d1c139f812b1378a495de1cd9b56f936456413b3
Deposit: 3af03d2dd50ba9930368e57b26c3d6f9c8e5f98bb7b180ee56c6c13d8456e1b1

Bisq version: 1.4.2 when the issue occurred (now 1.5.1)

**Comment by pazza83** [comment]
Hi @threehill

The screenshot of the trade posted does not look like a failed trade. It seems to have been successfully completed.

Please let me know if you are seeing any locked funds that shouldn't be locked in the GUI.

**Comment by pazza83** [comment]
closing as no response
