### ISSUE TITLE
Reimbursement for locked up FUNDS from failed trade 23718758

### ISSUE THREAD

**Issue by threehill** [bisq-network/support#623]
I have locked up **funds** from a failed trade. This message pops up all the time:

![image](https://user-images.githubusercontent.com/74426290/102936311-3d629f00-44a8-11eb-84b6-d66aa15fb1c2.png)

Here are the details regarding the failed trade:

![image](https://user-images.githubusercontent.com/74426290/102936262-26bc4800-44a8-11eb-9266-9b4c8cc8c0cb.png)

Maker: c70a19ea185828bc3903b2f913c3f2611fdaf432fb9299b833cb4a689caa62d7
Taker: f9fab0c120572675c84eee945ad71ab8dd1dd114c9ec4fba190e0f7a703dfcc9
Deposit: 476d5b5baddbf350f57b497cd12be67f84dd8cd39f8cb298dfb8ad83a1c96dc3

Bisq version: 1.4.2 when the issue occurred (now 1.5.1)

**Comment by MwithM** [comment]
What happens when you press ctrl+O, is it possible to open mediation?

**Comment by threehill** [comment]
I have already an open mediation and @leo816 is my mediator but he only reimburse fees and not funds. He advised me to message @refundagent which I have done.

**Comment by pazza83** [comment]
Hi @threehill there are no locked funds for the trade posted above all funds have been spent.

Please contact me on Keybase if you have any questions. My username there is pazza.
