### ISSUE TITLE
Reimbursement for trade giio5op (#396)

### ISSUE THREAD

**Issue by BisqTor** [bisq-network/support#624]
I had a failed trade 240 days ago and yesterday I received the fees (0.0007 btc).
Now I am waiting for my Security Deposit of 0.006 BTC.

![image](https://user-images.githubusercontent.com/64381948/102939231-a89e7800-448c-11eb-8e96-a8b7da0e456e.png)

Trade ID: giio5op
Maker: 4fc440a091291fd6ab57af89df0481b2d70ef1b8d7e2ce340cc58e97e4b99821
Taker: 3bcd8733a967d26b16642fa8eeafd700ade80975f8dfdaae60c24bc03caf3071
Deposit tx id: 49b2767538914b62b4eb16ae9bd9bcc00fa2a1a4bedfe48a1dc22882eae420f

Link of fee Reimbursement: https://github.com/bisq-network/support/issues/396

Deposit: 0.006

Bisq version: 1.3.2

**Comment by BisqTor** [comment]
Please @refundagent.
I am waiting my money back for 8 months!!!!

**Comment by BisqTor** [comment]
I need meditators.

**Comment by BisqTor** [comment]
@leo816 paid my fees - link: Link of fee Reimbursement: #396 

Now I need back my Security Deposit of 0.006 BTC.
Who can help me??

**Comment by BisqTor** [comment]
Hello.  Is Bisq dead?
Anyone?

**Comment by BisqTor** [comment]
???

**Comment by leo816** [comment]
If funds still appear as locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest way is to delete the ClosedTrades and FailedTrades files in the db folder. you have to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades. (Have you already tried resync and restore from seed using the same data directory?)

**Comment by BisqTor** [comment]
No. The balance of my wallet is zero. It never appears the 0.006 btc that was lost.
I just tried to inport my seeds in a new computer, but i see no funds.
![20210210_162421.jpg](https://user-images.githubusercontent.com/64381948/107560450-209b3b80-6bbc-11eb-99c2-b11c42e6c06b.jpg)

**Comment by pazza83** [comment]
Hi @BisqTor the trade failed. Therefore it is not possible to lose 0.006 BTC on this trade. The trade never took place.

If you have any questions please reach out to me on Keybase. My username there is: pazza
