### ISSUE TITLE
Deposit Transaction ID shows "N/A" for trade NOJLXU

### ISSUE THREAD

**Issue by appideias** [bisq-network/support#632]
Trade ID: NOJLXU
Maker fee tx: 521691c869f39e0fa6db1ebe82d90f6070dfa9be5fc84e29410dbd9042d0185e
Taker fee tx: 2f8c32cde5e990ec2074500aa4706ea15527cab5b8e88179c4db1033065a9584
Deposit Transaction ID tx: N/A
Delayed Payout ID tx: 16a81ddcea395a6fb2422b236ce876ee7ad076dc9a732c28c8668b535875fa07

BISQ version by the time of the issue: 1.5.0
BISQ version now: 1.5.1

My funds are locked and the trade can't be altered nor canceled... What should I do?

Thanks!

![Trade window](http://libertasbank.com/images/bisq/NOJLXU_trade.png)

![Blank tx](http://libertasbank.com/images/bisq/emptyOpenTradetx.png)

**Comment by MwithM** [comment]
https://github.com/bisq-network/support/issues/633#issuecomment-750036022
