### ISSUE TITLE
Reimbursement for trade 635795

### ISSUE THREAD

**Issue by catoptro-mancy** [bisq-network/support#634]
<img width="845" alt="Screen Shot 2020-12-23 at 7 18 26 AM" src="https://user-images.githubusercontent.com/76520635/102995730-aa4d5780-44ef-11eb-9d03-358255f146a5.png">

<img width="854" alt="Screen Shot 2020-12-23 at 7 18 10 AM" src="https://user-images.githubusercontent.com/76520635/102995740-ae797500-44ef-11eb-8e19-d20ad6ec996f.png">

Maker: 2b55560f4048d51e2e28c0b4cedaf7d19ecdda7699ccef381dd62d7c1f9fa397
Taker: 5727a04a8fd0e54fd8d746f22c37d54f4d583a4d90f8ff79e6747f26c52cdafd
Deposit: N/A

Bisq version: 1.5.1

Other notes:

Recurring issue in 1.5.1?

**Comment by catoptro-mancy** [comment]
BTC address for refund: 
bc1qfe038gnumfuel3efzhxk55gz2zqu55aqw4ma3x

**Comment by pazza83** [comment]
Hi @catoptro-mancy 

Apologies for the late reply.

Please can you repost the trade details screen shot to show if you were the maker or taker.

Many thanks
