### ISSUE TITLE
Fee reimbursement for trade 72999628

### ISSUE THREAD

**Issue by CoinJoinDay** [bisq-network/support#635]
72999628-13809a72-cf3d-4706-81a4-bdfdfb0e8e58-151

SCREENSHOT HERE
![imagem](https://user-images.githubusercontent.com/23665033/103039145-664e6700-4570-11eb-98e9-0417082d98f9.png)
![imagem](https://user-images.githubusercontent.com/23665033/103039428-30f64900-4571-11eb-8835-f4400b3c5444.png)

Maker Fee Transaction ID: 89540cee872ece232c4db8a30286b1cfd8fc8309ab84a8174914ecfecf204830
Taker Fee Transaction ID: 44cc0d164cb213b172e33006229d64c45a47c68979bb49daa516cc3a3d486f2f
Deposit Transaction ID: d95032abd04ee2944d85ece6059ac29e4399f1b79856a49d9cf1a96ad511fc09
Delayed Payout Transaction ID: e316496bd2dcbd1edbf6d36d6fbeedbe2298872b42b9c03fe3dfc78807920f02

Bisq version: 1.5.1

Other notes:

Windows 10 version, Transaction stuck on my side ( Buyer side )

**Comment by leo816** [comment]
did you try doing a resync?

**Comment by CoinJoinDay** [comment]
yes, still the same

**Comment by CoinJoinDay** [comment]
![imagem](https://user-images.githubusercontent.com/23665033/103150964-bd735800-4779-11eb-83fb-fd23da707bc6.png)

**Comment by CoinJoinDay** [comment]
can I have the reimbursement to this Bitcoin address: bc1q6znakvvd5vhms0dqnk6h8us008d7kw5kg7rxcz

**Comment by CoinJoinDay** [comment]
after update do version 1.5.2 and resync is everything OK
