### ISSUE TITLE
Fee reimbursement for trade MEzGMcUZ

### ISSUE THREAD

**Issue by pauls001** [bisq-network/support#636]
<img width="655" alt="1" src="https://user-images.githubusercontent.com/76539266/103043682-05c62680-457e-11eb-88e0-24a88a6c4bde.PNG">

Maker:  46087686a6dd83ab162d07fc6a58fb9a0df7862dc2ae8836388df6fde3e2730e
Taker:  2edfa3ee67afff0d3c297d742c146a68c3ab9cb41eda4c757fed21298557fe07
Deposit: N/A

Version 1.5.1

Funds are locked:
Taker fee tx failed at first, then deposit tx appeared as N/A.
Tried SPV resync.
Tried restoring from seed words.
Tried replacing the data directory form backups.
Funds still locked

(The trade does not appear as failed)

**Comment by leo816** [comment]
please provide a preferred btc address where you would like to receive the reimbursement

**Comment by pauls001** [comment]
Reimbursement adress:  bc1qsjg0lpkhj04g2guutqaw488vykwknrga26g988

**Comment by pauls001** [comment]
Regarding the locked funds... I'm not able to send the trade to failed trades... So I can't unlock the funds... Any idea or suggestion?

I have read about quite a few people having the same issue, but it seems to be unsolved as for now... Should I just wait for v1.5.2?

**Comment by leo816** [comment]
was this issue resolved after the update? fee reimbursement will be made soon

**Comment by pauls001** [comment]
Yeah, already solved... Thanks!

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.

**Comment by pauls001** [comment]
Oh... Okay, thanks anyway
