### ISSUE TITLE
Fee reimbursement for trade 505034

### ISSUE THREAD

**Issue by pauls001** [bisq-network/support#637]
<img width="650" alt="2" src="https://user-images.githubusercontent.com/76539266/103044133-acf78d80-457f-11eb-9263-2a5ec2c3f88b.PNG">

Maker: 92ad3de98b6ada6a4be1953578f3a5e0833a5e6dd932b6858ee97c05d6fa412e
Taker: 7d13b11995ef8344908b842d749d9d3e80c1b136fbab4335066c1e1f804daa12
Deposit: N/A

Version 1.5.1

Funds are locked:
Taker fee tx failed at first, then deposit tx appeared as N/A.
Tried SPV resync.
Tried restoring from seed words.
Tried replacing the data directory form backups.
Funds still locked

(The trade does not appear as failed)

**Comment by leo816** [comment]
please provide a preferred btc address where you would like to receive the reimbursement

**Comment by pauls001** [comment]
Reimbursement adress: bc1qsjg0lpkhj04g2guutqaw488vykwknrga26g988

**Comment by pauls001** [comment]
Regarding the locked funds... I'm not able to send the trade to failed trades... So I can't unlock the funds... Any idea or suggestion?

I have read about quite a few people having the same issue, but it seems to be unsolved as for now... Should I just wait for v1.5.2

**Comment by leo816** [comment]
if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by leo816** [comment]
were you the taker or the maker for this trade?

**Comment by pauls001** [comment]
Oh... Okay, thanks anyway
