### ISSUE TITLE
Fee reimbursement for trade 635795

### ISSUE THREAD

**Issue by keuspastis** [bisq-network/support#638]
![image](https://user-images.githubusercontent.com/76541450/103047588-19a27480-45e0-11eb-9a1f-954862ed0d62.png)

![image](https://user-images.githubusercontent.com/76541450/103047623-36d74300-45e0-11eb-93bb-f934019604b6.png)

Maker fee transaction ID: 2b55560f4048d51e2e28c0b4cedaf7d19ecdda7699ccef381dd62d7c1f9fa397
Taker fee transaction ID: 5727a04a8fd0e54fd8d746f22c37d54f4d583a4d90f8ff79e6747f26c52cdafd
Displayed payout transaction ID: 816b0967b31b83d76075551ffb5f42c8cdaaad0f4406dda62968d7521f05e707

Bisq version: v1.5.1

**Comment by leo816** [comment]
please provide a preferred btc address where you would like to receive the reimbursement

**Comment by keuspastis** [comment]
Here's my BTC address: 1FGHkCnYUMjSLc9Pb3C2Zs728nPYMy1fxP

Thank you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by keuspastis** [comment]
@leo816 > please provide a preferred btc address where you would like to receive the reimbursement

Hi,

I still haven't received the reimbursement.

Thanks

**Comment by keuspastis** [comment]
@leo816  Can I please get an update ? It's been a while since you asked my BTC address and haven't heard back from you. 

Thanks.

**Comment by leo816** [comment]
fee reimbursement will be made soon

**Comment by leo816** [comment]
were you the maker or the taker? please provide all the details of the trade (not including the personal data)

**Comment by keuspastis** [comment]
@leo816  I was the buyer.

Trade details:
Trade ID					 : 635795-d71643a8-08fb-4783-a21c-b8cdaf7616b2-151
Trade date					 : 22/12/2020 @ 8:25:03pm

Maker fee transaction ID	 : 2b55560f4048d51e2e28c0b4cedaf7d19ecdda7699ccef381dd62d7c1f9fa397
Taker fee transaction ID	 : 5727a04a8fd0e54fd8d746f22c37d54f4d583a4d90f8ff79e6747f26c52cdafd
Deposit transaction ID		 : 5676f5cfc42d16bc71502733477bca2d65289da253a3ef09d04cf8eb7d9a6ad5
Delayed payout transaction ID: 816b0967b31b83d76075551ffb5f42c8cdaaad0f4406dda62968d7521f05e707

Let me know if you need anything else.

**Comment by keuspastis** [comment]
Hi @leo816, 

Any update regarding this reimbursement ?

Thanks.

**Comment by leo816** [comment]
were you the maker or the taker? next batch payout will be made soon

**Comment by keuspastis** [comment]
> were you the maker or the taker? next batch payout will be made soon

I was the taker. Thanks

**Comment by keuspastis** [comment]
@leo816  

Any ETA regarding this payment ?

Thanks

**Comment by leo816** [comment]
maker fee not published. Funds never left your wallet. Reimbursement is not justified.

**Comment by keuspastis** [comment]
They're locked and I can't unlock them. I was told to raise this claim to
get them unlock.
