### ISSUE TITLE
Fee reimbursement for trade: agkokvij

### ISSUE THREAD

**Issue by s3mia** [bisq-network/support#639]
![agkokvij](https://user-images.githubusercontent.com/76541825/103048834-e61f0600-455d-11eb-9eda-ddd57cc93d79.PNG)

Maker: 41db1f3183663e4668c898a1582ffe9c77b4f77eefa855fc16899bb96139e377
Taker: f2ff21e5b646516c7c493a3c70fc841fc659a4ca9b80716f8b76c77c678726bf
Deposit: N/A

Bisq version: 1.5.1

Other notes:
Deposit Tx failed to broadcast. 
Please reimburse fees. Thanks.

**Comment by leo816** [comment]
please provide a preferred btc address where you would like to receive the reimbursement

**Comment by s3mia** [comment]
Receiving Address:
bc1qjkp254adnura550wd60pg353pm7cg02vxgw6s4

**Comment by s3mia** [comment]
Also, I am the Maker of the trade. If that matters.

**Comment by s3mia** [comment]
Please use this updated receiving address:
bc1qe6hdy0nctrv4tyzk8y34psjsclx46yraw5m985

Thank you.

**Comment by s3mia** [comment]
My apologies. Trying to get better with my address management. Sorry for the inconvenience.
This is the last and final address to be used: 
bc1qxckm5k0ndc6gs3a453je0ht3vag0dkyp2vgqk2

**Comment by leo816** [comment]
were you the maker or the taker? please provide a screenshot of all the details

**Comment by s3mia** [comment]
I was the maker of the Tx.
I made the screenshot above as per the github-template. Let me know which other information you would need to see.

**Comment by leo816** [comment]
ok, this will be reimbursed next cycle

**Comment by leo816** [comment]
Reimbursed with #926
