### ISSUE TITLE
Fee reimbursement for trade XXN4SMI

### ISSUE THREAD

**Issue by mescalboiled** [bisq-network/support#641]
![Screenshot from 2020-12-24 10-25-15](https://user-images.githubusercontent.com/76553543/103078528-5ebfaa00-45d2-11eb-8901-96347b3c98f9.png)

Maker:  00fc377e80c7e7cccce452b2e90140dc22bad1b3f049ea7a37f3ad47e6d7b130
Taker: N/A
Deposit: N/A

Bisq version:
1.5.1 - Ubuntu 20.10

Other notes:
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 663928, myLockTime=665643
Trade state: INIT

**Comment by leo816** [comment]
please provide a preferred btc address where you would like to receive the reimbursement

**Comment by mescalboiled** [comment]
bc1q5ela2j6eu2vzg7teu37kqc2ts72ph9cykz2fvd

Thank you!

**Comment by mescalboiled** [comment]
here's the address: 36MxcEo88qy9EYb6XEjPUP2gkDCh9YcaLR

thank you

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
