### ISSUE TITLE
Fee reimbursement for trade 94730575

### ISSUE THREAD

**Issue by myfeeplease** [bisq-network/support#644]
![Screen Shot 2020-12-25 at 3 15 33 PM](https://user-images.githubusercontent.com/76598748/103141708-26999380-46c6-11eb-9ef1-257f7a40bc8f.png)

Maker:  1b5c54005d879e014912d6fdc145bebd3ec8254d6cba535a7cc938f5d1acebfa
Taker: e77821623e8a3722b84d42dfb172530d077ad03dbc7602d7ce858c2caa566eb3
Deposit: d8bb6997b4684b2c4a79585755eb3bd72e16fa6857db52531cd226b9e35b2653

Bisq version: 1.5.2

Other notes:

Top right ticker still shows 0.06 btc locked, however available funds show original amount before trade (minus the fee)

![Screen Shot 2020-12-25 at 3 18 26 PM](https://user-images.githubusercontent.com/76598748/103141602-9f97eb80-46c4-11eb-855a-bb90a330c793.png)

**Comment by myfeeplease** [comment]
reimbursement address: bc1qpeawxvp9mgyv3gyh3q0drtxa6cm457wxt2rhme

**Comment by leo816** [comment]
did you try doing a resync? https://bisq.wiki/Resyncing_SPV_file

**Comment by myfeeplease** [comment]
> did you try doing a resync to unlock the funds? https://bisq.wiki/Resyncing_SPV_file

several times in fact

**Comment by myfeeplease** [comment]
> did you try doing a resync to unlock the funds? https://bisq.wiki/Resyncing_SPV_file

is the fee reissued yet?

**Comment by myfeeplease** [comment]
Can someone please help

**Comment by myfeeplease** [comment]
Still waiting @leo816

**Comment by leo816** [comment]
fee reimbursement will be made soon, regarding your locked funds was the issue solved with the update? if not, can you please message me through keybase, my handle is @leo816. Send me all the information from the trade (bisq logs, contract in Json format and any issues you faced that may have caused this)

**Comment by leo816** [comment]
if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)

**Comment by myfeeplease** [comment]
> if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

thanks, this seems to have solved the issue
