### ISSUE TITLE
Fee reimbursement for trade 42ck7xa 

### ISSUE THREAD

**Issue by BillBrouwer** [bisq-network/support#645]
![6D4F85F9-726A-4162-AF3D-07FF0EA89E7D](https://user-images.githubusercontent.com/76629525/103163041-c35c4e00-47f8-11eb-96b2-4a43ef98be79.png)

Maker: 13b11ab5e747b66478bf43de0dba49380efd66a99438bd99987da9b55f08fc4f
Taker:  47085e4526743796629f26d3419e276df7df9621b720baebd7aa1b6c443c61e9
Deposit:  N/A

Bisq version: v1.5.1

Bisq BTC address for the reimbursement:

bc1qf9y056j9277guknu765lpw8xke3nhj5g46hr9f

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
