### ISSUE TITLE
Fee reimbursement for trade 025882

### ISSUE THREAD

**Issue by kingbeef** [bisq-network/support#646]
![image](https://user-images.githubusercontent.com/76661326/103178104-f250df00-484d-11eb-9a65-be59d2e53d54.png)

Maker: 4cdc284fd21efedde7c543a6cccd3c5247f5b66b54607ca3bdd49ff4f6bc09ea
Taker: d7d44ced52c3eb46f6cd54b32f562018139d997c57f4b7750be97c6ec78f7abf
Deposit: ca8379e21743dc5856d0ca1b23a081204ddf7ad8f83841a60fee7899fdbf55bd

Bisq version: v1.5.2

Other notes:

reimbursement address: bc1qzsa54md2vxrvex5mqd6vx3hzryz5dd2d45ssen

0.0060 BTC currently locked. Installed new version 1.5.2, deleted SPV and resynched twice, but issue still persists:

![image](https://user-images.githubusercontent.com/76661326/103178206-c4b86580-484e-11eb-87d5-eeb0a925f837.png)

**Comment by leo816** [comment]
did you update to version 1.5.2 and tried SPV resync?

**Comment by kingbeef** [comment]
Yes upgraded to 1.5.2, then tried SPV resynch twice.

**Comment by kingbeef** [comment]
Note: Upgraded to 1.5.3, resynched again, but issues persists.

**Comment by leo816** [comment]
any update after the 1.5.4? please provide your preferred btc address to make the fee reimbursement to.

**Comment by kingbeef** [comment]
No. Same problem exists. How much longer until I get reimbursed? It's been a month, address is the same as before:

bc1qzsa54md2vxrvex5mqd6vx3hzryz5dd2d45ssen

**Comment by leo816** [comment]
If you still have locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest is to delete the ClosedTrades and FailedTrades files in the db folder. You have to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by kingbeef** [comment]
OK, that worked but I'm confused, do you no longer owe me a reimbursement? What happened to that .0060 of BTC?

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
