### ISSUE TITLE
Fee reimbursement for trade mmbtx

### ISSUE THREAD

**Issue by ninjavisa** [bisq-network/support#647]
![Screenshot from 2020-12-27 20-44-44](https://user-images.githubusercontent.com/76663311/103178779-fa138200-4853-11eb-9abc-30fc57f8b16a.png)

SCREENSHOT  #HERE

Maker: c644ab2882bc4be7157e5d1ed7ef110e3f962fe8718feb119b98172e6ffdcd5b
Taker: 84b930c0d071aa3f42587bf4db85991ce6b92cc135037174fbb47d50777da7bd
Deposit: ed55f87c9f5352c7ea03f7ccd0eb960c328d7ab9b65c4a22c5807964b3cd9027

Bisq version: 1.5.1

Remburse address: bc1qwhrz9ztlrzjymyd2je5syxecfnygrsj84euuna

0.0060 BTC currently locked. Installed new version 1.5.2, deleted SPV and resynched twice, but issue still persists:

**Comment by leo816** [comment]
did you try open a mediation?

**Comment by ninjavisa** [comment]
No, the transaction was reverted so all good there, but my 0.0060 BTC are still locked and I need help to unlock it

**Comment by ninjavisa** [comment]
@leo816 Is there anything else I need to do? Or I just have to wait to get the 0.0060 BTC

**Comment by leo816** [comment]
please open a mediation or get in contact with our support team on keybase. They will help you unlock those funds

**Comment by leo816** [comment]
please provide your preferred btc address to make the reimbursement to

**Comment by ninjavisa** [comment]
BTC reimbursements address: bc1q6pme4r04k3glmuegsgs20w2zhgfgef4g8yzp3j

**Comment by ninjavisa** [comment]
@leo816 Do I have to do anything else?

**Comment by ninjavisa** [comment]
@leo816 any updates on this? please let me know if you need any more information from me

**Comment by pazza83** [comment]
Hi @leo816 looks liek @ninjavisa has provided the btc address for reimbursement.

Please can you add this to your to do list.

**Comment by leo816** [comment]
@ninjavisa   sorry for the late response, Reimbursement will be made soon. Regarding your funds locked: if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by leo816** [comment]
Payout made with #1028
