### ISSUE TITLE
Fee reimbursement for trade bPyYrU

### ISSUE THREAD

**Issue by catoptro-mancy** [bisq-network/support#648]
<img width="911" alt="Screen Shot 2020-12-27 at 2 54 34 PM" src="https://user-images.githubusercontent.com/76520635/103178765-c46e9900-4853-11eb-9fb7-cc843a4e8a3f.png">

Maker: 3f44ff04c4c2599cdfdcf92dfddc42c24ae54f099c88c2bf76ae29ee4d561974
Taker: 9c6c78547b681d5568ac82fd08c48d3ad5ca8409e66a7b98396ccd8a7371878f
Deposit: N/A

Bisq version: ?

Other notes:

An old failed transaction that now shows up in v.1.5.2

**Comment by catoptro-mancy** [comment]
BTC address for refund: 
bc1qfe038gnumfuel3efzhxk55gz2zqu55aqw4ma3x

**Comment by leo816** [comment]
Will be reimbursed with #703

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/703#issuecomment-753506665
