### ISSUE TITLE
Fee reimbursement for trade bPyYrU

### ISSUE THREAD

**Issue by catoptro-mancy** [bisq-network/support#649]
<img width="916" alt="Screen Shot 2020-12-27 at 3 01 32 PM" src="https://user-images.githubusercontent.com/76520635/103178865-c7b65480-4854-11eb-9a51-2904eb51d18a.png">

Maker:  3f44ff04c4c2599cdfdcf92dfddc42c24ae54f099c88c2bf76ae29ee4d561974
Taker: ee23e19a0f3eadaea8257e2300ebab926c39418712ce1bbba3c48c66886b59c4
Deposit: N/A

Bisq version: ?

Other notes:

Not a duplicate - I have to failed trades with same trade ID in v.1.5.2

**Comment by catoptro-mancy** [comment]
BTC address for refund: 
bc1qfe038gnumfuel3efzhxk55gz2zqu55aqw4ma3x

**Comment by leo816** [comment]
you can't have two trades with the same trade id
