### ISSUE TITLE
Fee reimbursement for trade xnqfj

### ISSUE THREAD

**Issue by catoptro-mancy** [bisq-network/support#651]
<img width="917" alt="Screen Shot 2020-12-27 at 3 15 37 PM" src="https://user-images.githubusercontent.com/76520635/103179115-a6eefe80-4856-11eb-8dd1-82af0225c87a.png">

Maker:  8184902948ff793c9d8f6f7e3d0e5f19d180d467c19672b7d42bbb401fa3021e
Taker: da4f8caeec80d27b2633681f55f75b94d8be0566f7e4414c084b5005618740ed
Deposit: 9889816e6c1e4711eb71a030ebeb24941f8c648a168328d0115ef0b686eaf9ad

Bisq version: ?

Other notes:

An old failed transaction that shows up after upgrade to v.1.5.2

**Comment by catoptro-mancy** [comment]
BTC address for refund: 
bc1qfe038gnumfuel3efzhxk55gz2zqu55aqw4ma3x

**Comment by leo816** [comment]
please do a SPV resync after downloading the latest version

**Comment by pazza83** [comment]
Closing as this was a successful trade
