### ISSUE TITLE
Fee reimbursement for trade FgA8mrZY

### ISSUE THREAD

**Issue by montosolver** [bisq-network/support#653]
![Screenshot_5](https://user-images.githubusercontent.com/26772245/103180841-ebe85480-4899-11eb-8e40-437fec8c9c29.png)

Maker:  f1853e08c6d4e9e59b21d7e81846c0816adad4d08e6e8777fad410eec49b1334
Taker: N/A
Deposit: N/A

Bisq version: 1.5.2

Other notes:

Timeout reached. Protocol did not complete in 60 sec.

Trade state: INIT

can I have the reimbursement to this Bitcoin address: bc1q3mj8rmvvs8wm0y4umf9nk706cynukl45jy8v2x

**Comment by chimp1984** [comment]
NACK
No taker fee was created so no reimbursement is justified!
@leo816 Please always check if the trade fee was published, if not there have been no funds left the wallet.
