### ISSUE TITLE
Fee reimbursement for trade FgA8mrZY

### ISSUE THREAD

**Issue by bisqreimbursement** [bisq-network/support#654]
![image](https://user-images.githubusercontent.com/76680392/103198158-f5001280-48e7-11eb-8d40-31771df7fe58.png)

Maker:  f1853e08c6d4e9e59b21d7e81846c0816adad4d08e6e8777fad410eec49b1334
Taker: N/A
Deposit: N/A

Bisq version: 1.5.2

Other notes:

Timeout reached. Protocol did not complete in 60 sec.

Trade state: INIT

can I have the reimbursement to this Bitcoin address: bc1qs7eec5063flhxu9p4zyqxjxz7r05chns4rq7ak

**Comment by chimp1984** [comment]
NACK
No taker fee was created so no reimbursement is justified!
@leo816 Please always check if the trade fee was published, if not there have been no funds left the wallet.
