### ISSUE TITLE
Fee reimbursement for trade FgA8mrZY

### ISSUE THREAD

**Issue by mescalboiled** [bisq-network/support#655]
![Screenshot from 2020-12-28 11-06-46](https://user-images.githubusercontent.com/76553543/103206849-1fa89600-48fd-11eb-8539-2a9d974b7596.png)

Maker:  f1853e08c6d4e9e59b21d7e81846c0816adad4d08e6e8777fad410eec49b1334
Taker: N/A
Deposit: N/A

Bisq version:
1.5.2 - Linux Ubuntu

Other notes:
Timeout reached. Protocol did not complete in 60 sec.

Address for reimbursement: 34sDee715PivcGJidvr5Xs9ebBwvqGEC24

**Comment by chimp1984** [comment]
NACK
No taker fee was created so no reimbursement is justified!
@leo816 Please always check if the trade fee was published, if not there have been no funds left the wallet.

**Comment by pazza83** [comment]
Closing as per comment above.
