### ISSUE TITLE
Fee reimbursement for trade d1stvnu

### ISSUE THREAD

**Issue by bisqsucksballs** [bisq-network/support#660]
![Bisq_sucks_ball_1](https://user-images.githubusercontent.com/76654850/103216838-5390b500-4917-11eb-9bd0-e8a826ea2db6.png)

Maker: 8f1f20dc7eef0d5079112af44d9d5a79e837d1e1d2b136d5ee888b58bfedca41
Taker: 872d602e418805c1b03b423b7d09fe1affb4a218b141f9753c241f1aaabb13bf
Deposit: 328fe8d54380d64574514a9d756cff4ce6012a3ecf5d1737e6d4d08f9c72c57c
Payout: 136e0de2385b9bcd1ac6e0c24eab195d8e3d4716a7b8651d12b179a9d720313a

Bisq version: 1.5.2

Other notes:

![Bisq_sucks_ball_3](https://user-images.githubusercontent.com/76654850/103217004-cef26680-4917-11eb-90a1-e2912dbb2de9.png)

**Comment by bisqsucksballs** [comment]
If there is any locked funds send to bc1q2gxjznjxdcw659mcnzlm5p4uezdwy2fxyenrzq

**Comment by leo816** [comment]
Did you update and send the trade to fail trades? I will make the fee reimbursement to that address. If funds remain locked please contact our support team on keybase

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet. regarding your locked funds: if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades
