### ISSUE TITLE
Fee reimbursement for trade hxubrv

### ISSUE THREAD

**Issue by hseerrg** [bisq-network/support#661]
<img width="393" alt="2020-12-28 14_47_48-" src="https://user-images.githubusercontent.com/76692676/103218628-6f925780-4913-11eb-8b02-6bbb72569a20.png">

Maker:  9f391f7ec2312da46eb366bc1f5625eee4f3a76c82155dcab803274b54a63110
Taker: b9c72ea244042ecc18e826868a5a0035ce7b587a1da2e8968a4ce905bcdc98b2
Deposit: 702faa87c508fd61b6d1b6abdc6bc198855200ca1366139be0c722904f1646c6

Bisq version: v1.5.2

Please reimburse deposit to: bc1q2m8knn76uf3zc0z4nlyuseqr89ep438a44vdgc

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
