### ISSUE TITLE
Fee reimbursement for trade CMDZDFYU

### ISSUE THREAD

**Issue by monkfruit** [bisq-network/support#662]
![Screen Shot 2020-12-28 at 09 11 41](https://user-images.githubusercontent.com/76693667/103220669-df421b80-48ee-11eb-8065-ac22c8730c20.png)

Maker:  97b7c8961d369320278d2aafe92069cace8a5038cfba0c7f85c06ab82a0652eb
Taker: N/A
Deposit: N/A

Bisq version: 1.5.1

Please reimburse deposit to: bc1qwu34lk6cgul4xwpu4200zgcqyrzyga6nq7pkrh

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
