### ISSUE TITLE
Fee reimbursement for trade FgA8mrZY

### ISSUE THREAD

**Issue by molacek** [bisq-network/support#663]
![image](https://user-images.githubusercontent.com/44723196/103223516-b178c900-4926-11eb-946e-5d90ee24db58.png)

Maker:  f1853e08c6d4e9e59b21d7e81846c0816adad4d08e6e8777fad410eec49b1334
Taker: N/A
Deposit: 0.034419 BTC

Bisq version: 1.5.2

Other notes: Issue caused when taking offer to sell BTC. Connection timed out when confirming order. 

Thank you.

**Comment by leo816** [comment]
please provide the btc address where you would like to receive the payment

**Comment by molacek** [comment]
bc1q3jecqrvu87tmw5vdkwms24t95q5uwwu3fzyuk8

Thank you in advance.

**Comment by chimp1984** [comment]
No taker fee was created so no reimbursement is justified!
@leo816 Please always check if the trade fee was published, if not there have been no funds left the wallet.

**Comment by molacek** [comment]
I'm sorry guys, I misinterpreted the trade data. I didn't want to cause any harm. You can close this ticket now. Thank you.

**Comment by chimp1984** [comment]
No worry, not your fault. Not that trivial to interpret all the data correctly...

**Comment by chimp1984** [comment]
@molacek Can you post the full (long) trade ID? It seems the maker has some bug causing all take-attempts to fail. 
Can you PM me on keybase (same user name) the log files? If you see any error message in the app (trade details) you can post it here as well.

**Comment by molacek** [comment]
FgA8mrZY-2f62ee69-84b9-4f85-9969-bc4024ba0f25-142
