### ISSUE TITLE
Fee reimbursement for trade 19266

### ISSUE THREAD

**Issue by thereisaplace** [bisq-network/support#664]
![image](https://user-images.githubusercontent.com/76697885/103227601-bf195900-48fc-11eb-8048-06751dc56716.png)
![image](https://user-images.githubusercontent.com/76697885/103227661-e4a66280-48fc-11eb-861d-3102d1a1768f.png)

Maker:  a11e1f1c95d14ecf5a7ad14dd2dfc84ecdb6ea086a1430895beb6f7b013611f7
Taker: 904eec3499c6ae8e1886ef663c2492e2840dcc78b5eec3336d58b7924b5c9dce
Deposit: f3517aaf0f4ce91954c43d00a93d3a2f6880e048e155c070bc6e2efa17e6869e

Bisq version: 1.5.2

Please reimburse fees to: 

LOCKED FUNDS:  Ticker in top right of UI shows locked BTC for past 3 failed trades. Is that a correct amount?
![image](https://user-images.githubusercontent.com/76697885/103228822-ad858080-48ff-11eb-8c91-3781c7463458.png)

OTHER NOTES: 
Have performed multiple SPV/resyncs.
Upgrade to 1.5.2 allowed me to fail the trade.
This is the 3 of 3 trade that has failed in this manner over the past two weeks (had many other successful trades during that time tho).

**Comment by leo816** [comment]
hi, did you update to the new version and tried again to SPV resync?

**Comment by thereisaplace** [comment]
Yes, have upgraded to 1.5.2 to 1.5.3 and now 1.5.4.  Have performed many SPV/resyncs with no changes. Even though the trade failed I was still charged TAKER fees.

Please reimburse to bc1qtls9ldgsyl2mqa4hs2p6z6ypld33qjdacs3yl4

**Comment by leo816** [comment]
"if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades"

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
