### ISSUE TITLE
Fee reimbursement for trade 94730575

### ISSUE THREAD

**Issue by thereisaplace** [bisq-network/support#665]
![image](https://user-images.githubusercontent.com/76697885/103229956-28e83180-4902-11eb-9485-3c1fe1b30f4b.png)
![image](https://user-images.githubusercontent.com/76697885/103229977-39001100-4902-11eb-8edb-ad9c5c0b20d5.png)
Maker:  1b5c54005d879e014912d6fdc145bebd3ec8254d6cba535a7cc938f5d1acebfa
Taker: e77821623e8a3722b84d42dfb172530d077ad03dbc7602d7ce858c2caa566eb3
Deposit: d8bb6997b4684b2c4a79585755eb3bd72e16fa6857db52531cd226b9e35b2653

Bisq version: 1.5.2

Please reimburse fees to: 

LOCKED FUNDS:  Ticker in top right of UI shows locked BTC for past 3 failed trades. Is that a correct amount?
![image](https://user-images.githubusercontent.com/76697885/103228822-ad858080-48ff-11eb-8c91-3781c7463458.png)

OTHER NOTES: 
Have performed multiple SPV/resyncs.
Upgrade to 1.5.2 allowed me to fail the trade.
This is the 3 of 3 trade that has failed in this manner over the past two weeks (had many other successful trades during that time tho).

**Comment by leo816** [comment]
please update and try again. If it continues with the same issue let me know. when you click cmd + e do you see the total amount or are the locked funds still missing? 

please provide a preferred btc address for the payout.

**Comment by thereisaplace** [comment]
Yes, have upgraded to 1.5.2 to 1.5.3 and now 1.5.4.  Have performed many SPV/resyncs with no changes. 

The "locked funds" finally cleared out... I think the 1.5.4 took care of that. The trade eventually failed but I was still charged  fees.

Please reimburse to bc1q2t6ewpnqle89779e44gkj5egukugdt7kaqpdw7

**Comment by thereisaplace** [comment]
oops

**Comment by pazza83** [comment]
Hi @leo816 

Please can you add this to your to do list.

BTC address has been provided.

**Comment by pazza83** [comment]
Hi @leo816 please can you add this to your reimbursement to do list.

**Comment by thereisaplace** [comment]
Hello anyone - Is there any chance of getting this reimbursement this year? I have provided everything asked of me and here we are 11 months later. Help please?

**Comment by pazza83** [comment]
> Hello anyone - Is there any chance of getting this reimbursement this year? I have provided everything asked of me and here we are 11 months later. Help please?

Thanks for the chase up I will mention this to @leo816 in our next support meeting

**Comment by leo816** [comment]
added back to the list, reimbursements will be made tomorrow

**Comment by leo816** [comment]
Payout made with #1028
