### ISSUE TITLE
Fee reimbursement for trade MXTUF

### ISSUE THREAD

**Issue by thereisaplace** [bisq-network/support#666]
![image](https://user-images.githubusercontent.com/76697885/103230271-030f5c80-4903-11eb-99b3-b5a22b0c7f49.png)
![image](https://user-images.githubusercontent.com/76697885/103230293-11f60f00-4903-11eb-9b86-a7483df3d75c.png)

Maker:  0e13d4e3b893c5b5aca8ae9c556500a2ccddc81d67fbdca36a4e3e687ad29d57
Taker: 82625f9985950418cc1442421e38391a3aeeca99726006cf25aafb19f3f3f2fe
Deposit: d4eeec523fb466d7ee8a846c03d701e1d58a021470a8f2409f080f01e358c2ba

Bisq version: 1.5.2

Please reimburse fees to: 

LOCKED FUNDS:  Ticker in top right of UI shows locked BTC for past 3 failed trades. Is that a correct amount?
![image](https://user-images.githubusercontent.com/76697885/103228822-ad858080-48ff-11eb-8c91-3781c7463458.png)

OTHER NOTES: 
Have performed multiple SPV/resyncs.
Upgrade to 1.5.2 allowed me to fail the trade.
This is the 3 of 3 trade that has failed in this manner over the past two weeks (had many other successful trades during that time tho).

**Comment by thereisaplace** [comment]
I have upgrade to 1.5.4 and done multiple SPV/resycns. Failed trade but still charged fees.

Please reimburse to bc1qxanqmdss445zfzrl5ulp2z06k6w95nhwtzx83d

**Comment by pazza83** [comment]
Hi @thereisaplace I am closing as this appears to be a successful trade.  Deposit tx ID was successful
