### ISSUE TITLE
Fee reimbursement for trade qxccni

### ISSUE THREAD

**Issue by IronBitcoinHodl** [bisq-network/support#667]
![Screenshot 2020-12-28 at 18 17 54 copy](https://user-images.githubusercontent.com/73696029/103231939-6caa5d80-4939-11eb-85fa-39c48ebc513d.jpg)

Maker:  d5862bd2f3c44bcfb02654d6709d50c77b6255d1e27e9f7cd990540764e14c49
Taker: fae8ca80ff76a2d5f6575e95211b99ce562c84ca4f3ca419af8f6d54d29ab059
Deposit: 764fc56227e5bb376d10e39755c3bc15268f4187bfe5e2048b7b49b11294ceb7

Bisq version: v1.5.2 

Other notes:

Trade stuck waiting for blockchain confirmation.

![Screenshot 2020-12-28 at 18 23 51 copy](https://user-images.githubusercontent.com/73696029/103232181-14279000-493a-11eb-9e5e-b56437b18630.jpg)

**Comment by leo816** [comment]
payout was made here

**Comment by refund-agent2** [comment]
This trade is into arbitration now.
Delayed payout tx:13db8816d784c24874bd6083986eb6ca334df36d65d5f77a05d384b99c7eca9
