### ISSUE TITLE
Fee reimbursement for trade vswhgm

### ISSUE THREAD

**Issue by northben** [bisq-network/support#669]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/2553902/103244460-5b058d80-491a-11eb-9f94-069ed75249e6.png">

Maker:  79ae33d037f28087cfa43f760a51971c40e2948dac388bdbdced197abe889238
Taker: ...........
Deposit: ..........

Bisq version:

> 1.5.2

Other notes:

error message:
> An error occurred at task: TakerProcessesInputsForDepositTxResponse
> Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 665169, myLockTime=666146

**Comment by pazza83** [comment]
Hi @northben 

The taker transaction failed so you did not lose any fees on this trade.

Let me know if you have any questions.
