### ISSUE TITLE
Reimburse fees for failed trade gVBDzEd

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#67]
@cybairfly commented on [Fri Feb 02 2018](https://github.com/bisq-network/exchange/issues/1319)

![error](https://user-images.githubusercontent.com/18344357/35737299-56d099ae-082b-11e8-8ea6-ce6f57aa5b5f.png)
An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

[bisq.log](https://github.com/bisq-network/exchange/files/1689600/bisq.log)

**Comment by cbeams** [comment]
Thanks, @cybairfly. Can you send me the ID (hash) of the taker fee transaction? You should be able to find this in `Funds->Transactions`.

**Comment by ManfredKarrer** [comment]
It can be that the maker is using an older Bisq version and thus have caused the timeout or that it is a case where the connection just got lost in the critical moment when the trade message should got transferred. Lets observe if we get more such cases.

**Comment by cybairfly** [comment]
TX ID: 30b79b0584ad8f86f29113d16bb7ff1b576eafc28831ff3f51d065771462fdd6

Funds were returned safely to my Bisq wallet. Thanks, @cbeams @ManfredKarrer

**Comment by cbeams** [comment]
Staged for reimbursement in a975981.

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/70#issuecomment-370372195.
