### ISSUE TITLE
Fee reimbursement for trade WS1DuHa3

### ISSUE THREAD

**Issue by northben** [bisq-network/support#670]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/2553902/103244628-d9fac600-491a-11eb-8267-154df57a8567.png">

Maker:  42bedb767e32e8984c84e395fec2f80f6d6151a08be9de822494c630ffb3e0cd
Taker: ...........
Deposit: ..........

Bisq version:

> 1.5.2

Other notes:

error message:
> An error occurred at task: TakerProcessesInputsForDepositTxResponse
> Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 665169, myLockTime=666144

**Comment by pazza83** [comment]
Hi @northben 

The taker transaction failed so you did not lose any fees on this trade.

Let me know if you have any questions.
