### ISSUE TITLE
Fee reimbursement for trade hxubrv

### ISSUE THREAD

**Issue by maxowenwilliams** [bisq-network/support#671]
![p1](https://user-images.githubusercontent.com/76709518/103246203-f1f63800-4962-11eb-8257-eab7098aba73.png)
![p2](https://user-images.githubusercontent.com/76709518/103246204-f28ece80-4962-11eb-8963-5de8b7c9a57b.png)

Maker:  9f391f7ec2312da46eb366bc1f5625eee4f3a76c82155dcab803274b54a63110
Taker: b9c72ea244042ecc18e826868a5a0035ce7b587a1da2e8968a4ce905bcdc98b2
Deposit: 702faa87c508fd61b6d1b6abdc6bc198855200ca1366139be0c722904f1646c6

Bisq version: 1.5.2

Other notes:
Get an error message with "The deposit transaction (the 2-of-2 multisig transaction) is missing."
Request BSQ taker fee reimbursement to: B18aE5MzvZfFt2XPBtFSdy3nzc2pKo2cTXw

**Comment by pazza83** [comment]
Hi @maxowenwilliams 

Thanks for posting.

Please can you repost your screen shot showing if you were the maker or taker.

Many thanks

**Comment by maxowenwilliams** [comment]
Sure, here is the full screenshot with our personal details blanked out.
![Screenshot from 2021-08-29 10-13-19](https://user-images.githubusercontent.com/76709518/131243646-f53f083f-7cce-46ed-8a89-20578bc1bbeb.png)

**Comment by pazza83** [comment]
Hi @maxowenwilliams 

Thanks I can see you are due a reimbursement for your fees.

Please can you provide a BTC address for reimbursement (it is made in BTC no BSQ)

Many thanks

**Comment by maxowenwilliams** [comment]
Thanks @pazza83, the following BTC address will do:

1M6Q4K677dd2Nf4rsbf8wSH3HNDpJBydmn

**Comment by pazza83** [comment]
Thanks,

@leo816 please can you add this reimbursement to your to do list

**Comment by pazza83** [comment]
Hi @leo816 please can you add this to your reimbursement to do list.

**Comment by leo816** [comment]
Fee Reimbursement paid out with #1033
