### ISSUE TITLE
Fee reimbursement for trade 7T2LOU

### ISSUE THREAD

**Issue by GrinchOfChristmas** [bisq-network/support#672]
![image](https://user-images.githubusercontent.com/76711431/103248874-e9a2fa80-496c-11eb-99b2-3bb3dfc45a43.png)

Maker:  4dbbca3a198642d205e84eac88a3b0afcca7ca8ccb658fd7b47b6a231f418c7e
Taker: 14aded57725fb8d460543930272d6c4d4f7bcd06dde4b4ed380c8c45db3f15c4
Deposit: 35f5d8371e0f89372f156d6bc5a03b8e3a2c2805744670e93d836e53e801ad14

![image](https://user-images.githubusercontent.com/76711431/103248899-050e0580-496d-11eb-80bc-e619890d6e25.png)

Bisq version: v1.5.2

**Comment by GrinchOfChristmas** [comment]
how do I get someone to look at this please?

**Comment by pazza83** [comment]
Hi @GrinchOfChristmas 

Sorry for the late reply.

Please can you repost screen shot showing if you were the taker or maker and include a btc address for reimbursement.

**Comment by GrinchOfChristmas** [comment]
Hi, I was maker for trade 7T2LOU.

Please send to  bc1q6yxu4uf39axwu2ydtekgs6kjn5phf59kwfunyp


thanks!    On Sunday, August 29, 2021, 11:40:02 PM GMT+2, pazza ***@***.***> wrote:  
 
 


Hi @GrinchOfChristmas

Sorry for the late reply.

Please can you repost screen shot showing if you were the taker or maker and include a btc address for reimbursement.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pazza83** [comment]
Hi @GrinchOfChristmas 

Many thanks, the taker transaction failed:

https://mempool.space/tx/14aded57725fb8d460543930272d6c4d4f7bcd06dde4b4ed380c8c45db3f15c4

Therefore no fees where lost on this trade.

If you have any questions please reach out to me on support at keybase.
