### ISSUE TITLE
Fee reimbursement for trade TweBwD

### ISSUE THREAD

**Issue by XioaYao** [bisq-network/support#673]
![image](https://user-images.githubusercontent.com/76712197/103250432-aeec9280-496b-11eb-976c-747bbf304e6a.png)

Maker:  389e63eb630a6dc9d1091055bd884e6b7901b9eb8fa246bf1f4e055f576644ad
Taker: b88a2fd58ca74d88fe33d115f0f4cd76c87b01b8ed880e870f4a94c4f10f56af
Deposit: f776704462de7899d1572f11c0f5815c21d25b2e0f4afed0380ccfbe345537b6

Bisq version: v.1.5.1

Thanks in advance.

**Comment by pazza83** [comment]
Hi @XioaYao 

Please can you repost your screenshot showing if you were the maker or taker and also a btc address for reimbursement.

Many thanks
