### ISSUE TITLE
Fee reimbursement for trade FgA8mrZY

### ISSUE THREAD

**Issue by monkeyman1979** [bisq-network/support#674]
<img width="887" alt="Screen Shot 2020-12-29 at 11 22 57 AM" src="https://user-images.githubusercontent.com/37835299/103277095-83e45c00-49c8-11eb-8f56-368953032bcd.png">

<img width="889" alt="Screen Shot 2020-12-29 at 11 23 09 AM" src="https://user-images.githubusercontent.com/37835299/103277122-9494d200-49c8-11eb-9cb7-ca30bec97bc8.png">

Maker:  f1853e08c6d4e9e59b21d7e81846c0816adad4d08e6e8777fad410eec49b1334
Taker: N/A
Deposit: N/A

Bisq version: 1.5.2

**Comment by huey735** [comment]
Were you the maker or taker in this trade?

**Comment by fran-rial** [comment]
I was the taker
<img width="1268" alt="Screenshot 2020-12-30 at 18 19 54" src="https://user-images.githubusercontent.com/31315415/103370100-38b37180-4acc-11eb-979e-800736027610.png">
Logs are attached to https://github.com/bisq-network/bisq/issues/5023

**Comment by huey735** [comment]
If no Taker fee transaction was broadcast there's no fee to be reimbursed.
