### ISSUE TITLE
Fee reimbursement for trade XkVnF

### ISSUE THREAD

**Issue by monkeyman1979** [bisq-network/support#675]
<img width="887" alt="Screen Shot 2020-12-29 at 11 34 54 AM" src="https://user-images.githubusercontent.com/37835299/103277778-0e798b00-49ca-11eb-821a-11488f2c7220.png">

<img width="886" alt="Screen Shot 2020-12-29 at 11 35 03 AM" src="https://user-images.githubusercontent.com/37835299/103277787-15080280-49ca-11eb-8cbb-3faca059fcb2.png">

Maker:  1ff86587c25091412e74fb1c86cf44d9aa8b4968c9dac16db9d3ca2dc22f97a3
Taker: N/A
Deposit: N/A

Bisq version: 1.5.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: An error occurred at task: ApplyFilter Other trader is banned by their trading account data.

**Comment by pazza83** [comment]
Hi @monkeyman1979 

Please can you repost the screen shot showing if you were the maker or taker and include a refund btc address.

Many thanks
