### ISSUE TITLE
Fee reimbursement for trade XkVnF

### ISSUE THREAD

**Issue by mescalboiled** [bisq-network/support#677]
![Screenshot from 2020-12-29 11-49-23](https://user-images.githubusercontent.com/76553543/103279010-21418f00-49cd-11eb-9c83-63b9f8f2dc74.png)

Maker:  1ff86587c25091412e74fb1c86cf44d9aa8b4968c9dac16db9d3ca2dc22f97a3
Taker: N/A
Deposit: N/A

Bisq version:
1.5.2 - Linux Ubuntu

Other notes:
An error occurred at task: ApplyFilter
Other trader is banned by their trading account data.
paymentAccountPayload=SEPA - Account owner full name: G*** L*** M***, IBAN: ES***, BIC: CA***, Country of bank: ES

BTC address for reimbursement: 34sDee715PivcGJidvr5Xs9ebBwvqGEC24

**Comment by pazza83** [comment]
Hi @mescalboiled 

The taker transaction failed for this trade. No fees where lost.

Let me know if you have any questions.
