### ISSUE TITLE
Fee reimbursement for trade NVDFODI

### ISSUE THREAD

**Issue by fupm** [bisq-network/support#678]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![NVDFODI](https://user-images.githubusercontent.com/76731476/103278854-c445d900-49cc-11eb-83a2-cda3c9e037c6.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  425f8cfb0806505782895bb3995244d6b6c850db7074e798199fe908498a9bd6
Taker: deef841e6d2d40ada05af78ef1fd2239727fe631d6203203f6d82e3279d0094f
Deposit: 12ca873240e928b79903008f3f92d9d0033341029d126dfc95b3def18eb14d62

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.2

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by fupm** [comment]
I also have the payout and deposit blocked, but I can't find a template for that. What should I do?

**Comment by pazza83** [comment]
Hi @fupm thanks for posting, apologies for the late reply.

Please can you repost the screen shot showing  if you were the maker or taker.

Please also include an address for reimbursement.
