### ISSUE TITLE
Fee reimbursement for trade 94639336

### ISSUE THREAD

**Issue by Dic123** [bisq-network/support#681]
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/76741815/103296177-50a7ca00-49d4-11eb-97b5-f684d938e10e.png)

Maker: 5cade772f520480bcd4027541315d57d6c222643e7639cbde9fc42a10e50fa07
Taker: bbfb8a2297c3b48e8c2cef048118a217b8ffc221f78166856de4bc1fdcccd2e1
Deposit: N/A

Bisq version: 1.5.2

**Comment by pazza83** [comment]
Hi @Dic123 

Thanks for posting.

Please can you send a screen shot of the trade for which you are claiming reimbursement for.

Please also include a btc address for reimbursement.

Many thanks
