### ISSUE TITLE
Fee reimbursement for trade pnvfz

### ISSUE THREAD

**Issue by ads103** [bisq-network/support#683]
![image](https://user-images.githubusercontent.com/6362544/103358435-2eb55280-4a7b-11eb-9885-ca1659377072.png)

Maker: e8dbb6c56fbcf074fc0da4f6e8403245595ab5ccd30ac703b7e2c3ec950a62e7
Taker: 00a0a9fc6d25eef92e81c0049347872d90a25dba0f5ee88734c8c958830af539
Deposit: N/A

Bisq version: 1.5.3

Other notes:
Timeout reached. Protocol did not complete in 60 sec.

BTC address for refund:
38Y2FdEaMkTYrzLV4gwA9XVnSCeE72zK9L

**Comment by pazza83** [comment]
Hi @ads103 

Thanks for posting. I can see you have lost fees for this trade.

@leo816 will arrange reimbursement for yourself.

**Comment by pazza83** [comment]
Hi @leo816 please can you add this to your reimbursement to do list.

**Comment by leo816** [comment]
Fee Reimbursement paid out with #1033
