### ISSUE TITLE
uYXaBXT - TRADE ID

### ISSUE THREAD

**Issue by teamm80** [bisq-network/support#685]
my funds are locked, please help me move them to available balance.

Contract as json:
{
  "offerPayload": {
    "id": "uYXaBXT-f9e2ddc0-5cea-4b51-8a7f-9db8fe4c8c74-151",
    "date": 1608391548567,
    "ownerNodeAddress": {
      "hostName": "hss3fyj35pgi5jmh.onion",
      "port": 9999
    },
    "direction": "SELL",
    "price": 0,
    "marketPriceMargin": 0.01,
    "useMarketBasedPrice": true,
    "amount": 15800000,
    "minAmount": 2000000,
    "baseCurrencyCode": "BTC",
    "counterCurrencyCode": "EUR",
    "arbitratorNodeAddresses": [],
    "mediatorNodeAddresses": [
      {
        "hostName": "apbp7ubuyezav4hy.onion",
        "port": 9999
      },
      {
        "hostName": "a56olqlmmpxrn5q34itq5g5tb5d3fg7vxekpbceq7xqvfl3cieocgsyd.onion",
        "port": 9999
      },
      {
        "hostName": "sjlho4zwp3gecspf.onion",
        "port": 9999
      }
    ],
    "paymentMethodId": "REVOLUT",
    "makerPaymentAccountId": "967c5bc4-7c20-4655-bb3f-76a2fc2334b2",
    "offerFeePaymentTxId": "93482628f72dbadb7e365030d46c979eab5b21443eb9d58b8b4a537e0e0269f4",
    "versionNr": "1.5.1",
    "blockHeightAtOfferCreation": 662063,
    "txFee": 27144,
    "makerFee": 15800,
    "isCurrencyForMakerFeeBtc": true,
    "buyerSecurityDeposit": 2370000,
    "sellerSecurityDeposit": 2370000,
    "maxTradeLimit": 25000000,
    "maxTradePeriod": 86400000,
    "useAutoClose": false,
    "useReOpenAfterAutoClose": false,
    "lowerClosePrice": 0,
    "upperClosePrice": 0,
    "isPrivateOffer": false,
    "extraDataMap": {
      "capabilities": "0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16",
      "accountAgeWitnessHash": "c258359b056d0fdf7030dba72d8418ddd127308e"
    },
    "protocolVersion": 3
  },
  "tradeAmount": 12500000,
  "tradePrice": 193638783,
  "takerFeeTxID": "4ff1ae781a165a1d436cb7abbf096f60e59a987349bd2a2cf51f66e0ee2f235e",
  "buyerNodeAddress": {
    "hostName": "ef4zybrg7vr6yjpjkjemob4lh3tqd6sfkiuw4vajdj7dr7ybs2u3v7yd.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "hss3fyj35pgi5jmh.onion",
    "port": 9999
  },
  "mediatorNodeAddress": {
    "hostName": "sjlho4zwp3gecspf.onion",
    "port": 9999
  },
  "isBuyerMakerAndSellerTaker": false,
  "makerAccountId": "1089171059",
  "takerAccountId": "2000980111",
  "makerPaymentAccountPayload": {
    "accountId": "+000",
    "paymentMethodId": "REVOLUT",
    "id": "967c5bc4-7c20-4655-bb3f-76a2fc2334b2",
    "maxTradePeriod": -1
  },
  "takerPaymentAccountPayload": {
    "accountId": "XXXX",
    "paymentMethodId": "REVOLUT",
    "id": "1babd725-249b-43b9-9891-5f2d4d03b13d",
    "maxTradePeriod": -1
  },
  "makerPayoutAddressString": "bc1qcymclkxce209zp72fuk2w5asl08ek7827j7nwf",
  "takerPayoutAddressString": "bc1qayst20wtlnxnu3rffsl83d7cduasaavmr7twka",
  "lockTime": 665210,
  "refundAgentNodeAddress": {
    "hostName": "3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion",
    "port": 9999
  }
}

BuyerMultiSigPubKeyHex: 02a6c7f4df19da1abae334e2079a5f5c4e55563f3dac7e34d6d5aa176ea207ab43
SellerMultiSigPubKeyHex: 0385c0efe214a8a2b0f6dc9994d53389484f5a76c9f75fdc6a045dd4f79b80e961

BuyersAccountAge: Payment account created 47 days ago.
SellersAccountAge: Payment account created 992 days ago.

**Comment by teamm80** [comment]
please help!

**Comment by MwithM** [comment]
Make sure it's not a just a visual bug.
https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1

You'll find faster replies at Keybase. https://keybase.io/team/bisq
