### ISSUE TITLE
Fee reimbursement for trade 19266

### ISSUE THREAD

**Issue by s3mia** [bisq-network/support#686]
![19266](https://user-images.githubusercontent.com/76541825/103392085-134a5600-4b14-11eb-92d9-6bd162df34b9.PNG)

Maker: a11e1f1c95d14ecf5a7ad14dd2dfc84ecdb6ea086a1430895beb6f7b013611f7
Taker: 904eec3499c6ae8e1886ef663c2492e2840dcc78b5eec3336d58b7924b5c9dce
Deposit: f3517aaf0f4ce91954c43d00a93d3a2f6880e048e155c070bc6e2efa17e6869e
Delayed Payout: 4bbfaa3c225e45a0575dadff9ad2e8b0faa7d762001dab4f7466ea60a9e19cf1

Bisq version: WIN10 v.1.5.2

Other notes:
Trade failed, no Deposit Tx was created. Please reimburse fees. Thanks.

**Comment by s3mia** [comment]
Please use this receiving address for reimbursement:
bc1qld5jxntf8a249mdwj77jdjz9phnwyae3eyslwp

**Comment by leo816** [comment]
Reimbursed with #926
