### ISSUE TITLE
Fee reimbursement for trade 0A6I6u

### ISSUE THREAD

**Issue by Johannas333** [bisq-network/support#687]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Knipsel](https://user-images.githubusercontent.com/76809440/103406156-094b4600-4b5a-11eb-92f2-10b5882d532e.PNG)
![Knipsel1](https://user-images.githubusercontent.com/76809440/103406523-419f5400-4b5b-11eb-9531-c403e9533a75.PNG)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  fd69064d95ac04fffe5a4f40d02d603da7764ecf842be13cf6ea7c12ea5365f4
Taker: c9cdacf893e609dfa81930dd8eeb57cffd302d87870b17f2c6898d3f783876c2
Deposit: 664bc839a594a3018a8a163f41fd19c1f25275b628aa2b1e65f1c9f295d23476

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.5.3 

>_Provide the Bisq client version to help developers identify the causing issue. Starting with v1.5.0 or v1.5.1

Other notes:

>_Issue [#197](This trade failed and no funds were sent to escrow. However your Taker fee transaction was published. When a trade fails we recommend the traders to request reimbursement (https://github.com/bisq-network/support/issues/new/choose) and move said trades to Failed trades. And do a SPV resync if the UI still shows funds as locked for this trade: https://bisq.wiki/Resyncing_SPV_file#From_the_Bisq_interface.) can be used as a good example of a correct reimbursement request._

**Comment by Johannas333** [comment]
It's not clear how to move this transaction to 'Failed trades'. ?? 

Kind regards, J.

**Comment by pazza83** [comment]
Hi @Johannas333 

Please let me know if this is still an issue.

Normally if the red arrow to move to failed trades is not present, an SPV resync will help give you the option to move the trade to failed.
