### ISSUE TITLE
Fee reimbursement for trade NICQBG

### ISSUE THREAD

**Issue by winstonschmit** [bisq-network/support#689]
**Ticket closed on Dec 8, 2020 10:16:44 PM
Mediator node address: sjlho4zwp3gecspf.onion:9999

Summary:
Trade ID: NICQBG
Currency: GBP
Trade amount: 0.01 BTC
Payout amount for BTC buyer: 0.0060 BTC
Payout amount for BTC seller: 0.0160 BTC

Reason for dispute: Other

Summary notes:
tx bugged

-----BEGIN SIGNATURE-----
302d02150085836cfcf62986179b17e91cf5a1475ca88044fa02144bc2d00a428c941f3f7539a972593a00a770a9cb
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator**

Maker:  39f57abade3dc5e8dd21aab0e14f04eaf0d5b82af735ebc738b80010aa58303f
Taker: 386f15f96944132b2eace41d8645e077c701668526303fb1c1b78e9034ad4b25
Deposit: c78540928fa3fd877b41bb604f26b47448adc93e3e0d55bcc3cd564db2545f93

Bisq version: 1.4.2.0

Other notes:
Mediator suggestion accepted but re-imbursement still pending

**Comment by pazza83** [comment]
Hi @winstonschmit 

Thanks for posting.

Please can you send a screen shot of the failed trade details screen.

Many thanks
