### ISSUE TITLE
Reimburse fees for failed trade VLHYA

### ISSUE THREAD

**Issue by bitbam** [bisq-network/support#69]
Taker fee ID: 759a99576a1edc0431c9797487eadb1402e6dac81a64ab0dfe5e1e0df82f62ce
Maker fee ID: 1501d9bf64dfc46f87739c4c12e628f52f3e66cf42094534667629b0a1a25d76

Trade state: TAKER_FEE_PUBLISHED
Error message: A timeout has occurred

Many thanks @cbeams and @keo-bisq  for addressing this, really appreciated.

**Comment by cbeams** [comment]
What version of Bisq were you running, @bitbam?

**Comment by bitbam** [comment]
@cbeams 0.6.3 on the day this happened

**Comment by cbeams** [comment]
Ok. We'll reimburse this on Friday Feb 9th in a batch transaction. See #70.

**Comment by cbeams** [comment]
Staged for reimbursement in b5f34a4.

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/70#issuecomment-370372195.
