### ISSUE TITLE
Fee reimbursement for trade 9636091

### ISSUE THREAD

**Issue by sepu85** [bisq-network/support#690]
![image](https://user-images.githubusercontent.com/22507864/103421872-e5f6ba00-4b9e-11eb-9295-ba1f97f1bba6.png)
![image](https://user-images.githubusercontent.com/22507864/103421883-fdce3e00-4b9e-11eb-8b10-0c53efcf3651.png)

Maker: 162d64d3477e0b7e5674c595775673b6a7b8fa5a1a0545e41476e7313e179ab2
Taker: add296babdff9a7a622e04d41ae347102a716e649f541fd7ce6d429b05a989e3
Deposit: 0.0060

The trade transaction never propagated to the blockchain although it charged the taker fees, now It's in failed-folder. Please reimburse fees.
Thanks.

**Comment by pazza83** [comment]
Hi @sepu85 

Thanks for posting.

Please can you post a screen shot showing if you were the maker or taker.

Please also include a btc address for reimbursement.

Many thanks

**Comment by pazza83** [comment]
Hi @sepu85 what is your btc address for reimbursement?

**Comment by pazza83** [comment]
Closing as no response

**Comment by sepu85** [comment]
hey @pazza83 please reopen this again! BTC address is the following: 1EApr7XAk3mhoyXuMtCfhp5j5EexqRHszN

**Comment by pazza83** [comment]
Hi @sepu85 done :)

Please can you post a screen shot showing if you were the maker or taker.

**Comment by sepu85** [comment]
@pazza83 I opened this ticket more than one year ago... I'm not sure what are you asking me to do

**Comment by pazza83** [comment]
Hi @sepu85 

From the image you sent it is not clear if you are the maker or taker.

Maker and taker would have different reimbursement amounts.

I would like you to send the screen shot again showing the bit above `details` that confirms you as the maker or taker.
