### ISSUE TITLE
Fee reimbursement for trade ii50x7

### ISSUE THREAD

**Issue by Light2503** [bisq-network/support#693]
Hello,

Maker: 9aef93e9eb00e34a8803a0c59d1047cfc48dbba5c60a78179907d16c9de87d99
Taker: 515be6e199ed1d8fa3ce15f77baa20b65914e9bca4a5e0c32f30c2800c2b0ddc
Deposit: N/D

Bisq version:

v1.5.4

**Comment by pazza83** [comment]
Hi @Light2503 

Thanks. Please can you post using the provided [template](https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=dao-reimbursement-template.md&title=Reimbursement+for+_trader%27s+onion+address_).

thanks
