### ISSUE TITLE
Fee reimbursement for trade 96xdi....

### ISSUE THREAD

**Issue by askkbisq321** [bisq-network/support#694]
Trade id: 96xdi-6ba81435-a4cc-4f5a-bc37-1fd98504b444-152

Maker Fee transaction: 336b12ec63310bdca5a1d08527674d20ceb4b51de44ee900fa9615375b0e0efd

**Comment by pazza83** [comment]
Hi @askkbisq321 

Thanks. Please can you post using the provided [template](https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=dao-reimbursement-template.md&title=Reimbursement+for+_trader%27s+onion+address_).

thanks
