### ISSUE TITLE
Fee reimbursement for trade YVJVTS

### ISSUE THREAD

**Issue by loadedmodg** [bisq-network/support#695]
YVJVTS

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_
![image](https://user-images.githubusercontent.com/26777858/103449142-7d284400-4c69-11eb-8b61-81dd3991198f.png)

Maker: 5ac02adf62b139c44bd08eb818b88931ed6c88be0b2fc86c29299b4b1029853e
Taker: 327a55ccf3d88f3deae9f0b7b9ebfb5977fbc503694c3c8c1debf265bf2ac032
Deposit: 0074069af2eb34b436806fa5306b49ab5bf77743d434c2238dbce862ae9b19b3

Bisq version: v1.5.4

Other notes:

I have a number of failed trades at this point. I've deleted and resynced the spv manually and through the interface.  No luck here, keep on running into these issues.

If I need to create additional support tickets for all of those I will, but if I can have an all in one solution, the failed trades are these:

YVJVTS
TU7ZR
801112
32432
025882

**Comment by leo816** [comment]
please provide a preferred btc address for the payout

**Comment by loadedmodg** [comment]
3P8sELrgi1By7kEdbYRbRB2xmBeNr9nSWq

**Comment by leo816** [comment]
Maker fee was invalid so no reimbursement is justified, no funds left your wallet.
