### ISSUE TITLE
Fee reimbursement for trade TU7ZR

### ISSUE THREAD

**Issue by loadedmodg** [bisq-network/support#696]
TU7ZR

![image](https://user-images.githubusercontent.com/26777858/103449182-4272db80-4c6a-11eb-8c86-c7a5b6a8c719.png)

Maker: 346fa546e8738fbc504112780208bb65d25770a8d90074f75c571f1d885cdc72
Taker:  947278b8892c68d5cacc72779745a7e00cec9f5c044c60c6b65ab24dd7bc783a
Deposit: bc05f0eb91568dc81d298d0352c29cbb548f8e1b6db06ba6b25d8ea06dca5c91

Bisq version: 1.5.4

Other notes:

Thank you!

**Comment by leo816** [comment]
please provide a preferred btc address for the payout

**Comment by loadedmodg** [comment]
3P8sELrgi1By7kEdbYRbRB2xmBeNr9nSWq

**Comment by leo816** [comment]
Maker fee was invalid so no reimbursement is justified, no funds left your wallet.
