### ISSUE TITLE
Locked funds - trade DtZ1ea

### ISSUE THREAD

**Issue by loadedmodg** [bisq-network/support#700]
DtZ1ea

![image](https://user-images.githubusercontent.com/26777858/103449708-e57b2380-4c71-11eb-9df0-be3392c8a0ef.png)

![image](https://user-images.githubusercontent.com/26777858/103449728-0479b580-4c72-11eb-9075-e6923ed8bea0.png)

Maker:  d84f3414475b30896dbd2183aae51956069ec89d83b3555a68334a587b143ec3
Taker: 5fb504fe975d9cb4d61fc624ba57321748fcf5d1b1ea0bdce6887fbae884b2b3
Deposit: a6a9fa6b6d0483756fc937d0f3921f79a42ca521df41be7f3665bc04025be7f5

Bisq version: 1.5.4

Other notes:

Hi - this trade we were able to complete but I still have locked funds for some reason.  I am unable to create a support ticket because it was already moved to "Failed Trades".  Can you please assist?

Thank you!

**Comment by loadedmodg** [comment]
Update on this one - I was able to move it back to see if I could open a support ticket.  I now see this.

![image](https://user-images.githubusercontent.com/26777858/103574926-6dda0e00-4e96-11eb-9bb8-fd462f7b0043.png)

When clicking View Proposed Solution I get this (and so does the seller)

![image](https://user-images.githubusercontent.com/26777858/103574909-6286e280-4e96-11eb-8c70-4d26af796f76.png)

**Comment by leo816** [comment]
hi, can you reach our support team on keybase?

**Comment by loadedmodg** [comment]
Thank you @Bisq-knight !
