### ISSUE TITLE
Fee reimbursement for trade 629264

### ISSUE THREAD

**Issue by gitzxyzz** [bisq-network/support#701]
Message shows no funds are locked, but I am seeing funds locked for this transaction. 

![image](https://user-images.githubusercontent.com/76869888/103456918-03d93180-4cfb-11eb-8348-996119463a4e.png)

Maker:  45a0b2308e6571a8297e67aee1e0b27ed1e21fbb25fa9ba8180b5a5810c340bb
Taker: 4daef7045be321cbd534ed35e1d40229c8d76c666f517ba784a056f62b10e02c
Deposit: 801db0ec388e77e895d0f72ed1abe0e836108bd240b63fe699aaae32f6c8b62c

Bisq version: 1.5.4

**Comment by gitzxyzz** [comment]
![image](https://user-images.githubusercontent.com/76869888/103456983-88c44b00-4cfb-11eb-9506-51e3460edc13.png)

**Comment by gitzxyzz** [comment]
![image](https://user-images.githubusercontent.com/76869888/103457011-b6a98f80-4cfb-11eb-9eb1-5ab45bad1a6d.png)

**Comment by leo816** [comment]
please provide your preferred btc address for the payout

**Comment by gitzxyzz** [comment]
address for payout:
bc1qyxj25hhzkkcfasc74nmex8msvz3fr562smhhdf

**Comment by leo816** [comment]
Maker fee is invalid so no reimbursement is justified, no funds left your wallet.
