### ISSUE TITLE
Fee reimbursement for trade CwwGFzF

### ISSUE THREAD

**Issue by mexicaliblues** [bisq-network/support#702]
![Screenshot (9)](https://user-images.githubusercontent.com/70115976/103459933-4e15df00-4d0a-11eb-8d25-85616d14bece.png)
![Screenshot (10)](https://user-images.githubusercontent.com/70115976/103459935-5837dd80-4d0a-11eb-8321-73734ac06dc6.png)

Maker:  4c59aad08b0de5750735aeaba617562721071e4e2997059dbbcd87ce8ccfe9be
Taker: acf7be5a29f3c69a259ec83be40424919256cbdc1b2bef3f744890a216eb3aca
Deposit: 80715c802dac9d6bef010f93d7a76b6b066c3ebec36ced7fad080ec563604e2d

Bisq version:  v1.5.4  (the failed trade occurred prior to resyncing SPV and updating version)

Other notes:   

![Screenshot (13)](https://user-images.githubusercontent.com/70115976/103460069-4dca1380-4d0b-11eb-8c8c-9034bab7c72f.png)

**Comment by leo816** [comment]
please provide your preferred btc address for the payout

**Comment by mexicaliblues** [comment]
15kfuRqK8X6iPHDHfpqD6on2XLWUCFTa3p

thanks

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mexicaliblues** [comment]
was the payout made already?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by leo816** [comment]
payout will be made soon

**Comment by leo816** [comment]
Maker fee is invalid so no reimbursement is justified, no funds left your wallet.
