### ISSUE TITLE
Fee reimbursement for trade XkVnF

### ISSUE THREAD

**Issue by ghorrion** [bisq-network/support#704]
![reinbursement](https://user-images.githubusercontent.com/76882823/103464899-8bdd2c80-4d37-11eb-91ac-dfa491c33e34.JPG)

Maker:  1ff86587c25091412e74fb1c86cf44d9aa8b4968c9dac16db9d3ca2dc22f97a3
Taker: N/A
Deposit: N/A

Bisq version: V.1.5.4

Other notes:

I can not do trades, taker fee is not found for two different trades :S

**Comment by leo816** [comment]
please provide your preferred btc address for the payout

**Comment by ghorrion** [comment]
bc1qhs4mgyr67vj8sh6jajj5ytyrlt6zz0wj3a8ce7


Thanks!

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
