### ISSUE TITLE
fee reimbursement for hq0oz

### ISSUE THREAD

**Issue by 2goodtraders** [bisq-network/support#705]
![image](https://user-images.githubusercontent.com/63383093/103465469-7bed3900-4d87-11eb-8413-6be1cf5f1aca.png)

Maker: fbc33722885e31aeac80e51cc539f9376448224fa7da0c8cf8db87fb8ff4e09e
Taker: 227a8767075b9c8c43fda03bd0ec228f9ca523ab64966a091b68da227f330f9e
Deposit: e94a974cf621caf57717f23e772fda7a1ece86cad39a8041a2a04e6fe4018d7c

Bisq version:
1.5.4

Other notes:
deposit transaction failed to reach blockchain, trade was automatically moved to failed.  requesting reimbursement of fees.

**Comment by positiveelect** [comment]
Also requesting reimbursement of fees of this failed trade

**Comment by chimp1984** [comment]
Maker fee has not been broadcast, so no fee has been paid: https://mempool.space/de/tx/fbc33722885e31aeac80e51cc539f9376448224fa7da0c8cf8db87fb8ff4e09e

**Comment by positiveelect** [comment]
OK it makes sense.

**Comment by MwithM** [comment]
Closed as no reimbursement is necessary.
