### ISSUE TITLE
Fee reimbursement for trade SG8gL

### ISSUE THREAD

**Issue by 2goodtraders** [bisq-network/support#706]
![image](https://user-images.githubusercontent.com/63383093/103465506-e0a89380-4d87-11eb-8f3e-86ed5bcfb84d.png)

Maker:  c6e625d7b3b9b42849036a5b84813e4683da1a4aef60f125fe94ecd8b6401491
Taker: n/a
Deposit: n/a

Bisq version:
1.5.4

Other notes:

offer had to be canceled since the transactions were not even being broadcast to blockchain from bisq wallet (also see trade ID hq0oz )

**Comment by leo816** [comment]
please provide your preferred btc address for the payout

**Comment by 2goodtraders** [comment]
bc1qla23v9stvd9vkdc0uuryrfvykq8lhwfwxqhg42

**Comment by leo816** [comment]
Maker fee is invalid so no reimbursement is justified, no funds left your wallet.
