### ISSUE TITLE
Fee reimbursement for trade OOEPZ15I

### ISSUE THREAD

**Issue by Yabbadabba123** [bisq-network/support#708]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![reimbursement screenshot](https://user-images.githubusercontent.com/76888962/103469271-b7a8e400-4d30-11eb-8dfb-a49c54cb9cd3.jpg)

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  67a5fbcd15d3ca5795d3c16ca9bc5c424aa0da4857cf36e7576bca16b4d2b70b
Taker: cf79fd2c527f246fc0099de2b69fd4332684ffe64c920ac3e91d8dbaa461ad56
Deposit: 700bcab7ee749d1504f569907003f14bb4770ebfdade0603132ae6eca0b58443
Delayed Payout Transaction ID: dc70a34659002b558b731ee947718bd01ee71207e9c71391d55f0585440b2c95

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

>_Provide the Bisq client version to help developers identify the causing issue._
v1.5.4

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide your preferred btc address for the payout

**Comment by Yabbadabba123** [comment]
thanks: 14emntH5HzxVKGhXFoqpxwD5wR3UqagMJq
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Jan 5, 2021, 19:11 by notifications@github.com:

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
