### ISSUE TITLE
Trade '74786265' failed to move to arbitration 

### ISSUE THREAD

**Issue by pazza83** [bisq-network/support#709]
![arbitration - Copy](https://user-images.githubusercontent.com/66367547/103470496-d1671d00-4d6a-11eb-9e36-b6b4f59b0f3a.png)

## Problem:

My trade '74786265' has failed to move to arbitration. 

I clicked on the button to move it to arbitration.  The trade did not move to arbitration.

Now the button is not clickable, tells me to communicate in the 'support screen' with the arbitrator but I am unable to as the trade is not there.

## Background

I was the maker on a buy BSQ trade. 

Buyer took offer and sent BSQ.

Buyer was unable to mark as payment sent.

I was unable to release BTC.

Opened arbitration @Bisq-knight was mediator.

Trade was proposed to be settled amicably.

I accepted mediation, trade partner also told me they accepted, However this was not registered by client. Client says my trade partner did not accept.

I offered Trade partner manual payout via mediator but they did not use Keybase, so it never happened. . 

Today I moved the trade to arbitration and it failed to get their.

## Resolution required

I have received the BSQ so just need my BTC deposit returning.

Trade partner needs BTC deposit and trade amount. 

Let me know what I need to to.

## TX ID's

Maker:  3adb30c07c5a12ee8a92bb61446124901766ccdad92dadbeb7fe940e6b0a2b43
Taker: 835592abe23ce4a453930e4bce925d5afacc96b59ada89dc7fc15a414a7c16a8
Deposit: 61715b1316310c2486d943e8c425d893d9e38b5c9d0cc8eb0100831a4303f115

## Bisq version:

v1.5.4 (currently but trade taken on 13 December)

**Comment by jmacxx** [comment]
The app may not be showing the results you expected, but your multisig funds were successfully moved to the arbitrator at the time you made this post.  https://mempool.space/tx/3fb1272ca8368e40c600d8422856a530452940658e719b39cd7cbe38a9ca692f

![image](https://user-images.githubusercontent.com/47253594/103471472-7c191480-4d46-11eb-853e-3797012eb39d.png)

**Comment by pazza83** [comment]
Thanks, for the update.

Yes I can see the multisig was activated in my funds section. 

just need to find out how I can chat with them in the app, Any ideas?

**Comment by chimp1984** [comment]
So you dont see the ticket under support/arbitration?

**Comment by pazza83** [comment]
> So you dont see the ticket under support/arbitration? 

No it is not there.

>I think with cmd+o you can re-open it.

Thanks, I have done that. It has opened the mediator chat again, and as I as I was writing this it has moved it to arbitration.

Many thanks :)
