### ISSUE TITLE
Fee reimbursement for Trade 3883628

### ISSUE THREAD

**Issue by jodyrb** [bisq-network/support#711]
https://mempool.space/tx/c718ee95cac75dcf7984450b60f1aad1895b5d1a16a648398ddaa546da0b9b89

**Comment by MwithM** [comment]
I'm closing this as invalid, you have to use the Reimbursement Template displayed when a new issue is created. You can edit your first post and comment after to re-open it, or open a new one.
Also, the template doesn't ask for a BTC address to make your reimbursement to. Please point what address it should be.
