### ISSUE TITLE
Failed trade open issue I responded to since October needing action from Bisq

### ISSUE THREAD

**Issue by bisquit45** [bisq-network/support#712]
https://github.com/bisq-network/support/issues/478

The issue above hasn't been updated since October 2020.  I have a failed trade for which I requested a fee refund as well as unlocking my transaction's BTC.

Can someone please look at this, not sure if this fell off the radar of the assigned Bisq member leo... 

Thanks in advance

**Comment by pazza83** [comment]
Closing as now reimbursed https://github.com/bisq-network/support/issues/478#issuecomment-835997321
