### ISSUE TITLE
Fee reimbursement for trade 3883628

### ISSUE THREAD

**Issue by jodyrb** [bisq-network/support#713]
![image](https://user-images.githubusercontent.com/7084962/103539365-ed031e00-4e65-11eb-9e3a-0ef5dd11fb4a.png)

Maker:  c718ee95cac75dcf7984450b60f1aad1895b5d1a16a648398ddaa546da0b9b89
Taker: 9e1c18c0e1233c1b6fd00a6f4db9891de5f471de6c5873dd54b3b399587bfe18
Deposit: 422847a506138fb89a247f2c63d96a01794d0dd52020e7f512ade83809db80d0

Bisq version: 1.5.4 (started on 1.5.3)

Other notes: reimbursement address: bc1qlz79rhkjr0zjhh7qpyvlhlpt4re5se2dh5acpu

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the payout

**Comment by jodyrb** [comment]
bc1qe779rrgzlrk9qkf4jk4e6tfrwu4k95vms7fscr

**Comment by jodyrb** [comment]
Can you also tell me how to cancel a trade? Do we have to wait for the four days to expire to cancel?

**Comment by leo816** [comment]
in order to cancel a trade you have to open mediation and request it as a mediation proposal

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
