### ISSUE TITLE
Fee reimbursement for trade YAZNVH

### ISSUE THREAD

**Issue by Alvaato** [bisq-network/support#715]
<img width="878" alt="YAZNVH" src="https://user-images.githubusercontent.com/76105040/103636826-d387d200-4f4a-11eb-8099-6b50ff565bcd.png">

Maker:  95c97a20fc8c843233109ecfac5d665021da7771a34946a30109c07d773a1aba
Taker: bf518841f010c6ae7ba2b36d3363817579b525399a99c254ed7ea7ddcd2da94f
Deposit: 1dd9ee481aae6de5f157504b48d5086462c225328364a99bc0c06a73bf361b2e

Bisq version: v1.5.4

Other notes:
Hi, can anyone help me with this? Thanks.

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the payout

**Comment by Alvaato** [comment]
bc1qz7540pk5ulymy9y6l4y0umtlvtnu8a357sxsqv

**Comment by leo816** [comment]
no maker fee was created so no reimbursement is justified, no funds left your wallet.
