### ISSUE TITLE
Fee reimbursement for trade pwhnsmce

### ISSUE THREAD

**Issue by ceilican** [bisq-network/support#718]
![image](https://user-images.githubusercontent.com/1809436/103655655-522e4080-4f46-11eb-9208-f1cd3947f001.png)
![image](https://user-images.githubusercontent.com/1809436/103655686-5bb7a880-4f46-11eb-9c7b-e02c05395db5.png)

Maker: 91482f63953626c2af8be74de0d2de610905d3e1ee431684bba7996a0e0a7970
Taker: 9c96de7764775f726b4b7328e3b478aa1e44a2b54293cb6a348d50f28d0c8824

Bisq version: 1.3.6

**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by ceilican** [comment]
**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
