### ISSUE TITLE
Taken Offer Stuck (Trade Limit Reduced Before Offer Taken)

### ISSUE THREAD

**Issue by tomatopeel** [bisq-network/support#72]
![image](https://user-images.githubusercontent.com/13825174/36350743-66ea601c-149d-11e8-8001-178254480344.png)

I've an offer that appears to have been taken but is in a hanging state. I didn't receive a notification for it but noticed it under Portfolio > Open Trades.

I posted this offer to buy 0.1250 BTC, the trade limit changed to 0.0625 for my account age and then the offer was taken, maybe this has to do with it.

Trade ID is jupvro

**Comment by ManfredKarrer** [comment]
Can you send me the trade contract as json (open trade details by click on ID), and a screenshot of the trade details, and the log file (account/backup/button for opening the log)?  manfred at bitsquare dot io

**Comment by tomatopeel** [comment]
Have done, let me know if I missed anything, thanks for the quick response!

**Comment by cbeams** [comment]
Heads up @tomatopeel, @ManfredKarrer has had his head down getting v0.6.6 ready to ship. He'll get back to you here as soon as possible, I'm sure.

**Comment by tomatopeel** [comment]
Hey I'm wondering if this is related

https://github.com/bisq-network/exchange/issues/1393

This is occurring for me each and every time. 5 times now. The network seems to be okay because it's alright at discovering that the offer is available and okay to take.

**Comment by pazza83** [comment]
Closing as stale
