### ISSUE TITLE
Fee reimbursement for trade GZYSSG

### ISSUE THREAD

**Issue by ceilican** [bisq-network/support#722]
![Screen Shot 2021-01-05 at 11 15 48](https://user-images.githubusercontent.com/1809436/103656813-d634f800-4f47-11eb-95ef-9d51e241cf2b.png)
![Screen Shot 2021-01-05 at 11 15 59](https://user-images.githubusercontent.com/1809436/103656829-d9c87f00-4f47-11eb-890b-ef8c4cbb58d8.png)

Maker: d8f83b1d1ae4d88a9699bcf119d981ecaecd7d79b75a7b60cbe77509ced3225f

Taker: dc347cbe35bf1d0b93091b56f1faa6554320fc8390c5a72c1386ce15b0815b75

Bisq Version: 1.5.3

**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by ceilican** [comment]
**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
