### ISSUE TITLE
Fee reimbursement for trade LUAECG

### ISSUE THREAD

**Issue by ceilican** [bisq-network/support#724]
![Screen Shot 2021-01-05 at 11 16 42](https://user-images.githubusercontent.com/1809436/103657262-725eff00-4f48-11eb-814c-efac93b8925c.png)
![Screen Shot 2021-01-05 at 11 16 51](https://user-images.githubusercontent.com/1809436/103657267-7428c280-4f48-11eb-8120-07eab451fc88.png)

Maker: 48cd6de813ec13691565a23bd66b6f47f14f872677ec035ef41d0cf74ab9b05b

Taker: 2d0f3ea480374bb4545cc77404895687d286745755e00bad974c324ab64f3c1d

Bisq Version: 1.5.3

**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by ceilican** [comment]
**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
