### ISSUE TITLE
Fee reimbursement for trade THJVOW

### ISSUE THREAD

**Issue by ceilican** [bisq-network/support#725]
![Screen Shot 2021-01-05 at 11 17 06](https://user-images.githubusercontent.com/1809436/103657391-9e7a8000-4f48-11eb-8d07-67316426a122.png)
![Screen Shot 2021-01-05 at 11 17 18](https://user-images.githubusercontent.com/1809436/103657393-9f131680-4f48-11eb-978f-33f39b56dfee.png)

Maker: 6ce4580cad9886ca98c21e069380152d934a30c1c9798d72f1c17c057cb8d51f

Taker: 6fa1830813128c3f990519cc2c02de3e651e9f347b467c3c3724571b9bcd97e4

Bisq Version: 1.5.3

**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by ceilican** [comment]
**As discussed here (https://github.com/bisq-network/support/issues/560), please reimburse at the following address:**

bc1quf4dgpf298meq9lh2hx04r8vl669chnhdwee7k

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
