### ISSUE TITLE
Reimbursement for security deposits

### ISSUE THREAD

**Issue by Wrecktangl3** [bisq-network/support#726]
I made 3 deposits for trades but due to a bug I lost the trade data which caused the software to lose access to the trade data. 

I had @huey735 as my Support Agent who has been very helpful so far and has told me to make a refund request on the DAO and my Arbitrator has been @refund-agent2.

Below you will be able to get more of an insight into the issue:
![Dep](https://user-images.githubusercontent.com/77015544/103672048-a3085e00-4f73-11eb-8fd8-ebd163fcf8ca.PNG)

Bisq version:
1.5.4

**Comment by leo816** [comment]
did you try doing a SPV resync? https://bisq.wiki/Resyncing_SPV_file

**Comment by Wrecktangl3** [comment]
> did you try doing a SPV resync? https://bisq.wiki/Resyncing_SPV_file

Hello, yes I've done the SPV resync the trades are still not in my portfolio and I don't have my deposit money.

**Comment by huey735** [comment]
@leo816 These trades have gone into Arbitration and need to be solved there. In the future @Wrecktangl3 reach out to the support team on [Keybase](https://keybase.io/team/bisq).

**Comment by huey735** [comment]
@Wrecktangl3 will need to request reimbursement from the DAO because the Arbitrator has already processed these tickets.
