### ISSUE TITLE
Fee reimbursement for trade 15614 and unlock funds

### ISSUE THREAD

**Issue by wagnersantana** [bisq-network/support#727]
Hi, I could nod find my deposit tx id ae16c7b0a3202a42b55f43f57914b4d90f0747c2a884f7242e434b731caca7fa on any block explorer and had to fail the trade after the 4 days period.

I would like to ask for the fee reimbursement and also I need help to unlock to funds I have already deleted the spv file and resynced several times.

Details of the trade below:
Contract as json:
{
  "offerPayload": {
    "id": "15614-c1409c7b-a98e-408e-9263-50378dcd8a32-151",
    "date": 1608657439462,
    "ownerNodeAddress": {
      "hostName": "m5flg6rt5xjpcvbj.onion",
      "port": 9999
    },
    "direction": "SELL",
    "price": 0,
    "marketPriceMargin": 0.067,
    "useMarketBasedPrice": true,
    "amount": 1500000,
    "minAmount": 1500000,
    "baseCurrencyCode": "BTC",
    "counterCurrencyCode": "BRL",
    "arbitratorNodeAddresses": [],
    "mediatorNodeAddresses": [
      {
        "hostName": "apbp7ubuyezav4hy.onion",
        "port": 9999
      },
      {
        "hostName": "a56olqlmmpxrn5q34itq5g5tb5d3fg7vxekpbceq7xqvfl3cieocgsyd.onion",
        "port": 9999
      },
      {
        "hostName": "sjlho4zwp3gecspf.onion",
        "port": 9999
      }
    ],

Thanks in advance.

**Comment by leo816** [comment]
please check the format of other fee reimbursement requests and copy it.

**Comment by wagnersantana** [comment]
![image](https://user-images.githubusercontent.com/4016284/103717591-a6680d80-4fa4-11eb-864f-6e4b35652faa.png)

Bisq version: v1.5.4

Maker fee tx id: 0a2b008069c4964cc67eadf262619ffa9221d4a1afd7ba29cd36fbc6f20a70b0
Taker fee tx id: a0dc45117266fed15e7b798586a5d563a500d37238a0f8bfef304824efe65da1
Deposit tx id: ae16c7b0a3202a42b55f43f57914b4d90f0747c2a884f7242e434b731caca7fa
Delayed payout tx id: 7d85cf63cd91cea514fcb2e11d58078d68c3bf09027ed9b57300855bd1cc1ca4

Deleted spv file and resynced a few times.

Payout BTC Address: 1CUWSgVamTs21zh83ujvB3jbLCEGDTMuar

**Comment by wagnersantana** [comment]
Hi @leo816 is the format ok now? Please let me know if you need further information. Thanks in advance.

**Comment by leo816** [comment]
yes, fee reimbursement will be made soon. If you are referring to your deposit being locked please reach out to our support team on Keybase

**Comment by leo816** [comment]
No maker fee was created so no reimbursement is justified, no funds left your wallet.
