### ISSUE TITLE
Fee reimbursement for trade ssINxcMn

### ISSUE THREAD

**Issue by EvgeniySpinov** [bisq-network/support#728]
![Failed trade](https://user-images.githubusercontent.com/10797822/103698254-618ea780-4fa1-11eb-87d5-b1a05ea252c2.png)

Maker:  558339157abfcb641d4e8290b0dfa142177b4d2e77e6fe06aa378ad5bf6c7911
Taker: ec25401e3aa2c3ba890949aabf7e7127bbd7f3e788f26ee6f139c6c577497491
Deposit: 8c7e68dd670a065d99078ff98587206a27738fd00d6a8daddce8968ff7f0fa87

Bisq version: 1.5.4

Other notes:

Tried to do:
1. Resync SPV wallet (few times)
2. Rebroadcast raw transaction by hash
3. Some logs which are probably useful for debugging:

`Jan-05 00:36:13.175 [JavaFX Application Thread] INFO  b.c.b.w.TxBroadcaster: Txid: 8c7e68dd670a065d99078ff98587206a27738fd00d6a8daddce8968ff7f0fa87 hex: 0100000000010211796cbfd58a37aa06fee6772e4d7b1742a1dfb090824e1d64cbbf7a153983550100000000ffffffff91744977c5c639f1e66ef288e7f3d7bb27717ebfaa490989bac3a23a1e4025ec0100000000ffffffff02eadf210000000000220020efb7a0369d2667c94394ad2b129341b8ed8f2de23640c9d5b8d9961731cab24c0000000000000000226a2059f8f850d3a3ef4b69c527957eb567309d0d4be330d9ce397a7edff1f3b34e4702483045022100fbcfca42f5e6e91ae6e8d39b37d11df8134f97b87953fa68101696872b13a2a30220020b35fab44c820fabd8dbccc9d008a10af85a7e48ad1daf207e93ecf1adb2d8012103ba9669a963cdc05d670622318459d86d67463bb918ee214fc73df87b2033f0ae02483045022100ba57d9cf212e3cf5a5c3da27989ca93351ce6b086cff7906483da4b5686ba225022077b54f2e6512101cbbb9ede816a010c7299bdd3e5329053d10a4efaf135532fb012103d2ea32a99107932fa7577928536aa30bc687d01bba09a2f8be2bf83804a9c06b00000000`

`Jan-05 00:36:13.175 [JavaFX Application Thread] INFO  b.c.b.w.TxBroadcaster: Txid: 8c7e68dd670a065d99078ff98587206a27738fd00d6a8daddce8968ff7f0fa87 hex: 0100000000010211796cbfd58a37aa06fee6772e4d7b1742a1dfb090824e1d64cbbf7a153983550100000000ffffffff91744977c5c639f1e66ef288e7f3d7bb27717ebfaa490989bac3a23a1e4025ec0100000000ffffffff02eadf210000000000220020efb7a0369d2667c94394ad2b129341b8ed8f2de23640c9d5b8d9961731cab24c0000000000000000226a2059f8f850d3a3ef4b69c527957eb567309d0d4be330d9ce397a7edff1f3b34e4702483045022100fbcfca42f5e6e91ae6e8d39b37d11df8134f97b87953fa68101696872b13a2a30220020b35fab44c820fabd8dbccc9d008a10af85a7e48ad1daf207e93ecf1adb2d8012103ba9669a963cdc05d670622318459d86d67463bb918ee214fc73df87b2033f0ae02483045022100ba57d9cf212e3cf5a5c3da27989ca93351ce6b086cff7906483da4b5686ba225022077b54f2e6512101cbbb9ede816a010c7299bdd3e5329053d10a4efaf135532fb012103d2ea32a99107932fa7577928536aa30bc687d01bba09a2f8be2bf83804a9c06b00000000`

`Jan-05 00:36:14.140 [MemPoolSpaceTxBroadcaster @ http://mempool4t6mypeemozyterviq3i5de4kpoua65r3qkn5i3kknu5l2cad.onion/api/tx] INFO  b.c.b.w.h.MemPoolSpaceTxBroadcaster: Broadcast of raw tx to http://mempool4t6mypeemozyterviq3i5de4kpoua65r3qkn5i3kknu5l2cad.onion/api/tx failed for transaction 8c7e68dd670a065d99078ff98587206a27738fd00d6a8daddce8968ff7f0fa87. responseCode=400, error=sendrawtransaction RPC error: {"code":-25,"message":"bad-txns-inputs-missingorspent"}`

**Comment by leo816** [comment]
please provide a preferred btc address for the payout

**Comment by EvgeniySpinov** [comment]
Please transfer payout here: bc1qjynetylgdp3asnulh0qg940a237txy9aufm06k

Thank you.

**Comment by Sgiath** [comment]
Hi, I am Maker in this trade. Should I do something too? (never did fee reimbursement before)

**Comment by leo816** [comment]
payout will be made soon

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
