### ISSUE TITLE
Fee reimbursement for trade sykvfdry

### ISSUE THREAD

**Issue by thetimechain** [bisq-network/support#729]
![image](https://user-images.githubusercontent.com/74207976/103710047-a30b5c80-4f79-11eb-936a-4988a5e35c61.png)

Maker:  6f0870c772c2bc1db6816bbbc32b4e7a56b0c79b12891db2e42a011a65b0928b
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.5.4

Other notes:

It looks like the price was moving rapidly when someone tried to take this trade.

Reimbursement can be sent to: 34hA5M9UMWMYXr1Ep8B7yvfBLRFVxx6E2D

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
