### ISSUE TITLE
Reimburse fees for failed trade SeiOKTX

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#73]
@fran-rial commented on [Fri Feb 09 2018](https://github.com/bisq-network/exchange/issues/1340)

An error occurred when taking the offer.

A timeout occurred.

The taker fee is already paid. In the worst case you have lost that fee.
Please try to restart your application and check your network connection to see if you can resolve the issue.Please try to restart your application and check your network connection to see if you can resolve the issue.

[bisq_timeout_after_deposit.txt](https://github.com/bisq-network/exchange/files/1710062/bisq_timeout_after_deposit.txt)

Is there a way to get that fees back?

**Comment by cbeams** [comment]
@fran-rial, what version of Bisq were you running when this timeout occurred?

Please send the following information:

1. Go into Portfolio->Failed, click the `(i)` info button for the failed trade (`SeiOKTX`), and take a screenshot of the Maker / Taker transaction fee section
2. Also paste the text values of the Maker and Taker transaction fee IDs

I should be able to take it from there, and see about a refund of any lost fees.

**Comment by fran-rial** [comment]
Hi @cbeams  
it was under v0.6.5 
First  transaction
Maker fee transaction ID: 
078a5ed0208e6022f7b736b974ebfc876d24c9da49818d9eca959b34a7a06c48
Taker fee transaction ID: 
ed3956a752e7f04701dabe86b45dc873e86c2282e088cc7c831a7b3f652e3fbd

Second transaction
Maker fee transaction ID: 
078a5ed0208e6022f7b736b974ebfc876d24c9da49818d9eca959b34a7a06c48
Taker fee transaction ID:
1ce12803b40a9b3268cb7d538d89d4f42dd98bb1a44d2f5770ac13fc7a3b43ce


![bisq_seioktx-0bff3f98-57a1-48e7-ad68-984581a48f2e-065](https://user-images.githubusercontent.com/31315415/36666705-c3dd34c6-1aeb-11e8-9d70-23c8be6d6d34.jpg)
![bisq_seioktx-0bff3f98-57a1-48e7-ad68-984581a48f2e-065__7_46](https://user-images.githubusercontent.com/31315415/36666722-c95b36dc-1aeb-11e8-8c67-eed9d3685774.jpg)

**Comment by cbeams** [comment]
Thanks @fran-rial. I'll examine this and issue any reimbursements with the next batch transaction we do.

**Comment by cbeams** [comment]
Staged for reimbursement in 687d8cb.

**Comment by cbeams** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/70#issuecomment-370372195.

**Comment by cbeams** [comment]
@fran-rial, I have a follow-up question about this trade. Please let me know if you see this message.

**Comment by fran-rial** [comment]
@cbeams, hi
how can I help?

**Comment by cbeams** [comment]
Actually, I've just written up the situation I was looking into in detail in issue #80. If you have any insights after reading through it, please add a comment there. Thanks.
