### ISSUE TITLE
Fee reimbursement for trade 43741732

### ISSUE THREAD

**Issue by thetimechain** [bisq-network/support#730]
![image](https://user-images.githubusercontent.com/74207976/103710300-52483380-4f7a-11eb-914d-591dc5cc3bc2.png)

Maker: 3950754c9477258562a0d9a1328a7c06c00c563057fd4fe4601816c70a6dda86
Taker: 3617a2892587f75c9ab0894a9b34c10c0e405f2dbd9b48840a95fe009e3a459d
Deposit: e0880223a7a95eba9145ec1210c5cae33828fa4c4d0c2ca145b15157761f3008

Delayed payout: d8f817597929c62f0551eaee92324a16ab898929608b0e6e42b85cecd1232cae

Bisq version: v1.5.4  (I believe it was 1.5.2 when this trade was done)

Other notes:

Tried to resync the SPV chain. Did not change anything. Looks like trade has failed.

ReImbursement can be sent to: 33vKYTKpGaYmzepN9sLWZfh9QjdMa3TfRw

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
