### ISSUE TITLE
Fee reimbursement for trade 7210067

### ISSUE THREAD

**Issue by wagnersantana** [bisq-network/support#731]
![image](https://user-images.githubusercontent.com/4016284/103720827-0792df80-4fab-11eb-9cf0-9d1964a93919.png)

Maker:  d48c93e3164db9bd851badd33bb2845e826eb29bb7113198a7f1764868e87667
Taker: 5a77ea2d415aa285e3f940145ef8cd5d080159bfd1b8de5a6fa085624375a631
Deposit: 967f9b6cfa29cd1e92ece756320c1180d3aa6b8d93f51e4c4e1df9c7d9ca7680

Bisq version: v1.5.4

Other notes:

Deleted SPV file and resynced a few times.
My funds are locked, need help to unlock them.

Payout BTC Address: 1CUWSgVamTs21zh83ujvB3jbLCEGDTMuar

**Comment by leo816** [comment]
fee reimbursement will be made soon, if you are referring to your deposit being locked please reach out to our support team on keybase

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
