### ISSUE TITLE
Fee reimbursement for trade I1AeHmu

### ISSUE THREAD

**Issue by wagnersantana** [bisq-network/support#732]
![image](https://user-images.githubusercontent.com/4016284/103721276-0c0bc800-4fac-11eb-8c3d-086c726984f4.png)

Maker:  2e19973fc587615708c86b9240d9564ce0225f2b6c03cf8702bccf5c8980262a
Taker: c95aeac11ddaeccb57e92de4c1c408102ebc12c0d78b9cac648d34a8989cbc27
Deposit: 983f3ac509ba728681bebe2386b054a37386ff01403e9a191034c0bd14691109

Bisq version: v1.5.4

Other notes:

Deleted spv file and resynced a few times.
My funds are locked, need help to unlock them.

Payout BTC Address: 1CUWSgVamTs21zh83ujvB3jbLCEGDTMuar

**Comment by leo816** [comment]
No maker fee was created so no reimbursement is justified, no funds left your wallet.
