### ISSUE TITLE
Fee reimbursement for trade ta7ow

### ISSUE THREAD

**Issue by tomtombit** [bisq-network/support#733]
![bisq_trade_failed](https://user-images.githubusercontent.com/77053992/103762456-9be75b80-5018-11eb-8b92-8041fc643cac.png)

Maker: 33e7fe7bc551a30776bdbffdf758835a6c23dc5f1ff4a0047f635363ec17f3af
Taker: d4533d3e15775d78688c1b209f55ec392ae783c84e738d72d0bb5cdb592c7d31
Deposit: d78d673e1380865247296c89617ff02e9443acaa0dd3f3a8f21b6a40646f4bf6
Delayed: 9f1497237df116d0b419e036b10473f37196d2478fc021695115adffcbe3da9b

Bisq version: 1.2.5 (probably but it was a year ago i don't remember exactly)

Payout address: bc1qx4u29trxyqnjc443603dsvdd9eue09x3afkvt4

**Comment by tomtombit** [comment]
![image](https://user-images.githubusercontent.com/77053992/103764751-588eec00-501c-11eb-8828-b1bd03d3b430.png)

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
