### ISSUE TITLE
Trade failed at initiation after wallet funding and clicking take offer button

### ISSUE THREAD

**Issue by anakinsleftleg** [bisq-network/support#736]
![image](https://user-images.githubusercontent.com/77084568/103846956-44270f80-506d-11eb-8591-7c85e69eb82d.png)

![image](https://user-images.githubusercontent.com/77084568/103847155-949e6d00-506d-11eb-80c9-4e437d8b2dda.png)

![image](https://user-images.githubusercontent.com/77084568/103847199-a54ee300-506d-11eb-9303-2d80a3525af5.png)

Bisq v1.5.4

What do I do? Other then send it to failed trades? Is there something wrong with my wallet or installation?

**Comment by pazza83** [comment]
Hi @anakinsleftleg 

Thanks for the post. As the taker transaction failed you have not lost any funds for this trade.

You do not need to do anything other than send it to failed trades.

There is likely nothing wrong with your wallet. Trades fail for a variety of reasons.
