### ISSUE TITLE
Fee reimbursement for trade 963383

### ISSUE THREAD

**Issue by anakinsleftleg** [bisq-network/support#737]
Taker Fee needs reimbursed for a Failed Trade (invalid deposit transaction)

![image](https://user-images.githubusercontent.com/77084568/103847304-f232b980-506d-11eb-8024-8dd3a6085a66.png)

Maker: 763566a6ee2a18ac3cb8ca0ded6b7ab490ef2c7a306f2d9b61123832c226f499
Taker: df5fc7de55fc815c047fc0f3a92df6f87846c9e2cf61330940fb64faeb227849
Deposit: 646f7432aa2d55a078bc1b4799a371e334a11d77ec1f419bf131cc90b3b443c7

Bisq version: v1.5.4

Other notes:
![image](https://user-images.githubusercontent.com/77084568/103847404-24dcb200-506e-11eb-98fc-06d31d19751b.png)

Thank you!

**Comment by SatoshiThreepwood** [comment]
Please reimburse taker fee to: bc1q29tuf8xxc3kykq6mn79utagq8x2p7c0xmesv88

**Comment by pazza83** [comment]
Hi @huey735 I spoke to this user on Keybase today and have asked him to contact you about the taker  tx id. The maker tx and deposit tx failed but the taker was successful. They are unable to open mediation as the trade is missing a deposit tx id.

They will contact you on Keybase

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
