### ISSUE TITLE
Fee reimbursement for trade FgA8mrZY

### ISSUE THREAD

**Issue by CryptoD** [bisq-network/support#738]
SCREENSHOT HERE

![image](https://user-images.githubusercontent.com/25362387/103907143-2b683980-5101-11eb-9b13-432d342c06a5.png)

Maker:  f1853e08c6d4e9e59b21d7e81846c0816adad4d08e6e8777fad410eec49b1334
Taker: N/A
Deposit: N/A

Bisq version: 1.5.2

Other notes: 

![image](https://user-images.githubusercontent.com/25362387/103907777-fdcfc000-5101-11eb-933e-507323caf262.png)

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the reimbursement

**Comment by CryptoD** [comment]
15nCHAFEnL2pEoiswFu7VuB3RyMYg98tj3

**Comment by chimp1984** [comment]
NACK
No taker fee was created so no reimbursement is justified!
@leo816 Please always check if the trade fee was published, if not there have been no funds left the wallet.
