### ISSUE TITLE
Fee reimbursement for trade  I1AeHmu

### ISSUE THREAD

**Issue by iranilom** [bisq-network/support#740]
![Captura de tela de 2021-01-08 00-52-49](https://user-images.githubusercontent.com/11046207/103972880-c89c8f80-514c-11eb-8e64-88f690c29a7d.png)

Maker:  2e19973fc587615708c86b9240d9564ce0225f2b6c03cf8702bccf5c8980262a
Taker: c95aeac11ddaeccb57e92de4c1c408102ebc12c0d78b9cac648d34a8989cbc27
Deposit: 983f3ac509ba728681bebe2386b054a37386ff01403e9a191034c0bd14691109

Bisq version: v1.5.4

Other notes: Deleted spv file and resynced
My funds are locked, need help to unlock them.

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the reimbursement

**Comment by iranilom** [comment]
Please, 
Payout BTC Address: bc1qtq0x85a3v96yjze98q3zrcqeelq08u6lw6fgk6

**Comment by iranilom** [comment]
> please provide the preferred btc address where you would like to receive the reimbursement

Please,
Payout BTC Address: bc1qtq0x85a3v96yjze98q3zrcqeelq08u6lw6fgk6

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
