### ISSUE TITLE
Fee reimbursement for trade LKCbEW

### ISSUE THREAD

**Issue by merrick2252** [bisq-network/support#741]
![Screenshot 2021-01-07 201500](https://user-images.githubusercontent.com/77137300/103974015-c5da7400-5125-11eb-92e7-cbfe48351568.png)

Maker:  14ba0f30d7e1419d421accbf1c396afa51cdf640159344c6153742bb31419c56
Taker: ...........
Deposit: ..........

Bisq version: 1.5.4

Other notes: An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=505164270
makersPrice=511507985

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the reimbursement

**Comment by pazza83** [comment]
Closing as no response.
