### ISSUE TITLE
Fee reimbursement for trade sykvfdry

### ISSUE THREAD

**Issue by monkfruit** [bisq-network/support#742]
![secondfailedtrade](https://user-images.githubusercontent.com/76693667/103975406-0a740880-5142-11eb-9255-cd384426334a.png)

Maker:  6f0870c772c2bc1db6816bbbc32b4e7a56b0c79b12891db2e42a011a65b0928b
Taker: N/A
Deposit: N/A

Bisq version: 1.5.4

Please reimburse deposit to: bc1qwu34lk6cgul4xwpu4200zgcqyrzyga6nq7pkrh

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
