### ISSUE TITLE
Fee reimbursement for trade 423643

### ISSUE THREAD

**Issue by MGMGS** [bisq-network/support#743]
![Screenshot (5)_LI](https://user-images.githubusercontent.com/35510380/104025694-015f5780-5193-11eb-9cfb-9aa89ed21b02.jpg)

Maker: 2b8a9a6df3fd1f191156bad763e69d3ec752a23af77f7a3726734a5e1a5e3f22 
Taker: 381ca931b03e8dc935e06e2a98f6e2769d1218e601ef6a48776d666c71631871
Deposit: afa77afa89e1f4af8099348cf64d302a83ce85f6315cab8fcbd5fd4791368261 

Bisq version: 1.5.0

Other notes: Deposit transaction did not broadcast

payout address: bc1q02khyk2fqdn42mprtg88mg744jgy84s2kvvx6a

**Comment by leo816** [comment]
No maker fee was created so no reimbursement is justified, no funds left your wallet.
