### ISSUE TITLE
Fee reimbursement for trade ojuazlh

### ISSUE THREAD

**Issue by bathrobehero** [bisq-network/support#744]
![image](https://user-images.githubusercontent.com/6293506/104043185-ba498480-51db-11eb-9ec9-1f116d1c4bae.png)

Maker:  11bd8c3d0a71951cbeec630b07dd3899ae7cee99e4de0957055d9eaffa628e32
Taker: -
Deposit: -

Bisq version: 1.5.4

Other notes: client is fubar with a constant barrage of errors in 1.5.4, never had issues like this before.

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the reimbursement

**Comment by bathrobehero** [comment]
1Njqtm2bqchcMr57aRrPa7dhyAtcMSgpkr

Thank you.

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
