### ISSUE TITLE
Fee reimbursement for trade QR6OMMD1

### ISSUE THREAD

**Issue by bathrobehero** [bisq-network/support#745]
![image](https://user-images.githubusercontent.com/6293506/104043771-95094600-51dc-11eb-95b6-3e30d493a4f7.png)

Maker:  5772921f2a1c93a60d78c89508504098525d1f4c4b5747d9c9f8cbc7d607e729
Taker: -
Deposit: -

Bisq version: 1.5.4

Other notes: client is fubar with a constant barrage of errors in 1.5.4, never had issues like this before.

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the reimbursement

**Comment by bathrobehero** [comment]
1Njqtm2bqchcMr57aRrPa7dhyAtcMSgpkr

Thank you.

**Comment by bathrobehero** [comment]
Not sure if it's relevant but the seller tried to scam me saying he sent the funds and whatnot. Meanwhile it was clear (on my client) that this transaction wasn't happening and I couldn't even reply to him (java null pointer error).

**Comment by leo816** [comment]
it is relevant, please send me via keybase (@leo816) all the screenshots from the chat with him and his onion address so we can block him. Please send as much proof as possible. If possible without including any personal information, a bank screenshot were you can see that no payments arrived on that period.

**Comment by bathrobehero** [comment]
Hey, I would but I'm not going to use a Zoom/Tencent/CCP owned service that is keybase. Any other way to contact you/send you a screenshot privately?
