### ISSUE TITLE
Fee reimbursement for trade pQ1fhP

### ISSUE THREAD

**Issue by matheusjuvelino** [bisq-network/support#746]
![image](https://user-images.githubusercontent.com/15352892/104049260-6e8ae100-51c3-11eb-901a-e00a79c114cf.png)

Maker:  d2bd1d16d588e993124b76d75fd0cef999960b512c406888fbc7cf7338ce6855
Taker: 388f9ad306589c39a389ba1c18e18ab4801c43ce2a5dba93e0394257bbccf533
Deposit: 728132ccd0ba6324dc36a7858f5c6ae8ca6fc27db2409db1215d6f9626b60a7c

Bisq version: v1.5.4

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the reimbursement

**Comment by matheusjuvelino** [comment]
hello @leo816!

you can transfer to this address: 1HDzQuJMmCPq1pf66J9jjkeVCT1vym8NM2

**Comment by matheusjuvelino** [comment]
Hello @leo816!

How long does it take to make the refund?

**Comment by leo816** [comment]
payout will be made soon

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)

**Comment by matheusjuvelino** [comment]
Hello @leo816!

I inform you that the amount related to the security deposit of 0.006 remains blocked.
