### ISSUE TITLE
Fee reimbursement for trade tc3lry6

### ISSUE THREAD

**Issue by Scoop193** [bisq-network/support#747]
],
    "paymentMethodId": "CLEAR_X_CHANGE",
    "makerPaymentAccountId": "2645f721-cdea-4b71-96a8-6e958b38763d",
    "offerFeePaymentTxId": "9a58a90a43c0221c815c592316a22b30ec470421a9daacc5aadd3f5688063421",
    "versionNr": "1.5.4",
    "blockHeightAtOfferCreation": 664325,
    "txFee": 4430,
    "makerFee": 5000,
    "isCurrencyForMakerFeeBtc": true,
    "buyerSecurityDeposit": 600000,
    "sellerSecurityDeposit": 600000,
    "maxTradeLimit": 25000000,
    "maxTradePeriod": 345600000,
    "useAutoClose": false,
    "useReOpenAfterAutoClose": false,
    "lowerClosePrice": 0,
    "upperClosePrice": 0,
    "isPrivateOffer": false,
    "extraDataMap": {
      "capabilities": "0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16",
      "accountAgeWitnessHash": "39a388d48dd90a1df55a4d4692d5dd4e3f8b1835"
    },
    "protocolVersion": 3
  },
  "tradeAmount": 700000,
  "tradePrice": 329274435,
  "takerFeeTxID": "a4f9222f266ff633630475fad9e2fd9aafe5e321dd42a4932851f819cfdc1df9",
  "buyerNodeAddress": {
    "hostName": "bfgevg4nr2ypcysnylt2itqzqusb6qfssa66othpev4dcqgg2ufyzoid.onion",
    "port": 9999
  },
  "sellerNodeAddress": {
    "hostName": "36yk3uwc4ptsl4hc.onion",
    "port": 9999
  },
  "mediatorNodeAddress": {
    "hostName": "apbp7ubuyezav4hy.onion",
    "port": 9999
  },
  "isBuyerMakerAndSellerTaker": false,
  "makerAccountId": "1643025238",
  "takerAccountId": "391495348",
  "makerPaymentAccountPayload": {
    "emailOrMobileNr": "3474830121",
    "holderName": "Ludlow Consulting Llc",
    "paymentMethodId": "CLEAR_X_CHANGE",
    "id": "2645f721-cdea-4b71-96a8-6e958b38763d",
    "maxTradePeriod": -1
  },
  "takerPaymentAccountPayload": {
    "emailOrMobileNr": "2404011928",
    "holderName": "R. Delgado",
    "paymentMethodId": "CLEAR_X_CHANGE",
    "id": "1e49a1b4-c369-4075-a51f-0762b1bf7573",
    "maxTradePeriod": -1
  },
  "makerPayoutAddressString": "bc1qn53e0698jud2352pqzuegqjpk4sc0n4c3642wm",
  "takerPayoutAddressString": "bc1q5k52s4zvcluaz4w2hy6dphv4fam5dw5w4755gq",
  "lockTime": 667209,
  "refundAgentNodeAddress": {
    "hostName": "3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion",
    "port": 9999
  }
}

BuyerMultiSigPubKeyHex: 02e466afdd2103dc1f0c9893302e89e0d15c9171008c257c8e0cd1a63ffd5db4ff
SellerMultiSigPubKeyHex: 03c77347e843b4284818b2787f18df4837acf6c8287b40acf346587e36763af64f

**Comment by Scoop193** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/77167690/104050690-ff0df500-51b4-11eb-9274-6bcace38a035.png)

**Comment by Scoop193** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/77167690/104053441-3c748180-51b9-11eb-9fa7-fc0481270ba1.png)
![Screenshot (3)](https://user-images.githubusercontent.com/77167690/104053450-40a09f00-51b9-11eb-8115-2aa742898965.png)
![Screenshot (4)](https://user-images.githubusercontent.com/77167690/104053455-44342600-51b9-11eb-9307-5627c6f1c9f0.png)

**Comment by Scoop193** [comment]
Maker: 9a58a90a43c0221c815c592316a22b30ec470421a9daacc5aadd3f5688063421
Taker: a4f9222f266ff633630475fad9e2fd9aafe5e321dd42a4932851f819cfdc1df9
Deposit: 356eea399eb8ec92c7683e75ac3b55a13de45c09ac2931310df7ba1ced8e0385

Bisq version: 1.5.4

Other notes:

Tried to do:

1. Resync SPV wallet

**Comment by leo816** [comment]
please provide the preferred btc address to receive the payment

**Comment by Scoop193** [comment]
1G6S7bQUtH8cRkaTQaAMgAJqmKDQ1FQVv6

**Comment by Scoop193** [comment]
So what happens from here??

**Comment by leo816** [comment]
payout will be made soon, they are made once every cycle

**Comment by Scoop193** [comment]
Ok I was wondering what's going on

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)

**Comment by Scoop193** [comment]
So I'm still in dispute in the bisq what am I supposed to do?
