### ISSUE TITLE
Fee reimbursement for trade Y0PR7I

### ISSUE THREAD

**Issue by alwaysminingbtc** [bisq-network/support#749]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
![image](https://user-images.githubusercontent.com/59702404/104084411-a6ae1600-51fb-11eb-9129-2d96cb14c00d.png)
![image](https://user-images.githubusercontent.com/59702404/104084420-af9ee780-51fb-11eb-9b89-0b8ee2433a43.png)
![image](https://user-images.githubusercontent.com/59702404/104084423-b299d800-51fb-11eb-944a-f3be93a3db33.png)
![image](https://user-images.githubusercontent.com/59702404/104084456-fd1b5480-51fb-11eb-8115-f4ada2b01f79.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  d0528fc54e0e8c558d3a0e9c20984864fab3b7bd62a3467f29a66163a16f44ef
Taker: dab0a2c046a0418c696f626ea42d747c982c2fb5bd554fd9a0c37caedb9f57ca
Deposit: 6fc519b7d356f715acbf76146ac95cd9444466547f32eb5d0077dcc106b99978
Delayed Payout: 1b6db4917037a78d608f6c42011101de033e26d321a2a3a59d578738ada303a3

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
1.5.4
>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide the preferred btc address where you would like to receive the payment

**Comment by alwaysminingbtc** [comment]
32GUMSekiQJGXB6VU2zoyFFNY9T1rKS7Xa

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
