### ISSUE TITLE
Fee reimbursement for trade 539665

### ISSUE THREAD

**Issue by DamageIncorporated** [bisq-network/support#750]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![remmina_streb kamp local (SSH)_streb kamp local_202119-173446,507321](https://user-images.githubusercontent.com/7439747/104104667-ca2f9a00-52a9-11eb-9d68-abe972b0904d.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  1fa133bf131de349628c0d4be728864f2faae2b7a4c0635b3c8146762644de58
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: N/A

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by DamageIncorporated** [comment]
Adding the error message that was only partly visible in the screenshot:

An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=319523260
makersPrice=314597306

**Comment by leo816** [comment]
please provide the preferred btc address where you'd like to receive the reimbursement

**Comment by DamageIncorporated** [comment]
Ups, almost forgot about that...
A fresh address for this issue: bc1qanthnt20rak6c58a5a9ap2talj0snu6sm048e8

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
