### ISSUE TITLE
Bisq won't load up-stuck at 2/4 Tor node created after logging in (already for more than an hour)

### ISSUE THREAD

**Issue by Yabbadabba123** [bisq-network/support#751]
<if contains sensitive info please use the encryption feature on Keybase>

brief-description: Once loading Bisq, and after entering password, app states Synced with Bitcoin Mainnet... has a checkmark, and below that stuck at "(2/4) Tor node Created". Nothing happens for at least 30 minutes at which point I gave up. Tried rebooting PC, re-installing Bisq (after a backup) etc.

started_at_UTC: <yyyy-mm-dd hh:mm> 2021-01-09  17:00

started_at_block: 665297

closed_at_UTC: <yyyy-mm-dd hh:mm>

closed_at_block:

solution: no idea

github-issue: 

support_type:

**Comment by pazza83** [comment]
There have been problems with Tor this weekend that have affected connectivity. Is it still a problem for you?

**Comment by Yabbadabba123** [comment]
no it started working after about 40 minutes. Thanks.
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Jan 10, 2021, 13:49 by notifications@github.com:
