### ISSUE TITLE
Reimbursement and compensation for trade 9nwxc

### ISSUE THREAD

**Issue by brndnng** [bisq-network/support#752]
Reimbursement and compensation for trade 9nwxc

I am BTC buyer, as taker.
Trade amount: 2 BTC
Deposit amount: 0.3 BTC
Reimbursement amount: 2.6 BTC / [30 day BSQ average] BSQ = `[TOTAL AMOUNT] BSQ`
Reason for reimbursement: Seller did not respond.

I am aware that the refund agent can't reimburse over 0.5BTC to me. I am asking about the possibility that I be partially reimbursed with the 0.5BTC first and receive the remaining 2.1BTC from the DAO. Since I am the victim here that my funds are locked out until the next DAO cycle, I would like to at least claim some of my funds first as an assurance.
Ticket closed on Jan 8, 2021 12:04:16 AM
Mediator node address: apbp7ubuyezav4hy.onion:9999

Summary:
Trade ID: 9nwxc
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 2.30 BTC
Payout amount for BTC seller: 0.30 BTC

Reason for dispute: Seller not responding

Summary notes:
Seller never replied a single message

-----BEGIN SIGNATURE-----
302c021470784b57eedb0c1ea4a96a3cb3648711a3414d9902145af7e7f8ee5b0ce2c8b31612cbd299e5808b9f73
-----END SIGNATURE-----

Ticket closed on Jan 10, 2021 11:48:14 AM
Arbitrator node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Summary:
Trade ID: 9nwxc
Currency: XMR
Trade amount: 2.00 BTC
Payout amount for BTC buyer: 0.00 BTC
Payout amount for BTC seller: 0.00 BTC

Reason for dispute: Seller not responding

Summary notes:
Seller did not respond to mediation or arbitration. Trading amount too high for Refund Agent. DAO should reimburse the equivalent to 2.6 BTC.

-----BEGIN SIGNATURE-----
302c02145e3962ede67e07966accf5a80d3d0c597c3f5188021437bfa70510aed2d991462cbeb01ece47f4673ea8
-----END SIGNATURE-----

Next steps:
No further action is required from you. If the arbitrator decided in your favor, you'll see a "Refund from arbitration" transaction in Funds/Transactions

Next steps:
Open trade and accept or reject suggestion from mediator

Arbitrator secret: f908fd2372dc402672be4ae3b837ceed

**Comment by brndnng** [comment]
@refund-agent2 @Bisq-knight

**Comment by refund-agent2** [comment]
Secret is correct.
I have verified that buyer sent 350.87719298 to BTC seller's address and the delayed payout [txid](https://mempool.space/tx/cf034163faa8676dc1a5badff7b751aed1597f60ff1235193a7235d976da1b45).

**Comment by MwithM** [comment]
@brndnng When did this trade start?

**Comment by brndnng** [comment]
December 30 2020

**Comment by failedbisqtrade** [comment]
I do not have ability to release funds for this trade. I interacted with bisq support on January 1st to release funds.  MwithM pinged all mediators with no outcome.  MwithM alerted me of github thread and told me to post. MwithM can confirm I have done all to find mediator to have funds released.

**Comment by MwithM** [comment]
I confirm that Keybase user @ tradehelp contacted me on January 2nd. 
That same day I posted at bisq.support general group: 
_"Trader lost Bisq data, has old backup but can't find the offer. This is the metadata of the trade:
Trade started 29DEC, as BTC seller, 2BTC - 350.87719298 XMR"_
Nobody replied, I forgot about it until 11th Jan, because same Keybase user reminded me. I tried again at the same group and only @leo816 replied (negative) about finding this trade.
Then I found this "seller not replying post" and told to Keybase user and @refund-agent2

**Comment by Bisq-knight** [comment]
I got a message from tradehelp this friday (15th of Jan).

The tricky part here is how to verify he is who he says he is. I think we will be able to verify either by him moving the XMR to another address of his that tradehelp will provide or by signing a message (although I am not sure how to verify that in Monero)

**Comment by Bisq-knight** [comment]
and @failedbisqtrade  can you add your github verification on keybase so we can be sure you are tradehelp there?

**Comment by chimp1984** [comment]
> The tricky part here is how to verify he is who he says he is

He should be able to open mediation or arbitration case. cmd+o if it was not opened before. 
Why he did not get any reply for so long? Who was his mediator?

**Comment by Bisq-knight** [comment]
> > The tricky part here is how to verify he is who he says he is
> 
> He should be able to open mediation or arbitration case. cmd+o if it was not opened before.
> Why he did not get any reply for so long? Who was his mediator?

Doesn't look like he can since he lost his files and backup was from before the trade. He didn't answer my messages (I was the mediator) for the same reason.  See @MwithM 's comment:
> "Trader lost Bisq data, has old backup but can't find the offer. This is the metadata of the trade:

one way to verify is to prove ownership of the receiving XMR address, since the trade was executed correctly as far as I remember

**Comment by refund-agent2** [comment]
I have given instructions to @failedbisqtrade through Keybase to prove ownership of public address `bc1q8x9zaptyrcyas6exm522upuaahvfdtcf56hgr8`. It was used by the seller for this trade.

@brndnng I think you'd better open a new issue to request 2.3 BTC paid in BSQ. I'll submit a new arbitration ticket if it's possible. If @failedbisqtrade fails to verify that address in two weeks, you can claim the 0.3BTC remaining for next cycle.

**Comment by brndnng** [comment]
I opened a new issue https://github.com/bisq-network/support/issues/796

**Comment by pazza83** [comment]
closed as also open here https://github.com/bisq-network/support/issues/796#issuecomment-770343878
