### ISSUE TITLE
Fee reimbursement for trade 64654474

### ISSUE THREAD

**Issue by zopedope** [bisq-network/support#753]
Please reimburse me: 0.00642582 BTC 

this is for the 0.0063 BTC which is the "taker fee" and the 0.00012582 BTC miner fee in transaction: 32b74bd12a33fe476890fefb307f8259fb0edf6047ecf9b2e9f24ce2fba1d5c0

Send reimbursement to: bc1q4ga496slq69zs5hlf82uyzwpwqlec62hl2qr02

Bisq version: 1.5.4

No error message shown. 

Thank you

![trade-info-1](https://user-images.githubusercontent.com/67662939/104130561-62c42980-533f-11eb-992c-73a7c36ee7b9.png)

**Comment by zopedope** [comment]
Why no support ack? 
Is this missing any info? When can I expect reimbursement?

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by leo816** [comment]
I will reimburse the miner fee, If the deposit is still shown as locked funds in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. You have to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by leo816** [comment]
please write down the maker fee, taker fee and deposit tx id so I can copy and paste it

**Comment by zopedope** [comment]
Maker fee transaction id: 728c1fd12b1f10133ddfc9547f7ac11f8f58c7639ae02d4e7622823c4b02dffe
Taker fee transaction id: 32b74bd12a33fe476890fefb307f8259fb0edf6047ecf9b2e9f24ce2fba1d5c0
Deposit transaction id: 8ad1d6330d4171becc37a05217ca13d23b2b11d6ba23297d8da60c96d5c0a9dd

Please send reimbursement to: bc1qrp74x55ga5dtmnweh5gzyu66s5uy7g88mywkzs
thanks

**Comment by zopedope** [comment]
> I will reimburse the miner fee, If the deposit is still shown as locked funds in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. You have to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

What about this "taker fee" how do I get this back? 
32b74bd12a33fe476890fefb307f8259fb0edf6047ecf9b2e9f24ce2fba1d5c0
That is .0063 BTC

**Comment by zopedope** [comment]
Hi - can we complete this now? thanks

**Comment by zopedope** [comment]
@leo816 Can you help me with this?

**Comment by leo816** [comment]
hi, that is the deposit, If the deposit is still shown as locked funds in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest way is to delete the ClosedTrades and FailedTrades files in the db folder. You have to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by zopedope** [comment]
![locked amount](https://user-images.githubusercontent.com/67662939/112177781-9a691080-8bcf-11eb-97ec-957563655132.gif)

@leo816 when I delete those files I lose the "locked" amount. Is there no way to get back this failed trade "security deposit"?! 
If you check the transaction 32b74bd12a33fe476890fefb307f8259fb0edf6047ecf9b2e9f24ce2fba1d5c0 you will see my security deposit locked up.

**Comment by leo816** [comment]
did you try SPV Resync? https://bisq.wiki/Resyncing_SPV_file#From_the_file_system

**Comment by zopedope** [comment]
No. I just did a full resync and the 0.0063 is still locked.

**Comment by pazza83** [comment]
@zopedope 

Closing as reimbursement for fees has taken place 

https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
