### ISSUE TITLE
Fee reimbursement for trade TU7ZR

### ISSUE THREAD

**Issue by blacktac** [bisq-network/support#754]
![TU7ZR](https://user-images.githubusercontent.com/77252545/104139444-1b569100-5371-11eb-8a47-3bf001921ac7.jpg)

Maker:  346fa546e8738fbc504112780208bb65d25770a8d90074f75c571f1d885cdc72
Taker: 947278b8892c68d5cacc72779745a7e00cec9f5c044c60c6b65ab24dd7bc783a
Deposit transaction: bc05f0eb91568dc81d298d0352c29cbb548f8e1b6db06ba6b25d8ea06dca5c91
Deposit payout: 74a39056705b4e837f2e0a60cb66c5aac7fa337fa7e38d8eed72912807c73cf5

Bisq version:
1.5.4

Other notes:
Failed in 1.5.3
Deleted SPV and tried a resync

Refund address:
bc1qxjla0hyp87xkjkrdz8093pqzky692cc298w03p

**Comment by pazza83** [comment]
Hi @blacktac 

Thanks for posting.

Looks like this has yet to be actioned.

@leo816 please can you add to your to do list.

Many thanks

**Comment by pazza83** [comment]
Hi @leo816 please can you add this to your reimbursement to do list.

**Comment by leo816** [comment]
Fee Reimbursement paid out with #1028
