### ISSUE TITLE
Fee reimbursement for trade opaycbe

### ISSUE THREAD

**Issue by crptsly** [bisq-network/support#756]
<img width="886" alt="Snímka obrazovky 2021-01-11 o 18 41 39" src="https://user-images.githubusercontent.com/77293641/104219378-51157b80-543e-11eb-9f4c-f8d5d9755112.png">

Maker: b87beef6a6d1d0279c42b2beffd27843b4a4106a438abcdf442ed65c5049cfb5
Taker: N/A
Deposit: N/A

Bisq version: 1.5.4

Other notes: Timeout reached. Protocol did not complete in 60 sec.
                       I also cannot make new offer because this one is FAILED

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by crptsly** [comment]
My prefeffed btc address:

bc1q5ay95kveguqzmhadycsd269jz2tkvjrd6sylmg

**Comment by leo816** [comment]
taker fee was not created, reimbursement is not justified
