### ISSUE TITLE
Fee reimbursement for trade 73638

### ISSUE THREAD

**Issue by BeanMachine45** [bisq-network/support#757]
Fee reimbursement request for failed Trade 73638. Error message below.

![Bisq trade failed 1-11-21](https://user-images.githubusercontent.com/77294151/104224273-c2d7d000-5412-11eb-866c-f096e07845ff.png)
![Maker taker price difference 1-11-21](https://user-images.githubusercontent.com/77294151/104224280-c703ed80-5412-11eb-843c-038e4f98ca28.png)

(url)

Maker:  0.00006765 BTC
Taker: 0.00020295 BTC
Deposit: 0.02 BTC

Maker fee TX ID:  6152b0c7cffc6b520eeb6aa4feb4cd5719319ff62b8510dab163a311365652e7

Bisq version: 1.5.4

Please reimburse fees thanks and let me know if additional info is needed

please refund either back to bisq wallet or address: bc1qqrast47n4u9nkewa7jt36esmamzvn5lexuln0g

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
