### ISSUE TITLE
Fee reimbursement for trade eZMspA

### ISSUE THREAD

**Issue by fierce-deedee** [bisq-network/support#758]
![image](https://user-images.githubusercontent.com/76986121/104252414-d7be5e80-5426-11eb-9110-8b529b1a5fd6.png)
![image](https://user-images.githubusercontent.com/76986121/104252809-d17cb200-5427-11eb-96b4-edf6d134b840.png)

Maker: eca1c489e526ce93e40afc09dcdc6f1924f575ba6f147ca64794716c503d3acc
Taker: N/A
Deposit: N/A

Bisq version: v1.5.4

Other notes: Occurred during Tor attack. A bit before: Tue Jan 12 12:12:17 AM UTC 2021

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by fierce-deedee** [comment]
@leo816 

3JQLkraoV8AZ6AWcs7QCXzX54iNwCZJ6Jx

Is the preferred address. Thanks!

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, the trade fee wasn't published and no funds left your wallet

**Comment by fierce-deedee** [comment]
Got it.
