### ISSUE TITLE
Fee reimbursement for trade jr6jiqqp

### ISSUE THREAD

**Issue by ghorrion** [bisq-network/support#759]
![trade](https://user-images.githubusercontent.com/76882823/104373738-1f291580-5521-11eb-9a96-04a440d6b9d4.JPG)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  f014e4a3041f97a7f346b65d041526550f63a82f5fe2b016fc4210c085f20149
Taker: N/A
Deposit: N/A

Bisq version: 1.5.4

Other notes:

Failed transaction, I asked for help in the forum and my wallet may be corrupted

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by ghorrion** [comment]
bc1qljh84ekhajrcr543wv797ejw2nzvf3p2880g3u

Thanks

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
