### ISSUE TITLE
Fee reimbursement for trade YAZNVH

### ISSUE THREAD

**Issue by Larguson** [bisq-network/support#765]
file:///home/noglar/Desktop/Untitled%20window_001.png

Maker:  95c97a20fc8c843233109ecfac5d665021da7771a34946a30109c07d773a1aba
Taker: bf518841f010c6ae7ba2b36d3363817579b525399a99c254ed7ea7ddcd2da94f
Deposit: a8f661bbfb39c9064cae99e1a63fc25ee21714cff0b733f292a60ac2c37c6db7

Bisq version: v1.5.4

Other notes:

Deposit and trade amount is still locked.

Receiving the following error: 

Deposit transaction has been published.
The BTC buyer need to wait for at least one blockchain confirmation before starting the payment.

Requesting to be reimbursed the trade fee and for the deposit to be unlocked.
Refund can be made to the following address:

bc1qy43sk99axu4v9tz8rx2ddct0fhqqgyv3aff4vj

**Comment by MwithM** [comment]
I attach picture as Larguson is having dificulties to post it. 

 
![Untitled window_001](https://user-images.githubusercontent.com/50149324/104500862-3fb7a500-55df-11eb-8c8e-4b11728df200.png)

**Comment by DN25** [comment]
I had a similar issue.  Deleting the SPV and Resyncing fixed it for me.  https://docs.bisq.network/backup-recovery.html#resync-spv-chain

**Comment by MwithM** [comment]
There's more to look at when this happens, I checked and this is a failed trade. https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
