### ISSUE TITLE
Fee reimbursement for trade 512560

### ISSUE THREAD

**Issue by GrandVizierOfMalta** [bisq-network/support#766]
![Screenshot 2021-01-13 151244](https://user-images.githubusercontent.com/61128065/104521500-dff6d500-55b1-11eb-8d9d-4bbebcccaa0c.png)

Maker:  e52c224162d4741abe907b5877c2d7de9b4108d72627a36d219e011d883ab0d0
Taker: N/A
Deposit: N/A

Bisq version: 1.5.4

Other notes:

Failed XMR/BTC Altcoins Instant trade. Please review and reimburse. Thank you!

**Comment by GrandVizierOfMalta** [comment]
Edit: Removed second screen cap as it was from a different issue and added in error.

**Comment by leo816** [comment]
please provide a btc address where you would like to receive the reimbursement

**Comment by GrandVizierOfMalta** [comment]
Hello. Thank you for the update. BTC address to send to is:
bc1q9q39thllf92yz5qhtky8h44p7ny7v8d97mnncw

**Comment by GrandVizierOfMalta** [comment]
Thank you. BTC address has now been added in github issue.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.

**Comment by GrandVizierOfMalta** [comment]
Thank you for that explanation and looking into it.

Sent from ProtonMail mobile

-------- Original Message --------
