### ISSUE TITLE
Fee reimbursement for trade 54612933

### ISSUE THREAD

**Issue by tyler-hobart** [bisq-network/support#767]
![Capture2](https://user-images.githubusercontent.com/68714176/104546269-a8ebe800-55e0-11eb-8041-4b8eb6d39c62.PNG)

Maker: b79c158d672ff76903311f4dc70ab21cd9fc2de025b39be64c375c0da45a6fd2
Taker: 63046144024a201ffa6cfd4d8b24f5331fe7c1e1182b881ad8b7e183adadfe54
Deposit: c52ca991c253cd811892a289544bb97d9813918afc11ee0edd34f406af391130

Bisq version:

v1.5.4

Other notes:

![Capture](https://user-images.githubusercontent.com/68714176/104546392-ed778380-55e0-11eb-97ad-775d91ffa159.PNG)

Deposit transaction ID was not found in mempool. After a couple hours I deleted the SPV file and resynced.
Thank you for the support!

**Comment by tyler-hobart** [comment]
Preferred bitcoin address is bc1qas0ay8ft6sa5h7mcpg3tcdp4kf5068xy86e566

**Comment by tyler-hobart** [comment]
Thanks for the reimbursement. When will my locked funds from this failed trade be unlocked?

**Comment by leo816** [comment]
if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
