### ISSUE TITLE
Fee reimbursement for trade ozryrz

### ISSUE THREAD

**Issue by bisquser1** [bisq-network/support#768]
![IMG_2639](https://user-images.githubusercontent.com/77044917/104547473-7ee7f500-55e3-11eb-9b35-2eab1048efd1.jpeg)

Maker: 596a4966597c3c5848f8bb50a76ab2a3a680d18f13363e84b803ff9ca1a1acaf
Taker: N/A
Deposit: N/A

Bisq version: v1.5.4

Other notes:

"Timeout reached. Protocol did not complete in 60 sec." error. In failed folder. Thank you. 

Please reimburse fees to: bc1qg7edxr08ftasfy3lfrn4eudvkezwgd2xjf73dy

**Comment by leo816** [comment]
No taker fee was created so no reimbursement is justified, no funds left your wallet.
