### ISSUE TITLE
Fee reimbursement for trade 2308136

### ISSUE THREAD

**Issue by 23Yc8z** [bisq-network/support#772]
![Bisq pantallazo trade 2308136](https://user-images.githubusercontent.com/57015173/104621649-a34ddb00-5690-11eb-8d3f-3f175f32b00a.jpg)

Maker:  4c666d9a5bcbc511ab46e66d1b30a63abb30f01054cadff4eca74f4a92e28ca6
Taker: a5f07ed20ab38b6ea29c9380258c2e3773af394a0041c74e05829204499f71e6
Deposit: 7d7ef39914c034d42388e1eccfde5d9104447c7158a778a08e73fbdd11891b5c

Bisq version: 1.5.1

Other notes:

"The deposit transaction (the 2-of-2 multisig transaction) is missing." error.
Please reimburse fees.

Both seller and buyer had version 1.5.1 at the time of the trade.
I (the seller) have today installed version 1.5.4, and I have made a "SPV resync" today.

**Comment by 23Yc8z** [comment]
Hi, one month and no response yet...

**Comment by 23Yc8z** [comment]
Hi,


I have installed **v1.6.1**,
moved the trade from "failed" to "open trades"
and I get some warning messages (see attached screenshots):


    There is an issue with a missing or invalid transaction.
    Please do NOT send the fiat or altcoin payment.
    Open a support ticket to get assistance from a Mediator.
    Error message: Deposit transaction is null or has unexpected input count.
![Bisq 1 6 1 warning 02](https://user-images.githubusercontent.com/57015173/113136606-daf60900-9223-11eb-83f5-4ee7d237156f.jpg)

    The trade protocolol encountered some problems.
    The deposit transaction (the 2-of-2 multisig transaction) is missing.
    Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbuersed the trade fee here: https://github.com/bisq-network/support/issues.
    Feel free to move this trade to failed trades.
![Bisq 1 6 1 warning 03](https://user-images.githubusercontent.com/57015173/113136628-e0ebea00-9223-11eb-81a8-9a0d57937dfe.jpg)

The deposit transaction in null. You can move the trade to failed trades.
![Bisq 1 6 1 warning 04](https://user-images.githubusercontent.com/57015173/113136680-ef3a0600-9223-11eb-97d9-a79b433e693b.jpg)

**Comment by 23Yc8z** [comment]
Hi, 8 months and still waiting for a reimbursement...

**Comment by pazza83** [comment]
Hi @23Yc8z 

Many apologies for the lengthily wait.

I can see you lost fees on this trade.

@leo816 please can you add reimbursement of this trade to your to do list.

Many thanks

**Comment by 23Yc8z** [comment]
Hi, 

No reimbursement yet.

I have opened the issue at https://github.com/bisq-network/support/issues/1025
