### ISSUE TITLE
Fee Reimbursement for trade 3791636

### ISSUE THREAD

**Issue by RiBXX** [bisq-network/support#773]
![SS](https://user-images.githubusercontent.com/77477533/104701416-cbfac280-56da-11eb-826c-6e49cbe24492.png)

Trade ID: 3791636-45caaae7-a90e-4f47-bfd7-aea2a9a7fdcb-142

Maker: e6d202770987bfb917e4632c555da67b092b792fff4084c88448a2ae8bd0f41a
Taker: N/A
Deposit: N/A

Bisq version:

v1.5.1

Error Notes:

An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 658836, myLockTime=639145

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by RiBXX** [comment]
37u7qLA2c7ztgN5SjeNFXVxXv4yGR3x5SD

Thank you!
--
 Securely sent with Tutanota.



Jan 26, 2021, 10:29 by notifications@github.com:

**Comment by RiBXX** [comment]
Apologies for the late response. Here is my address:

bc1qxad5tg3a9rfayk4v7w90c5645uhwgkmc660ds6

--
 Securely sent with Tutanota.



Jan 26, 2021, 10:29 by notifications@github.com:

**Comment by leo816** [comment]
taker fee was not created, reimbursement is not justified, funds never left your wallet
