### ISSUE TITLE
Fee reimbursement for trade dkz4sv

### ISSUE THREAD

**Issue by reimbotsment** [bisq-network/support#774]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Screenshot_20210115_200459](https://user-images.githubusercontent.com/77505298/104762797-9e128e00-576d-11eb-97e2-107cbdd0f98f.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  6779c247dced5291c91a5acc57ff61295d6aff181ad2b7a94c92be0214124895
Taker: 26130811b992be26609671d81f36eb0ae40ed540e231b1c85439b173a5869c56
Deposit: 06cc39029943502194ad4d0c62c2a87c609ddf75a9ca75c6f94d731aae984098

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Please reimburse fees.
Thanks.
Preferred address: 
deleted for privacy reasons.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by reimbotsment** [comment]
Preferred address: 
bc1qt3avj6y234208dvs5wnxwd6nwgudtg5refqru5

**Comment by leo816** [comment]
taker fee is invalid, no funds should have left your wallet

**Comment by reimbotsment** [comment]
Thanks!
I know this is an unrelated issue, but I have 0.03btc locked in the top right corner. However, when I open the locked funds tab they are 0 BTC (which is the correct value). My question is, how can the 0.03btc in the top right corner go away to reflect the real value (0)BTC.

**Comment by leo816** [comment]
did you try doing a spv resync? https://bisq.wiki/Resyncing_SPV_file

**Comment by reimbotsment** [comment]
Yes, I have tried it multiple times, the display is still the same.

**Comment by leo816** [comment]
if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades
