### ISSUE TITLE
Fee reimbursement for trade QvBawN

### ISSUE THREAD

**Issue by ctonbton** [bisq-network/support#775]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Offer ID: QvBawN-9ffc6cab-39c7-43fc-a482-ba67cf384890-154
Maker:  7f5aa8ff5767739877a6c677ea8d567bde539edc2951a94a25aa721fecc8761b
Taker: fe1cf08ade44b562224cfbe763b27f20bbee99378bbece74fbad9ab3604a365c
Deposit: 05944e40f1f0cfdba0e9b338c41ee1eb9cdebd981f0ceda10cf73cbcb1e9831b
Delayed Payout Transaction ID: f95f982bf77da17328f7f2a1c190eb91c3e93f747fad2b2822a22d9fecad545c
Delayed Payout Transaction Sent To: 34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC
Contract Hash: 6bd1ff3fe1276668656c8fde32f98636d85c6fd3a9f1691749e475a9a578db67
![0](https://user-images.githubusercontent.com/34559154/104829523-63c2f280-583a-11eb-96e3-7c6d3e6d6b42.jpg)

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: The trade Failed (I am Taker) and no fees were sent to escrow. However, My Taker Fee was published. I am requesting a refund for my Taker fee... I believe 2.82 BSQ.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by pazza83** [comment]
Closing as no response.
