### ISSUE TITLE
Fee reimbursement for trade xHimAo

### ISSUE THREAD

**Issue by ctonbton** [bisq-network/support#776]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![0](https://user-images.githubusercontent.com/34559154/104829923-7b9c7580-583e-11eb-85fb-0e5841a6d6f0.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_
Trade ID: xHimAo-af3d63b9-2917-4411-bb2e-64b166b02ad9-124
Maker:  5409a3638d7aa351899c8b1437277b9d593c267e9f82fd6457efaab83f8c1900
Taker: 0813f9f9c2753bd5ca9268e388741c1735e187c46682582bdfed78070fb42909
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: I was the Maker for this Failed trade. Please refund my fees for this failed trade. Thank You!

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by pazza83** [comment]
closing as no response
