### ISSUE TITLE
Fee reimbursement for trade OBFCJA

### ISSUE THREAD

**Issue by BTCGonzo** [bisq-network/support#777]
![image](https://user-images.githubusercontent.com/77583871/104850904-1904b180-58f2-11eb-9ad8-2174c4f1997e.png)

![2021-01-14 BISQ Problem trade 2](https://user-images.githubusercontent.com/77583871/104852411-34c08580-58fb-11eb-819f-fc7de5a4f64d.JPG)

Maker:  1530753429
Taker: 1849006249
Deposit: 510453ed9bcfe54256a36b7985642b31874e26c37e0f4bdfbc50c5ae721b45e9

Bisq version:

v1.5.3

Other notes:

**Comment by huey735** [comment]
The Maker and Deposit transaction Ids are incorrect.

**Comment by BTCGonzo** [comment]
That's the best I can find:

"makerAccountId": "1530753429"

"buyerSecurityDeposit": 600000
"sellerSecurityDeposit": 600000
...I'm really not sure whats the Deposit transaction ID, could you please show me the line?

**Comment by huey735** [comment]
On that image of the trade Details above the on starting with 745f... is the Maker fee transaction, the one starting 5104... is the Taker fee transaction id, the Deposit transaction says 'N/A'. Matter of fact, where did you get this transaction id 510453ed9bcfe54256a36b7985642b31874e26c37e0f4bdfbc50c5ae721b45e9?

**Comment by pazza83** [comment]
closing as no response
