### ISSUE TITLE
Fee reimbursement for trade 67437214.

### ISSUE THREAD

**Issue by TsLh32** [bisq-network/support#779]
I am the BTC Buyer as maker for BRL. 
Trade amount and asset: 0,0020 BTC for 220,00 BRL. 
The security deposit for both parts was 0,006 BTC (which is still blocked - the transaction haven't started yet - status 1: Wait for blockchain confirmation).
The mining fee was 0,00007525 (Maker). 

![Bisq error](https://user-images.githubusercontent.com/77698251/105094445-0f5e8380-5a83-11eb-88e9-398a6745543a.png)

![Bisc error 2](https://user-images.githubusercontent.com/77698251/105095038-e4286400-5a83-11eb-8678-78a9c6f80579.png)

**Maker fee transaction ID:** 48271f74fe151c3fe97ec7ae5b42d982b529ac5f75e866ebb2e9b5eb0ce24d14 (confirmed);
**Taker fee transaction ID:** 5879315aa626ff7ee6a0078d4ceb4d90e440a81077ecc897469286a5a073b2b0 (unconfirmed/transaction not found));
**Deposit transaction ID:** b85a12dd7436feec7e99a64f5cfc0cdc794f088e4962ad54598d218197ec5194 (unconfirmed/transaction not found));
**Delayed payout transaction ID:** c41caf1b3f384a453dee96949197152b33fd01584af4ec3060c2959726acad40 (unconfirmed/transaction not found)

Bisq version: v1.5.4

Other notes: I think I've waited enough until opening this Issue. The seller didn't help much. If there is no way to confirm the transactions to complet the next steps of the trade (I really would like to have a solution and continue), than I wish to cancel it please, to have my security deposit unblocked and to have my mining fee reimbursed.

If there is some missing step I should do first, please, let me know.

Thanks in advanced! Hope everything gets solved soon!

**Comment by MwithM** [comment]
The trade has failed as the taker fee tx failed to broadcast, there's no way to keep with this trade. The fee refund agent will review the issue. 
https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1

**Comment by huey735** [comment]
Please edit the title to match the template: `Fee reimbursement for trade 67437214`

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by TsLh32** [comment]
bc1q7wdl84r8q34v0v3ljm60n3kralqgc0e3u2ssj3 here it is. Thanks in advance.

**Comment by TsLh32** [comment]
Please, I'd like to know what else can I do about the issue on the BISQ Plataform, so I can unlock the locked security deposit Also I'd like to know and estimated time for the free reimbursement, if there is one. 

Thanks in advance.

**Comment by huey735** [comment]
There's no security deposit locked despite what the User Interface may show. See [this thread](https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223) for help or reach out to me on [Keybase](https://keybase.io/team/bisq). I'm huey735

Batch reimbursement are done once a per cycle at the end of the Proposal Phase should be around March 7th

![daoCycles](https://user-images.githubusercontent.com/44140017/107418341-6f8a9780-6b0e-11eb-9592-ad931f23cc1f.png)

**Comment by pazza83** [comment]
Hi @leo816 

Please can you add this to you reimbursement to do list.

Many thanks

**Comment by TsLh32** [comment]
Hi @leo816 and @huey735 .

Here is the requested btc adress for reimbursement:

bc1qafv2l365yaajqygfumgey5rjk6x0egj33lxl74

Thanks in advance .

**Comment by leo816** [comment]
Reimbursed with #1006
