### ISSUE TITLE
Fee reimbursement for trade 0A6I6u

### ISSUE THREAD

**Issue by Johannas333** [bisq-network/support#780]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Knipsel](https://user-images.githubusercontent.com/76809440/105219773-22428800-5b57-11eb-8712-c81f42480d95.PNG)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: fd69064d95ac04fffe5a4f40d02d603da7764ecf842be13cf6ea7c12ea5365f4
Taker: c9cdacf893e609dfa81930dd8eeb57cffd302d87870b17f2c6898d3f783876c2
Deposit: 664bc839a594a3018a8a163f41fd19c1f25275b628aa2b1e65f1c9f295d23476

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Transaction failed with v1.5.0 or later 

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by huey735** [comment]
Duplicate https://github.com/bisq-network/support/issues/687
