### ISSUE TITLE
Fee reimbursement and for trade NVDFODI

### ISSUE THREAD

**Issue by fupm** [bisq-network/support#781]
ID: NVDFODI-bbdfe8e6-1147-4ce6-a1d4-10f96df26181-151

SCREENSHOT HERE
![ID_NVDFODI](https://user-images.githubusercontent.com/76731476/107254163-54992400-6a37-11eb-87e1-7673cdc1bd4f.png)

Maker: 425f8cfb0806505782895bb3995244d6b6c850db7074e798199fe908498a9bd6
Taker: deef841e6d2d40ada05af78ef1fd2239727fe631d6203203f6d82e3279d0094f
Deposit: 12ca873240e928b79903008f3f92d9d0033341029d126dfc95b3def18eb14d62

Bisq version: 1.5.2

We never get the confirmation of the blockchain so that the trade never could get started and my BTC deposit is blocked since then.

Thank you in advanced.

**Comment by huey735** [comment]
Please edit the title to match the template: `Fee reimbursement for trade NVDFODI`
And change the screenshot to the rest of the info of the trade like #790. But do blank the sensitive information.

**Comment by fupm** [comment]
Done!

**Comment by pazza83** [comment]
Hi @fupm 

Thanks for posting.

I can see you have lost fees on this failed trade.

@leo816 please can you add this to your to do list.

Many thanks

**Comment by pazza83** [comment]
Hi @fupm what is your btc address for reimbursement?

**Comment by pazza83** [comment]
Closing as no response
