### ISSUE TITLE
Fee reimbursement for trade 3YBWGV

### ISSUE THREAD

**Issue by sandinocoelho** [bisq-network/support#783]
![image](https://user-images.githubusercontent.com/21991717/105582322-93a85380-5d6e-11eb-8568-a64ab75a7e16.png)

Maker:  c6ad1512d39f7f8fc923c8637079957ea0571a1e665be7ca8b20d336d6e2ee78
Taker: N/A
Deposit: N/A

An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=2049613506

Bisq version: v1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

Refund to address: 18eNUeKfr5oooYo6uCF8SJQKmBPeQPF5Pd

Because of that failed transaction, I had to cancel other 5 orders:
#784 
#785 
#786 
#787 
#788

**Comment by leo816** [comment]
Closing as reimbursed via the Batch Reimbursement [794](https://github.com/bisq-network/support/issues/794#issuecomment-768499013)
