### ISSUE TITLE
Fee reimbursement for trade ZQTUOOH

### ISSUE THREAD

**Issue by sandinocoelho** [bisq-network/support#787]
![image](https://user-images.githubusercontent.com/21991717/105595443-31e9e880-5d72-11eb-9a86-68d0f0df2caa.png)

Maker:  408cefc9c0a52de79c6125d9014788cc6c3f8b82933c3acb459d0a43cbfdb039
Taker: ...........
Deposit: ..........

Bisq version: v1.5.4

Other notes:
Refund to address: 18eNUeKfr5oooYo6uCF8SJQKmBPeQPF5Pd

**Comment by huey735** [comment]
Have you been guided by any Support Agent? Please reach out to me on Keybase. I'm huey735.
