### ISSUE TITLE
Fee reimbursement for trade wuwif

### ISSUE THREAD

**Issue by alien7867** [bisq-network/support#790]
![Screenshot_2021-01-24_18-04-06](https://user-images.githubusercontent.com/35934419/105646787-d2720280-5e6f-11eb-946c-c57a19befa81.png)

Maker:  32171dee44f855ed2bc2bef051e8b03691f84e527030d68ed15e8f09ee1374e3
Taker: 9605eb0d773bd1ad9135f4c31cb8ac6a96e84a223fb99f9a30464036dda218a2
Deposit: 16b8d9c78323cd6e9ca5e862806f0ade16974447bf3289f038b7be543e6cc6ea

Bisq version: 1.5.4

Other notes: Tried the suggested delete of pending trades and spv resync but no desired result

**Comment by huey735** [comment]
Who is guiding you in this issue? Is this trade still under Open Trades? Please edit the title to match the template: `Fee reimbursement for trade wuwif`

**Comment by alien7867** [comment]
Nobody is guiding me. Yes, it is under open trades in Bisq. Changed the title as requested.

**Comment by huey735** [comment]
Please reach out to me on [Keybase](https://keybase.io/team/bisq). Identify yourself by trade ID and role (BTC seller/buyer, maker/taker). I'm huey735.

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by pazza83** [comment]
Closing as no response
