### ISSUE TITLE
Fee reimbursement for trade T8EYUCS

### ISSUE THREAD

**Issue by passatparts** [bisq-network/support#791]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/77888846/105699342-7a86da80-5f07-11eb-9451-226d2a3262b5.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  c9600039005a99a3a069f7303e960a8e5b5dfe7d0e20c01f181c761049fcec4d
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by huey735** [comment]
This trade doesn't seem to have failed. Isn't this the Deposit transaction:  9816a1d0d9e11e0d360cf75eac00a4e01d829d7a9857f825723237343252e921?

**Comment by passatparts** [comment]
[image: image.png]

**Comment by passatparts** [comment]
[image: image.png]

**Comment by huey735** [comment]
Are you trying to share an image? It's not being displayed.

**Comment by passatparts** [comment]
Yes - a screen snip of the transaction showing (amongst other info) a red
exclamation mark which when clicked produces the error screen I first
sent.  Another attempt below
[image: image.png]

**Comment by huey735** [comment]
It's not showing. Please reach out to me on Keybase.

**Comment by passatparts** [comment]
Sorry I don't have Keybase.  Can I make a file in Google Drive and link you
to it?

**Comment by huey735** [comment]
We use Keybase for troubleshooting so please consider installing it. The point is that it's likely that this trade hasn't failed despite what the User Interface is showing you.

Please confirm if you can see these transaction ids under your Funds > Transactions tab:
- eee54676dc51e38ab1fdbe8ebb971056ee6816baa6d7231bda79a66b0a88f49b
-  9816a1d0d9e11e0d360cf75eac00a4e01d829d7a9857f825723237343252e921

If you do then the trade hasn't failed for you.

**Comment by passatparts** [comment]
I'm sorry I don't see those transactions:  I have made a Google Doc with
the screen shots in.  In case that  helps.  Menawhile I'll investigate
Keybase

**Comment by passatparts** [comment]
Sorry stupid me

https://docs.google.com/document/d/1gB0zuNqEqtofo0x7jlYYPlRuk4W5D81hm5_XEkmvEwM/edit?usp=sharing

**Comment by huey735** [comment]
It's not open to access.

**Comment by passatparts** [comment]
I think its OK now

**Comment by huey735** [comment]
Ok. It looks like you didn't successfully take this trade but also that you didn't spend any funds with it. The date for the trade above is January 22nd and there's no transaction on your wallet around that time.

Please take your time to reach out to me on [Keybase](https://keybase.io/team/bisq). Identify yourself by trade ID and role (BTC seller/buyer, maker/taker). I'm huey735.
