### ISSUE TITLE
Fee reimbursement for trade 25250642

### ISSUE THREAD

**Issue by Juraci** [bisq-network/support#793]
![Screenshot 2021-01-27 142018](https://user-images.githubusercontent.com/2266929/106028840-37656c80-60ab-11eb-9f4b-5a17c4160984.png)

Maker:  9f37c5a65cf84c34a7cfa4be1e027b908f08383cac56d50d4868b15520e681da
Taker: 3fd845200eb3b65d62c8c1586d1e4679761b49d269a889a67243f4da21046a8a
Deposit: 89a5f2ee5911a2fc86f2c81cfe41499f53ae17805a98826a0f881679e536e831

Bisq version:

1.5.4

Other notes:

From Bisq Client
```
Attention

The trade protocol encountered some problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here[1].

Feel free to move this trade to failed trades.

[1] https://github.com/bisq-network/support/issues
```

**Comment by leo816** [comment]
please provide your preferred btc address for the reimbursement

**Comment by Juraci** [comment]
@leo816  `182WGvwocDnnTnAEsUf8u8PkSeEDT3nz3W`

**Comment by leo816** [comment]
Reimbursed with #862
