### ISSUE TITLE
Fee reimbursement for trade 80366

### ISSUE THREAD

**Issue by bobzrkr** [bisq-network/support#795]
![failed-trade](https://user-images.githubusercontent.com/3431447/106045125-d2efe080-609d-11eb-96ed-f5d5838bd4a6.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 354af01ae7523c320ea282b986d612d4fdfe0dcdabc5cdc794188649f647d271
Taker: 
Deposit: e68a9a619a4c43bbb3bd3a7f4a74fa3a7f286783ac8489cc3ab579a573c5d050

Bisq version: 1.5.4

**Comment by bobzrkr** [comment]
I'm not sure if there are fees to be reimbursed. I paid 0.00015 BTC in transfer fees to fund the wallet, and then I may have lost the BSQ fee. I'm not sure.

**Comment by leo816** [comment]
taker fee was not published, reimbursement is not justified. Please add up your transactions to make sure you have any funds missing and contact us through keybase if you have any more questions. (my handle is leo816)
