### ISSUE TITLE
Investigate the 4 failures of trade SeiOKTX

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#80]
In the attached screenshots below, you see the same trade offer `SeiOKTX` being taken by a buyer four times.

The left side is buyer no. 1, attempting to take the trade twice. As you can see the the `Trade date` is just 90 seconds apart. The `Maker fee transaction ID` is the same, and the `Taker fee transaction ID` is different for each. This all seems consistent with the kind of timeout errors we've seen before, although, as far as I can recall, I've never actually seen the same trade get taken twice like this. The trade has always ended up in a failed state for both taker and maker. Perhaps I'm mistaken about that though.

Now, the mystery: on the right side, you see the same trade offer `SeiOKTx` being taken twice, this time by buyer no. 2. Again, the `Trade date` values are just a few minutes apart. The `Maker fee transaction ID` remains the same as it was in the trade attempts with buyer no. 1, but—and here's the thing—**the trade amount is different** on the right side. In the first pair of attempts the trade amount was `0.1250 BTC`. On the right, it is 0.18 BTC. Offers are not (yet) editable in Bisq. Therefore it is a mystery to me how these values could ever be different while the `Trade ID` remains the same.

![image](https://user-images.githubusercontent.com/301810/37139578-b77b20d8-22ae-11e8-9838-f2e26ab04292.png)

I have already reimbursed buyer no. 1 in #73, and I am going to go ahead with a reimbursement for buyer no. 2. shortly. I originally thought there may be some fraudulent behavior here, but that seems unlikely given the very small amounts being reimbursed (just the fees). There is something going on here that I don't fully understand, and I believe it may be the first time we've seen this sort of thing, thus my writing it up here.

@ManfredKarrer, any thoughts?

**Comment by ManfredKarrer** [comment]
The offer probably had min. amount set lower so the trader 2 used a lower amount. taker fee txid is different as expected in that case as a new take-offer attempt use a new address.

can you post the onion address and offer details so we can try to contact the maker? seems his app is buggy or old...

**Comment by cbeams** [comment]
Closing as (investigation) complete.
