### ISSUE TITLE
Fee reimbursement for trade 4954

### ISSUE THREAD

**Issue by Wrecktangl3** [bisq-network/support#801]
Hey there, I tried to buy some Bitcoin yesterday but it failed and wouldn't go passed the first step.

![Bisq 2536](https://user-images.githubusercontent.com/77015544/106584576-454d3e80-653e-11eb-8f80-ba473deb7cfe.PNG)
![locked](https://user-images.githubusercontent.com/77015544/106584594-48e0c580-653e-11eb-8d52-26a2f2df1ca8.PNG)

Your system said I was owed a reimbursement by yourselves.

Bisq version:

1.5.4

**Comment by huey735** [comment]
Please follow the [issue template provided](https://github.com/bisq-network/support/issues/new/choose).
