### ISSUE TITLE
Fee reimbursement for trade 49540385

### ISSUE THREAD

**Issue by Wrecktangl3** [bisq-network/support#802]
![image](https://user-images.githubusercontent.com/77015544/106586559-847c8f00-6540-11eb-84ef-aa22f09291b6.png)
![locked](https://user-images.githubusercontent.com/77015544/106585388-361ac080-653f-11eb-8fab-66be3f230df4.PNG)

Maker: 1a4a64eccbedcc94a18d4757aef47820bb378e15ad47be1836954e1b4b3c0e51
Taker: da95374cb187f061075efbaab9e31a2b4d29f40164d40357997517ebf2f9f78a
Deposit:  0.0150 BTC

Bisq version:

1.5.4

Other notes:

Attention

The trade protocol encountered some problems.

The deposit transaction (the 2-of-2 multisig transaction) is missing.

Without this tx, the trade cannot be completed. No funds have been locked but your trade fee has been paid. You can make a request to be reimbursed the trade fee here[1].

Feel free to move this trade to failed trades.

**Comment by huey735** [comment]
Hello. Please reach out to me on [Keybase](https://keybase.io/team/bisq) regarding https://github.com/bisq-network/support/issues/797. I'm huey735.

**Comment by leo816** [comment]
was this solved?

**Comment by pazza83** [comment]
Hi @Wrecktangl3 

I am closing this ticket. Please respond if it is still to be actioned.
