### ISSUE TITLE
Fee reimbursement for trade 46493464

### ISSUE THREAD

**Issue by tvdatt** [bisq-network/support#803]
![Captura de pantalla 2021-02-02 a las 12 46 23](https://user-images.githubusercontent.com/78419380/106596274-10001b00-6555-11eb-9494-7e2ce5d94622.png)

Maker:  57a1c8e1ef0e222ad1c084cb3db36c14f107c1c3848a7215857c1cbdcc443dd4
Taker: ba22519eaac3c933faf05e49f0c1825d9eccb042975c4053141f258510167243
Deposit: 6400189135ad76736cf7ed8260065a909bec5bdeb9d3e76de774bac46f79fb92

Bisq version: 1.5.5

Other notes:

Deposit transaction does not go into mempool, already contacted support via Keybase

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by tvdatt** [comment]
32Jk93h1ccoXrQUiuwKrUQJ1S8J2rNGhKZ

Thanks.

**Comment by leo816** [comment]
Reimbursed with #926
