### ISSUE TITLE
Withdrawl Transaction Stuck for 2 Days

### ISSUE THREAD

**Issue by kkmckp** [bisq-network/support#805]
To Whom It May Concern,

I initiated a transaction to withdraw from my Bisq wallet but the transaction has been stuck for 2 days.  It only shows 1 confirmation and so has not been released.  Can you please assist?  Thanks.

https://blockstream.info/tx/4e9358cfe4cd002109ed6805d7559197b7d2a5150cca5470f3a0ff9721ce9a6a

**Comment by MwithM** [comment]
46 confirmations now.
For that amount, 1 or 2 confirmations should be secure enough, and your wallet should display the incoming transaction even with 0 confirmations (which are not secure). https://en.bitcoin.it/wiki/Confirmation
