### ISSUE TITLE
Fee reimbursement for trade 99556

### ISSUE THREAD

**Issue by Luk3zi** [bisq-network/support#806]
<a href="https://ibb.co/JccPvQv"><img src="https://i.ibb.co/p11pfyf/bisqrefund1.png" alt="bisqrefund1" border="0"></a><br /><a target='_blank' href='https://it.imgbb.com/'>mettere un immagine html</a><br />

Maker:  b58fb62e102026e7ee464a04970b60cb8a809b1599823f86238e59849d2523d2
Taker: 87c0379f0de6fa3bed5cc3063f3bfe4418b6f674dbc34b268191ef57fe2d1ee9
Deposit: ..........

Bisq version: v1.5.5

I lost mine deposit too through this, it didn't come back yet

**Comment by leo816** [comment]
please provide your preferred btc address

**Comment by Luk3zi** [comment]
bc1qwe7cp4ecdm0nwghmdjf86f86dkr84th7n1kfp2

Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by leo816** [comment]
btc address is not valid

**Comment by Luk3zi** [comment]
Oh sorry, this should be okay

bc1qhrtkr8xlh6he9hgpw0cswjykut4yjvj330u7aq

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 7 mar 2021, 21:11, leo816 ha scritto:

**Comment by Luk3zi** [comment]
Hi, Will have my sats back?

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 7 mar 2021, 21:50, luk3zi ha scritto:

**Comment by leo816** [comment]
Reimbursed with #926
