### ISSUE TITLE
Fee reimbursement for trade w6BnGI

### ISSUE THREAD

**Issue by refunq** [bisq-network/support#807]
![Screen Shot w6BnGI 2021-02-02 at 19 44 15](https://user-images.githubusercontent.com/78498508/106786070-6dc45e00-664e-11eb-9c70-fcf88e60a075.png)

Maker:  5cd27952094e2b2fdc5d31acb3e91b371ba2edcb7e67fde789b77f65d33b2ef0
Taker: N/A
Deposit: N/A

Bisq version: 1.5.1

Other notes: "Protocol did not complete in 60 sec" , the trade failed and is left in state INIT

I am asking for an reimbursement of the locked Maker fee

**Comment by leo816** [comment]
taker fee was not created and reimbursement is not justified. if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades
