### ISSUE TITLE
Fee reimbursement for trade ZQ8MJZ

### ISSUE THREAD

**Issue by ganaque** [bisq-network/support#809]
![Untitled](https://user-images.githubusercontent.com/44710786/106827001-07433e00-6656-11eb-86a5-876941db95e1.png)

Maker:  5e3a41fd4930495eeefef3ec3ce7a3846881c3749a4aea4b065e7106d0a573c2
Taker: b297cdd93314a928c152fbfdfc24999e7b27f1a72b2e5f800122ad1b8d5aa7cd
Deposit: 0.006 BTC

Bisq version: 1.5.5

Other notes:
Has failed and transaction stuck in "wait for blockchain confirmation" for more than a day

**Comment by huey735** [comment]
Please delete the image, blank out the sensitive information and re-upload it.
