### ISSUE TITLE
Fee reimbursement for trade 3042853

### ISSUE THREAD

**Issue by Ts00P** [bisq-network/support#810]
![trade-3042853](https://user-images.githubusercontent.com/25666838/106883797-c3494b00-66e0-11eb-91e0-9a241c3781b8.png)

Maker: 04cf93d89fe2269fe9f97904bc78f816841f82ae8c6972aaa04e42601171d6c7
Taker: eef4b9e407b6fbc605be7f99765123fb2fe8a1b07000c76ab06d5cef268712d2
Deposit: 0482101c62ff3f925df651abb9ab0bf2e040d9bf4dc76d8550671be1c319b1be

Bisq version:v1.5.5

Other notes:
2-2 mutlisig failed

**Comment by leo816** [comment]
please add your preferred btc address for reimbursement

**Comment by Ts00P** [comment]
here's the btc address

bc1q0mr0uveedpjwzm72dgzsh7wng9wxrwl8kxvhw3

**Comment by leo816** [comment]
Reimbursed with #926
