### ISSUE TITLE
Fee reimbursement for trade v6glkq5

### ISSUE THREAD

**Issue by 2cp-e** [bisq-network/support#811]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![2021-02-04_bisq_failed_v6glkq5](https://user-images.githubusercontent.com/78540727/106892556-83886080-66ec-11eb-927d-c28e6a993941.png)

Maker:  39380db97c8e9ad11f2aae3b55a42aba2c6a97d7e34b843ae827c3161a235281
Taker:    99cc147fd0f3df22f546ce2190b75edb571d83386a9d999834414f9d7fdb771d
Deposit: N/A

Bisq version: v1.5.5

**Comment by leo816** [comment]
please provide you preferred btc address for reimbursement

**Comment by 2cp-e** [comment]
bc1qs4l4uxzzhv3faj9m0qwwva5nefjm6ql2x6fwyd
thnx!

**Comment by leo816** [comment]
Reimbursed with #862
