### ISSUE TITLE
Fee reimbursement for trade ZQ8MJZ

### ISSUE THREAD

**Issue by ganaque** [bisq-network/support#812]
![Untitled](https://user-images.githubusercontent.com/44710786/106969669-4a1a1a00-6719-11eb-97f2-ee1ce60f95f9.png)

Maker: 5e3a41fd4930495eeefef3ec3ce7a3846881c3749a4aea4b065e7106d0a573c2
Taker: b297cdd93314a928c152fbfdfc24999e7b27f1a72b2e5f800122ad1b8d5aa7cd
Deposit: 0.006 BTC

Bisq version: 1.5.5

Other notes:
Has failed and transaction stuck in "wait for blockchain confirmation" for several days

**Comment by leo816** [comment]
please provide the deposit tx id

**Comment by ganaque** [comment]
deposit tx id b037a1206c1a646707735866c9cd5da876fd4172bd88b4f3b9cc4481aaf9fc33

**Comment by pazza83** [comment]
Hi @ganaque 

Thanks for providing. I can see you lost fees on this trade.

Please provide a BTC address for reimbursement.

Many thanks

**Comment by pazza83** [comment]
Hi @ganaque

Please can you provide a BTC address for reimbursement.

Many thanks

**Comment by pazza83** [comment]
closing as no response
