### ISSUE TITLE
Fee reimbursement for trade 32432

### ISSUE THREAD

**Issue by thespear256** [bisq-network/support#813]
>_The 32432 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/76235859/107109440-9d21c900-680e-11eb-9086-7e0f42e5b32e.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  478fb9a14b0b32453ec5f0a048126463a9188c874e08bff555cf9e37c7120562
Taker: 42dacd1994fd6335b6e7f804a9704babfbe823dbaf85f8b410ee73602baf2804
Deposit: 171c8da73cbe5a1685b05b84fc5ff4ef42c5e53ad15a0bc3601efc3aa9ff23cd

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:1.5.4

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by huey735** [comment]
@thespear256 please edit the title replacing `XXXXX` with the trade id, `32432`

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by thespear256** [comment]
bc1qnzm9hqe77z9l4zce3cdz9m845zq76kh870yznj 

thank u

**Comment by leo816** [comment]
Reimbursed with #862
