### ISSUE TITLE
Fee reimbursement for trade 46803

### ISSUE THREAD

**Issue by felipegtx** [bisq-network/support#814]
![image](https://user-images.githubusercontent.com/1022404/107128144-330f2f80-68b3-11eb-9f83-8c0cb2a2b65b.png)

**Maker:**  3c2a59ca7cc2effa8a75e9195305a47f8386c3338c21806dede93c7d4306ee8d
**Taker:** 2d1c13f0c58eb59c1d0871890afe3c390ed828ce68857e0a9e82f4da19dd313d
**Deposit:** adbe9c4cbe73308a20e4aa13f80f3068167bc828ddc8efa78455e92dcb93a6d5

**Bisq version:** 1.5.5

**Other notes:** The transaction took a long time to process, I did a “Delete SPV and Resynced” and then it showed me this message after it restarted:
![image](https://user-images.githubusercontent.com/1022404/107128130-1ecb3280-68b3-11eb-8d70-cf79736478b4.png)

Also, it looks like I have **0.075180BTC** locked as a side effect of this failed transaction.
`AddressEntry{address=bc1q..., context=MULTI_SIG, offerId='46803-bfa2e303-3eaf-4673-bb11-32cfee004f69-155', coinLockedInMultiSig=7518000, segwit=true}`

**Comment by leo816** [comment]
please provide you preferred btc address for the reimbursement, regarding your locked funds, a SPV resync should fix it. If not then: "if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easisest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades"

**Comment by felipegtx** [comment]
Please send it to `bc1qsqyxlp0ml0pa90wv3da48pc0mdf9jhyc35wzuc`.

I'll wait until the funds reach that wallet to perform the suggested action on top of my `dbs` once I'm hoping the "missing funds" to come back with it. Do you have an ETA for this transaction to start?

**Comment by leo816** [comment]
Reimbursed with #862
