### ISSUE TITLE
Fee reimbursement for trade BV4QTFH

### ISSUE THREAD

**Issue by samotokram** [bisq-network/support#815]
![image](https://user-images.githubusercontent.com/78666594/107131522-9317cd00-68d7-11eb-9a26-318abb21097e.png)

Maker:  8603f13daeb87edb5acf5c58a7191563bdb96e24704d6c57b69ec78bc3d998d5
Taker: d26692ae08117ef5b4989e756e5b1c92af03a854b49589da3206b62125a6c625
Deposit: 7a88c0a7e0701959bd15fa68727fde373f8116b87f50a354bf369ef8a977f239

Bisq version:v1.5.5

Other notes:
2-2 mutlisig failed

**Comment by samotokram** [comment]
Bisq version:v1.5.5

Other notes:
2-2 mutlisig failed

**Comment by leo816** [comment]
were you the maker or the taker?

**Comment by samotokram** [comment]
i was the maker

**Comment by samotokram** [comment]
I was the maker


______________________________________________________________
> Od: "leo816" <notifications@github.com>
> Komu: "bisq-network/support" <support@noreply.github.com>
> Datum: 26.02.2021 00:00
> Předmět: Re: [bisq-network/support] Fee reimbursement for trade BV4QTFH (#815)
>
> CC: <author@noreply.github.com>

were you the maker or the taker?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bisq-network/support/issues/815#issuecomment-786284842",
"url": "https://github.com/bisq-network/support/issues/815#issuecomment-786284842",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by samotokram** [comment]
hello, my btc adress is - bc1q2dhelnvktnlfhvnjmffwrf5yew4lg2qtqczura
 
 
 
______________________________________________________________
> Od: "leo816" ***@***.***>
> Komu: "bisq-network/support" ***@***.***>
> Datum: 08.04.2021 00:50
> Předmět: Re: [bisq-network/support] Fee reimbursement for trade BV4QTFH (#815)
>
> CC: ***@***.***>
 
please provide your preferred btc address for reimbursement

**Comment by leo816** [comment]
Reimbursed with #926
