### ISSUE TITLE
Fee reimbursement for trade 59650

### ISSUE THREAD

**Issue by zsoltmoravcsik** [bisq-network/support#816]
SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/31081836/107228415-f0696680-6a1c-11eb-83c9-d178c340ec84.png)

![image](https://user-images.githubusercontent.com/31081836/107228701-40482d80-6a1d-11eb-9668-19814d44067b.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:

Bisq version: 1.5.5

Other notes: The transaction took a long time to process, when I try to notify my trading partner I got this:
****
![image](https://user-images.githubusercontent.com/31081836/107229216-ce241880-6a1d-11eb-99dc-69d3d6d5b91a.png)

TXTlog:
if you need I can send it on Keybase.

**Comment by leo816** [comment]
taker fee wasn't published, reimbursement isn't justified.
