### ISSUE TITLE
Fee reimbursement for trade 59650

### ISSUE THREAD

**Issue by Augustas11** [bisq-network/support#817]
![image](https://user-images.githubusercontent.com/28995904/107243806-0f282700-6a36-11eb-8aae-1d6376b1dbcf.png)

Maker: 696bd50ec5a978e9de3fc594a1d8f088c0d7eab228df8be00c6ae3e69cac2be4
Taker: ...........
Deposit: ..........

Bisq version: 

1.55

Other notes:

**Comment by leo816** [comment]
taker fee tx id wasn't created. Reimbursement is not justified
