### ISSUE TITLE
Fee reimbursement for trade 073303

### ISSUE THREAD

**Issue by ReginaldVHunter** [bisq-network/support#818]
SCREENSHOT HERE

![image](https://user-images.githubusercontent.com/15248736/107283751-b74ce880-6a54-11eb-8b09-fe6a83f67f5a.png)

Maker:  ac7b064f59c6a93ed296eb0442cdff55a04f3875f334b79e82fe443eb2423095
Taker: 650a3d3d10d4b6177b577576bd2406e6beedb42579276dbe54e0e3a324b4dc6a
Deposit: 9aefd88884d512d0b89011215272664a4aaea8b5b158daeadc9836d75efc839e

Bisq version: v1.5.4 /v1.5.5 (might have updated after/during this trade)

Other notes: Deposit transaction is missing message popped up and the deposit transaction is highlighted red in the trade view. Which is reason trade cannot complete.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide your preferred btc address where you would like to receive the reimbursement

**Comment by ReginaldVHunter** [comment]
bc1qz3cvps80r3a92daac8c0n5thzacjngjmpg5hvn

Thanks
________________________________

**Comment by ReginaldVHunter** [comment]
Hi,

Has there been any update regarding this?

**Comment by leo816** [comment]
Reimbursed with #862
