### ISSUE TITLE
Fee reimbursement for trade 2978873

### ISSUE THREAD

**Issue by speedy5539** [bisq-network/support#819]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Untitled-2](https://user-images.githubusercontent.com/78820435/107416662-06f2e900-6b15-11eb-98da-5d1676e7b6b9.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  169a3821a41ca8cc74652b8764da4e49a7d92a4aeceeecdc03d8dfdf7e3dc3a3
Taker: 19e13a321c42e19b5121834b9785e4052f477c77ed23655101788940ffb35f48
Deposit: 3c5b5258b06721340289572a3d1fa1ed62909895431d27a56e4785d9ba813090

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.5

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
reimbursement is not justified. Trade completed correctly.
