### ISSUE TITLE
Fee reimbursement for trade QUANGEX

### ISSUE THREAD

**Issue by AzidanoValkran** [bisq-network/support#820]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/78864939/107536632-e4ff7200-6bb9-11eb-8086-a2991fc28551.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  fedc871f03d09288e23e11d9f2e654b14f2c68648b1e648c7bd7f795cdb3cf3d
Taker: b43aed2051350ac2ec8edd0459258082c50e950b45f8698cde085d87d6455379
Deposit: 094b0a9c2aae2ce547bced6501c1c2d23a40276aa0341f09aa4acb6ee5e9f136

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.5.5

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
trade failed, please provide you preferred btc address to receive the reimbursement

**Comment by AzidanoValkran** [comment]
Hi @leo816 sorry for the late response.

Please send the reimbursement to the following btc address:

bc1q2vqapeh63qsu26e3g6q48n0nj8hc7pcj2d7pmd

**Comment by leo816** [comment]
Reimbursed with #862

**Comment by AzidanoValkran** [comment]
Thank you for the reimbursement of the Maker transaction fee.

My 0.04 BTC is still locked up in the trade? Will this also be reimbursed? How do I get this back?
