### ISSUE TITLE
Reimbursement for trade date 19.12.2020

### ISSUE THREAD

**Issue by piuhyufo** [bisq-network/support#824]
Hello.

I opened a deal for the exchange of BTC-XMR, when my hard drive broke. I made backup but it was on the same disk (and I made backup before I opened the trade). The seller sent me XMR, but I did not have possibility to confirm the deal because couldn't go into the wallet. Yesterday I was able to restore the seed (got it from the broken disk) and the date when the wallet was created. But I have no disputes, no history of the transaction in my account.
In the address history, I see 2 used addresses. Checked them on the blockchain and saw that the funds from the second address were automatically transferred after 10 days to the donation address bisq.

Unfortunately I don't have trade ID.

I can provide the address where I deposited 2.3BTC for trade. 2BTC was the trade and 0.3BTC deposit.

The deposit address is bc1qf3rq02p4w094a99wvree8s2lx68xnwsfkccun2
Then BTC was moved to this address with seller's deposit bc1qx7nmqkw7z3wxa2gnfhrrpfkea3d09fc3r5e04u94zvmw4p3vvulsy0kwyr
And then after 10 days to bisq donation address.

I lost my deposit ... which was 0.3 bitcoin, a lot.

Is there any way to get my deposit back?

It is very strange that disputes are not restored through a seed phrase. In this case, you need to make a full backup of the wallet for each new open trade.

Thanks for help!

See further details on for making a reimbursement request here: https://bisq.wiki/Making_a_reimbursement_request

**Comment by refund-agent2** [comment]
The data of your trade corresponds to this other reimbursement [issue](https://github.com/bisq-network/support/issues/684).
All your security deposit was awarded to the BTC buyer by the DAO through a BSQ reimbursement. Bisq can't give you back any of it as it's spent already.
I'm sorry for your loses, you could have reported to support that you lost the data and access to funds sooner, during the trading window or at least once arbitration was opened but payout was not settled yet.

**Comment by pazza83** [comment]
Closing as per above comment.
