### ISSUE TITLE
Fee reimbursement for trade EQ022

### ISSUE THREAD

**Issue by tananaev** [bisq-network/support#826]
<img width="1326" alt="Screen Shot 2021-02-13 at 11 17 03 AM" src="https://user-images.githubusercontent.com/1161863/107859262-2166e400-6ded-11eb-88a8-a3c8621a52aa.png">

Maker:  c1a0e4e0411c5a4a40787367b7a48ae1f737eaf9e9b4354c1d867b26e6013cbf
Taker: c584c7edb129b1e1b48ba0f6af70b68ec878d951861f6df38ca0c2e8d7ff5bf5
Deposit: 4119b57fa3df4fb4792ddd74aa6ed87a8889e21764465e7f6d2698b536b1ab97

Bisq version: v1.5.5

Other notes:

Looks like taker transactions are missing from the blockchain.

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by tananaev** [comment]
Please use this address:

bc1qz9kgl8q5ptxu32f0h24tlf8ph22j57syzs7zr0

**Comment by leo816** [comment]
Reimbursed with #862
