### ISSUE TITLE
Fee reimbursement for trade udnnh

### ISSUE THREAD

**Issue by 72khz** [bisq-network/support#827]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![reimburse-request](https://user-images.githubusercontent.com/79034109/107868964-ac2bfb00-6e4e-11eb-89b2-eef5ba971b10.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

**Maker:**  4d48375acf2f955fd1bde87f9f9c4f37219bfcd19aeb3f83e979124dfc862fb4
**Taker**: e146fd0878db7002ae08fc14c1157f6d58717e1c55c292b396ad2d6cac5b1de5
**Deposit**: c748ab194a13f7073111f1ac1117973392eadf4b73f881f5c0563145884bb745

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.5.5

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: Trade failed on step 1 after fee deposit. Funds lost. Please reimburse.

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
were you the maker or the taker? please provide the full screenshot of all the trade details

**Comment by 72khz** [comment]
> were you the maker or the taker? please provide the full screenshot of all the trade details

Thank you for your response, @leo816. I was the taker. I have updated my Bisq version since the initial trade. Screenshots have been included below of the open trade section window, the open trade chat window, the attention/error message window within the open trade section and failed trade section. 

**Screenshot of Open Trade Window (Open Trade Section Window):**
<img width="1197" alt="1-Trade ID udnnh - Screenshot of Open Trade Window" src="https://user-images.githubusercontent.com/79034109/109406490-32f8d180-793f-11eb-8f61-21282f7976e8.png">

**Screenshot of Trade Chat (Open Trade Section Window):**
<img width="756" alt="2-Trade ID udnnh - Screenshot of Trade Chat" src="https://user-images.githubusercontent.com/79034109/109406494-3b510c80-793f-11eb-867f-3223ee5f419e.png">

**Screenshot of Attention/Error Message Window #1 (Open Trade Section Window)**
<img width="1199" alt="3-Trade ID udnnh - Screenshot of Attention Window" src="https://user-images.githubusercontent.com/79034109/109406497-42781a80-793f-11eb-9367-45f4b68d859e.png">

**Screenshot of Attention Window/Message #2 (Failed Trades Section Window):**
<img width="1196" alt="4-Trade ID udnnh - Screenshot of Attention Window 2 - Moving to Failed Trades" src="https://user-images.githubusercontent.com/79034109/109406523-73f0e600-793f-11eb-96ee-e032345c95cb.png">

Additionally, if you need the the detailed JSON trade udnnh data and/or an un-blurred screenshot of the trade details (the first screenshot image that was posted in the initial support request message on this thread by me 14 days ago) for complete verification, I can provide those as well. For privacy, these file access links are password-protected and will each expire within 30 days (March 29, 2021). If access to the detailed json trade data and/or un-blurred screenshot image of the trade details, please contact me via email for the password: 72khz@pm.me

_Detailed JSON trade udnnh data (.txt file):_
_https://drive.protonmail.com/urls/2X59V735HG_

_Un-Blurred Screenshot of udnnh Trade Details (.png file):_
_https://drive.protonmail.com/urls/8H3XK3JS7M_

❤️

**The information provided should verify the information of the trade, allow for the successful unlocking of funds and resolves this issue. If this is not the case and more information is needed, please let me know on this support request thread, or, you can contact me via email (72khz@pm.me) for any additional steps, or email me to receive password access to the 2 private links posted above.** 

With that said, I want to close the response with this: Thank you for your time, your attention, and for helping support one of the world's first _(and, in my opinion, the best)_ decentralized cryptocurrency trading platforms available right now. I wish the process to request and unlock funds from failed trades was much easier for Bisq _(because I would really like to receive the BTC back... just a thought for the future from an active Bisq user: can we somehow automatically and securely submit private trade information data [within the Bisq app] similar to how the XMR auto trade function works? Just a thought I had...)_, Anyways, I understand that the technology is still new, and time is very limited. Since it's new, and, like many of these new decentralized blockchain projects, there are still improvements to be made, kinks and issues to be worked out, but, ultimately, the Bisq network _will_ improve over time. Bisq already has a proven track record of incredible features, updates and fixes. This is the first time I've had a major issue like this and I've successfully used it for quite a few trades. Kudos to the whole Bisq team. I cannot speak on behalf of the traders or community members, nor do I know the entirety of your role for the Bisq network _(other than your response to this support request)_, but, from my perspective: your work, time, insight and vision are sincerely appreciated and valued as we begin to enter into the blockchain economy. Warm regards.

**Comment by 72khz** [comment]
Hi @leo816 has there been any update on this at all?

My BTC address in case it is necessary for the next steps: bc1qpcadn9q70gpv80r4kwfrx4svkxsmqyr7excqf3

Thanks again for your help!

**Comment by 72khz** [comment]
Hi @leo816 it has been almost 2 months since this initial request. Can you, or someone from the Bisq community/support team, _at least_ please give me confirmation on whether or not these funds will be reimbursed. @KanoczTomas @huey735 @cbeams 

Any next steps or insight would be appreciated. Thank you again for your time.

**Comment by leo816** [comment]
sorry that I didn't answer earlier, the taker fee wasn't published and the funds never left your wallet. Therefore a reimbursement is not justified. If this were to happen in the future please contact us through keybase, my handle is @leo816
