### ISSUE TITLE
Can not resync DAO State if I have a conflict

### ISSUE THREAD

**Issue by Willi2814** [bisq-network/support#828]
Hi.
The moderator "leo816" ask me to open this issue.
 
I am using:
Apple Macbook Air
OS X El Captain 
10.11.6
Bis: 1.5.5

I have the following issue:
I open Bisq go to DAO - Network monitor - DAO state 
One of your peers is not in consensus with the network but your node is in sync with the seed nodes.
I have one or more conflicts.
The moderator told me to resync the DAO state.
But there is no button to resync.

**Comment by MwithM** [comment]
Other than this message, is your node not working as expected. I think it's ok to not be completely synced with all nodes, so there's no need to show the resync DAO button.

**Comment by Willi2814** [comment]
Hi.
In general everything is working.
But I have an issue with an BSQ trade.
I am the BTC seller and I don´t receive the BSQ. The moderator ask me if I have a conflict in the DAO and ask me to resync the DAO status. (No button).

**Comment by MwithM** [comment]
I suppose the transaction is confirmed already. I don't remember now if there's another way to resync DAO state.
