### ISSUE TITLE
Reimbursement for trade pQ1fhP

### ISSUE THREAD

**Issue by matheusjuvelino** [bisq-network/support#829]
![image](https://user-images.githubusercontent.com/15352892/104049260-6e8ae100-51c3-11eb-901a-e00a79c114cf.png)

Maker:  d2bd1d16d588e993124b76d75fd0cef999960b512c406888fbc7cf7338ce6855
Taker: 388f9ad306589c39a389ba1c18e18ab4801c43ce2a5dba93e0394257bbccf533
Deposit: 728132ccd0ba6324dc36a7858f5c6ae8ca6fc27db2409db1215d6f9626b60a7c

Bisq version: v1.5.5

Other notes:

I inform you that the fee has already been refunded according to issue #746.

However, the balance remains blocked as shown below:
![image](https://user-images.githubusercontent.com/15352892/106190461-761d2480-6188-11eb-93d8-8b31903cc097.png)

I request the release of the balance.

**Comment by MwithM** [comment]
Read this [troubleshoot guide](https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1) and if it doesn't work, proceed to [support channel](https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1).

**Comment by matheusjuvelino** [comment]
the documentation helped, problem was solved.
