### ISSUE TITLE
Cannot exclude a person to take a trade, xlvna3y

### ISSUE THREAD

**Issue by keo-bisq** [bisq-network/support#83]
For trade xlvna3y it was impossible to pay via Cash App. This was known by the Maker since a previous trade with the same peer failed for the same reason. He tried to ban the takers onion address which did not work and he thus wants to be reimbursed for the fee. This issue has been raised on bisq-network/desktop Cannot exclude an onion-address to take an offer #1460

maker tx: 4c6aabadc3829db5583e4e05b09de99f0f1f6c7d0e33b8f53114d095be899fc4
taker tx: 3b1c5bd6ef6e75c64c21d0f9518036f36cf6968f85a52b486b5aa09b2b47a956
maker fee: 0.01 btc
taker fee: 0.003 btc
maker/taker adresses: 
1BYdDbXTE7CZh2SvbkAkVvf7p3B6gbWn7y / 1AC6E3kuwJ276zV4rgFtFrX5jw75JQAGCe

Keo

**Comment by marcusdiaz** [comment]
So then why continue to use Cash App if he can't use it?

**Comment by pazza83** [comment]
Closing as stale
