### ISSUE TITLE
Fee reimbursement for trade 5172383

### ISSUE THREAD

**Issue by Leonamrsm** [bisq-network/support#830]
![5172383](https://user-images.githubusercontent.com/52931821/107996218-9f2e1980-6fbe-11eb-86cc-3d0b5b2acd9c.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  8477b8d646c0137326c2f469ae71bad83ab7cd0dae3bd9bfb7350175829b9929
Taker: .8d8f82fff94432e0299a3e6b84ca63b6916c76d063fc657f93c646102ee3ddf8
Deposit: f0c930643b050a0d38dd371d690f146ad954f6960471e6ca22cd82590fa7cae3

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.5

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by pazza83** [comment]
Closing as no response
