### ISSUE TITLE
Fee reimbursement for trade yzsvpt

### ISSUE THREAD

**Issue by misch2** [bisq-network/support#832]
![image](https://user-images.githubusercontent.com/16558674/108242565-58225e80-714d-11eb-9875-0cf28c0767ac.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  895e0565c0d57e8ac17b7aba307e6db7788d43dae4e1fb588661c1a503d2dd55
Taker: 7e55d6bb2479c205ad9b993178b7e59d82a469c30bdac66033ea58872d86a7a7
Deposit: 1c1d78382a4aaf94277d9dab01914a90d81c4855fef6ca5998705b0155e170b6

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.5

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
please provide your preferred btc address for reimbursement

**Comment by misch2** [comment]
> please provide your preferred btc address for reimbursement

That would be bc1qkdha0nqjae5unrwm9xm3gw6f0um4law9v4hx2z
Thank you.

**Comment by leo816** [comment]
Reimbursed with #862
