### ISSUE TITLE
Fee reimbursement for trade 7d5fibk

### ISSUE THREAD

**Issue by tibletor** [bisq-network/support#834]
![Screenshot from 2021-02-18 14-47-27](https://user-images.githubusercontent.com/78879350/108366671-eacc0780-71f8-11eb-8840-dc884f035d30.png)

Maker:  60844e6fb987f74a58863b9db8cf33cede0ec291155a309d85f1ab9c69af4bfa
Taker: ...........
Deposit: ..........

Bisq version: v1.5.6

Other notes:
Error message:
An error occurred at task: ApplyFilter
Other trader is banned by their node address.
tradingPeerNodeAddress=xpuite4hwk7uvplsvfcozolwrvtd5mig4pv4j3vh4m6fgyt7magbk7qd.onion:31337

**Comment by leo816** [comment]
were you the btc buyer or the seller? please send a screenshot of all the details

**Comment by pazza83** [comment]
Closing as no response
