### ISSUE TITLE
Fee reimbursement for trade dfivlh

### ISSUE THREAD

**Issue by BuckshotTim** [bisq-network/support#837]
![failed trade](https://user-images.githubusercontent.com/79407825/108629140-2f87b680-7424-11eb-84ce-7dab6aeff97c.PNG)

Maker:  e6b0fcd81226c1fc788f3247f8d5c2c1dd9e161e18e6757899208e0c0d4ead23
Taker: 0a642338e470d79b6a44f3ee067585d7e10a60259c1fcd1c15b494b2f3927372
Deposit: 6e4d13c8269d0fe071bc8e3c15ad2688091ff388d3b917edad96c3b28bf2a74a

Bisq version:

1.5.6
Other notes:

Please reimburse fees for this failed trade

**Comment by askkbisq321** [comment]
I actually have 1.5.1 or so it says at the bottom of the Bisq Home page. Thanks Buckshot for getting me this help.

**Comment by leo816** [comment]
please provide you preferred btc address for reimbursement

**Comment by BuckshotTim** [comment]
Sorry, I injured myself and have been away healing-up. I'll get that btc address here in a bit

**Comment by askkbisq321** [comment]
Leo,
Thank you so much for helping. Just got this request. 
Should I use a btc address generated from my Bisq account?

**Comment by BuckshotTim** [comment]
My BTC address for reimbursement:
bc1q9vy9cg9rzz6xpws876c632mvpp6535upuutf68

**Comment by askkbisq321** [comment]
Hello Leo,
Can I use an address generated from my external wallet?
Thanks again!!

**Comment by askkbisq321** [comment]
Bitcoin address as requested

> bc1q8atfdzkq25dzddrswr04ycf5xlw85wjm4tdwqp

**Comment by askkbisq321** [comment]
Im not sure why bother user is responding to this request. BuckshotTim

**Comment by askkbisq321** [comment]
Hello. I am having problems resolving this trade. You seem informed and it seems you are reaching out to help. Can you direct me join the right direction?
Thank you

**Comment by leo816** [comment]
ok, I added this to lost fee reimbursements, for some reason it wasn't included. It will get reimbursed next cycle.
@askkbisq321 are you the counterparty for this trade? if so you would need to create a separate issue

**Comment by askkbisq321** [comment]
Thank you. I was the purchaser. 
Do I need to create a "new issue”?
How will it be different from the last one I posted?
Thanks so Much for your help.

Bg

**Comment by BuckshotTim** [comment]
@askkbisq321 the bisq funding btc address I provided no-longer appears in my funding addresses on bisq, I saw today. Do I need to grab a more current funding address?

**Comment by BuckshotTim** [comment]
Ugh...my bad. I meant to direct that last @leo816  about my address for reimbursement

**Comment by BuckshotTim** [comment]
@leo816 If we need another address for reimbursement (do the bisq funding addresses cycle themselves out after a while, or something? The one I gave you never got used. It just doesn't appear among my addresses anymore), let's just use this one: 1MnGP5qRDTNTFsRqCTeapL9FR32EBJAXv9

**Comment by askkbisq321** [comment]
Sorry. I am. bit confused about this thread. I remain eager to resolve this trade. What am I needing to do now?
Thanks

________________________________

**Comment by leo816** [comment]
Reimbursed with #904
