### ISSUE TITLE
Fee reimbursement for trade OVTOO

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/support#838]
![Capture 1](https://user-images.githubusercontent.com/67669956/108665749-f576ed00-74d5-11eb-93e4-83aadf13f722.jpg)
![Capture 1 1](https://user-images.githubusercontent.com/67669956/108665761-fd369180-74d5-11eb-8e18-4354ffafcb91.jpg)

MakerID:  
             OVTOO    - ef9da531a44344107cf07416d4441a5433a6416a69d67efbf48e31ac11facbf4
             

Bisq version: 1.5.5

Other notes:
Invalid maker fee transaction

Btc adress for reimbursement : bc1qhv92yypyy6sjzaa9d345mcydjqkg6h397z6adc

I was the seller

**Comment by leo816** [comment]
please create individual issues for the different requests

**Comment by RififiCastorjunior** [comment]
i don't merit that
