### ISSUE TITLE
Fee reimbursement for trade fussusp

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/support#841]
![Capture 13](https://user-images.githubusercontent.com/67669956/108667568-ce221f00-74d9-11eb-81d4-a826dcd19eab.jpg)
![Capture 10](https://user-images.githubusercontent.com/67669956/108667563-ccf0f200-74d9-11eb-8151-3538596170af.jpg)

Maker: 
           
           - 72649  -  1084947ecee4c9a001e8d82d41574074f3b930cfe4274427aaa9108171a48c20

Bisq version: 1.5.4 (first 2 pictures)
                      1.3.9 (two last pictures)

Other notes:
invalid maker fee transaction

i was the seller 

Btc adress for reimbursement : bc1qhv92yypyy6sjzaa9d345mcydjqkg6h397z6adc

**Comment by leo816** [comment]
please create 2 different issues for different trades

**Comment by RififiCastorjunior** [comment]
i don't merit that.
