### ISSUE TITLE
Support Call 2021.02.24

### ISSUE THREAD

**Issue by huey735** [bisq-network/support#842]
## Call Details

- Date: Wednesday February 24 2021
- Time: 18h00 - 19h30 Central European (CET)
- Place: (details tbd)

## Planned Topics

- Project to improve support and mediation
- Penalties
- Flagging users
- Mediation messages not being received
- Stuck in stage 1 and 2
- Mediator Compensation proposal

More ideas welcome. Please give a thumbs-up if you expect to join.

**Comment by leo816** [comment]
1. Penalties
2. Flagging users
3. Some messages are not being received
4. stuck in stage 1 and 2
5. Mediator Compensation method
