### ISSUE TITLE
Fee reimbursement for trade xoGNB

### ISSUE THREAD

**Issue by speedy5539** [bisq-network/support#843]
SCREENSHOT HERE

![Untitled-1](https://user-images.githubusercontent.com/78820435/108889622-e34b9a80-760c-11eb-8bc6-25629cc8f2ba.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  f39bc0a1b0c081e7637eca254f3dfb0bba9d2ee4f244c512763666771e1c4f26
Taker: a27313b66ffa5ac6df6ffab2f7dbfac39d1081c120952b9755d13d8c37073df1
Deposit:16f94f4c69a2192d8bd13e482e856287eee72a8219bd9db690ef7b5a70d9e855

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.6

**Comment by leo816** [comment]
what is the issue on this trade? why are you asking for a reimbursement?

**Comment by pazza83** [comment]
Closing as no response
