### ISSUE TITLE
Fee reimbursement for trade dfivlh

### ISSUE THREAD

**Issue by askkbisq321** [bisq-network/support#844]

**Comment by askkbisq321** [comment]
Someone has already listed this issue.
Thanks for that Buckshot.

**Comment by askkbisq321** [comment]
Leo, 
I have not yet had this failed trade resolved. I am not sure what to do. Can you help direct me please.

Thanks

**Comment by leo816** [comment]
hi, what is the issue? there are no details here

**Comment by askkbisq321** [comment]
Hello.
I have tried to get this trade resolved. It seems that the deposit BTC remains locked up. 
For some reason the trade continues to wait for deposit confirmations.

The Mempool says that is has not arrived. I am to sure what to do.

My Bisq version is 1.5.1

It will to let me update since this trade failed. Not sure how to move forward.

Thank you for reaching out.

Bg
