### ISSUE TITLE
Fee reimbursement for trade UmsvtEQE

### ISSUE THREAD

**Issue by dL5r8zDRCTv6** [bisq-network/support#845]
![UmsvtEQE_reimburse](https://user-images.githubusercontent.com/79609191/109076186-174cbb80-76f2-11eb-9c59-9c6e5e5df9a7.png)

Maker:  e3342261774816d950f20443cef71ce1fa189a2146eda88feb89b9c7faeb151f
Taker: 698512a799ce03f3f06d329e578f9ee98d3663d8ec6b530eb992de9a538e07f8
Deposit: bada85119e5165d86ed4689f3c5b998f91c1d5e6f6d67fa16f8250a7fab67147

Bisq version: v1.5.6

Other notes:

I am the maker in trade UmsvtEQE requesting reimbursement of the maker fee and release of security deposit as the trade has failed. The Deposit transaction ID cannot be found searching multiple blockchain explorers.

Request is made as per advice given in: https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223

**Comment by leo816** [comment]
please provide your preferred btc address for the reimbursement

**Comment by dL5r8zDRCTv6** [comment]
bc1qhs6kqcntv7nfw05ayfum37ycuqdpe7hwxt7x2n

**Comment by dL5r8zDRCTv6** [comment]
Thank you @leo816

**Comment by leo816** [comment]
Reimbursed with #904
