### ISSUE TITLE
Fee reimbursement for trade TKYSXDA

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/support#848]
![Capture 3](https://user-images.githubusercontent.com/67669956/109244631-4f7df800-77df-11eb-8a6c-02d340da55ca.jpg)
![Capture plousD](https://user-images.githubusercontent.com/67669956/109244655-5a388d00-77df-11eb-8770-57f9b273abde.jpg)

Maker ID: 

              TKYSXDA - 209280b5f0c36402e5c007302d567d3a858039e35874cb394683c72801ab7f11

Bisq version: 1.5.5

Other notes:
Invalid maker fee transaction

Btc adress for reimbursement : bc1qhv92yypyy6sjzaa9d345mcydjqkg6h397z6adc

I was the seller

**Comment by leo816** [comment]
Reimbursed with #862
