### ISSUE TITLE
Fee reimbursement for trade MAJBGE

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/support#849]
![Capture 4 1](https://user-images.githubusercontent.com/67669956/109245023-0bd7be00-77e0-11eb-8a2b-a9cc5c3d47aa.jpg)
![Capture 4 12](https://user-images.githubusercontent.com/67669956/109245048-16925300-77e0-11eb-943f-2a989a358da1.jpg)

Maker ID:
    
               MAJBGE - cb9a317bf529e64953b70ee1ca9d983936ab9500978048dfc431af93ddc50bae

Bisq version: 1.5.4

Other notes:
maker fee transaction error

Btc adress for reimbursement : bc1qhv92yypyy6sjzaa9d345mcydjqkg6h397z6adc

i was the seller

**Comment by leo816** [comment]
Reimbursed with #862
