### ISSUE TITLE
Track dropped arbitration messages

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#85]
@cbeams commented on [Wed Jan 10 2018](https://github.com/bisq-network/bisq-desktop/issues/1173)

Per details in the description of #1172, this issue exists for tracking arbitration cases where messages have been dropped, or we believe they have been dropped.

To make note of an incident, add a comment to this issue as soon as possible, mention the Trade ID, who the arbitrator is, and explain what happened as best as you can. **Do not** include identifying details about the trade or traders involved.

Note: this issue and the instructions are primarily intended for @bisq-network/arbitrators, but individual traders are also welcome to follow these instructions if they believe they're experiencing a dropped message problem during arbitration.

In any case, by keeping close track of how often this problem is happening, we'll be able to know when we've solved it.

This issue is closely related to, but distinct from #1174. Please do not confuse the two.

---

@cbeams commented on [Fri Jan 12 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-357176666)

For the record, my last known incident with dropped arbitration messages happened on **January 6th,** as documented in the forum at https://bisq.community/t/cannot-see-answers-of-closed-dispute-ticket/4262. I followed up with the user in a private chat there and all is well.

---

@keo-bisq commented on [Sat Jan 13 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-357442929)

I have several disputes where one trader is not responding, possibly due to dropped messages:
0423401, QITYNPXN, 4159602. These disputes have been hanging for weeks now with no messages on the forum.

---

@ManfredKarrer commented on [Sun Jan 14 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-357509685)

@keo-bisq Can you post that on the Forum as well? 

---

@cbeams commented on [Fri Jan 26 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-360742385)

Trade `96205518` definitely just had a dropped arbitration message. Namely, the seller sent me a message that I never received. I confirmed this with the seller via email, and saw a screenshot of his client confirming it. We had successfully exchanged chat messages on this ticket before, and now after the dropped message, but the dropped message never made it through.

---

@cbeams commented on [Fri Feb 09 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-364370303)

Trade `vNYbeG` appears to have dropped its 'payment started' message; I got screenshot proof that the buyer clicked the button, but the seller said they were unable to click 'payment received'.

---

@cbeams commented on [Mon Feb 12 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-364962383)

> Trade vNYbeG appears to have dropped its 'payment started' message; [...]

Note: adding the above message on this issue was a mistake on my part. I meant to add it to #1174, and I've done that now at https://github.com/bisq-network/exchange/issues/1174#issuecomment-364962145

---

@cbeams commented on [Mon Feb 26 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-368393063)

Trade ID `ZKdpG` experienced at least one dropped arbitration message on the buyer's side.

---

@cbeams commented on [Sun Mar 11 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-372092576)

It appears that the seller in trade `KEHENQM` never received my initial arbitration chat message, leading to significant delays in the arbitration process.

---

@cbeams commented on [Wed Mar 14 2018](https://github.com/bisq-network/bisq-desktop/issues/1173#issuecomment-372967221)

One of my arbitration messages to the buyer in trade `999999` was dropped, and this was verified by the buyer in a series of screenshots of our chat thread.

This dropped message caused at least one full day of unnecessary delay in the arbitration process.

**Comment by cbeams** [comment]
Trade `99999` exhibited something similar to this behavior, but instead of _dropped_ arbitration chat messages, the buyer in this trade received _duplicates_ of several of my messages.

**Comment by pazza83** [comment]
Closing as stale
