### ISSUE TITLE
Fee reimbursement for trade FiAGNVmI

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/support#850]
![Capture 5](https://user-images.githubusercontent.com/67669956/109245220-5fe2a280-77e0-11eb-9ce8-151b1dbc82a0.jpg)
![Capture 5 1](https://user-images.githubusercontent.com/67669956/109245226-63762980-77e0-11eb-9dee-e38c058f108e.jpg)

Maker ID:

              FiAGNVmI - db4a36465be987aef29d4ef181c1f6a4741f50057baa7c97ddcff7acf3159100

Bisq version: 1.5.4

Other notes:
maker fee transaction error

Btc adress for reimbursement : bc1qhv92yypyy6sjzaa9d345mcydjqkg6h397z6adc

i was the seller

**Comment by leo816** [comment]
Reimbursed with #862
