### ISSUE TITLE
Fee reimbursement for trade SJDUZ

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/support#851]
![Capture 7](https://user-images.githubusercontent.com/67669956/109245411-b6e87780-77e0-11eb-95c2-8a76971db9fc.jpg)
![Capture 11](https://user-images.githubusercontent.com/67669956/109245417-b9e36800-77e0-11eb-8e25-1f8f3857014e.jpg)

Maker: 
             -SJDUZ - e7f1ddf3e2abbe6e0cff21463f106abfb350fc93e008247f49e1d084db57e2f7
             

Bisq version:1.3.8

Other notes:
invalid maker fee transaction

Btc adress for reimbursement : bc1qhv92yypyy6sjzaa9d345mcydjqkg6h397z6a

**Comment by leo816** [comment]
Reimbursed with #862 
(please double check your address next time)
