### ISSUE TITLE
Fee reimbursement for trade eQnCB

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/support#852]
[Capture 8](https://user-images.githubusercontent.com/67669956/108667081-d463cb80-74d8-11eb-84a4-0f53b21058ab.jpg)
![Capture plous](https://user-images.githubusercontent.com/67669956/108682086-2cf29300-74f0-11eb-949b-3cd9cac1ad4e.jpg)

Maker ID:

            -eQnCB - e0ae0747c3a13006b8d1dc44dc5fd72df5301729ea6c808cb0734b5c83b5547a

Bisq version:1.3.8

Other notes:
invalid maker fee transaction

Btc adress for reimbursement : bc1qhv92yypyy6sjzaa9d345mcydjqkg6h397z6adc

**Comment by leo816** [comment]
please provide a screenshot of the trade details

**Comment by RififiCastorjunior** [comment]
![Capture plousH](https://user-images.githubusercontent.com/67669956/109848800-f683e900-7c50-11eb-9c11-5e6f9212db12.jpg)

**Comment by leo816** [comment]
Reimbursed with #862
