### ISSUE TITLE
Fee reimbursement for trade 902413

### ISSUE THREAD

**Issue by eleonorra12** [bisq-network/support#854]
![Snímek obrazovky (3)](https://user-images.githubusercontent.com/79769676/109402135-ac9aba80-7953-11eb-9076-e68b0af49c2d.png)

Maker:   92170b14ae65ae8d7425a6ce7cc0b38ac2f5e493b477225c9e6438bc69a9fba6
Taker:   62d6fd8dc0c0e572617e7e3d8558c176f099815908cc55d373ee868de07ea8dc
Deposit: d39f57aa3c96be058b1ea9b5d23bdee1bd023b68e8c2d1dc84b284108dae5244

By mistake I gave low fee (3 sat).

There was written that there are "no locked funds", but in fact the depossit (0.006 btc) is locked for now. I made SPV resync and it did not change.

So please, I kindly ask for reimbursement of trading fee and unlocking of my depossit.
Thanks, Eleonorra

**Comment by leo816** [comment]
were you the maker or the taker? regarding the locked funds, if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades

**Comment by pazza83** [comment]
Closing as no response
