### ISSUE TITLE
Fee reimbursement for trade ttycopk

### ISSUE THREAD

**Issue by artefactvfx** [bisq-network/support#858]
![Screenshot 2021-03-01 164232](https://user-images.githubusercontent.com/74461960/109563547-eda6e200-7aad-11eb-9289-b96a9196c763.jpg)

Maker:  3bd4d41d4686dd460a42b3c0f7112283e484fd8fb17084762160725e5d23bea4
Taker: N/A
Deposit: N/A

Bisq version:

1.5.6

Other notes:

This trade failed when I tried to fund it using the bisq wallet (I was the maker).  Please provide refund

**Comment by leo816** [comment]
taker fee not published, reimbursement is not justified. Funds never left your wallet

**Comment by artefactvfx** [comment]
Ok thanks, I saw the error msg and I wasn't sure
