### ISSUE TITLE
Fee reimbursement for trade WROXzwq

### ISSUE THREAD

**Issue by time885new** [bisq-network/support#860]
![2021-03-07 09_15_03-](https://user-images.githubusercontent.com/80207523/110242802-942c3080-7f4f-11eb-8258-9c0d407b357a.png)

Maker:  ba63b04affc9906b7d0955527198045d4b8479fee7aa5bba335262d1b69a44d1
Taker: ...........
Deposit: ..........

Bisq version: 1.5.9

Other notes:
Full text of error message in lower part of screenshot:
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 676109, myLockTime=676444

Asking for a fee refund per the message in the client.
![2021-03-07 09_19_10-](https://user-images.githubusercontent.com/80207523/110242933-20d6ee80-7f50-11eb-8f0e-2c3380a52be1.png)

**Comment by jmacxx** [comment]
Thanks for letting us know, I've contacted the maker of these trades asking them to re-sync their Bisq app.

**Comment by leo816** [comment]
taker fee not published, reimbursement is not justified
