### ISSUE TITLE
Fee reimbursement for trade W5YTQ

### ISSUE THREAD

**Issue by time885new** [bisq-network/support#861]
![2021-03-07 10_55_01-](https://user-images.githubusercontent.com/80207523/110245967-85e51100-7f5d-11eb-8e4f-fc5d424c2619.png)

Maker: ab303ab774b3b73199fed7dfaf95ca5e418f03afe1c8e4a9856b97af59167559
Taker: ...........
Deposit: ..........

Bisq version: 1.5.9

Other notes:
Full text of error message in lower part of screenshot:
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 676109, myLockTime=676446

Asking for a fee refund per the message in the client.
![2021-03-07 10_55_41-](https://user-images.githubusercontent.com/80207523/110245984-9b5a3b00-7f5d-11eb-84ca-fa4027c4330d.png)

This is second time this has happened in the same day. I did not realize that the attempted trade was with the same peer as it was with a different payment method. (see #860). Subsequent trades with other parties seem to be unaffected.

**Comment by leo816** [comment]
taker fee not published, reimbursement is not justified
