### ISSUE TITLE
alqonwmv

### ISSUE THREAD

**Issue by Hudhuranfushi** [bisq-network/support#863]
alqonwmv-d5a3bd69-a7ff-4a7a-87a1-33f7faf286d6-159

Description:

the 2 of 2 multisig transaction is missing

started_at_UTC:
07-03-2021  15:52

Payment made and the seller confirmed by message their receipt of payment however as of 14-03-21  05:50 the BTC has not been released
![IMG_5693](https://user-images.githubusercontent.com/49436236/111058758-7b100c00-8488-11eb-9886-b6a8dd08b841.JPG)

Maker
3fd7690b9d499e864d62090217fb75c4c307b28edfa6a6afea84453d195d4915
Taker
bb27299c8cf4e319aad35ceb5bc1eabee62791f0a567657b42a33c3659910796
Deposit
8eac64831d7cdcdfed029abbf8280723713d1c832e4fa332919d56c2b246ef72
Delayed
d5e440f5efc9b3dfd473931e83482cb2d7116fd83227ecac4b752c3bdc2edadf

Bisq version:
v1.5.9

Device or machine:
Windows 10

SCREENSHOTS HERE

Screen shots sent on keybase to leo816 screen shpt from today below
![IMG_E5688](https://user-images.githubusercontent.com/49436236/110970506-b9ef7600-8351-11eb-9fe9-51d7bc6cf434.JPG)

solution:

Other notes:
Ive been speaking with mwithm earlier today because after a SPV resync the trade has gone from failed to open with over 700 confirmations but timed out, I could still pay but want to make sure it is still safe to do so

**Comment by Hudhuranfushi** [comment]
this was just a failed trade on 7 Mar 2021 15:52:23 with a loss of 0.0000675 in fees no funds have been locked however the UI bug has raised its head again as its showing 0.006 BTC locked.

**Comment by Hudhuranfushi** [comment]
Its the latest version of BISQ on Windows

**Comment by MwithM** [comment]
Yes, I think that the best is to keep on with the trade as the deposit tx is set. The reason why you did not pay (deposit tx not confirmed on your end) should justify the delay and you can pay safely.

**Comment by Hudhuranfushi** [comment]
Thank you MwithM the payment has been made just awaiting receipt from the seller
