### ISSUE TITLE
Trades NUCUX and W5YTQ

### ISSUE THREAD

**Issue by ehwhocares** [bisq-network/support#864]
Description:

>_Provide a brief description of the bug_

With this one trader I tried twice and got the following error both times. Other trades during the time did not have this problem.
"An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 676109, myLockTime=676460"
and
An error occurred at task: TakerProcessesInputsForDepositTxResponse
Exception message: Lock time of maker is more than 3 blocks different to the lockTime I calculated. Makers lockTime= 676109, myLockTime=676459

This occurred for trade NUCUX-8bfb9aa0-cf36-47f5-ac1c-5fc526d66c31-159 and W5YTQ-659997c4-e2c3-4c8a-b54a-ae50180e9933-159

github-issue:
Not sure what to put here? Isn't this the ticket?

Bisq version:
Device or machine:
Windows Bisq Version v.1.5.9

I tried restarting, reinstalling Bisq, and resyncing my SPV file, none of which worked.

SCREENSHOTS HERE

![bisq trade issues](https://user-images.githubusercontent.com/80221801/110253475-246a7580-7f50-11eb-9d0c-8df39c0b1da5.png)

solution:

Other notes:

**Comment by ehwhocares** [comment]
Also, oddly, this is the only time this has happened to me (and its with the same trader for each) and i get the following when I try to message them.
![bisq-trade-issues-2](https://user-images.githubusercontent.com/80221801/110253676-3a2c6a80-7f51-11eb-958a-ecb28cd52bfe.png)

**Comment by jmacxx** [comment]
Thanks for the report.  Sent a message to the maker asking them to [SPV Resync](https://bisq.wiki/Resyncing_SPV_file)

**Comment by ehwhocares** [comment]
Hi,

Thanks for the response. Unfortunately, I posted a screenshot showing I
can't even send messages to them.

**Comment by jmacxx** [comment]
:+1:  Was just letting you know that I messaged them.  (You can't trader-chat because the trade contract was not set)

**Comment by ehwhocares** [comment]
Ohh im sorry I read it incorrectly as "send" not "sent". Thanks a lot!

**Comment by ehwhocares** [comment]
Should I move the trades to failed? Or Just leave in open? I can move them
back and forth but does it matter?

**Comment by huey735** [comment]
This trade failed. The Taker fee and Deposit transaction weren't properly broadcast. So yes, feel free to move them to failed.

**Comment by ehwhocares** [comment]
OK, cool, thanks!
