### ISSUE TITLE
Fee reimbursement for trade W5YTQ

### ISSUE THREAD

**Issue by toddrunner** [bisq-network/support#867]
![t1](https://user-images.githubusercontent.com/80294969/110401677-03854b80-8048-11eb-955a-1cd78e669fe8.png)

Maker:  ab303ab774b3b73199fed7dfaf95ca5e418f03afe1c8e4a9856b97af59167559

BTC address for reimbursement: bc1qtes60e0kk8tf7gtlltwaqxgfga6mr6hj3hqgzq

Bisq version: 1.5.9

**Comment by leo816** [comment]
were you the maker or the taker? please provide a full screenshot of the trade details

**Comment by toddrunner** [comment]
I am the taker
![sss](https://user-images.githubusercontent.com/80294969/116154417-a48e9b00-a6b6-11eb-8653-1e337574568d.png)

**Comment by leo816** [comment]
taker fee is missing, reimbursement is not justified
