### ISSUE TITLE
Fee reimbursement for trade 27362

### ISSUE THREAD

**Issue by toddrunner** [bisq-network/support#868]
Maker:  15f455034d771d472932ea0fe3ffa97be8be93711bb367eaaa1218b5f14c7d63
Taker: 424e2bb8d339ef2ae555b792a80fe552ff407d338cf05fa3e76ffde78074fe5a
Deposit: 4fab3dbc226793bd0ec5e2f41c5e77d22f2661d989abda0c7088b8a411ca12d8

BTC address for reimbursement: bc1qtes60e0kk8tf7gtlltwaqxgfga6mr6hj3hqgzq

Bisq version: 1.5.9

**Comment by leo816** [comment]
were you the maker or the taker? please provide a full screenshot of the trade details

**Comment by toddrunner** [comment]
I am the taker
![sss](https://user-images.githubusercontent.com/80294969/116154874-41e9cf00-a6b7-11eb-9440-af7aa71df8be.png)

**Comment by leo816** [comment]
taker fee not published, reimbursement not justified
