### ISSUE TITLE
Fee reimbursement for trade xxqqjw

### ISSUE THREAD

**Issue by toddrunner** [bisq-network/support#869]
Maker: 94c03db1d6ca71091463dda22ba2b06df9b816f607165ce40b2c5a39d39449f0
Taker: 951ec7197d48e533b3d7c90895fa59fb3f23cdb40f9296af702eb63da2597c84
Deposit: 5a1d6345ce41d23d5b6260ff3c6dfc412e68d45ac452cc9e2ec05388d2fc9279

BTC address for reimbursement: bc1qtes60e0kk8tf7gtlltwaqxgfga6mr6hj3hqgzq

Bisq version:  1.5.9

**Comment by leo816** [comment]
were you the maker or the taker? please provide a full screenshot of all the trade details

**Comment by toddrunner** [comment]
I am the taker
![sss](https://user-images.githubusercontent.com/80294969/116155069-9bea9480-a6b7-11eb-9209-c87b1b141f75.png)

**Comment by leo816** [comment]
taker fee not published, reimbursement not justified
