### ISSUE TITLE
Fee reimbursement for trade NUCUX

### ISSUE THREAD

**Issue by toddrunner** [bisq-network/support#871]
![t4](https://user-images.githubusercontent.com/80294969/110402794-03864b00-804a-11eb-82c6-00f545d2eea1.png)

Maker:  131d1a84cb77db71d370f2958cf4da0b8ddb19d3bcf4332cac5c1256888dde29

BTC address for reimbursement: bc1qtes60e0kk8tf7gtlltwaqxgfga6mr6hj3hqgzq

Bisq version:  1.5.9

**Comment by leo816** [comment]
were you the maker or the taker? please provide a full screenshot of the trade details

**Comment by toddrunner** [comment]
I am the taker
![sss](https://user-images.githubusercontent.com/80294969/116155252-df450300-a6b7-11eb-8079-d4417e8c4b27.png)
