### ISSUE TITLE
Fee reimbursement for trade 502282

### ISSUE THREAD

**Issue by johnsmith-sudo** [bisq-network/support#874]
![2021-03-10-235946_1920x1080_scrot](https://user-images.githubusercontent.com/68829077/110754968-44729100-81fd-11eb-9c15-cd94a8fd2dd9.png)
Maker: c9dd5d92bc33d65fe09be240075f173236299100531ce89945092453c14c4304
Taker: 
Deposit: 0.00673260 BTC

Bisq version: 1.5.9

**Comment by johnsmith-sudo** [comment]
If any reimbursement of fees is due please do so. I marked this accepted offer as failed, but I still have the offer published, so I still have my funds for this offer I think?

**Comment by leo816** [comment]
were you the maker or the taker? please provide a screenshot of all the trade details

**Comment by pazza83** [comment]
Closing as no response
