### ISSUE TITLE
Fee reimbursement for trade NVDFODI

### ISSUE THREAD

**Issue by fupm** [bisq-network/support#877]
![ID_NVDFODI](https://user-images.githubusercontent.com/76731476/111026781-8ca3d600-83ec-11eb-9272-2c83503070b4.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 425f8cfb0806505782895bb3995244d6b6c850db7074e798199fe908498a9bd6
Taker: deef841e6d2d40ada05af78ef1fd2239727fe631d6203203f6d82e3279d0094f
Deposit: 12ca873240e928b79903008f3f92d9d0033341029d126dfc95b3def18eb14d62

Bisq version: 1.5.2
BTC address for reimbursement: bc1qjyq52pnh06yg0n5gzn82s0876d3pptldk8gqgt

Other notes:

**Comment by leo816** [comment]
Reimbursed with #904
