### ISSUE TITLE
Fee reimbursement for trade JR6JIQQP

### ISSUE THREAD

**Issue by sandu-c** [bisq-network/support#880]
![image](https://user-images.githubusercontent.com/4200291/111070529-72442800-84d2-11eb-952c-aad9a210581e.png)

Maker:  f014e4a3041f97a7f346b65d041526550f63a82f5fe2b016fc4210c085f20149
Taker: N/A
Deposit: N/A

Bisq version: 1.5.1
BTC address for reimbursement: bc1qlay3gvh30tppt4upfdewamcwqdmevnrd78f2pm

Other notes:
Trade remained in an inconsistent state after upgrading form 1.5.0 to 1.5.1

**Comment by sandu-c** [comment]
no updates ?

**Comment by leo816** [comment]
taker fee not published, funds never left your wallet, reimbursement is not justified
