### ISSUE TITLE
Fee reimbursement for trade kvpukl

### ISSUE THREAD

**Issue by toddrunner** [bisq-network/support#881]
Maker:  41a1059dee612c8d0b3ebc323907fae6bd7587c1802bafe3a9681bd48d6a1ccc
Taker: fb2050bd2f93061eae2fce6bdf2f3f7986707bfde4e1ca7f3aa2c318946fbbdf
Deposit: bc99630f9bb4880a153cb1ec3f430f82b6f2e86e1ab4167d0390d99170e9fe46

BTC address for reimbursement:  bc1qvm6ca6dc8xwcjcshnrxasr6dtust2g5ae29g7n

Bisq v1.5.9

**Comment by leo816** [comment]
were you the maker or the taker? please provide a full screenshot of the trade details

**Comment by toddrunner** [comment]
I am the taker
![sss](https://user-images.githubusercontent.com/80294969/116155988-e587af00-a6b8-11eb-8ce8-bde069c9d5a8.png)

**Comment by leo816** [comment]
Reimbursed with #945
