### ISSUE TITLE
Fee reimbursement for trade mowzy5s0

### ISSUE THREAD

**Issue by Wrecktangl3** [bisq-network/support#882]
![image](https://user-images.githubusercontent.com/77015544/111146363-3b791b00-8581-11eb-9878-36d8f99b0737.png)

Maker:  1405a101701fffc264113480adef1ba9459b919122740626dfa542b6b489d7bb
Taker: 14d826373e32a5f6c088962967640f323cfe779dda641b6720b1f957d62f5586
Deposit: e48dfef2554d4bb52faf882536735c40f35050c419d229c682909294946cecad

Bisq version: 1.5.9

Deposit Fee locked and seeking re-imbursement for 0.011240 BTC

**Comment by leo816** [comment]
please provide a preferred btc address for reimbursement

**Comment by Wrecktangl3** [comment]
> please provide a preferred btc address for reimbursement

Hi There, please check keybase for btc address

**Comment by leo816** [comment]
Reimbursed with #904
