### ISSUE TITLE
Fee reimbursement for trade LZAWWJT

### ISSUE THREAD

**Issue by sam-0710** [bisq-network/support#883]
<img width="896" alt="Screen Shot 2021-03-15 at 6 06 01 PM" src="https://user-images.githubusercontent.com/80728542/111241262-01783b00-85ba-11eb-831e-4fbf70d6fd76.png">

Maker:  52e315a45217c546f99a2d5715ab580d1b798d622685a069b39a87ea8f2b7629
Taker: N/A
Deposit: N/A

Bisq version: v1.5.9
BTC address for reimbursement: bc1q0upqkdklne95hn24ar8ygc4lghkvalq0lyvavm
Other notes:

An error occurred at task: MakerProcessesInputsForDepositTxRequest
Taker's trade price is too far away from our calculated price based on the market price.
takersPrice=571176138
makersPrice=563691590

**Comment by sam-0710** [comment]
@leo816 can someone please take a look? much appreciated!

**Comment by leo816** [comment]
you can direct message me your btc address through keybase

**Comment by leo816** [comment]
please provide your btc address for reimbursement

**Comment by sam-0710** [comment]
@leo816 sorry just got back to this! I just went ahead and updated the issue with the address. No need for keybase. Thanks again

**Comment by pazza83** [comment]
Hi @leo816 btc address has been provided. Please can you add this to your to do list.

**Comment by leo816** [comment]
Reimbursed with #1006
