### ISSUE TITLE
Fee reimbursement for trade INASX

### ISSUE THREAD

**Issue by g3rv4** [bisq-network/support#886]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/6250774/111344209-f0333b00-865a-11eb-8aef-1546c10c9475.png">

Maker:  6a28a1392fe3fd4a92aa32e50d57d65597a91556ba485b9728c43b1e183e54f4
Taker: 56afe39c5cb5f555bb34712c2ed5836f80a3b21801f23c332c77a1415f878e75
Deposit: 89182334312195231ed39e85921f98207559b6ccb9917c511b2a18628dec01ba
Delayed payout transaction ID: 80cea76130a9ac935f0ad5930af3a76b40889e1c84ad2c948efb596b7c901c73

Bisq version: 1.5.9
BTC address for reimbursement: 13sXiTtLeHwr9E8k34a2m1udGNqm85Le17

Other notes: **I have the funds Locked** and need help unlocking them. I opened a dispute but the other party couldn't accept it. Now I can't even open a dispute because I get this error:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/6250774/111345291-e3631700-865b-11eb-84c1-83adcdb48798.png">

**Comment by leo816** [comment]
Reimbursed with #904
