### ISSUE TITLE
Fee reimbursement for trade nwjecu

### ISSUE THREAD

**Issue by d4amenace** [bisq-network/support#887]
![Screenshot from 2021-03-22 14-10-12](https://user-images.githubusercontent.com/29969146/112046434-05f0a680-8b1a-11eb-8c9b-ffe6ed920ec1.png)

Maker: ac5b112fd7664620d03e85f0e19d30ebb7ebcd210eeb40f26268e14b070fbd8f
Taker: N/A
Deposit: N/A

Bisq version: 1.5.9
BTC address for reimbursement: 13o5VjzvjSfzEeahZysQidQRyZJKMSs6j9

Other notes:

I was at the point of blockchain confirmation and i received a message that said:

     _An error occurred at task: MakerCreateAndSignContract
     Exception: java.lang.NullPointerException__

It also informed me that my maker fee might have been taken by error and I needed to submit a request here to have the issue resolved. I realize that this offer is still open and the only way the maker fee will be taken is if I remove the offer.  Is there any way to get the offer canceled?

**Comment by leo816** [comment]
Reimbursed with #904
