### ISSUE TITLE
Fee reimbursement for trade OVTAXHRD

### ISSUE THREAD

**Issue by fbcosta-oceano** [bisq-network/support#889]
![Sem título](https://user-images.githubusercontent.com/81367373/112476215-6ec16400-8d50-11eb-8cd9-094dd178b94e.png)

SCREENSHOT HERE

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: 7d1e5bf7542efe69bf40aacbf038f8ebf295db40013cfb2b4db569f519cae85a
Taker: N/D
Deposit: N/D

Bisq version: 1.5.9
BTC address for reimbursement: 17kgc48g54kvsKYq91Z6haNp94Y7tVAQBx

Other notes:

It says I might have lost my trade fees

**Comment by leo816** [comment]
Taker fee not published, reimbursement not justified.
