### ISSUE TITLE
Fee reimbursement for trade 55756910

### ISSUE THREAD

**Issue by crt83** [bisq-network/support#894]
![bisq](https://user-images.githubusercontent.com/81455906/112709935-50c14400-8eb5-11eb-8354-9580a07749e2.PNG)

Maker:  71624073a13ac2d3e774634436c1ee15d7bbbf9341810869031d56a0e6fc3a88
Taker: 76183ed2130a4358a04f2ddfd121bdae9698f0b833fa820cf61bd06a70adb23b
Deposit: N/A

Bisq version: 1.5.9
BTC address for reimbursement: 1G69B8R5RMEKk1RfuybnRvaMYkpdZPuour

Other notes: I am the BTC taker

**Comment by leo816** [comment]
Reimbursed with #904
