### ISSUE TITLE
Fee reimbursement for trade UT9Z1BJ

### ISSUE THREAD

**Issue by Askuwheteau** [bisq-network/support#895]
<img width="860" alt="Screenshot 2021-03-27 at 16 53 39" src="https://user-images.githubusercontent.com/41007491/112726361-4aff4900-8f1d-11eb-86a7-ca3a6d48bc89.png">

Maker:  6a7182e019f719e923e9e2aff87a3c5a8bd22a78e774e44c0efba0b86ca426fa
Taker: 6cccde8ef369d0b4d47aa0c0d955162d0e976d2d8a21955098868150ca9dc3b1
Deposit: 36fbc216e6884e6cf7fac53ae186add4a4785760b6e6bb9631b35444ade58fe3

Bisq version: 1.5.9

<img width="789" alt="Screenshot 2021-03-27 at 17 00 07" src="https://user-images.githubusercontent.com/41007491/112726462-edb7c780-8f1d-11eb-824d-17b7509b43a8.png">

I am asking for a fee reimbursement.
I have moved the trade to the failed trades.

thanks,

**Comment by leo816** [comment]
were you the maker or the taker? please provide a full screenshot of all the trade details not included here. (excluding personal data of course)

**Comment by leo816** [comment]
Please provide a preferred btc address for reimbursement

**Comment by Askuwheteau** [comment]
<img width="898" alt="Screenshot 2021-04-07 at 14 21 07" src="https://user-images.githubusercontent.com/41007491/113865727-ba422c00-97ac-11eb-8068-e73dbe635bf8.png">

**Comment by Askuwheteau** [comment]
preferred BTC receive address is : bc1qhkrsngvpkml620c2p0mjctyla9u9qvjnh5umnj

Thanks!

**Comment by leo816** [comment]
Reimbursed with #904
