### ISSUE TITLE
Fee reimbursement for trade DCHK5g-d700b3b2-ca91-4204-abee-5640077acfcd-137

### ISSUE THREAD

**Issue by billypendennis** [bisq-network/support#899]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._
DCHK5g

SCREENSHOT HERE
![screenshot](https://user-images.githubusercontent.com/78545634/113215228-73b37580-9272-11eb-9584-a12bac46c797.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker: e574fe2d991cfaf76a8d5c4dfa6dad2a9522e9f5803aeec0b4bdd394e9ef0e00
Taker: cef69d9b32cb7263603e67ca024f6834efbbfcb1bcd704ec50c453fdbffc7023
Deposit: ecc1da067b30b467eb0240c8a021045a3bfc57ed7ec2f9a3b47c5a9160e09708

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.9
BTC address for reimbursement: 1NV7jWScbHoMFsQkagwthSmtt97NfADCXi

>_Provide the Bisq client version to help developers identify the causing issue._
1.3.7
Other notes:

Ticket closed on Sep 9, 2020 11:06:47 PM

Selected mediator: leo816 (sjlho4zwp3gecspf.onion:9999)

Summary:
Payout amount for BTC buyer: 0.0030 BTC
Payout amount for BTC seller: 0.0190 BTC

Summary notes:
btc buyer never made the payment or answered

Next steps:
Open trade and accept or reject suggestion from mediator

I opened the trade and accepted the mediator's suggestion as above. The buyer did not respond to the mediator.

**Comment by billypendennis** [comment]
Please help to solve this issue.

Thanks.

**Comment by leo816** [comment]
This trade will be solved through arbitration. I see the payout to the donation address was already made. Please reach out to our support team on keybase if you have any further questions.
