### ISSUE TITLE
Fee reimbursement for trade nRtjjZWA

### ISSUE THREAD

**Issue by nadjanahaus** [bisq-network/support#901]
>_The nRtjjZWA part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/82121390/113932984-55aabf80-97f4-11eb-83ec-6a45a68d8129.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  uf7iumk5vslqpr7uzdri3uufr23t55n7bw7e2ubmke5p5fvwi5f6o7yd.onion:9999
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.6.2
BTC address for reimbursement: bc1qvlkwzeyn3ak3whlr5az9kvlmvmxjdfktcdwvxw

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

Maker fee transaction ID: a71a7258ae170c3e8fc68346171d237e4eb52582f8998b301845d5a1fcddb5a4
> Error log:
[bisq 20210704.txt](https://github.com/bisq-network/support/files/6274464/bisq.20210704.txt)

**Comment by leo816** [comment]
taker fee not published, reimbursement not justified.
