### ISSUE TITLE
Fee reimbursement for trade Q0kNS

### ISSUE THREAD

**Issue by nadjanahaus** [bisq-network/support#902]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/82121390/113934244-cbfbf180-97f5-11eb-9350-3293291c59b9.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  N/A
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.6.2
BTC address for reimbursement: bc1qvlkwzeyn3ak3whlr5az9kvlmvmxjdfktcdwvxw

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>Trading peers onion address. px365vxmbqit7nayslbxlhoajv2z6dsoqdhjm73wlfg75d2horfcz4yd.onion:9999
> Maker fee transaction ID: f78ef7f409083296c59f154e465f2342fadc097d3524830fe194235ab13f6055

**Comment by leo816** [comment]
taker fee not published, reimbursement not justified.
