### ISSUE TITLE
Fee reimbursement for trade 3u21WSk

### ISSUE THREAD

**Issue by nadjanahaus** [bisq-network/support#903]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/82121390/113935800-3feac980-97f7-11eb-928c-4bfbf946044f.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  N/A
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.6.2
BTC address for reimbursement: bc1qm3h5753k9s9kryhjglpgmvsk3tq2vpzu0lugex

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

Trade ID: 3u21WSk-9db5870d-056d-4e66-bc63-5fbc179dcbac-159
Trading peers onion address: bfsleo4jmle6noou7466d52tj2qea6cxgqa5t5zdekxceelgfvw2fmad.onion:9999
Maker fee transaction ID: 6f1bfa1369356bf889f9e727fee7e7f2a8421533b141c123d7c265342e82265a

Further screenshots & error log file:

[bisq 20210704 2.txt](https://github.com/bisq-network/support/files/6274607/bisq.20210704.2.txt)

**Comment by leo816** [comment]
taker fee not published, reimbursement not justified.
