### ISSUE TITLE
Fee reimbursement for trade IDKC8I35

### ISSUE THREAD

**Issue by nicholaspufal** [bisq-network/support#905]
![Screen Shot 2021-04-06 at 3 52 00 PM](https://user-images.githubusercontent.com/680151/114254539-db4d7d00-9964-11eb-9ea9-473caba67aea.png)

Maker:  d15b6713e4fad8be9b08f25aa477a98bb52a24d0bc97f844cade85303e9bab2c
Taker: aeb16aadcfdb81ef2ed643421085ff5c96c2cfb4b58d936a35443d792dedb7af

Bisq version: v1.6.2
BTC address for reimbursement: bc1qxedfszqs5f72g3vgs8x337s53j02latkfjleuv

Other notes:
"Timeout reached. Protocol did not complete in 60 sec." after that I haven't seen some BTCs come back to my wallet. 
0.00053222 BTC to be exact.

I was the taker.

**Comment by leo816** [comment]
Reimbursed with #945
