### ISSUE TITLE
Trade NGNTD-f3f04653-b8ea-4680-bc3f-81444b7c474b-159

### ISSUE THREAD

**Issue by wudkwo8rhf** [bisq-network/support#906]
Hello. I have an open trade with ID - NGNTD-f3f04653-b8ea-4680-bc3f-81444b7c474b-159

Exchange 2 BTC for XMR. Time has passed for the transaction, but the seller still hasn't sent the Monero. Unfortunately, yesterday my SSD broke down and I tried to restore the wallet from the back up zip archive (Bisq folder), but it turned out to be corrupted. I also had my seed phrase and wallet date. I recovered by the phrase, but naturally I have no open trades and I cannot engage a mediator and I cannot contact the seller because don't have a trade chat.

My 2 BTC + deposit + seller's deposit - http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/address/bc1qssglxwj48yg9ngvpp60336ph5yk6yhhe6fdq3674cfuvh5ndvr2skp5anu

What should I do in this situation? 

thanks for the help

**Comment by wallclockbuilder** [comment]
Get instant chat help at the Bisq [Support Chanel](https://keybase.io/team/bisq#support).
