### ISSUE TITLE
Trade reimbursement for NLSXVv

### ISSUE THREAD

**Issue by Akira45-0** [bisq-network/support#908]
![grafik](https://user-images.githubusercontent.com/63785272/114686800-689d2280-9d13-11eb-8501-db34075371b9.png)

Reimbursement for trade NVLSXv-13f424d1-6d7b-45b6-97ff-f004f166ee68-160

I am BTC buyer as maker for XMR.
Trade amount and asset: 1.00 BTC for 232.50839355 XMR
Deposit amount: 0.30 BTC

Maker:  49a282c73ea0674e965ec93f286296d3bb52480a46f93b28db9278850df5f69f
Taker: afd04e0234deccabcc5046c70f664412267bb74b27d16ddaeaa4d4b6aac21a81
Deposit: 949a478081e6600d9935ce90d8ae72529059ed2e8c953390806938861a8c4de1
Delayed payout: 6afdd02a7d788d6cf1420e63b541153f189356bcc6bf57fa59fec3fb970a11f9
BuyerMultiSigPubKeyHex: ..........
SellerMultiSigPubKeyHex: ..........

Reimbursement amount: 1.085 BTC / 0.00003956 BTC/BSQ = 27426.69 BSQ
Reason for reimbursement: BTC seller did not confirm payment reception and disappeared

BTC address ownership proof:

Bisq version: 1.6.2

Other notes:
Reimbursement proposal tx id 588504f28cf23aae3daa9f2a934ddf76906469f6019ccef1815d006023986b8c

Mediator summary:
--------------------------------------------------------------------------------------------------------------
Ticket closed on Apr 6, 2021 10:05:30 AM
Mediator node address: sjlho4zwp3gecspf.onion:9999

Summary:
Trade ID: NVLSXv
Currency: XMR
Trade amount: 1.00 BTC
Payout amount for BTC buyer: 1.55 BTC
Payout amount for BTC seller: 0.05 BTC

Reason for dispute: Other

Summary notes:
btc seller never confirmed or released. payment made correctly

-----BEGIN SIGNATURE-----
302c021476e8d4cc62865998ce7fa8b1b779ee3266f85fb4021400f7885209ca8fc0f206a7f5022eff7ab5c39d0b
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator

Arbitration summary:
--------------------------------------------------------------------------------------------------------------
Ticket closed on Apr 14, 2021 11:10:03 AM
Arbitrator node address: 3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999

Summary:
Trade ID: NVLSXv
Currency: XMR
Trade amount: 1.00 BTC
Payout amount for BTC buyer: 0.50 BTC
Payout amount for BTC seller: 0.00 BTC

Reason for dispute: Trader not responding

Summary notes:
BTC buyer did the XMR payment. Seller did not release the funds, and did not respond to mediation or arbitration.
BTC refund is 0.5BTC and the remaining funds, a BSQ equivalent to 1.085BTC, should be reimbursed by the DAO.
Overall payout is:  buyer 1.585BTC, seller 0BTC. DAO will burn 5% of seller’s security deposit.

-----BEGIN SIGNATURE-----
302c02142233876b385aa4f5abd44aafcc097f9cb6d7d3b102143ce4120769acb205a1cc230ff7a4645ec698a70d
-----END SIGNATURE-----

Next steps:
No further action is required from you. If the arbitrator decided in your favor, you'll see a "Refund from arbitration" transaction in Funds/Transactions

Arbitration secret: e7e3c5eb4bd47c04344916ed2a46a76d
@refund-agent2 @leo816

**Comment by refund-agent2** [comment]
0.5BTC were paid out on 6abdeb0938d20b760842c3bc6080e5c4925b75f02bdf385f9c1af562743b9ed4, and the arbitration secret is correct. 

This is a question to DAO contributors: Should we wait a few more days before getting the BSQ price and submit this request to DAO? There's still almost a month to next cycle's proposal phase, and therefore, a high BSQ volatility risk for trader and DAO.

**Comment by Akira45-0** [comment]
OK, I edited the reimbursement amount and I intend to fill it in 2 weeks.

**Comment by Akira45-0** [comment]
Reimbursement amount updated.

**Comment by Akira45-0** [comment]
Sold 20000 BSQ for 0.7912 BTC at 0.00003956 BTC/BSQ to @burningman3
