### ISSUE TITLE
lost my bitcoin

### ISSUE THREAD

**Issue by margeem** [bisq-network/support#91]
I upgraded my bisq app and in doing so, lost my bitcoin.  I have had several suggestions as to how to get it back, but none of them have worked.  I have my original seed words, but when I enter them with the date, the 'restore wallet' button is greyed out.  Please help.

**Comment by cbeams** [comment]
Hi @margeem. Can you explain what you've tried so far? Have you reset your SPV file in `Settings->Network->Resync SPV file`?

**Comment by margeem** [comment]
This came to me as a blank email. Could you please resend the text?
Thank you very much.Margaret

	-----------------------------------------From: "Chris Beams" 
To: "bisq-network/support"
Cc: "margeem", "Mention"
Sent: 24-Mar-2018 19:37:41 +0000
Subject: Re: [bisq-network/support] lost my bitcoin (#91)

**Comment by cbeams** [comment]
The content of that email would have / should have been what you see above in https://github.com/bisq-network/support/issues/91#issuecomment-375919183.

**Comment by pazza83** [comment]
Closing as stale
