### ISSUE TITLE
Failed transaction

### ISSUE THREAD

**Issue by walfait** [bisq-network/support#913]
>_The XXXXX part are a random string generated with the command `date | shasum | cut -b-6`._

Description:
Hello\
I am starting this ticket since I have experienced a failed transaction and I used a reimbursement template which remained unnoticed. Please help.

started_at_UTC:
<_yyyy-mm-dd hh:mm_

github-issue:
>_Please provide a reference issue number to which this case is related. If there isn't one go ahead and create that issue first._
d5hxylx-e72f3dd6-ac4c-4c13-8a90-000a3c0c827c-162

Bisq version:
>_Provide the Bisq client version to help developers identify the causing issue._

Hello
Device or machine: mac
>_Provide the Operating System and Version_

SCREENSHOTS HERE
![image](https://user-images.githubusercontent.com/82743506/115165369-754aaf00-a062-11eb-9540-0d8ddddd2288.png)

>_Always when possible share screenshots of the error messages. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

solution:

Other notes:

**Comment by MwithM** [comment]
From the screenshot, you're the taker and there is no taker fee, so there is nothing to reimburse.
Just use this [guide](https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1) if your funds are still displayed as locked.

**Comment by walfait** [comment]
Hello, thanks for the reply. The reference issue number is 912. There you can see a reimbursement template used to show a failed transaction.
