### ISSUE TITLE
Fee reimbursement for trade LZYHUDKR

### ISSUE THREAD

**Issue by rogueserious** [bisq-network/support#914]
![LZYHUD](https://user-images.githubusercontent.com/74083368/115266210-de770480-a0ec-11eb-944c-391980df325f.png)

Maker:  c773e13196817a50fed20d553926b4d067d30f8c1771e0b47a2d61f43fe31c73
Taker: 55ec6b8dcdeae9bdc8ecb1ab198672d5bdb001091c4992c2ef5cda6e25ce5954
Deposit: dc1e98b953e6119e79ca54f8ad12fef09ca30348a4557fb7957d2863b8027333

Bisq version: 1.6.2
BTC address for reimbursement: bc1qn2756z7cjrvakr44r355r5zwhp2z63kua8q63s

**Comment by leo816** [comment]
taker fee not published, funds never left your wallet. Reimbursement is not justified
