### ISSUE TITLE
Fee reimbursement for trade 93023

### ISSUE THREAD

**Issue by luz808** [bisq-network/support#915]
<img width="897" alt="Screenshot 2021-04-21 at 11 28 47" src="https://user-images.githubusercontent.com/82939735/115531209-cf32bb00-a294-11eb-953c-e4e93a85d8a9.png">

Maker:  2f01aea547980c24312641972da7f1be0e97633600abdff7083108ccd7b7e825

Bisq version: 1.5.5
BTC address for reimbursement: 

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

This request is made by the taker (who has NOT lost the fee). Please reimburse fee to maker.

**Comment by leo816** [comment]
taker fee not published, reimbursement not justified
