### ISSUE TITLE
Fee reimbursement for trade IOUUAJ

### ISSUE THREAD

**Issue by EvonBer** [bisq-network/support#919]
![BISq Issue3](https://user-images.githubusercontent.com/83350935/116410679-8777da80-a824-11eb-8b22-53e4ba251606.jpg)

Maker: 5a897b505b4e3b4226e19a0af67f715b44fc79e473483d6170741ff8bb65930d
Taker: ed3b59b7c5e06edb01f657d83ac340abf73734d99f7741fe9e4d82d5a57b745b
Deposit: d0fb5d15df54527b156f67dea52af515c9269196f20c9c99d3f76051094170fb

Bisq version: v1.62
BTC address for reimbursement: bc1q79h9p805hqlg2klsyc7htvf7acz293kg4al737

**Comment by leo816** [comment]
Reimbursed with #926
