### ISSUE TITLE
Fee reimbursement for trade snm6OHg

### ISSUE THREAD

**Issue by Sn0wPierc3r** [bisq-network/support#920]
![Bisq snm60Hg](https://user-images.githubusercontent.com/83362892/116451953-269fd080-a82b-11eb-810f-12c2d7d51992.jpg)

Maker: d1d5489d3fd8fd4b3d0e1f21f0c2660b54e957bcfcb8cbbbbefeca176c08dda2 
Taker: 036c88606e8a4fff2dac0bc58d1578012ff1fd53af62e2982d1bade5a0081940
Deposit: N/A

Bisq version: v1.6.2
BTC address for reimbursement: bc1qgxwdarrq8y3mf90ssah7dry6npjrym5vl9tjmm

**Comment by leo816** [comment]
Reimbursed with #945
