### ISSUE TITLE
refund trade fee for trade id 2dhxz

### ISSUE THREAD

**Issue by henkdevrieskist** [bisq-network/support#923]
id like a refund for the fees for my failed trade with id 2dhxz and the locked funds unlocked please.

**Comment by henkdevrieskist** [comment]
![Capture](https://user-images.githubusercontent.com/50537421/116731075-8a6ff800-a9e9-11eb-9643-2bee3185899d.PNG)

I was Taker in this transaction. taker fee: `f815cbadf0af5b0b9884b26467ab64f90aaed83711249d4f011595fc7b60693e`

**Comment by henkdevrieskist** [comment]
Trade Id: 2dhxz-b09ffc8b-d4b0-49e2-8313-59bc01870b27-162

Maker: f815cbadf0af5b0b9884b26467ab64f90aaed83711249d4f011595fc7b60693e
Taker: 2f897ef8f95bbd35b35a785106f052e15e0e51b0a53658c29c50a2e510954b95
Deposit: N/A

I was a taker. My funds are still locked after the trade failed to produce a deposit transaction. i also paid fees .


Bisq version: v1.6.2
BTC address for reimbursement: bc1qmmxxrw9nhzjsd77vvmywlrfylf83vnanmjz8l3

**Comment by leo816** [comment]
Taker fee: 2f897ef8f95bbd35b35a785106f052e15e0e51b0a53658c29c50a2e510954b95 
was not published, therefore the funds never left your wallet. Reimbursement is not justified.

> I was Taker in this transaction. taker fee: f815cbadf0af5b0b9884b26467ab64f90aaed83711249d4f011595fc7b60693e

that is the maker fee

**Comment by henkdevrieskist** [comment]
Thanks for the reply and sorry for the confusion. 
Bisq says that my deposit funds are still locked. How can i fix this? I already tried SPV Resync.

**Comment by leo816** [comment]
if a user has still locked funds shown in the UI but no failed trade in the pending trades view, a closed or failed trade causes the problem. to solve that easiest is to delete the ClosedTrades and FailedTrades files in the db folder. the user has to shut down bisq first, do a backup and then delete those 2 files. after that the locked funds should be 0 if not other open trades
