### ISSUE TITLE
Case XXXXX

### ISSUE THREAD

**Issue by GrinchOfChristmas** [bisq-network/support#924]
![image](https://user-images.githubusercontent.com/76711431/116814647-42bcae00-ab5a-11eb-83cc-d95ee4df2f7c.png)

>_The XXXXX part are a random string generated with the command `date | shasum | cut -b-6`._

Description:

As can be seen I have 0.0540 Btc Locked in account (see top right) but under 'locked funds' tab there shows nothing as locked in trades. Where are these 0.054 btc locked?
Not sure if this is connected with issue I had before : https://github.com/bisq-network/support/issues/672

started_at_UTC:
<_yyyy-mm-dd hh:mm_

github-issue:
>_Please provide a reference issue number to which this case is related. If there isn't one go ahead and create that issue first._

Bisq version:
v.1.6.2

Device or machine:
Windows 10

**Comment by MwithM** [comment]
Hi, I think that this post might be helpful to solve your case: https://bisq.community/t/failed-trades-and-deposit-tx-not-confirmed-troubleshoot-v1-5-4/10223/1
