### ISSUE TITLE
Fee reimbursement for trade 3896217

### ISSUE THREAD

**Issue by diegoviola** [bisq-network/support#927]
![bisq](https://user-images.githubusercontent.com/4371/117661216-760fc600-b174-11eb-84f5-79ad699b79ef.png)

Maker: 17fa60906054dc727d4951a534883eb225c7b87bde8e103c7a3285cdef93d130
Taker: b9ea7b8fd714003b51a1cf4598e41b4b82d72fbfdbdbdcbeb00d271f6c3ef5ff
Deposit: N/A.

Bisq version: v1.6.4.
BTC address for reimbursement: bc1qrdumuz3m02s2xln6yl2y50qungf3mfshvj2xjl

**Comment by diegoviola** [comment]
@refund-agent2 any ideas about this yet please?

**Comment by leo816** [comment]
Reimbursed with #945
