### ISSUE TITLE
Reimbursement for trade kotvik11

### ISSUE THREAD

**Issue by lukaskotvan** [bisq-network/support#928]
Hello,

I have made trade (buying 0.01 btc) on 23 FEBRUARY 2021, due to technical issues I got disconnected. 

When I have logged back in - there was no sign of any trades. I could not continue, dispute or finalize this trade: "transaction". 
![transaction](https://user-images.githubusercontent.com/82460219/117683722-a414fa80-b1b4-11eb-9432-a0409b378bed.JPG)

My onion address is znngrloovnqdbdpeemckbsowjmvbmuyptug55yqebasoqmmhm5iuo3yd.onion:9999  https://mempool.space/tx/c5818b8e674b25d94b1bec860ec96e142310a9ee97f5995cdeee52566ed45dfa  

I have approached mwithm viac keybase, he has done some investigation see "mwithm" 
![mwithm](https://user-images.githubusercontent.com/82460219/117683766-ad9e6280-b1b4-11eb-8106-00a138ca5149.JPG)

and referred me to mediator leo816 see: "mediator has case". 
![asking for support](https://user-images.githubusercontent.com/82460219/117683896-c9a20400-b1b4-11eb-85df-d8136b8c675d.JPG)

![mediator has case](https://user-images.githubusercontent.com/82460219/117683836-bd1dab80-b1b4-11eb-833d-607d249325f1.JPG)

leo816 closed it in my favor see: "leo816".
![leo816](https://user-images.githubusercontent.com/82460219/117683877-c60e7d00-b1b4-11eb-85c1-e012c69cba99.JPG)

However, no refund has been received: "no funds":
![no funds](https://user-images.githubusercontent.com/82460219/117683970-d9b9e380-b1b4-11eb-9ed8-32fbf1f0a17a.JPG)

As the trade in not recorded anywhere in bisq platform I can not use trade ID as reference, I have asked if leo816 can find it for me, but no reply since 17th of April: "no trade ID".
![no trade ID](https://user-images.githubusercontent.com/82460219/117683937-d45c9900-b1b4-11eb-9622-0b75e0a51e51.JPG)

Therefore, I have decided to submit my request without it and provide my reference - nickname from Keybase, where you can track my conversion with support. 
Hopefully you have enough info.

I have made only one single transaction and it is taking ages to sorted out.

As you can see from evidence provided it is clear that I should receive reimbursement, hopefully minor technicality such is missing Trade ID won't be reason for not received rightfully owned refund.

Thanks for help.

Kotvik11

**Comment by pazza83** [comment]
Hi @lukaskotvan and @leo816 what is the status of this reimbursement request?

**Comment by lukaskotvan** [comment]
It has been added to "waiting for info" line 20 days ago. No progress so far.

**Comment by leo816** [comment]
Reimbursed with #1006
