### ISSUE TITLE
Fee reimbursement for failed trade (no trade ID)

### ISSUE THREAD

**Issue by youss833** [bisq-network/support#929]
![image](https://user-images.githubusercontent.com/84043034/117970967-4f2dcd00-b2f7-11eb-9fad-01c4768969de.png)

Maker:  I am the maker
Taker: no taker, see notes below
Deposit: no deposit, see notes below

Bisq version: 1.6.4
BTC address for reimbursement: bc1qtxj4gsxyyde0qc68rhmfqpgjvzpx0vv5ake85g

Other notes: I tried creating a trade (for selling) in Bisq and correctly funded the trade but when I clicked on the confirm button to confirm the creation of the trade, it said that it failed to create the trade so I had to cancel. I tried again creating a new trade and the same thing happened. The problem is that I still got charged the trade and transaction fees both times, even though no trade was created.  Since no trade was created (because it failed to create) there is no trade ID, no deposit, and no taker.

Transaction ID # 1: c4655f1adf7e0b9bda908f0ec4fed525eb6ab4b99faf405ad844d4f62f891ada
Transaction ID # 2: 6b3a7ef1b3c1207ded3ad08f28147cab9e4961a8ac29c0c1b612630e38bb558f

Thank you.

**Comment by pazza83** [comment]
Hi @youss833 

Thanks for posting.

Please can you add the information provided as per the template: https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX

it is not possible to reimburse you based on the information provided above.

**Comment by youss833** [comment]
I provided all the information I have because there is not trade ID since the trade failed to be created. That's why I need a reimbursement because I got charged the fees but the trade FAILED to be created.  So no trade ever got created because of a bug, but the fees were taken from my wallet anyways because of a bug.There is no maker, taker and deposit because no trade was created since it failed to create.  If the trade would have been created I wouldn't need a refund.I provided the only information I have in the screenshot.Thank you,youss833On Aug. 22, 2021 18:39, pazza ***@***.***> wrote:
Hi @youss833
Thanks for posting.
Please can you add the information provided as per the template: https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX
it is not possible to reimburse you based on the information provided above.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

On Aug. 22, 2021 18:39, pazza ***@***.***> wrote:
Hi @youss833
Thanks for posting.
Please can you add the information provided as per the template: https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX
it is not possible to reimburse you based on the information provided above.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

On Aug. 22, 2021 18:39, pazza ***@***.***> wrote:
Hi @youss833
Thanks for posting.
Please can you add the information provided as per the template: https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX
it is not possible to reimburse you based on the information provided above.

**Comment by pazza83** [comment]
Thanks for explaining should have read your original notes more carefully. 

I can see that the trades above failed and each one incurred a trade and mining fee.

Sorry for the inconvenience. 

@leo816 will be able to reimburse you for the costs incurred.

**Comment by pazza83** [comment]
Hi @leo816 please can you add this to your reimbursement to do list.

**Comment by leo816** [comment]
Fee Reimbursement paid out with #1028
