### ISSUE TITLE
Trade failed, BTC missing

### ISSUE THREAD

**Issue by BisqBoo** [bisq-network/support#931]
>_The XXXXX part are a random string generated with the command `date | shasum | cut -b-6`.

Hello, all. I am new here and I really need your help. I tried sell some BTC on Bisq but for some reason the trade fail,also, i cannot see anywhere my BTC. I can provide screenshots with id transaction, all needed to prove BTC funds transfer was done and completed but they dont show on Bisq. I am kind of lost. How do I find and retrieve them back? Please guide?

started_at_UTC:
<_yyyy-mm-dd hh:mm_

github-issue:
>_Please provide a reference issue number to which this case is related. If there isn't one go ahead and create that issue first._

Bisq version:
v1.6.2

Device or machine:
windows 7

SCREENSHOTS HERE
![trade fail 2](https://user-images.githubusercontent.com/84079214/117977992-0cd9af80-b33a-11eb-92a0-67696649d2a2.JPG)
![info](https://user-images.githubusercontent.com/84079214/117978301-65a94800-b33a-11eb-8b5b-6a3ea18f24f7.jpg)

solution:

Other notes:

**Comment by leo816** [comment]
please follow the format of other reimbursement requests, otherwise the request won't be processed

**Comment by pazza83** [comment]
Closed as no reponse
