### ISSUE TITLE
Fee reimbursement for trade AHLGWN

### ISSUE THREAD

**Issue by tommyscience** [bisq-network/support#932]
![BISQ error 2](https://user-images.githubusercontent.com/65740847/118043608-718d0e00-b32a-11eb-8f7b-f6b37fe728a1.png)

Maker:  16086d0f58bbc708e52f108200baac9cbd9e9bf1b7d5acaa68544523252bf045
Taker: N/A
Deposit: N/A

Bisq version: 1.6.4
BTC address for reimbursement: bc1qglggja6sv5lcr43l3lepayyrhpfqzs747g0dn7

An error occurred at the task: CreateTakerFeeTx
Exception message: Insufficient money,  missing 0.00177008 BTC

**Comment by leo816** [comment]
taker fee not found, reimbursement is not justified.
