### ISSUE TITLE
Fee reimbursement for trade CEKNC

### ISSUE THREAD

**Issue by viperperidot** [bisq-network/support#933]
![image](https://user-images.githubusercontent.com/70721357/118754633-b7633e00-b824-11eb-986d-f85865310b72.png)

Maker:  fa2a84df48fd2b3e103b5f69e2cee207e512d2cd655542d72bf81c6b31510fa0
Taker: e9118194b567eaa9a58f0b7024345345362a0ca2ece29f86af422396afe4824e
Deposit: N/A

Bisq version: 1.4.1 or 1.4.2
BTC address for reimbursement: bc1qqeemhwdkmdp02r8ad05t4l2399chhkecurc8xjtge8ycgnspzgfqf099w0

Other notes:

I meant to apply for this reimbursement earlier, sorry for the delay.

**Comment by leo816** [comment]
Reimbursed with #945
