### ISSUE TITLE
Fee reimbursement for 4 trades: balx8, w4xztle3, MshuOTLi & SBE4N0R

### ISSUE THREAD

**Issue by nostrasapientia** [bisq-network/support#935]
![image](https://user-images.githubusercontent.com/84709593/119326411-2821b480-bc82-11eb-8ba6-5b5797c42682.png)

Please I don't know how to provide all the information requested here I need assistance to figure out where to see the maker, taker, etc details of the transactions.

![image](https://user-images.githubusercontent.com/84709593/119342490-71c7ca80-bc95-11eb-9b5d-867b161c384a.png)

All I know is that I made 4 offers trying to buy 0.85 BTC and all 4 got cancelled all of a sudden without any input from my side. 

Now I have been deprived of all the transaction fees and blocked funds. More than 0.14BTC in total. Transaction IDs:

0.03055224 BTC - 86bcf9d163dbe7a7fd3b36dbe0b902c660947f0ca886c698d85e6809e9582bf0
0.03815880 BTC - 061ce509dfd3ecd7f533b53d25cff2c299d7138fc59ab9d7aedd2290b0c1d737
0.00132682 BTC - 1d213336339f50a8a9b98e861c1290b090ad314833a10448cc30e97893b614c4
0.00207940 BTC - cf635aa7a3e37cb9a00dbec6814d44edf065bb720d908a28cd0bd5903d6b5b34
0.00172940 BTC - b9e0139f9d1e3aaec77234b7ca21cfa204775f136a445f042a7cc7b35f20bfb0
0.03065880 BTC - 11d2c806e7f658de73808cb8e6cb9450b68cb402f32eefedd42864a0eefd93a7
0.03788212 BTC - af4f31d677d900a9f1dcfccf043020fde7c8f29724ad540fbe36b2f012e6d5d6
0.00194106 BTC - ffd2a52caaafb29c590b782adb8c2e94c6398ded8bea3603ad43ce8bb778ff83

TOTAL: 0.14432864 BTC

I have been a polite and trust-worthy member of the Bisq community for over 6 months and never have had any issue in the dozens upon dozens of trades I've been a part of. 

Please help

**Comment by pazza83** [comment]
Hi @nostrasapientia 

Thanks for the post.

Please reach out to me on Keybase.  My user name there is pazza. Happy to help you work out what funds have been lost. I think it is likely a lot less than is being claimed for.

It would also be useful to make separate remibursement requests for each trade ID.

You can use the template here: https://github.com/bisq-network/support/issues/new?assignees=&labels=&template=reimbursement-template.md&title=Fee+reimbursement+for+trade+XXXXX

Many thanks
