### ISSUE TITLE
Fee reimbursement for trade 81738

### ISSUE THREAD

**Issue by greengardengnome** [bisq-network/support#936]
![bilde](https://user-images.githubusercontent.com/84743701/119405998-6cdd3800-bce2-11eb-89fd-538495bb0c63.png)

Maker:  606e150c5bdf4765ee87e8870c729e98f48b1fbb8ec61eabd1f8e1ce523ed3a2
Taker: 511bddf0a332de3cec637b510e7064b634beb2b61aae769d1d46f84320783e70
Deposit: N/A
Delayed payout transaction ID: c87fcc4b94fb5b9dc32d59b29db7cd48e60e8de3c646003efbe4f5be8cae4414

Bisq version: 1.6.4
BTC address for reimbursement: bc1qpp4mx844xutpya8wlm06ygewj94y0jcccvp5xq

Other notes:
"Timeout reached. Protocol did not complete in 60 sec." error. It's in failed-folder. Please reimburse fees.
Thanks.

**Comment by leo816** [comment]
were you the maker or the taker for this trade?

**Comment by greengardengnome** [comment]
> were you the maker or the taker for this trade?

BTC buyer (taker)

**Comment by leo816** [comment]
Reimbursed with #945
