### ISSUE TITLE
Fee reimbursement for trade bftwefrs

### ISSUE THREAD

**Issue by AzidanoValkran** [bisq-network/support#937]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![image](https://user-images.githubusercontent.com/78864939/119474015-a4300100-bd43-11eb-8d5a-d373fb5c30a2.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  0c4df02d6c5454e3437bd8049975362f0cc0df7a0d1ecec6194b1ef46d1ed7ba
Taker:  364cc5897c0e0e9d14fd5b14344e67ef1055c5d5a1fc1f0dd2eb1597fe419bbc
Deposit:  17250e91afb6a593d99a99483a6621b41ff956d9190c9f20a0d091c0ff4331aa

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.6.4
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by leo816** [comment]
btc address not provided

**Comment by AzidanoValkran** [comment]
Hi there,

Please send the reimbursement to the following Bitcoin address:

bc1qz2sq6a4x9wp399sfz3k9s9ypuxpp7gmzecgxl6

Many thanks

**Comment by AzidanoValkran** [comment]
Hello? There has been no movement on this ticket for the past 2 months, is everything alright?

**Comment by pazza83** [comment]
Hi @AzidanoValkran 

Thanks I can see you lost fees on this trade.

@leo816 please can you add this to your to do list.

**Comment by AzidanoValkran** [comment]
> Hi @AzidanoValkran
> 
> Thanks I can see you lost fees on this trade.
> 
> @leo816 please can you add this to your to do list.

Any further movement on this?

Many thanks

**Comment by pazza83** [comment]
Hi @AzidanoValkran I have asked @leo816 to comment

**Comment by leo816** [comment]
thank you for the reminder, this will be reimbursed this cycle

**Comment by AzidanoValkran** [comment]
Thank you so much, really appreciated!

**Comment by leo816** [comment]
Reimbursed with #1006
