### ISSUE TITLE
Fee reimbursement for trade 2rsyt09l

### ISSUE THREAD

**Issue by hvsmfaith** [bisq-network/support#938]
![bisq_reimbursement](https://user-images.githubusercontent.com/34965814/120079305-8819c000-c0b3-11eb-8f36-06369e3838d6.png)

Maker:  6352dbcc31f3aeab0e471644062d280fb4901779e8bbfac0d5b39bb276aa214c
Taker: e3097bc0159224b81d74932206cf5fb6a23b8c3feba731ec2447268f3924c2c1
Deposit: N/A

Bisq version: 1.6.4
BTC address for reimbursement: bc1qc07lh0w7ugtduszh0e65rze27m3yn8vnvv695e

Other notes: Timeout reached. Protocol did not complete in 60 sec.

**Comment by leo816** [comment]
Reimbursed with #945
