### ISSUE TITLE
Fee reimbursement for trade 9160058

### ISSUE THREAD

**Issue by kbhk71** [bisq-network/support#939]
![2021-06-01](https://user-images.githubusercontent.com/84517231/120284600-b3233000-c2bc-11eb-87b6-d4c72c9f168e.png)

**Maker:** 4243fbf77a266eff8eab3de18e76c127a07a376f32738a94a117428f2bbb6a47
**Taker:** 13f90fb2646d15ebd17c7e39f1f8b0165b5c95b01ffe38e54f7c68fa6bf2fa83
**Deposit:** 16ab90bed482a9aa68175daf396b65f33b8f7360f9c93d0677a0d11385430f55

**Bisq version:** 1.6.4
**BTC address for reimbursement:** bc1qr3uzaf2vd2x7dmp7j6c7w0mgldqdsxee973yun

**Other notes:**
Security deposit transaction on trade 9160058 is still unconfirmed after 288 hours, as transaction is still not found in the mempool.

![2021-06-01 (1)](https://user-images.githubusercontent.com/84517231/120285733-d7cbd780-c2bd-11eb-9229-bde3862e2b05.png)

**Comment by kbhk71** [comment]
How do I move this trade to **Failed Trade**?

**Comment by leo816** [comment]
taker fee not found, reimbursement is not justified
