### ISSUE TITLE
Track trades with failed Bitcoin transaction broadcasts

### ISSUE THREAD

**Issue by cbeams** [bisq-network/support#94]
This is essentially a follow-on to https://github.com/bisq-network/bisq-desktop/issues/1193, which was closed with the release of Bisq v0.6.5. We've now seen a number of similar looking failed trades, where one or more of maker, taker and deposit transactions do not get broadcast. Several log files have been analyzed at this point, and it is not clear what is causing them.

I have seen perhaps 4 or 5 such failed trades in the last couple weeks, but just today I saw the same trader incur this problem three times in a row with trades `egloilal`, `dxwmp` and `ejpdk`. Like other "tracking" issues, we'll keep this one open, and @keo-bisq and I can use it to record incidences of this problem.

Any reimbursement support issues related to this problem should include a reference link back to this issue.

**Comment by cbeams** [comment]
Note that this is the message I used when closing the trades above:

> This trade failed due to technical issues. Any lost mining and trading fees will be reimbursed. Please see and subscribe to the support issue at `https://github.com/bisq-network/support/issues/[PUT_ISSUE_NUMBER_HERE]` for further details and status updates. Please also note that in order to correct your Bisq wallet balance, you may need to resync your SPV file by going to Settings->Network info->Resync SPV file.

**Comment by cbeams** [comment]
`TKGUVL` just showed up with this problem. This trade, along with the other three mentioned above have all been with the same onion address on the seller side. I'm investigating with the seller now about what might be causing the issue.

**Comment by yourwpguy** [comment]
Trade ID: 423719
Maker: 4b5e5ddaec3c3674e7dc7f63257d2690ce18929b9cf131ea7e67c80fe9525533
Taker: 144dfec41edcd4ff3cc49c05c01eb307b1ef142f30f8f5a562bfad87dc39415f
Deposit: 1613811bd3449022a522ce0b638c727306fd6eb7b7655fa1d7c718ec93270607

Deposit tx was never published. What to do next?

**Comment by Thiagojm** [comment]
Fee reimbursement for trade anY1E34k #265

**Comment by pazza83** [comment]
Closing as stale
