### ISSUE TITLE
[Reject] Reimbursement for Cycle 25

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/support#940]
I paid out 0.48265664 to traders. 30D BSQ/BTC rate is 0.00003930.
I ask DAO to reimburse me 35387.23BSQ.

Role report: https://github.com/bisq-network/roles/issues/93#issuecomment-855257876

**Comment by refund-agent2** [comment]
fce333682c82aaf10205037385e69ab24617cd6d910754a9a4ce0ebd57bac46a

**Comment by sqrrm** [comment]
This does not seem right. At the given rate the reimbursement should be 0.482655664/0.00003930 = 12281.31BSQ. It looks like the BSQ amount requested is the same as from the previous cycle, https://github.com/bisq-network/support/issues/925 where the number did add up.

@refund-agent2 could you please check on this discrepancy?

**Comment by refund-agent2** [comment]
I used the old reimbursement request as template but I forgot to change the final amount of BSQ requested as reimbursement.
Please reject this reimbursement, I'll add the 0.4826 BTC to the next Ccyle's reimbursement request, using the 30D average on that moment.

**Comment by refund-agent2** [comment]
Was accepted.
