### ISSUE TITLE
Fee reimbursement for trade PVUTSAUC

### ISSUE THREAD

**Issue by qySPocwCbgB4oiKpwXui** [bisq-network/support#941]
![Bisq-Failed-Trade_1](https://user-images.githubusercontent.com/85519468/121079609-a29e1880-c7da-11eb-8dc5-242770dace96.png)

Maker: 81d7619b374b9bacedb67e40eeb09aae886b6296aa53faae3f516aec653c100e
Taker: c85a033c7d97d5ddcc34cbe20b4eef6a7c517ac193f2b3af4b733a0d2794ab8e
Deposit: N/A

Bisq version: 1.6.5
BTC address for reimbursement: bc1q288pyp34xlphprkpycrlvc4acv2hle99gaqktn

Other notes: Timeout reached. Protocol did not complete in 60 sec.

**Comment by qySPocwCbgB4oiKpwXui** [comment]
Would be a shame if the money got lost... :\

**Comment by qySPocwCbgB4oiKpwXui** [comment]
Since no one seems to know, I guess this is a bug rather than a feature...
Should I open a new issue for this?

**Comment by leo816** [comment]
Reimbursed with #945
