### ISSUE TITLE
Fee reimbursement for trade 10017180

### ISSUE THREAD

**Issue by PoltergeistEx** [bisq-network/support#942]
![bisqissue1](https://user-images.githubusercontent.com/85572634/121216005-cc117f80-c880-11eb-8656-7302a5108001.jpg)

Maker:  986215eed2c16e69dbd1fded74ee31c8b1be1f45299805d2069db2e7d5bf3ee1
Taker: 07d6ef415689e7730aed92dda45d500c21d37af00daef070f6fccbbff127fff4
Deposit: N/A

Bisq version: 1.6.5.
BTC address for reimbursement: bc1q67ja2z4tt2h4dp5lq9w53l5swcvsawwq7equyz

Other notes: An error occurred at task: BuyerFinalizesDelayedPayoutTx
Exception message: Delayed payout tx is paying less than the minimum allowed tx fee
Please reimburse security deposit and fees.

**Comment by leo816** [comment]
Reimbursed with #945
