### ISSUE TITLE
Fee reimbursement for trade 07793

### ISSUE THREAD

**Issue by SoldadoBTC** [bisq-network/support#943]
![image](https://user-images.githubusercontent.com/85647096/121425232-8f10c000-c948-11eb-90bc-b5cb4e13282e.png)

Maker:  10c8bce7007144cf1a6d37eb117d3d525d340b0679466d3048fa24feab3bc0d0
Taker: 86e2a0738df6f37f49c2243ff1dccccf8fe9c86ca245c009ae5367c183d0e238
Deposit: ef3126e5bceacb6e00ee673d1392e84084ffe6f8c48db51b93f6b93ec9ad7211

Bisq version: 1.6.5
BTC address for reimbursement: bc1q4ydl2mcpavmzjcu97dlphx4pje5qd0duyxaj2j

Other notes:
![image](https://user-images.githubusercontent.com/85647096/121425680-0fcfbc00-c949-11eb-87fe-98e7efee0395.png)

**Comment by leo816** [comment]
Reimbursed with #945
