### ISSUE TITLE
The trade contract is not set.

### ISSUE THREAD

**Issue by ThisMightHelp** [bisq-network/support#946]
Newbie. I had 0.057 BTC showing available, made a buy offer, said 0.015 BTC needed, then showed sufficiently funded, and this error popped up. Then I realized the balance is pending arbitration payout and not available. I don't know if I lost my trade fee. Please let me know what other info I can give. Thanks for any help.

![SS Failed trade ](https://user-images.githubusercontent.com/60980763/122486286-be59a980-cfa6-11eb-9b41-b14ebd4fd592.png)

**Comment by ThisMightHelp** [comment]
Also: An error occurred at task: CreateTakerFeeTx Exception message: Insufficient money,  missing 0.00690775 BTC

**Comment by CLPBH** [comment]
Hello.

Something similar happened to me. Did you get some answers from the community o did you solve it somehow?

Thanks in advance for the feedback.
