### ISSUE TITLE
Fee reimbursement for trade ENUMCP

### ISSUE THREAD

**Issue by Ex0ticButt3rs** [bisq-network/support#947]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screen Shot 2021-06-19 at 8 32 42 PM](https://user-images.githubusercontent.com/86173897/122659044-7fac2680-d141-11eb-9be5-ac04fc48912d.png)

![Screen Shot 2021-06-19 at 8 48 02 PM](https://user-images.githubusercontent.com/86173897/122658972-d9f8b780-d140-11eb-9e36-4f1990597582.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  3cbfcb1dbb79fb5f1357556dbd73dcd145ec0541c0620e5ba09f4cf6b4d0b437
Taker: bd96de41b43f721ac03bfaca5bfe32a47b65fc1859bf7a0d654096e2cacfc17e
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.6.5
BTC address for reimbursement: bc1q90lqgukmmsnr4ex4ql09j7wv33rnydg86s8mup

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: I appreciate your attention to this matter! I'm newer to Bisq; in this situation did I not receive BTC I purchased in this trade as well as paying the trade fee? I'm trying to understand what happened. I appreciate your patience. Thank you!

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Reimbursed in tx id: https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
