### ISSUE TITLE
Fee reimbursement for trade WtNAuHe

### ISSUE THREAD

**Issue by JasMartine** [bisq-network/support#949]
![1](https://user-images.githubusercontent.com/86481137/123439236-6f74cb00-d5c9-11eb-9807-2d7992c699d0.png)

Maker:  6f54265061caa2bec70a10a022faf73b22287a5c4b40fa5f34be69bfea0d594e
Taker: e2f2659008cc0764ae7165c11d478448c59a32271ad1a2cdbb7cea8c33806165
Deposit: N/A

Bisq version: 1.6.5
BTC address for reimbursement: bc1qrqpd05ha0ap359t9mqwet7rlqu85kygmmxp96c

**Comment by leo816** [comment]
Reimbursed with #1006
