### ISSUE TITLE
Fee reimbursement for trade gLqQklQx

### ISSUE THREAD

**Issue by crptsly** [bisq-network/support#952]
<img width="810" alt="Snímka obrazovky 2021-06-29 o 22 47 28" src="https://user-images.githubusercontent.com/77293641/123865724-9108e600-d92c-11eb-9d30-12458857fec2.png">
<img width="895" alt="Snímka obrazovky 2021-06-29 o 22 47 48" src="https://user-images.githubusercontent.com/77293641/123865832-ad0c8780-d92c-11eb-805e-e0faf00285ff.png">

Maker: f5fe021566dc11fc82e28ac69f970c74b3704ccd62a903124c8935c813e3d922
Taker: 4b3f7361d4c5d4c40b71cff5628d939ad3657f133aad8776ceea606e790d989d
Deposit: 7932987d628681936555ad47a9b5cc4e3c4a916fd274301a684470d8672000f9

Bisq version: 1.7.0
BTC address for reimbursement: bc1qrhqaqxqjwvs5f5q8ydhafg5m8l25qu730n0045

Other notes:   Locked: 0.0150 BTC

**Comment by pazza83** [comment]
Hi @crptsly 

You were the taker for this trade.

Taker tx ID failed: https://mempool.space/tx/4b3f7361d4c5d4c40b71cff5628d939ad3657f133aad8776ceea606e790d989d

You have not lost any funds for this trade.

The locked funds shown in Bisq might be a GUI error.

Please reach out to me on Keybase my user name there is pazza if this is still unresolved.
