### ISSUE TITLE
Fee reimbursement for trade IYAYEL

### ISSUE THREAD

**Issue by CLPBH** [bisq-network/support#953]
![image](https://user-images.githubusercontent.com/86716344/123941639-a288d700-d99a-11eb-9d35-391cb172721f.png)

![image](https://user-images.githubusercontent.com/86716344/123941776-c6e4b380-d99a-11eb-9e1c-04c4e955024b.png)

![image](https://user-images.githubusercontent.com/86716344/123941856-dc59dd80-d99a-11eb-9a12-06a45bf6ea38.png)

Maker:  4bb55b2e214d08b88a44ab8a43d3182e3e327b05d76e416f0ab39d9a137554de
Taker: Not available
Deposit: Not avaliable

Bisq version: v1.6.5
BTC address for reimbursement: bc1qxlhcwtyew9rvs74h6zydckw4qr8pmxrldj5dnr

Other notes: It was my first transaction on Bisq. Sorry if I did something wrong. I tried to reach the other peer, sending messages, but he didn't answer.

**Comment by CLPBH** [comment]
Any help about this? 

I'm new to Bisq and I would love to have a short comment teaching me what was done wrong by my in this case and how can I fix it for the next transactions.

Many many thanks in advance!

**Comment by leo816** [comment]
the taker fee is not valid, which means the funds never left your wallet and a reimbursement not justified. A SPV resync should solve this. Please reach out to our keybase team for more questions or message me directly (leo816).

**Comment by pazza83** [comment]
Closing based on above comment
