### ISSUE TITLE
Fee reimbursement for trade ngpmy

### ISSUE THREAD

**Issue by monkeyman1979** [bisq-network/support#954]
<img width="863" alt="Screen Shot 2021-07-01 at 3 46 56 PM" src="https://user-images.githubusercontent.com/37835299/124134875-94fb4c00-da83-11eb-96a1-a4e3ee6f2cc5.png">

Maker:  113d64380fd3af54a36b796286dc3ca3fc4b76ca5ac98d23411bf3d54c43c1c6
Taker: N/A
Deposit: N/A

Bisq version: V1.7.0
BTC address for reimbursement: 1MwBuHDW7twcFm6K2apdPBjDYdvB43q2fu

Trade ID: ngpmy-94ed7172-ac36-4094-8df3-aed8714ca862-170

**Comment by pazza83** [comment]
Hi @monkeyman1979 

Please can you repost the screenshot to show if you were the maker or taker.

Many thanks

**Comment by pazza83** [comment]
closing as no response
