### ISSUE TITLE
Fee reimbursement for trade y4yuwnms

### ISSUE THREAD

**Issue by Ex0ticButt3rs** [bisq-network/support#955]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![y4yuwnms - trade screenshot 7 1 2021](https://user-images.githubusercontent.com/86173897/124145809-20acb280-da5b-11eb-8880-92e04a97c554.png)
![y4yuwnms - Attention - deposit transaction is missing 7 1 2021](https://user-images.githubusercontent.com/86173897/124145812-21454900-da5b-11eb-8a01-ef5f8955cdb9.png)
![y4yuwnms - Warning - security deposit transaction still unconfirmed 7 1 2021](https://user-images.githubusercontent.com/86173897/124145816-21454900-da5b-11eb-8902-6d5655b3b577.png)
![y4yuwnms - Warning - missing or invalid transaction 7 1 2021](https://user-images.githubusercontent.com/86173897/124145817-21454900-da5b-11eb-86b3-ebab2968071b.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  a6621685e4a960bba48e36e6379be15daa37255b50828c583e98085b2a7b2485
Taker: 48518f57e5f8cf53c11208abcef97e226c01cd84c59ccb74bdcd2e8720d10e1f
Deposit: 8917a65e78f67d82bffaa3ab3ed3e2d74a2da7a8fe3e931c97c8e0e53853d2e4

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.7.0
BTC address for reimbursement: bc1q90lqgukmmsnr4ex4ql09j7wv33rnydg86s8mup

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: I appreciate your attention to this matter!

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @Ex0ticButt3rs

You were the maker for this trade.

Maker tx ID failed: https://mempool.space/tx/a6621685e4a960bba48e36e6379be15daa37255b50828c583e98085b2a7b2485

No transaction took place.

You have not lost any funds or fees for this trade.

Let me know if you have any questions.
