### ISSUE TITLE
Fee reimbursement for trade 8gkkt

### ISSUE THREAD

**Issue by Ex0ticButt3rs** [bisq-network/support#956]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![8gkkt - trade screenshot 7 1 2021](https://user-images.githubusercontent.com/86173897/124147449-b3018600-da5c-11eb-8e77-e40c828a5a68.png)
![8gkkt - Attention - deposit transaction is missing 7 1 2021](https://user-images.githubusercontent.com/86173897/124147452-b3018600-da5c-11eb-9f33-4880fe83b353.png)
![8gkkt - Warning - security deposit transaction still unconfirmed 7 1 2021](https://user-images.githubusercontent.com/86173897/124147453-b39a1c80-da5c-11eb-9bdc-1f9da600d567.png)
![8gkkt - Warning - missing or invalid transaction 7 1 2021](https://user-images.githubusercontent.com/86173897/124147454-b39a1c80-da5c-11eb-8de5-b528f207bd42.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  602e756b19bc7e8153ef678ce68b7b7f866aee2de277a2792e7315dbd232c2a8
Taker: 140e701fd923d7199ecbd7dc167c76ec2d52be177e3643a292362810a135da4f
Deposit: 15744979eec69feee61b538c06820cea201fce9097e307793a1b2ed40d432474

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v1.7.0
BTC address for reimbursement: bc1q90lqgukmmsnr4ex4ql09j7wv33rnydg86s8mup

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes: I appreciate your attention to this matter! 

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @Ex0ticButt3rs 

You were the maker for this trade.

Maker tx ID failed: https://mempool.space/tx/602e756b19bc7e8153ef678ce68b7b7f866aee2de277a2792e7315dbd232c2a8

No transaction took place.

You have not lost any funds or fees for this trade.

Let me know if you have any questions.

**Comment by pazza83** [comment]
Closing issue based on my above comment.
