### ISSUE TITLE
Fee reimbursement for trade y4yuwnms

### ISSUE THREAD

**Issue by offeror** [bisq-network/support#957]
![Untitled](https://user-images.githubusercontent.com/86822878/124236200-75f9ca00-db16-11eb-9374-0ffd155b1aae.png)

Maker: a6621685e4a960bba48e36e6379be15daa37255b50828c583e98085b2a7b2485
Taker: 48518f57e5f8cf53c11208abcef97e226c01cd84c59ccb74bdcd2e8720d10e1f
Deposit: 8917a65e78f67d82bffaa3ab3ed3e2d74a2da7a8fe3e931c97c8e0e53853d2e4

Bisq version: v1.7.0
BTC address for reimbursement: bc1qy6wzqlgznt8qme6r8lw0g5pvqy2kdyuqax3nza

Other notes:
Error message: Deposit transaction is null or has unexpected input count

**Comment by pazza83** [comment]
Hi @offeror please can you repost the screen shot to show if you were the maker or taker.

**Comment by offeror** [comment]
Hi @pazza83 I was taker in this trade, I can't do any screenshots from this trade, as I had to switch to another bisq folder, as we discussed in Keybase due to inaccessible funds in BTC wallet. But I still have backups from old bisq folder, if you need anything. Also my BTC address for reimbursement chanched: bc1qy6wzqlgznt8qme6r8lw0g5pvqy2kdyuqax3nza

Thanks

**Comment by pazza83** [comment]
Hi @offeror 

Thanks for confirming you were the taker and your new btc address for reimbursement. 

@leo816 will refund you the fees incurred.

Hope things are running smoothly with your new Bisq data directory.

**Comment by pazza83** [comment]
Hi @offeror this has now been reimbursed in tx id: https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
