### ISSUE TITLE
Completion of trade  uMpKLvsp

### ISSUE THREAD

**Issue by CognitiveDiss** [bisq-network/support#958]
Hi. I got a failed trade message so went to mediator who confirmed continuation. I paid my money and the seller confirms this but cannot release the btc. It seems we are both getting 'Failed Trade' pop-ups. I messaged support on Keybase a few hours ago, but I've had no response. Suggestions please! Thanks.

**Comment by CognitiveDiss** [comment]
![Skärmavbild 2021-07-05 kl  16 21 37](https://user-images.githubusercontent.com/74058624/124578502-78428800-de78-11eb-8b1b-6ea8adbc93ff.png)
![Skärmavbild 2021-07-05 kl  16 26 59](https://user-images.githubusercontent.com/74058624/124578522-7c6ea580-de78-11eb-9a91-b1d76a6426be.png)
![Skärmavbild 2021-07-06 kl  07 10 01](https://user-images.githubusercontent.com/74058624/124578525-7d9fd280-de78-11eb-9b2a-fcfe56e150c2.png)

**Comment by CognitiveDiss** [comment]
I can't communicate with the mediator on the platform and it seems too that my messages to the seller are not getting through.
![Skärmavbild 2021-07-06 kl  16 58 55](https://user-images.githubusercontent.com/74058624/124581895-b8573a00-de7b-11eb-8b8a-56a890626eef.png)

**Comment by leo816** [comment]
trade closed correctly

**Comment by CognitiveDiss** [comment]
Thanks Leo, but, for the record, the trade has still not settled. The seller has not confirmed receipt of my transfer nor released the btc, and my messages to him on the platform do not appear to be getting through.
Alan



 



 


"Anyone who can make you believe absurdities, can make you commit atrocities.” - Voltaire

 

    On Wednesday, 7 July 2021, 04:56:53 GMT+7, leo816 ***@***.***> wrote:  
 
 


Closed #958.

**Comment by leo816** [comment]
Payout was made correctly, the btc seller released and you received the funds to the address assigned on your bisq account. this is the deposit tx id: 6efe7b9b6350c61998cff7ed8d32b77db9d9e71e503292383d895321d2a5a3c0
let me know if you have any questions

**Comment by leo816** [comment]
I believe this reimbursement request is not justified

**Comment by opticbit** [comment]
this is linked in cycle 31.. its supposed to go here

https://github.com/bisq-network/compensation/issues/958
