### ISSUE TITLE
Fee reimbursement for trade gwoopjy

### ISSUE THREAD

**Issue by iplesko** [bisq-network/support#960]
![screenshot-anonymized](https://user-images.githubusercontent.com/645099/124708686-e62f9380-defa-11eb-9308-d3f3e5dfab6a.png)

Maker: 8b594883c2f0ecec25b8cefc5765bb80aaf05526b5ed4ea8bd1499cfc380b0da
Taker: d62d336a725d62d4183a2d5b4ac47e8fd74dd18958949e67be57c6132ea31dcb
Deposit: 08a1b1d557270c0049f6785971ba3dd7421abcaba750f3344e758d1c7670c995

Bisq version: 1.7.0
BTC address for reimbursement: bc1q9k2qde2aqzt2x7pvmk262gk3j5tmhr7f8gx63s

Other notes:
Bisq client also says that there is 0.001110 BTC of security deposit locked.

**Comment by iplesko** [comment]
Well, this is strange. I counted everything and I found out that have every satoshi I wanted to have. I believe there is in fact nothing locked, but the client says so anyway 🤷‍♂️  So I think we can close this issue (or maybe even delete it) and I'll just ignore the incorrect information about locked deposit in my client. But if there is a way how to reset the incorrect information, please let me know. I already did the SPV file resync.

Sorry for the noise 😇

**Comment by huey735** [comment]
This trade failed and no funds were sent to multisig. Do a SPV resync if the UI still shows funds as locked for this trade: https://bisq.wiki/Resyncing_SPV_file#From_the_Bisq_interface. Please refer to https://github.com/bisq-network/support/blob/master/docs/known-bugs.md if issues still remain.

Make sure all other trades are finished and under the History tab.

    If the failed trade is still under Open Trades, please make a backup, close Bisq. Go to your Bisq data directory. And delete the Bisq/btc_mainnet/db/PendingTrades file. This will delete the data related to the failed trades and should fix the issue.

    If you were able to move the trade to the Failed tab, please make a backup, close Bisq. Go to your Bisq data directory. And delete the Bisq/btc_mainnet/db/FailedTrades file. This will delete the data related to the failed trades and should fix the issue.

**Comment by iplesko** [comment]
Since this was my only opened trade, I removed the Bisq/btc_mainnet/db/PendingTrades file which resolved the issue. Now the UI shows correctly that I have 0.00 BTC locked. I received this hint via support ticket, so thank you. Closing this one.

**Comment by iplesko** [comment]
Thank you very much. Deleting the Bisq/btc_mainnet/db/PendingTrades really
helped.
Is there any chance that you would also delete the ticket
<https://github.com/bisq-network/support/issues/960> from github? I have
some privacy considerations as my github account is public.
Many thanks.

st 7. 7. 2021 o 16:33 huey735 ***@***.***> napísal(a):
