### ISSUE TITLE
resync my SPV file and now the trade is gone.  transaction refund

### ISSUE THREAD

**Issue by quickdrawgrandrpa** [bisq-network/support#965]
I got a pop up for a Transaction refund but now it when away.  On my upper right menu next to available balance states 0.32045... is locked.  But when I go to locked funds under the funds menu it states No funds available.  

I had a transaction  with an error popup that said security deposit transaction on NJyhgg is still unconfirmed after 13 hours.  One of the fixes was to resync the SPV file.  When I did that is when I got a link to this site to request transaction fee return.  

I have since then rebooted my Bisq and all I see is this 0.032045... stating locked in the upper right hand corner of the Bisq app.  Did I lose the whole BTC on the transaction?

I found it in my failed trades and moved it back to open trades.  It says the deposit transaction (the 2-of2 multisig transaction) is missing.  without this tx the trade cannot be completed.  No funds have been locked b uy your trade fee has been paid.  You can make a request to be reimbursed  the trade fee here.  

Here is the trade id:
NJyhgg-e5507f6d-6029-4202-ab0c-38119a092677-170

I am the Seller.

**Comment by pazza83** [comment]
Hi thanks for raising this issue. 

If this is still yet to be sorted please reach out to me on [Keybase](https://keybase.io/team/bisq) and I will investigate it for you.

Please quote trade: NJyhgg in your message

My username on Keybase is: pazza

**Comment by pazza83** [comment]
HI @quickdrawgrandrpa please reach out to me on Keybase if this is still to be resolved

**Comment by pazza83** [comment]
closing as no response
