### ISSUE TITLE
Reimbursement for Cycle 26

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/support#967]
30D BSQ/BTC rate is 0.00003516.
Last cycle I did a mistake and reimbursement had to be [rejected](https://github.com/bisq-network/support/issues/940). 0.4826BTC were left for reimbursement, at current 30D average this equals to 13725.82BSQ.
I paid out  to traders 1.14501601BTC. For reimbursements on current cycle, I ask DAO to reimburse me 32565.87BSQ.

In total, I ask DAO to reimburse me **46291.69 BSQ**.

Role report: https://github.com/bisq-network/roles/issues/93#issuecomment-881258194

CC @leo816 @sqrrm please review before I submit to DAO.

**Comment by sqrrm** [comment]
Looks good now. Sorry for the late review.

**Comment by ripcurlx** [comment]
@refund-agent2 Can you please verify that this is the correct transaction id: `07e8d2698c6170005a5e328900d2569fa2072f9d76481ea70cd6c792365ac2b2`? Thanks!

**Comment by refund-agent2** [comment]
Was accepted.
