### ISSUE TITLE
Fee reimbursement for trade 6kqwyrl

### ISSUE THREAD

**Issue by Mangobeach** [bisq-network/support#968]
![InkedCapture7_LI](https://user-images.githubusercontent.com/87566836/126033979-837c9b71-a988-4e26-9fb2-e4a2ca78777f.jpg)

Maker: 9ad56c945d37e2ad0030013ce14bfaa249d3eae3b61a840e80ebee68b08b67e8
Taker: 7649a503a49ca3725209a0d1110e222bd2cf7e50360240e3e3c32d7fa50de920
Deposit: ae51e8f79dc7e3c89dbebd8b56abacde86d21dd2a0bdcfb89688302357040d90

Bisq version: v1.7.0
BTC address for reimbursement: bc1q9lxlqwf9mw3znwhfrurng7p94hn88x0f38y6k0

**Comment by pazza83** [comment]
Hi @Mangobeach 

This has now been reimbursed here: https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
