### ISSUE TITLE
Fee reimbursement for trade vwuqsac

### ISSUE THREAD

**Issue by emmieG** [bisq-network/support#971]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

![Screenshot_907](https://user-images.githubusercontent.com/87716321/126361519-2345410d-64ef-4138-9a6a-9d4e754dc427.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by emmieG** [comment]
![Screenshot_908](https://user-images.githubusercontent.com/87716321/126364648-1a7db9a1-a766-4306-b58d-dea126692d9e.jpg)

**Comment by pazza83** [comment]
Hi @emmieG 

Please can you copy and paste the full transaction IDs for this trade:

Maker transaction ID
Taker transaction ID
Deposit transaction ID

**Comment by pazza83** [comment]
closing as no response
