### ISSUE TITLE
Fee reimbursement for trade 289978

### ISSUE THREAD

**Issue by lmsequeira2016** [bisq-network/support#975]
<img width="881" alt="Captura de ecrã 2021-07-30, às 22 43 16" src="https://user-images.githubusercontent.com/17260845/127714918-4b9a76a6-c1e6-43fd-8211-d8df7700776f.png">

Maker: b70032768da1d97b732881adac9c1dd3bfc306f1e3e63b9b587836142a9bab04 
Taker: 59f065656b3de563a552c82b7276a4aa8bcae86ff33fe3c4cf0b5330fe91c165
Deposit: 85a2684f11ad103f234ac71bedc3a360231ce2c2d3f6fa6e3ffe770fcdea5439

Bisq version: v1.7.2
BTC address for reimbursement: bc1qhrfqh3gaz7sj4w5m7lsynhlh978s72a4yyye6x

**Comment by pazza83** [comment]
Hi @lmsequeira2016 

Thanks for opening the issue.

No transaction took place when you took the offer: https://mempool.space/tx/59f065656b3de563a552c82b7276a4aa8bcae86ff33fe3c4cf0b5330fe91c165

You have not lost any funds or paid any fees on this trade.

Let me know if you have any questions.
