### ISSUE TITLE
Fee reimbursement for trade vgrnp

### ISSUE THREAD

**Issue by LPerm** [bisq-network/support#977]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![fail-vgrnp](https://user-images.githubusercontent.com/88529867/128474710-ffa35e46-4ab6-4c34-a5da-f385c027814e.PNG)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  2b59ad8fe90846ba3d91831fb697969830b2716242e0f977e6d7cb41b53864bf
Taker: cd46260884d81372100848a305f369b62e05f99886877ac132732148d074ca4e
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: v.1.7.2
BTC address for reimbursement:  bc1qzyc70vdm7vjaa0pcvhmfcvmujvnmmz96zrqj2y

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>_Issue [#197](https://github.com/bisq-network/support/issues/197) can be used as a good example of a correct reimbursement request._

**Comment by pazza83** [comment]
Hi @LPerm 

This trade has now been reimbursed

https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
