### ISSUE TITLE
Fee reimbursement for trade 04267419

### ISSUE THREAD

**Issue by zulu68** [bisq-network/support#978]
![reim](https://user-images.githubusercontent.com/75555532/128608006-6387fed1-26f9-4272-b05c-58624af9abdf.PNG)

Maker:  94a7be43aa14b761edb9d735fc7f20808411cb1fd8b1af9801e87b8284525b1e
Taker: c979ea5210678be6ca93c8e1e8b9b2550ecd90abe92f278a74730ca392b3b365
Deposit: 67a287600cbedf268a29c2d28bb3a967c18bfe592fd5c5dfe400ca823c217502

Bisq version: 1.7.1 (error occurred on 1.4.1)
BTC address for reimbursement:

Other notes: Delayed payout transaction failed, Resulting in my security fee being locked up indefinitely.

**Comment by pazza83** [comment]
closing as trade completed successfully.

@zulu68  please comment below if I have missed anything.
