### ISSUE TITLE
Fee reimbursement for trade 97647430

### ISSUE THREAD

**Issue by charleedr** [bisq-network/support#980]
Maker:  9ea54cb5af39758fa5e65bb61c73196a701c0d31db5e0e07c344ea91dc827efb
Taker: N/A
Deposit: N/A

Bisq version: 1.7.0
BTC address for reimbursement: bc1qkm0a52cjus5rah2yz4ug8yza546pgv4xr4df2a

Other notes: 

![Captura de pantalla 2021-08-10 182200](https://user-images.githubusercontent.com/88732544/128896746-cb8212dd-1904-499b-9a79-d4ffdd23a64a.png)

**Comment by pazza83** [comment]
Hi @charleedr 

The fees for this trade  have now been reimbursed:

https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
