### ISSUE TITLE
Fee reimbursement for trade 270874

### ISSUE THREAD

**Issue by jongofjoo** [bisq-network/support#981]
<img width="884" alt="Screen Shot 2021-08-11 at 6 14 17 PM" src="https://user-images.githubusercontent.com/88804354/129110640-1a1baa24-d2cb-49c3-9b92-a6462f36f2e9.png">

Maker: f103293724f0cd124eb1fa0e806ad96b16b0cc84de3ee6ad405ca7e5a529f977
Taker: 7c97a87b7505c772129bf943372286804cccd64320e3c574e8683fbe26201208
Deposit: 7c04204eb811a693cfe7bddea5525720aabde3fb044a61dc1da6bfc1cc176f3f

Bisq version:v.1.7.0
BTC address for reimbursement: bc1qeddyklhw3l8funt8trs9uhhrftn30cdnkjtsxh

Other notes: Security deposit transaction failed.

**Comment by pazza83** [comment]
Hi @jongofjoo 

The fees for this trade have been reimbursed:  https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
