### ISSUE TITLE
Fee reimbursement for trade RRAYX

### ISSUE THREAD

**Issue by aidfarh** [bisq-network/support#982]
![image](https://user-images.githubusercontent.com/1995786/129434703-24209807-6398-4189-9c16-54203ee24578.png)

Maker:  d9fd8b1f84342a9c4bb14607c16875aba28563076d0fd80b5acff28aab7b37b3
Taker: 7483fba121e94f3426a2168d7d129722fbad01350458ef18ca508d0c6e0f5d0a
Deposit: cbd407c6d96f59e0e99a92425481cb6ff0abe5246ee4af5f07e628ea441142bb

Bisq version: 1.7.2
BTC address for reimbursement: bc1qsuz492arp28w4tlz0c9vgxhh2mgtvm4pdm653m

Other notes: Deposit transaction is missing. Moved to failed trades. Please reimburse maker fee.

**Comment by pazza83** [comment]
Hi @aidfarh 

The fees for this trade have been reimbursed https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2

**Comment by aidfarh** [comment]
> Hi @aidfarh
> 
> The fees for this trade have been reimbursed https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2

Thank you very much for your support.
