### ISSUE TITLE
Double payout on trade 88378794

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/support#983]
Due to this [bug](https://github.com/bisq-network/bisq/pull/5649), the Bisq client created 2 different payouts for the trade 88378794.
I have asked to the onion address a5iob... to reimburse me the funds through the chat.

The 2 payouts are: 
[8a40228597d6ce10baa0bc3c5ded7c9d45924c14946a28da22e4cd900678c13d ](http://mempool.space/tx/8a40228597d6ce10baa0bc3c5ded7c9d45924c14946a28da22e4cd900678c13d)
[a6aa9ad460ba96fd590eab3030d70f8d0c057d53e1d2f5575f63a876f91f00d2](https://mempool.space/tx/a6aa9ad460ba96fd590eab3030d70f8d0c057d53e1d2f5575f63a876f91f00d2)

Both tx are sending 0.08136250 BTC to the address bc1qnth6eaml5x7ugm0vaf45kw7rmura4cs2p0qc53 so I demand the owner of this address to give me back 0.08136250 BTC by sending them to the address bc1qlprzx6tur0cvhmvzn3d6pvphzggpjfxj8unpvn (used as input in the second payout) or to the DAO donations address 34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkZLbxYV kC7EjlRx7IOE5PM dEeQlOO0zXrJt7R 3OEeY1VBjhf7Csd WaLJtSaQpRAGRZT MzYNpnszfviZs59 2zJrVLGpH18LhZ7 lB9f9asOkh9rchc KTJ3G9R5JwnTWWk mh6qOXrDZYWSxyS Cwaj9UE26ozLAbJ DdzlCIhXIacy6x9 kN5hTcgoeg31Xqz GYW8qQfFjYvRy22 6aWyMtF71th1mG4 GyX8U7z6PQiz9zy A55Qq3tVCQjcArd j2eDGsLVkmeDreX UrGB9cnbMq3Ekrt yO2Vc3UYN9KQkzP luCQc2VabeDPwFa J7kv9EolD4PvrMN ymAbuJf5NehsYpD cWMivHiWUGWg1pa g1T2UWUATjqmQLn TfWxrJIP3z9Xl2f U8CxqTEbAMAYvFh xK2q7AN04WR7rbS g9gDsfiDTm3cFmo VNjJfa8Kgl6JlaD JGyATr7sOkpHNtW OA9OYKCzYDnlbxG 42D1V2L8eBkllpQ UuGy4GN36JLRksf HKmrsze4jhkvf5V 7lA1Wfr7nP2yLh6 7LeeCcUmsXWS1nr T7zHbNwa1i6m04F cNaMnjHEU8GjckI y0M5cF5QFYnDfgK 3roH2k8ag52gZAl j4v3NbVc2EcUEWA DKNEbil6nmZs6wE 0kjGrEDGK0xt7Qm V2k8vpIefWWDjBf OxTFwr2aUCpobMh 3RkUPUgFUYWdkX1 GUFhFCE3cgLN3On ZjKfJzgB0qNnvwt CjRNkyBjl8BHRuK ZL5dTwOGGCcOMTa BAut6MWGV9nOQCj WcwVDgjgxwfRZk0 YbnqgYqRc8Aky8s RhXGWTe7CX5e1SW sAm6tzIbrvenaIg vWUKKCqgwTmgdSk mjomyPl4bdZvJM8 SwpTWScjScYFMJ1 Gz5NzkTXZXrs0sw ClUGc0lh2mACz4b CrIEat5RQlYLNUZ MRcLIkp3QT1wae2 H8HKfrLjTFWzvCQ 1t1ggd0n8P1VXj7 h9TR92rYv4Sc1Bh cAkt5NAyrpqhRt6 Tt1VkfpcKfvUS4R RH0R37db64dmPDw 5fZtqszp5ndxkwC F1th8yoZxdN6RYH ouEj8D8KuQhhYkH Ag6Esy6fCWovEDU CLvC5i077gPCSYd MeVKv6STmSvmBpo 10uoqTDDzuF7GVG Hrnw4ORMZCeVJUR DBxwoGZC9eqgXkW gmVBYzod9if9nmP baynPiHiBcy7vr6 c5fUXiIeyGtWY3X f5IoAgvGZiYi1Dh 0MDO3rEPbkfzRr4 wVnbKdz8lIyhijx LvRjndBFqnCtoPb QQGz10cy5Wf9j35 3irYVFKbXH7fFaU rUu4sliDGrTyrQQ HBwyuvnyT6Nqtzl jp2dBgXCyLxAuxE x3fBwJfW5Xb0cXN ejE7rtZSQeYAxth ss. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by Akira45-0** [comment]
Sent back, tx id 521f9855e6f6cafdc5d8520449be4661588957492c44602fbf9664b15a09ce4d
