### ISSUE TITLE
Fee reimbursement for trade jeAZOx

### ISSUE THREAD

**Issue by corey66** [bisq-network/support#984]
![image](https://user-images.githubusercontent.com/24442577/129459156-353e29c8-8b0c-465e-a694-bdb3639236d0.png)

Maker:  5a211ffb257dd83a6c869901070f82297c429a4254a1a21149b150600c003ad9
Taker: 070907328fe692c34eb70fc7c312db5801b0160a9d4416e0c78bba19b623d10e
Deposit: bbfa2db54b99ae4c6870e9beee27190afb9c12707b95bc256fe39f04964a5b2a

Bisq version: 1.7.2
BTC address for reimbursement: bc1qz5w4ug5h29ln2jahurkhypknjqfm23c4w97xqh

Other notes: Deposit transaction not found in mempool. After support discussion with pazza moved to failed trades. Please reimburse maker and transaction fee.

**Comment by pazza83** [comment]
Hi @corey66 

The fees for this trade have been reimbursed:

https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2
