### ISSUE TITLE
reimbursement of deposit for trade kotvik11

### ISSUE THREAD

**Issue by lukaskotvan** [bisq-network/support#986]
Hello,

I have made trade (buying 0.01 btc) on 23 FEBRUARY 2021, due to technical issues I got disconnected. When I have logged back in - there was no sign of any trades. I could not continue, dispute or finalize this trade. 

![image]
(https://user-images.githubusercontent.com/82460219/129565645-b641ce44-1920-4f25-9794-686ddca1e7c7.png)
My onion address is znngrloovnqdbdpeemckbsowjmvbmuyptug55yqebasoqmmhm5iuo3yd.onion:9999  

I have approached mwithm viac keybase, he has done some investigation see "mwithm@ and referred me to mediator leo816 see: "asking for support, mediator has case". leo816 closed it IN MY FAVOR .
![image]
https://user-images.githubusercontent.com/82460219/121901399-a7a51f80-cd26-11eb-98a0-022ef764a83b.png

I have raised request no. 928 - that has been closed, however, no refund has been received. 
I HAVE BEEN ASKED TO RAISE ISSUE BY leo816 but it has been rejected as invalid - as it was not in correct repository 
![image](https://user-images.githubusercontent.com/82460219/129566426-d4d6db10-ef73-4b3d-bf70-fc5635165a2d.png)

Deposit of 0.006512: bc1qchndufrvkrvuwrlmgae25gpa5uumfxh8p7sp9t
Maker: bc1qp6q4wlh94gf4pdrp33tef42jpxelw6z6cn6mnz
Taker: c5818b8e674b25d94b1bec860ec96e142310a9ee97f5995cdeee52566ed45dfa
Bisq version: 1.5.4
BTC address for reimbursement: 3FNzn9adLSaBQdM8cozivoigojiUbk8p6t

https://mempool.space/address/bc1qchndufrvkrvuwrlmgae25gpa5uumfxh8p7sp9t

Hopefully it is now all ok.

Thanks

**Comment by leo816** [comment]
what is the situation with this trade? @pazza83 could you look if you have his onion address in one of your tickets?

**Comment by pazza83** [comment]
Hi @leo816 apologies for the late reply.

I have no tickets with the onion znngrloovnqdbdpeemckbsowjmvbmuyptug55yqebasoqmmhm5iuo3yd.onion:9999 in my current or historic mediations:

**Comment by pazza83** [comment]
Looks like the trade went to mediation over a year ago:

https://mempool.space/tx/4b310a57f578cc4ae9746b03fd9d736b9a75cce1287e9f054843239cf753bf25

@lukaskotvan reimbursement requests are only be valid if submitted within 3 months see: https://github.com/bisq-network/proposals/issues/369
