### ISSUE TITLE
Fee reimbursement for trade JIUXU

### ISSUE THREAD

**Issue by space2111** [bisq-network/support#989]
![Trade](https://user-images.githubusercontent.com/89323961/130337675-78c5f90b-2733-4a12-ab97-34b2fdca85a8.png)

Maker: f642cec060a23d63870ea2fbfb79ecb43a93f7343ea201d0edfc9b5d0af38c98
Taker: eb88403f2df525c35f3f40213471728c6e10ee66c97e160caeed8c9e61235ab5
Deposit: 890bae78e3fcb6db97f5111f6e8571906fda038cb957b31c685d4b1acb71f5a6

Delayed payout TX ID: b6e800d42a9bb89d781cad721d3a86c978841e6cc70aa2acc0d4760bb75caa75
Delayed payout TX sent to: 34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC

Bisq version: v1.7.2
BTC address for reimbursement: bc1q3zu5ynssg2slauqvafuwzyfw38dupy4ttg479x

Other notes:

Requesting reimbursement for failed mediation due to the payout having to be adjusted and the adjusted payout transaction failing to be broadcast.

Funds are still locked in deposit TX.
I requested manual payout from mediator, leo, and signed the manual payout TX, but I have not received anything or heard anything since.

Thanks

**Comment by pazza83** [comment]
Hi @space2111 

Thanks for raising this issue and speaking to me about it on Keybase.

As @leo816 is your mediator for this trade I will leave it for him to help coordinate a manual payout to release the btc from the multisig.

Failing this he can help release the funds to burningman and you can claim them through the refund agent.

**Comment by leo816** [comment]
waiting for the signature from both parties to make the manual payout

**Comment by pazza83** [comment]
Hi @space2111 

The funds for this trade are still locked in the multi-sig.

If you update your Bisq to the latest version https://bisq.network/

You should be able to select trade JIUXU and then press 'Ctrl + O'

This should then send the trade to arbitration.

You can then contact the arbitrator and request a refund via Support > Arbitration

**Comment by space2111** [comment]
Thank you @pazza83 

I've updated to Bisq 1.8.2 and tried pressing Ctrl-O on the trade info page from Portfolio -> History as well as the trade info page from Support -> Mediation.
I've also tried this from the chat window with @leo816 but nothing happens.

Please could you advise?

**Comment by pazza83** [comment]
Hi @space2111 

Thanks as funds are still in the deposit transaction they should be able to be released the donation address and you can then claim reimbursement from the arbitrator.

Here is the wiki about the process: https://bisq.wiki/Dumping_delayed_payout_transactions

I am happy to support you with this. Please can you reach out to me on [Keybase](https://keybase.io/pazza) or [Matrix](https://matrix.to/#/@lpazza83:matrix.org)

**Comment by leo816** [comment]
was this solved?

**Comment by pazza83** [comment]
Hi @leo816 no funds are still in the multisig: https://mempool.space/tx/890bae78e3fcb6db97f5111f6e8571906fda038cb957b31c685d4b1acb71f5a6

@space2111 please contact me to resolve this.

**Comment by pazza83** [comment]
@space2111 has contacted me on Matrix. I will assist them with this case.

**Comment by pazza83** [comment]
The funds have now been sent to the donation address: https://mempool.space/tx/b6e800d42a9bb89d781cad721d3a86c978841e6cc70aa2acc0d4760bb75caa75

**Comment by space2111** [comment]
not yet. i will attempt to release the funds to the donation address again
this weekend. contacting arbitrator did not do anything.

**Comment by pazza83** [comment]
Hi @space2111 this reimbursement was completed in May 2022 as on out of Bisq reimburesment:

https://github.com/bisq-network/roles/issues/93#issuecomment-1129005650
