### ISSUE TITLE
Fee reimbursement for trade vFzKzU

### ISSUE THREAD

**Issue by metaltrance** [bisq-network/support#990]
<img width="904" alt="Screenshot 2021-08-27 at 00 53 46" src="https://user-images.githubusercontent.com/88378939/131046582-5da4d831-0168-4082-af70-e2c42c2c56ef.png">

Maker:  14a0e314e2d3ad0c950cb4e85e0ff642c70ca187502144a9bc5e34f2daa47575
Taker: 86030baf76adf382a66ba9ee1420660fe17c925dd8740d765cfc0200459e20a8
Deposit: a2abcb48b0a828bcdcce7010a24022f77c1cfdef97847359eafe720428b9c4cd

Bisq version: v.1.7.2
BTC address for reimbursement:  bc1qj5xg7j9p3v3qpfnujdas6cunyvfm7zqhrxp7rw

Other notes:

Deposit transaction is not showing up on the mempool. Maker fee transaction was also missing.
The trade was stuck at the first step, 'waiting for blockchain confirmation'.
After spv resync was able to move to failed trades and got advise to raise this issue.
Hope this helps to resolve the issue.

Thanks.

**Comment by pazza83** [comment]
Reimbursed tx id: https://mempool.space/tx/1beb4847496943bae86d1032d364af6936cfe217f49dd18d9964bf6aa2f95ae2

**Comment by metaltrance** [comment]
Hi, thanks for this.
There is still 0.0015 BTC locked in the wallet because of failed trade.
What is going to happen with this?

**Comment by pazza83** [comment]
Hi @metaltrance 

please can you reach out to me on Keybase. My username there is: pazza

The locked funds are more likely to be a GUI display error.
