### ISSUE TITLE
Fee reimbursement for trade ZB3G2HR

### ISSUE THREAD

**Issue by GoAdMo** [bisq-network/support#991]
![Screenshot from 2021-08-28 17-24-14](https://user-images.githubusercontent.com/42103906/131231715-aaae9bcc-a756-49a2-b97f-2f20181b86aa.png)

Maker: f3a8c4ccc59efaec92b123ca9d9ad336f1c23778d48103fea972a292f68d63ae
Taker: f2c1c10b02cd1ac46ac8dc3410d7009bb11eb07158be727bcbee0327011dc21c
Deposit: c91834b9958252319d5338d24e579e0d8228b996996987fd03fac2ab99edc743

Bisq version: v.1.7.2
BTC address for reimbursement: bc1q4wd8yxgnw955ntlcxehnhuunwduu73gjwsudp3

Other notes:

The deposit transaction (the 2-of-2 multisig transaction) is missing.
Error message: Deposit transaction is null or has unexpected input count.

**Comment by pazza83** [comment]
Hi @GoAdMo thanks for posting.

I can see you lost fees on your maker transaction: https://mempool.space/tx/f3a8c4ccc59efaec92b123ca9d9ad336f1c23778d48103fea972a292f68d63ae

@leo816 will arrange a refund for yourself.

**Comment by pazza83** [comment]
Hi @leo816 please can you add this to your reimbursement to do list.

**Comment by leo816** [comment]
Fee Reimbursement paid out with #1033
