### ISSUE TITLE
Fee reimbursement for trade ONJXWAVO

### ISSUE THREAD

**Issue by savarela88** [bisq-network/support#993]
![image](https://user-images.githubusercontent.com/87943392/131381297-9ec91894-30e9-4c26-a8d0-859bc1ac3d1f.png)

Maker: 1379d6e18e1645e6881804df34ed747bed9b026e5fc2d609f5e3b9ed876334e7
Taker: 4b8ae57bef840fc7cebbee75a9d51da26661ba79afe77b639c2d4c5d574c7fa6
Deposit: 6732cb0cd18b6fba399a1159dde8f292da145d461d8333f174bf7184fe30c2cb

Bisq version: 1.7.2
BTC address for reimbursement: bc1qc5rrnaz622t6m0dyyrn4uc2d29e05tk2rlaydv

Other notes:

The deposit transaction (the 2-of-2 multisig transaction) is missing.
Error message: Deposit transaction is null or has unexpected input count.

Please, I request a reimbursement based on the above

**Comment by pazza83** [comment]
Hi @savarela88
 
Thanks for creating this issue.

As you were the maker and no maker transaction occurred you have not lost any fees for this trade as no funds will have left your wallet:

https://mempool.space/tx/1379d6e18e1645e6881804df34ed747bed9b026e5fc2d609f5e3b9ed876334e7
