### ISSUE TITLE
Fee reimbursement for trade njgeiah

### ISSUE THREAD

**Issue by blex97** [bisq-network/support#994]
![Bildschirmfoto von 2021-08-31 08-14-58](https://user-images.githubusercontent.com/61120848/131457780-40138e89-ba42-48cb-8f86-139728153c8d.png)

Maker d0d664e2b57c93a1cdd5d32cc0fba04b790ec57c41f00fa152707fbfdce08a90
Taker 0e0eae54a5533a4b0ec41c8baf1470d54429e3b107f04f0d14de33398cb54c49
Deposit 214902972cdc8706850e08d0724e40b631d283b98f7dedb6108edd35e607d325

Bisq version 1.7.3

BTC address for reimbursement: 1aGf7fS6J8v72FdQEDAG76wBL5a119ZGD

Other notes:

The deposit transaction (the 2-of-2 multisig transaction) is missing.
Error message: Deposit transaction is null or has unexpected input count.

Please, I request a reimbursement based on the above

**Comment by leo816** [comment]
Reimbursed with #1006
