### ISSUE TITLE
Fee reimbursement for trade PINAXAJ

### ISSUE THREAD

**Issue by RaRaLuK** [bisq-network/support#995]
![screen](https://user-images.githubusercontent.com/89964105/131805077-335f7493-01c4-4439-bb69-a998ff38b509.jpg)

Maker:  b97893b7af8067d3523b771877ba725fc716b482763ec3a11610667c49c8a70d
Taker: b1b165343e470ea2941b399595dd447356b38ab5693992c1e6d24bd49e9a2323
Deposit: 038b14f27cba5da21612821988c54a11c12e61aa40931b7bb36f826938e7ec85

Bisq version: 1.7.3
BTC address for reimbursement: bc1qqhwwxhjgsnr4zl5989p4xwnneyft8xg9jp02ph

Other notes:
Error msg: Deposit transaction is null or has unexpected input count.

**Comment by leo816** [comment]
Reimbursed with #1006

**Comment by RaRaLuK** [comment]
Hi,I have received the trade fee, but I also need the locked sum of 0.015. Please unlock it. Thank you!
