### ISSUE TITLE
Fee reimbursement for trade mmbtx

### ISSUE THREAD

**Issue by lekanovic** [bisq-network/support#996]
>_The mmbtx-d23defbb-a74d-45fd-af95-adb384754a31-151 part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![Screenshot from 2021-09-03 10-06-37](https://user-images.githubusercontent.com/3911096/131973011-758a2a44-d356-4686-ad79-3c0772cf0bdb.png)

Maker:  c644ab2882bc4be7157e5d1ed7ef110e3f962fe8718feb119b98172e6ffdcd5b
Taker: 84b930c0d071aa3f42587bf4db85991ce6b92cc135037174fbb47d50777da7bd
Deposit: ed55f87c9f5352c7ea03f7ccd0eb960c328d7ab9b65c4a22c5807964b3cd9027

Bisq version: v1.7.3
BTC address for reimbursement: bc1q42du7grcc34yvqya92y4mxrhvfwzrnnmz7m2cm

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

Error message "The deposit transcation (the 2 -of- 2 multusig transaction) is missing

**Comment by lekanovic** [comment]
I have done the resync and it did not help

**Comment by pazza83** [comment]
Hi @lekanovic 

Thanks for posting.

I can see you have lost trade and mining fees for this trade.

@leo816 will make reimbursement to your btc address in the next trading cycle.

**Comment by lekanovic** [comment]
@pazza83 @leo816 when is the next trading cycle?

**Comment by pazza83** [comment]
Hi @leo816 please can you add this to your reimbursement to do list.

**Comment by leo816** [comment]
Fee Reimbursement paid out with #1033
