### ISSUE TITLE
Fee reimbursement for trade bhmgid

### ISSUE THREAD

**Issue by blackanji** [bisq-network/support#997]
![Screen Shot 2021-09-06 at 7 14 44 PM](https://user-images.githubusercontent.com/90225631/132268410-05d10142-ed53-4f4e-9266-762a63311322.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version:
BTC address for reimbursement:

mac os version 1.7.3

Other notes:

>_IAn error occurred at task: CreateTakerFeeTx
Exception message: Insufficient money,  missing 0.0156766 BTC

**Comment by pazza83** [comment]
Hi @blackanji thanks for posting.

As you were the taker for this trade and no taker fee is present no funds will have left your wallet. There is no reimbursement required.

**Comment by pazza83** [comment]
As you have had a couple of trades fail it might be that your wallet is corrupt.

I would recommend doing an SPV resync:  https://bisq.wiki/Resyncing_SPV_file

Also make a backup of your Bisq first: https://bisq.wiki/Backing_up_application_data
