### ISSUE TITLE
Fee reimbursement for trade lybzS

### ISSUE THREAD

**Issue by blackanji** [bisq-network/support#998]
![Screen Shot 2021-09-06 at 7 15 19 PM](https://user-images.githubusercontent.com/90225631/132268862-1854ef92-d271-436a-a9b4-c0d6a7f44110.jpg)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  ..........
Taker: ...........
Deposit: ..........

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: mac os ver 1.7.3
 address for reimbursement: 1BN2ej4hAqmdVdC9GeMWd6YAds7oKW4qQu

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

>An error occurred at task: CreateTakerFeeTx
Exception message: Insufficient money,  missing 0.0053642

**Comment by pazza83** [comment]
Hi @blackanji thanks for posting.

As you were the taker for this trade and no taker fee is present no funds will have left your wallet.  There is no reimbursement required.
